### ISSUE TITLE
Launcher 1.4.1.6 Fresh Install

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#100]
Reporting a new bug to squash.

For windows (and possibly other systems), on a fresh install, config sub directory under .maptool is not properly created causing launcher to fail as it can not create the default launch.properties file.

**Comment by Azhrei** [comment]
Have there been any other reports of this problem recently?  I've been using 1.4.1.7 lately on my Mac and it's working fine, but I will try renaming my .maptool directory and testing some more.

How does the launcher handle failure?  For example, what if the parent of .maptool is read-only so the subdirectory can't be created?  Of what if .amptool already exists but is read-only?  New files wouldn't be allowed but existing files could still be edited...  I guess I have a few things to test. :)

**Comment by Azhrei** [comment]
It looks like the current code doesn't check whether the directory creation succeeded.  Since the launcher will eventually go away (under use from the new Java8 "packager"), this is low-priority and won't be fixed at this time.
