### ISSUE TITLE
DrawableNoise taking up too much memory

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1006]
**Describe the bug**
There has been multiple reports of MapTool using up much more memory since 1.5.7

Reverting commits in batches, I think I've isolated the problem to the `DrawableNoise` feature (commit 2275f6f8323a7205e2cd5f9afd9fd920117bb8c5).

Each `ZoneRenderer` stores up a `DrawableNoise` object, which takes up a lot memory. @Phergus estimated that each noise mask is around 28MB.

**To Reproduce**
1. Load a campaign with multiple maps.
2. Record how much memory it is using.
3. Modify the source code of ZoneRenderer, so that the line

```java
private final DrawableNoise noise = new DrawableNoise();
```

is replaced by

```java
private final DrawableNoise noise = null;
```

4. Run and load the same campaign.
5. Record how much memory it is using. In my case, it went from 250mb to 100mb.

**Expected behavior**
Users shouldn't have to pay hundred of mbs in memory if the feature isn't active.

I suggest that `noise` variable be only constructed once the user activates the noise feature.

**MapTool Info**
- Version: 1.5.7+
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Probably should have the `/tn` on and off commands add/remove the drawable noise from the ZoneRenderer.

**Comment by Phergus** [comment]
Closing.
