### ISSUE TITLE
When you clear the "GM" macro panel, the confirmation popup text is for "Campaign" panel (cosmetic)

### ISSUE THREAD

**Issue by RicoTheBold** [RPTools/maptool#1021]
**Describe the bug**
When you attempt to clear the "GM" macro panel, the confirmation text is wrong.  It says "You are about to clear the Campaign macro panel. Are you sure you want to continue?"

If you select yes, it clears the GM macro panel as expected, so this bug is only in the confirmation popup text itself.

**To Reproduce**
1. Go to the GM macro panel
2. Right-Click on it, and select "Clear Panel"
3. Confirmation pop-up displays erroneous text.
4. Confirmation action still works correctly.

**Expected behavior**
The confirmation popup should ask you to confirm you want to clear the GM panel.

**Screenshots**
First picture is confirmation prompt
![PanelConfirm](https://user-images.githubusercontent.com/42160122/71451116-9b8d6280-272c-11ea-883f-ddae7b954d88.PNG)

Second picture is (correctly) empty "GM" panel after selecting "Yes" on confirmation prompt
![EmptyPanel](https://user-images.githubusercontent.com/42160122/71451120-a647f780-272c-11ea-9cd3-8354d33fe609.PNG)

**MapTool Info**
- Version: 1.5.8
- Install: Upgrade [many previous versions]

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [10, v1909]

**Comment by Phergus** [comment]
Fixed by #1022

**Comment by Phergus** [comment]
Closing.
