### ISSUE TITLE
execFunction chokes on apostrophes

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1024]
**Describe the bug**
The function `execFunction` doesn't work as expected when using the symbols `'` and `"`.

**To Reproduce**
1. Create a token with the "Dragon" name.
2. Run
`[execFunction("setName", json.append("[]", 'A "little" Dragon', 'Dragon'))]`

3. Notice the Dragon token hasn't been renamed. It should have been renamed to `A "little" Dragon`.

**Expected behavior**

Apostrophes should not create issues.

**MapTool Info**
- Version: 1.5.7
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
It would also be nice for the current token to be taken into account when using `execFunction`.

**Comment by Phergus** [comment]
@Merudo  See [forum post](https://forums.rptools.net/viewtopic.php?p=275154&sid=ddb0a17298ff6c284ba7d4590f86cd66#p275154) re function names.

**Comment by Merudo** [comment]
@Phergus I think the intent is for [function names to be case-insensitive](https://github.com/RPTools/maptool/issues/132#issuecomment-367857761).

**Comment by Phergus** [comment]
Guess so.  I think that's silly but it is what it is.

**Comment by Phergus** [comment]
Tested.  Working as described.
