### ISSUE TITLE
Update JIDE Libs to current release.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1029]
Need to move MapTool up to current JIDE libs to be compatible with newer Java releases and get the many bug fixes that have been made to the libs.

Current (12-2-2019) JIDE release is 3.7.8.   The 3.7.6 libs are currently in the JIDE branch of the MapTool repo.

**Comment by Phergus** [comment]
Builds and runs under Windows with the 3.7.6 libs.

**Comment by Phergus** [comment]
Part of this should be to get the libs put in a proper maven repo.  Probably using [GitHub packages](https://help.github.com/en/github/managing-packages-with-github-packages/about-github-packages).

**Comment by Phergus** [comment]
Thanks to @xdy for the heads up on the Maven repo for the JIDE open source libs.

https://mvnrepository.com/artifact/org.bidib.com.jidesoft

**Comment by xdy** [comment]
I was wrong about that though. It's *a* place to get them. Doubt it's *the* place. (Though I doubt that a german railway modelling software standards organisation would upload anything fishy.)

See https://github.com/jidesoft/jide-oss/issues/27 for the gory details on why jidesoft isn't updated on maven. Does not inspire confidence...
```
jidesoft commented on Dec 15, 2018
We couldn't get it working.
```
The *it* being able to update their package in maven. Meaning they've probably lost their Sonatype account. And/or their gpg keys...

**Comment by thelsing** [comment]
We use version 3.7.9 currently.
