### ISSUE TITLE
With MapTool default layout Draw Explorer is open but not checked in Window menu

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1030]
**Describe the bug**
With the default layout for MapTool the Draw Explorer is visible but not checked in the Window menu.  Selecting the Draw Explorer in the Window menu makes it active and checked in the Window Menu but _unchecks_ the Map Explorer.

**To Reproduce**
1. Open MapTool
3. Backup layout.dat file in config dir if you want to keep your layout.
2. Select _Restore layout_ from _Window_ menu.
3. Note Map and Draw Explorer windows are open but only Map Explorer is checked.

**Expected behavior**
Expect Window menu to reflect the currently open/closed windows.

**Screenshots**
![Screenshot 2019-12-27 11 56 40](https://user-images.githubusercontent.com/34379254/71529326-6d7d5f00-28a1-11ea-8cdb-c7be6bf27bfa.png)

**MapTool Info**
- Version: 1.5.8 (but has been this way for a long, long time.
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
The Select and Global macro windows also appear to toggle each other's status in the Menu.

**Comment by Merudo** [comment]
I don't see the problem? In the picture you have Map Explorer showing and the Draw Explorer not showing. The menu reflects that.

**Comment by Phergus** [comment]
I've always assumed the check mark indicated windows that were open, i.e. not closed.  So I think both Map and Draw Explorer should be checked.   Not sure what the point is of having the check indicate that window is the top of a set of tabbed panels.  That's immediately obvious looking at the group where the tab names are visible as is the frame label indicating which one is on top.

If I have a window open, but not docked, it might be hiding behind another un-docked window.  Both will be checked and because of that I know they are both open.

Not having looked at the code I'm guessing though that the current behavior is intentional so probably should just leave it alone.

**Comment by Azhrei** [comment]
It's likely that the JIDE implementation changed over the years.  When Trevor first implemented it, it probably _was_ "opened panels" vs. "visible panels".

**Comment by Phergus** [comment]
That could be.    Changing it at this point may not be worth the effort unless they are others that are bothered by this.

**Comment by Azhrei** [comment]
Well, if someone wants to look for a new method call/API, then great, but yeah, I’m not going to lose any sleep over it.  We can just leave it open as a reminder...

**Comment by melek** [comment]
Just to add a note, tabbed panels that aren't on top are never checked, so the default layout is following the same rules as any custom layouts.

Here is a quick example with all the panels as tabs in one window:
![image](https://user-images.githubusercontent.com/220149/71602406-20052a00-2b0d-11ea-8710-aac13a49c358.png)
