### ISSUE TITLE
MapTools uses a few dependencies with (according to snyk.io) high severity vulnerabilities.

### ISSUE THREAD

**Issue by xdy** [RPTools/maptool#1037]
xstream: https://app.snyk.io/vuln/SNYK-JAVA-COMTHOUGHTWORKSXSTREAM-31394 and more medium severity
beanutils: https://app.snyk.io/vuln/SNYK-JAVA-COMMONSBEANUTILS-30077
bouncy castle:https://app.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-32412
jetty: https://app.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-32383 https://app.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-30090 https://app.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-32385 https://app.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-460763 https://app.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-31117 https://app.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-32151 and more medium serverity
(commons collection was also noted by snyk, and kind of scary, but the PR for that is already in)

I'll try to fix them (or note in the build.gradle if we can't upgrade for whatever reason)
I may do the ones only affected by medium security vulnerabilities too (reflections and pdfbox).

**Comment by xdy** [comment]
As far as I can tell this works, but given how wonky the windows installer is this should be tested on someone else's machine. (And probably on a linux and mac machine as well.)

**Comment by Phergus** [comment]
Tested locally.  Was able to build a Windows installer and install.  Basic functionality working.
