### ISSUE TITLE
Increase minimum Windows version to 6.1 in Inno Setup file

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1039]
The config file `\package\windows\MapTool.iss` still calls out WinXP.  Recommend moving to 6.1 (Windows 7) or better.

And while we're at it update the copyright notice to 2020.

**Comment by xdy** [comment]
PR https://github.com/RPTools/maptool/pull/1043 does this.

**Comment by Phergus** [comment]
We're still debating the version cutoff and timing.   :)

**Comment by xdy** [comment]
Yep, I was just in a caffeine-induced hacking frenzy so ran ahead without looking. :)

**Comment by Phergus** [comment]
Min Version set to 6.1 (Windows 7).  Closing.
