### ISSUE TITLE
Should the webapp feature be removed?

### ISSUE THREAD

**Issue by xdy** [RPTools/maptool#1040]
This issue was created after a discussion on discord, was originally part of #1037, and should probably be done after that one is merged.
The webapp feature hasn't been touched since 2014, isn't being maintained and pulls in jetty as a dependency, which seems unreasonably heavyweight as well as risky. (It also includes ancient versions of bower and jquery. If the feature is kept that should be done some other way.)

I've made a PR that removes it, merge it if it seems like a good idea.

**Comment by xdy** [comment]
Or, rather, *now* I've done the PR, https://github.com/RPTools/maptool/pull/1044

**Comment by Phergus** [comment]
As something like this is only likely way that MapTool will ever support tablets and phones as clients, I'd hate to lose it.   However, as you note, it has languished since its initial exposure and is serious need of updating if it is to be supported versus a hidden/lost experimental feature.

**Comment by xdy** [comment]
Yeah, it'd be better if someone adopted the feature.

**Comment by xdy** [comment]
Closing issue after discussion on discord.
