### ISSUE TITLE
Update all dependencies to the latest version

### ISSUE THREAD

**Issue by xdy** [RPTools/maptool#1045]
Intended to be a sub-issue of #1041 
I'll start working on this.

**Comment by xdy** [comment]
I've now created a PR, https://github.com/RPTools/maptool/pull/1048 that should update most every dependency that's not in another PR (such as xstream).

**Comment by Phergus** [comment]
Awesome.  Working out if we want to pull this into 1.5.9 or put it in 1.5.10.

**Comment by xdy** [comment]
If you decide leave this for 1.5.10, it'd probably be a good idea to at least do https://github.com/RPTools/maptool/pull/1042 in 1.5.9, unless it breaks on mac or linux of course. (But I bet the problem you had earlier with modules was the uberjar one I fixed in the 1048 PR.)

**Comment by Phergus** [comment]
Pulled in for 1.5.9.   Builds and installs locally.  No issues found.
