### ISSUE TITLE
Token VBL doesn't properly rotate with token when Token Layout is off-center.

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#1049]
**Describe the bug**
When a token's Layout is set off-center, generated token VBL rotates in-place instead of rotating properly with the token around the origin square.

**To Reproduce**
1. In a new campaign, add the 'Dragon' top-down token from the Default tokens.
2. Edit the token and in the Config tab Layout area double click the token image to reset it's size, then drag the image to the lower left corner of the layout area.
3. Edit the token and in the VBL tab change the sensitivity to 1 and generate VBL.
4. Close the token editor and with the token selected enter VBL mode.
5. Hold Shift and scroll the mousewheel to rotate the token. Observe the VBL rotating in place, instead of rotating around the origin square.

**Expected behavior**
Token VBL should always appear correctly on the token image.

**Screenshots**
![image](https://user-images.githubusercontent.com/220149/71564646-fd193e00-2a58-11ea-88f0-c05a4fb0140c.png)
![image](https://user-images.githubusercontent.com/220149/71564658-2508a180-2a59-11ea-8048-ae306b791884.png)

**MapTool Info**
- Version: 1.5.8
- Install: Upgrade from 1.5.4-rc2

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
There are some additional small bugs related to this that I'm not submitting issues for immediately, but are worth mentioning:
* When rotating the token, I sometimes could not easily select it again by clicking on its image. I had to drag a box to select it then rotate it with the scroll wheel to get it working. 
* When the token Layout is altered, it would sometimes mis-render the token VBL preview on the token in the VBL tab of the token editor (though it appeared to be correct on the actual map)

**Comment by Phergus** [comment]
I could have sworn there was an issue for this already but couldn't find it.

**Comment by melek** [comment]
There was a similar issue that was closed because it couldn't be duplicated, #220 - might that be it? Though that looks more like the 1 degree bug that was fixed.

Investigating this bug using a perfectly round token (setting it to 'Top down'), the generated VBL still seems to rotate off its center, but only a tiny amount compared to the actual token image. In this screenshot, the token is perfectly centered on the corners of its parent square, but when faced 180 degrees the VBL is sitting offcenter:
![image](https://user-images.githubusercontent.com/220149/71636039-cc174580-2bdf-11ea-92ed-43c953f48360.png)

Rooting around I think the issue is in `Token.getTransformedVBL(Area)`, but I haven't monkeyed around enough to figure anything out. The Selection bug is a mystery to me.

**Comment by Merudo** [comment]
The issue also occurs if the token is rotated by the `setTokenFacing` command.

**Comment by Merudo** [comment]
PR #1397 fixes this bug.

**Comment by Phergus** [comment]
Tested.  VBL rotates correctly now with token image.
