### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by xdy** [RPTools/maptool#1056]
Intended to be a sub-issue of #1041
Initially I'll run https://github.com/nebula-plugins/gradle-lint-plugin/wiki on the project.
Seems I'll also need to make PR:s on the other rptools projects maptool depends on. I won't make issues for those, just reference this issue in those PR:s. (I know I'm in a minority, but, well, I *like* monorepos. I'm lazy. :)

**Comment by xdy** [comment]
Done first round of PR:s on the sub-projects (upgrade gradle to 5.3.1)
https://github.com/RPTools/clientserver/pull/11
https://github.com/RPTools/parser/pull/17
https://github.com/RPTools/maptool-resources/pull/1
https://github.com/RPTools/dicelib/pull/20

I'll unassign myself from this one for now, if anyone feels like grabbing it, go ahead.

**Comment by Merudo** [comment]
I believe the 11 following dependencies are unused:

- Antlr: added before 1.4, used to compile other RPTools project but not this one
- decktool: added before 1.4, appears to be at the prototype stage
- 4 jide dependencies: not needed by the jide elements we use
- jetty-servlet, websocket-client: added before 1.4, not used by webapp
- jetty-continuation: deprecated, added before 1.4, not used by webapp
- ca.odell.renderpack: fetched from Craig's website. Contains class HTMLTableCellRenderer, HTMLRenderer, HTMLListCellRenderer, but these are not used. Added before 1.4.
mockito-core: for mocking features during unit tests, but is not used by any test. Added in 1.5.0.

**Comment by Phergus** [comment]
Builds and runs after changes.
