### ISSUE TITLE
Reset Function/Menu Option for Token/Stamp Images

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#106]
An option added to the Token popup menu to restore default size and orientation to a MapTool token or stamp along with a MTScript function to do the same.

**Comment by JamzTheMan** [comment]
We still looking to add this one? Another quick hit?

**Comment by oliver-szymanski** [comment]
some questions about that (or maybe I'm missing something here):
- Is facing == orientation?
- I think a clear facing facing is already in the menu for token
- is the default size for token just setting it back to medium?
- I don't see any option to change size or facing of a draw stamp

**Comment by Phergus** [comment]
I think this needs some further explanation.  As you say, we already have Clear Facing on the menu and the size can be reset as well via the Size sub-menu.

**Comment by rkathey** [comment]
When you're manipulating stamps you can royally foul it up by flipping, and drag resizing it. What I would like is a way to reset it to its original dropped state and start over. Note, an undo function would help as well but that part of MapTool really needs some refactoring and love (or so I"m told). 

To see the issue, drop an image onto the background layer then click the small box in the corner and drag it around.

**Comment by Phergus** [comment]
So perhaps a Native Size option just under Free Size?  Should it also reset any rotation or leave that to the Clear Facing item?

**Comment by rkathey** [comment]
Yes, that would work perfectly fine for the size reset to use native size.

I'm not sure if the reset flips is obvious with native size but I think it still works. They'd figure it out after one try. The case could be made the resetting flips isn't that big a deal since it's pretty easy to reverse that one.

I would leave reset rotation to clear facing. I don't know that's it's obvious that facing and rotation are the same thing for new users. It's not much of a learning curve.

All that said, the term reset (to me) is obvious for all of those things. <shrug>

**Comment by Phergus** [comment]
Both **Reset Size** and **Native Size** seem obvious as to what they would do to me.  The question would be what is the behavior on the Token layer.  Does it go to Medium  or the Native Size.  For the first option, Reset Size would be the only choice.  For the second option, either would work.

**Comment by rkathey** [comment]
I think on the token layer Native Size makes the most sense. Basically, you're setting it to free size and removing any free-size size modifications.

**Comment by Phergus** [comment]
I'm 100% with that.

**Comment by oliver-szymanski** [comment]
Added a Reset Size popup menu entry. As far as I understand it resets the size as defined. Clear facing and flipping still left to the original menu entries.


Fix in https://github.com/RPTools/maptool/pull/311
