### ISSUE TITLE
Labels, Halos, and Selection boxes incorrectly render when changing facing on top-down tokens with off-center layouts

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#1060]
**Describe the bug**
I mentioned in #1049 that the selection box seems to rotate weirdly with facing on top-down tokens with off-center layouts. Halos thankfully track the selection box rather than the token image.  

**To Reproduce**
1. On a new map add a new token.
2. Edit the token. In the Config tab, change the Shape to 'Top Down'. In the Layout area, drag the token to the top right corner. Save the token.
3. Right click on the token and add a bright halo color such as Yellow. Optionally, select 'Show Token Names' in the 'View' menu.
4. Change the token's facing to observe the error. Notice you cannot click on the token image to select it, only on the box created by the halo.

**Expected behavior**
The selection box and halo should follow the token image.

**Screenshots**
Here is an example:
![image](https://user-images.githubusercontent.com/220149/71636286-a93a6080-2be2-11ea-8246-c1f26c2cf66c.png)
![image](https://user-images.githubusercontent.com/220149/71636304-e272d080-2be2-11ea-9bc9-c5470a6f1742.png)

Here is an example showing the misplacement of the label and the VBL at the same time:
![image](https://user-images.githubusercontent.com/220149/71636013-6034dd00-2bdf-11ea-851f-5ebfa400164b.png)

**MapTool Info**
- Version: 1.5.8
- Install: Upgraded from previous version

**Desktop (please complete the following information):**
 - Windows 10

**Comment by Phergus** [comment]
Almost certainly related to #997, #1049 and I think another, older one.

**Comment by melek** [comment]
I've done a little more bug testing to see if I could isolate the behavior and compare it to how the Token VBL misaligns.

I've found that only moving the image in the 'Layout' area Y position (moving it upwards/downwards), rather than to a corner or to the side, lines up the VBL and the Halo.
![image](https://user-images.githubusercontent.com/220149/71752657-bbabd880-2e34-11ea-8b52-3ec7f6b79f27.png)

Also, I didn't notice before, but the red-white selection marker follows the image perfectly, even though the 'box' you must click to select the token follows the halo.

**Comment by Phergus** [comment]
I'm putting this in the 1.5.10 queue and flagging it as `up-for-grabs`.  Hopefully someone can get this done before release.  :)

**Comment by melek** [comment]
Great :) I'm trying to grok it, but the ZoneRenderer code is pretty complicated. 

I changed the token size to 'Native', and the halo/label position didn't improve - though the Token VBL DID work that way for some reason (another clue for #1049  maybe)

![image](https://user-images.githubusercontent.com/220149/71754034-67efbe00-2e39-11ea-81f2-a8fa77f33912.png)

**Comment by JamzTheMan** [comment]
IIRC there is an "anchor" value for the token used for this offset and is probably not used everywhere.

The whole offset/rotation/scale is a PITA in MT, it's scattered and replicated across several places like the renderer, token, functions. Years ago when I did the VBL stuff I seem to recall having to account for this stuff all over the place...

**Comment by Azhrei** [comment]
Yeah, IMO it should be possible to ask the Token for it’s rendered image, or to provide a GC and have it render to the GC.  I’m sure it started out simple and was never refactored. Sigh.

**Comment by melek** [comment]
I found a stray 'x' instead of a 'y' when ZoneRenderer calculates `tokenBounds` facing rotation for top-down tokens. That seems to have lined the halo/label/selectable area up with the token image correctly. 

I tried to refactor a bit at first but it was hard; maybe if I can figure out the issues with VBL and States I'll be familiar enough with the relevant pieces to try to move the rotation logic into a method someplace.

**Comment by melek** [comment]
Should this be closed now, as I found the bug for this particular issue? I didn't see it in the 1.5.11 notes so I'm not sure where this and the related pull request are at in the process.

**Comment by Phergus** [comment]
Hmm.  This got missed somehow.  I'll get it appropriately set.

**Comment by Phergus** [comment]
So testing it I see that the VBL still gets offset if rotated.  The halo and selection outline now follow the token image which is now offset from the actual cell it occupies if snap-to-grid is turned on.

**Comment by Phergus** [comment]
This appears to address the issue with label, halos and selection boxes.  Other issues address remaining issues.  Closing.
