### ISSUE TITLE
Add Vision setting to New Map Preferences and New Map dialog.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1062]
**Is your feature request related to a problem? Please describe.**
Being able to set a Vision default (Off, Day, Night) for new maps would be convenient.

**Describe the solution you'd like**
Add a drop-down selector to both the Preference settings for New Map and also the New Map dialog.

**Describe alternatives you've considered**
Currently setting vision for a map is a separate menu action after adding a map.

**Additional context**
[Forum post](https://forums.rptools.net/viewtopic.php?f=6&t=28509)

**Comment by emmebi** [comment]
I am starting working on this.

**Comment by Phergus** [comment]
Tested.  Working as requested.

**Comment by Phergus** [comment]
Wiki documentation added.
