### ISSUE TITLE
getNativeHeight/Width Script Function

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#107]
A function to return the native height and width of a token or stamp.

**Comment by JamzTheMan** [comment]
We still want/need this? Quick hit for new devs...

**Comment by oliver-szymanski** [comment]
on it

**Comment by oliver-szymanski** [comment]
Done, fix in https://github.com/RPTools/maptool/pull/309

**Comment by Phergus** [comment]
Will need to be documented on the wiki.

Was this done as one function or two?   If one, is it returning a JSON array `[200,200]` or an object `{"width":200, "height":200}`?

**Comment by oliver-szymanski** [comment]
Its 2 function to be consistent with the existing
getTokenHeight/getTokenWidth function. Of course I will add it to the wiki
once I know which version it will be in.
