### ISSUE TITLE
Add "mapName" parameter and localization to MacroFunctions

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1072]
**Is your feature request related to a problem? Please describe.**
Meta macro functions such as `getMacroProps` and `getMacroIndexes` do not have a "mapName" argument.

Additionally, the error messages of the meta macro functions are not localized.

**Describe the solution you'd like**
Add a mapName macro argument to the functions, and add localization to the error messages.

**Comment by aliasmask** [comment]
I would really like to see this done for at least getMacroProps and getMacroIndexes just so the macro command text can be read from other maps. But having all the meta macro functions with map option would allow something like my RPEdit work from different maps.

**Comment by Merudo** [comment]
PR #1076 added the mapname parameters to the MacroFunctions.

Documentation has been updated:

- [createMacro](https://lmwcs.com/rptools/wiki/createMacro)
- [getMacroCommand](https://lmwcs.com/rptools/wiki/getMacroCommand)
- [getMacroIndexes](https://lmwcs.com/rptools/wiki/getMacroIndexes)
- [getMacroProps](https://lmwcs.com/rptools/wiki/getMacroProps)
- [getMacros](https://lmwcs.com/rptools/wiki/getMacros)
- [removeMacro](https://lmwcs.com/rptools/wiki/removeMacro)
- [setMacroCommand](https://lmwcs.com/rptools/wiki/setMacroCommand)
- [setMacroProps](https://lmwcs.com/rptools/wiki/setMacroProps)

**Comment by Phergus** [comment]
Functions tested using ID/Map Name.
