### ISSUE TITLE
createMacro: applyToSelected=1 doesn't work

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1075]
**Describe the bug**
The option `applyToSelected=1` is not applied when using `createMacro`.

**To Reproduce**
1. Create a token named `Dragon`.
2. Type
`[createMacro("test", "", "applyToSelected=1;", ";", "Dragon")]`
3. Type
`[createMacro(json.set("{}", "applyToSelected", 1, "label", "test2", "command", ""), "Dragon")]`
4. Check both macros. Both have Apply to Selected Tokens unchecked.

**Expected behavior**
Apply to Selected Tokens is checked.

**MapTool Info**
- Version: 1.5.9
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1077 fixes this.

**Comment by Phergus** [comment]
Working as expected now.  Closing.
