### ISSUE TITLE
States and Bars do not follow off-center top-down tokens as their facing is rotated.

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#1092]
**Describe the bug**
States and Bars do not follow the bounding box of a top-down image with an off-center layout as it's facing is rotated.

This seems related to other top-down token issues with the token layout setting and token facing in  #1060 and #1049.

**To Reproduce**
1. On a new map, create a new token.
2. In `Token Editor > Config Tab > Shape`, select *Top Down*.
3. In `Token Editor > Config Tab > Layout`, drag the token to a corner of the layout area .
3. In `Token Editor > States Tab`, check *Dead* and unhide the Health bar, setting it to 100% value.
4. Rotate the facing on the token.
5. Observe the bar and state do not move with either the Halo, or the Token image. 
6. Optionally, add Token VBL and observe that they don't follow Token VBL rotation either.

**Expected behavior**
States and bars should remain centered on the center of the token image as it has its facing rotated.

**Screenshots**
The error with token labels visible and a halo applied:
![image](https://user-images.githubusercontent.com/220149/72006852-56c1fb00-3205-11ea-957d-e0d7e22a3e34.png)

When set to 'Circle', the same token renders perfectly:
![image](https://user-images.githubusercontent.com/220149/72006163-e5ce1380-3203-11ea-8bcc-3a118d328311.png)

This image shows how Halos/Labels/Selection area, Token image, Token VBL, and States and Bars misalign in off-center, top-down tokens when their facing is rotated:
![image](https://user-images.githubusercontent.com/220149/72005844-59235580-3203-11ea-82f1-afb774bbca03.png)

**MapTool Info**
- Version: 1.5.10
- Install: Upgrade throughout 1.5.x

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Bars and States do scale correctly on tokens that are scaled in the Token Layout settings.
If this is fixed, it might be logical that it be fixed along with #1060 and #1049.

**Comment by Merudo** [comment]
PR #1393 fixes this issue.

**Comment by Phergus** [comment]
Tested new code.   States, Halos and Bars correctly moving with rotating token.  VBL still offset.

![Screenshot 2020-03-20 07 46 15](https://user-images.githubusercontent.com/34379254/77169331-ee05c300-6a7e-11ea-9bc4-970d96273a0d.png)

**Comment by Phergus** [comment]
As #1049 covers the VBL issue.  Considering this one complete.
