### ISSUE TITLE
Option to not allow players to access and use their Library window to drop things onto the map.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#1104]
**Is your feature request related to a problem? Please describe.**
Players can drag and drop their own tokens onto the map from their own Library window during a game.  As a GM, I would like to have an option to disallow players access to their Library window -- or at least not be able to drag and drop their own tokens onto the map.

I've had some players thoughtlessly drop random tokens onto the map, and that damages the gaming experience for everyone else.

**Describe the solution you'd like**
When starting the server, one of the options presented is a checkbox to allow the GM to **disable** player ability to -- or as an option we set in Preferences:

1. access their own Library window

2. drag and drop tokens onto the map

**Describe alternatives you've considered**
I don't know of an alternative other than to ask players not to do it when they do -- and they so far comply (but it's still slightly awkward for everybody).  It would be better to just disable access.

**Additional context**
![1](https://user-images.githubusercontent.com/50708405/72209047-13b79000-3470-11ea-8953-c4d15d4634dc.PNG)
![2](https://user-images.githubusercontent.com/50708405/72209048-16b28080-3470-11ea-8630-2640f7eba575.PNG)
![3](https://user-images.githubusercontent.com/50708405/72209051-1a460780-3470-11ea-86f7-bfcbf5e08d49.PNG)
![4](https://user-images.githubusercontent.com/50708405/72209057-1d40f800-3470-11ea-8783-2c5f341d98b5.png)

**Comment by JamzTheMan** [comment]
Drag and drop disable would be enough. Probably not the hardest, maybe someone will pick it up.  But a better idea would be to add a GM toolbar to enable/disable a few things on the fly globally without the need to restart the server.

This sort of thing comes up every so often, usually with drawing tools. Usually the response is "get better players". And it's one thing to say that for a static weekly game, but I know some people like to play pickup type games like PFS so I can see a use for this.

**Comment by adventuremagic123** [comment]
Sounds fine to me.  Thanks, JamzTheMan.

**Comment by aliasmask** [comment]
How about a warning popup and ban option per player? Only affects player role, not gm. Or maybe a permission popup. 

"Player 'Bob' is attempting to drop token 'My Token 2' - || Allow || Disallow ||"
When disallowed 
"Server had turned off token dropping for this session."

**Comment by Azhrei** [comment]
The pop up would work if it had a “Don’t ask again” checkbox so the GM could turn off dropping per client with just one pop up.  Otherwise, an annoying player could spam the GM with these things, leading to a DoS.

**Comment by JamzTheMan** [comment]
You could need a way to turn it back on.

Character levels up, get a companion, or some other valid reason the GM may want to turn it back on (at least temporarily) to let the PC(s) drop a new token on. 

Until then, the command it "Please do not drop tokens on a map unless asked" and if that doesn't work use the Connections window. :)

**Comment by Azhrei** [comment]
Yeah, turning it back on would be a right-click on the Connections panel.

Right-click on the word "Players" and you change all of them at once, or right-click on a specific player and change just that one.

And until we have a "Ban" option, booting a player doesn't really work.  (They'll just log in again.  And we can't currently change the password without restarting the server.)

**Comment by adventuremagic123** [comment]
I've updated this issue.  It doesn't matter a lot to me where you put this option -- either when starting the server or somewhere where I can specify that behavior as a default that maybe can be enabled or disabled during the game.  Sometimes it might be beneficial to allow players to drop something onto the map from their library -- like for an object to represent a spell effect.

**Comment by Phergus** [comment]
Implied by Jamz's comment is that disabling the library window won't stop drag-n-drop into MapTool from other sources.  So a solution needs to stop that as well.

Blocking the display of the Resource Library may also create an annoyance for the players whose carefully arranged UI windows may be disrupted if the Resource Library disappears.

**Comment by thelsing** [comment]
Just disabling the drop functionality should be enough then.

**Comment by Phergus** [comment]
@michaelperino  Add a comment to this so it can be assigned.  Thanks.

**Comment by michaelperino** [comment]
Done

**Comment by michaelperino** [comment]
Above commit successfully implements it, not sure if that's the best way to do it in swing though. If someone wants to take a look, let me know. I will try to do fuller testing this weekend to ensure everything still works as expected.

**Comment by Phergus** [comment]
I can see that you are disabling the asset panel based on server policy but don't see any code there that adds options to the Start Server dialog.   Disabling the asset panel will stop players from dragging assets from the panel but won't stop players from dropping images/tokens onto the map itself.  See discussions above about drag-n-drop.

**Comment by michaelperino** [comment]
All that code was implemented in the last commit before my cancelled pull request (due to discussion available there). The only thing that should've been changed with this one is putting a panel that can be swapped to for a "GM has disabled your asset panel" label

**Comment by Phergus** [comment]
Okay.  Since you closed that PR I wasn't sure if those changes were still valid or not.

**Comment by Phergus** [comment]
Tested.  Server option disables Player client access to Resource Library.
