### ISSUE TITLE
Strings returned by UDFs have extra symbols `"` appended around them

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1117]
**Describe the bug**
Strings returned by UDFs have extra symbols `"` and `"` surrounding them.

**To Reproduce**
1. Load the attached program in MapTool 1.5.11-alpha-7
2. Click on the `showError` macro on the token
3. Notice the ouput is `"A String"`
4. If you do the same in MapTool 1.5.10, the output is `A String` instead.

**Expected behavior**
No `"` added around the String.

**MapTool Info**
- Version: 1.5.11-alpha-7, develop (1/14/2020)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

[UDF_Bug.cmpgn.zip](https://github.com/RPTools/maptool/files/4063506/UDF_Bug.cmpgn.zip)

**Additional context**
@cwisniew clarified the issue, the bug is with all strings returned by UDFs and doesn't have anything to do with UDF input parameters.

**Comment by cwisniew** [comment]
Just ran a test the "" are not being appended to the input parameters. Instead they are being appended to the value as part of the process formatting it for chat.

Example, using the attached campaign
[h: val = test("A String")] [r: val] --> A String
[r: val = test("A String")] - [r: val] --> "A String" - A String

If you change the test macro button to [r: length(arg(0)] --> 8 (which matches the length of the String without quotes)

If you change the test macro button to [r: ".." + arg(0) + ".."] --> "..A String.."

**Comment by Merudo** [comment]
Thanks for the details @cwisniew, I've updated the bug report to reflect the information you uncovered.

**Comment by Merudo** [comment]
Tested. Now that #1119 has been merged, UDFs no longer return strings with extra `"` around them.
