### ISSUE TITLE
Strings containing numbers are trimmed when put in json

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1139]
**Describe the bug**
Strings containing a number surrounded by white spaces have their white spaces removed once put into a json object or array.

**To Reproduce**
1. Type `[r: json.append("[]", " 0 ")]`
2. The output on develop or 1.5.11 alpha 7: `[0]`
3. The output for the same command on 1.5.10: `[" 0 "]`

**Expected behavior**
The behavior is the same as 1.5.10: the leading and trailing white spaces are not removed on 1.5.11.

**MapTool Info**
- Version: 1.5.11 Alpha 7, develop (1/17/2020)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Tested and working as expected.
