### ISSUE TITLE
Add getLibMap(libTokenName) and/or getMap(tokenName) function

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#1142]
Now that we have all these neat functions that can utilize the map location, now all we need is a way to know which map a token is on. lib:tokens are unique so that function should only have one result, but if possible having a `getMap(tokenName): array of maps` would be optimal.

Currently, if I want to know which map my library token is on I set a property on the lib token. You can't use default values for library token properties, and setting properties during onCampaignLoad isn't supported (duplicate token thing, but can be worked around), so this should to be done manually in the token props. The other method to find a token on a map is to loop through all the maps and use findToken. 

So, getLibMap() and getMap() would be very helpful and more convenient to have. If getMap() is too complicated or time consuming then I'll settle for just getLibMap().

**Comment by Merudo** [comment]
The function `getLibMap` seems useful to me. If the lib token doesn't exist, I suppose it should return a blank string?

**Comment by Phergus** [comment]
Seems like it should be just one function.  Perhaps by extending the `findToken()` function.

**Comment by Merudo** [comment]
`findToken` returns the token ID of the token though, not the map where it is from.

**Comment by aliasmask** [comment]
findToken() would be complimentary for sure. Yes, empty string for no results.

**Comment by Phergus** [comment]
So essentially you want something like this:
```
[h: tok = "Hero"]
[h: mapNames = getAllMapNames("json")]
[h: mapArray = "[]"]
[foreach(map, mapNames, ""),code: {
	[h: id = findToken(tok, map)]
	[h, if(id != ""): mapArray = json.append(mapArray,map)]
}]
[r: mapArray]
```
```
["Grasslands","Arid"]
```
I'm not against having a single function that does the same thing in one call.  Just looking for current functions that could be extended to do the same thing.

**Comment by aliasmask** [comment]
Basically. Now with the findToken(id,map) option, you don't have to actually change maps to use findToken like you did before. I just thought it was strange there was no simple way to know which map my lib token was on even when running a macro from that token.

An example use case is this:
```
[H: macroName = arg(0)]

[H: this = getMacroLocation()]
[H: map = getLibProperty("map",this)]

[H: output = getMacroCommand(number(getMacroIndexes(macroName,",",this,map)),this,map)]
```
I have to set a property on the token to know which map it's on. This function searches for macros only on that lib token, but I could be on a different map when running the macro.

**Comment by Phergus** [comment]
That's the problem with no actual design before willy nilly throwing in macro functions.  Why doesn't `findToken()` find tokens?  It just gets the ID of token if you now the name and until recently only on the current map.

Being able to locate the map(s) a token is on by name or ID seems like an obvious function to have even if I've never needed it.

**Comment by aliasmask** [comment]
I usually use findToken() to validate a token is on the current map. The is mostly for custom frames holding persistent data. For example, I have a custom chat that allows you to "impersonate" a token even if that token is on another map. I save the relevant token info and update it if the token is on the current map. There may be the same token on multiple maps with the same name, but the id may be (is always?) different.

**Comment by Merudo** [comment]
Yeah `findToken` is unfortunately named, and doesn't actually do what the name implies it does.

It reminds me of the "Find Traps" spell in D&D 5e, which doesn't actually find or locate traps, it just tells you whether there is a trap present within 120 feet at the time of the casting.

**Comment by Merudo** [comment]
Instead of `getMap`, wouldn't it make more sense to call it `getTokenMap` to make it more clear that we try to find map(s) associated with a token?

I also suppose we could had the usual `delim` parameter, so that the list of map can be returned as a list or as a json.

**Comment by aliasmask** [comment]
getTokenMap() fits better with the existing naming convention.

**Comment by Phergus** [comment]
Tentatively put on 1.5.11 in case someone wants to jump on this quickly.

**Comment by Merudo** [comment]
PR #1168 adds the feature.

**Comment by Merudo** [comment]
Documentation: https://lmwcs.com/rptools/wiki/getTokenMap

**Comment by Phergus** [comment]
Tested.  Working as documented.
