### ISSUE TITLE
execFunction fails for functions requiring trusted macros when defer = 1

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1149]
**Describe the bug**
`execFunction` no longer works for functions requiring a trusted macro when the `defer` parameter is set to 1.

**To Reproduce**
1. Type `[h: execFunction("broadcast", "['test']", 1)]`
2. Notice how `test` is not broadcasted.
3. The same function works in 1.5.8 and when `defer` is set to 0.

**Expected behavior**
`execFunction` works with `defer` set to 1 for all functions.

**MapTool Info**
- Version: 1.5.10, develop (1/18/2020)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1150 resolves this issue.

**Comment by Phergus** [comment]
Tested.  Working as expected.
