### ISSUE TITLE
Extra (empty) entry created when using: strPropFromVars 

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#116]
Apparently an old bug had reared its head again. When using strPropFromVars a redundant ; is added at the end, which (for example) results in an empty key value pair when you transform that to a json object. Other issues as well as the stray simply adds an extra empty value. The fix is to remove the ; when using strPropFromVars

test code: 
`[h:var1=12][h:var2=13][r:strPropFromVars("var1,var2","UNSUFFIXED")]`

and for a deities sake, make the 'UNSUFFIXED' part optional please!!. (Where it defaults to 'UNSUFFIXED'). The other way round it's optional as well, so it makes little sense why its not for this function.

**Comment by Phergus** [comment]
Confirmed still present in 1.5.0.

**Comment by Phergus** [comment]
@Merudo - Comment on this so that I can assign you.

**Comment by Merudo** [comment]
The bug should be fixed now.

**Comment by Phergus** [comment]
Tested and working as described.
