### ISSUE TITLE
macrolink argument encoding/decoding failing for ; in 1.5.11 alpha builds

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1173]
**Describe the bug**
For macro links the ; is encoded as &#59 and not decoded

**Expected behavior**
Macro link should decode to ;
**MapTool Info**
1.5.11 alpha

**Comment by Phergus** [comment]
Basic testing against macroLink, execLink and encode/decode.  Will need more testing against actual frameworks.
