### ISSUE TITLE
getTokenNames / getTokens don't work with mapName option

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1175]
**Describe the bug**
`getTokenNames` / `getTokens` don't work with `mapName` option anymore, because extra `"`s are added around the value of the `mapName` parameter.

**To Reproduce**
1. Create a project with the `Grasslands` map.
2. Type the following in MapTool 1.5.11 beta 1 or develop (1/22/2020)
```[h: cond = json.set("{}", "mapName", "Grasslands")][r: getTokenNames(",",cond)]```
3. Notice the error message:
 ```Can not find map ""Grasslands"" in function "getTokenNames".```

**Expected behavior**
The map is properly found.

**MapTool Info**
- Version: 1.5.11 beta 1, develop (1/22/2020)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1176 fixes this.

**Comment by Phergus** [comment]
Tested.  Working as expected now.
