### ISSUE TITLE
json.difference no longer works with strings

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1177]
**Describe the bug**
`json.difference` no longer works with strings. It used to interpret strings as arrays of size 1.

**To Reproduce**
1. Type in 1.5.11 beta 1 / develop (1/22/2020):
```[json.difference( "test",  "test")]```
2.  Notice the error:
```Argument number 1 to function "json.difference" must be a JSON Array or Object.```

3. In 1.5.10, it worked and returned the null array `[]`.

**Expected behavior**
The function returns the same output as in 1.5.10.

**MapTool Info**
- Version: 1.5.11 beta 1, develop (1/22/2020)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Tested and now works as before.
