### ISSUE TITLE
AI distance calculations incorrect when using terrain modifiers

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#1178]
**Describe the bug**
In some paths taken when including diagonals across terrain modifiers, costs could be incorrect for some cells due to rounding errors.

**To Reproduce**
Use a Multiplier 4 terrain modifier and move token diagonal several times and note the costs.

**Expected behavior**
Correct math!

**Screenshots**
See discord channel....

**MapTool Info**
- Version: 1.5.10 (probably back to 1.5.0)
- Install: Any

**Desktop (please complete the following information):**
 - OS: Any

**Additional context**
A sample campaign I use to run tokens through...
[AStartWalker.zip](https://github.com/RPTools/maptool/files/4100856/AStartWalker.zip)

**Comment by Phergus** [comment]
**Changes**
 * **New Map Option** for AI rounding of cell costs, NONE, CELL_UNIT, INTEGER. More can easily be added if needed.

**Debugging Options**
 * ZoneRenderer now show blocked movements if class log debug is on (previously required manual boolean change while developing)
 * ZoneRenderer now shows raw cost without cell units while debugging when showing token Path

**Comment by Phergus** [comment]
New rounding modes and terrain modifier types tested with low to medium complexity maps.

**Note for Documentation:**  Terrain Modifiers on tokens/objects only apply when the token/object has a _set size_.  Free Size will be treated as a single cell with TM at the center.

**Comment by Phergus** [comment]
[Introduction to Tokens](http://www.lmwcs.com/rptools/wiki/Introduction_to_Tokens#Config) page updated with screenshot and some verbage.

**Comment by Phergus** [comment]
Add a basic [Map Properties](http://www.lmwcs.com/rptools/wiki/Map_Properties) page to wiki.

**Comment by Phergus** [comment]
Added new info to the [AI Pathfinding](www.lmwcs.com/rptools/wiki/AI_Pathfinding) wiki page.
