### ISSUE TITLE
Add unit tests for json macro functions

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1189]
**Is your feature request related to a problem? Please describe.**
We need more unit tests to prevent regressions.

**Describe the solution you'd like**
Maptool macro functions for json elements (json.set, json.path.read, json.difference, etc.) have relatively few dependencies - most of them take one or more string(s) and return a string. Unit tests (at the macro function level) can be implemented easily.

For example, we can use
```
JSONMacroFunctions.getInstance().childEvaluate(parser, functionName, argument)
```
 to test if the macro function returns the appropriate string. If it doesn't, the test is failed, and we know there is a problem with the function.

**Comment by Merudo** [comment]
PR #1188 implements tests for `json.path.read`.

**Comment by Phergus** [comment]
PR #1192 adds tests for `json.difference`, `json.isEmpty`, `json.set`, `json.get`, `json.append`, `json.toList`, `json.type`

**Comment by Phergus** [comment]
@Merudo  Is this done for now?

**Comment by Phergus** [comment]
No adverse effects found.  Closing.
