### ISSUE TITLE
Move the jar repository for RPTools jars to rptools.net

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#12]

**Comment by rkathey** [comment]
Is this still needed?

**Comment by Azhrei** [comment]
I don't know.  What does this mean?  Is this because there's a Maven repo on Craig's personal machine?  If so, then yes, we should get that to RPTools.net sooner as opposed to later...

**Comment by JamzTheMan** [comment]
@cwisniew can we close this issue?

**Comment by Phergus** [comment]
Four years is enough.  Closing.
