### ISSUE TITLE
input list: new option to select a different delimiter

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1210]
**Is your feature request related to a problem?**

When using the `input` dialog, there is an option to use a list to create a drop-down list of choices.

Unfortunately, the list needs to be comma delimited. This is inconvenient when working with items with themselves have commas in them.

**Describe the solution you'd like**
An option to specify a different delimiter for the list. Something such as

```DELIMITER=X```

where `X` is the delimiter to use. Additionally, the option to use a json array instead of a list would be welcome.

**Additional context**

One issue is that each option is separated by a space. Hence, I'm not sure how a delimiter including a space could be specified.

**Comment by Azhrei** [comment]
Using JSON would seem to be a solution to embedded commas and spaces, but I can see some ease-of-use considerations for a single character as delimiter.

**Comment by Merudo** [comment]
PR #1211 implements this.

**Comment by Phergus** [comment]
- Add option DELIMITER for drop-down lists in input.
- Default DELIMITER value is a comma, as before
- DELIMITER can't have spaces
- DELIMITER can be set to json, in which case a json array should be used instead of a list

**Comment by Phergus** [comment]
Tested.  Working as described.

**Comment by Phergus** [comment]
Documentation and examples added to [wiki page](http://www.lmwcs.com/rptools/wiki/input).

**Comment by Phergus** [comment]
Change may have broken something else.  Following code works in 1.5.12 but not in current develop.
```
[h: foo = 'doSwitchInterMap|Change to other map, do not change to other map, do not change AND store coords|<html><span title="<html><b>Change to other map</b>: When using inter map teleport, switch to the map after teleportation<br><b>do not change to other map</b>: do NOT switch to destination map after teleportation<br><b>do not change AND store coords</b>: when using the do NOT switch map option, the system needs to<br>check the destination pad for the correct coords before sending the token there and then return to<br>the current map. This causes maptool to reload the current map. To prevent this you can use this third<br>option, which will store the coords of both pads on eachother during the <i>initialize pads</i> process.<br><b>BUT</b> that means that you CANNOT move the interPads without running <i>initialize maps</i> again.</html>">Automatically swap to map for interpads</span></html>|RADIO|SELECT=2']
[r: result = input(foo)]
```

**Comment by Merudo** [comment]
I'll work on a fix.

**Comment by Merudo** [comment]
PR #1233 fix this issue.

**Comment by Phergus** [comment]
Re-Tested.  Radio button and Drop-down Lists now working.
