### ISSUE TITLE
IOUtils.closeQuietly is deprecated and should be replaced with try-with-resource

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#1215]
**Is your feature request related to a problem? Please describe.**
IOUtils.closeQuietly has been deprecated and is marked as such in the code. The alternative is to use try-with-resources statement, which will remove some repetitive code.

The reference documentation is here: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Describe the solution you'd like**
Remove all the try/finally blocks of code including IOUtils.closeQuietly with try-with-resource statement

**Describe alternatives you've considered**
I am not aware of alternative ways to accomplish this.

**Additional context**
I am looking at blocks of code like this:
```
  public static Object objFromResource(String res) throws IOException {
    XStream xs = getConfiguredXStream();
    InputStream is = null;
    try {
      is = FileUtil.class.getClassLoader().getResourceAsStream(res);
      return xs.fromXML(new InputStreamReader(is, "UTF-8"));
    } finally {
      IOUtils.closeQuietly(is);
    }
  }
```

which can now be rewritten as:
```
  public static Object objFromResource(String res) throws IOException {
    XStream xs = getConfiguredXStream();
   try (
        InputStream is =  FileUtil.class.getClassLoader().getResourceAsStream(res);
   ) {
      return xs.fromXML(new InputStreamReader(is, "UTF-8"));
    }
  }
```

The same pattern could be applied also to other places, like for example PersistenceUtils.saveCampaignProperties

**Comment by emmebi** [comment]
On the same topic, the PackedFile could declare to implement the Autoclosable interface, and be used in the same way.

**Comment by emmebi** [comment]
Please assign this to me as I am going to do some clean-up work on this during the week.

**Comment by emmebi** [comment]
There are 45 ```IOUtils.closeQuietly``` in the code.

**Comment by Phergus** [comment]
@emmebi  I noticed that saved token files aren't getting their preview images in the Resource Library with the current dev code.

**Comment by emmebi** [comment]
@Phergus Can you detail this a little more? I will look into it in the week-end.

**Comment by Phergus** [comment]
Talking about this:
![Screenshot 2020-02-21 06 18 12](https://user-images.githubusercontent.com/34379254/75038097-e4367300-5472-11ea-9ba0-9c9f729bf610.png)

**Comment by emmebi** [comment]
I wonder if this could be related to https://github.com/RPTools/maptool/pull/1266 instead

**Comment by emmebi** [comment]
( Drawing Foreground/Background Texture Select Using Resource Library Directory )

**Comment by Phergus** [comment]
Maybe.  It showed up very recently and I haven't had a chance to look at it more.  The image is there.  If I drop one of them on a map, the image shows up.  Could also be #1268

**Comment by emmebi** [comment]
Ok, apparently this was introduced with this patch. I checked out the develop branch, and if you go to the "Fix input PROPS type not working", images are shown. If you move three commit forwards, this doesn't work :( 

So, looking into this to understand why (I so much want to add tests ;) )

**Comment by emmebi** [comment]
Found! The problem was indeed introduced in the getFileAsInputStream, which uses again a try with resources; but in this case the return value should be the InputStream, and the InputStream should not be closed at the exit of the function.

Posting a PR for this soon.

**Comment by Phergus** [comment]
Fix tested and working.  No other issues found.
