### ISSUE TITLE
Update Javadoc generation to generate HTML5 javadoc

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1219]
Update the gradle build to generate HTML5 Javadoc.

This will also require some tweaks to existing Javadoc comments in the code to remove tags that are invalid in HTML

Also add a @note tag option to format notes automatically.

**Comment by Phergus** [comment]
Running `gradlew javadoc` builds javadocs and the HTML5 flag is set in the build.gradle file.
