### ISSUE TITLE
Javadoc warnings cleanup

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1223]
**Describe the bug**
Generating Javadoc causes so many warnings about bad/missing tags.

**To Reproduce**
gradlew javadoc

**Expected behavior**
Warnings should be eliminated.
sure the Javadoc is not in the greatest state at the moment, but it's easier to get people to add Javadoc to new functionality if generating it doesn't cause so many issues to be reported.

**Comment by Merudo** [comment]
If the following is added to gradle:

```
options.addStringOption('Xmaxwarns', '2000')
```

then the current number of javadoc warning is reported to be 399.

**Comment by cwisniew** [comment]
> 
> then the current number of javadoc warning is reported to be 399.
That means I am just over 1/4 of the way through fixing the warnings :(

**Comment by balp** [comment]
I started to look into this issue to understand how the tooling of maptool works today. Ending up removing all warnings with not to big effort.

**Comment by Merudo** [comment]
Awesome! Thank you so much for this! I'm only getting 6 warnings now:

```
javadoc: warning - invalid usage of tag &threadID
javadoc: warning - invalid usage of tag &start
javadoc: warning - invalid usage of tag &threadID
javadoc: warning - invalid usage of tag &start
javadoc: warning - invalid usage of tag &threadID
javadoc: warning - invalid usage of tag &start
```

**Comment by balp** [comment]
> Awesome! Thank you so much for this! I'm only getting 6 warnings now:
> 
> ```
> javadoc: warning - invalid usage of tag &threadID
> javadoc: warning - invalid usage of tag &start
> ```

I or rather IntelliJ thinks that ScrollableFlowPanel, where this issue is can be deleted, the links to http://forum.java.sun.com/thread.jspa?forumID=57&threadID=701797&start=2 are broken as well. I guess the forum has moved, and or is closed.

**Comment by Phergus** [comment]
Tested.  JavaDocs generate without errors/warnings.
