### ISSUE TITLE
"Exception during look and feel setup" while booting MapTool (develop)

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1225]
**Describe the bug**
An error message pops up while booting up MapTool:

`Exception during look and feel setup. java.lang.NullPointerException`

In the console:

```
ERROR net.rptools.maptool.client.MapTool - msg.error.lafSetup
java.lang.NullPointerException: null
        at net.rptools.maptool.client.MapTool.main(MapTool.java:1736) [main/:?]
        at net.rptools.maptool.client.LaunchInstructions.main(LaunchInstructions.java:49) [main/:?]
```
**To Reproduce**
1. Get latest develop (2/2/2020)
2. Boot up MapTool
3. See the message

**Expected behavior**
No error message

**MapTool Info**
- Version: 1.6.0 develop (2/2/2020)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Yeah.  I've got a fix for it was just testing a few things.
