### ISSUE TITLE
Choosing a non-writable directory fails silently while downloading a new version

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#1231]
**Describe the bug**
When MapTool tries to download a new version, it fails with no error message if it can't write on chosen directory.

**To Reproduce**
1. Download a version which is not the latest (e.g. 1.5.10)
2. Run it
3. Accept to download a new version
4. When asked where to download choose c:\ (or similar, non writable by a normal user directory)

**Expected behavior**
1. At least, you should receive an error message stating the nature of the error (e.g. you can't write in that directory)
2. Ideally, the tool should ask you to choose a new directory

**MapTool Info**
- Version: 1.5.10
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
@emmebi  Was there an issue with having it prompt for a new directory or where you just going to pass on that for now?

**Comment by Phergus** [comment]
Currently user is warned if chosen directory is not writable by user.

**Comment by emmebi** [comment]
@Phergus I didn't think of that; let me see.

**Comment by Phergus** [comment]
Excellent.  I'll wait on closing this till you report back.

**Comment by emmebi** [comment]
I actually have spotted a problem with previous version; I am fixing this, while asking for a new file location; I probably will push an update this evening (UTC time).

**Comment by Phergus** [comment]
Very good.  I'll keep an eye out for it.
