### ISSUE TITLE
Lights using GRID may display incorrect sized radius

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#1243]
**Describe the bug**
Lights or type GRID may display wrong size if using maps of different grid sizes.

**To Reproduce**
1. Create a light with radius of 20 and of type GRID then apply to token on a map with grid size 50
2. Create new map with grid size of 100 and place same light on a token
3. Lighted area will be half the size needed

**Expected behavior**
Light should be the same radius regardless of grid size.

**MapTool Info**
- Version: 1.5.x
- Install: Any

**Desktop (please complete the following information):**
 - OS: Any
 - Version Any

**Additional context**
For performance, GRID radius is built using combined awt Areas and are cached the first time one is created for a given radius but is cached using the current grid size.

**Comment by Phergus** [comment]
Tested.  Lights created using the GRID shape occupy the same number of grid cells no matter the pixels per grid setting.
