### ISSUE TITLE
Modify PackedFile to implement AutoCloseable

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1268]
**Describe the bug**
As @emmebi pointed out in #1215 PackedFile should implement AutoCloseable so that it can be used with try with resources. 

**Additional context**
Using try with resources minimises try/catch/finally blocks and generally leads to easier to read/maintain code.

**Comment by emmebi** [comment]
I will work on this in the context of https://github.com/RPTools/maptool/issues/1215

**Comment by Phergus** [comment]
No visible change for end users.

Tested Loading/Saving/Reloading
- Campaign files
- Tokens
- Campaign Properties
- Macros
- Macro Sets
- Maps
- Tables
