### ISSUE TITLE
Exporting a campaign with too short a name throws exception

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#1269]
**Describe the bug**
Exporting a campaign with a short name causes an error

**To Reproduce**
1. Launch MapTool
1. Click on File -> Export -> Campaign As...
1. Enter c1 as the campaign name
1. Click ok
1. The error message is shown

**Expected behavior**
The campaign to be saved as c1.cmpgn

**Screenshots**
Attached screenshot of the error 

**MapTool Info**
- Version: 1.5.12 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

![export_dialog_error](https://user-images.githubusercontent.com/1532349/74102775-ae25f480-4b3e-11ea-95a2-b8bcdcbd74b9.png)

**Comment by Phergus** [comment]
Is this specific to short names or the timing after starting MapTool?

**Comment by emmebi** [comment]
Yes: I thought it had to do with the timing (and the fact that the campaign was not saved yet) but it turned out that you could reproduce the same also with a saved campaign.

**Comment by Phergus** [comment]
Note that this is for the File -> Export action only.

**Comment by Merudo** [comment]
If I remember right, it is related to the file extension.

**Comment by emmebi** [comment]
Correct, the problem is in the AppState.getCampaignName:
```
  public static String getCampaignName() {
    if (AppState.campaignFile == null) {
      return "Default";
    } else {
      String s = AppState.campaignFile.getName();
      // remove the file extension of the campaign file name
      return s.substring(0, s.length() - AppConstants.CAMPAIGN_FILE_EXTENSION.length());
    }
  }
```

As you can see, this assumes that the name has always an extension.  Not posting a fix for this now because I will be busy with other stuff during the week; if this is still active during the week-end, I will create a fix for it :)

**Comment by Phergus** [comment]
Tested.  Exporting campaign files with as few as 1 character file names works as expected.
