### ISSUE TITLE
Can't delete a map image

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1270]
**Is your feature request related to a problem? Please describe.**
Once a map image has been set (Map -> Edit Map -> Map), it is impossible to remove the image.

The image can be replaced by another image, but not removed.

**Describe the solution you'd like**
There should be an extra button to remove the image.

Alternatively, pressing the cancel button should remove the image.

**Comment by amccarthy1** [comment]
How would something like this look:

![image](https://user-images.githubusercontent.com/5650580/75419096-ecb30180-58e9-11ea-8d7a-e4a1e9af6210.png)

The "Clear" button just resets the image. If this is acceptable / desired functionality I can open a PR.

**Comment by Phergus** [comment]
I think that I would have put it on the Map Properties.  Probably like can be see on the edit token dialog for Portraits and Handouts.  Something like this:

![RemoveMapConcept](https://user-images.githubusercontent.com/34379254/75450150-82bb4c00-592b-11ea-85ce-37484d560fab.png)

There is a little `cancel_sm.png` image under resources used on the token config panel.

Or the current Map button could be changed to Add Map with another button under it that said Remove Map.

Or the current Map button could change text depending on if the zone already has a map.  It would say Remove Map if there is one and Add Map (or just Map) if there isn't.

**Comment by JamzTheMan** [comment]
I like that design Phergus. Assume we would only sure the X when there is a map image added.

**Comment by Phergus** [comment]
Yeah.  Just like the token config panel.  Simple and pretty obvious what it does I think.

**Comment by Phergus** [comment]
Tested

- [ ] Map menu -> New Map -> Add Map
- [ ] Map menu -> New Map -> Add Map -> Remove Map
- [ ] Map menu -> Edit Map -> Add Map
- [ ] Map menu -> Edit Map -> Remove existing map
- [ ] Map menu -> Edit Map -> Replace existing map
- [ ] Resource Library -> New Map ->  Remove
- [ ] Resource Library -> New Map ->  Remove -> Add different
 
No issues found.
