### ISSUE TITLE
input() PROPS option no longer works.

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#1278]
**Describe the bug**
I'm getting an error in alpha 6 that I don't get in 1.5.12. Apparently the PROPS option no longer works. Gives null pointer exception error.

**To Reproduce**
[input("test|one=1;two=2;|Test|props")]

**Expected behavior**
Should give me fields "one" and "two" with their values.

**MapTool Info**
- Version: 1.6.0-alpha-6

**Other**
I thought alpha 6 and 1.5.12 was the same build, but with html5 stuff. I do recall mention a change to input() to include json options. Maybe that change was implemented in alpha 6 and has a bug in it.

**Comment by Phergus** [comment]
Not the same build at all.

**Comment by Phergus** [comment]
@Merudo  Appears to be a casualty of the input() changes.

**Comment by aliasmask** [comment]
BTW, having a json option for "props" where it uses the key value for the label and value for the data would be awesome. Then I could have multiple word labels.

**Comment by Merudo** [comment]
@aliasmask it might be doable. What do you suggest the option be called?

**Comment by aliasmask** [comment]
If figured it just keep the PROPS option and just note if the format is a JSON object rather than a string prop then it just use that.

I would hate to try and write the raw json part out would likely always use strformat to put in the json. But maybe it's easier to specify it as an option like type=json. So, given the above: 
```
[H: a = json.set("{}","one",1"two",2)]
[H: input(strformat("test|%{a}|Test|PROPS|type=json"))]
```

**Comment by aliasmask** [comment]
I think if it could determine the type between the |'s, type=json would actually specify the return type. So, you could have a as a string prop and test would return a json object. Going the other way doesn't work well with the limitations of string props, ie a is a json and test is a string prop.

**Comment by Merudo** [comment]
So there would be two parameteers, one for the value and one for the return type? Am I getting it right?

**Comment by Merudo** [comment]
PR #1280 fixes the bug with PROPS.

**Comment by Phergus** [comment]
New Option for PROPS type:  WIDTH .  Same as for TEXT with a default of 14.

**Comment by Phergus** [comment]
Tested.  PROPS input type working as expected.  New WIDTH option working.

**Comment by Merudo** [comment]
> BTW, having a json option for "props" where it uses the key value for the label and value for the data would be awesome. Then I could have multiple word labels.

PR #1283 adds the feature.

**Comment by aliasmask** [comment]
Does "test" become a json object or remain a string prop when a json is used for key/value pairs? I just tested the json functions for converting and they would work fine if not converted to json with an invalid string prop key like "two words=1;"

**Comment by Phergus** [comment]
```
[H: a = json.set("{}","Little Jon",1,"Friar Tuck",2)]
[H: input(strformat("test|%{a}|Test|PROPS"))]
[r: test]<br>
[r: getstrprop(test, "Little Jon")]<br>
[r: json.fromStrProp(test)]
```
returns
```
Little Jon=4 ;  Friar Tuck=5 ; 
4 
{"Little Jon":4,"Friar Tuck":5}
```

**Comment by Merudo** [comment]
PR #1286 adds the second feature.

Example:
```
[H: a = json.set("{}","Little Jon",1,"Friar Tuck",2)]
[H: input(strformat("test|%{a}|Test|PROPS|TYPE=JSON"))]
[r: test]
```

returns `{"Little Jon":1,"Friar Tuck":2}`.

**Comment by aliasmask** [comment]
Yeah, I noticed the string prop was more forgiving. Not sure when that happened. Something like "Little Jon=1" would only display "Little" and "1" for value. But now it seems fine. Still happy about the type=json option. I never use it, but I wonder how using setvars=unsuffixed would work with an "invalid" name for a local property assignment.

**Comment by Phergus** [comment]
New options tested.  Wiki page updated.  Closing.
