### ISSUE TITLE
The Edit Token Dialog doesn't resize Properties grid properly. 

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#1288]
**Describe the bug**
When resizing the Edit Token Dialog, the property grid doesn't follow all the way. At some point the grid stops resizing vertically. 

**To Reproduce**
1. Select a Token
2. Right-click and Select Edit
3. Go to Properties tab
4. Resize Dialog until it is very large. 
5. Observer PropertyGrid not resizing completely. 

**Expected behavior**
I expect the property grid to fill the tab at all sizes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2953375/74612109-a2b86780-5102-11ea-88ce-4010fa0d1a2c.png)

**MapTool Info**
- Version: 1.5.12
- Install: Upgrade [1.5.xx]

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
==== MapTool Information ====
MapTool Version: 1.5.12
MapTool Home...: C:\Users\Thomas\.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 444 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\Users\Thomas\AppData\Local\MapTool\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
PATH...........: C:\Users\Thomas\AppData\Local\MapTool\app;C:\Users\Thomas\AppData\Local\MapTool
Number of Procs: 4

**Comment by emmebi** [comment]
Assign it to me, will work on this during the week.

**Comment by Phergus** [comment]
Tested.  Properties grid now fills the available area.
![Screenshot 2020-02-25 06 40 01](https://user-images.githubusercontent.com/34379254/75252350-bebea780-5799-11ea-9d67-30298b33acd4.png)
