### ISSUE TITLE
Condition options setStates/unsetStates return wrong data in getTokens/getTokenNames

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1292]
**Describe the bug**
Passing a string with a single state name instead of an array does not produce an error but instead returns incorrect information.  Passing a string did work in 1.5.10.

Both _setStates_ and _unsetStates_ conditions for `getTokens()/getTokenNames()` are documented to take a JSON array of the states to be checked for.

**To Reproduce**
1. Drop multiple tokens on a map.
2. Enable the _Dead_ state on some tokens

With this code, and one or more tokens with the Dead state set, MT 1.5.12/13 returns an empty string.
```
[h: conditions = json.set("{}", "setStates", "Dead")]
[r: names = getTokenNames(",", conditions)]
```
With this code and one or more tokens with the Dead state **not set**, MT 1.5.12/13 returns all of the tokens.
```
[h: conditions = json.set("{}", "unsetStates", "Dead")]
[r: names = getTokenNames(",", conditions)]
```

**Expected behavior**
In version 1.5.10, the same code returns the correct list of tokens.

**MapTool Info**
- Version: 1.5.12
- Install: Any

**Desktop:**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1295 fixes this.

**Comment by Merudo** [comment]
Also there is a similar bug with `propertyType`, which I also fixed.

**Comment by Phergus** [comment]
Tested conditions `setStates`, `unsetStates`, `propertyType`, `light`, and `owned`.  Working as expected.

**Comment by Phergus** [comment]
Wiki pages for getTokens()/getTokenNames() updated.
