### ISSUE TITLE
NPE on Hero Lab tokens if XML data is missing

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#1296]
**Describe the bug**
This shouldn't normally happen but user reported running Hero Lab using Wine on Linux and any portfolio created doe not save the XML data for an unknown reason.

**To Reproduce**
1. Extract the Grognard.por from the attached hero-lab-test.zip
2. Attempt to import Grognard
3. See error

[hero-lab-test.zip](https://github.com/RPTools/maptool/files/4222747/hero-lab-test.zip)

**Expected behavior**
MapTool should handle NPE gracefully and note that the XML file is missing.

**MapTool Info**
- Version: 1.5.+
- Install: Any

**Desktop (please complete the following information):**
 - OS: Linux via Wine
 - Version Unknown

**Comment by Phergus** [comment]
Tested.  POR files missing the xml statblock load correctly now.
