### ISSUE TITLE
Function getName()

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#132]
The MTscript function `getName()` produced this error:

`Function "setName" requires at least 1 parameters; 0 were provided.`

The message is wrong because it says "setName".  Not a big deal, just a typo to fix the next time the code is being edited... :)

**Comment by JamzTheMan** [comment]
Either this was fixed or possibly "pilot" error? Code looks fine to me...

`private Object getName(Parser parser, List<Object> args) throws ParserException {
		Token token;

		if (args.size() == 1) {
			if (!MapTool.getParser().isMacroTrusted()) {
				throw new ParserException(I18N.getText("macro.function.general.noPermOther", "getName"));
			}
			token = FindTokenFunctions.findToken(args.get(0).toString(), null);
			if (token == null) {
				throw new ParserException(I18N.getText("macro.function.general.unknownToken", "getName", args.get(0).toString()));
			}
		} else if (args.size() == 0) {
			MapToolVariableResolver res = (MapToolVariableResolver) parser.getVariableResolver();
			token = res.getTokenInContext();
			if (token == null) {
				throw new ParserException(I18N.getText("macro.function.general.noImpersonated", "getName"));
			}
		} else {
			throw new ParserException(I18N.getText("macro.function.general.tooManyParam", "getName", 1, args.size()));
		}
		return token.getName();
	}`

**Comment by Azhrei** [comment]
It's likely in the properties file; there the word "setName" is used when it should be "getName" (most likely).

**Comment by JamzTheMan** [comment]
Mmm, that could be the case. Just happened to notice this so checked...

**Comment by Jaggeroth** [comment]
I think the issue here is case sensitivity. 

The Parser is not case sensitive. So if your macro calls "getname" in all lowercase, the parser recognises that as being covered by the TokenNameFunction class and sends it there.

However the TokenNameFunction class makes case sensitive comparisons, and only "getName" is treated as that function. Whereas "getname" will be treated the same as "setName".

All functions should match using "equalsIgnoreCase" rather than "equals"

**Comment by Azhrei** [comment]
I don't have a lot of motivation to fix these kinds of things unless I'm already in there and it's just an auxiliary change. 🙄  But I'll keep this in mind while doing the cleanup I have pending.  (I'll run through each of the outstanding issues and see about picking off the low hanging fruit.)

**Comment by Jaggeroth** [comment]
I do have the motivation :)

I would be quite happy to run through the function classes, make them case insensitive, centralise common code to the abstract class and maybe add in alternative names.

I'd be happy to take that one, if we agree a new naming standard.

**Comment by Azhrei** [comment]
As long as it doesn't break existing scripts (I can see how it might), then I'm fine with it.  Maybe check with some of the scriptmeisters to see if case-sensitivity would cause them a problem if it were to change...?

**Comment by Phergus** [comment]
This has been fixed by changes for 1.5.4.

Closing.

**Comment by Merudo** [comment]
The message is still wrong.

**Comment by Phergus** [comment]
It was correct in 1.5.5 though the issue of case sensitivity was still there.
