### ISSUE TITLE
Minimal support for alphabetical sort in Artpacks

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#1320]
**Is your feature request related to a problem? Please describe.**
The Artpacks are not ordered alphabetically; this makes searching among them very difficult.

**Describe the solution you'd like**
I would like to have a simple alphabetical sort of Artpacks.

**Describe alternatives you've considered**
We could wait for https://github.com/RPTools/maptool/issues/185 to be implemented, but the scope is much wider.

The idea is to first implement this one and leave the rest of the feature for a further refinement.

**Comment by emmebi** [comment]
The fix is trivial, but I would like to put some unit tests around the functionality. 

A large majority of the code is not easily accessible from outside of the AddResourceDialog itself. I am thinking about pulling out the code, for example creating a class for the SwingWorker in the downloadLibraryList method and the other dependencies (the LibraryRow, maybe the Model). Any objection on this?

**Comment by Azhrei** [comment]
None from me.  Modularity and testability is always good. 👍

**Comment by Phergus** [comment]
Tested.  Help menu option links to [wiki frameworks page](http://www.lmwcs.com/rptools/wiki/Frameworks).
![HelpMenu](https://user-images.githubusercontent.com/34379254/75510645-e8015280-59a8-11ea-95e1-67c374c12bbd.png)
