### ISSUE TITLE
Add a Download Framework menu entry

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#1323]
**Is your feature request related to a problem? Please describe.**
The frameworks are distributed among the entries in the forums. 

**Describe the solution you'd like**
I would like a menu entry with a list of known frameworks which can be download. The framework could be in a standardized format (e.g. a ZIP file with a readme). I don't expect the framework to be automatically installed into the current campaign, for the moment (as this would require that we provide a much more detailed structure for the frameworks themselves).

**Describe alternatives you've considered**
We could keep a web page with the list of the frameworks, or keep relying on the forums.

**Comment by Phergus** [comment]
We do have this wiki page:  http://www.lmwcs.com/rptools/wiki/Frameworks

**Comment by emmebi** [comment]
This seems about right (silly me not to find it). Would it be a good idea to add a menu entry for that (much like the Networking Setup) ?

**Comment by Phergus** [comment]
That would be a good "right now" solution I think.

Having a menu that links actual frameworks to download would incur a maintenance burden on all subsequent builds unless those are stored in a repository somewhere.  The downside to that is that they become "official" with the implication that the devs have vetted and will maintain them.

**Comment by emmebi** [comment]
Ok, if you agree on the menu entry pointing to the wiki page, assign it to me. I think for the more general solution (something similar to Artpacks, maybe being able to auto-install them) can be left to another issue, as it will require quite some design.

**Comment by Phergus** [comment]
Agreed.  (On both topics.)

**Comment by Azhrei** [comment]
@emmebi Pointing to the wiki or a forum post?  Both are fine, but the wiki is planning to move soon/eventually/ever so maybe a locked forum post is more flexible...?

If you go with forum post, the same image can be used as for the NFAQ entry to indicate that both go to the forum...

**Comment by emmebi** [comment]
@Azhrei Either are fine for me: my thought was that once an user has maptool, should be able to reach the required resources easily. Is there a forum post we can use for that?

**Comment by Azhrei** [comment]
There’s not a single, comprehensive one at the current time.  You can create one and then link to it (referencing the other threads?) or just point to the wiki.

If you go with a forum post, we can configure it to appear prominently in the forum and lock it so it doesn’t become a discussion thread.

**Comment by JamzTheMan** [comment]
We had also talked about creating a GitHub repo for Frameworks. You would have a single source for downloads & versions (just attaching raw .cmpgn files) but could also attach other things needed like lib tokens or tables, images, etc. 

One folder per "framework".  But would require some buy-in I think from the framework coders to update/submit changes to GH.

just an idea...

FWIW, you could then use the GitHub API to get a raw list of frameworks and make it dynamic.

**Comment by emmebi** [comment]
@Azhrei As I am quite slow when it comes to writing, I am going to link to the wiki, and then putting together the forum post.

@JamzTheMan The selling point for the framework coders would be that the framework is that as long as they pack following some defined format, we would lift all the setup process for them.  But again, all these things require some design.

**Comment by JamzTheMan** [comment]
Agreed. I think anything for temporary is ok. We want to take a more serious look after we go to campaign directories and have some better options.

**Comment by Phergus** [comment]
Tested.  Help menu option links to [wiki frameworks page](http://www.lmwcs.com/rptools/wiki/Frameworks).
![HelpMenu](https://user-images.githubusercontent.com/34379254/75510645-e8015280-59a8-11ea-95e1-67c374c12bbd.png)
