### ISSUE TITLE
Add Tests for ImageUtils

### ISSUE THREAD

**Issue by amccarthy1** [RPTools/maptool#1325]
**Is your feature request related to a problem? Please describe.**
I noticed that some of the code in ImageUtils is not covered by tests and would be interested in writing some to get started.

**Describe the solution you'd like**
I would like for the methods within ImageUtils to have enough coverage to prevent some regressions.

**Describe alternatives you've considered**
I also considered refactoring/optimizing some parts of these utils, but given that there are no tests, I thought adding tests would be more valuable first.

**Additional context**
I'm new to this project! I'm mostly looking for ways to get started that will help me understand the codebase.

**Comment by amccarthy1** [comment]
I have started working on this already with #1324

**Comment by Phergus** [comment]
No adverse effects seen.  Closing.
