### ISSUE TITLE
No response of program

### ISSUE THREAD

**Issue by bassieman** [RPTools/maptool#1334]
When the application "MapTool.exe" is run, nothing happens.

The program files are in my onedrive folder, and work when run from another PC.
This is untill I adjust the Max memory preference to any value other than "blank".

Running the jar file in ./app results in two messages:

> Error: A JNI error has occured, please check your installation and try again.

> A java exception has occurred

I have tried:
Updating Java
    * was updated, but no change in behavior
Uninstalling and reinstalling 1.5.13 but opting to keep data
    * not starting
Uninstalling all of and Reinstalling 1.5.13
    * resulted in the same situation of working, untill closed after changing max memory to 1024M
Installing 1.6.0 alpha7 also
    * not starting

**Comment by Azhrei** [comment]
I'll let our Windows folks look at this one, but I'm sure they're going to ask...  Which version of Windows?  What directory is `MapTool.exe` installed into (it's known that pathnames containing certain characters will fail on Windows)?

**Comment by Phergus** [comment]
You've set the memory to an invalid size.
Go to `%appdata%\net.rptools.maptool.client\packager\` on the computer having the issue and delete the jvmuserargs.cfg file.

If you need to set more memory, make sure you follow the tooltip of the memory setting field.  Use `4G` for 4 gigabytes or `4096M` for the same.  Adjust to suit.

The jar won't run if you installed the wrong version of Java.  MT 1.5+ comes with its own JVM that it uses.

**Comment by bassieman** [comment]
Thank you phergus!
The memory setting was set at xxxxMB instead of xxxxM.
This fixed it!

**Comment by Phergus** [comment]
Glad you got it going!
