### ISSUE TITLE
Add Pick-Once Functionality to Tables

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1337]
**Is your feature request related to a problem? Please describe.**
Using the current Table system for card decks requires extensive management via macros.  Flagging Tables as pick-once would help simplify this.

**Describe the solution you'd like**
- Add a checkbox to flag a table as Pick Once.  This would allow a table to function as a deck of cards, pile of dominoes or a table of unique random encounters.
  - Each item in the table can only be picked once until the table was reset via button or macro.
  - Table should indicate when viewed if an entry has already been picked.

**Describe alternatives you've considered**
Can be done with macros.

**Additional context**
Meant as an interim solution until much more complete card deck support is available.  See #1335

**Comment by Phergus** [comment]
The `pickOnceTables` branch has a first pass at adding Pick Once support to tables.  Currently must use macros to configure/setup.

New Macro Functions:
- getTablePickOnce("tablename") to check if table is pick once
- setTablePickOnce("tablename", 0|1) to set/unset a table as pick once
- resetTablePicks("tablename") to reset all entries to unpicked
- getTablePicksLeft("tablename") to get the number of available picks left

Other table functions _should_ be working normally.

A campaign file with some tables and macros and no useful information about what they do.

[TableTesting.cmpgn.zip](https://github.com/RPTools/maptool/files/4290715/TableTesting.cmpgn.zip)

More to come.

**Comment by Phergus** [comment]
Basic Usage for current implementation:
- Create Table normally.
- Use `setTablePickOnce(name,1)]` to flag as Pick Once
  - To see if a table is Pick Once, use `getTablePickOnce(name)`.
- Use Table panel and double-click to draw from table or use `table/tableImage()` macros for same.
- A table with no picks left will return NO_PICKS_LEFT.
  - Use `resetTablePicks(name)` to restore the picked choices or _shuffle the deck_.  This can be done at any time.

**Comment by Azhrei** [comment]
I was thinking about this feature being used for card games (duh) and wondered how you’d use it if you were playing the kids game, War.  Two players and each gets a full deck, then they each draw one card from the top of their stack and the higher card wins.  (Called a “trick”.)  When a player runs out of cards, they collect all of the tricks they’ve won, shuffle them, and use the result as their new stack.

How would PickOnce tables be used for this?

You’d need two tables with the same contents, and a list to keep track of cards won as a result of tricks.  But then what?  All shuffling has to be done with the lists and the tables wouldn’t be used again.

So maybe a better approach is a set of functions that copy table data into a list instead?  Then the list is shuffled and a single card at a time is drawn (using functions we already have).

But there isn’t a convenient UI for lists like tables have.  And War is only one game.  What other games might need more support than just “pick once”?

And I leave it there.  I couldn’t think of other games where a single MT table wouldn’t be good enough, except table games like blackjack that frequently use multiple decks.  Are there any others?

**Comment by Phergus** [comment]
I believe there are some RPGs that use some type of deck per player system but couldn't say for sure.  For that we would need the ability to associate a table with a player or character and persist information about what draws the character/player has or has discarded.

For the War example, you can already duplicate an existing table so that's there.  The cards from each trick could be put into a new deck/table per player with macros.  When the first deck runs out, they switch to the next one.  Might be nice to have alternate image sets so that one could visually see which cards were won from the other player in a trick.  Would be simple enough to automate with macros I think.

Most of that is out of the scope of this issue however which has a lesser goal of allowing tables to be used like a deck of card or for the unique random encounter tables sometimes used in modules. 

Managing hands, tracking multiple decks, ownership, etc. fall under #1335.

**Comment by Azhrei** [comment]
Okay, sounds like you've considered all this. 👍

**Comment by Phergus** [comment]
Wiki pages added for new macro functions.

**Comment by Phergus** [comment]
New Tables page (thanks Melek!) with Pick Once section:
http://www.lmwcs.com/rptools/wiki/Introduction_to_Tables#Pick_Once_Tables

**Comment by Phergus** [comment]
Current functionality documented on wiki.

**Comment by Phergus** [comment]
Closing.  Any further improvements/changes will be handled in new ticket.
