### ISSUE TITLE
Expand Asset class to support things other than Images

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1346]
**The Asset class should be able to support multiple types of assets.**
At the moment the Asset type is being used to store other unknown binary types for the Hero Lab support, but this should be expanded so that it can store things like text (and be aware its text/sound/etc).

**Comment by JamzTheMan** [comment]
FWIW this should probably include Asset Library for better integrations of file filter types. Or another issue?

It's only related in the sense that there are a lot of assumptions in the code that Assets should be an image type but currently it knows about .por and .PDF files and probably will/should know about other binaries like audio files as well.

**Comment by cwisniew** [comment]
> FWIW this should probably include Asset Library for better integrations of file filter types. Or another issue?
> 
Yeah already considered it, its part of #1348 and #1349

**Comment by bubblobill** [comment]
Using this would be able to have snd: tokens in the same way we have img: tokens?

**Comment by Phergus** [comment]
Yes.  That's one of the goals.

**Comment by Phergus** [comment]
Foundational work completed.
