### ISSUE TITLE
Method for storing HTML / CSS/ JavaScript / Audio / etc in campaign

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1348]
**Create a Method for storing HTML / CSS/ JavaScript in campaign.**
The campaign file needs to be able to store these text types to make it easier to create HTML forms/character sheets etc for the new HTML5 frame. 

This should be extended to Audio and all sorts of supportable assets.

This depends on the work done for #1346

**Describe alternatives you've considered**
This could all be done in token properties or tables for the text types but its a messy messy kludge.

**Comment by Phergus** [comment]
@cwisniew is this considered complete or is there more to be done?

**Comment by cwisniew** [comment]
> @cwisniew is this considered complete or is there more to be done?

Probably can be considered complete. Any additional changes can get a new issue
