### ISSUE TITLE
Way to add / remove  / browse Assets for a campaign

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1349]
**Is your feature request related to a problem? Please describe.**
Issue #1348 requires a away for users to add assets and browse what assets are in a campaign to be useful

**Comment by Azhrei** [comment]
This may also be needed for the token split implementation (so that a new token can be tied to an existing data object).  That obviously won't be an "asset" using the current terminology, but if the solution for this issue is generic enough, perhaps the Picker can be used for both?

**Comment by Phergus** [comment]
Closing. Future work will be under new issues.
