### ISSUE TITLE
Code Maintenance: Replace UTF-8 by StandardCharsets.UTF_8

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1352]
**Is your feature request related to a problem? Please describe.**
There are quite a few places using a "UTF-8" string for encoding/decoding.

These should be replaced by the constant `StandardCharsets.UTF_8`. This leads to cleaner code, and in some cases allows us to remove a bogus `try/catch` for an `UnsupportedEncodingException` that cannot happen.

**Comment by Merudo** [comment]
PR #1354 implements this change.

**Comment by Phergus** [comment]
No adverse effects seen.  Closing.
