### ISSUE TITLE
Map Coordinates appear over top of Token notes

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1359]
**Describe the bug**
Map coordinates appear over the top of the token notes popup making the notes hard to read.
![file](https://user-images.githubusercontent.com/34379254/75991337-93336f80-5eb3-11ea-820e-4a2cd7290db2.png)

**To Reproduce**
1. Enable Show Coordinates in View menu
2. Click on an Object layer token to bring up the notes (it must have notes)
3. See that notes are partially obscured by coordinates

**Expected behavior**
Notes pop up should be over the coordinates or possibly should shift to the right if coordinates are shown.

**MapTool Info**
- Version: Any
- Install: Any

**Additional context**
Forum post:  https://forums.rptools.net/viewtopic.php?p=275596#p275596

**Comment by daltonhahn** [comment]
Just reviewed this issue in the latest version of the develop branch (October 24th, 2020).  This is no longer an issue. Screenshot attached to demonstrate behavior.

<img width="1227" alt="Screen Shot 2020-10-24 at 1 00 36 PM" src="https://user-images.githubusercontent.com/12523605/97088795-ed2aa600-15f8-11eb-8387-a9e011142a9e.png">

**Comment by Phergus** [comment]
@daltonhahn thanks for the heads up!

**Comment by Phergus** [comment]
Fixed by other changes in 1.8.0.
