### ISSUE TITLE
MegaGrid 

### ISSUE THREAD

**Issue by mudpyr8** [RPTools/maptool#1367]
Add an additional overlay grid that is not linked to the current grid/snap-to-grid functions.

MegaGrid should visually toggle separate from the base grid. 

Grid size at a minimum should be a multiple of base grid size, or could be explicit pixel size. 

Grid color should support transparency to be as unobtrusive as possible.

**Comment by Azhrei** [comment]
Please use the Feature Request template in the future.  We have it for people to use it. 🙂

Your feature request doesn't describe why you want it or how it would be used.  It's hard to have a discussion on the merits without those pieces...
