### ISSUE TITLE
can't build 0698aef (1.4.1-dev)

### ISSUE THREAD

**Issue by tlhonmey** [RPTools/maptool#138]
Looks to me like it doesn't like the version of spotless it gets on a clean build attempt.  Let me know if you need it run with debug options, but those seemed to produce more clutter without supplying anything helpful.   

```
$ ./gradlew build 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/laurence/build/maptool/maptool/build.gradle' line: 91

* What went wrong:
A problem occurred evaluating root project 'MapTool'.
> com/diffplug/gradle/spotless/SpotlessPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


```

**Comment by JamzTheMan** [comment]
And this is with the latest code from the repo? You didn't change the spotless version?  I have no issue with my build...

**Comment by Azhrei** [comment]
And the automated Travis build didn't have an issue.  Probably a local configuration problem.  He did specify "clean build attempt", but Travis does that every time too...

**Comment by perkinslr** [comment]
It doesn't successfully build for me using icedtea-8, but does with the official oracle java 8 (missing libraries, bad library versions).  It may be related to the problem you are having.  Once it is built, it will happily run with icedtea.

**Comment by Azhrei** [comment]
Paste the OP's error message into Google (```gradle/spotless/SpotlessPlugin : Unsupported major.minor version 52.0```) and you'll get hits for other people with the same issue.  It seems they're running Gradle under one version of Java and trying to use libraries from a different version.  The first hit I got had multiple solutions from different people, but they all boiled down to ensuring that JAVA_HOME (and JAVA8_HOME) were set correctly _everywhere_.

**Comment by tlhonmey** [comment]
Sorry it took me so long to come back to this.  It appears it doesn't like Gentoo's version of Iced Tea 7.  Switching my system over to Iced Tea 8 has it building fine, so I will close this and go pester them about it instead.  :)
