### ISSUE TITLE
Cannot access the site or the forum to download MapTools

### ISSUE THREAD

**Issue by drakkanis** [RPTools/maptool#1380]
Hello,

I have been attempting to access https://rptools.net and https://forums.rptools.net and I get a pop-up asking for username and password. The message is below:

> https://rptools.net is requesting your username and password. The site says: “Access Restricted (suspend)”

How do I access the site? How do I access the forums? Where do I register?

**Comment by cwisniew** [comment]
The website / forums are suffering from DDOS attack.
You can always download releases from https://github.com/RPTools/maptool/releases

**Comment by drakkanis** [comment]
Ah, figured it had to be some kind of malicious issue at hand. Thank you for the reply. 
Hope everything will be alright and you guys will emerge out of it safe and sound.
Do you happen to have a Discord?

**Comment by cwisniew** [comment]
Latest link will be on the MapTool subreddit (rather than posting a link that might be outdated here when someone else is searching)
https://www.reddit.com/r/MapTool/

in Other Resources
