### ISSUE TITLE
Macro export - nonsense message

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#1381]
**Describe the bug**
Exporting macro in 1.5.10 where file exists.
Expected file exists/overwrite dialogue. Got nonsense message in dialog instead.
Still functions as overwrite confirmation, just the message is confusing.

**To Reproduce**
Export macro in 1.5.10 to file that already exists.

**Expected behavior**
Overwrite confirmation.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/45483160/76724450-f5c71e00-6785-11ea-8567-836f7bfb3290.jpg)

**MapTool Info**
- Version: 1.5.10
- Install: New, Upgrade [previous version], or JAR [Java Version]
 - OS: Win 10

**Comment by Merudo** [comment]
PR #1415 fixes this.

**Comment by Phergus** [comment]
While the fix does correct the message content, it doesn't address the issue of _overwriting_ an existing file without a warning.

**Comment by Phergus** [comment]
I see what happened.  If the name filed just has the _name_ of the macro without the extension it will overwrite an existing saved macro without warning.

**Comment by Phergus** [comment]
Tested with update.  Exporting a macro with specifying the file extension now warns on overwrite.
