### ISSUE TITLE
createToken()

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#1385]
**Is your feature request related to a problem? Please describe.**
When trying to code wargames with lots of miniatures I would like to be able to create tokens on the fly when contructing armies through the framework UI. Similarly, when using tokens for disposable purposes I would like to be able to create and discard without having to set up a template token of each type for each case.

**Describe the solution you'd like**
something akin to copyToken where I can create a new token with options to define location, layer, propertyType, property values, etc.

**Describe alternatives you've considered**
This is a wishlist thing, it is doable by just copying an existing token but not as elegant.

**Comment by Phergus** [comment]
So it sounds like you want a version of `copyToken()` that takes an asset ID instead of a token ID.

For this to work you will have to provide an asset ID for the token image.  Which means there will be a token with that asset as its image already in the campaign.  Which means that you can just use `copyToken()`.

Both location and layer can be set with `copyToken()`.  Property Type could be added to the options for Updates.  Same for property values.

**Comment by bubblobill** [comment]
a) Tokens are not the only sources of images.
b) As I said, this is a wishlist thing. If it is not something anyone is keen to do and can be quickly and easily implemented then close it. It doesn't add any huge functionality that can't be performed by working through existing means.

**Comment by Merudo** [comment]
I think in many cases it would be cleaner to use

```newId = createToken(assetId, numCopies)```

The asset could be stored in a table.

**Comment by Phergus** [comment]
PR #3170 
Added two MT Macro Script functions
`createToken(tokenValues)` to create a token from a JsonObject
`createTokens(arrayofTokenValues)`  to create multiple tokens from a JsonArray of JsonObjects.

The format of the JsonObject is the same as https://wiki.rptools.info/index.php/copyToken but both name and Token Image are required.

Examples:

Create a single Token
```
[val = json.set("{}", "tokenImage", data.getStaticData("net.rptools.addon.some-lib", "/public/stick-figure.png"), "name", "test1")] 
[r: tokenID = createToken(val)]
```

Create Multiple Tokens
```
[val1 = json.set("{}", "tokenImage", data.getStaticData("net.rptools.addon.some-lib", "/public/stick-figure.png"), "name", "test1")] 
[val2 = json.set("{}", "tokenImage", data.getStaticData("net.rptools.addon.some-lib", "/public/stick-figure.png"), "name", "test2")]
[vals = json.append("[]", val1, val2)]  
[r: tokenIDarray = createTokens(vals)]
```

**Comment by bubblobill** [comment]
I love you

**Comment by Phergus** [comment]
Tested.  Functions working as expected.

**Comment by Phergus** [comment]
Wiki pages added.
https://wiki.rptools.info/index.php/createToken
https://wiki.rptools.info/index.php/createTokens
