### ISSUE TITLE
Non valid folder name (Windows 7)

### ISSUE THREAD

**Issue by helmoald** [RPTools/maptool#139]
I cannot check out the current branch (1.4.1-dev) because of the folder "C:\.net.rptools\AppUtilTest" in maptool. 
The issue is that Windows 7 does not allow ":" and "\" in folder names.

**Comment by JamzTheMan** [comment]
How are you checking this out?  I have now issues (Windows 10 environment).  I've used git checkout command line as well as within Eclipse more than several times...

**Comment by helmoald** [comment]
git clone https://github.com/RPTools/maptool.git
git checkout 1.4.1-dev-branch
fatal: cannot create directory at 'maptool/C:\.net.rptools\AppUtilTest': Invalid
 argument

**Comment by JamzTheMan** [comment]
welll... ok ya, that is odd. Looks like a merge or something went bad. Surprised travis-ci didn't catch that!
@Azhrei can you fix this?

@helmoald I don't have that in my repo.  I suggest you create a fork and then just remove that commit, it's not needed.  If you plan on making changes and submitting pull requests, it's better to checkout your own fork anyway and not directly from upstream.

**Comment by Jaggeroth** [comment]
I don't think you can remove it in Windows. At least Source Tree didn't understand the commit and so would not let me remove it.

**Comment by JamzTheMan** [comment]
yea, i think @Azhrei or @cwisniew will have to roll back that commit...

If you want, until then, you can fork my fork and check out 1.4.1.8 or 1.4.1.9 which is based on the latest dev branch.

**Comment by Azhrei** [comment]
I'll take a look.  In the meantime, "git cherry-pick" should solve the problem.  Another option would be a checkout hook that renames the file (but this is a LOT more work).

To prevent this in the future, we should probably add *:* to the .gitignore file...

**Comment by helmoald** [comment]
@JamzTheMan I will have a look at your forks. Thanks!

**Comment by Azhrei** [comment]
Corrected in 1.4.1.8 (or slightly earlier).
