### ISSUE TITLE
getAllPropertyNames ignores delim parameter if non-json

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1400]
**Describe the bug**
The function getAllPropertyNames ignores the delimiter parameter is it is something else than `json`, and instead use `,` as the delimiter.

**To Reproduce**
1. type `[getAllPropertyNames("Basic", "-")]`
2. observe how it returns the properties with `,` as the delimiter

**MapTool Version**
At least as far back as 1.4.0.5.  Maybe always.

**Comment by Merudo** [comment]
PR #1401 fixes this.

**Comment by Phergus** [comment]
Test.  Wiki page updated.
