### ISSUE TITLE
Function to return the Token ID

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#1405]
**Is your feature request related to a problem? Please describe.**
Token Id is fundamental to getting many things to work correctly but is not easily accessible, a bit of 
a pain when I need to pass it to UDFs and the like.

**Describe the solution you'd like**
a function like thisToken() that returns the ID of the token the macro is running on.

**Describe alternatives you've considered**
currentToken(), getSelected(), findToken(), getTokens() don't always return what you want and may require extra processing to ensure you have the correct result. I favour getSelected() but need to guard against multiple selections.

**Comment by Phergus** [comment]
Can you give an example of when it is that  `currentToken()` and `getImpersonated()` _don't always return what you want_?

**Comment by bubblobill** [comment]
hmmm.. just reread the documentation on currentToken which indicates it is what I want. I shall try to replicate the error. If I can do so reliably I shall submit a bug report instead.

**Comment by Phergus** [comment]
The `currentToken()` is pretty sparse but not sure what more could be added to it.  If you think of something let us know.

**Comment by Phergus** [comment]
Available functions are sufficient.  Closing.
