### ISSUE TITLE
Draw Explorer drawings depend on pen width even if foreground is invisible

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1408]
**Describe the bug**
If a drawing is made with no foreground, the displayed picture on the map does not depend on the selected pen width.

However, the drawing in the draw explorer reflects the selected pen width, even if there is no reason for it to do so.

**To Reproduce**
1. Select the Rectangle in `Drawing Tools`
2. Select no foreground by clicking `Cancel` while selecting the foreground color
3. Set the pen width to something really high, for example 60, and draw a rectangle
4. Draw the same rectangle but with a pen width set to 1.
5. Notice how different the two rectangles are in the Drawing Explorer.

**Expected behavior**
If no foreground texture/color is picked, the drawing does not depend on the pen width.

**Comment by Merudo** [comment]
PR #1409 fixes this.

**Comment by Phergus** [comment]
> Select no foreground by clicking Cancel while selecting the foreground color

Just FYI, you can just left-click or right-click in the top-left palette square to get transparent for fore/background respectively.

**Comment by Phergus** [comment]
Tested.  Preview of drawing in Drawing Explorer matches the drawing on the map.
