### ISSUE TITLE
Flickering when changing VBL/MBL mode from MBL to VBL

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1412]
**Describe the bug**

The new icon (right in VBL tools) lets the user switches from MBL to VBL, to Both (M/V), back to MBL.

When changing from MBL to VBL, the icon briefly flickers to the M/V .

**Expected behavior**
No flickering when switching from MBL to VBL.

**MapTool Info**
- Version: Develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Tested.  No more flicker.
