### ISSUE TITLE
Clickable links on hidden layer popups

### ISSUE THREAD

**Issue by jfranciscoap** [RPTools/maptool#1420]
I've seen this discussed every so often, but couldn't find an issue linked to it. I may have overlooked something, and apologize if that's the case.

I find the popup window that appears when you are in the Token layer and click a token in the Hidden layer to be one of the most useful features of Maptool. However I think that usefulness would be greatly improved if you could add working links - especially macroLinks - to that popup.

A scenario I envision is, for instance, a locked door or a trap. If you place a marker on the hidden layer you can bring about a popup with info (e.g. for D&D the DC to pick the lock or find the trap, the consequences, etc.). It would be great if there was a clickable link to run a macro to mark the door as unlocked, or the trap as activated, or a door as opened, setting or clearing VBL, automatically rolling damage etc. I can see lots of potential uses, and I get the impression it wouldn't be that difficult to implement. This would remove the need to switch between the Token and Hidden layers to initiate macros, which helps preserve the pace of the game.

I've seen some alternatives suggested, the most practical one being a docked window and a macro that updates on mouseover to get a similar effect, but this is, in my mind, less intuitive than a link and creates some accidental macro update problems.

**Comment by Phergus** [comment]
Just going to point out that Object layer items also get the popup for notes in case you were unaware.

**Comment by Merudo** [comment]
Should the hidden layer popups be changed to HTML5, or do we just want to enable links?

**Comment by jfranciscoap** [comment]
I think ideally it should be HTML5, because it's just too darn nifty to be able to style stuff, but if that adds layers of complexity I think enabling links would be enough.

I kinda want HTML5 there too, though...........

**Comment by Merudo** [comment]
The popup currently disappears after any click to it. Should that also happens after a click on a link?

**Comment by jfranciscoap** [comment]
I don't know about the rest of the peeps, but I'd be fine with the popup not disappearing at all when clicked on, only disappearing when clicking off of it (which is what I do naturally). But i assume more people may want to weigh in.

If we're not changing that base behavior, I'd make the link click behave as the rest of the popup, opening the link then disappearing.

**Comment by Merudo** [comment]
Currently, the Notes and GM Notes fields do not accept any macro code. So unless macro code gets enabled, the macrolinks in the notes would have typed by hand. Doesn't seem very doable.

**Comment by cwisniew** [comment]
> Should the hidden layer popups be changed to HTML5, or do we just want to enable links?

I have it on my todo list to make them HTML5 based and a little more configurable

**Comment by jfranciscoap** [comment]
That's a shame @Merudo ! Thanks a lot for trying though! However what did you mean by
> the macrolinks in the notes would have typed by hand
? Even if it's not very streamlined it could be useful.

**Comment by Phergus** [comment]
Tested.  Links in Objects and Hidden now open browser to URL.
