### ISSUE TITLE
Configurable HTML5 Replacement for mouse over stat sheets

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1424]
Replace the stat sheet for mouse over of tokens with a configurable one (using HTML5). 
The default should be similar to current stat sheet.

**Comment by JamzTheMan** [comment]
@cwisniew can you look at my latest comment on #1425 ? Since you are working on this already but I feel like we may have some opportunity for overlap/merge with these 2 issues?

**Comment by Akaku-Keninari** [comment]
Could this be basically an "onMouseHover()" event that has a default of launching a statsheet?

**Comment by thelsing** [comment]
I we are speaking about configurable mouseEvents: I would like the change be able to change the actions for DoubleClick on tokens too. In our round we have the MarkerPopup for DK for the DM (So that he can see the stats for monsters and the notes of roomtokens) and ShowHandout for players. (So that they can watch the nice pictures.) I guess this should be done in some kind of framework where menus, and toolbars are also configurable.

**Comment by kwvanderlinde** [comment]
This would be a very useful feature, along with similarly customizable notes.

I've got some questions for the sake of discussion:
1. Where should the configuration point be? Should individual tokens override it for themselves, or should this be restricted to lib: tokens / add-on libraries? And what do we do if there is more than one override?
2. Should the config point be phrased as applying to "mouse hover" or "show statsheet"? I.e., should we focus on the user interaction (implying some possible generality), or should we be specific about the purpose?
3. Assuming it's a macro that provides the overriding behaviour, should the macro be executed when a stat sheet is needed,, or should it just contain the HTML needed to show it (similar to what `html.overlay()` would expect). If executed, should it just return an HTML doc or should it be responsible for everything, including opening an overlay?
4. How do we close the statsheet when the hover ends? _This is only tricky if we expect the override to open its own overlay._

***

My own opinions are:
1. Don't care
2. Be specific, so phrase this as "show statsheet" or similar.
3. No macro execution, just use the HTML inside as if it was referenced via `html.overlay()`. Also implies the macro can't open its own overlay.
4. N/A given my take on (3).

**Comment by Azhrei** [comment]
> My own opinions are:
> 
> 1. Don't care

+1

> 2. Be specific, so phrase this as "show statsheet" or similar.

+1

> 3. No macro execution, just use the HTML inside as if it was referenced via `html.overlay()`. Also implies the macro can't open its own overlay.

I would make this dependent on the **Autoexecute** field of the macro editor's **Options** tab.  If auto-execute is turned on, it's a macro and should be executed to generate the HTML.  If auto-execute is turned off, it contains the raw HTML to be displayed.

My concern is that users already make mistakes with this particular option and don't even know it's there.

**Comment by cwisniew** [comment]
> This would be a very useful feature, along with similarly customizable notes.
> 
> I've got some questions for the sake of discussion:

Are you looking over my shoulder? I started on this last night for inclusion in 1.14


> 
> 1. Where should the configuration point be? Should individual tokens override it for themselves, or should this be restricted to lib: tokens / add-on libraries? And what do we do if there is more than one override?

The solution I have in mind is not just for the hover stat sheets but also starting point for character sheets in the future.

1. Implement a way to add stat/character sheets to MT (could be something like how add-ons are managed as a starting point)
2. In Campaign Properties -> Token Properties, add the ability for a "default" stat sheet for each "Token Type"
3. Each token can override this and have its own stat sheet if required.

All of the above is only able to be performed by GM so players cant break their game. 



> 2. Should the config point be phrased as applying to "mouse hover" or "show statsheet"? I.e., should we focus on the user interaction (implying some possible generality), or should we be specific about the purpose?

I think something, like pop up stat sheet + character sheet, will work



> 3. Assuming it's a macro that provides the overriding behaviour, should the macro be executed when a stat sheet is needed,, or should it just contain the HTML needed to show it (similar to what `html.overlay()` would expect). If executed, should it just return an HTML doc or should it be responsible for everything, including opening an overlay?

No macro execution to create a stat sheet, no macro execution in the stat sheet. This is for a couple of reasons
* It's harder to make stat sheets, I would prefer that those that are good at creating websites that look nice have as little barrier to creating this as possible. Especially when we get to full-blown character sheets
* It's not possible to call a macro from a HTML5 control that updates a HTML5 control without creating a race condition at the moment, and I am not sure this is going to be easy to solve for this case. Doing it this way eliminates the chance that someone does it

I am experimenting with a couple ways to do this that require no JS knowledge as well.


> 4. How do we close the statsheet when the hover ends? _This is only tricky if we expect the override to open its own overlay._
> 

No need, as its completely managed by MapTol
