### ISSUE TITLE
Make html 3.2 macro & hyperlinks easier to click, and enable internal anchors

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1427]
**Is your feature request related to a problem? Please describe.**

The MapTool links are notorious hard to click; if you move the mouse between press and release, the link won't work.

This has lead many to conclude that the links are bugged:  https://forums.rptools.net/viewtopic.php?f=21&t=28439

Additionally, anchor links of the form `a href="#x">` don't work within frames and dialogs.

**Describe the solution you'd like**

Both issues can be fixed relatively easily by replacing the `addHyperlinkListener` of the HTML pane by a regular `mouseListener`.

I suggest we make links fire if the mouse is released on the link.

**Additional context**
I have done most of the work already, with only a few details needing fixing.

**Comment by Merudo** [comment]
Test for an anchor link:

[dialog("test"):{<html><body><a name='link1'>test</a>some text<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />some more text<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />some more text<a href='#link1'>jump to top</a></body></html>}]

**Comment by Merudo** [comment]
PR #1428 implements this.

**Comment by Phergus** [comment]
Limited testing.   Anchors working in frames.  Macro links in chat are clickable. (Note I never had an issue with this so effectively no change for me.)
