### ISSUE TITLE
Macrolinks not working with the `usemap` attribute of `img`

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1430]
**Describe the bug**

The `usemap` attribute of `img` can allow the use to specify multiple links at given coordinates of an image.

Unfortunately, #1428 breaks the feature.

**To Reproduce**
1. Drop a "Dragon" token on the map.
2. Create a macro called "test" in the Campaign menu, with the content `RECEIVED`.
3. Run the following code:

```
[h: link = macroLinkText("test@Campaign", "all")]
[h: image = getTokenImage("", "Dragon")]

[frame("test"):{
  <img src="[r: image]" usemap="#imagemap">
  <map name="imagemap">
  <area shape="rect" coords="0,0,200,100" alt="left" href="[r: link]">
</map>
}]
```

4. Notice only the top half of the image is clickable (as intended), but clicking on it does nothing.

**Expected behavior**
macroLinks work with `usemap`

**MapTool Info**
- Version: develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
Oops! I just realized I need to use a `macroLinkText` instead of a `macroLink` for it to work. My bad!

**Comment by Phergus** [comment]
I did my href links differently but they work for me.
[ImageMap.cmpgn.zip](https://github.com/RPTools/maptool/files/4402727/ImageMap.cmpgn.zip)

**Comment by Phergus** [comment]
Ah.  You mean in current develop code.  Yeah.  Broken there now.

**Comment by Merudo** [comment]
PR #1431 fixes this.

**Comment by Phergus** [comment]
Tested.  Image maps working again.
