### ISSUE TITLE
Autosave in MT 1.4.1.8+ doesn't work

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#144]
A user reports here http://forums.rptools.net/viewtopic.php?f=60&t=23681&p=267496#p267496 that the autosave feature only works one time after a manual campaign save is performed.

**Comment by Azhrei** [comment]
New thread to discuss options:  http://forums.rptools.net/viewtopic.php?f=86&t=27325

**Comment by oliver-szymanski** [comment]
Is this fixed now? It was still not working for me before 1.5.0 release.

**Comment by Azhrei** [comment]
If it doesn't work for you, please specify your situation.  I was setting breakpoints in various places and waiting for them to trigger (with an autosave of 1 minute) and it looked to be working.

**Comment by oliver-szymanski** [comment]
I was just not sure if that was included in 1.5.0 I'm on the dev branch

**Comment by JamzTheMan** [comment]
@Azhrei this didn't get lost between 1.4.1.8 -> 1.5.0 did it? Maybe it never made it into my fork?

**Comment by Azhrei** [comment]
1418 was released Aug 2017.  The autosave fix went in in early 2018.  So it would've been in 1419 (but no official 1419 was released).  It should be in 150.  It's PR #173 if you want to look at it.

**Comment by oliver-szymanski** [comment]
Seems to work so far. I know it never worked with the Nerps version I had.

**Comment by Phergus** [comment]
As this won't be fixed in 1.4.1.8 and appears to be working in 1.5.0, recommend closing this as Won't Fix.

**Comment by Phergus** [comment]
This appears to be working fine in 1.5.0+

Closing.
