### ISSUE TITLE
Bug: Show as Player (Control-Shift-P) doesn't work when server is set to I.Views=Off

### ISSUE THREAD

**Issue by dorpond** [RPTools/maptool#146]
(1.4.0.5 and Jamz1.4.4.0)

Show as Players (Control-Shift-P) doesn't work when server is set to I.Views=Off. The view changes but all PC tokens vanish. Note: I.Views=On works fine.

-Start a server with I. Views=Off
-Vision must be either Day or Night

Here is a campaign file if you wish to test:
https://rptools.slack.com/files/U18GPQKDH/F723X44RJ/controlshiftp.cmpgn

**Comment by Phergus** [comment]
This appears to be the same as Issue #357.  Closing this issue.
