### ISSUE TITLE
A missing case in a switch causes an obscure error message

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#1460]
**Describe the bug**
When a macro encounters an unhandled switch case, it produces an obscure error message which doesn't explain the source of the error

**To Reproduce**
1. create a new macro
1. add the following code:
```
[h: m = 2]
[switch(m):
case 1: x = 2
]
```
1. run the macro

The output is something like 
```
"line 1:8: unexpected char: ':' " 
```

**Expected behavior**
A proper error message explaining the missing case

**Screenshots**
None

**MapTool Info**
- Version: 1.6.x
- Install: New

**Desktop (please complete the following information):**
 - OS:  Windows
 - Version 10

**Comment by Phergus** [comment]
Tested switch statement without Default and uncaught case.
```
[h: m = 2][h: x = -1]
[h, switch(m):
  case 1: x = 2;
  case 3: x = 3;
]
[r: x]
```
now produces
```
SWITCH option found no match for "2".
       Statement options (if any): h, switch(m)
       Statement Body : case 1: x = 2; case 3: x = 3;
```
