### ISSUE TITLE
Update Window menu to be alphabetical

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#1463]
**Describe the bug**
The Window menu currently has the list in seemingly random sequence.  I propose that the text be translated and sorted alphabetically, with named frames at the bottom below a separator.

**To Reproduce**
1. Look at the Window menu

**Comment by xdy** [comment]
Added a fix for this on my branch.

**Comment by xdy** [comment]
PR created https://github.com/RPTools/maptool/pull/1604

**Comment by Phergus** [comment]
Tested with English language.  Windows appear in menu in alpha order.
