### ISSUE TITLE
Make Maps roatateable when importing

### ISSUE THREAD

**Issue by dbirchbauer** [RPTools/maptool#1466]
Right now when you are importing a map from a PDF you are at the mercy of whomever embedded the image in the PDF and their orientation choice. Being able to rotate a map in increments of 90 degrees would make things a lot easier to deal with.

**Comment by JamzTheMan** [comment]
If you have a mouse wheel, you can rotate any image in 90 degree increments.

I want to say you can also hold down one of the modifier keys while dragging a corner will cause it to snap in even increments as well?

**Comment by dbirchbauer** [comment]
> 
> 
> If you have a mouse wheel, you can rotate any image in 90 degree increments.
> 
> I want to say you can also hold down one of the modifier keys while dragging a corner will cause it to snap in even increments as well?

I am using 1.5.14 and am not seeing any of those options. If you could provide a little more detail on how, it would be appreciated

**Comment by Phergus** [comment]
1. Select Background in Layer selector.
2. Click and drag map image from PDF folder in Resource Library to map area.
3. Hold down Shift and rotate image with mouse wheel.

Default rotation is 90 degrees (60 on hex grids).  Facing in Edit -> Preferences allows rotation in 45 (or 30 on hex grids) by enabling On Vertices.  Holding down Ctrl while rotating allows finer rotation.

**Comment by Azhrei** [comment]
> 1. Select Background in Layer selector.
> 2. Click and drag map image from PDF folder in Resource Library to map area.
> 3. Hold down Shift and rotate image with mouse wheel.

Because of the funkiness with horizontal scrolling on macOS, step 3 must be replaced:

3. Right-click and choose **Set Facing**, then move the mouse.  Note how the bottom edge of the image rotates to face the current mouse position.

Can we close this?

**Comment by Phergus** [comment]
I think so.
