### ISSUE TITLE
onChangeSelection event fires too many times

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1468]
**Describe the bug**
The event `onChangeSelection` fires too many times. This leads to macros being executed multiple times instead of once, lagging the system and possibly causing bugs.

**To Reproduce**
1. Creates a macro on the campaign panel called `print` with `[r: macro.args]` inside
2. Creates this macro: 
```
[h: processorLink = macroLinkText("print@Campaign", "all", "event fired")]
[frame("Test"):{<link rel='onChangeSelection' type='macro' href='[r:processorLink]'>}]
```
3. Launch the macro, and select/unselect tokens. Clicking on a token causes it to be executed 2 or more times.

- Selecting a token: fired 4 times
- Selecting the same token: fired 3 times
- Dragging a selection rectangle stoken / unselecting all tokens : fired  2 times

**Expected behavior**
The onChangeSelection event is only fired once.

**MapTool Info**
- Version: 1.5.14, 1.6.0 beta 2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by JamzTheMan** [comment]
Yes, that's a stupid bug that needs to be squashed and usually requires hacks to prevent macros from running multiple times which is painful.

Is this the only event macro that fires multiple times?

**Comment by Merudo** [comment]
I don't know a thing about `onChangeImpersonated` as I almost never use impersonation.

When I changed macros to update only the properties of interest instead of sending the whole token everything,  I tried keeping `onChangeToken` only firing once per macro. I suspect there might be a few cases of duplicated event firing in there, though.

**Comment by Merudo** [comment]
PR #1470 fixes this.

**Comment by Phergus** [comment]
Tested with test case provided and modified to include `onChangeToken` event.  Only single events observed for selection, deselection and moving of tokens.
