### ISSUE TITLE
Cursor offset when dragging a token on the background layer

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1469]
**Describe the bug**
Dragging a token on the background / object layer causes the cursor to end up at the slightly wrong place after the drag.

**To Reproduce**
1. Create a token on the background layer
2. Drag it a fair distance
3. Notice the cursor ends up about 1 square away of where it should

**Expected behavior**
No cursor jumping after a drag.

**MapTool Info**
- Version: 1.5.14, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Notes**
A similar glitch was seen on the token layer for a while. I guess the Stamp tool version is not fixed.

**Comment by Phergus** [comment]
Testing #1475 changes.  Moving medium sized tokens is improved but native-sized stamps that are snap-to-grid are much worse with the mouse pointer shifted far up and left from the original click point.

Suspect it should be using grid cell size instead of token bounds.
```
dragOffsetX = (pos.x - tokenBounds.x) - ((int)getZone().getGrid().getCellWidth() / 2);
dragOffsetY = (pos.y - tokenBounds.y) - ((int)getZone().getGrid().getCellHeight() / 2);
```

**Comment by Merudo** [comment]
You are absolutely right, good catch!

**Comment by Phergus** [comment]
Tested again with #1476.  Working as expected now.
