### ISSUE TITLE
Bug: VBL drawing tool is using drawing tool opacity setting

### ISSUE THREAD

**Issue by dorpond** [RPTools/maptool#147]
(1.4.0.5 and Jamz1.4.4.0)

-Set the drawing tool Opacity to something low, like 1 (any value will work but 1 will certainly show you the bug the best).
-Now change to VBL and draw a VBL line or Polygon (those are the only two VBL drawing tools effected).
-You won't see the VBL line as you are drawing it, but you will see the executed end result. 

I accidentally stumbled across this because I was drawing maps in MT and using opaque layering; I had left the drawing tool opacity at 20% and later, when I went to draw VBL, and I was like "what is going on??"

**Comment by Jaggeroth** [comment]
Can I grab this Issue?

**Comment by JamzTheMan** [comment]
Absolutely.

**Comment by JamzTheMan** [comment]
We don't have access to assign issues to each other so we?

**Comment by Jaggeroth** [comment]
I don't think so. At least, I couldn't work out how :)

**Comment by Jaggeroth** [comment]
Well that was easy.
Two line of code added :)

**Comment by JamzTheMan** [comment]
should this be closed out?
