### ISSUE TITLE
Add Image Tokens to output of getInfo("client")

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1473]
**Is your feature request related to a problem? Please describe.**
Currently no way to get a list of image tokens ("image:target.png") via macro.

**Describe the solution you'd like**
Lib:tokens are already listed in the getInfo("client") output and image tokens could be done the same.

```
"library tokens": {"lib:traps": "unknown", "lib:spells": "unknown"},
"image tokens": {"image:pittrap": "unknown", "image:fireball": "unknown"},
```

**Describe alternatives you've considered**
No other way found to get a list of tokens that includes the image tokens.

**Comment by xdy** [comment]
Possible fix on branch.

**Comment by Phergus** [comment]
Looks good.  Go ahead and do a PR.

**Comment by Phergus** [comment]
Tested with develop. Image tokens (`image:tokenname`) now included in output of `getInfo("client")`.
