### ISSUE TITLE
HTML5 form submission ignores novalidate & formnovalidate

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1477]
**Describe the bug**
The form attribute `novalidate` (to bypass validation on a form) as well as the attribute `formnovalidate` (to disable validation when clicking a button) are both ignored in frame5 and dialog5.

**To Reproduce**
Example of a form where the submit button should always be allowed because of `novalidate`:

```
html
<form action=[r:processorLink] method="json" id="myform" novalidate>
Name: <input type="text" name="charName" value="" required>
<input type="submit" name="submit" value="submit" form='myform'>
</form>
```

**Expected behavior**
The `novalidate` and `formnovalidate` attributes are respected.

**MapTool Info**
- Version: develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1478 fixes this.

**Comment by Phergus** [comment]
Tested with:
```
[h: link = macroLinkText("foo@Campaign", "all")]
[frame5("test"):{
<html>
<form action=[r: link] method="json" id="myform" novalidate>
Name: <input type="text" name="charName" value="" required>
<input type="submit" name="submit" value="submit" form='myform'><br />
<input type="submit" formnovalidate="formnovalidate" value="Submit without validation">
</form>
</html>
}]
```
Working as expected.
