### ISSUE TITLE
previous initiative function and button

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#1479]
**Is your feature request related to a problem? Please describe.**
Accidentally advancing initiative with a double click or before the player has finished up their actions is a pain. It is my assumption that I cannot be the only person who does this more often than they should.

**Describe the solution you'd like**
It would be nice to have a Prev. button as well as a Next button. There may also be call for a functon that performs the same for people coding fancy initiative interfaces. Accessibiility would be improved if there was a button rather than right-click interface options.

**Describe alternatives you've considered**
Coded a macro to do it, but it doesn't conveniently live in the initiative window. Otherwise it is select the previous token > right-click > Make Current.

**Comment by mrkwnzl** [comment]
There is a “Previous” button in the initiative window in the “Next” contextual menu (the little arrow on the right hand side of the button). It’s easier than right-clicking the token and make it current.

**Comment by bubblobill** [comment]
Not so easy if you area using speech control or other accessibility software compared to a button.

**Comment by Phergus** [comment]
@selquest Need you to comment on the issue.

**Comment by selquest** [comment]
Added macro function - the rest of this (UI button) was already taken care of in 1.7

**Comment by selquest** [comment]
Wiki page added for `prevInitiative()` function, marked as coming in 1.8.

**Comment by Phergus** [comment]
Note that Previous Initiative button was added in MT 1.7.0 in #1758 .

**Comment by Phergus** [comment]
Tested.  Working as expected.
