### ISSUE TITLE
MT on Raspberry Pi 3

### ISSUE THREAD

**Issue by mjmeans** [RPTools/maptool#148]
Hi. I've been using MapTool 1.4.0.5 on a Raspberry Pi 3 (using the zipped java package) to operate a projector. It's working fine. I'd like to try the latest version of MapTool dev but I don't see a download ZIP file of a JAVA version like there is for 1.4.0.5. Would you please post it or tell me where to get it that doesn't require installing anything. I just need to extract it to a folder on the Raspberry Pi and run it with the java command line without having to install anything that isn't already there and able to run the other version.

**Comment by rkathey** [comment]
That's the second request for a zip file I've seen today. Is there a way to
produce that form the current build process?

**Comment by Azhrei** [comment]
It’s already there.  Visit the download page at http://www.rptools.net/downloadsw/, click the MapTool image, then look below the dev versions and you’ll see it.

**Comment by rkathey** [comment]
Going forward, is there a way to add a zip file to the dev releases?

**Comment by Azhrei** [comment]
Hm.  I suppose.  But testing installer changes is part of testing a development build, so we want people to use it as packaged.  However, the .tar files can be used if people want to download and extract the JARs — WinZip and friends will handle tar files correctly.

**Comment by mjmeans** [comment]
1. It's not already there. ZIP with Java version is only for 1.4.0.x, not the latest 1.4.1.x.

2. I've tried extracting .tar file on Windows to put it on a USB stick so I can get it onto the RPi. All I get is another single file with no extension. I've tried using built-in Windows ZIP extraction and WinRAR. Years ago I tried WinZip and it had bloatware included so I uninstalled it and never looked back. If there were an alternative to Sun Java's installer (which also has bloatware) I would stop using that too.

**Comment by Azhrei** [comment]
Doh, you're right.  I saw the "1.4.0.5" in your message and misread what you were looking for.  My bad.

I just looked inside the tar file and you're right -- it's a Linux executable, which... I don't understand.  I'll have to try it and see what it produces -- it may be the equivalent of a self-extracting zip.

Thanks for mentioning this -- we'll get something produced that can just be unpacked...

**Comment by Syndaryl** [comment]
Check out the OpenJDK
http://openjdk.java.net/install/



-- 
Emily Smirle
<emily.smirle@gmail.com>

**Comment by JamzTheMan** [comment]
@Azhrei The gradle build should still be producing the old zip releases as well and will be in the main \build dir if you want to post them.

OR you could also just post the MapTool & Launcher fat jar's.  TBH that would probably be easier for this use case, you just have a single file to copy to the PI (if you launch via command line) or 2 if you need the launcher.

**Comment by mjmeans** [comment]
@Azhrei Yeah, and a Linux executable is likely CPU dependent; and if so it wouldn't work on a RPi with an ARM processor or a DragonBoard that uses a Qualcomm SnapDragon processor. OS dependent executables are also an issue, so even if there is an ARM executable, it might not work in Raspbian. Also neither of these are likely to work on one of the large format Android tablets.

**Comment by Azhrei** [comment]
Thanks for the input, everyone.  I've uploaded the ZIP files for 1418 and they're available from the Download page (just verified).  I'll make sure the ZIP versions are uploaded when I do future builds. :)

**Comment by mjmeans** [comment]
@Azhrei Thanks. Perhaps the [Invalid] tag on this issue can be removed.

**Comment by Phergus** [comment]
This appears to be resolved.

Closing.

**Comment by emmebi** [comment]
@Phergus Any reason why this is still open?

**Comment by Phergus** [comment]
No reason.
