### ISSUE TITLE
Editing a macro which is already being edited creates new Find/Replace entries in Edit menu

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#1495]
**Describe the bug**
The 'Find/Replace' menu items under 'Edit' open up repeatedly if you try to open a macro window which is already open. These items do nothing and then linger until you restart MapTool.

**To Reproduce**
1. Right-click and edit a macro on any macro panel.
2. Without closing the editor, repeat step one to your heart's content.
3. See error - multiple copies of the Find/Replace macro editor options appear in the edit menu.

**Expected behavior**
These options should only open once when I right-click on a macro and edit it, even if it is already open.

**Screenshots**
Weeeeee!
![image](https://user-images.githubusercontent.com/220149/78918194-e06fa780-7a44-11ea-9c45-da61933fe388.png)

**MapTool Info**
- Version: 1.5.14 and 1.6.0rc1
- Install: New alongside many previous versions

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Maybe these options should reside in each Macro Editor rather than appending to the top-level Edit menu. That would also solve the issue of having multiple anonymous looking copies when multiple macros are open.

**Comment by Phergus** [comment]
Pretty sure there is an issue for this already.

**Comment by melek** [comment]
I also remember something similar.. but I looked and couldn't find it :(

**Comment by Phergus** [comment]
Me either.  Just searched all the closed ones as well.  It was a pretty old issue and I think this was a side-effect of some Mac fix.

**Comment by Azhrei** [comment]
It is/was.  It's my fault (I'm sure I said that in the other issue as well! 😉).

The menus are done differently on macOS and while the main program takes care of this, it isn't broken out into its own class so Jamz wouldn't have known unless he'd gone looking for it.  And I didn't realize the macro editor was modeless and thus multiple could be open at once.  The fix will also require that the menu actions be directed to the macro editor with the focus and I'm not sure how that's done without reading some docs.

If no one else jumps on this one, I'll look into it.  Refactoring the menu management of MapTool should probably be done so that dialogs like this one can take advantage of it as well.  And this ties into #1462 #1463 (and possibly others).

**Comment by JamzTheMan** [comment]
Is it time to wrap all these dialogs into a tabbed window instead? May make solving this easier.

Wrapping this into a parent frame and having the macro command in tabs with the detail "tab" moved to the bottom of the parent window in a collapsible pane also solves another issue/complaint of taking too many clicks to edit a macro name or other details...

**Comment by melek** [comment]
I keep macro editors side by side when working on related macros sometimes. Being able to dock them together like chrome tabs and break them into windows when I want would be neat, but seems like a lot of work. 

To address the original issue, I wonder if it would help if each macro editor window had its own little 'edit' menu when focused instead of appending options to the main menu. Not sure how that would work on mac, however.

**Comment by Merudo** [comment]
This issue is directly related to #1426. After following @melek's step above, quitting MapTool will launch an NPE.

**Comment by Merudo** [comment]
My suggestion is that if a macro edit window is already open, clicking on its button doesn't do anything except focusing on it.

**Comment by Merudo** [comment]
PR #1825 fixes the bug while we wait for a more thorough refactoring of the dialogs.

**Comment by Phergus** [comment]
Attempting to edit a macro already open in an edit dialog no longer adds multiple instances of the edit menu items.

**Comment by JamzTheMan** [comment]
Nice!
