### ISSUE TITLE
Common Macros group is only available when the selected tokens share at least one macro

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#1496]
**Describe the bug**
If you select two tokens with no macro in common, the Common Macros group is not shown. Since the Common Macros group also contains the "Add New (macro?) To Selected", or the "Import Macro To Selected", it would make more sense to have this group always shown when two or more tokens are selected.

**To Reproduce**
1. add a token 
1. add another token
1. select them both and check the Selection Panel: no common macros
1. add a macro (don't rename it) to first token
1. add a macro (don't rename it) to the second token
1. now the Common Macros group is shown

**Expected behavior**
Common macros is always shown when more than one token is selected.

**MapTool Info**
- develop
- Install: new

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by emmebi** [comment]
As I am working on macro groups at the moment, feel free to assign it to me.

**Comment by Phergus** [comment]
Calling it a bug/feature as I think it was intentional but I agree that the group should show up even with none in common.

**Comment by Phergus** [comment]
Tested.  Common Group now shows even if both tokens have no macros.  Import Macro and Import Macro Set to Common adds them to the selected tokens.  Context menu options for the groups and buttons working as expected.

Selected panel documentation will likely need updating.
https://wiki.rptools.info/index.php/MapTool_User_Interface#Macro_Panels
