### ISSUE TITLE
Macro not being parsed correctly

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#1497]
**Describe the bug**
While editing a HTML5 frame macro with apparently correct syntax, I found that the code was sometimes misinterpreted by dumping code verbatim to the frame, or would result in a syntax error, or would happen to work fine, all depending on whether I applied certain trivial changes to the code.

**To Reproduce**

I apologize for the verbosity here. Normally I would reduce such a bug much further, but in this case I couldn't do any better. There are three versions of the `statSheet_BuggedFrameContent` which differ only in minor ways, but which result in completely different behaviour from the macro system.

1. Add a new lib token named "Lib:token".
2. Add two macros, disabling "Allow Players to Edit Macro":
   1. `statSheet_BuggedOpenFrame`:
   ```
   [frame5("showSelected"): {
   	[r, macro("statSheet_BuggedFrameContent@lib:token"):""]
   }]
   ```
   2. `statSheet_BuggedFrameContent`:
   ```
   [h: selection = getSelected()]
   <!DOCTYPE html>
   <html lang="en">
       <head>
           <link rel='onChangeSelection' type='macro' href='[r:macroLinkText("statSheet_BuggedOpenFrame@lib:token")]'>
       </head>
       <body>
           [r, if (listCount(selection)==1), code:
               {
                   <!-- When a single token is selected, show the stat sheet -->
                   [foreach (saveBonusEntry, "CON=5,DEX=4"), code:
                       {
                           [r: strformat('%+d', 5)]
                       }
                   ]
                   [r, if(0), code:
                       {
                           [foreach(something, "a,b,c"), code:
                               {
                               }
                           ]
                       };
                       {
                       }
                   ]
               };
               {
                   <!-- When a multiple tokens are selected, show a table of them. -->
                   This should not be displayed when only one token is selected!
                   [foreach(id, selection, ""), code:
                       {
                           ''
                       }
                   ]
               }
           ]
       </body>
   </html>
   ```
3. Run the `statSheet_BuggedOpenFrame` macro by clicking on its button. an HTML5 frame should open. My looks like this: 
![image](https://user-images.githubusercontent.com/7492219/78940000-ffccfb80-7a69-11ea-9454-ae62de690f6e.png)
4. Add a regular token to the map and select it. Doesn't matter what you choose (it could even be lib:token actually). The frame should update to look like this: 
![image](https://user-images.githubusercontent.com/7492219/78940136-386cd500-7a6a-11ea-9e1b-93a96e25aea4.png).
   * This is the first sign of trouble.
   * Notice that all the code after the `if(0)` roll is dumped verbatim rather than treated as code.
   * I can verify that the other `foreach`s and `if`s run normally (at least as far as observable).
5. Modify `statSheet_BuggedFrameContent` to remove the quotes from the final `foreach`:
   ```
   [h: selection = getSelected()]
   <!DOCTYPE html>
   <html lang="en">
       <head>
           <link rel='onChangeSelection' type='macro' href='[r:macroLinkText("statSheet_BuggedOpenFrame@lib:token")]'>
       </head>
       <body>
           [r, if (listCount(selection)==1), code:
               {
                   <!-- When a single token is selected, show the stat sheet -->
                   [foreach (saveBonusEntry, "CON=5,DEX=4"), code:
                       {
                           [r: strformat('%+d', 5)]
                       }
                   ]
                   [r, if(0), code:
                       {
                           [foreach(something, "a,b,c"), code:
                               {
                               }
                           ]
                       };
                       {
                       }
                   ]
               };
               {
                   <!-- When a multiple tokens are selected, show a table of them. -->
                   This should not be displayed when only one token is selected!
                   [foreach(id, selection, ""), code:
                       {
                       }
                   ]
               }
           ]
       </body>
   </html>
   ```
   Hit apply, then re-select the token. Now we get an error in the chat window: 
![image](https://user-images.githubusercontent.com/7492219/78940760-3d7e5400-7a6b-11ea-96ec-cd99fd951d32.png)
   ```
   Error in roll for IF option.
         Statement options (if any): r, if (listCount(selection)==1), code
         Statement Body (first 200 characters): {  [foreach (saveBonusEntry, "CON=5,DEX=4"), code: { [r: strformat('%+d', 5)] } ] [r, if(0), code:
   ```
   At least now the macro system acknowledges that there is a problem, but I don't see why this has changed anything, nor do I see where issue is with the code.
6. Revert the previous change, and now instead remove the most nested `foreach`:
   ```
   [h: selection = getSelected()]
   <!DOCTYPE html>
   <html lang="en">
       <head>
           <link rel='onChangeSelection' type='macro' href='[r:macroLinkText("statSheet_BuggedOpenFrame@lib:token")]'>
       </head>
       <body>
           [r, if (listCount(selection)==1), code:
               {
                   <!-- When a single token is selected, show the stat sheet -->
                   [foreach (saveBonusEntry, "CON=5,DEX=4"), code:
                       {
                           [r: strformat('%+d', 5)]
                       }
                   ]
                   [r, if(0), code:
                       {
                       };
                       {
                       }
                   ]
               };
               {
                   <!-- When a multiple tokens are selected, show a table of them. -->
                   This should not be displayed when only one token is selected!
                   [foreach(id, selection, ""), code:
                       {
                           ''
                       }
                   ]
               }
           ]
       </body>
   </html>
   ```
   Despite the fact the we just removed an empty foreach that never runs, this works with no errors and renders as expected:
![image](https://user-images.githubusercontent.com/7492219/78941045-bf6e7d00-7a6b-11ea-9336-7d9b3a8d43e5.png)

**Expected behavior**

I would expect the above examples to run largely the same as opposed to demonstrating entirely different behaviour and errors.

**Screenshots**

Here's a shot of my macro editor: 
![image](https://user-images.githubusercontent.com/7492219/78941357-605d3800-7a6c-11ea-8f25-59de1e9280c1.png)
Syntax highlighting and code folding matches my understanding of the code structure.

**MapTool Info**
- Version: 1.6.0.rc1
- Install: New install

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 19.4

**Additional context**

Not sure if this is of any use in this case, but here is the debug information:
```
==== MapTool Information ====
MapTool Version: 1.6.0.rc1
MapTool Home...: /home/kenneth/.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 300 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: /opt/MapTool/runtime
Java Version: 10.0.2

==== OS Information ====
OS Name........: Linux
OS Version.....: 5.3.0-46-generic
OS Architecture: amd64
PATH...........: /home/kenneth/.local/bin:/home/kenneth/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Number of Procs: 6

==== User Information ====
User Name: kenneth
User Home: /home/kenneth
User Dir.: /opt/MapTool/app

==== Network Interfaces ====
Display Name..: wlo1
Interface Name: wlo1
Address...: 2001:569:728a:b100:11ab:5ef:4dc1:7c59%wlo1
Address...: 2001:569:728a:b100:6755:b36d:63e8:c1fa%wlo1
Address...: fe80:0:0:0:b1df:e4b0:4b98:b892%wlo1
Address...: 192.168.1.74

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.1.254

==== Locale Information ====
Country.: Canada
Language: English
Locale..: English (Canada)
Variant.: 

==== Encoding Information ====
Default Locale:   en_CA
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(-1)

==== Internet Gateway Devices ====
Device Name.: Actiontec V1000H GUI
Model Name..: V1000H
Manufacturer: Actiontec
Model Number: null
Model Desc..: (null)
Firmware....: Custom/1.0 UPnP/1.0 Proc/Ver
External IP.: 64.180.95.208
```

**Comment by Phergus** [comment]
One too many nested code blocks.  You'll need to break up that macro into calls to other macros.  Look at User Defined Functions (UDFs) via the `defineFunction()` macro.

Take out that inner `foreach` block:
![TooManyCodeBlocks](https://user-images.githubusercontent.com/34379254/78946076-07e36600-7a7f-11ea-8a4c-dbd03bac7ed9.png)

**Comment by kwvanderlinde** [comment]
Awesome, thanks! Yep, I've been using UDFs for some things already so it shouldn't be hard to pull some logic out. I didn't realize there was a hard limit on nesting code blocks, but since you mentioned it I was able to find that this is actually described in the cookbook: https://www.lmwcs.com/rptools/wiki/Working_With_Two_CODE_Levels

**Comment by Merudo** [comment]
Is this specific to `frame5`? Or does the same happens for `frame`?

**Comment by Phergus** [comment]
His example was for frame5 but it applied to either one.
