### ISSUE TITLE
sendToBack & bringToFront macros break states and bars

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#150]
Still outstanding per the wiki:

> As of 1.3.b63 there appears to be a bug in which token states are not rendered properly after calling sendToBack or bringToFront. As a work-around, macros should change the token ordering first, then turn states on or off.

**Comment by JamzTheMan** [comment]
Note to self:  I have this fixed in my fork, need to port it back...
Thoughts, should I create a label here like "Fixed in Nerps" or something to denote as such?

**Comment by Phergus** [comment]
Issue was fixed in Nerps branch and thus in 1.5.0.

Tested sendToBack and bringToFront with tokens with existing states with no issues.

Closing.

**Comment by Phergus** [comment]
Wiki pages updated.
