### ISSUE TITLE
"User data directory is already in use" with frame5/dialog5 on two instances of MapTool

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1501]
**Describe the bug**
When two instances of MapTool on the same machine call frame5 or dialog5, an ugly error message is printed to the chat: `User data directory [null (C:\Users\user\AppData\Roaming\java\webview)]`.

**To Reproduce**
1. Start two instances of MapTool on the same machine
2. Run `[frame5("test"):{test}]` in both
3. Look at the error message

**Expected behavior**
No error message.

**MapTool Info**
- Version: 1.6.0 RC1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
I do not believe it is possible to turn off the user data directory. The user directory is not used by frame5 and dialog5 anyway and so I suggest we just hide the message.

**Comment by Merudo** [comment]
PR #1502 hides this error message.

**Comment by Phergus** [comment]
Tested with develop.  No longer shows error message when two or more MapTool instances use the `frame5()` and `dialog5()` functions.
