### ISSUE TITLE
Edit Token Dialog doesn't update Properties when viewing a different token

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1504]
**Describe the bug**
The Edit Token Dialog is _remembering_ the properties of the first token opened in a MapTool session when viewing new tokens.  This extends to remembering the Property set used on that first token even after a New Campaign is loaded.

**To Reproduce**
1. Load a campaign with two or more tokens that have properties already set.
2. Double-click on a token to open Edit Token dialog and observe token properties.
3. Close dialog.
4. Double-click on a different token and observe token properties.
6. Same values are displayed.
7. Note that Stat Sheet displays the actual token properties and retrieving properties via macros works correctly.

**Expected behavior**
Properties displayed should match those on the token.

**MapTool Info**
- Version: 1.6.0
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Example campaign with tokens.
[TokenPropsBug.cmpgn.zip](https://github.com/RPTools/maptool/files/4462753/TokenPropsBug.cmpgn.zip)

**Comment by JamzTheMan** [comment]
Is this the refresh issue or is it truly letting you see and edit old them?

**Comment by Phergus** [comment]
Both.  If you don't change anything in properties the current token keeps its actual values.  But if you change even one property all of them are changed to the values of the originally selected token.

**Comment by mrkwnzl** [comment]
It doesn’t appear to happen on my old campaign that I created on some 1.5 version, only when I create a new one.

**Comment by Merudo** [comment]
It happens only if the token's property type is the first in the property type list.

**Comment by mrkwnzl** [comment]
In my campaign file, it’s the first property type in the list and doesn’t happen.

**Comment by Phergus** [comment]
And you have multiple property sets?

**Comment by mrkwnzl** [comment]
Yes, three.

**Comment by Merudo** [comment]
It also doesn't happen for my old campaign. Which is the one I used for my tests when I wanted to make sure my fix to #472 wasn't breaking anything :/.

**Comment by Merudo** [comment]
Oh! I think it's because the "Basic" type changed in an update.

**Comment by Phergus** [comment]
One of my older ones didn't do it but another did.  And the new one I created above did.

**Comment by Phergus** [comment]
Tested fix. 
- Dialog now displays the correct info when going from token to token.
- Dialog correctly updates after loading a different property set for tokens.
- Dialog correctly updates when loaded a different campaign.
- Works correctly with older campaign.
Appears to be working correctly now.

**Comment by Merudo** [comment]
If you have tokens with a non-listed property type, the blank screen becomes the index 0 choice.

**Comment by Phergus** [comment]
Interesting.  I always reuse the Basic as you can't get rid of the stupid thing.
