### ISSUE TITLE
Feature request: Androports integration

### ISSUE THREAD

**Issue by Eteepell** [RPTools/maptool#151]
A few months ago a new app by the same guy that wrote andropen office came out. It is running native linux applications.

Native linux Firefox, thunderbird, and gimp so far is running on nonrooted android devices. He is going to introduce linux native libreoffice as well through the same app.

This would be a great opportunity to attain a maptools android port with little to no change of existing code. It would get on google play as well through the androports app. The app is on github.

Links:
https://github.com/androidports
https://www.twitter.com/androports
http://androports.blogspot.ca

**Comment by Phergus** [comment]
The Androports project appears to be untouched for several years.
