### ISSUE TITLE
Two issues - image drop and push to talk not working

### ISSUE THREAD

**Issue by ThePsycher** [RPTools/maptool#1511]
**Describe the bug**
First, for many iterations now, I am unable to drag an image file from another location (desktop, folder) and drop it onto the map area. I have missed this ability, please fix.

Second, when I and my group use Discord to talk while using maptools, none of our push to talk buttons will work while the maptools window is selected - we have to tab to any other window for it to function, but if we go back to maptools window it stops working. Please fix, this is making it difficult for us to play together virtually.

**To Reproduce**
Out of six copies of maptools, my group and I have failed not to reproduce these bugs.

**Expected behavior**
Image files, when clicking and dragging, should load onto the map in the same manner as when  selected from the library folders.

Push to talk buttons should continue to function for discord the same as every other window (first program I've encountered with this bug)

**Screenshots**
None

**MapTool Info**
- Version: 1.6.1, though this applies to many of the 1.5 versions as well, and as for when images could no longer be click-dragged into maptools, that has been a problem now for at least a year.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [10, 18362]

**Additional context**
None

**Comment by Merudo** [comment]
I'm on Windows 10 and never had trouble dragging an image to the map as a host or player.

**Comment by ThePsycher** [comment]
I'm assuming current version?

**Comment by Merudo** [comment]
Yep. 1.6.1.

**Comment by ThePsycher** [comment]
Hmm, I was wondering if it may be a compatibility issue, the native size of the fonts/menus was so insanely small I had to select "Change high DPI settings" under "Compatibility" of the shortcut properties to fix scaling problems, let me change that back and see if it fixes it.

**Comment by ThePsycher** [comment]
No, when I click/drag an icon (in this case, a png file of a pog I made to represent an NPC), I get a banned symbol (circle with a \ through it) the moment its anywhere over the maptools window, it will not let me drop it, nor can I copy it and paste.

**Comment by Phergus** [comment]
Dropping a graphic file on the map works fine here with MT 1.6.1 and every previous version.

MapTool uses nearly every key on the keyboard for something so finding a key that MT isn't using can be challenging.  I've used Break and I believe Ctrl.

**Comment by ThePsycher** [comment]
Wish I could figure out why I lost the ability to drop a graph file on the map. I can do it within the program from the library, but not from another window/desktop. I've even tried a fresh install of MT.

As for the alternate keys for push-to-talk, neither Break nor CTRL will work, I'll try to go through each one and see if I can find one.

**Comment by ThePsycher** [comment]
Initially my push-to-talk was "MOUSE 4" - I don't think MT has that premapped. Is there some special compatibility mode I should be running it in?

**Comment by Phergus** [comment]
I don't run any kind of compatibility mode here.  Don't have any mice with extra buttons so can't test if there is an issue with mouse-buttons passing through.

Not sure what might be preventing drag-n-drop from working.

**Comment by ThePsycher** [comment]
I have a monitor with 2560x1440 resolution, I have to run the program with compatibility settings for "Change high DPI settings" so I can easily read everything, but even when I turn that off these two issues persist. It's almost as if the maptools window excludes all other programs from interacting with it.

**Comment by ThePsycher** [comment]
When I test it with keybindings I cannot find any that will work for push-to-talk once I select the MT window, they work again if I tab off.

**Comment by ThePsycher** [comment]
I cannot even paste anything I've copied outside of MT.

**Comment by ThePsycher** [comment]
Well, a small ray of silver lining, apparently voice activation will still work... it means my group will have to put up with hearing my type, but at least I'll be able to talk to them while I'm using MT. If anyone has any suggestions I'm eager to try them.

**Comment by Azhrei** [comment]
> I cannot even paste anything I've copied outside of MT.

Copy/paste uses the same transfer mechanism as drag/drop — they both query the MIME type of the data and attempt to figure out what to do with it.  Because different OSes can use different MIME types for some kinds of content, MapTool checks for many different types before failing.  However, if it can't find a matching type, the visual result is the 🚫 symbol and the "can't drop it here" result.  (Although the symbol is OS-dependent.)

Since MIME types are provided by the OS when a drag operation is started (or when a selected item is copied), it would seem there is an OS problem on your system.  What are your locale settings?  Do you have any applications installed that try to control how copy/paste works?  Or any apps that provide the ability to drag/drop in unusual ways (such as dragging from your desktop into a remote desktop window such that the data is copied to the other system)?  Those types of apps might be interfering with the assignment of the MIME type.

Since the drop operation is failing, there's probably an entry in your log file under `~/.maptool-rptools/logs` regarding the `TransferableHelper`.  The error message might give you enough information to determine the cause, but if not, posting the relevant messages here would be helpful (probably a dozen or so lines above and below the last (failed) reference to `TransferableHelper`.

**Comment by ThePsycher** [comment]
Sorry I'm a newb when it comes to the log files (can't seem to find where it is)... I found the debug command in the game, here are the results:

==== MapTool Information ====
MapTool Version: 1.6.1
MapTool Home...: C:\Users\seeje\.maptool-rptools
Max mem avail..: 7 GB
Max mem used...: 1 GB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\Users\seeje\AppData\Local\MapTool\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
PATH...........: C:\Users\seeje\AppData\Local\MapTool\app;C:\Users\seeje\AppData\Local\MapTool
Number of Procs: 4

==== User Information ====
User Name: seeje
User Home: C:\Users\seeje
User Dir.: C:\Users\seeje\AppData\Local\MapTool\app

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Intel(R) Ethernet Connection (2) I219-V
Interface Name: eth4
Address...: 192.168.1.74
Address...: fe80:0:0:0:6c78:e4f5:aa0a:4864%eth4

Host Address...: 192.168.1.74
Default Gateway: 192.168.1.1

==== Locale Information ====
Country.: United States
Language: 
Locale..: United States
Variant.: 

==== Encoding Information ====
Default Locale:   _US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 2560x1440(32)
Display 2: 2560x1440(32)

==== Internet Gateway Devices ====
Device Name.: RT-AC68P
Model Name..: RT-AC68P
Manufacturer: ASUSTeK Computer Inc.
Model Number: 3.0.0.4.376
Model Desc..: RT-AC68P
Firmware....: ASUSTeK UPnP/1.0 MiniUPnPd/1.4
External IP.: 69.180.214.128

**Comment by Azhrei** [comment]
> Sorry I'm a newb when it comes to the log files (can't seem to find where it is)... I found the debug command in the game, here are the results:

No problem!

Is this the complete listing, with no edits?  I ask because this field is weird (I'm not sure it would affect the MIME type, though):

> Default Locale: _US

Also, your **logs** directory will be found here:

    C:\Users\seeje\.maptool-rptools\logs

You can attach the entire file or just the parts I referred to above.

**Comment by ThePsycher** [comment]
To be clear, I looked in my maptools folder but there were no files nor subfolders labeled "logs"

**Comment by ThePsycher** [comment]
Found it! sec...

**Comment by ThePsycher** [comment]
[maptool.log](https://github.com/RPTools/maptool/files/4464019/maptool.log)

**Comment by Azhrei** [comment]
Yep, you found it, but that one doesn't show the drag/drop or copy/paste errors. :(

Can you clear out the **logs** directory, then execute MapTool and do some drag/drop operations that fail as you described?  And maybe a copy/paste operation that fails, just for comparison?  Please try a couple of different files — different failures may help in tracking down the problem.

**Comment by ThePsycher** [comment]
I also restarted maptools, tried dragging several items to drop (getting the "can't drop it here" result), then closed maptools. Here's that log data:

[maptool.log](https://github.com/RPTools/maptool/files/4464033/maptool.log)

**Comment by ThePsycher** [comment]
I tried dragging/dropping jpegs and pngs, several different ones. I'm not certain how to "clear out" the logs directory other than restarting Maptools

**Comment by Azhrei** [comment]
Hm.  There's nothing in there to show there was a problem. :(  I'm running out of ideas...

**Comment by ThePsycher** [comment]
Okay, I opened MT, drug from the Library and pasted two tokens into the map, unsuccessfully tried to repeat this with tokens from my desktop (same two), the copied/pasted within map the two successful tokens, then unsuccessfully tried to repeat this with the tokens on the desktop (it just pasted the last successful one two more times):

[maptool.log](https://github.com/RPTools/maptool/files/4464041/maptool.log)

**Comment by ThePsycher** [comment]
Well I'm grateful you tried. I wonder if the error message near the top of the log (the last 2020-04-10 ... entry) may be a factor?

**Comment by Azhrei** [comment]
Your last log file contains these two lines at the bottom:

> 2020-04-10 23:35:20.947 INFO  net.rptools.maptool.client.TransferableHelper - Selected: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-serialized-object;representationclass=net.rptools.maptool.model.Asset]
> 2020-04-10 23:35:25.785 INFO  net.rptools.maptool.client.TransferableHelper - Selected: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-serialized-object;representationclass=net.rptools.maptool.model.Asset]

They don't indicate any errors.

I may have you run a macro to enable more detailed logging, but I'll need to review the code first and see if I can't replicate the problem myself.  If anyone else sees an issue with the TransferableHelper code, please post here.

**Comment by Merudo** [comment]
Could there be a problem with the file you are trying to import? Maybe you could share of the image here, just so we can eliminate that possibility.

**Comment by ThePsycher** [comment]
![Abomination](https://user-images.githubusercontent.com/63482428/79042971-ac6dc100-7bc1-11ea-9c3d-e3e2d0ae2506.png)
![Aberration](https://user-images.githubusercontent.com/63482428/79042977-b263a200-7bc1-11ea-9fe9-e725990f0d7f.png)
Here are a couple of the files I'm trying to import. For the record, I can import just fine from the library within MT, it's dragging from outside the program that's an issue.

**Comment by ThePsycher** [comment]
I've been thinking back when these troubles began, it was a year ago so difficult to remember exactly when - at the time, I'd just assumed it was something broken when MT was updated, and if I wait, it'd get fixed again.

I remembered installing some Oculus programs at the time for a game (EDprofiler, etc.) that seemed a bit wonky, I've uninstalled the oculus software and edprofiler and rebooted but it apparently isn't that.

**Comment by ThePsycher** [comment]
Folks, there are six of us that use maptools on Windows 10. Five of us have the same issue where using push-to-talk on Discord won't work. For the one that works, we cannot figure out what he's doing differently (we even all tried the same push-to-talk button as him, the Z key). Please be aware this isn't an issue only I am facing.

**Comment by JamzTheMan** [comment]
I'm not able to replicate this using Windows 10, Discord, MapTool 1.6.1.

I even used the z key and even when typing in chat the z key triggered push to talk.  There must be something else going on. Have a few windows 10 users in my game that use push to talk without issue as well.

Either there is another setting in MapTool (can't imagine what) or one in Discord we're missing.

What happens if you set it to mouse3 or something? And does it only not work if MapTool has focus and works if MapTool is not in focus? (not in fullscreen are you?)

**Comment by ThePsycher** [comment]
If there's a setting we missed I'd love to find it.

We've tried mouse buttons and all sorts of keys to no effect. It won't work
either in full screen or as a window, with the caveat that if you click
away from maptools (go to another window) push to talk works again, it's
only when MT window is selected that it stops working - voice activation
still works, but some of us have screaming kids in the background so it's a
tricky workaround.

**Comment by Azhrei** [comment]
I suppose it's possible that Java is activating some graphics driver feature that when you click away is turned off.  Have you investigated this in whatever "Safe Mode" is called these days?

**Comment by ThePsycher** [comment]
Frank,

you might be on to something there... I haven't explored the Java angle (do
I have the right version installed, etc.) - I'll look into this.

**Comment by JamzTheMan** [comment]
MapTool (provided you used the installer) comes with it's own version of Java just for maptool (so other installed versions have no bearing) 

I assume the one player that this works for is also windows 10 and used the same .exe to install as the rest of you?

And long shot, does it matter if you use the web version of discord vs the installed version?

**Comment by ThePsycher** [comment]
Thinking it might be a Java issue, I went to uninstall maptools and Java,
but I could not find java in my list of installed programs. I
uninstalled/reinstalled MT 1.6.1 but I have the same issues.

HOWEVER - restarting discord as an Administrator FIXED IT!!!! Now I can use
push-to-talk while using maptools, my players will be thrilled if it works
for them too.

This did not fix my other issue, however - I still cannot drag images from
my desktop (or folders) and drop them into maptools - I get the circle with
a line through it symbol (error symbol I guess). This is whether I run as
administrator or not. Should I try and find/install the latest version of
java?

**Comment by JamzTheMan** [comment]
See above comment: MapTool comes with all the java it needs and sits in the same dir as MapTool.

**Comment by Azhrei** [comment]
I'm glad that helped.

MapTool comes with it's own JRE bundled, so there is no need to ever install or update Java on your system unless you need it for other applications.  Your other issue (drag/drop of desktop images) is, literally, a separate issue and should have it's own report here on GitHub.  In any case, there is nothing I can think of that would cause that problem, but if you file another report and include the MapTool log file we can look into it further.  (The log file will be under `~/.maptool-rptools/logs` where `~` is your home directory.)

**Comment by JamzTheMan** [comment]
Maybe you have some security issue or something.  If you install 1.5.0 do you still have the drag/drop issue?  I can't imagine what that is, we haven't changed how that has worked in forever (pre 1.4.x)

If you install TokenTool 2.1, can you drag and drop from windows dir to TT?

**Comment by ThePsycher** [comment]
Yes TokenTool still works as always ... there was an issue where it
wouldn't come up when I started it, but eventually I figured out it was
starting minimized and right-clicked to maximize to use it again, but
drag/drop works with it (thank Gawd, 50% of my encounter impacts are the
images on those pogs I create with that wonderful, wonderful tool).

Folks, I'll start a separate thread on the drag/drop issue, thank you so
much for everyone's help!

**Comment by JamzTheMan** [comment]
k, we'll close this one out. TT uses different drag n drop code but still good to know.

**Comment by sabanknight** [comment]
@thePsycher same issue with drag and drop, we use discord so no voice issues. On MY end starting maptools (NOT AS ADMIN) solved it. No clue why, Run as Admin usually solves issues, but in this case it did the opposite. Hope this helps the community figure out what is going on here, because in my limited knowledge that should not have fixed it.

**Comment by ThePsycher** [comment]
I got so excited when I saw this, sadly it didn't work for me. With or
without admin the problem of drag/drop remains the same.
