### ISSUE TITLE
Theme issues - RT Default Dark unreadable text in Map and Draw Explorer

### ISSUE THREAD

**Issue by DethangelsShadow** [RPTools/maptool#1513]
**Describe the bug**
Map Explorer items are white on white unless selected

**To Reproduce**
1. Go to Map Explorer (with tokens or items) or Draw Explorer (and 'draw' something)
2. Folder names are white on white.  IClick on any folder, all items except currently selected are white on white.

**Expected behavior**
Explorer items should be visible.  

**Screenshots**
![image](https://user-images.githubusercontent.com/63486693/79035381-f5a31e00-7b8b-11ea-9f20-55532255b0d0.png)

![image](https://user-images.githubusercontent.com/63486693/79035387-0784c100-7b8c-11ea-86cc-9a5494a344f5.png)

**MapTool Info**
- Version: 1.6.1
- Install: Upgrade

**Desktop (please complete the following information):**
Windows 10 Pro

**Additional context**
The text colors and background colors need to be adjusted.  Some File menu items are black on dark grey as well with this theme.
![image](https://user-images.githubusercontent.com/63486693/79035424-7c57fb00-7b8c-11ea-8f0c-9707c8eea668.png)

**Comment by nmeier** [comment]
The menu looks better for me by changing the order of when the theme is loaded (before the menu is created)

![image](https://user-images.githubusercontent.com/312857/79627728-bf741a00-8108-11ea-92b0-6b4798c01c93.png)

See patch below - I kept the order as is for Mac as I can't test on that.


```
Index: src/main/java/net/rptools/maptool/client/MapTool.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/net/rptools/maptool/client/MapTool.java	(revision ee6c30462c16b88848855891cd0888f6f90d9f17)
+++ src/main/java/net/rptools/maptool/client/MapTool.java	(date 1587183296990)
@@ -1734,6 +1734,7 @@
         UIManager.setLookAndFeel(AppUtil.LOOK_AND_FEEL_NAME);
         menuBar = new AppMenuBar();
         OSXAdapter.macOSXicon();
+        loadTheme();
       }
       // If running on Windows based OS, CJK font is broken when using TinyLAF.
       // else if (WINDOWS) {
@@ -1742,29 +1743,9 @@
       // }
       else {
         UIManager.setLookAndFeel(AppUtil.LOOK_AND_FEEL_NAME);
+        loadTheme();
         menuBar = new AppMenuBar();
       }
-      // After the TinyLAF library is initialized, look to see if there is a Default.theme
-      // in our AppHome directory and load it if there is. Unfortunately, changing the
-      // search path for the default theme requires subclassing TinyLAF and because
-      // we have both the original and a Mac version that gets cumbersome. (Really
-      // the Mac version should use the default and then install the keystroke differences
-      // but what we have works and I'm loathe to go playing with it at 1.3b87 -- yes, 87!)
-      File f2 = AppUtil.getThemeFile(AppUtil.getThemeName());
-      // File f = AppUtil.getAppHome("config");
-      // if (f.exists()) {
-      // File f2 = new File(f, "Default.theme");
-      if (f2.exists()) {
-        if (Theme.loadTheme(f2)) {
-          // re-install the Tiny Look and Feel
-          UIManager.setLookAndFeel(AppUtil.LOOK_AND_FEEL_NAME);
-
-          // Update the ComponentUIs for all Components. This
-          // needs to be invoked for all windows.
-          // SwingUtilities.updateComponentTreeUI(rootComponent);
-        }
-      }
-      // }
 
       com.jidesoft.utils.Lm.verifyLicense(
           "Trevor Croft", "rptools", "5MfIVe:WXJBDrToeLWPhMv3kI2s3VFo");
@@ -1844,4 +1825,28 @@
         });
     // new Thread(new HeapSpy()).start();
   }
+
+  private static void loadTheme() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
+    // After the TinyLAF library is initialized, look to see if there is a Default.theme
+    // in our AppHome directory and load it if there is. Unfortunately, changing the
+    // search path for the default theme requires subclassing TinyLAF and because
+    // we have both the original and a Mac version that gets cumbersome. (Really
+    // the Mac version should use the default and then install the keystroke differences
+    // but what we have works and I'm loathe to go playing with it at 1.3b87 -- yes, 87!)
+    File f2 = AppUtil.getThemeFile(AppUtil.getThemeName());
+    // File f = AppUtil.getAppHome("config");
+    // if (f.exists()) {
+    // File f2 = new File(f, "Default.theme");
+    if (f2.exists()) {
+      if (Theme.loadTheme(f2)) {
+        // re-install the Tiny Look and Feel
+        UIManager.setLookAndFeel(AppUtil.LOOK_AND_FEEL_NAME);
+
+        // Update the ComponentUIs for all Components. This
+        // needs to be invoked for all windows.
+        //SwingUtilities.updateComponentTreeUI(rootWindow);
+      }
+    }
+    // }
+  }
 }

```

**Comment by cwisniew** [comment]
@nmeier The menu looks ok as is on a Mac so this should hopefully fix the menu part of this issue. Create a pull request and claim some credit :)

**Comment by nmeier** [comment]
testing a bit more, there are still problems, beyond the menu that made me happy. Will look a bit deeper.

**Comment by Phergus** [comment]
I seem to recall there were issues with the them and the Map Explorer and Draw Explorer panels.

**Comment by nmeier** [comment]
So the TokenPanelTreeCellRenderer fudges with hardcoded colors to make non-visible tokens show up differently. A good intent, but badly implemented as it clashes with the look and feel.

I can easily make it go away
![image](https://user-images.githubusercontent.com/312857/79639187-1c4af100-8158-11ea-8b5a-c6c7c513013c.png)

I'm thinking a different indicator but color would be better - bold/strikethrough/italic for example to indiate hidden.  Overriding component colors was du jour in 2015.

Any suggestions?

**Comment by Phergus** [comment]
I would go with italic for tokens that aren't visible but I'm not sure how distinguishable that will be at a glance.  The color highlighting difference really stands out.

**Comment by nmeier** [comment]
how about italicize and shading the image? (bottom two are not visible to players)

![image](https://user-images.githubusercontent.com/312857/79641812-c3835480-8167-11ea-8bce-162df5d3756a.png)

**Comment by nmeier** [comment]
both explorers 
![image](https://user-images.githubusercontent.com/312857/79642369-0e529b80-816b-11ea-8f85-cecbb0abba10.png)

**Comment by Phergus** [comment]
Tested new code with RT Default Dark theme.  Noted issues with theme have been addressed.
