### ISSUE TITLE
New parameter to dialog() and frame() to prevent scroll change on reload

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1528]
**Is your feature request related to a problem? Please describe.**

In the words of @mrkwnzl: 

> I use a frame for a character sheet. To update the sheet, I just call the macro again. Problem is, if I scrolled down in the frame, it jumps back up. Is there a way to save the current scroll position of the frame?

There should be a way for the previous scroll position to be remembered when updating a frame or dialog with new html content.

**Describe the solution you'd like**
An extra parameter to `dialog()` and `frame()`, `scrollreset`, which if set to `0 (false)` keeps the same scrolling it had previously.

**Comment by Phergus** [comment]
Should it default to `false`?

**Comment by Merudo** [comment]
I think it should default to `true` for compatibility purposes, but it could go either way really.

**Comment by Phergus** [comment]
Not sure myself.

**Comment by mrkwnzl** [comment]
I see the point of compatibility, but from an end-user perspective, I can’t really think of a reason why it shouldn’t default to `false`. 

It would mean that the default behavior of frames and dialogs would be that they don’t change if they reload (by scrolling back up), while I need to tell it to reset the scroll position on a reload. Seems more intuitive to me.

**Comment by Merudo** [comment]
What should be the behavior if the frame is closed, then reopened with new content? Should the default be to scroll back to the previous location?

**Comment by mrkwnzl** [comment]
Intuitively, I would expect new frames (frames with different title) to start at the top. 

I don’t really have a strong intuition about re-opened frames, but I think it would be nice to have it remember the old position.

**Comment by Merudo** [comment]
PR #1531 adds the feature, with `scrollreset` set to `false` (scrolling is remembered) as a default.

**Comment by Phergus** [comment]
@Merudo   Doesn't seem to be working with dialog5 or frame5.  Works with the old ones.
```
[frame5("Frame5 Test","width=300; height=200; scrollReset=0"): {
<html>
  <body>
  <table border="1">
  <tr><td><pre>It is an ancient Mariner,
And he stoppeth one of three.
'By thy long grey beard and glittering eye,
Now wherefore stopp'st thou me?
</pre></td></tr>
  <tr><td><pre>The Bridegroom's doors are opened wide,
And I am next of kin;
The guests are met, the feast is set:
May'st hear the merry din.'</pre></td></tr>
  <tr><td><pre>He holds him with his skinny hand,
'There was a ship,' quoth he.
'Hold off! unhand me, grey-beard loon!'
Eftsoons his hand dropt he.</pre></td></tr>
  <tr><td><pre>He holds him with his glittering eye—
The Wedding-Guest stood still,
And listens like a three years' child:
The Mariner hath his will.</pre></td></tr>
  <tr><td><pre>The Wedding-Guest sat on a stone:
He cannot choose but hear;
And thus spake on that ancient man,
The bright-eyed Mariner.</pre></td></tr>
  <tr><td><pre>The Wedding-Guest sat on a stone:
He cannot choose but hear;
And thus spake on that ancient man,
The bright-eyed Mariner.</pre></td></tr>
  <tr><td><pre>The ship was cheered, the harbour cleared,
Merrily did we drop
Below the kirk, below the hill,
Below the lighthouse top.</pre></td>
  </tr>
  </table>
  </body>
</html>
}]
```

Also passing in a `scrollReset=false` errors out in a non-helpful way.

**Comment by Merudo** [comment]
Oops! PR #1533 fixes this.

**Comment by Phergus** [comment]
scrollReset option now working with frame5/dialog5.
