### ISSUE TITLE
Replace Apache Commons with version 3.2.2 or greater

### ISSUE THREAD

**Issue by lynxworx** [RPTools/maptool#153]
Maptools is using Apache Commons version 3.2.1, which has the COLLECTIONS-580 security vulnerability -- see https://commons.apache.org/proper/commons-collections/release_3_2_2.html

Since this is a remote execution vulnerability, the Commons Collections library dependency should be bumped up to 3.2.2 ASAP.

**Comment by lynxworx** [comment]
This might be a particularly severe issue -- I haven't looked at the client/server communications code, but if it's serialized objects that are being slung between the endpoints, then this is definitely a hot vulnerability.

**Comment by Azhrei** [comment]
Thanks for the note.  I’ll be reviewing the libraries and updating the ones that need it, hopefully with a build by the end of the week or over the weekend.  Thanks again. :)

**Comment by Phergus** [comment]
OBE - We've moved on to 4.1.
