### ISSUE TITLE
Button label cleanup:  Token Editor has "Close" and it should be "Cancel"

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#1538]
**Describe the bug**
The Token Editor dialog (the dialog that opens when double-clicking a token), shows "OK" and "Close" in the bottom right; the "Close" should be "Cancel".

**To Reproduce**
1. Open the Token Editor dialog by double-clicking a token.
2. Modify a field (any field).
3. Click the "Close" button.
4. Re-open the editor and note that the field value did not change.

**Expected behavior**
If "Close" is going to function as cancel, then it should be labeled "Cancel". :)

**MapTool Info**
- Version: 1.5.14+

**Comment by Merudo** [comment]
PR #1579 fixed this.

**Comment by Phergus** [comment]
Tested.  Dialog now has Cancel instead of Close.
