### ISSUE TITLE
AI movement should be enforceable via Start Server options

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#1539]
**Describe the bug**
The AI button routes tokens around obstacles, but clients can turn it off without the approval (or even knowledge of) the GM.

**Expected behavior**
The GM should be able to enforce the constraints they want to use for their campaign.

**MapTool Info**
- Version: 1.5.14+

**Comment by Merudo** [comment]
The A* timeout delay should be configurable, either on the server side or on the client's.

**Comment by Azhrei** [comment]
Not just the timeout, but whether the GM even wants it used in their game.

**Comment by JamzTheMan** [comment]
You really should try 1.6.1 @Azhrei. Just saying...

**Comment by Azhrei** [comment]
I have it installed.  Are you saying it already does enforce it?  The Start Server doesn't imply that, and the tooltip doesn't either.  This page says it works the exact opposite of this bug report:  http://lmwcs.com/rptools/wiki/AI_Pathfinding

![Screen Shot 2020-04-14 at 12 13 06 AM](https://user-images.githubusercontent.com/4120974/79185540-2cc03c00-7de5-11ea-8b04-f059d0c458d8.png)

**Comment by JamzTheMan** [comment]
#1287 

I didn't make it a server start option so the GM can turn it on and off during game. Seemed like a better choice,  no?

**Comment by Azhrei** [comment]
Ah, so the docs are just wrong.  Cool.  I can handle that. 👍

And while @Merudo is right that the timeout should be configurable, that's a separate issue.

**Comment by JamzTheMan** [comment]
Yea, the wiki is a release behind, we can ask @melek to give it an update please? :)

**Comment by JamzTheMan** [comment]
@Merudo re time out, yes but if you open an issue for this, please consider a shorter time out also limits MapTool finding a valid route as well. Only giving it, say, 100 ms may lot allow it to find a valid route that is only 300 ft away for instance and users may not understand that compromise.

A more important fix is for it to better kick out on moves it knows is invalid like starting our ending on solid vbl and gray the token or something. Also to not allow it to move through FoW.  

Things I had planned for in the future...

**Comment by melek** [comment]
Will do. 

Looks like the features that are missing are:
* VBL AI Blocking Toggle
* GM controlled AI Toggle

I'll snoop around the github issues for any other details sometime this week and update the article. :)
