### ISSUE TITLE
Feature Request: Make it easier for the DM to see at a glance which tokens are hidden from players

### ISSUE THREAD

**Issue by lynxworx** [RPTools/maptool#154]
More than once I've "surprised" my players by having them getting jumped by enemies they couldn't see on the table, because I had unchecked the "Visible to Players" menu instead of hiding them behind the fog of war.  The only way that I can see right now to tell if a token is player visible is by either clicking on the token and making sure the checkmark is in place, or by switching to "view as player".

What would be nice is if tokens not visible by players would have their colors desaturated until they are made visible, that would make it easier to notice this at a glance.

**Comment by dorpond** [comment]
During my games, I just hit Control-T (View->Show Token Names) to show the labels of the assets on the map. Tokens that are not visible will be in grey. It is a real quick way of checking.

But I do like the suggestion, thanks!

**Comment by JamzTheMan** [comment]
Yea, I currently use a macro that sets the visibility and adds a "state" so I can see it.

If we add an "effect" i.e. desaturation, is this something you would want on in ALL situations? Does it need a separate option/toggle? Any other ideas to denote such tokens other than color saturation?

**Comment by lynxworx** [comment]
Personally, I'd be fine with it in all situations, but I think it would be good to make it a preference item, as it may not suit everyone's playing styles.

**Comment by Phergus** [comment]
@Azhrei   Your response suggests that this feature will not be implemented at this time.  If other action is needed please indicate what.

**Comment by Azhrei** [comment]
I don't see a need as we do have a solution that works, as dorpond points out; even Jamz' approach of using states also works.  I think adding more info to the menu option tooltip is enough.  Just IMO, of course.

**Comment by Phergus** [comment]
Okay. Re-focusing request on tooltip update.

**Comment by Phergus** [comment]
Add additional tooltip text explaining the color combinations used to the Show Token Names option of View menu.

- Visible NPC - White on Blue
- Visible PC - Black on Light Grey
- Not Visible Token - White on Dark Grey
