### ISSUE TITLE
getTablePickOnce and setTablePickOnce functions returning strings instead of 0 and 1

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1548]
**Describe the bug**
Both functions return a string "true" or "false" instead of the 0 or 1 expected by conditionals in macros.

**To Reproduce**
1. Run `[r: getTablePickOnce("D6")]` (assumes default tables)
2. Get the string "false" back.

**Expected behavior**
Expect 0 or 1

**MapTool Info**
- Version: 1.5.14+

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Noticed issues with older table functions as well:
* getTableAccess
* getTableVisible
* setTableAccess
* setTableVisible

All were returning strings instead of BigInteger 0/1.

Tested all functions with following code constructs:
```
[r, if(getTablePickOnce("D6") == 1), code:{
		True
	};{
		False
}]
```
```
[r, if(getTablePickOnce("D6")), code:{
		True
	};{
		False
}]
```
```
[h: x = getTablePickOnce("D6")]
[r, if(x == 1), code:{
		True
	};{
		False
}]
```
```
[r: x = if(getTablePickOnce("D6"), "True", "False")]
```
```
[r: x = if(getTablePickOnce("D6") == 1, "True", "False")]
```

**Comment by Merudo** [comment]
Tested functions `getTablePickOnce`, `setTablePickOnce`, `getTableAccess`, `getTableVisible`, `setTableAccess`, and `setTableVisible`. Functions now return `1` and `0` instead of `true` and `false`.
