### ISSUE TITLE
Frame5 / Dialog5 : console.log doesn't work during page load

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1551]
**Describe the bug**
The `console.log` command doesn't properly print the message to the chat box if it is executed during the loading of a page.

**To Reproduce**
1. Run this script:

```
[frame5("test"):{
<script>console.log('this will not show')</script>

<button onclick="console.log('but this does')">Click me</button>
}]
```
2. Notice that "this will not show" is not printed to the chat window.
3. Click on the button. The message is printed normally.

**Expected behavior**
The `console.log` command works in javascript executed on the page load.

**MapTool Info**
- Version: 1.6.1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 10

**Additional context**
The issue is caused by the Java Bridge not being setup early enough. However, I found a workaround on stackexchange that will solve this issue.

**Comment by Merudo** [comment]
PR #1552 fixes this issue.

**Comment by Phergus** [comment]
Tested. Work as expected.
