### ISSUE TITLE
Internationalize Abeille forms

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1553]
**Is your feature request related to a problem? Please describe.**
Since the amazing crowdin support  was added, the translation of MapTool into other languages has progressed tremendously.

However, Abeille forms do not support i18N translation, and remain English-only.

**Describe the solution you'd like**

A way for Abeille forms to automatically use i18N translation.

**Completed:**
Token Popup Menu
Library images mouseover
Autosave message

**Dialogs:** Connect to Server, Connection Information, Start Server, Edit Token, Adjust Grid control, Campaign Properties, Map Properties(New/Edit), New Token, Preferences, Campaign Export, Update MapTool, Add Resources, Transfer Window, About, Layer Selection, Macro Button, Chat Window, Adjust Map Board, Paint Chooser, Image Chooser, Performance Window, System Info, Log Console, Table Window, Edit Table, Export Screenshot

**Comment by Azhrei** [comment]
There's already initial support for this.  Check out AbeillePanel.  Trevor's plan was to add an auto-binding feature.  Just name the field in Abeille the same as the property key and prefix it with "@" and it would do the lookup.

I played with it for a very short time when I was just learning the MT code base, but I couldn't get it to work the way I thought it should.

**Comment by Azhrei** [comment]
Ah, looks like you found it!

**Comment by Merudo** [comment]
I thought `@` was only to bind data?

**Comment by Merudo** [comment]
PR #1554 implements translation for Abeille forms in general, and specifically for New Token dialog.

It doesn't use the `@` binding though, instead using `form.getFormAccessor` to get the form components and replacing their text. I wonder what is most efficient?

**Comment by Azhrei** [comment]
You could be right.  I last looked at this about 12 years ago... :-/

**Comment by Merudo** [comment]
PR #1557 adds support for more form components, and add I18N support to the Connect to Server form.

**Comment by Merudo** [comment]
PR #15588 adds I18N support to the Server Info dialog.

**Comment by Merudo** [comment]
I believe all the Abeille forms currently in use now support I18N.

**Comment by Phergus** [comment]
Tested in French.  Unless I missed some, text in all dialogs was localized.
