### ISSUE TITLE
Campaign default property bugged with {} assignment

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1560]
**Describe the bug**
Setting up a default property value with `{}` assignment doesn't work anymore since 1.5.12.

**To Reproduce**
1. Set the following default property:
```
var1:10
*var2:{var2=var1}
```
2. Put your mouse over a token. You will see `{"var1":"var2"}` in the stat sheet.
3. In 1.5.10, the stat sheet shows `10`

Note that the bug doesn't occur if there is no variable assignment within the `{}`. So, 

```
var1:10
*var2:{var1}
```
works fine.

**Expected behavior**
MapTool returns the value, not the assignment code.

**MapTool Info**
- Version: 1.5.12+
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by bubblobill** [comment]
Does this work with {var2}={var1} or [r:{var2}={var1}]?

**Comment by Merudo** [comment]
Don't work:
`*var2:{var2}={var1}`, creates a loop

Work: 
`*var2:[r:{var2}={var1}]`
`*var2:[r:var2=var1]`

**Comment by Phergus** [comment]
This didn't really work in 1.5.10 either.   If you have your properties defined as in the OP but no default for `prop1` then when you open the Edit Token dialog to put in a value for `prop1` the formula in `prop2` is set to empty.  Now it doesn't matter what `prop1` is.

**Comment by Merudo** [comment]
Discussion on the forum: https://forums.rptools.net/viewtopic.php?f=6&t=28676

**Comment by Merudo** [comment]
I think the problem is that the `{a=b}` type of campaign properties are confused for a json object `{a:b}`.

**Comment by Merudo** [comment]
PR #1871 fixes this.

The order of operation was reversed - the property should be parser as code and then potentially parsed as a json - doing it in the opposite order leads to `{a=b}` being parsed as a json.

**Comment by Azhrei** [comment]
Is this the only place where code can be enclosed in braces?  Everywhere else requires the use of `[r: ...]` to achieve the same effect, right?

If so, why even allow the braces here?

**Comment by Merudo** [comment]
> Is this the only place where code can be enclosed in braces? Everywhere else requires the use of `[r: ...]` to achieve the same effect, right?
> 
> If so, why even allow the braces here?

Nope, everywhere else `[r: ]` and `{}` give identical results.

**Comment by Phergus** [comment]
@Azhrei I think that at one time square brackets weren't allowed in properties and you had to use the curly braces but there's probably a 50/50 chance my recall is faulty on that.  I'm not even sure the curly brace usage is documented on the wiki.

**Comment by Merudo** [comment]
They are.

https://lmwcs.com/rptools/wiki/Macros:Roll:types

**Comment by Phergus** [comment]
Cool.  Hooray for us!

**Comment by Phergus** [comment]
Tested.  Auto-calculated properties with/without assignment, using square & curly braces, working as expected.
