### ISSUE TITLE
Feature Request: Large text information storage solution per token.

### ISSUE THREAD

**Issue by lynxworx** [RPTools/maptool#158]
Well, let me explain things a bit.  In my WEG Star Wars game, I've been using JSON to encode a LOT of information per token -- the character's attributes, skills, force stats, force skills, weapons, etc.  Really magnificent for that as I've been able to make much of the game mechanics a simple button push for my players.

However, I've been having to use the Players Notes box to store the character's JSON data into.  While it works, that doesn't seem like the proper role for the Player's Notes area, and the GM Notes area certainly isn't appropriate since I want my players to be able to edit their JSON data.

So based on the above description, can we get the ability to add more large-text (multi-line, much more then what a property can hold) in some macro-addressable format that doesn't use the player/gm notes blocks?

In fact, a token config tab which has the ability to add multiple multi-line texts, keyed by a name, would be great, because then I could simplify my JSON by looking up a text block by name (say, one  named "Attributes", another named "Weapons") so I wouldn't need to crush every bit of data into one JSON document, as smaller JSON makes it a lot easier to find where I omitted a character.

**Comment by Phergus** [comment]
Since you aren't really storing "notes" in the notes field wouldn't it make more sense to store your JSON data in Token properties and then use Frames or Dialogs to allow the users to view/edit the data?  This way they wouldn't have to edit JSON data directly with all the potential for typos invalidating it.  Instead use either the input() macro or HTML forms such that you could control and error check the input.

In your example you would add an Attributes and a Weapons property to the Token Properties.

**Comment by lynxworx** [comment]
Well, properties have a maximum length do they not?  I think I remember that being a challenge when I was running a D&D4e campaign and was encoding weapon information in a semicolon-delimited properties list (was not using json at the time)

In my current D6 Star Wars game, I'm encoding character information like the following:

```
  "Attributes" : {
     "Dexterity" : {
        "DieCode" : { "Die" : "3", "Pips" : "0" },
        "Skills" : {
          "Brawling Parry" : { "Die" : "5", "Pips" : "0", "isAttackSkill" : "false"  },
          "Vehicle Blasters" : { "Die" : "3", "Pips" : "0", "isAttackSkill" : "true"  },
        }
     },
     "Knowledge" : {
        "DieCode" : { "Die" : "2", "Pips" : "0" },
        "Skills" : {
           "Planetary Systems" : { "Die" : "5", "Pips" : "0" },
        }
     },
<snip>
}
```

While all the human readable formatting could be eliminated when dropped into a property, I'd like to preserve it.  So presently, the token's Player Notes is the only option available that I could do that with.

**Comment by Phergus** [comment]
There may be a limit but I would expect it to be fairly large.   I currently have 18K worth of weapon info in a property on one lib token.  That's for 74 weapons as JSON objects with about 240 characters in each.

Your snippet is only 500 chars and would have to be 36 times larger to equal what I have in the one property so I don't think you are going to hit a limit with just your character attributes.

Using a TextArea in an HTML form would still allow you to edit the contents in the human-readable format you are using.

Not that having the ability within MapTool to easily pull up a editable large text area dialog/window wouldn't be handy.

**Comment by Azhrei** [comment]
Be aware that the current implementation copies the entire Token across the network to all clients when the Token is dragged by anyone (GM or Player), so storing large amounts of data there is not ideal.

You might have better luck discussing this kind of thing in the MapTool (or MapTool 1.4) subforum on our website at forums.rptools.net.  You'll get a lot of ideas from some _very_ experienced people about what they've tried and what works well for them.  Summary:  you're not the first to want to do this. :)

**Comment by Phergus** [comment]
No further comments received.  Closing.
