### ISSUE TITLE
Restrict portrait in overlay to maximum image size when resizing with SwingUtil.constrainTo

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1583]
**Is your feature request related to a problem? Please describe.**

Currently the statsheet overlay with portrait turned on is forced to a static value from AppPreferences.getPortraitSize. I've bumped up that setting to a large value so I can get a decent sized portrait to show up (larger than 175). This works for those pics that are large enough:

![image](https://user-images.githubusercontent.com/312857/79521961-692faa00-8028-11ea-8ca4-40033af798ca.png)

Smaller images get stretched to my new limit of 600 though, which leads to ugly stretching.

![image](https://user-images.githubusercontent.com/312857/79521854-308fd080-8028-11ea-9808-8e69ca8cf7ce.png)

**Describe the solution you'd like**

I think it would be better if the portrait doesn't get stretched beyond what its native resolution is. In my 2nd case above

![image](https://user-images.githubusercontent.com/312857/79522037-a1cf8380-8028-11ea-980f-b244a2bbe246.png)

**Describe alternatives you've considered**

There could be another option in the preferences but that dialog seems overloaded already.

**Additional context**

I have a fix ready and figuring out how to make that a pull request.

**Comment by Phergus** [comment]
Preferences does have a size setting for the portrait.
![Screenshot 2020-04-16 19 35 14](https://user-images.githubusercontent.com/34379254/79522727-b48e8c00-8019-11ea-8df5-96dc05dd7541.png)

In any case, it definitely shouldn't scale it past native size.

**Comment by Phergus** [comment]
Before submitting a PR a couple notes.
* Create a local branch off of _**develop**_ to do your work.
* When you submit your PR target **develop** and make sure you have _Allow edits from maintainers._ checked.

Read over these guidelines:
https://github.com/RPTools/maptool/blob/master/doc/Code_Style_and_Guidelines.md

**Comment by JamzTheMan** [comment]
So. If I'm on a hidpi monitor and my gm used portraits of low resolution, you are saying I can not scale those up so I can see them??

**Comment by Merudo** [comment]
Maybe make it a per-token option? The picture of the token could either "scale-down" to fit the specified size (lowers its size until it fits inside the panel, but not enlarge it). Or , it could be forced to take the exact size (current behavior).

**Comment by Phergus** [comment]
If it was made a Token option, the Jamz would still lack control over the portrait size on his display.

Could also be an preference option to go along with the setting for portrait size.

_Enlarge undersized Portraits._

I'm guessing that folks will then want:

_Use native size for Portraits._

**Comment by nmeier** [comment]
There could be more options but one could argue the GM should have sufficient resolution for hi def players.

How about two boxes Statsheet portrait size [Min] and [Max]. Pictures are scaled at min to what the hiresolution player has, and restricted by max. One could fit two text boxes into the space where there's currently one.

**Comment by JamzTheMan** [comment]
Right now `Statsheet Portrait Size` is used as a set size and 0 removes the image.

How about just allow `200+`  which would set the portrait to 200 OR what ever the images size is

or maybe allow `min(200)` and `max(200)` to set the portrait equal to the image size with a min or max of x?

or maybe `100-300` uses portrait image size with a min of 100 and max of 300?

Lots of options...

**Comment by JamzTheMan** [comment]
> There could be more options but one could argue the GM should have sufficient resolution for hi def players.

This same argument could be used against your example. It wouldn't be "ugly stretching" if the GM supplied appropriate 600x600+ hidpi images.

**Comment by nmeier** [comment]
> Right now `Statsheet Portrait Size` is used as a set size and 0 removes the image.

Is 0 needed as a value? There's also a setting for having to use shift to reveal the portrait. One could use the number as before for a target sizE to scale to and use 0 as use-picture-native-size.

A range sounds easy enough though, could make this 64-200 as suggested yes

**Comment by Phergus** [comment]
This still needs to be resolved.  Here are the options:

1. Revert change - issue will be pushed to next release
2. Change Prefs to accept two values in current size field.  As it isn't actually a "range", would prefer to see something like `80:250` but either way it is probably prone to user errors.
3. Change Prefs to have both Min & Max size fields

I'll need a PR doing either option 2 or 3 in the next couple days or we default to option 1.

**Comment by nmeier** [comment]
Ultimately I think the range is too complicated. Vote to stay with #1 and stick with the old behavior, right 50% of the time.

**Comment by nmeier** [comment]
btw realized why the scaled images bug me - the handout and the token draw doesn't scale for quality but for speed. See the difference in handout and a couple of tokens - LEFT as per current maptool, RIGHT when I tweak the graphics2d settings

![image](https://user-images.githubusercontent.com/312857/80329111-4a42cc00-880f-11ea-9077-2b348656a647.png)

There's code all over the place that modifies graphics2d - looking into whether there's a good place to tweak the appropriate hint that's currently missing

**Comment by Phergus** [comment]
@nmeier Do you have Display Scaling enabled in Windows?

**Comment by nmeier** [comment]
@Phergus  don't have that on. Confirmed the issue is the rendering hints that are not applied in token rendering and the portrait floating view https://github.com/RPTools/maptool/issues/1709

For this here, let's roll back. Don't think we need to keep this request for a flip in sizing behavior to stay open.

**Comment by Phergus** [comment]
Roger that.  This can be explored later after the move to Java 14 and in the context of some of the newer features such as overlays.
