### ISSUE TITLE
Feature Request: Macro lint

### ISSUE THREAD

**Issue by lynxworx** [RPTools/maptool#159]
Debugging macros can be ... quite an exercise at times.  Usually it's a misplaced comma or something, and the message produced doesn't really laser into the point of failure.

What would be nice is, in the macro editor, there to be a lint button, which parses the macro, and identifies (by changing text color to red) parts of the macro that would fail compile when executing the macro.

Sure this won't find runtime bugs, but half of the bugs in my macro code tend to be syntax errors, which this would be a great help for taking care of!

**Comment by Phergus** [comment]
With the new editor in 1.5.0 is this still needed?

**Comment by Phergus** [comment]
No response.  Closing.
