### ISSUE TITLE
Allow macros to clear Token Portrait and Handout

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1597]
**Is your feature request related to a problem? Please describe.**

These optional token images cannot be reset to empty 

```
  private static void setPortrait(Token token, String assetName) throws ParserException {
  private static void setHandout(Token token, String assetName) throws ParserException {
```

since getMD5Key(assetName, SET_PORTRAIT) ends up throwing ParserException.

`Argument number 1 invalid argument type for function "setTokenHandout".
`
This shows when copying handout/portrait from one to another for automation, where the source has no image set

`  setTokenHandout( getTokenHandout("",sourcetokenid) , desttokenid)`

**Describe the solution you'd like**

While macros can check the result of grabbing an image from one token before handing it to another I think something like this should inherently be allowed:

`  setTokenHandout( getTokenHandout("")  )`

Suggest to fix setTokenPortrait|setTokenHandout to interpret an empty assetName as desire to clear and do the needful to avoid futile MD5Key look-up.

**Describe alternatives you've considered**

Considered changing TokenImage.getMD5Key() but expecting a valid asset there seems a reasonable check to keep.

Considered two new macro APIs deleteTokenHandout/deleteTokenPortrait but that is verbose.

If someone knows why these setters need to continue to throw that exception would be good to know.

**Additional context**

2 line fix, provided 

[updated post feedback]

**Comment by Phergus** [comment]
What is the use-case for having a token with no image?

**Comment by nmeier** [comment]
ok, the example is not the best - the main issue is a token without portrait or handout. Those two cannot be unset even though one can do that through the UI

**Comment by Phergus** [comment]
Seems reasonable to want to remove handout or portrait images from tokens but removing the actual token image isn't going to happen.

Please update your code to remove the changes to setImage() and update PR.

**Comment by Merudo** [comment]
Maybe removing the main token image could cause it to be replaced by a blank image of predefined size? I'm concerned about the token becoming unselectable.

**Comment by Phergus** [comment]
And the many places in the code where the image for token is checked for size or overlap or to draw a selection box or displayed in the Edit Token dialog or Initiative panel or chat window or...

**Comment by nmeier** [comment]
PR updated, this allows token handout and portrait to be cleared only

**Comment by Phergus** [comment]
Tested.  Macro functions `setTokenPortrait("")` and `setTokenHandout("")` now clear the respective images from the token.
