### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lynxworx** [RPTools/maptool#160]
No one likes legalese, myself included, but anyone who's looking to become involved in any open source project really should understand what license agreement a project is abiding by before they even start looking at the source code. 

Quickly peeking at the java source heder (or at least the one I looked at, AppActions.java) it looks like it's Apache Commons License V2 -- it would be great to have a LICENSE file at the project root and mentioned in the README.md file that identifies the project's license without looking at the source code.

**Comment by JamzTheMan** [comment]
@Azhrei FYI: I just did this for my fork, all you do is on master, create new file in GitHub, type LICENSE for name and it will prompt you to pick/add a license. It then will be tagged in GitHub and searchable.

**Comment by Azhrei** [comment]
Sounds good.  I’ll add it to the master branch, since there’s no reason to wait.  Thanks for checking.

**Comment by irisiflimsi** [comment]
Should be handled with care, since we have several licenses at work (at least Apache, LGPL, APGL). Unless we have someone versed in legalese, we should stick with what we have. By putting up a top-level license--Y(et)A(nother)L(icense)--we don't simplify things. Maybe just refer to https://github.com/RPTools/maptool/blob/master/doc/LICENSE in the README.md?

**Comment by JamzTheMan** [comment]
It's the same license in readme and GitHub is tagging the same. I believe we are using same one now in all the new code...

**Comment by irisiflimsi** [comment]
I just saw https://github.com/RPTools/maptool/issues/59 too. If we use the same license in the *new* code, doesn't mean it applies to the *old* code we still deliver. It also doesn't apply to all the dependencies. (I also found an GPL and MIT licenses in our repo in the mean time.)

**Comment by Azhrei** [comment]
There's a plan to include a gradle task that updates the license in every source file every time a build is done.  Once that is integrated, updating the license information will be automatic and a single PR will fill all references.  But Jamz is working on AppVeyor integration right now and I don't want to distract him (he's our gradle guy!).
