### ISSUE TITLE
Pressing + and - in a frame5 textbox zooms the map

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1614]
**Describe the bug**
Pressing a `+` or a `-` while typing in an `<input>` or `<textarea>` of `frame5` can cause the map to zoom in and out.

**To Reproduce**
1. Run the macro: `[frame5("Test"):{<input type="text">}]`
2. Click on the map, and press `+` or `-` so it zooms
3. Click on the textbox, and press `+` or `-`
4. Notices how the map zooms

**Expected behavior**
No zoom if typing into `frame5`.

**MapTool Info**
- Version: 1.6.1, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Version: 10

**Comment by Merudo** [comment]
PR #1618 fixes this.

**Comment by Phergus** [comment]
Tested new code.
Hitting +/- keys when frame has focus no longer zooms map view.
Keys still work when map has focus.
