### ISSUE TITLE
Campaign properties dialog is too wide and doesn't allow for translation of instructions for light tab

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1629]
**Describe the bug**

The Campaign properties dialog has two issue

1) it's around 1600 pixels wide when opening after Swing has pack'd it. This is due to a label being used for the sight instructions

![image](https://user-images.githubusercontent.com/312857/79702109-47c0ff00-8270-11ea-849a-d8c391c085c7.png)

2) the light instructions cannot be localized - they're embedded in the properties dialog xml-file

**To Reproduce**

Open the campaign properties - notice that the dialog is excessively wide (wider than my laptop display at 1600w). Notice that the html for light instructions are in an xml file (whereas the sight instructions are in the language properties file). When using a the dark layout theme the dialog is another bunch of pixel wider due to some decorations.

**Expected behavior**

The ui element for explaining the light and sight syntax should be the same - a disabled, scroll-enabled editor pane.

**Screenshots**

see above

**MapTool Info**
- Version: 1.6.1 branched
- Install: ANy

**Desktop (please complete the following information):**
 - OS: At least Windows
 - Version 10

**Additional context**

Preparing a pull request for both.

**Comment by nmeier** [comment]
Proposal how this looks when both tabs are layout the same way

![image](https://user-images.githubusercontent.com/312857/79702191-041ac500-8271-11ea-93b3-e3fecef2a57f.png)

![image](https://user-images.githubusercontent.com/312857/79702193-0d0b9680-8271-11ea-87ec-92d313d51ffc.png)


sight text is already in i18n.properties - light can go there, too. Did spread it over multiple lines though for ease of reading. Translating this html is tricky because of the required properties line ending (\) and special care with brackets/pre.

![image](https://user-images.githubusercontent.com/312857/79702222-47753380-8271-11ea-9946-3a81deb48658.png)

**Comment by Azhrei** [comment]
Good job. :)

It would be nice if the built in docs could link to the wiki as well.  Some day we'll get to the point of having a little question mark symbol on every page that points to the wiki, but until then...

**Comment by Phergus** [comment]
Tested new code. Campaign Properties dialog is now compact and help text is pulled from the i18n files.  Other functionality is unchanged.

**Comment by Merudo** [comment]
Nice! Well done!

I noticed the text of the explanation of `Light` and `Sight` is larger than the text of the other tabs. Maybe the font size could be reduced a little?

**Comment by nmeier** [comment]
I'll have a look at the font configuration for those editor panes ...

**Comment by Phergus** [comment]
I'd hate to see those get much smaller as they don't use the theme font size.

**Comment by Merudo** [comment]
There should be a way for the `JEditorPane` to use the theme font size, no?

**Comment by Phergus** [comment]
But the help text is wrapped as HTML and that does funny things.

**Comment by Merudo** [comment]
Maybe use the Chat Font Size in Preferences, then?

**Comment by Phergus** [comment]
That might work.

**Comment by Merudo** [comment]
Something like

```java
HTMLDocument document = (HTMLDocument) lightHelp.getDocument();
StyleSheet style = document.getStyleSheet();
style.addRule(String.format("body { font-size: %dpt;}", AppPreferences.getFontSize()));
```

**Comment by nmeier** [comment]
good point on theme - I didn't realize this myself. The dialog sets an explicit color but no font on the component

![image](https://user-images.githubusercontent.com/312857/79757353-fbb2a080-82e9-11ea-815e-14483ff14e99.png)

I can remove taht color so default/theme applies

![image](https://user-images.githubusercontent.com/312857/79757976-c78baf80-82ea-11ea-867f-452a467a2b98.png)

Unfortunately it seems that the text pane defaults to black -  I don't see a way to tweak that through tinylaf's theme.

Found some discussion on default font/style of a text pane which shows how special this thing seems to be http://javatechniques.com/blog/setting-jtextpane-font-and-color/

The font is not explicitly set in the dialog resource. I couldn't figure out a way to configure this in the theme either.

Maybe the text pane is not the best choice. Is an explanation there really the right thing?

**Comment by Phergus** [comment]
Will @Merudo 's idea of using HTMLDocument and setting font size work?

**Comment by nmeier** [comment]
Found another way https://stackoverflow.com/questions/12542733/setting-default-font-in-jeditorpane

color and font makes it in from the theme, can add that. That solves all problems, right?

![image](https://user-images.githubusercontent.com/312857/79759943-51d51300-82ed-11ea-8e06-495a6b260511.png)

**Comment by Merudo** [comment]
Looking good! Is the a way to set the background of the panel to a different third color specified by the theme?

**Comment by Phergus** [comment]
Definitely need a different background color there.

**Comment by nmeier** [comment]
Looks good for default theme

![image](https://user-images.githubusercontent.com/312857/79762685-11779400-82f1-11ea-93e8-f5c82f1ee67d.png)


for other themes like dark not sure sure what foreground/background could be used. I think dark is simply dark and should look like light white on dark, as the input above is.

There's nothing in that scheme that has the purpose of inverting that imo

![image](https://user-images.githubusercontent.com/312857/79762890-513e7b80-82f1-11ea-9bd4-d1c6b4530c41.png)

**Comment by nmeier** [comment]
shot too fast - there's a tlaf textpane bg color that seems to go through for a styled document - I haven't changed the themes yet but I'd venture to say a theme could tweak the look as desired

![image](https://user-images.githubusercontent.com/312857/79766447-ff4c2480-82f5-11ea-8708-09c20f90fadd.png)

**Comment by Phergus** [comment]
Certainly if we can have it use a theme color and only need to adjust the themes that would be great.

**Comment by Phergus** [comment]
Tested again with latest fixes.  Light & Sight tabs in Campaign Properties now use theme colors.

**Comment by Merudo** [comment]
Great job! I'm loving the new look!
