### ISSUE TITLE
Add Resource dialog hardcodes colors that clash with theme

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1631]
**Describe the bug**

The add resource dialog has colors embedded in the resource dialog xml file. With e.g. dark theme the text cannot be read 

![image](https://user-images.githubusercontent.com/312857/79704884-8317f980-8281-11ea-998f-85d7fc919c15.png)

**To Reproduce**

Set dark theme, restart, open resource image dialog - notice white on white text

**Expected behavior**

The theme should be respected. There should be no hardcoded colors in this dialog, so the result for this theme is white text on dark background

![image](https://user-images.githubusercontent.com/312857/79705030-26690e80-8282-11ea-8433-e326641259d5.png)

**Screenshots**

see above

**MapTool Info**
- Version: 1.6.2/development
- Install: All

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

fix coming

**Comment by Phergus** [comment]
@nmeier please contact me on Discord or via email (My nickname at gmail).  Thanks.

**Comment by Phergus** [comment]
Tested fix.  Add Resource dialog now uses selected theme colors.
