### ISSUE TITLE
Tweak window decorations in Dialogs and Frames

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1635]
**Describe the bug**

So this is a bigger one. All dialog/windows in MT seem to be using the native window decoration (unless without all decoration,, e.g. Handout/AssetViewerDialog) - this means the titlebar doesn't match the theme - that bites my dark experience. Here's how the before/after looks like

![image](https://user-images.githubusercontent.com/312857/79708388-494cf000-828d-11ea-8b5d-aab0a383d92b.png)
![image](https://user-images.githubusercontent.com/312857/79708418-5a95fc80-828d-11ea-876f-0628f2692862.png)

![image](https://user-images.githubusercontent.com/312857/79707953-1b1ae080-828c-11ea-9216-da57da32c5a1.png)
![image](https://user-images.githubusercontent.com/312857/79708440-65509180-828d-11ea-84fd-0e5641f3fc1d.png)

![image](https://user-images.githubusercontent.com/312857/79707990-32f26480-828c-11ea-9f64-ba90541fef94.png)
![image](https://user-images.githubusercontent.com/312857/79708483-7bf6e880-828d-11ea-8781-ab22149df274.png)

![image](https://user-images.githubusercontent.com/312857/79708054-5cab8b80-828c-11ea-83a9-75dc7d42cf9b.png)
![image](https://user-images.githubusercontent.com/312857/79708503-8d3ff500-828d-11ea-9eb1-a13884cade3f.png)

Since I'm in the same code right now I'm also thinking that when the main window is maximized (not set to fullscreen) the titlebar takes up a lot of space.

![image](https://user-images.githubusercontent.com/312857/79710041-c4180a00-8291-11ea-92f5-5c9a191b6220.png)

If I'm DMing, and use hide/unhide toolbar to gain space (keeping my dockables and menu) I'd suggest to control the visibility of the titlebar for the maximized window. This gives me more space.

![image](https://user-images.githubusercontent.com/312857/79709824-2fada780-8291-11ea-8bc2-f781787ed4bc.png)

**To Reproduce**

Apply a non windows theme, check frame/dialog title bars. Maximize main window (not full screen) and use hide/unhide toolbar button. Notice that the titlebar of the maximized window is controlled as well.

**Expected behavior**

Better Titlebar experience.

**Screenshots**

See above

**MapTool Info**
- Version: 1.6.1/develop
- Install: All

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

The discussion about hiding the titlebar when maximized can be divorced from the theme issue. The tooltip at least of the little menubar hide/unhide chevron "Hide the Toolbar" would have to be updated.

I'm pushing a change that can be tested. Especially on Mac I can't test whether the swing titlebar would cause an issue.

**Comment by Phergus** [comment]
I'm all for fixing the various dialogs so that they use theme colors.

Not as sure about the title bar nor what impact that has on Macs.

@Azhrei @cwisniew @JamzTheMan  thoughts?

**Comment by bubblobill** [comment]
As a laptop user, screen real estate is precious. I can't use fullscreen as that removes the functionality I need in the various frames. If there are options to maximise the window that would allow minimising things like title bars and menu bars I would be all in favour. Alternately a variety of full-screen with added bits would be groovy.

Something like this with flyouts to access menus and bars.
![image](https://user-images.githubusercontent.com/45483160/79755307-811a6d00-834b-11ea-941e-8e7cdb7750f0.png)
![image](https://user-images.githubusercontent.com/45483160/79755462-bfb02780-834b-11ea-82ad-8d72729f6120.png)

**Comment by nmeier** [comment]
@bubblobill that's a more complicated change :)

With what I have you get 50+% there. One bar remains at the top for the menu - that allows all activity with your power tools. One could add window related buttons to the menu bar I assume, but that's more tricky work.

Is there someone with a mac who can test how the behavior I have with titlebar manipulation works out on that platform? That's a big concern.

**Comment by nmeier** [comment]
Since I'm looking at windows and system elements - also removing the taskbar java popup during enjoyment of splash screen

![image](https://user-images.githubusercontent.com/312857/79772839-97e6a280-82fe-11ea-843d-c2d43f8a5c7d.png)

**Comment by kayila** [comment]
Tested in Linux, and the title bars are correctly colored now, and opening/closing the top bar functions as expected. At least on Linux, this PR seems to check out, pending verification on Mac and Windows.
:+1:

**Comment by Phergus** [comment]
No issues seen on Windows.  Working as described.

**Comment by mrkwnzl** [comment]
I tested i1636-test-build. I’m not sure what is supposed to happen on Macs, but the title bar is still in the default grey in every dialog I tested and the main window. This happens in both light and dark mode (just in case this would impact how the title bar is rendered). But after a quick(!) test, it didn’t seem to break anything.

Was the expectation that the title bar is also black there?

<img width="847" alt="Screen Shot 2020-04-28 at 17 54 52" src="https://user-images.githubusercontent.com/40534855/80509545-dbce4d00-8979-11ea-8f71-0a8e42e950e7.png">

**Comment by nmeier** [comment]
Thanks for testing, Mac is special, I wish I could test this out directly but have no such device.

I found some evidence that the window decorations provided by the OS might or might not show up based on the look and feel, That you don't have two titlebars is already a win I guess.

https://stackoverflow.com/questions/139088/jframe-setdefaultlookandfeeldecoratedtrue

[Reference setDefaultLookAndFeelDecorated](https://docs.oracle.com/javase/7/docs/api/javax/swing/JFrame.html#setDefaultLookAndFeelDecorated(boolean))

How does the main window look like? I'm curious about the menu bar, and how it looks when you click the arrow on the right to hide the toolbar.

**Comment by Phergus** [comment]
Thanks for testing this out @mrkwnzl .  First priority is that this change doesn't break anything on MacOS and secondarily that the MapTool window decorations follow the theme. Assuming that's possible under the MacOS.

**Comment by mrkwnzl** [comment]
I’ll provide some more screenshots tomorrow. Anything else I should test specifically?

**Comment by Phergus** [comment]
Mostly checking that the menus and title bars remain readable. Various dialogs like Edit Token, Preferences, Campaign Properties and such are still usable.

**Comment by weisJ** [comment]
I would like to add that calling `setUndecorated(true)` on a JFrame etc. is generally a bad idea. It completely undermines all features the os offers for frames e.g. on Windows aero snap, frame shadows, etc. is lost.
If you want to have the title bar follow the theme I can offer you to check out [darklaf](https://github.com/weisJ/darklaf). It’s a LookAndFeel I am developing which offers multiple themes and offers nicely coloured title bars without giving up on OS features.

**Comment by Phergus** [comment]
@weisJ - Thanks for the post!

The use of `setUndecorated(true)` is only for when MT is running full screen with the toolbar hidden.  Otherwise all the normal OS features are there to be used.

Will take a look at your project.

**Comment by nmeier** [comment]
To clarify there are two things here - 
1) the change makes all windows use the Look and Feels' rendering for the title bar - the result is that the window looks styled nicely, e.g. in dark. This does indeed mean the OS doesn't render the titlebar (not sure what exactly is going on with Mac as that OS doesn't like replacing the OS titlebar unless there's a certian LnF in place I think). If your LnF offers something that leaves OS titlebar in place with color management, that could a compromise. Don't get yet how that works.

2) Fully undecorated windows are as before - there's no OS or LnF titlebar for certain viewers (e.g. Asset/Handout) and when the main frame is maximized.

As soon as you go LnF with a Java application you're entering this question - consistent look or a mix. It's in the eye of beholder.

**Comment by weisJ** [comment]
> To clarify there are two things here -
> 
> 1. the change makes all windows use the Look and Feels' rendering for the title bar - .... Don't get yet how that works.

It's rather involved and requires to change the window on the OS level.

> 2. Fully undecorated windows are as before - there's no OS or LnF titlebar for certain viewers (e.g. Asset/Handout) and when the main frame is maximized.
 
You might want to take a look at the [full screen api](https://docs.oracle.com/javase/tutorial/extra/fullscreen/exclusivemode.html).

**Comment by Phergus** [comment]
Full screen and maximized are not the same thing.

**Comment by weisJ** [comment]
> Full screen and maximized are not the same thing.

I see. As you are only moving the window buttons into the menubar then I'd say there are better solutions.

1. Windows: Darklaf already moves the menu bar into the title bar by default. This is how it looks:
![Annotation 2020-04-29 194726](https://user-images.githubusercontent.com/31143295/80628858-49e64300-8a52-11ea-88ba-30013a863cef.png)


2. macOS: The menubar sits in the native manu anyway and there is a native fullscreen mode.

3. Linux: Here darklaf doesn't change the titlebar (not implemented to this point), but on most desktop managers there is the option to disable the titlebar for maximized windows, so the OS can do that job.

Generally I think it is a bad idea to force disappearing titlebars onto the user. It's inconsistent with the rest of the OS and may be confusing. But that's just my opinion and its your decision what to do. I'm just offering a possible solution.

**Comment by mrkwnzl** [comment]
Sorry, for being a day late. Had to work late yesterday.

This is the main window maximised (not fullscreen):

<img width="1440" alt="Screen Shot 2020-04-30 at 09 36 16" src="https://user-images.githubusercontent.com/40534855/80684505-11804c80-8ac6-11ea-9b48-cb597f993731.png">

To be honest, since the title bar is grey already, I don’t find it too distracting. But for comparison, here’s how it loos with macOS in Dark Mode:

<img width="1440" alt="Screen Shot 2020-04-30 at 09 46 37" src="https://user-images.githubusercontent.com/40534855/80685436-81db9d80-8ac7-11ea-94b2-1f3cb8b68e56.png">

It’s a bit more distracting in Dark Mode, than it is in Light Mode, I think. The usual handling of this is that apps in Dark Mode have a dark title bar, even if the OS is in Light Mode.

There is not little arrow to hide the menu bar, as the menu bar is not part of the program window on macOS. But it’s also not needed. The native fullscreen mode works perfectly and already hides the menu bar.

This is the main window in fullscreen mode:

<img width="1440" alt="Screen Shot 2020-04-30 at 09 40 20" src="https://user-images.githubusercontent.com/40534855/80684881-a6834580-8ac6-11ea-8523-f2f9ab8565bd.png">

This is the main window in fullscreen mode when I move the mouse pointer to the upper edge to open the menu bar (note that the menu bar and title bar hovers over the MapTool window now; the windows does not get rendered anew):

<img width="1440" alt="Screen Shot 2020-04-30 at 09 41 00" src="https://user-images.githubusercontent.com/40534855/80684971-ca468b80-8ac6-11ea-95f7-d622cc6a0bb7.png">

The menu bar disappears automatically when I move the mouse pointer back down. Please don’t do anything that disrupts the native handling of the fullscreen mode in macOS. It’s a very smooth experience and works in line with native apps.

Edit Token window. Works great, but some buttons in the Properties tab aren’t dark, as are the Property values:

<img width="711" alt="Screen Shot 2020-04-30 at 09 54 37" src="https://user-images.githubusercontent.com/40534855/80687248-4f7f6f80-8aca-11ea-97d5-6d8e1c5f39e4.png">
Now that I have loaded a campaign, I’m finding a few spots which could be improved:

<img width="1440" alt="Screen Shot 2020-04-30 at 09 55 44" src="https://user-images.githubusercontent.com/40534855/80686315-d6334d00-8ac8-11ea-9251-553e80d8501d.png">

The Token Names in the Resource Library and the macro groups in all macro windows (Camapaign, Selected, GM) are black on grey, which is not ideal.

The items in the Map and Draw Explorer are white text on white bars, which makes it unusable. 

The tabs to change between those Explorers (and presumably other tabs) are grey text on darker grey background. A lighter grey for the text would be better.

<img width="366" alt="Screen Shot 2020-04-30 at 10 02 24" src="https://user-images.githubusercontent.com/40534855/80686876-b6505900-8ac9-11ea-8a84-3c9a7bf85846.png">

There’s a white bar behind each token in the Initiative window. The buttons “Next” and “Round” are black text on dark grey background.

<img width="421" alt="Screen Shot 2020-04-30 at 10 03 57" src="https://user-images.githubusercontent.com/40534855/80687022-eef03280-8ac9-11ea-9551-eba5a1fdd28e.png">

There’s something weird happening, when I hover the mouse pointer over the buttons. A border appears around each button which i hover over, and they all disappear when I click on the buttons. I haven’t seen this on 1.6.1 with a light theme.

I’ll do more testing after work. Let me know if you want to see something specific.

**Comment by nmeier** [comment]
Super, i'll go through your screenshots later today, and come back with suggestions.
Where the lnf clashes with color overrides, still, I should be able to fix.

**Comment by Phergus** [comment]
Thanks a ton @mrkwnzl !   That will be a big help.

Here is a dark theme that Aliasmask tweaked.  I think it will improve the explorer windows and maybe others.
http://www.lmwcs.com/rptools/wiki/Dice_Expressions
[AM_Dark.zip](https://github.com/RPTools/maptool/files/4558353/AM_Dark.zip)

**Comment by nmeier** [comment]
So the Edit Token dialog is interesting as it uses the (marco) syntax editing component to render the property values - If I switch that out for a default table renderer you get the expected result (see below).

The special renderer offers word wrap - @Phergus  is that needed? Do token properties allow for multi line values?

![image](https://user-images.githubusercontent.com/312857/80738102-7cd81780-8ae2-11ea-94ef-5089b4cba6fa.png)

**Comment by Azhrei** [comment]
I don't know about Phergus, but I have JSON elements stored in properties and I use the **wrap** checkbox all the time.  I don't know whether newlines can be embedded inside property values, though.

**Comment by nmeier** [comment]
ok, I see, I didn't realize the little button on the right either. Thanks for clarifying

**Comment by Phergus** [comment]
@nmeier  Folks do use the multi-line and it is handy to have the syntax highlighting when you open the little editor window.
![image](https://user-images.githubusercontent.com/34379254/80740107-d5a0b380-8ad4-11ea-9c49-00021629cab9.png)

![image](https://user-images.githubusercontent.com/34379254/80740148-e51ffc80-8ad4-11ea-8bb8-5dcfde30e586.png)

**Comment by mrkwnzl** [comment]
Okay, next round.

In Campaign Properties > Sight & Light, the text field isn’t discernible from the background.

<img width="1011" alt="Screen Shot 2020-04-30 at 20 41 11" src="https://user-images.githubusercontent.com/40534855/80748044-9bf79900-8b24-11ea-92da-f210156fd9ed.png">

“Add Resource to Library” has white text on white background. 

<img width="618" alt="Screen Shot 2020-04-30 at 20 43 47" src="https://user-images.githubusercontent.com/40534855/80748027-9601b800-8b24-11ea-9c8f-b70fff4a9046.png">

The map selection seems a bit out of place, and has white corners.

<img width="110" alt="Screen Shot 2020-04-30 at 20 45 18" src="https://user-images.githubusercontent.com/40534855/80747999-8f734080-8b24-11ea-9e48-625402c24aa0.png">

That’s all that I noticed. I think I went through most, if not all, dialogs through the menu, and most of them looked fine and the text was readable. Preferences, save dialogs, new/edit map, etc.

Let me know if there’s something I likely missed and which I could take a look at.

**Comment by Phergus** [comment]
Thanks!  The Add Resource to Library issue has been fixed I believe.

**Comment by nmeier** [comment]
Status below - overall the jide/lnf, customization leads to mixed results. We've tweaked it a little bit and didn't clearly regress. I feel like that's about all I can do there right now.

## Edit Token - properties table cells have white background

The values can be multiline and uses the same component as for editing, that would mean it also could show syntax highlighting. Don't think it makes sense to change that rendering - it's a special component.

## Resource Library and Macro WIndow - groups are black on grey

TBD

## Map and Draw Explorer - items are white text on white bars

[is fixed on develop branch](https://github.com/RPTools/maptool/issues/1631)

## Panel tabs - grey text on darker grey shaded background

Couldn't figure out how to change that. Overall JIDE and the L&F remains problematic for a sleek UI imo.

## Initiative window - white background, weird colored buttons

There is some JIDE specific weirdness on color. Even the buttons are looking black on black. The panel modifies the look and feel which is not fast nor wise

```
    LookAndFeelFactory.installJideExtension(LookAndFeelFactory.VSNET_STYLE_WITHOUT_MENU);
    menuButton = new JideSplitButton(I18N.getText("initPanel.menuButton"));
    LookAndFeelFactory.installJideExtension(LookAndFeelFactory.XERTO_STYLE);

```

## Toolbar - sticky border indication on hover

TBD

**Comment by JamzTheMan** [comment]
FYI rsyntax component does have its own mechanism to change it's theme so simple one could be created to match the tiny laf theme. Maybe follow the same naming and load them in the properties panel.

Check the maco editor code for examples of needed.

**Comment by nmeier** [comment]
On the initiative window @mrkwnzl  - it's using one of the worst L&F compatible components, the JIDESplitButton (which does some weird lnf unset/setting as well).

I'm tempted to replace it - that allows for normal components to control the fairly complex initiative panel. Would also go in direction of divorcing from JIDE if that's considered.

Simple looks - there's no button/menu combination in Swing so we could use a menu in a top toolbar-like panel. I've also changed how the selected (not current) item is indicated, instead of a hardcoded black border, reuse the selection border the other components use as well.

What do you guys think about that? 

Dark

![image](https://user-images.githubusercontent.com/312857/80854619-98890e00-8c07-11ea-85b0-731f3e792cf1.png)

in default style, with menu opened

![image](https://user-images.githubusercontent.com/312857/80854641-c79f7f80-8c07-11ea-953b-c36647b0ddd7.png)

**Comment by bubblobill** [comment]
Add a "Previous"/"Back" button and I support your intent.

**Comment by nmeier** [comment]
That toolbar can certainly be modified. At the moment it offers **next** as a top-level action.
That button is replaced by **Toggle Hold** if the user can use their limited permission to control the token. I'm not sure why this action is elevated like this - switching out buttons is weird imo. 

![image](https://user-images.githubusercontent.com/312857/80865743-5be60280-8c59-11ea-9fad-710d34b542bd.png)



```
    // Set up the button
    if (ownerPermissions || hasGMPermission()) {
      NEXT_ACTION.setEnabled(true);
      nextButton.setAction(NEXT_ACTION);
    } else {
      TOGGLE_HOLD_ACTION.setEnabled(true);
      nextButton.setAction(TOGGLE_HOLD_ACTION);
    } // endif

```

![image](https://user-images.githubusercontent.com/312857/80865331-ac0f9580-8c56-11ea-94f0-d2aee9b515d1.png)

**Comment by JamzTheMan** [comment]
I'm ok with switching out that combo button/menu. Less reliance on jide is better IMO.

**Comment by Phergus** [comment]
Ditto.  As I don't use the Initiative window I don't know what any of the toggle hold stuff is about but agree that swapping out buttons is poor design.

**Comment by bubblobill** [comment]
I would suggest a further improvement. Replace the split-button yes. But revamp the available buttons to icons, a la
![image](https://user-images.githubusercontent.com/45483160/80914438-13743500-8d7e-11ea-82ec-0ac3e67ba4e5.png)

**Comment by nmeier** [comment]
> I would suggest a further improvement. Replace the split-button yes. But revamp the available buttons to icons, a la
> ![image](https://user-images.githubusercontent.com/45483160/80914438-13743500-8d7e-11ea-82ec-0ac3e67ba4e5.png)

I like simple symbol better than text. 

Really though, does anyone know what hold is supposed to do? IIRC 'next' just cycles through all tokens, whether on hold or not. So why put something on hold in the first place?

**Comment by mrkwnzl** [comment]
I can’t say if that is the proper use of “hold,” but many in may games, characters can break the usual initiative order by going on hold. I don’t think this function itself does something beyond signifying that the character is on hold. It can be used in macros, I believe.

**Comment by nmeier** [comment]
Yeah, ok, found something to that point
https://lmwcs.com/rptools/wiki/More_Roll_Initiative

**Comment by JamzTheMan** [comment]
Hold is just a visualization really. Because really, init panels had no logic other than round count and tracking current token that had initiative.

Usually people use it to denote a delayed action. But it had to be generic really, you could use it to denote teams i suppose it other things.

For Pathfinder we have Ready and Delay. If i were to put that logic into they init panel, it would automatically remove the Hold if it came around to that tokens init turn again. If the hold was pressed when it wasnt the tokens turn it would remove the hold and put the token just before the current tokens position to denote interrupting the current token ala using a Ready action. Using delay would have to move it before the current init token so it goes next.

That is just one have system. Not sure you would want to force that logic on everyone. Hence it does "nothing"

**Comment by Phergus** [comment]
Further modification of Initiative Window should be moved to a new issue.  Good to go ahead with the menu button change and current initiative highlighting.

**Comment by Phergus** [comment]
@nmeier  Any idea which change caused MT on MacOS to lose the native title bar?

**Comment by nmeier** [comment]
looks related, checking in on #1752

**Comment by nmeier** [comment]
moving the discussion around initiative to #1758

**Comment by mrkwnzl** [comment]
I just checked on the current develop branch. I noticed one thing more for the dark theme. The tabs for hidden windows might be darker to be less intrusive.

<img width="376" alt="Screen Shot 2020-05-06 at 07 20 19" src="https://user-images.githubusercontent.com/40534855/81140681-92c65c00-8f6a-11ea-9b83-605bb9080c89.png">

**Comment by nmeier** [comment]
Yeah, I had a quick look at at jide dockables but couldn't figure out how to have them styled as per look and feel. The gradient rendering they put everywhere in that library is tricky. Maybe a conversation for the future of the docking library used.

**Comment by Phergus** [comment]
A move to JFX for all of the UI will require a different docking library so I'm sure we'll have a whole new set of _challenges_ to deal with then.

**Comment by Phergus** [comment]
Further tweaks and corrections to the LaF implementation can be done under new tickets or #1758  for the Initiative window.

Closing.
