### ISSUE TITLE
Frame5 unable to use src on the script tag

### ISSUE THREAD

**Issue by stolkun** [RPTools/maptool#1637]
**Describe the bug**
When you write <script src="TheLinkOfJSMacro"></script> it doesn't work

**To Reproduce**
1:create a frame5
2:create a 2nd macro with your JS
3:try to link it with script src

**Expected behavior**
The expected behavior when you write the tag script with the src attribute is to link your script from another file, here macro.
For example it should work as the tag link <link rel="stylesheet" type="text/css" href="TheLinkOfMacro"/>

**MapTool Info**
- Version: 1.6.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903

**Comment by Phergus** [comment]
It's an intentional limitation right now as a better storage system for holding scripts and other similar content is being worked on.

**Comment by stolkun** [comment]
Okay thanks for the response i'll close the thread
