### ISSUE TITLE
Macrolinks added via Javascript don't work in frame5/dialog5

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1638]
**Describe the bug**
Macrolinks / hyperlinks added via Javascript after the page has been created are not properly handled by frame5/dialog5.

**To Reproduce**
1. Run the following script:

```html
[frame5("test"):{
<script>
[r: '
function add_link() { 
	var a = document.createElement("a");  
	var link = document.createTextNode("This is a new link"); 
	a.appendChild(link);  
	a.title = "This is a new link";  
	a.href = "https://www.google.com";  
	document.body.appendChild(a);
} ']
</script> 

<button onclick="add_link()">Click me</button>
<a href='https://www.google.com'>Link created at page load</a><br>

}]
```

2. Click on `Link created at page load`. MapTool opens the default browser and launches www.google.com, as expected.

3. Click on the button, and then on the newly created link. The HTML5 frame changes to www.google.com instead.

**Expected behavior**
Links created via javascript behave the same as links created with HTML.

**MapTool Info**
- Version: 1.6
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1639 fixes this, by adding a MutationObserver on the document so that new nodes are properly dealt with.

**Comment by Phergus** [comment]
Tested with fix.  Links created via javascript after page load now work as expected.
