### ISSUE TITLE
New Campaign resets the VBL/MBL drawing mode but not the toggle button.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1642]
**Describe the bug**
The VBL/MBL/Both toggle button is keeping the last setting even though File -> New Campaign resets the actual drawing mode to VBL.

**To Reproduce**
1. In an open MapTool window, select VBL Tools and change to MBL
2. Draw a section of MBL.  Should appear as Magenta.
3. From File menu select New Campaign.
4. VBL mode should still be on MBL
5. Draw a section of MBL. Will come out the Blue of VBL and if tested it is VBL

**Expected behavior**
Button should be reset on selecting New Campaign to VBL only mode or, vice-versa, the mode should be set to match the button.

**MapTool Info**
- Version: 1.6.1 and current dev
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Needs to be checked against Loading Campaigns as well.

**Comment by Merudo** [comment]
The same issue happens after creating a new map.

**Comment by Phergus** [comment]
At least Import Map doesn't have the issue.

**Comment by Phergus** [comment]
Tested:
- Open Campaign
- New Campaign
- New Map
- Changing Maps
- Quick Map
- Edit Map
- Delete Map
- Import Map
- Start Server

VBL mode matches button state for all cases.
