### ISSUE TITLE
Deleting / cutting multiple tokens should only fire TOKEN_REMOVED once

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1654]
**Is your feature request related to a problem? Please describe.**
Deleting / cutting multiple tokens fires the TOKEN_REMOVED event multiple times, causing lag as the selection / impersonate panels reset multiple times.

There is a hack in the code to handle to handle the case where 10 tokens are deleted at a time, but a better solution is needed.

**Describe the solution you'd like**
Refactoring so the TOKEN_REMOVED event is only triggered once, even if multiple tokens are cut or deleted.

**Comment by Merudo** [comment]
PR #1655 implements this change

**Comment by Phergus** [comment]
Tested.  Deleting multiple tokens (<10) with common macros, selection window open and impersonated window open is pretty close to instantaneous.  Much improved over 1.6.1.
