### ISSUE TITLE
Macros deleted through common macro panel don't get updated to clients

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1657]
**Describe the bug**
Macros deleted through the common macro panels don't get their change updated to the server or clients.

**To Reproduce**
1. Have a client join the server.
2. Select multiple tokens with the same macro
3. Delete the macro for all the tokens through the common macro panel
4. Check the client. The macros are not deleted.

**Expected behavior**
The macros are deleted on all clients

- Version: 1.6.1, 4/21/2020 develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1663 implements this.

**Comment by Phergus** [comment]
Tested.  Deleting a macro from the Common group updates all tokens on client.
