### ISSUE TITLE
Deleting a token should not reset the impersonated token panel

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1658]
**Describe the bug**
Deleting a token that is not impersonated should not trigger a reset of the impersonation panel.

**To Reproduce**
1. Load a campaign with a token with a lot of macros
2. Impersonate that token
3. Delete an empty token. MapTool will lag while it is resetting the impersonated panel.

**Expected behavior**
The impersonated panel is only reset if the impersonated token was among those deleted.

**MapTool Info**
- Version: 1.6.1, develop 4/21/2020
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1659 fixes this.

**Comment by Phergus** [comment]
Tested.  Not actually seeing a huge difference between 1.6.1 and current dev with this fix.  Using tokens with 200 macros on them and one of those is impersonated.  The update to the Selection window is faster by a small amount.  Delete a token with no macros and then quickly dragging another might also be faster by a small margin.

**Comment by Merudo** [comment]
Try the following:

1) Impersonate a token with tons of macro, such as the `OnTokenMove` token from the BoT.
2) Make sure the Selection panel is closed, and the Impersonate panel is open
3) Delete exactly 10 new tokens, or cut a large number of tokens. The impersonated token should not be selected for this step.

Deleting the 10 tokens / cutting the many tokens is instant with this fix, but takes a long time on 1.6.1.

The reason the number of deleted tokens needs to be 10 is that there was a hack in place to make the deletion faster if 11 or more tokens were deleted.

**Comment by Phergus** [comment]
Okay.  By bumping the number of macros up to 400 and deleting 10 tokens, I got it up to near a second on 1.6.1 and instant with current dev.
