### ISSUE TITLE
<Ctrl><F> does not work in macro editing windows

### ISSUE THREAD

**Issue by taustinoc** [RPTools/maptool#1660]
<Ctrl><F> does not bring up the Find dialog if the program focus in on a macro editing window. It does if the focus is on the main MapTool window. In addition, if more than one macro editing window is open, there does not appear to be any way to control which one is searched.

**To Reproduce**
Open a campaign file with macros.
Open an editing window for a macro.
While the macro editing window has the focus, press <Ctrl><F>. Nothing will happen.
Set the focus to the main MapTool window, and press <Ctrl><F>. The Find dialog will open.

If more than one macro editing window is open, the Find dialog will only search one (possibly the first one opened, but it's not clear).

**Expected behavior**
<Ctrl><F> while the focus is on a macro editing window should open a Find dialog that will search through that particular window.

**MapTool Info**
- Version: 1.6.1
- Install: Upgrade 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

From MapTool, paste info from menu Help -> Gather Debug Information...

==== MapTool Information ====
MapTool Version: 1.6.1
MapTool Home...: C:\Users\terry\.maptool-rptools
Max mem avail..: 4 GB
Max mem used...: 4 GB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\Users\terry\AppData\Local\MapTool150\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 7
OS Version.....: 6.1
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PATH...........: C:\Users\terry\AppData\Local\MapTool150\app;C:\Users\terry\AppData\Local\MapTool150
Number of Procs: 2

==== User Information ====
User Name: terry
User Home: C:\Users\terry
User Dir.: C:\Users\terry\AppData\Local\MapTool150\app

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Realtek PCIe GBE Family Controller
Interface Name: eth3
Address...: 192.168.50.240
Address...: fe80:0:0:0:44d7:48a4:b4cb:8a34%eth3

Display Name..: VirtualBox Host-Only Ethernet Adapter
Interface Name: eth5
Address...: 192.168.56.1
Address...: fe80:0:0:0:7897:3327:5079:3743%eth5

Host Address...: 192.168.50.240
Default Gateway: 192.168.50.2

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(32)

==== Internet Gateway Devices ====
	No IGDs Found!

**Comment by Merudo** [comment]
Try `<Ctrl><Shift><F>`.

**Comment by taustinoc** [comment]
That does work. It is very confusing. Perhaps that could be some indication of that somewhere on the window.

**Comment by Phergus** [comment]
This part of #1495
