### ISSUE TITLE
Changing selection should not reset the impersonated token panel

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1666]
**Describe the bug**

Changing selection currently triggers a full reset of the Impersonated token panel.

This can slow down MapTool, especially if the impersonated has a lot of macros.

Once a token is impersonated, a change of Selection can never trigger a change of impersonation by itself, and thus the change of selection should not reset the panel.

**Comment by Merudo** [comment]
PR #1671 fixes this.

**Comment by Phergus** [comment]
Testing with 1.6.1 and tokens with a large number of macros (400+) shows a noticeable delay when switching selection while one of the tokens is impersonated and the impersonated window is open.

Using latest develop with this fix, no perceptible delay seen.
