### ISSUE TITLE
Updating Token properties change all tokens, Basic properties updates don't reflect on tokens [1.7a]

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#1667]
**Describe the bug**
In 1.7a, updating a property (like 'HP') changes that property for all existing and new tokens. Furthermore, adding a new property via the Campaign Properties updates the token properties list in 'Campaign Properties', but not in the 'Edit Token' dialog on tokens.

**To Reproduce**

*Property Changes affect All Tokens*
1. Install 1.7.0-alpha-1
2. Add two new tokens
3. Double click the first token and change 'HP' and any other properties to any value. Press 'OK'.
4. Double click the second token and view the 'Properties' tab. See error.
5. Add a new token, double click it, and view the 'Properties' tab. See error.

*Campaign Properties Don't Update*
6. In Campaign Properties, Import the 'Stars without Number' predefined properties. Press 'Update' and 'Ok'.
7. Double click any token and view the 'Properties' tab. See error - Basic properties were not updated.

*Property Types Changes affect All Tokens*
8. Double click any token, select the 'Config' tab, and change the property type to 'Starship'. Press 'OK'. 
9. Double click any other token and view the 'Properties' tab. See error - property types match 'Starship'.
10. Click the 'Config' tab. Property type still says 'Basic'. 

**Expected behavior**
Token properties should work independently and reflect Campaign Property changes as in previous versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/220149/80003997-a48e0680-8476-11ea-94d3-76fd18c5d415.png) ![image](https://user-images.githubusercontent.com/220149/80004016-aa83e780-8476-11ea-9daf-d89dc42360ee.png)
![image](https://user-images.githubusercontent.com/220149/80004104-ca1b1000-8476-11ea-8f23-9c60a23a0c5b.png)

**MapTool Info**
- Version: 1.7.0-alpha-1
- Install: New alongside many previous versions

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
You can force the basic properties to refresh after updating Campaign Properties by changing any token to a different property set and back to 'Basic', but of course it affects all existing and future tokens.

```==== MapTool Information ====
MapTool Version: 1.7.0-alpha-1
MapTool Home...: C:\Users\melek\.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 256 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\Users\melek\AppData\Local\MapTool-1.7.0a1\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PATH...........: C:\Users\melek\AppData\Local\MapTool-1.7.0a1\app;C:\Users\melek\AppData\Local\MapTool-1.7.0a1
Number of Procs: 4

==== User Information ====
User Name: melek
User Home: C:\Users\melek
User Dir.: C:\Users\melek\AppData\Local\MapTool-1.7.0a1\app

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: VirtualBox Host-Only Ethernet Adapter #3
Interface Name: eth2
Address...: 192.168.95.1
Address...: fe80:0:0:0:dcd6:4118:81fe:c5c%eth2

Display Name..: Realtek PCIe GBE Family Controller
Interface Name: eth3
Address...: 192.168.0.114
Address...: fe80:0:0:0:c4df:cb97:74d7:1ddb%eth3

Display Name..: VirtualBox Host-Only Ethernet Adapter #4
Interface Name: eth6
Address...: 192.168.94.1
Address...: fe80:0:0:0:6528:383e:4882:3055%eth6

Host Address...: 192.168.94.1
Default Gateway: 192.168.0.1

==== Locale Information ====
Country.: United States
Language: 
Locale..: United States
Variant.: 

==== Encoding Information ====
Default Locale:   _US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 1920x1080(32)
Display 2: 1680x1050(32)

==== Internet Gateway Devices ====
Device Name.: CenturyLink UPnP v1.0
Model Name..: C3000Z
Manufacturer: ZyXEL
Model Number: C3000
Model Desc..: (null)
Firmware....: Custom/1.0 UPnP/1.0 Proc/Ver
External IP.: 97.120.123.71

```

**Comment by Phergus** [comment]
Confirmed.

**Comment by Merudo** [comment]
It seems the problem is specific to the token editor. I'm on it.

**Comment by Merudo** [comment]
PR #1672 merge the 1.6.1 fix back into develop.

**Comment by melek** [comment]
@Merudo I had the issue when updating properties with macros, as well. Not sure if that matters!

**Comment by Phergus** [comment]
As in `[r: setProperty("Strength",12)]` would affect all tokens on the map?
