### ISSUE TITLE
Add Overlay Helper Functions [1.7a]

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#1669]
**Is your feature request related to a problem? Please describe.**
The new overlay roll option is very exciting, but lacks important helper functions that frames and dialogs enjoy.

**Describe the solution you'd like**
I would like a few functions:
* `isOverlayRegistered(overlayTitle)` - Returns 1 or 0. (Checked status in Window -> Overlays menu.)
* `closeOverlay(overlayTitle)` - Closes named overlay if open & returns 1. Returns 0 if the overlay wasn't found but doesn't error
* `get / setOverlayProperties` - Returns / sets any properties, especially z-order.
  `{"name":"Overlay","zorder":0,"visible":1}`

**Describe alternatives you've considered**
Just leaving overlays open all the time, because I can't close them.

**Additional context**
`isOverlayVisible` would be the consistent name for the first proposed function, but since users can toggle 'Visibility' of overlays it might be confusing.

**Comment by Phergus** [comment]
Just FYI, you can close overlays, just pass an empty content block:  `[overlay("Overlay"):{}]`

But having the convenience methods wouldn't be a bad thing.

**Comment by melek** [comment]
In the interrim knowing that I cam close overlaps is helpful, thank you :)

**Comment by Merudo** [comment]
PR #1826 adds isOverlayRegistered, closeOverlay, getOverlayProperties

**Comment by Phergus** [comment]
This seems to have broken something.

With 1.7.0b2 I can open two overlays at the same time with different titles and then close and reopen them with no issue.

With current develop, if I open two overlays they see to get bound together.  Only the 2nd one is "registered"  and closing it closes both.  Calling either macro opens the combination of them once the both have been opened.

**Comment by Merudo** [comment]
Do both overlay have the same Z order?

**Comment by Phergus** [comment]
I assume so since I didn't specify.

**Comment by Merudo** [comment]
Might be a java bug. `ConcurrentSkipListSet` should be able to two elements such that `o.compareTo(e) == 0` as long as `o.equals(e) == false`.

Yet, it doesn't seem to be the case.

**Comment by Merudo** [comment]
Well the information from the javadocs is seriously misleading. Apparently `o.compareTo(e) == 0` must imply `o.equals(e)` for the contract of the SortedSet interface to be fulfilled. 

You won't find this in any of the documention of concurrentskiplistset, though.

https://stackoverflow.com/questions/48101005/concurrentskiplistset-using-comparator-will-not-add-new-unique-values

**Comment by Merudo** [comment]
PR #1851 fixes this.

Thank you so much for identifying this bug before release @Phergus :). Having it sneak into the release would have been awful.

**Comment by Phergus** [comment]
Teamwork!  Glad you found a fix.  This is just the kind of thing I am worried about popping up moments after release.

**Comment by Merudo** [comment]
I forgot, hashcode of the names being equals does not imply the names are equal. Using hashcode coud therefore cause bugs. PR #1852 fixes this by changing it to sort according to the name itself.

**Comment by Phergus** [comment]
@Merudo  `getOverlayProperties()` includes the `visible` status but you can only get the properties if it is visible.  Shouldn't this function return the properties as long as the overlay has been opened, visible or not, and only return an empty string otherwise?

**Comment by Merudo** [comment]
By visible, I mean whether it has been checked in the Window -> Overlays submenu.

Maybe "visible" is not the best word for this?

**Comment by Phergus** [comment]
Not actually a problem.  Just confusion on my part leftover from testing before the recent fixes.  It is all working as expected now.

**Comment by Phergus** [comment]
Wiki pages added.
http://www.lmwcs.com/rptools/wiki/isOverlayRegistered
http://www.lmwcs.com/rptools/wiki/closeOverlay
http://www.lmwcs.com/rptools/wiki/getOverlayProperties
