### ISSUE TITLE
Left button release while selecting multiple tokens doesn't select just one

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1675]
**Describe the bug**
Releasing the left button on a token when multiple are selected doesn't select the single token anymore.

**To Reproduce**
1. Select multiple tokens
2. Left click on one of the selected tokens
3. Notice how the tokens are still selected

**Expected behavior**
Only the token that was left clicked should be selected.

**MapTool Info**
- Version: 1.7 A1, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Bug caused by #1503

**Comment by Merudo** [comment]
PR #1676 fixes this.

**Comment by Phergus** [comment]
Tested.  Left-clicking on a token/object/stamp deselects any others that are selected while selecting or keeping selected the clicked token.
