### ISSUE TITLE
Users should receive more helpful message if MapTool can't start

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1678]
**Is your feature request related to a problem? Please describe.**
Some users report unhelpful error messages when trying to start MapTool.

Examples:

- A Java Exception has occurred
- Failed to Launch JVM
- Error invoking method

Users end up being confused about what is wrong. And with the limited error message, it is difficult to help them

**Describe the solution you'd like**
More useful error messages.

**Comment by Phergus** [comment]
No sure how to test this change.  From the code change I gather that we should be more likely to get info to the log and/or an error dialog in MT when the are "issues" affecting startup.

**Comment by Phergus** [comment]
No testable use cases.  Closing.
