### ISSUE TITLE
Bogus language "ac" available in preferences

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1686]
**Describe the bug**
A bogus language "ac" is available in the language list of startup preferences.

Is isn't a real language, and should be removed.

**To Reproduce**
1. Open Preferences go to Startup
2. Look at the list of languages, and notice "ac" is in there.

**MapTool Info**
- Version: 1.6.1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1687 fixes this.

**Comment by Phergus** [comment]
Tested.   Non language "ac" no longer shows up in list.
