### ISSUE TITLE
Figure tokens are visible to players on the hidden layer

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1688]
**Describe the bug**
From https://forums.rptools.net/viewtopic.php?f=3&t=28703:

> My players commented on the fact that they could see something that was on the hidden layer. I change the object to "only visible to owners" and then they couldn't see it. Then it happened again.
> 
> So today, I threw 2 NPCs on the Hidden layer and a player token on the Token layer. One of the NPC tokens is marked as a "Figure" token, the other is a top down. When i click on player token and press Ctrl+Shift+P to "View as Player", I can't see the top down token on the Hidden layer...but sure enough, I can see the Figure token! Not good!

**To Reproduce**
1. Put a Figure token on the Hidden layer .
2. Check "View as Player". The token is visible.

**Expected behavior**
Figure tokens shouldn't be visible while on the hidden layer.

**MapTool Info**
- Version: 1.6.1, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1689

**Comment by Phergus** [comment]
Tested.  The fix works for Maps with Vision on but fails without it.  Figure tokens placed on Hidden layer are still visible to players in that case.

**Comment by Merudo** [comment]
The same thing happens to "Visible over FoW" tokens.

**Comment by Phergus** [comment]
As in tokens on the Hidden layer that are flagged Visible over FoW?

**Comment by Merudo** [comment]
Yep.

**Comment by Merudo** [comment]
PR #1715 fixes this.

**Comment by Phergus** [comment]
Tested.  Hidden layer Figure tokens and tokens flagged as VoFoW no longer visible to players.
