### ISSUE TITLE
New tokens show up as "?" to clients until a map repaint

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1700]
**Describe the bug**
If a token with a previously unused image is put on the map, it will be displayed as a question mark `?` to all clients.

The token will remain displayed as a `?` until the client's map is repainted. Actions that can trigger a repaint include:

- Sending a chat message
- Clicking the mouse on the map
- Zooming the map
- Having a mouseover over a token on the token layer
- Having another client add or move a token

**To Reproduce**
1. Connect a MapTool client to a server (both can be on same machine)
2. Drop a previously unused token on the map as one of the players.
3. The other player will see the token as a `?` until they trigger a repaint.

**Expected behavior**
The new tokens don't stay as `?`.

**MapTool Info**
- Version: 1.5.14, 1.6.1, develop, probably all older versions
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1701 fixes this.

**Comment by Phergus** [comment]
Could not reproduce with the above steps but could with different ones.  Probably a matter of preferences settings.

**On 1.6.1:**
1. Start Server
2. Connect with Player Client
3. Drop token on Server (Prefs: NPC, Not Visible to Players)
4. Nothing seen by Player
5. Right-click on new NPC token and set Visible to Players
6. Player sees Question Mark and can force update as noted above.

With fix applied, Player Clients get updated as soon as token is set visible.
