### ISSUE TITLE
Portrait image rendering is not scaled with sufficient quality

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1709]
**Describe the bug**

Various places in MapTool set or don't set the rendering hint for interpolation. The PointerTool painting the portrait for example sets no hint, resulting in a badly scaled image. The Handout (AssetViewer) does set Bilinear (only applies when picture is larger than screen size). 

Also considered : the Token rendering itself (ZoneRenderer) is done without appropriate hint (right side, left side with patched in rendering hint)

![image](https://user-images.githubusercontent.com/312857/80331805-0e136980-8817-11ea-9178-52de825b0aad.png)

The ImagePanel has a switch - shrink with bilinear, grow with bicubic as of [#691](https://github.com/RPTools/maptool/issues/691)

```
          if (dim.width < image.getWidth(null) || dim.height < image.getHeight(null)) {
            g.setRenderingHint(
                RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
          } else if (dim.width > image.getWidth(null) || dim.height > image.getHeight(null)) {
            g.setRenderingHint(
                RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
          }

```

**To Reproduce**

Look at rendered images. 

**Expected behavior**

Use bilinear everywhere consistently, not sure bicubic is worth it anywhere.

**MapTool Info**
- Version: 1.6.1/develop

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

SwingUtil has a common antialiasing method/pattern, that should probably be used everywhere. Maybe it should just set up antialiasing and interpolation hint to 'pretty'. There are some spots in code that explicitly turn off antialiasing (sharp lines needed).

**Comment by nmeier** [comment]
Is there a performance issue? There could be an option for rendering - 

FAST (no antialising, no interpolation)
NORMAL (antialiasing, bilinear interpolation)
QUALITY (antialiasing, bicubic interpolation)

**Comment by Merudo** [comment]
I appreciate your effort to improve the image rendering in MapTool. I for one has been disappointing of how scaled images look.

However, I find your example troubling. The image on the right looks terrible to me, and much worst than the one on the left. Some of the text is near unreadable, and the edges of the characters look jagged.

**Comment by Phergus** [comment]
Indeed.  That right side image is really terrible.

As we will be moving to Java 14 in the very near future there may be other rendering options available or there may be other improvements that will help.

Most of the decisions about the scaling inside of MapTool happened a long time ago and performance was certainly a concern at the time.

**Comment by nmeier** [comment]
oops, sorry, I mixed up left and right, the left is the one that I've patched

**Comment by nmeier** [comment]
![image](https://user-images.githubusercontent.com/312857/80423857-a6a8f880-88ae-11ea-9584-d7d0350f2b5b.png)

background image - top, as per branch develop, bottom, if I set hint to cubic

**Comment by Merudo** [comment]
From some tests I did, I believe the zone renderer currently uses `VALUE_INTERPOLATION_NEAREST_NEIGHBOR`.

I tried switching it to `VALUE_INTERPOLATION_BILINEAR` and got a very noticable improvement in quality when downsampling high quality images.

Also, I found some options for resizing images in Java:

https://stackoverflow.com/questions/24745147/java-resize-image-without-losing-quality

**Comment by Azhrei** [comment]
I'm sure lots of people have done studies/analysis trying to figure out the best approach for a given situation.  Might as well take advantage of that.  I'm off to read the SO link...

**Comment by nmeier** [comment]
The ZoneRenderer doesn't use a scaling hint right now - we [tried that](https://github.com/RPTools/maptool/commit/06828de1cfcf3b345222535408eb37db84c64244) but the difference was not THAT visible and [rendering speed decreased](https://github.com/RPTools/maptool/pull/1716#issuecomment-620946237).

VALUE_INTERPOLATION_BILINEAR Is used in
AssetViewer
ImagePanel
Saving of Token
Overlay (Portrait)

Overall I found the improved quality when scaling a token to be not significant enough.

@Merudo do you have a screenshot? I'm still wondering if background images should at least be scaled with a hint. Ultimately we'll need an option to turn on/off high quality rendering to not lock out slow machines.

**Comment by Merudo** [comment]
When you inspected the images for quality, which scaling did you choose?

In my tests, the difference was very pronounced at about 50-80% scaling.

**Comment by Merudo** [comment]
The link to your now defunct commit related to the zone renderer: https://github.com/nmeier/maptool/commit/7ef77f91ab4793a4c2e7c96175248e12d106f9c7

**Comment by Merudo** [comment]
![img1](https://user-images.githubusercontent.com/7371085/82091182-881f6b80-96bc-11ea-98ba-d25b04218ad0.png)
![img2](https://user-images.githubusercontent.com/7371085/82091206-91103d00-96bc-11ea-9e8f-c623035904e4.png)

**Comment by Merudo** [comment]
This one is at 75% scaling:

![img3](https://user-images.githubusercontent.com/7371085/82091943-ed279100-96bd-11ea-92ed-f68dafac0148.png)
![img4](https://user-images.githubusercontent.com/7371085/82091959-f57fcc00-96bd-11ea-9ebb-e0b67af92e54.png)

**Comment by JamzTheMan** [comment]
Yea, that top one is definitely more readable. 

I'm not opposed to adding a Graphics? Video? Performance? section (tab?) for 1.8 and add some options.  I don't think there is a UI option (just /command?) for Craigs noise filter thing either which could be added?

**Comment by Merudo** [comment]
Some final images:

![dude1](https://user-images.githubusercontent.com/7371085/82092890-b05c9980-96bf-11ea-96d9-cb0c50611c47.png)
![dude2](https://user-images.githubusercontent.com/7371085/82092893-b2265d00-96bf-11ea-8517-af0029ff63d5.png)

**Comment by melek** [comment]
> Yea, that top one is definitely more readable.
> 
> I'm not opposed to adding a Graphics? Video? Performance? section (tab?) for 1.8 and add some options. I don't think there is a UI option (just /command?) for Craigs noise filter thing either which could be added?

Though it's a sidenote, the noise should go in the existing accessibility tab (imo)

**Comment by nmeier** [comment]
Such a high quality background image works well, yes. Question for me was whether the performance hit is ok for pattern images. And tokens themselves seemed not significantly better without pixel peeping.
Agree on the settings - that made me focus on the overlay/portrait only as that's something you want to show and be able to read. It's rendered once only, so no significant performance hit to speak off.

There should be an issue for a real rendering hint/quality of rendering setting, yes.

**Comment by Phergus** [comment]
A new issue to add a rendering quality selection to the Application -> Performance preferences for selecting interpolation method and the noise filter settings to Accessibility -> Visual(?) would be a good idea.

The quality improvement doesn't justify the 10x performance hit for bicubic and the 2x hit for bilinear for me but those with gaming rigs I'm guessing won't be impacted.

**Comment by Phergus** [comment]
Tested.  Portrait rendering improved.  No adverse side effects observed.

**Comment by JamzTheMan** [comment]
> > Yea, that top one is definitely more readable.
> > I'm not opposed to adding a Graphics? Video? Performance? section (tab?) for 1.8 and add some options. I don't think there is a UI option (just /command?) for Craigs noise filter thing either which could be added?
> 
> Though it's a sidenote, the noise should go in the existing accessibility tab (imo)

Fair enough and good point.  I think there is also a Performance section with just 2 options. Maybe an assessment of what goes where is needed. A little housecleaning. It's easy enough to move those things around in the same dialog.
