### ISSUE TITLE
States - unable to create new states

### ISSUE THREAD

**Issue by DethangelsShadow** [RPTools/maptool#1711]
**Describe the bug**
Cannot add new States under the Campaign Properties (unless specific order is performed)

**To Reproduce**
1. Go to Edit->Campaign Properties->States tab
2. Enter Name for the state (group or no group)
3. Change Type to a non-image 'type' (ie - cross, diamond, yield)
4. Add button remains grayed out

**Expected behavior**
Changing the Type to a non-Image type should allow the Add button to be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/63486693/80352802-6f046700-8842-11ea-863f-ed2ac918c1eb.png)

**MapTool Info**
- Version: 1.6.1
- Install: Upgrade 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version [[Version 10.0.18362.778]

**Additional context**
If you change the "Type" first...
![image](https://user-images.githubusercontent.com/63486693/80353267-1c777a80-8843-11ea-9d4f-e1774520f428.png)

![image](https://user-images.githubusercontent.com/63486693/80353432-59437180-8843-11ea-9f4d-e2881afba07a.png)

"Add" button is available:
![image](https://user-images.githubusercontent.com/63486693/80353536-81cb6b80-8843-11ea-9304-06ad7fbfc41a.png)

**Comment by DethangelsShadow** [comment]
This is also happening in the 1.8.0 test build:
![image](https://user-images.githubusercontent.com/63486693/80356090-f358e900-8846-11ea-8433-6fc5b95111c6.png)

Typing Name first:
![image](https://user-images.githubusercontent.com/63486693/80356200-1c797980-8847-11ea-9624-fd3373353b6e.png)

Selecting Type first THEN typing name:
![image](https://user-images.githubusercontent.com/63486693/80356286-3dda6580-8847-11ea-9df6-868fc4348341.png)

**Comment by aliasmask** [comment]
Sure would have been handy to know this the other week. Anyway, It seems to be specifically related to the color attribute. Default starts on image. If I change to another type that doesn't have color grayed out, then I can type in a name and the Add button will appear. If, I do something like change it to corner image, then it's still bugged. Also, if there is a name in the field when changing the type it still will not show the Add button. But you can erase the name and change the type to get it to work.

**Comment by emmebi** [comment]
Please assign this to me, I am publishing a PR to fix this.
