### ISSUE TITLE
Selecting an token/object via Map Explorer doesn't update the Selection panel if panel is showing

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1725]
**Describe the bug**
Double-clicking on a object highlights the object on the map but does not update the Selection panel if the panel is open and visible.

**To Reproduce**
1. Make sure Selection panel is open and visible
2. Make sure Map Explorer panel is also visible
3. Drop multiple tokens on map.
4. Double-click on a token in the Map Explorer panel.
5. Token appears selected on map but does not appear on Selection panel.
6. Close and reopen Selection panel and selected token now appears in panel.

**Expected behavior**
Worked in 1.5.14.  Selecting a token via Map Explorer should cause Selection panel to be updated.

**MapTool Info**
- Version: 1.6.1 also broken in current dev
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Worked in 1.5.14

**Comment by Merudo** [comment]
Something in #1471 caused this. Will try to fix.

**Comment by Merudo** [comment]
PR #1749 fixes this.

**Comment by Phergus** [comment]
Tested.  Working as expected.
