### ISSUE TITLE
Allow JavaScript / CSS to be fetched from several large CDN

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1728]
Modify the webview so that it can fetch javascript and CSS from several large CDNs as this will allow people to use common libraries that are not likely to disappear and render a framework unuseable as a self hosted script might.

We can investigate caching these locally or within the campaign file in the future if need be to even further mitigate the chances of not being able to find a required script or needing to run offline.

**Comment by Phergus** [comment]
@Merudo   This is yours to test.

**Comment by Phergus** [comment]
**White lists the following CDNs**
- JQuery CDN (https://code.jquery.com)
- JSDelivr CDN (https://cdn.jsdelivr.net)
- Bootstrap CDN (https://stackpath.bootstrapcdn.com)
- unpkg CDN (https://unpkg.com)
- CloudFlare JS CDN (https://cdnjs.cloudflare.com)
- Google CDN (https://ajax.googleapis.com)

**Also white lists google fonts**
- https://fonts.googleapis.com
- https://fonts.gstatic.com

**Comment by Phergus** [comment]
Pinging @melek

**Comment by melek** [comment]
Okay, I've added a page about these CDN with some bare-bones examples. I've put it in the Cookbook and as an advanced tutorial. I've left it as a stub for now.

- [Whitelisted CDNs](https://lmwcs.com/maptool/index.php?title=Whitelisted_Content_Delivery_Networks)

I've linked it from the frame5 & dialog5 articles, a new overlay roll option article,and the Supported CSS Styles article in a note that tops the page linking folks to the new frame5/dialog5/overlay/CDN features.

**Comment by Phergus** [comment]
@melek Can I consider this tested and approved?

**Comment by melek** [comment]
Sorry for the delay, hadn't actually _tested_ anything... lazily documented without that.

![image](https://user-images.githubusercontent.com/220149/81763628-89665380-9484-11ea-9c02-8c80516314f2.png)

Works, I'd say its tested and approved!

**Comment by cwisniew** [comment]
Linking one of the small test campaigns I used, it has google fonts and animation library. Sadly the animation leaves a little to be desired performance wise.
[animtest.cmpgn.zip](https://github.com/RPTools/maptool/files/4619688/animtest.cmpgn.zip)

**Comment by Phergus** [comment]
That's great.  Thanks!

**Comment by Merudo** [comment]
I think there might be a way to cache animations? Not sure how that would work.
