### ISSUE TITLE
getImpersonatedName doesn't return name of impersonated token

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1732]
**Describe the bug**
The macro function `getImpersonatedName()` doesn't always return the name of the impersonated token in macros. It instead returns the name of the token the macro is on.

**To Reproduce**
1. Create a Dragon token and impersonate it.
2. Create a macro with `[r: getImpersonatedName()]` on an Eagle token.
3. Click on the macro. It will display `Eagle` instead of `Dragon`.

**Expected behavior**
The macro returns the name of the impersonated token.

**MapTool Info**
- Version: 1.5.14., 1.6.1, 1.7.0 A2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

As of 1.7.0 A2, here is the behavior of the `Impersonated` and `Current` token:

Impersonated: the impersonated token returned by `getImpersonatedName()`. It can differ from the one explicitly impersonated through the `Impersonate` right click menu:

- Chat: the impersonated token is the one chosen through the UI
- Macro on GM/Campaign panel, with `Apply to Selected Tokens` unchecked: the impersonated token is the one chosen through the UI
- Macro, with `Apply to Selected Tokens` checked: the impersonated token is the one selected
- Macro on a token, with `Apply To Selected Tokens` unchecked: the impersonated token is the token the macro is on
----

Current Token: the token referred to when using a token function without specifying an id, and the one displayed when printing a message to chat. Can be temporarily changed in a macro with `switchToken()`.

Unless changed by `switchToken()`, the current token depends on the context:

- Chat: the current token is the impersonated token
- Macro:  the current token is one of the selected tokens
- Macro called by `macroLink` / `macroLinkText`: the current token is the target of the link

**Comment by cwisniew** [comment]
Is this with apply to selected checked? If so this is because for the duration of such a macro the selected token is the impersonated token. For multiple tokens this is run once for each token, with each token acting as the impersonated token in turn. If its happening in all cases then its a bug in the non apply to selected.

I would be very wary of changing this for the apply to selected case though.

**Comment by Merudo** [comment]
No, it works this way even if `apply to selected` is unchecked.

**Comment by cwisniew** [comment]
> No, it works this way even if `apply to selected` is unchecked.

Then that bit would be a bug :)

**Comment by Merudo** [comment]
If we don't want to change the current behavior (it may break macros), maybe we could add an extra parameter to `getImpersonated` & `getImpersonatedName`?

Something like local/global or macro/UI, where the default option would return the same as it does currently, but where global/UI always return the token that was impersonated through the right popup token menu option "Impersonate".

**Comment by Phergus** [comment]
Maybe just a boolean option that defaults to returning the current result and if passed a `1` it would get the "global" impersonation.

**Comment by Phergus** [comment]
Tested.  Working as expected.
