### ISSUE TITLE
Leading embedded double quote not processed correctly in JSON Object

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#1733]
**Describe the bug**
When the value stored in a JSON Object property starts with an embedded double quote, that character and the last character of the string are removed.

**To Reproduce**
1. Put the code below into a macro and run it.
2. Note that the last line of output doesn't match the first line (and it should).

```
[h: var = '{ "weapon": "\\"Mournblade\\" mithral rapier"}']
Original JSON: [r: var]<br>
Extracted string: [r: new_var = json.get(var, "weapon")]<br>
New JSON (via json.set): [r: new_json = json.set("{}", "weapon", new_var)]
```

Output appears as:

```
Original JSON: {"weapon":"\"Mournblade\" mithral rapier"}
Extracted string: "Mournblade" mithral rapier
New JSON (via json.set): {"weapon":"Mournblade\" mithral rapie"}
```

**Expected behavior**
Data extracted from JSON values should not require modification when reinserted in order to maintain their content.

**MapTool Info**
- Version: 1.6.1
- Install: macOS DMG

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.6 (latest)

**Additional context**
May be related to #1143 as that one also dealt with quotes.  Also, that issue references additional unit tests but those tests don't include sample data in which a field value begins with a double quote.  (Probably should add such data and also test with a leading single quote.)

This can't be fixed with a UDF that converts all double quotes into `&quot;` entities because passing the string value to a UDF causes the initial double quote to be removed.  If inline code is use to make this replacement, the visual aspects are maintained, but the trailing letter **r** is still trimmed.

The above example code assigns a variable on line 1, but my actual macro retrieves the information from XML via `herolab.XPath()`.  In trying to create as small an example as possible for this report, I found no way to embed a double quote into a string variable.  (I tried backslashes, double backslashes, using single quotes on the outside and double quotes on the inside, and more.)

**Comment by selquest** [comment]
Looks like this may have been resolved in 1.8 dev.  For the provided sample I get the described results in 1.7, but on dev:
```
Original JSON: {"weapon":"\"Mournblade\" mithral rapier"}
Extracted string: "Mournblade" mithral rapier 
New JSON (via json.set): {"weapon":"\"Mournblade\" mithral rapier"}
```

**Comment by Phergus** [comment]
@Azhrei you want to test this with your HeroLab data?  It does appear to have been fixed.

**Comment by Azhrei** [comment]
Thanks, I'll give this a shot. :)

**Comment by Phergus** [comment]
Still working correctly in current dev.  Moving on.
