### ISSUE TITLE
Some jpg images used as maps are displayed as black

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#1737]
**Describe the bug**
Some jpg images used as maps are displayed as black

**To Reproduce**
1. Save the image linked from the following URL: https://jaredblando.com/horde-of-the-dragon-queen/the-hunting-lodge-ground-floor-revised-dmplayer-version-
1. From MapTool, click on Map -> New Map
1. On the Map creation dialog, Click on Map
1. Click on file system
1. Select the jpg image you downloaded
1. The map preview is black; if you click ok, the map appears as black

**Expected behavior**
The image is shown in the new map.

**MapTool Info**
- Version: 1.6.1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional Notes**
Opening the file and re-saving seems to solve the issue. 

_The image in the page linked above is RGB and not CMYK.  It works just fine in both 1.7 and current develop for 1.8.  Likely that paid for image is the CMYK file._

**Comment by wfentress** [comment]
Looks like MapTool doesn't support CMYK JPEGs. I created an sRGB JPEG in Gimp and converted it to CMYK with `convert srgb.jpg -colorspace CMYK cmyk.jpg`. srgb.jpg displayed correctly in 1.7.0-alpha-2; cmyk.jpg was all black.

**Comment by Phergus** [comment]
Actually it does.  This CMYK JPEG image will be rendered incorrectly in Firefox, Chrome, Edge, and Opera.
![bfoz-41,w=300](https://user-images.githubusercontent.com/34379254/80915094-108d2c00-8d0d-11ea-89f7-ac142ded6107.jpg)

But drop it into MapTool and it will display correctly.
![image](https://user-images.githubusercontent.com/34379254/80915190-eb4ced80-8d0d-11ea-841f-6957f0263528.png)

Original image info:
```
C:\>magick identify -verbose bfoz-41.jpg
Image: bfoz-41.jpg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 789x911+0+0
  Units: Undefined
  Colorspace: CMYK
  Type: ColorSeparation
  Base type: Undefined
  Endianess: Undefined
  Depth: 8-bit
  Channel depth:
    Cyan: 8-bit
    Magenta: 8-bit
    Yellow: 8-bit
    Black: 8-bit
```

**Comment by Azhrei** [comment]
Yes, I noticed something similar.  The CMYK seems to fail when the image is not in a JFIF container.

I’m not familiar enough with what other JPEG formats are available (I know about JPEG2000 and JPEG) to know what the differences might be in terms of why the Java image library wouldn’t handle it properly.

**Comment by Phergus** [comment]
The primary difference seems to be that the one that doesn't work has an SVG clipping path element in it.

I'll note that original image also doesn't work with Java 14.

**Comment by JamzTheMan** [comment]
FWIW for JDK14 I did notice CMYK are not working, there is some special handling to with the image libs used for this and will need to double check if it's compatible with JDK14. Next on the list.

Also, I may even open up what we can support, we already have a lib for the PDF extraction as a dependency which brings with it a lot of support for things like PSD, TIFF, and other stuff...

**Comment by JamzTheMan** [comment]
Noting exception message under JDK 14 here to work on image issues for 1.8.x

``` java
sun.awt.image.ImageFormatException: Unsupported color conversion request
	at java.desktop/sun.awt.image.JPEGImageDecoder.readImage(Native Method)
	at java.desktop/sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:141)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
	at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)
```

This block of code should be looked at to see if it needs updated if not the library used. If changed, PDF Extraction should be tested as part of the change.

https://github.com/RPTools/maptool/blob/b0e07187ebaa0aaea18e7dfb22b2ffa28cee2364/src/main/java/net/rptools/maptool/client/MapTool.java#L1709

**Comment by JamzTheMan** [comment]
FYI: Here are 2 images. A CMYK image that didn't load in the <= 1.7.0 but for reference
And a GiantSlayer logo image that does load in 1.7.0 but not in current develop branch.

[A JPEG Test.zip](https://github.com/RPTools/maptool/files/4652962/A.JPEG.Test.zip)

**Comment by Phergus** [comment]
Testing and the images from the linked campaign do display correctly as does another image that showed only black under 1.7.0.

The CMYK jpeg from my post above will display correctly if dropped in from desktop and or Library.  Attempting to load the image directly from the `Page 13.pdf` produces a 0 length JPG .

**Comment by Phergus** [comment]
I've requested some test images from Jared Blando (creator in link of original post) directly so that we can better test.

**Comment by Phergus** [comment]
@emmebi  Jared said you should contact him directly and he will provide you with RGB files to use.

Jared provided me with a sample of the problem map and it works correctly in 1.8.  Considering this issue resolved.

**Comment by emmebi** [comment]
@Phergus understood; feel free to resolve this, thanks for the follow up.
