### ISSUE TITLE
RT Default Dark Theme is not user friendly - 1.6.1

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#1740]
**Describe the bug**
Using the main menu item: Themes to set a dark theme (RT Default Dark). I think this is default installed with MapTool. The Dark theme is clearly not finished, or at least needs lots of tweaking. 

**To Reproduce**
1. Click the main menu item "Themes"
2. Click the item "RT Default Dark"
3. Restart MapTool

**Expected behavior**
I expected a clear and readable interface with a dark theme. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2953375/80915557-5bca2d80-8d53-11ea-8bab-815975083932.png)
Menu items are black on dark grey.

![image](https://user-images.githubusercontent.com/2953375/80915576-7b615600-8d53-11ea-9182-c671eb0ae23f.png)
Map Explorer is even more unreadable. 

![image](https://user-images.githubusercontent.com/2953375/80915661-178b5d00-8d54-11ea-9028-849b962b4c33.png)
Macro group headers suffer the same issue as menus. 

**MapTool Info**
- Version: 1.6.1
- Install: Upgrade from 1.5.14

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10 Home. 1909

**Additional context**
==== MapTool Information ====
MapTool Version: 1.6.1
MapTool Home...: C:\Users\Thomas\.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 809 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\Users\Thomas\AppData\Local\MapTool\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: AMD64 Family 21 Model 56 Stepping 1, AuthenticAMD
PATH...........: C:\Users\Thomas\AppData\Local\MapTool\app;C:\Users\Thomas\AppData\Local\MapTool
Number of Procs: 4

==== User Information ====
User Name: Thomas
User Home: C:\Users\Thomas
User Dir.: C:\Users\Thomas\AppData\Local\MapTool\app

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Qualcomm Atheros AR8171/8175 PCI-E Gigabit Ethernet Controller (NDIS 6.30)
Interface Name: eth0
Address...: 192.168.0.11
Address...: fe80:0:0:0:fdce:7093:4c51:1afa%eth0

Host Address...: 192.168.0.11
Default Gateway: 192.168.0.1

==== Locale Information ====
Country.: Denmark
Language: 
Locale..: Denmark
Variant.: 

==== Encoding Information ====
Default Locale:   _DK
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(32)

==== Internet Gateway Devices ====
Device Name.: SAGEMCOM F@ST3890
Model Name..: BCM9338x
Manufacturer: Sagemcom
Model Number: 1.0
Model Desc..: Broadband router
Firmware....: Custom/1.0 UPnP/1.0 Proc/Ver
External IP.: 176.23.121.33

**Comment by Phergus** [comment]
Some of the issues are theme problems while some are hard-coded color settings within the MapTool code.   Many of the MapTool issues have already been addressed for 1.7.  See: #1635

**Comment by Tdue21** [comment]
Oh, I missed that one. You can close this one as a duplicate, if the other one covers the same.
