### ISSUE TITLE
bug in movedOverToken

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#1755]
first tim I'm trying to do this (issuing a bug report on github) so im hoping im doing this right:

I can be short though

this works:
```
    [t = json.get(lastPath,0,0)]
    [movedOff = !json.isEmpty(movedOverToken(padName,t))]
```
and this doesnt:
```
    [movedOff = !json.isEmpty(movedOverToken(padName, json.get(lastPath,0,0)))]
```
: java.lang.ClassCastException: com.google.gson.JsonArray cannot be cast to java.base/java.lang.String

**Comment by Phergus** [comment]
Fixed by some change in the past.
