### ISSUE TITLE
moveToken() does not work correctly with image translated in layout

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#1757]
**Describe the bug**
Using a macro that moves a token a given distance -x and then moves the token the same distance +x. The token should end up in the original position.

This works as expected for this case
![image](https://user-images.githubusercontent.com/45483160/81087924-e4e88c80-8f2c-11ea-81a8-a0a10b079b9c.png)

But does not work as expected for this case
![image](https://user-images.githubusercontent.com/45483160/81088024-021d5b00-8f2d-11ea-9535-63525208f4fc.png)

Token moves about 16 pixels left then about 66 pixels right where it should be moving 43 picxels each way.

**To Reproduce**
[Use this token](https://www.dropbox.com/s/h1gm7qd308f61h8/Buggy_Opening_Swing_Door.rptok?dl=0)

1. In the selection pane, click the macro open/close a couple of times.
2. Translate the image to the right in the layout panel as shown above.
3. In the selection pane, click the macro open/close a couple of times.

**Expected behavior**
The translation of the image in layout should not affect the x,y positioning of the token.

**Screenshots**
**With no translation**
Start
![image](https://user-images.githubusercontent.com/45483160/81088840-2299e500-8f2e-11ea-9b8c-dbe14ea77534.png)
click open
![image](https://user-images.githubusercontent.com/45483160/81088925-3fceb380-8f2e-11ea-985b-ff4ec2fb3260.png)
click close
![image](https://user-images.githubusercontent.com/45483160/81088983-5248ed00-8f2e-11ea-964a-cd700eccffa5.png)

**With translation**
Start
![image](https://user-images.githubusercontent.com/45483160/81088840-2299e500-8f2e-11ea-9b8c-dbe14ea77534.png)
click open
![image](https://user-images.githubusercontent.com/45483160/81089104-845a4f00-8f2e-11ea-9eb7-5637826028e4.png)
click close
![image](https://user-images.githubusercontent.com/45483160/81089189-9fc55a00-8f2e-11ea-8731-3c26d14636d4.png)

**MapTool Info**
- Version: 1.5.10

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
This does not meet the criteria for the getTokenX exception listed in the wiki.

**Comment by Phergus** [comment]
Simpler token with macros showing issue.
[MoveMe.rptok.zip](https://github.com/RPTools/maptool/files/4583433/MoveMe.rptok.zip)

**Comment by Merudo** [comment]
I can reproduce for non snap-to-grid tokens.

Does the bug also occurs for snap-to-grid tokens?

**Comment by Merudo** [comment]
PR #1792 fixes this.

**Comment by Phergus** [comment]
Tested on all Layers with/without snap.  Freesize & named sizes.
