### ISSUE TITLE
User-friendly functions like sum(), min(), and max() for JsonArrays

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#1764]
**Is your feature request related to a problem? Please describe.**
Functions like `getRolled()` return arrays of numbers, but the existing `sum()`, `min()`, and `max()` functions do not accept array arguments.

**Describe the solution you'd like**
User-friendly functions like `math.arraySum()` or similarly named functions that operate on JsonArrays and string lists of numeric elements to total/average/etc the elements.

List of functions to be added from discussion below:
* `math.arraySum()`
* `math.arrayMin()`
* `math.arrayMax()`
* `math.arrayMean()`
* `math.arrayMedian()`
* `math.arrayProduct()`
* _corresponding `math.listSum()` and similar that operate on string lists_

**Describe alternatives you've considered**
The existing `json.path.read(theList,"sum()")` comes closest among current functions, but I think a built-in capability would be more approachable and easier to find.

**Additional context**
I'll start work on implementation, but I think there's some outstanding discussion about most appropriate naming/prefix conventions.
The original thought was just to modify the existing `sum()` and similar functions, but those are defined directly in the parser lib and would not be appropriate for json support (and also are used for things like the `+` operator itself, and probably shouldn't be mucked about with).

**Comment by selquest** [comment]
After continued discussion on Discord, it seems the consensus is to do this as `math.X()` functions:
* `math.sum()`
* `math.min()`
* `math.max()`
* `math.mean()`

Any other core operations that should be included?

**Comment by Phergus** [comment]
* `math.median()`

The parser also has `multiply()`, `divide()`, `subtract()` though I'm not sure just how useful those are.

**Comment by selquest** [comment]
Adding `math.multiply()` might make sense, but I have a hard time imagining a use case for multi-argument division or subtraction like this.

Updated description to include list of planned functions, will add more if continued discussion recommends them.

Can you assign this to me please?

**Comment by Phergus** [comment]
I assume those questionable functions were put in because it's pretty much one chunk of code switching between different operators.  I doubt anyone would miss them.

**Comment by JamzTheMan** [comment]
*maybe* `subtract` would be useful for getting a final negative modifier? I would think `sum()` would suffice but no idea how people may store or use typical combat modifiers or such.

**Comment by bubblobill** [comment]
math.product not math.multiply

**Comment by selquest** [comment]
Implemented methods to operate on arrays and lists.

I took the path of two different versions of each function (`math.arraySum()` and `math.listSum()`) because allowing flexibility between the two was seeming more likely to result in user error than user convenience.

**Comment by Phergus** [comment]
Tested.  Working as expected.

**Comment by melek** [comment]
Not sure how to document this. Should I just ensure these are in the list on https://lmwcs.com/rptools/wiki/math ?

**Comment by Phergus** [comment]
@melek  Yeah.  I think that should be all that's needed.

**Comment by selquest** [comment]
Added docs for the new functions.

**Comment by bubblobill** [comment]
When this was originally discussed I actually wanted mathematical operations between arrays for convenience of performing some vector maths
i.e
```
[0,1,2,3,4] x [0,1,2,3,4] = [0,1,4,9,16]
[0,1,2,3,4] + [0,1,2,3,4] =[0,2,4,6,8]
[0,1,2,3,4] - [0,1,2,3,4] = [0,0,0,0]]
[0,1,2,3,4] / [0,1,2,3,4] = [e,1,1,1,1]
```
Have since ventured into the realms of coding and made them myself as
- array.divide
- array.product
- array.subtract
- array.sum
- array.sumProduct

Not sure if they are up to snuff yet but they work.

**Comment by kwvanderlinde** [comment]
@bubblobill A new feature request should be opened for it as this one is already complete.
