### ISSUE TITLE
Add a macro function to convert markdown to HTML

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1765]
**Is your feature request related to a problem? Please describe.**
Markdown is often a lot easier for people to write and understand than HTML for simple formatting and is often enough for what most people need.

**Describe the solution you'd like**
A macro to convert Markdown into HTML so that it can be displayed in a frame5 or dialog5. 

**Additional context**
This will not add a dedicated control for displaying Markdown nor add Markdown support directly to frame5/dialog5. This functionality will be added later.

**Comment by cwisniew** [comment]
Pull request #1766 contains details of how to use and example output.

**Comment by mrkwnzl** [comment]
Just wanted to say that this is awesome! Thanks for that!

**Comment by Phergus** [comment]
Tested.  A few odd spacing issues with lists and the strike-through didn't work on the markdown types I tried but is otherwise working well.

**Comment by Merudo** [comment]
Nice! Markdown is indeed much easier on the eyes than HTML.

Is there any chance a HTML to Markdown function could be implemented? Obviously it wouldn't be able to convert everything, but it would help moving from HTML to Markdown and back to HTML.

From flexmark:

> Extensible HTML to Markdown Converter module: flexmark-html2md-converter. Sample: HtmlToMarkdownCustomizedSample.java

**Comment by mrkwnzl** [comment]
Is it possible to have this for non-HTML5 frames and dialogs as well? While it seems to work somewhat, it doesn’t seem to be working quite right.

**Comment by Phergus** [comment]
I'm guessing that the HTML it outputs will be beyond the HTML 3.x  / CSS 1.x that the older frames/dialogs support.

**Comment by mrkwnzl** [comment]
I just tested this with some HTML code markdown outputs and using that directly in a frame. It’s the same result as with `markdownToHTML()`, which is a good sign. It just doesn’t look as good, but (at least for basic Markdown), there shouldn’t be anything in there HTML 3.2 can’t handle. Maybe I can do something about the looks using my css macro.
