### ISSUE TITLE
Form Submit: the <select multiple> element only return one element

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1782]
**Describe the bug**
The `<select multiple>` element in frame5 / dialog 5 lets the user select multiple values from the list.

However, on form submission, only the first selected value is returned.

**To Reproduce**
1. Make a macro `print` in the Campaign panel with the code `[r: macro.args]`
2. Run the following code:

```
[frame5("test"):{
	[h: processorLink = macroLinkText("print@Campaign", "all")]
	<form action="[r:processorLink]" method="json">

	<select name="options" multiple>
          <option value="V1">Choice 1</option>
          <option value="V2">Choice 2</option>
          <option value="V3">Choice 3</option>
	</select>
	
	<input type="submit">
	</form>
}]
```
3. Select multiple options, and press Submit. Only the first option selected is returned.

**Expected behavior**
A json array containing all the selected options is returned.

**MapTool Info**
- Version: 1.6.1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1783 fixes this.

**Comment by Phergus** [comment]
Tested.  Now works as expected.
