### ISSUE TITLE
Several places are not showed translated text

### ISSUE THREAD

**Issue by fw** [RPTools/maptool#1790]
**Describe the bug**
Some elements that will be showd japanese are not showed correctly.

* Server Info dialog
* Export Screenshot dialog
* Export Campaign dialog
* Add Resource to Library... dialog
* Macro editing status ("Ready" and "Saved" showed avobe "RUN MACRO" button)
* "VBL Optimization" in VBL tab in Edit Token dialog.
* "Token Visibility" in VBL tab in Edit Token dialog.

**To Reproduce**

*Server Info dialog*

1. Launch the Maptool with language setting is Japanese.
2. Go to 'File' menu then click 'Connecting Information' ('接続情報' in ja.)
3. Bring dialog 'Server Info' ('サーバー情報' in ja.).
4. There are showed rectangle characters ('□□□□') at places where 'Server Info', 'Name:', 'Local Address:', 'External Address:' and 'Port:'.

![mt-server-info-dialog](https://user-images.githubusercontent.com/29275/81484353-ce6d6880-927f-11ea-8544-dabb0b4ae5eb.jpg)

*Export Screenshot dialog*

1. File -> Export -> Screenshot or Screenshot as. ('書き出し' -> 'スクリーンショット' in JA)
2. There are showed rectangle characters ('□□□□') at place where 'Export Screenshot' with bolded.

![mt-export-screenshot-dialog](https://user-images.githubusercontent.com/29275/81484368-e6dd8300-927f-11ea-9c48-790054c49878.jpg)

*Export Campaign dialog*

1. File -> Export -> Campaign as. ('書き出し' -> 'キャンペーンを別名で保存' in JA)
2. There are showed rectangle characters ('□□□□') at place where 'Export campaign to a previous version' with bolded.

![mt-export-campaign-dialog](https://user-images.githubusercontent.com/29275/81484373-ee049100-927f-11ea-8ede-5a27a6e4500a.jpg)

*Add Resource to Library dialog*

1. File -> Add Resource to Library... ('素材保管庫に素材を追加' in JA)
2. There are showed rectangle characters ('□□□□') at place where
    * 'Local Directory', 'Path:' and left and right parensis in 'Local Directory' tab.
    * 'Name:' and 'URL:' in 'URL' tab.
    * 'Library' in 'RPTools Library' tab.

![mt-add-resource-dialog](https://user-images.githubusercontent.com/29275/81484381-f78df900-927f-11ea-9ab8-4a8d84f8597f.jpg)
![mt-add-resource-dialog-2](https://user-images.githubusercontent.com/29275/81484384-f9f05300-927f-11ea-821e-b1bd81c1d36e.jpg)
![mt-add-resource-dialog-3](https://user-images.githubusercontent.com/29275/81484387-fc52ad00-927f-11ea-8e32-81cc224335f1.jpg)

*VBL tab in Edit Token dialog*

1. Launch the Maptool with language setting is Japanese.
2. Drop a image on Token layer.
3. Doubleclick new token and showed Edit Token dialog.
4. Select VBL tab ('遮光レイヤー' in JA).
5. There are showed rectangle characters ('□□□□') at places where are 'VBL Optimization' and 'Token Visibility'.

![mt-edit-token-dialog](https://user-images.githubusercontent.com/29275/81484391-02e12480-9280-11ea-98bd-bf0f945e8c10.jpg)

*Code status in Macro Editor*

1. Show Campaign Panel ('キャンペーンマクロ' in JA).
2. Create new macro button.
3. Edit it and open Macro Editor.
4. There are showed 'Ready' (not Japanese) above 'RUN MACRO' button ('マクロ実行' in JA).
5. Type anything in the editor.
6. Its status change '□□□□'.
7. Click 'APPLY' button ('適用' in JA).
8. There are still showed '□□□□'.

![mt-macro-editor-ready](https://user-images.githubusercontent.com/29275/81484516-ec879880-9280-11ea-92aa-223fa56454af.jpg)
![mt-macro-editor-ready-2](https://user-images.githubusercontent.com/29275/81484520-f01b1f80-9280-11ea-9baa-fd83da9df578.jpg)

**Expected behavior**
Displaing translated Japanese text.

**Screenshots**
See above.

**MapTool Info**
- Version: 1.7.0-beta-2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
I looked for on themes both Default and TL Golden Sans 13.

**Comment by Merudo** [comment]
Thank you for the report. I assume these fields have hard-coded fonts that are not supported by the Japanese language.

**Comment by Phergus** [comment]
Yup.  That's what happens when it uses the Trebuchet and some other fonts as they don't have the full character set.

Try this version of the TL_Golden_Sans_13 theme.  Unzip, rename (so it doesn't get overwritten) and drop it in the `themes/ui` folder under `.maptool-rptools`.  That should fix a couple of those.  Some are probably hard-coded however.

[TL_Golden_Sans_13.zip](https://github.com/RPTools/maptool/files/4604595/TL_Golden_Sans_13.zip)

**Comment by Merudo** [comment]
Regions supported by Tahoma:
![image](https://user-images.githubusercontent.com/7371085/81485983-2b810400-9217-11ea-952c-e127b40c37fd.png)

**Comment by Merudo** [comment]
@Phergus the problematic fonts are coded in the Abeille forms. I could change them to something else. What would you recommend?

**Comment by Phergus** [comment]
Yeah.  Tahoma is another one.   I've just been changing the themes to use SanSerif.  Seems to be working.

**Comment by Merudo** [comment]
PR #1791 fixes this.

**Comment by Phergus** [comment]
Tested.  All dialogs noted above now display Japanese the correct characters.
