### ISSUE TITLE
Allow for form completion and submit in the chat box

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1797]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to submit a form displayed in the chat (message panel).

Form elements such as `input`, `select`, `text` etc. can be displayed, but their content can't be submitted.

**Describe the solution you'd like**
Forms printed to the chat box should be submitable through the usual macroLinkText machinery.

**Additional context**
Here is an example of implementation that could work once this feature is implemented.

After Fireball, the GM receives a form in the chat. The GM selects the damage received by each creature, then clicks the button to submit the form. The macro can then automatically apply damage.

![](https://cdn.discordapp.com/attachments/667250337350156290/708975188498186290/unknown.png)

Currently, this does not work because clicking the button does nothing.

**Comment by Azhrei** [comment]
This sounds like a nice feature.

I’m curious to see how this will work.  Since the chat panel is Swing there’s no JS, so each form will need a separate id for submission (I assume; otherwise, how will **submit** know which form elements to send?).

Will the selections be saved so that they appear in the chat log when the session is over?

**Comment by Merudo** [comment]
PR #1806 implements this.

**Comment by Merudo** [comment]
> I’m curious to see how this will work.  Since the chat panel is Swing there’s no JS, so each form will need a separate id for submission (I assume; otherwise, how will submit know which form elements to send?).

Elements within a form have their data included when the form is submitted.

**Comment by Phergus** [comment]
Using this macro:
```
[h: processorLink = macroLinkText("print@Campaign", "all")]
<form action="[r:processorLink]" method="json">

<label for="fname"><b>My Form</b></label><br>
First:  <input type="text" name="fname" value="John"><br>
Last:  <input type="text" name="lname" value="Doe"><br><br>

<input type="checkbox" name="cb1" value="A"> A
<input type="checkbox" name="cb2" value="B"> B
<input type="checkbox" name="cb3" value="C"> C
<input type="checkbox" name="cb4" value="D" checked="checked"> D<br>

<input type="submit" name="button" value="Submit">
</form> 
```
I get this in chat:
![image](https://user-images.githubusercontent.com/34379254/81750080-18b23d80-946a-11ea-8633-5d6b51d369ec.png)

Appears to be working as expected.

**Comment by Phergus** [comment]
Note that the submit button can be pressed multiple times.
