### ISSUE TITLE
Quotes in light segments array of Light definitions of `getInfo("campaign")` are being escaped

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1799]
**Describe the bug**
The light definitions returned by `getInfo("campaign")` are improperly formed. The quotes around the  object keys in the `light segments` array are being escaped with `\` and the objects themselves are quoted.

Example from default campaign:
```
"light segments":[
"{\"facingOffset\":0.0,\"radius\":5.0,\"arcAngle\":360.0,\"isGM\":false,\"ownerOnly\":false}",
"{\"paint\":{\"color\":1677721600},\"facingOffset\":0.0,\"radius\":10.0,\"arcAngle\":360.0,\"isGM\":false,\"ownerOnly\":false}"
]
```

**To Reproduce**
1. Run `[r: lights = json.path.read(getInfo("campaign"),"['light sources']['D20'][0]['light segments']")]`
2. Note return has quote marks on object `keys` escaped and the objects themselves in quotes.
  `["{\"facingOffset\":0.0,\"radius\":5.0,\"arcAngle\":360.0,\"isGM\":false,\"ownerOnly\":false}","{\"paint\":{\"color\":1677721600},\"facingOffset\":0.0,\"radius\":10.0,\"arcAngle\":360.0,\"isGM\":false,\"ownerOnly\":false}"]`

**Expected behavior**
Expected this:
`[{"facingOffset":0.0,"radius":5.0,"arcAngle":360.0,"isGM":false,"ownerOnly":false},{"paint":{"color":1677721600},"facingOffset":0.0,"radius":10.0,"arcAngle":360.0,"isGM":false,"ownerOnly":false}]`

**MapTool Info**
- Version: 1.6.1+
- Install: Any

**Desktop:**
 - OS:  Windows
 - Version: 10

**Comment by Merudo** [comment]
PR @1800 fixes this.

**Comment by Phergus** [comment]
Tested.  Returned JSON is correct now.
