### ISSUE TITLE
Initiative panel 'Next' button is a dropdown and it's not obvious why

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#180]
The **Next** button on the initiative panel has a dropdown arrow attached to its right side, but it's not clear what that arrow does, nor is there a tooltip that pops up when the mouse hovers over it.

I suggest we add a separate **Settings** button to the right of the **Round** number that is a dropdown menu and remove it from the **Next** button.  Oh, and we should add some tooltips as well.

**Comment by irisiflimsi** [comment]
I wouldn't completely move it. There are settings (Hide NPCs) combined with operations on the list (previous). The latter I would still see in the dropdown list. To be precise: I see "previous", "sort", "toggle wait", "set/reset", "remove token" as part of the drop down, the rest as settings, although I feel that "add all" is wrong here altogether.

If you are looking for a previous, I find it natural to have a look at the dropdown next to "next". And just dropping down doesn't change any state, the menu looks natural enough I don't think it should be changed drastically.

**Comment by Azhrei** [comment]
All good points!  It'll need to be split, definitely. :)

**Comment by selquest** [comment]
This would seem to be satisfied by 1.7 and beyond, and can probably be closed.

**Comment by Phergus** [comment]
True.
