### ISSUE TITLE
Token image handling is slow

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1801]
**Describe the bug**

Switch back and forth between two maps with tokens - notice that switching is slow.

Copy a set of tokens, switch to another map, paste - notice that tokens are placed but background loading images is progressive and slow.

Select a set of tokens, start dragging - notice the initial delay before the drag previews smoothly follows the mouse.

**To Reproduce**

Do any zone switching, copy/pasting, or dragging with 100 or so tokens to really notice the effect.

**Expected behavior**

All these activities should be pretty instant as image data is already loaded. Instead there is image data that is force-uncached without need and temporary images generated in getRGB/setRGB loop.

**Screenshots**

dragging a large number of tokens

![image](https://user-images.githubusercontent.com/312857/81512874-247af400-92f2-11ea-8b2c-6237a272583d.png)

**MapTool Info**
- Version: 1.6 + 1.7 beta

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by nmeier** [comment]
I'm working on a PR that speeds up rendering of tokens by not generating images in Java but an alpha composite. The ImageManager can also be sped up by using softreferences - allows GC to reclaim memory without losing all already generated images immediately.

**Comment by nmeier** [comment]
Need to test with a set of tokens that have different effects on them (halo, facing, etc.).

Noteworthy difference - instead of rendering the old token position in gray, it's now rendered with half the opacity of the token. This could make a barely visible token even less visible. Don't think that matters by FYI.

**Comment by Phergus** [comment]
Tested with current develop.

Performance is much improved for the initial drag after selection.  Nearly instantaneous.

No issues seen dragging mass tokens (200+) with Facing, States, Halos, Light Emblem or combinations of same.

Big issue with changing facing on tokens.  Once facing is changed, States are being rendered offset down and right across the map.  Location dependent upon zoom level.  Does not happen under 1.7.0-beta-2.

![FacingChangeGlitch](https://user-images.githubusercontent.com/34379254/81568953-c4209c80-935b-11ea-80c3-235d4d1c3f37.jpg)

Test campaign:

[MassTokens170b2.cmpgn.zip](https://github.com/RPTools/maptool/files/4609942/MassTokens170b2.cmpgn.zip)

**Comment by nmeier** [comment]
thx for testing, looking into it

**Comment by nmeier** [comment]
ok, know what's going on - just have to untangle the two PRs I have going

![image](https://user-images.githubusercontent.com/312857/81574579-fc33d980-9373-11ea-8e0c-ad1a0f97e0ea.png)

**Comment by Phergus** [comment]
Further testing.
 
- States issue fixed.
- Startup when dragging large numbers of tokens is faster.
- Swapping maps with large numbers of tokens is noticeably faster.
- Copying large numbers of tokens from map to map is faster.

Looks good.
