### ISSUE TITLE
Hidden Tokens visible on Map Explorer

### ISSUE THREAD

**Issue by rtakehara** [RPTools/maptool#1803]
**Describe the bug**
If I have **Strict token ownership** unchecked, a token set to be not visible to players, placed on the hidden layer will still be visible on the Map Explorer Widow if set PC

**To Reproduce**
1. Start a server with strict token ownership disabled
2. create a token and set it as PC
3. Hide it from players either putting it on Hidden layer or setting Visible to players unchecked, or both
4. Connect an instance of MapTool on the server as a Player.
5. Open the Map Explorer window, the supposed hidden token will show there, if it's in the hidden layer it will show on both Hidden and Player folders on the map explorer

**Expected behavior**
Even if set as PC, players shouldn't be able to see hidden tokens.

**Screenshots**
![Screenshot (32)](https://user-images.githubusercontent.com/49849179/81514549-2cdd2a00-9306-11ea-80ee-9dbbe2bc0489.png)
![Screenshot (33)](https://user-images.githubusercontent.com/49849179/81514559-32d30b00-9306-11ea-8122-3ba3d019af15.png)

**MapTool Info**
- Version: 1.6.1
- Install: Upgraded

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
The same bug happens with "Strict token ownership" if  the player is given ownership of the PC token.

**Comment by Merudo** [comment]
PR #1840 fixes this. 

New logic for PC tokens:

 <ol>
<li>If the token is not a PC, return <code>false</code>.
<li>If the current player is the GM, return <code>true</code>.
<li>If individualized view is on or the token is visible only to owner, and the token is not
 owned by the current player, return <code>false</code>. (Takes into account
 StrictTokenManagement and the AllPlayers ownership flag).
<li>If the token is not visible to players or is on the hidden layer, returns false.
<li>Otherwise, return true.
</ol>

**Comment by Azhrei** [comment]
I don’t agree with the first test.  It means that players with ownership of an NPC can’t see that NPC in the map explorer, correct?

I will sometimes give players ownership of a henchman or hireling so they can move it themselves.  (Although such tokens don’t get vision so they don’t expose.)  They Howe are usually non-combat NPCs, but still...

**Comment by Merudo** [comment]
Sorry for the confusion! I do tend to be edit my messages after the fact, as I usually make a few typos that I somehow only see once my post is submitted :/

**Comment by Phergus** [comment]
Tested.  Tokens on Hidden layer whether PC/NPC or owned by Player are not visible in Player's Map Explorer.
