### ISSUE TITLE
Rework zone (map) selection to make it simpler and behave like a normal popup 

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1804]
**Describe the bug**

The zone (map) selection component behaves unusual for a swing component and doesn't work well with LnF

* the popup hides the button
* the entries are rendered complicately with a button signalling the current zone

|  ![image](https://user-images.githubusercontent.com/312857/81515218-f8b33a80-9300-11ea-9df1-5775efede214.png)  |  ![image](https://user-images.githubusercontent.com/312857/81515206-eafdb500-9300-11ea-9ae4-973122c3585e.png) |

**To Reproduce**

Click on the zone selection button in top right corner - observe the popup handling and how the items are rendered

**Expected behavior**

Make it a simple menu - checkbox on current zone

![image](https://user-images.githubusercontent.com/312857/81515275-3c0da900-9301-11ea-9d23-a8f7bc7e3d9d.png)

**MapTool Info**
- Version: 1.6/1.7 beta

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by nmeier** [comment]
PR coming

**Comment by JamzTheMan** [comment]
Be sure to test with a lot of maps. It was recently changed to give it a scrollbar.

**Comment by Phergus** [comment]
@nmeier This change doesn't handle more than 20 maps.  Needs the scroll bar.

Here's a campaign file with 50+  maps.

[50PlusMaps156.cmpgn.zip](https://github.com/RPTools/maptool/files/4607515/50PlusMaps156.cmpgn.zip)

**Comment by Phergus** [comment]
Also it does this:
```
      BufferedImage thumb =
          MapTool.takeMapScreenShot(new PlayerView(MapTool.getPlayer().getRole()));
```
But doesn't use it.

**Comment by bubblobill** [comment]
Sounds like an image that should appear on hover that didn't eventuate

**Comment by nmeier** [comment]
yeah, sorry, that was not a good PR. I was playing with a thumbnail but didn't get it to work yet. And scrolling is broken. Looking into it.

**Comment by Phergus** [comment]
Scrolling is fixed and now noticed that the Hidden maps no longer have "highlighting" to indicate they are hidden.

I know.  Never happy.  ;)

**Comment by nmeier** [comment]
That's fine - I have to catch up what's possible in MT - hidden maps, can indicate that. checking how that looked in 1.6

**Comment by nmeier** [comment]
I think it's best to keep standard elements like that popup fairly plain and adhering to it's function: a list to pick from. Without going much further into custom rendering I'm thinking this could work:

* The menu works as a natural LnF component
* checkbox denotes current renderer
* highlight as per LnF shows current selection being considered
* if not the current renderer (checkbox) a little symbol denotes that map is not visible
- if the current selected map is also not visible to players one only sees the checkbox 

![image](https://user-images.githubusercontent.com/312857/81613034-beeb3e00-93ab-11ea-8abf-7c69d1da6476.png)

Alternative

* The menu works as a natural LnF component
* item that can't be selected denotes current renderer (no reason to select the current renderer anyways)
* highlight as per LnF shows current selection being considered
* a little symbol denotes that map is not visible for current or any renderer

![image](https://user-images.githubusercontent.com/312857/81613513-9ca5f000-93ac-11ea-873d-567118a2d230.png)

Does one of those work?

**Comment by Phergus** [comment]
I think that first one is the most intuitive.  Very clear which one is current, which one is pending selection and which ones are hidden.

**Comment by Phergus** [comment]
I think it looks a lot better now.

![image](https://user-images.githubusercontent.com/34379254/81698104-c26ddc00-9422-11ea-81ed-f2ed6e229ba5.png)

Your map selector list stays inside the MT frame for you?  Mine doesn't and didn't before either.

**Comment by Phergus** [comment]
It seems that the more maps the wider the dropdown.

Default
![image](https://user-images.githubusercontent.com/34379254/81735540-6de25500-9452-11ea-9703-8d4155aff500.png)

2 Maps
![image](https://user-images.githubusercontent.com/34379254/81735558-73d83600-9452-11ea-988e-74f7b67ab463.png)

50ish Maps
![image](https://user-images.githubusercontent.com/34379254/81735570-79358080-9452-11ea-8770-529f572d46b4.png)

**Comment by nmeier** [comment]
Hmm, just one map changing from long name to short name doesn't shrink the popup. Something with the preferred size on the contained menu item that doesn't work. Investigating.

**Comment by nmeier** [comment]
ok, I know what's going on - holding on to a JPopupMenu with menuitems where the length of the items inside change over time doesn't jive as the component remembers old text value stats. Swing is fun.

The old design had less Swing/LNF to hit this. I'll have a fix shortly.

**Comment by nmeier** [comment]
So 1.6.1 does a bit better with the popup staying in the frame, it doesn't take the scrollbar into account though

![image](https://user-images.githubusercontent.com/312857/81762272-3bf4e100-949a-11ea-8c80-352d896db36f.png)

I'm going to push a change that adresses these remaining issue

1. make popup right align with the button to not go beyond the window

![image](https://user-images.githubusercontent.com/312857/81762375-79f20500-949a-11ea-9462-ec8e0082495a.png)

2. use minimum amount of space - whether map names are long, short, changing

![image](https://user-images.githubusercontent.com/312857/81762446-a279ff00-949a-11ea-9a13-fb31565b0862.png)

![image](https://user-images.githubusercontent.com/312857/81762466-af96ee00-949a-11ea-8a2a-fc20ca4a64ec.png)


3. use minimum the button width - if there were super short map names by chance

![image](https://user-images.githubusercontent.com/312857/81762526-d1907080-949a-11ea-92e7-7f313123779c.png)

**Comment by Phergus** [comment]
Still going slightly out-of-bounds for me when it is a mix of short and long names.  The longer names were added after the menu had already been viewed once.

![image](https://user-images.githubusercontent.com/34379254/81961941-4618fb80-95d0-11ea-9d32-64fc7d1c1f05.png)

**Comment by Phergus** [comment]
I assumed the checkbox was in a separate column so that current map could also be marked with the slash/eye.
![image](https://user-images.githubusercontent.com/34379254/81965861-e3c2f980-95d5-11ea-873d-424b8df2cf98.png)

**Comment by nmeier** [comment]
ok, just really keyed in that you have to columns for the checkbox/eye - I only have one. Which theme is that? Those couple of pixels might not be accounted for when the preferred size is calculated.

**Comment by nmeier** [comment]
Found the theme that enables Theme.menuAllowTwoIcons. The preferred size calculation seems wrong   for the tinylf, worse with two icons. Debugging what result is generated.

**Comment by Phergus** [comment]
Hmm.  A theme issue.
I'm using this one: 
[MT_Flat_Green_Sans_14_TableRows.zip](https://github.com/RPTools/maptool/files/4630466/MT_Flat_Green_Sans_14_TableRows.zip)

Probably some weird setting in TinyLaF.

**Comment by JamzTheMan** [comment]
Wait when did we get an eye column lol, does that replace the hash marks over the map name?

**Comment by nmeier** [comment]
So some of the LnF themes can chose to show two columns - checkbox column for selection - eye for visible. It's a little bit of wasted space imo but hey.

I found an issue with inset calculation that makes this an issue for those cases. One more PR coming.

Note that the shadow of the menu is part of the inset (pixel peeping taught me that) - so the menu is not snug with the right side. Don't want to further play with that so there will be a little bit of (deterministic at least) gap

![image](https://user-images.githubusercontent.com/312857/81981985-13d2c280-95ff-11ea-8f87-a383e7d766ab.png)

**Comment by Phergus** [comment]
I found the theme setting.  Not sure why that is turned on.  Probably because I modified one of Rod's themes to make the base theme for it.  A little gap on the side/bottom for the shadow looks fine to me.

@JamzTheMan  Yes.  The eye symbol replaces the hashing.

**Comment by Phergus** [comment]
Tested with a couple different themes.  No layout issues seen.  Map selection working correctly.  Current and hidden map indicators working.

**Comment by melek** [comment]
The updated 'Select Map' functionality has been documented:
https://lmwcs.com/rptools/wiki/MapTool_User_Interface#Select_Map_Dropdown

**Comment by melek** [comment]
Additionally updated Introduction to Mapping article (had reallly old images):
https://lmwcs.com/rptools/wiki/Introduction_to_Mapping#Selecting_Maps
