### ISSUE TITLE
Using spaces vs tabs

### ISSUE THREAD

**Issue by irisiflimsi** [RPTools/maptool#181]
See https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/

On a more serious note, I read the FXML code from tokentool and it is unbearable on the Github web frontend. I'd have to clone the repo for just a quick glance.

So take this with a grain of salt, but I have always been on the side of spaces.

**Comment by JamzTheMan** [comment]
I think you meant to put this in the TokenTool repo, we don't have FXML here... yet! :)

**Comment by JamzTheMan** [comment]
Here's a fix for you, which you couldn't do with spaces btw... :)

Add ?ts=2 to the end of the URL (or ?ts=4, etc) to change the tab spaces on github...

**Comment by Jaggeroth** [comment]
http://www.bbc.co.uk/news/technology-40302410

**Comment by JamzTheMan** [comment]
@irisiflimsi You have to use ?ts=4 if it's tabs not?s=4

And I feel ya.  Coding "style" is always going to be a personal touch but to be honest, as long as I'm doing any coding here, I'll ALWAYS use tabs. Spaces annoy the F out of me. :-)  I'm not really going to change that so someone can view code online easier, especially when there are work arounds and various other ways to view the code. (There are other apps/editors/etc to view code with).

**Comment by irisiflimsi** [comment]
Seems my screen font is too teeny, I couldn't read "ts", sorry. Probably to fit more code on screen.

It's okay to close this with wontfix - at least it is labelled as something that could have been fixed, not as something that was correct in the first place...

Coincidently, indentation in TokenTool.fxml is wrong starting line 142 and I'm not going to fix it, hah.

And yea, I'll stick with the added salary :-p

(Truth be told, I thought tabbing was inherited from Trevor or so and we just stuck with it out of tradition. I wasn't aware that we had actual proponents. Which boggles the mind.)

**Comment by Phergus** [comment]
There are (or were) style guidelines somewhere for MT and I thought spaces were called out in it but maybe not.  I remember years ago setting Eclipse to use the prefs file that Trevor had made available.

Clearly spaces are the superior choice but some people like using manual typewriters and quills for writing so...

**Comment by JamzTheMan** [comment]
Well lets get FXML out of the way, I'm not updating/creating/editing FXML files. I use SceneBuilder (why wouldn't you?) and it generates those files. Sure, I have manually edited them for a few things but once you open it in SceneBuilder, it reformats the FXML again anyway.  I really don't care how that file is formatted honestly.

I suppose the XML files created in MapTool by Abilie Forms probably bugs you too? :-)

And ya, there are "Style Guidlines" and they were exported from Ecllipse so Spotless applies those formatting rules as they stand.

**Comment by irisiflimsi** [comment]
You can do more things with FXML than with SceneBuilder - at least this is what I remember. I think it doesn't really render custom components, does it? So I used to let it create the frame and the generic parts, but anything else I needed to code directly. But it's been a while.

If that FXML was generated by Scenebuilder, then it's mind-boggling indeed. There are options for XML writers to pretty print and opening a tag one one line and closing it on a later line but the same line as an enclosed tag I find hard to swallow. Why not put everything in one big line and save on the blanks as they do with production-javascript if nobody cares to read it?

<Strolling off to have a look at the Abilie Forms' XML>

**Comment by irisiflimsi** [comment]
<Coming back from the stroll>

You should have a look at those XML files. Heartwarming, really heartwarming.

**Comment by JamzTheMan** [comment]
You can do custom components in SceneBuilder if you add them. I did TT using pure Java components only and didn't want to get crazy with the first project.  So yep, those are all auto-generated files...

Now, with that said, if you are only concerned with XML/FXML formatting, I have less issue if someone wants to change Spotless to apply formatting to those files and change tabs to spaces. I consider them "data" files and not code so less worried about it.

I'm not sure but I don't think spotless is running on FXML, being in the "resource" directory and all.

**Comment by irisiflimsi** [comment]
No I am not only concerned with XML formatting, it's all formatting. I am here to convince you of the sacred ways of the _space_.

On a more serious note: I suppose such XML files will be read by humans occasionally, e.g. when looking for i8n tags in FXML. It is not uncommon to require useful indentation in such files as well.

**Comment by Azhrei** [comment]
Yeah, I agree that a standard indentation is a Good Thing.  I don't think we're going to agree on whether should be spaces or tabs.  I've actually changed the spotless config to use spaces.  I will always hit the Tab key when I'm coding, but I prefer a device-neutral storage format.

**Comment by irisiflimsi** [comment]
I also hit the tab key, but it comes out _spaces_. :-)

One of the more interesting arguments regarding tab vs space I heard lately, was that you couldn't remove space from being a valid character, but you could remove tab. So in the sense of minimizing your range of code points... (Anybody create a proper unicode variable name in Java lately?)

**Comment by irisiflimsi** [comment]
After all this time, who had the last laugh... Shouldn't we retroactively turn this into _fixed_ now? :-)
