### ISSUE TITLE
Calling a macro on the GM panel from a trusted context fails to make the macro trusted

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1812]
**Describe the bug**
Calling a macro on the GM panel from a protected macro doesn't give the macro the trusted status if the player is not a GM.

**To Reproduce**
1. Create a macro `printNotes` on the GM panel with the protected macro `[r: getGMNotes()]`
2. Call this macro with `[macro("printNotes@GM"):""]` from a protected macro, such as a non-player editable macro.
3. Attempt to run the macro created in 2) as a player. Notice the macro returns `you do not have permission to call the "getGMNotes" function.`

**Expected behavior**
The macro runs fine if a protected macro called it.

**MapTool Info**
- Version: 1.6.1
- Install: New

**Comment by Merudo** [comment]
PR #1817 fixes this.

**Comment by Phergus** [comment]
Tested.  GM panel macros called from a trusted context are themselves trusted.
