### ISSUE TITLE
Changing name/image of impersonated token doesn't update chat label

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1822]
**Describe the bug**
Changing the name or image of the impersonated token doesn't update the chat box properly. The old image and label are still displayed.

**To Reproduce**
1. Impersonate a token
2. Change the token name with `[setName("newname")]`
3. Notice that the chat box still displays the old name

**Expected behavior**
The chat box displays the changed name and/or image.

**MapTool Info**
- Version: 1.6.1, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10,

**Comment by Phergus** [comment]
Same thing when done through the Edit Token dialog.

**Comment by Merudo** [comment]
PR #1823 fixes this.

**Comment by Phergus** [comment]
Tested.  Changing name/image through macros/dialog updates Chat panel appropriately.
