### ISSUE TITLE
'getSightType()' fails on newly created tokens.

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#1828]
**Describe the bug**
`getSightType()` fails on newly created tokens.

**To Reproduce**
1. Open a blank campaign.
2. Drag a token to the map.
3. Right Click on the token and select `Impersonate`.
4. In chat, type `[getSightType()]`. Macro won't run, See error: 
   > ```
   > Error in body of roll.
   > Statement options (if any):
   > Statement Body : getSightType()
   > ```
5. Double-click the token to edit it, and hit 'Ok'. 
6. Repeat step 4. Now the result is `Normal`.

**Expected behavior**
`getSightType()` should work on new tokens without opening the token editors.

**Screenshots**
![image](https://user-images.githubusercontent.com/220149/81977359-c34b6d00-95de-11ea-84ee-43dcb0cf1420.png)

**MapTool Info**
- Version: 1.5.14 and 1.7.0b2
- Install: New alongside many other versions

**Desktop (please complete the following information):**
 - OS: Win10

**Additional Context**
This happens whether or not the new token dialog is displayed when a new token is created. 

For some reason, some trusted macros which affect the tokens will fix the issue when run by GM, but not when called by the player. It might be because the macros I tried this with were called from the GM panel, which has trust issues (#1817)

**Comment by Phergus** [comment]
Might be related to #1811 .  Same kind of situation.

**Comment by Merudo** [comment]
I don't understand how MapTool determines which sight type should be the default. Ideally it should be a Campaign property.

**Comment by melek** [comment]
I'm guessing that when the Edit Token dialog populates the 'Sight Type' list, it grabs the first one and sets it.

However, a campaign is still valid with no defined sight types, and `getSightType` should not break a whole macro in that case; in my opinion it should return an empty string.

**Comment by Phergus** [comment]
> However, a campaign is still valid with no defined sight types, and getSightType should not break a whole macro in that case; in my opinion it should return an empty string.

This is the important part.  It should not produce an error especially one that implies that the macro script is in some way wrong.

Adding the ability to set a default Sight type would be a separate issue.

**Comment by balp** [comment]
I think I understand what happens in this code path and like to have a go at a solution.

**Comment by balp** [comment]
Returning an empty string.

![image](https://user-images.githubusercontent.com/39064/82080770-7605f300-96e5-11ea-8ab3-fdaf327c25e8.png)

**Comment by Phergus** [comment]
Tested.  Running `getSightType()` on newly added token no longer produces an error but instead returns `""`.

**Comment by melek** [comment]
Updated the wiki:
https://lmwcs.com/rptools/wiki/getSightType
