### ISSUE TITLE
math.* functions always say argument 0 was at fault when rejecting non-numeric arguments

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#1831]
**Describe the bug**
`math.X()` functions always say argument 0 was at fault when rejecting non-numeric arguments, regardless of actual position of a non-numeric argument.

**To Reproduce**
execute `[r: math.min(1, 2, "someStr")]`
> Argument number 0 "someStr" to function "math.min" must be a number.

**Expected behavior**
Error message should properly identify the position of the argument that was invalid.

**MapTool Info**
- Version: 1.6.1

**Additional context**
In foreach loop, `i` is never incremented:
https://github.com/RPTools/maptool/blob/fabf84b0692271811e9ff0735ee78679a4c5beb9/src/main/java/net/rptools/maptool/client/functions/MathFunctions.java#L102-L111

Pull request coming momentarily.

**Comment by selquest** [comment]
Hrmmm, looks like the standard used most other places is to 1-index parameters in these kinds of error messages.  I'm not sure we're entirely consistent, but if that standard was decided upon at some point then I need to update this to not use 0-indexing.

**Comment by Phergus** [comment]
I don't know if there was an actual decision reached at some point but I could it being more user-friendly.   If the majority of error messages for functions report using a 1-index numbering probably should stick with it.

**Comment by selquest** [comment]
I'm not sure it's really more user friendly to use 1-index numbering in error messages when interactions with arrays and lists and such would have to use 0-index in the scripts users write, but that's a longer conversation.  I'll switch to 1-index here for better consistency with other error messages, and we can revisit the overall preference elsewhere.

**Comment by Phergus** [comment]
Tested.  Passing bad values for parameters reports correct parameter index now.
