### ISSUE TITLE
Registration on the RPTools forum is broken

### ISSUE THREAD

**Issue by ogrotten** [RPTools/maptool#184]
The forum requires captcha, but the captcha service was shut down on March 31, 2018.

https://www.programmableweb.com/news/google-recaptcha-v1-api-shutting-down-march-2018/brief/2017/10/24

Also, info@rptools.net email bounces

Couldn't get on the forum, and the contact emails don't inspire much confidence, so that just leaves posting here.

**Comment by Azhrei** [comment]
Yes, we know.  I have posted an Announcement that the forum software will be updated tomorrow night (Sunday, April 15) at about 8PM EDT (GMT-4).  It'll probaby take about an hour.

**Comment by ogrotten** [comment]
Ok thank you for the response.

**Comment by Azhrei** [comment]
Okay, it's working again.  It was an issue with the default version of PHP being used.  I've simply reverted the version back for now and will correct this issue as part of the upgrade of the forum software.  Thanks again for reporting it. :)
