### ISSUE TITLE
Refactor Initiative classes to avoid raw list type

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1843]
The classes `InitiativeListCellRenderer`, `InitiativePanel`, and `InitiativeListModel` use lists with unparameterized raw types.

References to raw types should be parameterized because it provides stronger typing, improves code readability, and avoids needless casting.

**Comment by Merudo** [comment]
PR #1844 does this.

**Comment by Phergus** [comment]
Tested basic functionality of panel.  No issues seen.
