### ISSUE TITLE
Frame5/Dialog5/Overlay load CSS in incorrect order when link points to  macro

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1853]
**Describe the bug**
When CSS is loaded from a macro via the link tag it is inserted at the top of the head element before anything else.

**To Reproduce**
Campaign Attached which demonstrates the error.

**Expected behavior**
CSS should be loaded in the order it is defined in the link tag.

**MapTool Info**
1.7 Alpha
[CSSPrecedenceError.zip](https://github.com/RPTools/maptool/files/4637990/CSSPrecedenceError.zip)

**Comment by Phergus** [comment]
Tested.  Test cases that failed prior to fix now work as expected.
