### ISSUE TITLE
Token image layout offset changes when pasting token to map with different pixels/grid setting

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1859]
**Describe the bug**
When a token has the image offset (via Config tab of Edit Token dialog), copy/pasting to a map with a different grid size (pixels/grid cell) the offset is kept constant instead of adjusting to the new grid size.

**To Reproduce**
1. Create a Map at 50 Pixels per Cell.
2. Add a Token suitable for use as a familiar such as Devin's `familiarSummons_07`
3. Open the Edit Token dialog for that otken and go to the Config tab.
4. In Layout section, reduce size and reposition to a corner of the grid cell.
5. Click on OK to close dialog
6. Add the Hero token and place the Familiar token on top.
7. Select both and hit Ctrl-C to copy them.
8. Add a New Map at 100 pixels per cell.
9. Paste copied tokens.  Note that familiar is now nearer the center of the cell.
10. Add a New Map at 10 pixels per cell.  Zoom in some.
11. Paste copied tokens.  Note that familiar is now positioned outside of cell.

**Expected behavior**
Layout offset should be preserved as a percentage of grid size.

**Screenshots**
Familiar token in Layout
![image](https://user-images.githubusercontent.com/34379254/82128359-d34a8480-9777-11ea-8759-7de4365b50b7.png)

Placed over Hero token on 50 pixels/cell map.
![image](https://user-images.githubusercontent.com/34379254/82128372-ecebcc00-9777-11ea-9dda-b09c2674a0c0.png)

Copied to 10 pixels/cell map
![image](https://user-images.githubusercontent.com/34379254/82128402-376d4880-9778-11ea-80a0-fceee0639ea3.png)

Copied to 100 pixels per cell map
![image](https://user-images.githubusercontent.com/34379254/82128423-5c61bb80-9778-11ea-8873-7e34a16fe06e.png)

**MapTool Info**
- Version: 1.6.1, 1.7.0-b3
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows,  MacOS (by misterz)
 - Version: 10

**Additional context**
Reported by misterz on Discord.

Example 1.7.0b3 campaign with maps and tokens.
[LayoutErrorGridSetting.zip](https://github.com/RPTools/maptool/files/4639109/LayoutErrorGridSetting.zip)

**Comment by melek** [comment]
Is this the same as https://github.com/RPTools/maptool/issues/997 ?

I would love to see this patched!

**Comment by Phergus** [comment]
Yes it is.  Forgot all about that one.

Closing as duplicate.
