### ISSUE TITLE
Add macro location where the function error occurred to the error message

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1861]
**Is your feature request related to a problem? Please describe.**
Tracking down macro bugs is hard. The user only gets the function that caused the error and doesn't get where it occured.

For example, imagine you have a complex framework that depends on json a lot. Imagine one day you get the following error when running a macro:

> Argument number 1 to function "json.set" must be a JSON Array or Object.

You'll have to search your entire project to find in which macro the bug occurred.

**Describe the solution you'd like**

The error messages are displayed with the name of the macro in which it occurred:

> Macro "Attack@Lib:framework": Argument number 1 to function "json.set" must be a JSON Array or Object.

In addition, an additional macro function `getErrorTrace` could report the error trace of the last error:

> Error trace: "Attack@Lib:framework", "Select Attack@Lib:framework", "Prepare Attack@Lib:framework", "Attack NPC@Campaign"

**Comment by Merudo** [comment]
Related: https://github.com/RPTools/maptool/issues/797

**Comment by Merudo** [comment]
An alternative proposed by @kayila : instead of printing only the name of the macro where the error occurred, the full stack trace could be automatically displayed to the chat.

**Comment by Merudo** [comment]
My branch https://github.com/Merudo/maptool/commits/add-error-macroname showcases how the stack trace could be displayed.

Here is what is printed to the chat:

![image](https://user-images.githubusercontent.com/7371085/82138956-19403080-97ea-11ea-9002-29229e20d2ec.png)

**Comment by Merudo** [comment]
@kayila recommended using arrows instead:

![image](https://user-images.githubusercontent.com/7371085/82143548-5b796a00-980a-11ea-9496-b39fb6f63d6c.png)

**Comment by JamzTheMan** [comment]
This is going to help immensely! I'd get that error and say "geez, I only use json.set a million times, so which one is blowing up?

**Comment by Merudo** [comment]
PR #1925, together with the parser update, add this feature.

**Comment by Phergus** [comment]
Tested with `macro()`, `eval()`, `execMacro()`, `macroLink()` and UDF calls.  Working as expected.

```
Function "setTokenDrawOrder" requires at least 1 parameters; 0 were provided.
Error trace : m3@Campaign <<< m2@Campaign <<< m1@campaign
```
