### ISSUE TITLE
HTML5 Form submit not allowed at document load

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1863]
**Describe the bug**

Form submission cannot occur right after document load.

This is related to how the `console.log` used to not work until after document was fully loaded (see #1551).

**To Reproduce**
1. Create a macro on the Campaign panel named `print` with the code `Form submitted`
2. Run the following macro:

```
[frame5("test"):{
    <form action="[r: macroLinkText('print@Campaign', 'all')]" method="json" id="form">
        <input type="" name="test" value="test value">
        <input type="submit" value="Submit form">
    </form>
    
    <script>
        document.getElementById('form').submit();
    </script>
}]
```
3. Clicking on the button launches the macro. Simply loading the frame does not.

**Expected behavior**
The form can be submitted at document creation.

**MapTool Info**
- Version: 1.7
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1869 fixes this.

**Comment by Phergus** [comment]
Tested.  Form submission now working from frame load.
