### ISSUE TITLE
Macrolinks producing no text produce empty chat line

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1867]
**Describe the bug**
If a macroLink launches a macro that produces no output, a blank line of text is still produced in the chat box.

**To Reproduce**
1. Create an empty macro `blank` in Campaign panel
2. Type the following in the chat:
```
[r:macroLink("Click me", "blank@Campaign", "all")]
```
3. Click on the link. A blank message is printed in the chat.

**Expected behavior**
No message is printed if the macro produces no output.

**Screenshots**

**MapTool Info**
- Version: 1.6.1, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
A workaround is to set the macrolink output to `none`; however this is not helpful if the macro is to only produce output under certain conditions.

**Comment by Merudo** [comment]
PR #1868 fixes this.

**Comment by JamzTheMan** [comment]
ZOMG, thank you! My 7 year old framework is riddled with these! I try to fix them as I find them but it's such a PITA!

**Comment by Phergus** [comment]
Tested with empty macro and with macro that produces no output.  No longer produces spurious empty lines in chat.
