### ISSUE TITLE
getMacroProps returns misnamed property "toolapplyToSelected"

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1874]
**Describe the bug**
The json returned by `getMacroProps` returns the property `toolapplyToSelected`.

The property name should be `applyToSelected` instead.

**To Reproduce**
1. Use `getMacroProps` on a macro.
2. Notice the included property `toolapplyToSelected` and the missing `appyToSelected`

**Expected behavior**

The property is named  `appyToSelected`

**MapTool Info**
- Version: 1.7.0
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1875 fixes this.

**Comment by JamzTheMan** [comment]
@aliasmask are you using/relying on this json name/property in your rpedit? Note the change if som

**Comment by aliasmask** [comment]
That would explain the difference in my recent update with the apply to selected. Thought I had it checked, but my upload didn't have it checked. I just loaded a token and none of the apply to selected were checked when on the token they are. It doesn't give an error otherwise. I did put in a temp fix for now.

```
[H: temp = json.get(macro,"toolapplyToSelected")]
[H, if(temp == "true"): applyToSelected = 1]
```

**Comment by aliasmask** [comment]
Thanks for the heads up.

**Comment by JamzTheMan** [comment]
No problem. It's something that certainly could "break" frameworks if they are relying on the old/incorrect name, but I think we should change it anyway. Worse case we have to leave the old name in, but we don't have a way to tell people it's "deprecated" so how long do you leave it in?

(has this been wrong for a while/forever or just recently?)

**Comment by Merudo** [comment]
> (has this been wrong for a while/forever or just recently?)

Since #1088

**Comment by aliasmask** [comment]
Looks like bug was introduced in to 1.5.11. If there is going to be a permanent change to remove "applyToSelected", then let me know and I'll make the change.

**Comment by Phergus** [comment]
Tested.  Property name is returned correctly now.
```javascript
{
  "autoExecute": true,
  "color": "default",
  "fontColor": "black",
  "group": "",
  "includeLabel": false,
  "sortBy": "",
  "index": 1,
  "label": "Props",
  "fontSize": "1.00em",
  "minWidth": "",
  "playerEditable": false,
  "command": "[r: json.indent(getMacroProps(1,\"json\"),2)]\/pre>",
  "maxWith": "",
  "tooltip": "",
  "applyToSelected": false,
  "compare":   [
    "group",
    "sortPrefix",
    "command",
    "includeLabel",
    "autoExecute",
    "applyToSelected"
  ],
  "metadata":   {
    "uuid": "f2dd1667-7883-4000-9e67-a84011034652",
    "commandChecksum": "a8086719ce71909b2cf4637e007244c3",
    "propsChecksum": "f68722c609955b0ffa54ab914d7f7b27"
  }
}
```
