### ISSUE TITLE
Unwanted quote symbols created by [if(0), code:{}]

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1876]
**Describe the bug**

The code

```
[if (condition), CODE:{ some code }]
```
Will print a unwanted `''` as output if the condition is equal to zero (false).

The current workaround is to add an empty `{}` for the other condition,

```
[if (condition), CODE:{ some code };{}]
```

**To Reproduce**
1. Type `[if(0), code:{}]`
2. Notice the unwanted symbol `''`.

**Expected behavior**
No `''` if no condition is evaluated.

**MapTool Info**
- Version: 1.5.0 to 1.7, probably earlier as well
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1877 fixes this.

**Comment by Phergus** [comment]
Tested.  No longer getting spurious quote marks when `else` block of `if()` roll option is left out.
