### ISSUE TITLE
Frame5 / Dialog5 : button formaction is ignored

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1878]
**Describe the bug**
With HTML5, the button property `formaction` can specify which action/link is to be used with the form submit.

This property is currently ignored with `frame5` / `dialog5`, and the submitted form just uses its own action instead.

**To Reproduce**
1. Create a campaign macro `print` with the code `Form submitted`.
2. Run the following text:

```
[frame5("test"):{
<form method="json">
  <button type="submit" formaction="[r: macroLinkText('print@Campaign','all')]">Submit</button>
</form>
}]
```
3. Click on the submit button. Notice it doesn't do anything.

**Expected behavior**
If the `formaction` property is present on a button, it should override the form's action property.

**Screenshots**

**MapTool Info**
- Version: 1.7.0
- Install: New

**Desktop (please complete the following information):**
 - OS: Window
 - Version: 10

**Comment by Merudo** [comment]
PR #1879 fixes this.

**Comment by Phergus** [comment]
Tested using:
```
[h: args = json.set("{}", "a", 1, "b", "duck")]
[frame5("test"):{
<form method="json">
  <button type="submit" formaction="[r: macroLinkText('print@Campaign','all',args)]">Submit</button>
</form>
}]
```
Where the print macro was simply `[r: macro.args]` and get this result:

`{"a":1,"b":"duck"}{}`

With an extra empty object.

**Comment by Merudo** [comment]
I don't think you can add `args` to the macroLinkText when using forms.

The following doesn't work either:

```
[h: args = json.set("{}", "a", 1, "b", "duck")]

[frame("test"):{
<form method="json" action="[r: macroLinkText('print@Campaign','all',args)]">
  <input type="submit">
</form>
}]
```

**Comment by Phergus** [comment]
Ah.  Wondered about that.
```
[r: args = json.set("{}", "a", 1, "b", "duck")]
[frame5("test"):{
<form method="json">
        <input type="" name="test" value="test value">
  <button type="submit" formaction="[r: macroLinkText('print@Campaign','all',args)]">Submit</button>
</form>
}]
```
Produces this in `macro.args`:
`{"a":1,"b":"duck"}{"test":"test value"}`

Probably needs to be documented and a separate issue opened.

Considering this issue has complete.
