### ISSUE TITLE
Overlay transparency now broken

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1884]
**Describe the bug**
The overlays are no longer transparent, making them pointless.

**To Reproduce**
1. Launch any overlay, such as with `[overlay("test"):{Text}]`

**Expected behavior**
Overlays are transparent.

**MapTool Info**
- Version: develop only (5/19/2020)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1885 fixes this.

**Comment by Phergus** [comment]
Tested.  Overlays are transparent as expected.
