### ISSUE TITLE
copyToken() doesn't preserve Shape setting of token

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1889]
**Describe the bug**
Using `copyToken()` doesn't preserve the Shape setting of the copied token setting the new token to `Circle`.

**To Reproduce**
1. Drop Hero token on default Grasslands map and set it to Top-Down.
2. Run this code:
  - `[copyToken("Hero", 1, "Grasslands", {"x":6,"y":7, "useDistance":0, "size":100, "layer":"TOKEN","facing":270}')]
3. Observe that new token is set to Circle.

**Expected behavior**
Expect copied token to preserve all properties not explicitly changed by the `copyToken()` function.

**MapTool Info**
- Version: 1.5.0 and possibly earlier.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
The problem is with `"layer": "TOKEN"`.

`[copyToken("Hero", 1, "Grasslands", '{"layer":"TOKEN"}')]`

**Comment by JamzTheMan** [comment]
@melek It looks like copyToken is missing documentation for this. setLayer has this option so you can borrow text from there?

Do we need to confirm if there are any other missing options for copyToken?

**Comment by Phergus** [comment]
`forceShape` isn't documented either.

**Comment by JamzTheMan** [comment]
> `forceShape` isn't documented either.

*either*? That is the missing documentation, or did you mean something else?

**Comment by Merudo** [comment]
I've updated the `forceShape` parameter description: https://lmwcs.com/rptools/wiki/copyToken

**Comment by Phergus** [comment]
> > `forceShape` isn't documented either.
> 
> _either_? That is the missing documentation, or did you mean something else?

That using `layer` changes the token shape isn't documented.

**Comment by JamzTheMan** [comment]
> > > `forceShape` isn't documented either.
> > 
> > 
> > _either_? That is the missing documentation, or did you mean something else?
> 
> That using `layer` changes the token shape isn't documented.

gotcha. ya, it should note what happens if you don't set `forceShape`. I assume it follows the same logic as setLayer so depends if you copy to TOKEN or OBJECT "stuff" happens and that should be under `layer` option, good point.

**Comment by Phergus** [comment]
Wiki documentation has been updated with additional comments and details of `forceShape`.
