### ISSUE TITLE
transferVBL macro function is misnamed

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#189]
The transferVBL() function is somewhat misnamed.  If you transfer something it is moved from one place to another.  The function is really a copyVBL() function.

Changing this might break existing macros but it would be useful if it did what it said.

Alternatively a second parameter that determined transfer or copy could be added.  This might also break existing macros as the current second parameter, token ID, would need to be pushed to the third slot.

**Comment by JamzTheMan** [comment]
Agreed. We could add add a copy of function and deprecate the current.

We could also use logic to deprecate functions :)

**Comment by Phergus** [comment]
Use logic?  Inconceivable!

**Comment by JamzTheMan** [comment]
Marking some issues as "Help Wanted" that could be good places to start for new developers...

**Comment by oliver-szymanski** [comment]
Adding my opinion: I don't like copyVBL() either cause it would suggest I do a paste later. So I would more be a copyVBLTo…

What I suggest is adding an optional parameter to the transferVBL function. 
transferVBL(value, id, delete)

Then if delete is true it actually deletes it, so equal to a real transfer/move.

That way we do not hit existing macro code and I guess its still doing what the idea of this Jira is.

If you guys agree and still want it I can add that.

By the way, the much bigger problem with VBL is the different scale between token and normal VBL (also just my POV ;) )

**Comment by Phergus** [comment]
Normal MT macro function usage is to have the token ID as the last, optional parameter.

So it would be:
```
transferVBL(to/from)
transferVBL(to/from, delete)
transferVBL(to/from, delete, id)
```
While that might break a handful of existing macros it should be a big impact as the function is probably not used much in framework code.

**Comment by oliver-szymanski** [comment]
I will change it in a way to not change current behaviour (by checking
parameter types)

**Comment by oliver-szymanski** [comment]
Fix in https://github.com/RPTools/maptool/pull/310
Amended to use a new Boolean optional delete parameter, fully backwards compatible.
