### ISSUE TITLE
Clean up copyToken, add mapName to deleteToken

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1890]
**Is your feature request related to a problem? Please describe.**
The function `copyToken` should be cleaned up to use `FunctionUtil.blockUntrustedMacro`, `FunctionUtil.getTokenFromParam`, and `FunctionUtil.checkNumberParam`.

The function `removeToken` could have a parameter "mapName" added to delete a token on another map.

**Comment by Merudo** [comment]
PR #1891 fixes this.

**Comment by Phergus** [comment]
Tested:
- Internal code changes to `copyToken` made.
- `removeToken()` now accepts a mapName parameter.

Wiki page for removeToken() updated.

**Comment by selquest** [comment]
These changes also fixed a bug in 1.7 where the new copy of a token has sight regardless of the hasSight value on the original.
