### ISSUE TITLE
Dim light cancels out bright light

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1893]
**Describe the bug**
An area lighted by a bright light can be made dim if a dim light source is nearby.

**To Reproduce**
1. Create a token with a source of dim light and a token with a source of bright light
2. Have the light source overlap by moving them around. Sometimes, the area lit by both source will be dim instead of bright.

A special case: a vision has Darkvision (creates personal bright light) is near a dim light source.

**Expected behavior**
Unless negative lumen is used, a dim light source never makes vision worse.
 
**Campaign**

Dragon has Darkvision, and can see worse near a dim light:

[testDarkvision.cmpgn.zip](https://github.com/RPTools/maptool/files/4657356/testDarkvision.cmpgn.zip)

**Screenshots**

![image](https://user-images.githubusercontent.com/7371085/82459084-1c9f1a80-9a7d-11ea-88e3-e25a196b4896.png)

![image](https://user-images.githubusercontent.com/7371085/82455894-26268380-9a79-11ea-900a-c0afa8de58b9.png)

Example from Maccwar:

Because dim light can make vision worse, VBL that blocks dim light will make vision better

![image](https://user-images.githubusercontent.com/7371085/82454095-fbd3c680-9a76-11ea-82f0-8fdf629d6d3c.png)

![image](https://user-images.githubusercontent.com/7371085/82454126-05f5c500-9a77-11ea-90dc-c1c117b58112.png)

**MapTool Info**
- Version: 1.7
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by JamzTheMan** [comment]
1. Lets use "Personal Lights" vs darkvision which can be a defined light source on Sights.

2. I *think* there is an outstanding issue with lights in general where they don't always *stack* or *blend* properly and may be around the lumens code.

A separate issue also exists to add lumens to personal lights which may or may not want to be tied together with this (depending on which code is being touched). IIRC its threaded for speed and sounds like it could be a race condition.

**Comment by Merudo** [comment]
What would be the best approach to fix this? Draw the lights in order of (absolute) brightness maybe?

**Comment by Merudo** [comment]
I see what you mean. This happens when the lumens of two light source are equal, in which case the order in which they are drawn is randomized.

Setting the lumen explicitly to two different values ensure they are properly rendered.

**Comment by Merudo** [comment]
Seems like this is a rather complicated, actually.

I think it would be worth distinguishing various issues that I at first conflated:

1.  Light sources with equal lumens are displayed in an apparently random order. This I believe is intended, although it could be desirable for light sources with same lumens to be displayed according to their CSS luminosity
2. The lumens of personal light sources / darkvision can't be changed from 100.
3. A light source with multiple types of light (such as dim 40' bright 20') has to have the same lumen for all types
4. Light sources with different lumens will sometimes display the light from the wrong source. For example a bright light source will occasionally produce dim light. This is reset once a token moves. I assume this might be the result of a race condition.
5. Darkvision / personal light doesn't seem to work right with lumens, and is almost always overridden by other light sources.

**Comment by JamzTheMan** [comment]
1. It draws in order of lumens specifically to hand negative lumens to emulate "darkness" effects but also emulate some magical lights > some magical darkness > some other lights.  Sources of equal lumens wasn't specifically handled but I like your idea of using the color alpha as the order.

2. Yes, separate "feature" enhancement. I'd only bother adding this in if it helps to fix the current issue, which may "help" considering there is no other way for users to adjust the "sorting" of lights in this case without specifying lumens on all their lights.

3. Ya. And technically, we don't *really* have dim vs bright light, just different "colors" people can use to refer to what they consider "dim" vs "bright" vs "ambient" vs "whatever".  I suppose we could add another keyword like DIM or BRIGHT etc but that's scope creep and needs it's own issue to review.

4. Probably

5. The "FoW" reveal should be working just fine, but the color of the lights, yes, the coloring of the lights is probably off somewhere.  Be sure to add some -90 and -110 lights into the mix when testing to confirm personal vision does and does not reveal FoW in those lights when making changes.

**Comment by JamzTheMan** [comment]
oh and also be sure to verify "low-light" vision isn't playing with things. There's a setting to make other "lights" larger for the specific token... I saw "elf" mention and it's common for them to have a x2 sight type.

**Comment by Merudo** [comment]
I tested some more, and it seems `lumens` are only taken into account for figuring out FoW.

The lights are otherwise painted in the following order: drawable (colored) lights first, then bright lights (lights without a CSS color) after.

**Comment by JamzTheMan** [comment]
Too bad, maybe they should then?

**Comment by selquest** [comment]
I'm not sure I follow this correctly - "bright lights" (those without a CSS color) don't really get drawn, they get subtracted out of the area covered by "drawable lights" in `ZoneRenderer.renderLights()`.

**Comment by Merudo** [comment]
PR #1899 fixes 5).

**Comment by Merudo** [comment]
I've found a bug related to personal lights. After editing the campaign properties once, all sight types are given a bogus personal light source. This bugged light source makes `sight.hasPersonalLightSource()` always return true, causing needless computations and caching.

**Comment by Phergus** [comment]
This issue and #1896 are likely to expose a big 'ol can of worms.  Pun intended.

The following are all with the code from PR #1899 and prior.

A convoluted setup.  Hero token with default Normal Vision.  T object has a light source (12.5') with Lumens of -90.  S object has a light source with Lumens of -110.  Campfire has the default Torch light source.  The 3 wood floor tiles have token VBL.  Dragon has Darkvision with an added blue tint.
![image](https://user-images.githubusercontent.com/34379254/82582816-d666bb80-9b4f-11ea-8fe2-b067eb93fa36.png)

Server running.  IV and IFoW. Hero token client.
![image](https://user-images.githubusercontent.com/34379254/82583685-994ef900-9b50-11ea-8f8b-442b9cdac90f.png)
Note the -90 darkness has overwhelmed the torch light and is just black (green line).

Two areas (noted with red) are visible to Hero even though the -110 darkness is in between the light source and those areas.  Not unexpected as lights don't block light but contrary to what might be expected.

Dragon Client view
![image](https://user-images.githubusercontent.com/34379254/82585261-f64bae80-9b52-11ea-872a-20c26405eb2f.png)
The areas that are "dimly" illuminated by the torch show darker (because of the personal light source tint) than the areas only illuminated by the personal light source.  The same issue with areas that shouldn't be visible are seen here as well.

**Comment by Merudo** [comment]
Thanks for the pictures and explanation, Phergus.

Two points:

1) Having darkness act as VBL (blocking what's behind the darkness) would certainly be desirable. However I feel it would be well beyond the scope of this issue.
2) The way colored lights combine is certainly odd, but I think it should be discussed in #1895

**Comment by Merudo** [comment]
After some tests, I have noticed that the cache `drawableLightCache` and `brightLightCache` can get multiple duplicates of the same lights. This happens when lights in `lightSourceCache` get flushed but `drawableLightCache` and `brightLightCache` don't.

Is there any reason why `lightSourceCache` should be flushed but not the other two caches?

Reminder:

`lightSourceCache`: maps (lightsource id, sight type, lumens) to an area. Constructed in `getLightSourceArea(baseToken, lightSourceToken)`.Used to construct `allLightAreaMap` (map between lumens and area), which is used to determine the visible area of a token. 

`drawableLightCache` : maps (light source id, sight type) to a set of `DrawableLight`. Constructed in `calculateLightSourceArea`. Used in `renderLights` to render colored lights.

`brightLightCache`: maps (light source id, sight type) to a set of `area` representing bright lights. Constructed in `calculateLightSourceArea`. Used in `renderLights` to rend bright lights by subtracting it from colored lights.

**Comment by Phergus** [comment]
I mentioned the "darkness" not blocking light mostly as an illustration that MT is not and was not meant to be a physics model for how light works.

Also note that your #5 hasn't been completely addressed as much of the Darkvision area for the Dragon has been overridden by the dim light area.

**Comment by Merudo** [comment]
I noticed nearly all calls to exposeFoW are needlessly duplicated. PR #1918 fixes this.

**Comment by Merudo** [comment]
A similar duplication exists for `flush(token)`. PR #1919 fixes it.

**Comment by JamzTheMan** [comment]
Please also note, "darkness" lights purposefully do not block LoS per most DnD fantasy rules (up to the time of it being coded). Most "effects" simply "reduce" the light level in the area.

The effect is akin to if you stood at one end of a 100' hallway holding a candle and there was a torch at the other end, you would see the end of the hallway but not the goblin in the middle of the hallway hiding. Natural "darkness" and "magical darkness" work in the same way here.

Besides, if you need it to be VBL just add VBL :)

Carry one.

**Comment by Phergus** [comment]
That's pretty silly but it is a mechanic just for D&D so...

**Comment by JamzTheMan** [comment]
> That's pretty silly but it is a mechanic just for D&D so...

Not sure why people think it is silly, if you think of it removing light vs creating darkness, you end up with what maptool would show in those cases anyway if you deleted the light source.

**Comment by Phergus** [comment]
Because for the observer at the end with a candle to see anything at the other end the light from that end has to reach the observer.  If the light travels through a _light removing area_, aka darkness, there won't be any light reaching the observer.

In the case where there is something in the hallway between the two points, such as a goblin, the goblin would be backlit to some degree or just eclipsing the light from the other end and thus at least partially observable.

**Comment by Azhrei** [comment]
Yep.  I always thought that the D&D definition of how this should work was wonky, but it _is_ magic, after all.  IIRC, the descriptions of these effects typically limit the description to saying that those _within_ the radius cannot perceive any light.  The same wording is applied to _silence_ spells and the like.  So at least they're consistently wrong on the physics of it. 🙄

**Comment by Phergus** [comment]
So in the current D&D rules a person inside of an area of darkness can't _perceive_ light and not that light doesn't reach them?   This suggests that to an outside observer the area under darkness looks completely normal and illuminated by whatever light sources are in range.  If nothing else it would be humorous watching the those in the "darkness" stumble around blind.

**Comment by JamzTheMan** [comment]
#magic

Why stop there, why not have blast templates calculate the proper area that a fireball should really fill?

Short answer if because no one in the real world can properly understand "magic" and improperly fill in the blanks with the physics you do grasp.

What if the magic reduces light in an area while ay the same time create a warping field that passes light from one side to the other? Much like sci fi cloaking? 

Sorry, rant off, I just like to keep science out of my magic.

**Comment by Phergus** [comment]
Tested.  Original issue has been corrected as has several performance issues.  Other issues commented upon here should be handled in their own issues.
