### ISSUE TITLE
Trusted functions not running from GM panel when called from a frame, even when playing as GM

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#1894]
**Describe the bug**
`log.info` and `broadcast` no longer work from the GM panel when called from a frame. 

**To Reproduce**
1. Add the following macro to the Campaign panel:
> ```
> [h, if(macro.args == "INFO"): log.info("log.info Works!")]
> [h, if(macro.args == "BROADCAST"): broadcast("broadcast Works!")]
> [frame("Test Frame"): { 
> 	<h3>Testing [r: vThisMacro = getMacroName() + "@" + getMacroLocation()]</h3>
> 	[macroLink("Run LOG.INFO Test", vThisMacro, "none", "INFO")]<br>
> 	[macroLink("Run BROADCAST Test", vThisMacro, "none", "BROADCAST")]
> }]
> ```
2. Click on the macro to open the testing frame.
3. Open the log console. 
4. Click on each test. They should work.
5. Copy the macro to the GM panel.
6. Reopen the frame and re-run the tests.
7. Each test fails:
> ```
> You do not have permission to call the "log.info" function.
> You do not have permission to call the "broadcast" function.
> ```

**Expected behavior**
The GM panel should allow trusted functions from trusted contexts/behave like the Campaign panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/220149/82480383-8f61c300-9a88-11ea-83ca-dad22a55891e.png)

**MapTool Info**
- Version: 1.7.0, 1.7.0b3 (Does not happen in 1.7.0b2, 1.6.1, and 1.5.14)
- Install: New alongside many versions

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
I think this is a bug introduced by related fixes to GM panel trust issues. 

This was found by a user of my framework: 
https://github.com/melek/Simple5e/issues/15

**Comment by Merudo** [comment]
I guess a macro on the GM panel should always be considered secure because it is not possible for a player to edit it?

**Comment by melek** [comment]
I don't know, but at very least is should behave like the Campaign panel.

**Comment by Merudo** [comment]
This was caused by #1817

**Comment by Merudo** [comment]
PR #1900 gives the gm macro permission when ran through a macro link.

**Comment by Phergus** [comment]
Tested.  Functions requiring Trusted context now working in frames opened from GM Panel.
