### ISSUE TITLE
Lights with Lumen=100 don't reveal FoW for tokens with personal light

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1896]
**Describe the bug**
Light sources with lumen=100 will not reveal FoW for tokens with personal light / darkvision.

**To Reproduce**
1. Create a light source with lumen = 100
2. Create a token with personal light
3. Set vision to night
4. Expose vision for token with personal light. The light source doesn't reveal FoW

**Expected behavior**
Light source with lumen 100 exposes FoW

**MapTool Info**
- Version: 1.7, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1897 fixes this.

**Comment by Phergus** [comment]
Tested.  Light with `lumens=100` now expose for tokens with personal light.
