### ISSUE TITLE
Feature Request: Add VBL copy/paste buttons to Edit Token Dialog

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#190]
On the VBL tab of the Edit Token Dialog, add buttons to copy or transfer VBL from the map to the token and to paste VBL on the token down to the map.

**Comment by oliver-szymanski** [comment]
I think that's already in the dialogue. At least I have thse buttons. I might have it cause I always started from Nerps.

Are you sure this is still an open requirement?

**Comment by rkathey** [comment]
I believe this is resolved in #254. I suggest closing this one.

**Comment by Phergus** [comment]
Issue was duplicated in #254.
