### ISSUE TITLE
Macro Editor: Dark and Large theme

### ISSUE THREAD

**Issue by rogue-ronin** [RPTools/maptool#1906]
**Is your feature request related to a problem? Please describe.**
As I get older, it's harder to see. :)

**Describe the solution you'd like**
I prefer dark themes, helps things pop for me. I would like the Dark theme of the macro editor to also have a Large Text version. (eg: Dark w/ Large Text)

**Describe alternatives you've considered**
Sunglasses + Large Text theme.

**Comment by JamzTheMan** [comment]
We don't have a built in theme editor but the Macro Editor themes are just XML and pretty easy to do. There are also a few default themes to choose from (under Preferences) including dark themes.

In your `~\.maptool-rptools\themes\syntax` dir you will find the default themes, just copy one to the same directory and change it.

Nerps (Dark) is a 16 point dark theme I put together and use. If you want larger text? Change it to 18pt or larger. Play with the colors.

@melek Do we have a wiki on where this option to select the theme is? (it's a little buried)  Maybe we can put a quick article up on how to change the XML? There is a dtd and I "think" it's obvious the fg is foreground color and bg is background color, but we may want to spell out what the `tokens` are and what will change, for instance, UDF name vs function names vs other...

**Comment by rogue-ronin** [comment]
Thanks! I'll take a look around, and see what I can mangle into shape. :)

**Comment by Phergus** [comment]
You are looking in Preferences -> Interactions -> Macro Editor?  Pretty sure it is one of the include themes for the macro editor.  It has its own themes separate from the rest of the UI.  (Cuz we like things complicated.)

**Comment by Phergus** [comment]
In any case, this is the line you want to change in the theme once you find them:
```
   <baseFont size="18"/>
```
I think the default theme is like 13 which is too small for my ancient eyes as well.

**Comment by rogue-ronin** [comment]
Yeah, I'm looking in Edit --> Preferences --> Macro Editor.

And yes, now that I look again with your prompting, I find Nerps (Dark) at the top of the list above Dark and Default and Nerps.

I expected these to be together, I don't know why. Probably expecting alphabetical sorting, even though they plainly are not.

Nerps(dark) is pretty good, so I won't go create my own. (Yet.)

Thank you.

**Comment by Phergus** [comment]
Editor theme selection is documented on [MapTool Preferences](http://www.lmwcs.com/rptools/wiki/MapTool_Preferences#Macro_Editor) page.
