### ISSUE TITLE
Change Facing performance drops with continuous changes.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1921]
**Describe the bug**
For tokens with Vision, and when a number of light sources are nearby, changing facing via mouse-wheel starts out responsive but becomes jerky and skips facing positions after just a few spins of the mouse-wheel.

[TokenFacingPerformanceIssue_1_5_14.cmpgn.zip](https://github.com/RPTools/maptool/files/4671807/TokenFacingPerformanceIssue_1_5_14.cmpgn.zip)
(Remove `.zip` from filename.)

**To Reproduce**
1. Load attached campaign.
2. Go to **Multiple Lights** map.
3. Select Hero token.
4. Use Shift-Mouse-Wheel to change facing doing so continuously for several complete facing revolutions.
5. Observe that the facing pointer will start out keeping up with the mouse input but quickly drops facing positions in order to keep up.
6. Switch to **No Lights** map and change facing on Hero token.  Changing facing works smoothly.

Issue can also be seen holding down Shift and Left/Right cursor keys.

**Expected behavior**
Expect changing facing to work smoothly.

**MapTool Info**
- Version: 1.5, 1.6, 1.7, current develop
- Install: Any

**Desktop:**
 - OS: Windows
 - Version: 10

**Additional context**
Reported on forums:
https://forums.rptools.net/viewtopic.php?p=276303&sid=1df0c59f5469df4c928f4ecc1ec6801e#p276303

**Comment by Merudo** [comment]
The issue is the same as one described in #1893, the[ duplication of lights](https://github.com/RPTools/maptool/issues/1893#issuecomment-632668046) in the `drawableLightCache` and `brightLightCache`.

This is caused by clearing the `lightSourceCache` but not the other two caches just mentioned.

**Comment by Merudo** [comment]
PR #1924 fixes this.

**Comment by Phergus** [comment]
Tested:  Performance is much improved with this change..   Some symptoms are still there when continuously and rapidly spinning the mouse-wheel but this may be mouse driver/system/java limitations.  When doing more than 2 full rotations per second only the last position is displayed.  Performance does not stay degraded as with previous MT versions so this a big improvement.
