### ISSUE TITLE
Display Hot Key? macro setting not working

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#1926]
**Describe the bug**
When a hot key is assigned to a macro, the Display Hot Key setting does not work. The checkbox is unchecked, but the hot key is still displayed. When the macro editor is opened after that, the checkbox is checked again.

**To Reproduce**
1. Open a new campaign.
2. Create a new macro. 
3. Edit the macro and go to the Details tab.
4. Assign a hot key and uncheck Display Hot Key?
5. Close the editor. Note how the hot key is still displayed on the macro button.
6. Open the editor again and go to the Details tab.
7. Note how the checkbox Display Hot Key? is checked again.

**Expected behavior**
I expect that option to work and not display the hot key on the macro button, when I check the option.

**MapTool Info**
- Version: 1.7.0
- Install: Upgrade 1.6.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.4

**Comment by Phergus** [comment]
Apparently broken since the checkbox was added in 1.5.2.  The checkbox state is only kept the very first time the macro is edited.  Likewise the Apply button only works on first edit.

**Comment by mrkwnzl** [comment]
Haven’t seen that the Apply button only works on the first edit. I have used that extensively since 1.5.X

**Comment by Merudo** [comment]
All the "macro commonality" options are not saved either.

**Comment by Phergus** [comment]
> Haven’t seen that the Apply button only works on the first edit. I have used that extensively since 1.5.X

Sorry.  Wasn't clear.  It works to apply changes to hotkey but not the checkbox for display hotkey.

**Comment by Phergus** [comment]
> All the "macro commonality" options are not saved either.

Heh.  Same situation.  They are saved on first edit but after that you can't change them.

**Comment by Merudo** [comment]
PR #1928 fixes this.

**Comment by Phergus** [comment]
Tested.  Noted issues have been corrected.

Discovered that Min Width is apparently being applied as both Minimum and Maximum width.  The Max Width field is always disabled.
