### ISSUE TITLE
With dark theme, panels use black text for macro group names

### ISSUE THREAD

**Issue by rogue-ronin** [RPTools/maptool#1931]
**Describe the bug**
With dark theme, macro group names on Selected, Impersonated, GM, Campaign and Global panels are black-text on dark-background.

**To Reproduce**
1. Apply RT Default Dark theme
2. Open any of the following panels: Selected, Impersonated, GM, Campaign or Global
3. See that macro-group names are black-text on dark-background

**Expected behavior**
I expect the macro groups to use the same white text as the rest of the interface.

**MapTool Information**
MapTool Version: 1.7.0
MapTool Home...: /home/rogue/.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 281 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

**Java Information**
Java Vendor.: Oracle Corporation
Java Home...: /opt/MapTool/runtime
Java Version: 10.0.2

**OS Information**
OS Name........: Linux
OS Version.....: 5.6.12-1-MANJARO
OS Architecture: amd64
PATH...........: /home/rogue/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
Number of Procs: 4

**User Information**
User Name: rogue
User Home: /home/rogue
User Dir.: /opt/MapTool/app

**Locale Information**
Country.: United States
Language: 
Locale..: United States
Variant.: 

**Encoding Information**
Default Locale:   _US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

**Display Information**
Number of Displays: 2
Display 1: 1680x1050(-1)
Display 2: 1680x1050(-1)

**Comment by Rukbat16** [comment]
The issue persists in version 1.10.4, on Windows.

MapTool Version: 1.10.4

OS: Windows 10 Home x64

Locale: EN-GB

Number of Displays: 1
Display 1: 1920x1080
