### ISSUE TITLE
Add option to reroll initiative each round.

### ISSUE THREAD

**Issue by RlndVt** [RPTools/maptool#1936]
To allow for a more 'dynamic' fight, where the dragon doesn't get to save against the Wizard's spell immediately each round, add an option to reroll initiative every round. 

**Describe the solution you'd like**
Every round the system rerolls initiative for all combatants in a fight using the initiative bonus stored in their token. (Taking possible advantage into account.)

**Additional context**
Improved-initiave.com has this feature for reference.

**Comment by melek** [comment]
The existing initiative system can accommodate this with a macro button. I don't think MT needs a new option, personally, since every system is different - but I can suggest a macro solution!

This macro can go on your GM or Campaign panel and can be used to advance the initiative. When a new round is detected, it will reroll a 1d20 for initiative for each token, sort the list, and set the initiative to the first in the list. 
```
[h: vRound = getInitiativeRound()]
[h: nextInitiative()]
[h, if(getInitiativeRound() > vRound), code: {
	[vInitTokenList = json.get(getInitiativeList(), "tokens")]
	[foreach(vInitToken, vInitTokenList, ""), code: {
		[vTokenID = json.get(vInitToken, "tokenId")]
		[switchToken(vTokenID)]
		[setInitiative(1d20)]
		[sortInitiative()]
	}]
	[setCurrentInitiative(-1)]
	[nextInitiative()]
}]
```

For your game, change the `vInitBonusProp` to the name of whatever token property you use to determine initiative bonus.

**Comment by RlndVt** [comment]
As far as I can see MT doesn't have a built in initiative rolling system does it? But again with a macro you could get it done?

I guess if that's the preferred method I better start learning how to write (and implement) these macro's.

**Comment by Phergus** [comment]
That's correct.  As different systems have different rules for managing initiative the automation of the Initiative panel is left to macros.

You might look at:  http://www.lmwcs.com/rptools/wiki/Roll_Initiative

**Comment by melek** [comment]
Just so you know, the UI accessible way to do what you want out of the box is totally possible. 

The macro I posted does the following steps for you, but all the tools to do it without a macro are absolutely there if you prefer to avoid macros for some reason. It wouldn't even take too long to do if you ask players to re-enter their own initiative each round :)

1. Right click on each token that will participate in Initiative, and click 'Add to Initiative'. Players can add their own tokens to initiative.
2. For each token, roll their initiative with your preferred method (`/roll 1d20` in chat works great).
3. Right click on each token in the initiative panel and click 'Set Initiative...'. Then enter their total initiative roll.
4. Click on the Initiative menu on the Initiative panel (![image](https://user-images.githubusercontent.com/220149/82944388-f501f380-9f4f-11ea-8611-c2f21a7fdcf8.png)) and click 'Sort'. 
5. Use the 'Next' button (![image](https://user-images.githubusercontent.com/220149/82944445-15ca4900-9f50-11ea-9d3a-8ca2baf01b3b.png))to advance initiative turns, and repeat steps 2-4 at the top of each new round.
