### ISSUE TITLE
Form macroLinkText appending form data at end of macro.args

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1937]
**Describe the bug**
Since 1.5.12, form macroLinkTexts defined with a data argument append the form data in a strange way.

For example, if you define a form action macro link as

`[macroLinkText(mymacro, 'all', json.set("{}", "character", "John")]`

and then use the link in a form with the button

`<input type = "submit" name = "action" value = "Submit"></input>`

The macro specified in the macroLinkText will receive the follow `macro.args`:

` {"character":"John"}{"action":"Submit"}`

In effect the data from the link and the form are appended one after the other, which doesn't make much sense.

In addition, this leads to `macro.args` no longer being recognized as a json object, possibly causing an error message if `json.get` is used.

**To Reproduce**
1. Create a campaign macro named `print` with the code `[r: macro.args]`
2. Run the following macro:

```
[frame("Test"):{
[h: processorLink = macroLinkText("print@Campaign", "all", json.set("{}", "character", "name"))]
<form action="[r:processorLink]" method="json">
<input type="submit" name="action" value="Submit">
</form>
}]
```
3. Click on the `Submit` button
4. Notice the output: `{"character":"name"}{"action":"Submit"}`

**Expected behavior**
The previous behavior was to ignore the form data, so the result would be ` {"character":"name"}`.

I think a better solution would be to combine the data from the form and the link:  `{"character":"name", action":"Submit"}`

**MapTool Info**
- Version: 1.5.12 to 1.7, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Although combining two json objects is straightforward enough, I'm not sure how the data should be combined if the macroLinkText is given a json array, string or number as data.

**Comment by Phergus** [comment]
The only downside I see to combining them like that are if one of the passed args was also "action".

Perhaps `{"args":{"arg1":"key1", "arg2":"key2", ...}, "form":{"action":"submit"}}`

**Comment by Merudo** [comment]
It would break compatibility though - macroLinkText without argument are currently expecting 

`"form":{"action":"submit"}`

while macroLinkText with arguments are expecting

`{"arg1":"key1", "arg2":"key2", ...}`

**Comment by Phergus** [comment]
So then I guess the answer is combining the results in one object and putting a warning on the wiki that you can't `action` as a key in the passed in arguments for it.

**Comment by Azhrei** [comment]
> It would break compatibility though - macroLinkText without argument are currently expecting
> 
> `"form":{"action":"submit"}`

I presume you mean:

`{"form":{"action":"submit"}}`

> while macroLinkText with arguments are expecting
> 
> `{"arg1":"key1", "arg2":"key2", ...}`

Another option:

`{"form":{"action":"submit"},"arg1":"key1", "arg2":"key2", ...}`

Existing code that assumes no arguments still sees the `form` property, and code that expects arguments see those arguments.  Of course, this time it's the `form` property name that conflicts...

**Comment by Merudo** [comment]
This works for json objects, but what if the data defined in the macroLink is a string, number or json array?

Should the form data just be ignored in those cases?

**Comment by Merudo** [comment]
PR #1946 fixes this.

- If there is no macroLinkText argument, the `macro.args` will be of the form

`{"action":"submit"}`

- If the macroLinkText argument is a json object, the `macro.args` will be of the form

`{"form":{"action":"submit"},"arg1":"key1", "arg2":"key2", ...}`

- If the macroLinkText argument is not a json object, the form data will be ignored.
