### ISSUE TITLE
Player clients logging in with drawing layer other than Token can draw on that layer.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#194]
If a player has selected a layer other than Token in the drawing tools just prior to connecting to a server their drawings will appear on that layer.  i.e.  A player could be drawing on the Hidden, Object or Background layers!

Seen in 1.4.0.5 and current Nerps.

**Comment by Azhrei** [comment]
Wow, good catch!  Luckily it should be a one or two line fix, I would think.  Jagged will likely get to it before I have his current PR merged.  (@Jaggeroth Please file a separate PR and refer to this issue.  Thanks!)

**Comment by Phergus** [comment]
I would think a simple setCurrentDrawingLayer("Token") or whatever at client connection init would do it.

**Comment by Jaggeroth** [comment]
See Pull Request #195

**Comment by Phergus** [comment]
Fixed with PR #195
