### ISSUE TITLE
Update to Parser 1.7.1

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1943]
Update MapTool to use parser v1.7.1 with [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) character support.

This allows the use of "Latin alphabet no. 1" characters in macro code.

Example:
```
My Dextérité is [r: Dextérité]<br>
My Dex Mod is [r: floor((Dextérité-10)/2)]
```
Or in Campaign Properties
![image](https://user-images.githubusercontent.com/34379254/83027458-62b02d00-9fed-11ea-8641-693d5802af06.png)

**Comment by Phergus** [comment]
Characters now supported:

![1920px-Latin-1-infobox svg](https://user-images.githubusercontent.com/7371085/83023716-e4568980-9ff2-11ea-949e-826d81e1a5f4.png)


The ones after the `......................................` are added by this PR.

The last two rows can be used in variable names, except for the × and ÷ symbols.

**Comment by Phergus** [comment]
Tested.  New parser allows the accented characters noted above to be used in macro code.

**Comment by bubblobill** [comment]
um... has anyone tried this with the "cheater" characters?
