### ISSUE TITLE
New onTokenInitiative event

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#1944]
**Is your feature request related to a problem? Please describe.**
The initiative tool can be made drastically more powerful if there were automation. I propose a `onTokenInitiative` event analogous to `onTokenMove` which gets triggered when a token receives Initiative and gets executed on whatever token just received initiative.

**Describe alternatives you've considered**
The alternative is to create a macro which forwards the initiative and then executes a macro on the token. This is less desirable for two reasons: (1) It’s an extra step in the macro economy and (2) GMs need to remember not to use the native initiative controls. Judging from some of the questions regarding this on the Discord, (2) is especially alienating for some people.

**Comment by Phergus** [comment]
Already covered by #720 and #987.
