### ISSUE TITLE
getname() is being invoked as setName() instead of getName()

### ISSUE THREAD

**Issue by Akaku-Keninari** [RPTools/maptool#1950]
**Describe the bug**
getname(token id) instead invokes setName(name)

**To Reproduce**
[r: getname(token id)]

**Expected behavior**
It either says invalid syntax or actually calls getName()

**MapTool Info**
- Version: 1.7.0
- Install: Upgrade [previous version]

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
PR #1951 fixes this.

**Comment by Phergus** [comment]
Tested.  Invoking as `getname()` or `getName()` calls the correct function.
