### ISSUE TITLE
getTokens() area points/polygon

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#1961]
**Is your feature request related to a problem? Please describe.**
getTokens() using 'area' requires an array of all points within the area. Generating the list of points is computationally intensive in MT script and mathematically complex for many shapes. I don't know if it even works for non-grid related co-ordinates.

**Describe the solution you'd like**
The ability to describe the area by providing the bounding points of a polygon as used in movedOverPoints

**Describe alternatives you've considered**
For my use case of a rotated rectangle:
-Store a set of points and apply affine transforms to each point. 
-Generate the points using linear interpolation for each line of the rectangle.
These take too long (3.5-17 secs depending on method) for an area 15 x 30 cells.

**Comment by Phergus** [comment]
Functionality should be handled in whatever is done for #3257.
