### ISSUE TITLE
Colors in drawing tool color picker are unreliably clickable

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#1962]
**Describe the bug**
Like HTML links in 1.5.x (see #1427), the colors in the color picker seem not be activated if there is only a slight movement of the mouse cursor between pressing and releasing the mouse button.

**To Reproduce**
1. Open the drawing tool.
2. Press and hold the left mouse button over a color currently not set.
3. Move the mouse cursor a bit.
4. Release the mouse button. Nothing happens.

**Expected behavior**
I expect the color to be selected even if I move the mouse cursor slightly. I think the solution in #1427 (activate the color picking on mouse button release) would be appropriate here as well.

**MapTool Info**
- Version: 1.7.0
- Install: Upgrade from 1.6.1

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5

**Comment by Merudo** [comment]
PR #1964 fixes this.

**Comment by Phergus** [comment]
Tested.  Selecting colors is not so picky now.
