### ISSUE TITLE
Feature Request: option to disable "ESC closes chat"

### ISSUE THREAD

**Issue by Syndaryl** [RPTools/maptool#197]
... or at least add a button to equally-quickly restore chat. Or have it just collapse the chat window instead of delete it so it can be opened relatively quickly?

Having my chat window suddenly vanish while I'm trying to cancel something is extremely frustrating, because it always happens when I'm trying to do something _quickly_. Having it vanish when I'm trying to do something quickly makes it twice as bad, as I flail around the menus trying to get it open again quickly.

I'm not entirely sure what the usage scenario for this is, since it doesn't seem paired with a speedy command to open it. If it was ESC to _toggle_ the chat window, I could cope with it and could even find use for it (quickly revealing more of the map, check things out, quickly get my chat back). But if I were doing that, I would want it to hide _all_ the tabs, and then _restore_ all the tabs.

**Comment by Azhrei** [comment]
Hm, good points.  I’m sure we’re not specifically looking for the ESC key and closing the chat window, so maybe it’s the underlying third party library (JIDE) that manages the docking panels?  (Well, I’m _pretty sure_, anyway.  If we are, we should change it!)

**Comment by Phergus** [comment]
We are specifically closing the chat window after an ESC key event.  Given that I have to believe it was done intentionally.  Presumably just as a fast escape from and closing of the window.  Note that Ctrl-Enter will reopen (not as convenient) and forward slash (`/`) will also open it but puts a slash on the line.

So the question becomes, which option do we want:
1. make the ESC key toggle the chat window state
2. don't close the chat window on ESC
3. add a preference to not close the window on escape
4. something else entirely

Let's have some feedback peoples,  @Syndaryl  @RPTools/coredevs @RPTools/frequent-contributor

**Comment by melek** [comment]
I would add a preference between turn off, toggle, and do nothing.

**Comment by aliasmask** [comment]
I never ran across this. I know Esc key will close a dialog which is good if someone specifies no frame or buttons. Seeing how none of the other frames close when using Esc (they just lose focus) not really sure why we have that feature. Maybe just change the shortcut to ctrl-esc to avoid accidental usage. Having an info panel of the various shortcuts used in MT not specific to the menus would be nice as well. I'm looking at you [spacebar].

**Comment by Phergus** [comment]
@melek  I don't know what you mean by "turn off".

Some more context.
- Esc allows you to abort what you are currently typing into the chat window _and clears the input_.  That it also closes the window seems weird but I'm guessing somebody wanted it that way.
- Esc gets you out of Full Screen Mode.
- Esc gets you out of the Input dialog as if you hit Cancel.
- Esc closes macro dialogs.

I'd be good with Esc not closing the chat window and just clearing the current input line.

**Comment by Azhrei** [comment]
Using ESC to close the chat panel probably predates the integration of the JIDE libs that provides sociable and floating panels.  When the JIDE stuff was added, the ESC event handler just wasn’t updated/removed.

It doesn’t matter to me.  ESC closes dialogs, but probably shouldn’t close the chat panel as it’s not a dialog.

**Comment by melek** [comment]
Sorry for being unclear; I meant 'turn off' as in close the chat panel when it is in focus (the current behavior). 

Reading all the responses here and playing around with the panel a little, I agree that ESC shouldn't be closing the chat panel for consistency's sake. 

I like the idea of having ESC clearing the chat input area when the chat panel is in focus without hiding the panel, but I don't feel strongly about it.
