### ISSUE TITLE
Provide graphics scaling options to improve rendering quality

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1971]
**Is your feature request related to a problem? Please describe.**
The default image scaling algorithm is "Nearest Neighborhood".

This scaling results in low quality when downscaling an image to 50%-80% of its original size, and in horrendous quality when scaling an image to less than 50% of its size.

**Describe the solution you'd like**
Users should have the option to select a higher quality scaling algorithm. The algorithms available should include:

- Nearest neighbor (current algorithm)
- Bilinear
- Bicubic
- Progressive bilinear
- Progressive bicubic

**Additional context**
Previous discussion: [Portrait image rendering is not scaled with sufficient quality](https://github.com/RPTools/maptool/issues/1709)

**Comment by bubblobill** [comment]
How often is scaling performed? Is the performance hit once per image for size or once per image presentation? i.e. I expect each resize is cached and the resized image used thereon so the performance his is negligible. If it is resized on every draw then it could be an issue. 

If users get the option then offering info on performance hits and rendering issues like "Does weird things in OpenGL" will be appropriate.

**Comment by Merudo** [comment]
> I expect each resize is cached and the resized image used thereon so the performance hit is negligible.

That would be the idea. Shrank versions of each image at 50%, 25% and 12% would be cached. The performance hit would be negligible but the memory used would increase.

**Comment by Phergus** [comment]
Tested.  Map rendering quality improved for higher zoom settings when set to Medium or High.
