### ISSUE TITLE
listGet broken with spaces

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1972]
**Describe the bug**
On develop, if a list entry has a space in it, `listGet()` will ignore the characters after the space.

**To Reproduce**
1. Type `[r: listGet("Wild Magic Surge", 0)]`
2.  `Wild` is returned, instead of `Wild Magic Surge`.

**Expected behavior**
Characters after the space are not ignored.

**MapTool Info**
- Version: develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
@nmeier could it be due to one of your performance improvements to list strings?

**Comment by nmeier** [comment]
checking

**Comment by nmeier** [comment]
spaces in elements was missing from tests, adding that and preparing a fix that trims leading/trailing space correctly

**Comment by Merudo** [comment]
Now I'm getting an error using `==`: 

`[r, if(1 == 1): "match"]`

> Invalid condition in IF(1 == 1) roll option.

**Comment by nmeier** [comment]
Not related to a string function.

Related to the ExpressionParser which can't format `if(1 == 1, 1, 0)` unless a deterministic expression is built first. Filed https://github.com/RPTools/maptool/issues/1974 to correct this.

**Comment by Phergus** [comment]
Tested.  Correctly retrieves items with spaces in name and trims leading/trailing.
