### ISSUE TITLE
Disabling the deterministic expression building can lead to NPE

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#1974]
**Describe the bug**

As part of #1898 and https://github.com/RPTools/dicelib/issues/43 I've made a deterministic expression optional. That breaks for this simple if roll expression though `if(1 == 1, 1, 0)` since xp.format() can't handle '==' operator.

This worked fine before since the deterministic expression for `if(1 == 1, 1, 0)` is `1`

**To Reproduce**

Run this macro

[r, if(1 == 1): "match"]

**Expected behavior**

should return "match"

**MapTool Info**
- Version: 1.8 develop

**Additional context**
https://github.com/RPTools/maptool/issues/1898
https://github.com/RPTools/dicelib/issues/43

**Comment by nmeier** [comment]
Checking a quick fix to get this going again by using deterministic parser for the branch condition.

I'll create test-cases for all parseExpression() to see if there's more dependency on the parser  - all those add on expressions branch/while/etc. might suffer from this.

**Comment by Phergus** [comment]
A quick and easy fix is to just change all of those calls to `parseExpression()` to pass `true` until each case can be thoroughly tested.

**Comment by nmeier** [comment]
yes, will do a PR just for that. Then test, then change dicelib - which seems needed here


https://github.com/RPTools/dicelib/blob/master/src/main/java/net/rptools/common/expression/ExpressionParser.java#L244


the core parser doesn't seem to support those conditional expressions passed through rolls/dicelib in format

https://github.com/RPTools/parser/blob/master/src/main/java/net/rptools/parser/InlineTreeFormatter.java#L37

**Comment by Phergus** [comment]
Tested.  Code is returned to deterministic expression building.
