### ISSUE TITLE
Overlay refresh not erasing previous content

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1976]
**Describe the bug**
Using `overlay` with the same name does not erase the content of the previous overlay. This leads to content being drawn on top of previous content.

**To Reproduce**
1. Type `[overlay("test"):{Old text}]`
2. Type `[overlay("test"):{New}]`
3. The text "New" is printed on top of "Old text".

**Expected behavior**
The previous content of the overlay should not be kept.

**MapTool Info**
- Version: develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
Issue appeared after switching to Java 14: https://stackoverflow.com/questions/62186782/javafx-webview-transparent-webview-keeps-old-content-drawn

**Comment by Merudo** [comment]
PR #1983 fixes this.

**Comment by Merudo** [comment]
PR #1984 changes the reflection to invocation, which is faster, more modern, provides better error traces and is more secure.

**Comment by Phergus** [comment]
Tested.  New content erases old content.
