### ISSUE TITLE
Localize Layer Selection Dialog

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1987]
**Is your feature request related to a problem? Please describe.**
The layer names shown in the Layer Selection Dialog are not localized.

**Describe the solution you'd like**
Use existing layer names from the i18n file in the dialog.

**Additional context**
![image](https://user-images.githubusercontent.com/34379254/83953163-3f5e5c80-a7fb-11ea-9c28-191635f1e622.png)

**Comment by Merudo** [comment]
This would involve some refactoring as some parts of the code relies on the hardcoded English names of the layers.

**Comment by Azhrei** [comment]
Yep.  The same statement applies to the use of "PC" and "NPC".  I remember looking into this a _long_ time ago and decided there was no practical way to change it without some major, intrusive changes.

**Comment by Irarara** [comment]
@Phergus Looks like I forgot to check if there was already an issue about this when opening #2560. Whoops! I suppose this can be closed.

**Comment by Phergus** [comment]
OBE.
