### ISSUE TITLE
playClip hogging the JavaFX Application Thread

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1988]
**Describe the bug**
Using `playClip` occupies the JavaFX Application Thread, freezing up the `frame5/overlay` functions.

**To Reproduce**
1. Run the following code:
```
[h: playClip("https://dl.dropboxusercontent.com/s/qq8vvfqx2l8sljb/Dice%201.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/salpl0q89cmi5cv/Dice%202.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/s6tgm9t2brsuuyz/Dice%203.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/wq412ham20ogqsx/Dice%204.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/04ywyfzc44n3485/Dice%205.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/3pfz4mg3hg9dq6c/Dice%206.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/92yjy54qfl0d18e/Dice%207.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/a8lwk0puqf1uq9j/Dice%208.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/i3rnq0dkhotxrt0/Dice%209.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/5xo1ood7czprsaa/Dice%2010.wav?dl=0")]
[h: playClip("https://dl.dropboxusercontent.com/s/5m634y43j8rh4cv/Dice%2011.wav?dl=0")]
[frame5("test"):{test}]
```

2. Notice how long it takes for the frame to display its content.

**Expected behavior**
playClip should not slow down `frame5` and `overlay` this badly.

**MapTool Info**
- Version: 1.7.0, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
Question I posted on StackOverflow: [Java Audioclip: new AudioClip(s) with remote URL creates UI lags](https://stackoverflow.com/questions/62241277/java-audioclip-new-audioclips-with-remote-url-creates-ui-lags)

**Comment by JamzTheMan** [comment]
At least it's not hogging the swing thread :)

But yep, probably going to have to background those on another thread. Platform.runlater? Really the FX thread should be for UI only.

**Comment by Merudo** [comment]
PR #1994 fixes this.

**Comment by Phergus** [comment]
Tested.  Audio files played back sooner and overlay shows up in well under a sec as compared to nearly 6 seconds before.
