### ISSUE TITLE
bundle.getString is checked for null

### ISSUE THREAD

**Issue by grimreaper** [RPTools/maptool#1992]
In `net.rptools.lib.i18n.I18NManager#getText` bundle.getString is checked for null. However, it is not legal for this function to return null and in fact throws a `MissingResourceException` if the resource does not exist.

In a search across the rest of the code bast this is the only instance of this issue since `net.rptools.maptool.language.I18N#getString(java.lang.String)` translates MRE to `null`.

**Comment by grimreaper** [comment]
meta question: I'm going to have several of these small bugs or code quality cleanups. Is there a better way of communicating this than creating a an issue + a PR for each one? Can I create a general class-of-issue bug?

**Comment by Merudo** [comment]
I think a single issue could cover either multiple small code cleanups in a single class, or a single type of cleanup in multiple classes.

**Comment by Phergus** [comment]
> Can I create a general class-of-issue bug?

Yes.  If there are similar/related fixes then creating one issue with one or more PRs is fine.  Just need to keep the original issue updated as to the progress.

**Comment by Azhrei** [comment]
Just remember that other people can be working in the code at the same time.  If there’s a conflict, it’ll likely be on you to resolve it (since it’s a lower priority “cleanup”), so you may want to stick to smaller batches of files in your PRs.

**Comment by grimreaper** [comment]
@Azhrei that makes sense. I often use cleanup as a means to figure out how a community works, how to submit PRs, etc. that said, because its lower priority refactoring it isn't always a perfect process.

**Comment by Phergus** [comment]
Tested.  No issues seen with retrieving localized strings.
