### ISSUE TITLE
capitalize() also capitalizing the possessive "s"

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1995]
**Describe the bug**
Function `capitalize()` also capitalizes the `'s` used to indicate possession.

**To Reproduce**
1. Type `[r: capitalize("a bug's life")]`
2. Check the result: `A Bug'S Life`

**Expected behavior**
The `'s` is not capitalized.

**MapTool Info**
- Version: 1.7.0, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
I believe there was a discussion about this on Discord at the time it was added and it was thought better to handle `capitalize("rick o'shea")` => `Rick O'Shea` correctly than worry about possessives.

@cwisniew ?

**Comment by Merudo** [comment]
If the `'s` ends the word, it shouldn't be capitalized.

**Comment by Merudo** [comment]
It's more than just a `'`.

Example: `capitalize("i'll do it. no you won't")`
Result:  `I'Ll Do It. No You Won'T`

**Comment by Azhrei** [comment]
Wow, that's going to be tough to solve, especially considering that the locale is a factor.

I seem to recall that the String class allows a locale to be specified for things like a case-insensitive equals function... Perhaps there's something similar for case conversion?

**Comment by Merudo** [comment]
True. In French you have `"C'est la vie"` which definitely should be capitalized to `"C'Est La Vie"`.

**Comment by selquest** [comment]
I'd tend to agree with Merudo that the downsides of treating `'` as a word boundary here outweigh the somewhat incidental gain of capitalizing "O'Brien".  The function is intended (or at least, is described as intended) to capitalize the first letter of each word, so it doing any kind of internal capitalization seems inappropriate.

For what it's worth, that's the approach taken by the Apache Commons library's `WordUtils.captialize()`, and ICU4J's `UCharacter.toTitleCase()` methods.

**Comment by Phergus** [comment]
Unless the code changed since it was added back in October it is using common-language WordUtils.capitalize().

**Comment by Merudo** [comment]
> Unless the code changed since it was added back in October it is using common-language WordUtils.capitalize().

It is using Regex:

```java
  private String capitalize(String str) {
    Pattern pattern = Pattern.compile("(\\p{IsAlphabetic}+)");
    Matcher matcher = pattern.matcher(str);

    StringBuffer result = new StringBuffer();
    while (matcher.find()) {
      String word = matcher.group();
      matcher.appendReplacement(result, Character.toTitleCase(word.charAt(0)) + word.substring(1));
    }

    matcher.appendTail(result);

    return result.toString();
  }
```

**Comment by Phergus** [comment]
Had to go back to the discussion last October.  Craig was going to use it but didn't.  From the discussion it was desired that symbols and numbers were seen as word breaks which coincidentally is exactly what the documentation says.

Feel free to add a parameter that switches to using `WordUtils.capitalized()`.

**Comment by selquest** [comment]
Wiki page for `capitalize()` updated to reflect changes coming in 1.8
(though, sidenote: if anyone can come up with a more succinct name for the new `treatNumbersSymbolsAsBoundaries` parameter, *please* feel free to replace it in those docs!)

**Comment by Phergus** [comment]
Tested.  New parameter provides an alternative way to get capitalization wrong.

```
[r: capitalize("o'shea thinks it's a sin")]
[r: capitalize("o'shea thinks it's a sin",1)]
```
produces `O'Shea Thinks It'S A Sin`

```
[r: capitalize("o'shea thinks it's a sin",0)]
```
produces `O'shea Thinks It's A sin`

**Comment by selquest** [comment]
@Phergus if that second option doesn't produce a capital `Sin`, we've got problems - but I'm assuming it's just a typo in your comment.

**Comment by Phergus** [comment]
Yup.  lol

Pasting out of MT chat into issues is a nuisance and I was too lazy to do it first in NP++ and then into the issue.
