### ISSUE TITLE
Several dependencies need to be updated.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2]
Several dependencies need to be updated so we can use the jars in the normal nevertheless repositories instead of the temporary one.

**Comment by rkathey** [comment]
Complete?

**Comment by cwisniew** [comment]
not yet, some we will do as 1.4.1.x hopefully

**Comment by JamzTheMan** [comment]
do we have a list of what you are hosting vs what we get from maven? (I think that is what you meant?)

**Comment by rkathey** [comment]
Complete?

**Comment by JamzTheMan** [comment]
I'm going to close this. I've updated several dependences as needed. If we identify others we can do those as needed. Also 2.0 will take s fresh pass at reminding libs...
