### ISSUE TITLE
Java9 EOL

### ISSUE THREAD

**Issue by LukasDJacobs** [RPTools/maptool#200]
As Java9 is not a LTS release, it already has reached it's end of life. It's still required by the CI system, but oracle doesn't seem to offer a download any longer, which is why builds (at least macOS builds...) fail.
I've read, that Oracle is planning on releasing a new major version of Java every 6 months, so this should be kept in mind.

Maptool builds and runs fine using Java10, thus I recommend updating the build files.

**Comment by Azhrei** [comment]
Yep, that's the plan.
