### ISSUE TITLE
Include SmartDoors in default tokens

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2010]
**Smart Doors** were developed with the intention they be included as part of the default assets delivered with MT.

The attached file contains the current set of doors.
They incorporate crude language support though at present only English is available.
They have been community tested and seem to have the bugs ironed out when operated by the GM but there are currently permission problems with the macros when operated by a connected player. 

**The permissions should be tested with new releases prior to inclusion.**

Each token contains the following information in their properties.
_copyright_notice:_ Copyright © 2020, Jay Stratton
_copyright_license:_ PERMISSION TO USE COPYRIGHTED MATERIAL
I, as the copyright holder grant permission to rptools.net to use, modify, reproduce, and distribute all content subject to the condition that such actions are for non-commercial purposes

<edit: new version>
[Smart_Doors_v1.4.2.zip](https://github.com/bubblobill/MapTool/raw/master/SmartDoors/Smart_Doors_v1.4.2.zip)

[on GitHub](https://github.com/bubblobill/MapTool/tree/master/SmartDoors)

**Comment by Merudo** [comment]
Is there an established criteria to determine if a resource should be included in the default assets instead of the RPTools Library?

**Comment by cwisniew** [comment]
@Merudo Unless you also plan to put it in the now not so much used rplib repository I would just add it to MapTool.

**Comment by bubblobill** [comment]
Someone on Discord said it would be nice to have doors with VBL included with MT. Doors being ubiquitous and commonly needed by everyone. I thought that was a good idea so I made some for that purpose.

Unfortunately I have the urge to fiddle so instead of boring tokens with VBL we have tokens macroed up the wazoo.

If they generate too much hassle and questions we can move them to an art-pack.

**Comment by bubblobill** [comment]
Naturally I do not have write-access to **maptool-resources**.

someone else can add them

[Doors.zip](https://github.com/RPTools/maptool/files/4792432/Doors.zip)

**Comment by Phergus** [comment]
The original idea was that these would be generic doors with VBL to be included under Default but they did get a little crazy.  :)

They should still be placed under Default somewhere.

**Comment by bubblobill** [comment]
New version - bugfix
[Smart_Doors_v1.4.2.zip](https://github.com/RPTools/maptool/files/5116479/Smart_Doors_v1.4.2.zip)

**Comment by bubblobill** [comment]
Can't be done under trust framework.
