### ISSUE TITLE
Double clicking on a token in the "initiative" pane doesn't populate the "selected" pane

### ISSUE THREAD

**Issue by Zuljita** [RPTools/maptool#2021]
**Describe the bug**
double clicking on a token in the initiative pane doesn't populate the "selected" pane

**To Reproduce**
1. put tokens into initiative
2. double click a token with the selected window open
4. token will get a dotted line selection box around it but the selected window doesn't populate with the token's macros.

**Expected behavior**
The selected window will populate with the token's macros after I double click on it in initiative

**MapTool Info**
- Version: 1.6.1 at least, probably earlier too

**Desktop (please complete the following information):**
 - OS: tested on windows with multiple versions

**Additional context**

**Comment by Merudo** [comment]
PR #2026 fixes this.

**Comment by Phergus** [comment]
Tested.  Double-clicking on a token in the Initiative Window makes the token active in the Selection window.
