### ISSUE TITLE
Add parameter “preferences” (or similar) to getInfo()

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#2032]
**Is your feature request related to a problem? Please describe.**
I think it would be useful to have a function to check various preferences, for example to check whether “Show Avatar per line” is checked to have different broadcast outputs depending on that setting (a broadcast including the token image or not).

**Describe the solution you'd like**
@Azhrei suggested an additional parameter for `getInfo()` for this on Discord. I think that is a good idea.

A parameter could be “preferences.” Or finer grained parameters like “chat,” “tokens,” “maps,” etc., corresponding to the areas in the preference pane.

**Describe alternatives you've considered**
One could duplicate various settings as token properties to replicate the settings, but that would be cumbersome.

**Additional context**
One stepping stone I can think of is that the preferences are client based. Changing macros based on client preferences leads to different results for different people if they have set different preferences. To use the example from above, if one client has “Show Avatar per line” unchecked and it uses a macro that broadcasts something in the chat, it appears without the token image for all players, even if they have “Show Avatar per line” checked. On the other hand, this might be desired for other applications.

**Comment by selquest** [comment]
Looks like some other client preferences (show portrait, show stat sheet, etc.) are already included in `getInfo("client")`.  Should be easy enough to add "show avatar per line" to that output.

**Comment by selquest** [comment]
Working on adding this now.

**Comment by JamzTheMan** [comment]
@selquest While you are in there (and maybe a different issue needs to be opened?) but one thing I notice is missing is a way to tell if a "server" is running or not.

IIRC there is a serverIsRunning in one of the getInfo but it only tells you if *you* are running a server. So, if I'm a "player" running a server and the GM connects to my server, I had macros fail because the "GM" is running the macro but serverIsRunning (or what ever it's called) returns false.

I don't know if we need an easier way to collect clientInfo for all connected players? Or...? Thoughts?

**Comment by selquest** [comment]
@JamzTheMan looks like the easiest addition would be to add a "personal server" boolean to the `getInfo("server")` output.  The "hosting server" output would still indicate whether or not the executing player is a host, but if "personal server" is false then you know you're either hosting or connected to an actual running server.  Would that suit your needs?

**Comment by selquest** [comment]
#### Added to `getInfo("client")`:
- show avatar in chat
- suppress tooltips for macroLinks
- use tooltips for inline rolls
```json
{
  "face edge": 1,
  "face vertex": 0,
  "portrait size": 175,
  "show portrait": true,
  "show stat sheet": true,
  "file sync directory": "",
  "show avatar in chat": true,
  "suppress tooltips for macroLinks": false,
  "use tooltips for inline rolls": true,
  "version": "0.0.1",
  "isFullScreen": 0,
  "timeInMs": 1592519870334,
  "timeDate": "2020-06-18 18:37:50",
  "isoTimeDate": "2020-06-18T18:37:50.33516-04:00",
  "user defined functions": {},
  "client id": "7a024f3b-28db-4a65-8a75-c38765682621"
}
```

#### Added to `getInfo("server")`:
- personal server
```json
{
  "tooltips for default roll format": 1,
  "GM reveals vision for unowned tokens": 0,
  "players can reveal": 0,
  "auto reveal on movement": 0,
  "movement locked": 0,
  "token editor locked": 0,
  "restricted impersonation": 0,
  "individual views": 0,
  "individual fow": 0,
  "strict token management": 0,
  "players receive campaign macros": 0,
  "movement metric": "ONE_TWO_ONE",
  "using ai": 1,
  "vbl blocks movement": 1,
  "timeInMs": 1592519870371,
  "timeDate": "2020-06-18 18:37:50",
  "gm": ["theGM"],
  "hosting server": 0,
  "personal server": 1
}
```

**Comment by JamzTheMan** [comment]
Ah ya thats a good idea. If personal server is 0 then you are either running or connected. I like it.

**Comment by selquest** [comment]
Wiki page for `getInfo()` updated to reflect changes coming in 1.8

**Comment by Phergus** [comment]
Tested.  New information is seen in results and reports current settings.
