### ISSUE TITLE
Cannot Create New Token Types

### ISSUE THREAD

**Issue by mr-krustev** [RPTools/maptool#2043]
Thew **New** button on the Token Properties window does nothing for me and I cannot create other token types except the "Basic" one.

**Comment by Merudo** [comment]
Once you click "New", you need to enter a type name and then click "Update".

**Comment by bubblobill** [comment]
A feature of th UI that could be improved upon.

**Comment by Phergus** [comment]
@mr-krustev When you open the Token Properties tab, you are essentially in the creation mode for a new Token _Property_ Type.  If you put in a name in the Name field and then add one or more Properties to the big property field text area you can hit Update and that will make it available for use under the Config panel of the Edit Token dialog.

Note this doesn't create a Token Type like PC or NPC.  This is for Property Type sets.  Most folks use it for things like Lib Tokens or door objects to give them their own set of properties specific to their application.

**Comment by Phergus** [comment]
No further responses.  Closing.
