### ISSUE TITLE
GM name for maps -- just like we have a GM name for tokens.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#2044]
**Is your feature request related to a problem? Please describe.**
As a GM, I need for my maps to have a GM name -- just like tokens.  The other name is visible to the players and is for THEM to see.  The problem is that I need to use different names for the players so that nothing is inadvertently revealed to them about the map.  I need a GM name so that I can tell what the map is really for. 

**Describe the solution you'd like**
I would like to have a GM name for each of my maps.  If I don't give them a GM name, then the map name should also function as the GM name.  I would like to see the list of  maps in the map selector to display the GM name with the name of the map visible to players shown in parentheses -- like "Ambush (Dark Forest Path)".  In the Map selector, these should be sorted by GM name.

**Describe alternatives you've considered**
There is no real workable alternative.

**Additional context**
None.

**Comment by Azhrei** [comment]
I like this idea.

Importing old .rpmap files could assign the same string to both fields, but exported maps wouldn't be loadable in older versions of MT.  (I'm not sure that's important anyway.)

**Comment by JamzTheMan** [comment]
I thought we had an issue for this but ya, everyone likes the idea. Just need a volunteer to code it. :)

Im not sure if I like the Player Map Name (Gm Map Name) as that could get sort of long?

What if we put then on separate lines like 
:heavy_check_mark: Player Map A
:eye: Final Battle with the Witch!

That also solves showing the player visible and current map selectors at the same time (players only need to see the checkmark) in some themes with one column.

Bonus if we group those two lines in alternate background shading or such so its a single selection item.

**Comment by adventuremagic123** [comment]
> I thought we had an issue for this but ya, everyone likes the idea. Just need a volunteer to code it. :)
> 
> Im not sure if I like the Player Map Name (Gm Map Name) as that could get sort of long?
> 
> What if we put then on separate lines like
> ✔️ Player Map A
> 👁️ Final Battle with the Witch!
> 
> That also solves showing the player visible and current map selectors at the same time (players only need to see the checkmark) in some themes with one column.
> 
> Bonus if we group those two lines in alternate background shading or such so its a single selection item.

For the GM, it's actually "GM Map Name (Player Map Name)" as I was talking about it above.

**Comment by bubblobill** [comment]
Not sure that indenting would jibe with the proposed feature of grouping maps presentation-wise.

**Comment by adventuremagic123** [comment]
No problem.  Whatever you guys decide.

**Comment by melek** [comment]
I believe this has been solved in 1.9.0 with #2701 which resolved #2647 and can be closed:
![](https://user-images.githubusercontent.com/33206261/118392198-f3688a00-b5fd-11eb-962e-6698869bc568.png)

**Comment by Phergus** [comment]
OBE.
