### ISSUE TITLE
remove java version checks

### ISSUE THREAD

**Issue by grimreaper** [RPTools/maptool#2047]
**Describe the bug**
There is a function verifyJavaVersion which checks to see if we're running on Java 6+ but
1) We provide our JRE/JDK
2) We actually require Java 14+
3) The version check is actually ended in the class itself (java won't run invalid versions)

Similarly we use reflection in AssetGroup to permit multiple java versions when it is now unnecessary.

**Expected behavior**

Remove said code

**Comment by Phergus** [comment]
@grimreaper - Please use the Issue Templates.

**Comment by grimreaper** [comment]
> @grimreaper - Please use the Issue Templates.

Updated the titles. There isn't a great template for code maintenance tasks though.

**Comment by Phergus** [comment]
> Updated the titles. There isn't a great template for code maintenance tasks though.

True.  Feel free to submit one.  Can just be _adequate_ or _okay_ though.  Doesn't have to be great.

**Comment by Phergus** [comment]
Tested.  Java checks removed.  No issues seen.
