### ISSUE TITLE
Layer List allows multiple selection

### ISSUE THREAD

**Issue by RevenantBob** [RPTools/maptool#205]
Allowing someone to select multiple layers with the ctrl key causes some issues. I only notice it because CTRL tends to be my push to talk.

**Comment by Azhrei** [comment]
Ah, that's an easy fix — just turn off multi-select on that list box...

**Comment by xdy** [comment]
I just made a PR that should fix this, https://github.com/RPTools/maptool/pull/973

**Comment by Phergus** [comment]
Tested.  List no longer allows multi-select.
