### ISSUE TITLE
Token properties that are json arrays of size 1 are incorrectly read (develop only)

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#2057]
**Describe the bug**
Token properties that are a json array of size exactly 1 are not read properly by MapTool.

**To Reproduce**
1. Create a token in a new campaign and impersonate it.
2. Type `[setProperty("AC", json.append("[]", "single value"))]`
3. Place the mouse over the token. The stat sheet displays: `"single value" = "single value" = single value`.
4. Type `[r: getProperty("AC")]`. The output is `« "single value" = "single value" = single value »`

**Expected behavior**
Both the stat sheet and `getProperty` should display `["single value"]`.

**MapTool Info**
- Version: develop (1.7 works fine)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by nmeier** [comment]
Having a look, might be related to the optimization for json arrays

**Comment by Azhrei** [comment]
Also related to #1733, another JSON/string conversion issue...?

**Comment by nmeier** [comment]
so MapToolLineParser interprets the ["single value"] [array as a roll](https://github.com/RPTools/maptool/blob/6d193e3f5cc635aed30730ec09fde2a210870054/src/main/java/net/rptools/maptool/client/MapToolLineParser.java#L801) - that seems to always have been there but didn't surface. Something in the detailed expression ends up slightly different (double quote). Still investigating.

**Comment by nmeier** [comment]
... that leads to a roll `""single value""` (a quoted string in the roll) which evaluates to the single value
single value

in expandRoll a comparision between value returned and detailed expression ends up unequal

`""single value"" != "single value"
`

**Comment by nmeier** [comment]
same behavior in https://github.com/nmeier/maptool/commit/a3760e29ca68266f70cd1c672cdc236884830ec5
going backwards to see when this changed

**Comment by Merudo** [comment]
It's my fault after all. #1871 causes the issue.

**Comment by Phergus** [comment]
Oops.

**Comment by Merudo** [comment]
The string `["single value"]` is parsed as `"single value"`, which caused the error.

PR #2058 fixes this by having the conversion to json array be done before the parsing.

**Comment by Phergus** [comment]
New code works for single element arrays added as described in first post or entered by hand.

One anomaly is that directly editing a property and putting in `'[1]'` also results in `« Property = ' »1 = 111 = 11«  »` in the stat sheet or when evaluated in a macro (`[Property]`).  Putting in an array with more elements such as  `'[1,2,3]'` is recognized as a JSON array and displays normally.  This is not new behavior and can be seen in MT 1.5.1+.
