### ISSUE TITLE
Bug: toggleFoW() macro generates spurious output

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#206]
Apparently the translation strings are missing from the i18n.properties which causes it to output either **msg.info.action.disableFoW** or **msg.info.action.enableFoW**
to the chat window.

Also true for **exposeFogAtWaypoints()** function which is returning/outputting:
**msg.info.action.enableRevealFogAtWaypoints
msg.info.action.disableRevealFogAtWaypoints**

Version: 1.4.1.8 and 1.4.5.3

Updated to note exposeFogAtWaypoints() and that problem shows in Nerps 1.4.5.3

**Comment by JamzTheMan** [comment]
Note this macro is a toggle, probably not the best name...

msg.info.action.enableRevealFogAtWaypoints: FoW will now expose at all cell points along the path.
msg.info.action.disableRevealFogAtWaypoints: FoW will now only expose at designated waypoints.

msg.info.action.disableFoW: FoW disabled.
msg.info.action.enableFoW: FoW enabled.
