### ISSUE TITLE
1.7.0: full token visible as soon as 1 pixel of token's square is within view

### ISSUE THREAD

**Issue by BlackPhoenix** [RPTools/maptool#2069]
**Describe the bug**
When a PC moves so that the NPC's token is not entirely blocked by VBL, the entire NPC becomes visible. In 1.6.1, only the part of the NPC token not blocked by VBL was visible.

**To Reproduce**
1. Create a new map with vision set to "Day"
2. Put a line of VBL
3. Place a PC token on one side
4. Place an NPC token where VBL prevents the PC from seeing it. Make sure "Is Visible over FOW" is not checked.
5. Move the PC little by little.
6. Once a single pixel of the NPC's *square* is not blocked by VBL, the entire token is visible.

**Expected behavior**
Only the portion of the NPC token that is not blocked by VBL should be visible. The PC could, for example, only see half of the NPC's token.

**Screenshots**
![image](https://user-images.githubusercontent.com/3641980/86522295-b6ead000-be29-11ea-9f5f-dee878c70dae.png)
![image](https://user-images.githubusercontent.com/3641980/86522297-bb16ed80-be29-11ea-98b8-70733e41c2da.png)

**MapTool Info**
- Version: 1.7.0
- Install: New
- Issue appears both on .deb package (Gentoo Linux) and .exe (Windows 7)

**Desktop (please complete the following information):**
 - OS: Windows 7, Gentoo Linux-5.4.28

**Comment by Merudo** [comment]
I can't reproduce:

![image](https://user-images.githubusercontent.com/7371085/86522481-1514b480-be24-11ea-8109-218dcca03fc8.png)

**Comment by Merudo** [comment]
I can reproduce, but only if the VBL is a token (token VBL).

**Comment by BlackPhoenix** [comment]
In my screenshots above, the dice is just to show the VBL. It's the wolf token that should not be visible in the second screenshot.

**Comment by Merudo** [comment]
![image](https://user-images.githubusercontent.com/7371085/86522589-e992c980-be25-11ea-91c9-10bc90c427d3.png)

The VBL is on the map and not a token VBL.

**Comment by BlackPhoenix** [comment]
Note that I did was not using FOW.

**Comment by Merudo** [comment]
Reverting #1802 fixes this bug.

It's likely that the tokens are not properly clipped to fit the visible area.

**Comment by Merudo** [comment]
Line causing bug: https://github.com/RPTools/maptool/pull/1802/files#r449819758

@nmeier can the line just be changed back to `clippedG.drawImage(workImage, at, this);`?

**Comment by Phergus** [comment]
That makes it work but will definitely need a bunch of vision testing.

**Comment by nmeier** [comment]
will look tomorrow - I can't remember why I introduced the graphics for the token only

**Comment by nmeier** [comment]
pull request coming shortly 

![image](https://user-images.githubusercontent.com/312857/86542174-4ef7c080-bee1-11ea-9cd3-43674ae820e4.png)

**Comment by nmeier** [comment]
test case 
[visiontest-2069.zip](https://github.com/RPTools/maptool/files/4876237/visiontest-2069.zip)

**Comment by Phergus** [comment]
Tested.  Seems to be working correctly for GM and Player views.
