### ISSUE TITLE
Drag/drop broken on macOS High Sierra and MT 1405

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#207]
Trying to drag an image from Finder and drop it on a map produces a popup dialog with an error message:

    Unable to obtain data from dropped object.
    Likely causes are an empty object due to a network error (such as proxy settings or
    missing authentication) or possibly an incompatible object was dropped (such as an
    invalid file type).

Given the error, it might be that file types are being checked in a particular order such that the PNG I tried to drop was detected first as something else, then the file couldn't be parsed as that "something else".  And it failed.

Note that drag/drop also fails to the Token Editor's Config panel, specifically the Portrait and Handout images, but also the Token image itself.  (Using the little green `+` and navigating to the file works fine).

**Comment by Phergus** [comment]
FWIW, a PNG file renamed with a .jpg extension and a JPEG file renamed with a .png extension both Drag/Drop without issue on Win10/Java10/MT1.4.0.5.

**Comment by JamzTheMan** [comment]
We may be ignoring extension of file and pull it in as a byte array and run it through the imagio lib and let it try and guess the image type.

**Comment by JamzTheMan** [comment]
@azhrei can you drag and drop rptok files?

**Comment by Azhrei** [comment]
Nope.  Just tried and got the same error message.

Yes, the code uses the MIME type.  So MIME types that include things like `image/*` are likely passed through to the Java image class and that class either reads it or doesn't.  Relying on filename extensions is _sooooo_ 1990's. 😉

**Comment by JamzTheMan** [comment]
So, which version of Java are you using? Since 1.4.0.5 is just the jar, I believe it was compiled/targeted for 1.7

**Comment by Phergus** [comment]
Time has rendered this irrelevant.  Closing.
