### ISSUE TITLE
Updating overlay doesn't remove previous onChangeSelection event

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#2074]
**Describe the bug**
Changing an overlay keeps the old onChangeSelection event if the new overlay has no such event defined.

**To Reproduce**
1. Create a Campaign macro named `print` with the code `[r: macro.args + 1d100]`
2. Run the following macro:

```
[h: processorLink = macroLinkText("print@Campaign", "all", "event fired: ")]
[overlay("Test"):{<link rel='onChangeSelection' type='macro' href='[r:processorLink]'>}]
```
3. Click on a token, and notice the chat message as expected
4. Run the  macro `[overlay("Test"):{No events}]`
5. Click on a token, and notice a chat message even though there is no `onChangeSelection` event.

**Expected behavior**
Launching an overlay doesn't keep the old events.

**MapTool Info**
- Version: 1.7, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #2075 fixes this.

**Comment by Phergus** [comment]
Tested working as expected.

Noticed that `onChangeToken` produces 4 events and is happening on a mouse-over.

**Comment by Merudo** [comment]
> Noticed that `onChangeToken` produces 4 events and is happening on a mouse-over.

Good catch! I created a new issue for this bug: #2078
