### ISSUE TITLE
Event onChangeToken fires on mouseover, two times per property displayed

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#2078]
**Describe the bug**
When moving the mouse over a token, the `onChangeToken` is fired twice per property displayed in the stat sheet.

**To Reproduce**
1. Create a new campaign with the Campaign Property showing HP and AC.
2. Create a token, set its HP and AC to any fixed value.
3. Create a campaign macro named `print`, with the code `[r: macro.args + " " + 1d100]`
4. Run the code
```
[h: processorLink = macroLinkText("print@Campaign", "all", "event fired: ")]
[frame("Test"):{<link rel='onChangeToken' type='macro' href='[r:processorLink]'>}]
```
5. With the frame open, move the mouse over the token created in 2. Four `onChangeToken` events will be fired, even though no token was actually changed.

also

6. If you impersonate any token and repeat 5., the event `onChangeToken` will instead be continuously fired non-stop until the frame is closed or the token is no longer impersonated.

**Expected behavior**
Moving the mouse doesn't trigger any `onChangeToken` event if the token is not changed.

**MapTool Info**
- Version: 1.5.2, 1.7, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
This is caused because the [parser triggers a onChangeToken](https://github.com/RPTools/maptool/blob/6d193e3f5cc635aed30730ec09fde2a210870054/src/main/java/net/rptools/maptool/client/MapToolLineParser.java#L1508) even if the token isn't actually changed.

**Comment by Merudo** [comment]
Seems like the following problematic code should just be deleted:

```java
        // If we have exited the last context let the html frame we have (potentially)
        // updated a token.
        if (contextStackEmpty() && tokenInContext != null) {
          HTMLFrameFactory.tokenChanged(tokenInContext);
        }
```
Functions that change tokens already fire a `onTokenChange` event by themselves, so there is no need for this additional bit of code.

**Comment by Phergus** [comment]
>     6. If you impersonate any token and repeat 5., the event `onChangeToken` will instead be continuously fired non-stop until the frame is closed or the token is no longer impersonated.

Egads.  That's not good.

**Comment by Merudo** [comment]
PR #2079 fixes this.

**Comment by Phergus** [comment]
Testing.  `onChangeToken` event only fires once when a property/attribute of a Token is changed.

Somewhat anomalous behavior:
* Right-click on token and select Impersonate
* Note that a `onChangeSelection` event occurs and token is still selected.
* Change a property of the token, e.g. [r: Strength = 3d6] or [r: setVisible(0)] from chat.
* Note an `onChangeSelection event fires along with an `onChangeToken` event.  The token remains selected.
