### ISSUE TITLE
DungeonDraft VTT import does not correctly handle doors where closed = false

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2081]
**Describe the bug**
When importing DungeonDraft VTT files if a doors closed property is set to false then vision and movement blocking will still be applied. Neither should be applied if the door is not closed.

**To Reproduce**
Create a map in DungeonDraft and set the closed property of a door to false before exporting.

**Expected behavior**
Doors with closed property set to false should not have vision or movement blocking.

**MapTool Info**
- Version: 1.7+

**Comment by Phergus** [comment]
Tested. Closed = true portals have VB.  Closed = false do not.
