### ISSUE TITLE
The default white light is painted over darkness sources with colors

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2094]
**Describe the bug**
The default white light trumps areas of light sources with colors, even if those light sources are darkness that the white light source does not penetrate.  This means that even the GM does not get a visual explanation for a token's inability to see certain areas.

**To Reproduce**
1. Create a Darkness source: `Darkness: circle 20#aa00aa lumens=-120`
2. Place the Darkness source on a token.
3. Add a generic light source (one without a specified color) to a nearby token.
4. Observe that the default light removes the visual indicator of darkness.

**Expected behavior**
If the light is not bright enough (lumens) to penetrate into the darkness, the color of the darkness source should be rendered over top of it, or at least should have some kind of blending like is done to light sources that have colors other than the default.

**Screenshots**
<img width="731" alt="1_7DefaultLightBleedIntoDarkness" src="https://user-images.githubusercontent.com/2325887/87569366-04223980-c695-11ea-8f65-b9f206f6fbdf.png">
This is from 1.7 - you can see that while the Hero's light source does not let him see into the darkness, the white light still covers it completely.

**MapTool Info**
- Version: 1.7 and current dev build for 1.8

**Additional context**
I originally thought this was an issue produced by #1893, but since it's behaving the same on 1.7, that's apparently not the case.  Definitely a related issue though.

Attached campaign (renamed to .zip) used in demonstration.

[LightsAndDarkness.cmpgn.zip](https://github.com/RPTools/maptool/files/4926480/LightsAndDarkness.cmpgn.zip)

**Comment by adyoungblood** [comment]
I'm currently working on the lighting code (specifically color blending), and this issue is cropping up in my tests. The default "white" light overrides the colors of CSS colored lights (even actual white ones, #ffffff hex code and all). Darkness sources are coded as lights, so it's the same code to be changed in this case. My only concern is that the default "white" light overriding the colors of other actual lights seems to be intended (at least, intended when the code was written). I imagine that is no longer the case?

**Comment by Phergus** [comment]
My expectation would be that a colored light source overlapping a default "white" light source would _tint_ the overlapped area at a lesser saturation.  Not sure why the current behavior is to override colored lights completely.

Unless someone comes up with an objection to the change I would say go ahead and fix it.

**Comment by adyoungblood** [comment]
The implementation of the default light being tinted would be akin to giving it a color, but only when it intersects colored lights. For that reason, it may be less obvious to users why their colored lights are changing tones when they overlap a default light.

It would be easiest to make the default light not affect colored lights at all; remove a few lines of code and it'll work just like that. Intuitively, a light without a color would therefore be a "clear" light, still exposing vision but not changing any colors.

**Comment by Phergus** [comment]
Sounds good.

**Comment by Azhrei** [comment]
Thank you, @adyoungblood — I'm looking forward to testing out your changes!

**Comment by Phergus** [comment]
Testing.  Mostly working as desired though note that the Red light is rendered over the Black darkness source while the Blue light is under it.  Both tokens were pasted onto the map after the darkness sources were added. GM View.

![image](https://user-images.githubusercontent.com/34379254/178311636-2bc59f3c-1b22-4602-83c4-7a53ef979a48.png)

On the Player client the darkness areas don't get rendered:
![image](https://user-images.githubusercontent.com/34379254/178312178-e7de529f-f386-4a84-96e6-1f85f19654c2.png)

Player client: Purple darkness over three colored lights gets rendered as white.
![image](https://user-images.githubusercontent.com/34379254/178312839-3e8e7327-4785-45f9-a20e-3f841a541953.png)

GM Client: Darkness is rendered as purple.
![image](https://user-images.githubusercontent.com/34379254/178312944-94fac597-0634-41a2-a844-cf2228d61a43.png)

**Comment by Phergus** [comment]
Tested.  Darkness sources no longer painted with white by other colored lights.  Any further issues should go on new ticket.
