### ISSUE TITLE
Add optional "sort order" argument to sortinitiative()

### ISSUE THREAD

**Issue by LarryWoestman** [RPTools/maptool#2097]
**Is your feature request related to a problem? Please describe.**
I am currently using the initiative window to track "who goes first" without an initiative roll.  I'm tracking seconds, rather than rounds.  It would make my macro programming easier if I could sort the initiative in "smallest first" order instead of the existing "largest first".

**Describe the solution you'd like**
It would be helpful if sortinitiative() allowed an optional "sort order" argument, allowing you to specify any of the "usual" pre-defined java sorting order choices.

**Describe alternatives you've considered**
I am currently using negative numbers for initiative values, but the programming would be easier to do and understand if I could use positive numbers and change the sort order.

**Additional context**

**Comment by selquest** [comment]
I'm going to try and work on some incremental changes to Initiative this weekend, and this one seems like an easy addition.

**Comment by selquest** [comment]
Added support for reverse (ascending) sort order.  This is implemented as a simple reversal of the default order, so blanks come first and strings (in ascending lexical order) come before numbers.
  - Initiative Panel menu option to use reverse ordering when using the Sort menu action (saved as a campaign property)
  - `sortInitiative()` function now accepts an optional `ascendingOrder` parameter:
    - `sortInitiative()` or `sortInitiative(0)` continues to use the default (Descending) sort order
    - `sortInitiative(1)` uses the new (Ascending) order
    - Note: I toyed with the idea of letting the `sortInitiative()` no-argument default follow the `Use Reverse Sort` setting, but decided against it to limit issues with backwards-compatibility.

**Comment by Phergus** [comment]
Tested.   Macro function `sortInitiative()` allows sorting Initiative Panel in Ascending (1) or Descending (0) order.

Setting Initiative Panel menu option,Use Reverse Sort Order does not affect use of default case for `sortInitiative()` and panel option is not changed when using the opposite sort order.

**Comment by selquest** [comment]
Described the default and reverse sort orders in the new http://lmwcs.com/rptools/wiki/Introduction_to_Initiative (WIP).
Updated wiki for `sortInitiative()` to describe optional param coming in 1.8
