### ISSUE TITLE
Importing macrosets is slow and requires too much memory

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2118]
**Describe the bug**
Originally reported by Ao on discord - when importing Campaign or GM macrosets for his pf2 framework, MapTool hangs for a long time and uses multiple GB of available memory.

The macrosets in question contain hundreds of macros, and many of the buttons are decorated with images, both of which are presumably contributing factors.

**To Reproduce**
1. Create a macroset with hundreds of macro buttons, many with labels including `<img />` tags.  _(NB: it may be helpful if Ao attaches the particular sample files used, but I don't feel comfortable passing them along myself without permission_)
1. Right-click the GM or Campaign macro panels and choose "Import Macro Set"
1. Note hang time, and observe consumption of additional memory (provided sufficient heap space).  In my testing with Ao's files, it often took several minutes to complete.  Task Manager showed 5GB of memory used at peak.

**Expected behavior**
Large macro sets should not take this long to import, nor fill multiple GB of heap.

**MapTool Info**
- Version: 1.7, Windows

**Additional context**
Some initial observations from looking into the ImportMacroSetAction code linked below - there's some O(n<sup>2</sup>) execution here as we iterate across the updated list of macros each time we add to it.  In fact, we do so multiple times:
1. to compare hashcodes and de-conflict
2. when finding the next Index to use for the newly created macro 
3. to save the newly created macro

There may be other things going on here contributing to the memory bloat (I haven't delved deeply into how the decorated macro buttons are impacting this, for instance), but re-implementing this to eliminate the need for these nested loops would probably be a good first objective.

Relevant code _(note: inside a foreach loop)_
https://github.com/RPTools/maptool/blob/496c0c69de639ebc30c594db8eb4e6bc42344964/src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttongroups/ButtonGroupPopupMenu.java#L379-L398

**Comment by pizzystrizzy** [comment]
Campaign File: https://www.dropbox.com/s/lmm8fxz8xb71wmy/pf2-fw-July24.cmpgn?dl=1

Campaign macros: https://www.dropbox.com/s/ta7vrai26q6hw6t/Campaign-Macros.mtmacset?dl=1
GM macros: https://www.dropbox.com/s/jxwbltq17zelurh/GM-Macros.mtmacset?dl=1

Related to this issue, I believe, is that when a token has many macros that contain images on their buttons, memory use becomes outrageous. See, for example, in the main cmpgn file, what happens when you click on the token "Spell Macros - Level 1", especially if you try to edit the macros on that token.

**Comment by Phergus** [comment]
The first few times I did the import of the campaign and then campaign macros, the images used on the buttons failed to load.  The log complained of broken images.  With no images, the campaign macros loaded in a few seconds and memory usage was under 2GB.  I'll note that that instance of MT 1.7 had been running for a couple days with a variety of abused heaped on it so not really concerned about the images failing to load.

Ran with current 1.8 develop code and the campaign loaded with all images.  Importing the campaign macros now took a bit over 5 minutes and pushed memory usage to just under 4GB.

Switched to 1.7 and the results were the same.

Images on buttons, using HTML in the labels to do so, seems to be really inefficient.

**Comment by selquest** [comment]
The GM & Campaign macro panels are reset when each newly imported macro is saved.  This reset includes revalidating and repainting the panel.  Presumably there's our memory issue, since the images will get loaded/painted again after each addition.

https://github.com/RPTools/maptool/blob/496c0c69de639ebc30c594db8eb4e6bc42344964/src/main/java/net/rptools/maptool/model/Campaign.java#L545

**Comment by selquest** [comment]
I'm going to add a version of the `Campaign.saveMacroButtonProperty()` method that makes calling the `reset()` method optional, and see where that gets us.  I expect that avoiding the repeated repaints will significantly improve performance and memory footprint, even if the nested loops remain.

Eliminating those loops would improve performance, but given that we don't really expect `n` to be more than a few hundred, we can probably get by with the current process.  If we did want to further streamline things though, the changes that would be needed to avoid nested loops:
1. Restructuring the Campaign & GM macro button lists to allow addition/update without having to loop across all existing buttons
1. Replacement methods to get the next button index of Campaign & GM panels without looping across all existing buttons
1. Re-implementation of the `ImportMacroSetAction` to populate a map for de-duplication and avoid repeated looping

Those first two items are the potentially problematic ones, as I haven't looked deeply enough to predict side-effects.

**Comment by nmeier** [comment]
I profiled the loading of the campaign properties and 75% of the time is indeed spent when the MacroButtonProperties are instantiated (226).

https://github.com/RPTools/maptool/blob/6d193e3f5cc635aed30730ec09fde2a210870054/src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttongroups/ButtonGroupPopupMenu.java#L395

I would suggest to build a list of MacroButtonProperties (those that don't auto save), collect them and pass them in one go. Then you don't have to suppress reset() with an eventual update. Since this runs on another thread anyways, it would be better to just load all that data, and then pass to the awt event queue.

**Comment by selquest** [comment]
> I profiled the loading of the campaign properties and 75% of the time is indeed spent when the MacroButtonProperties are instantiated (226).
> 
> https://github.com/RPTools/maptool/blob/6d193e3f5cc635aed30730ec09fde2a210870054/src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttongroups/ButtonGroupPopupMenu.java#L395
> 
> I would suggest to build a list of MacroButtonProperties (those that don't auto save), collect them and pass them in one go. Then you don't have to suppress reset() with an eventual update. Since this runs on another thread anyways, it would be better to just load all that data, and then pass to the awt event queue.

@nmeier If you look inside the MacroButtonProperties constructor, it's calling `save()`, which is what calls the `reset()`.

**Comment by selquest** [comment]
I've made some changes to allow macro buttons to be added in bulk without repainting after each one, and I'm definitely seeing the expected speedup.  In implementing these changes it ended up being necessary to handle some of the other items I'd identified, so there's some overall efficiency gains too.  I've got some more testing to do to make sure there aren't unwanted side effects, so probably won't have an actual PR until tomorrow.

**Comment by nmeier** [comment]
@selquest , there are constructors that don't save on creation.

**Comment by selquest** [comment]
Took me a couple days to get back to this, but changes are now in.  These sample files now load in my dev environment in a few seconds, and without a tremendous spike in memory used.  A good bit of additional memory is apparently required just to have the images on the buttons, but we're no longer multiplying the problem with redundant instances.

@nmeier I think we misunderstood eachother a bit here - avoiding the auto-saves to attach the new buttons en masse was definitely the plan, and a big part of avoiding the repaints.

**Comment by Phergus** [comment]
Nice improvement in performance.

Importing a 200 plain (no images) macroset:
**MT 1.7.0**:  14.5 secs
**Current Dev**:   < 1 sec

Loading AO's campaign macroset:
**MT 1.7.0**:  5 min 35 secs
**Current Dev**:  ~ 2 secs

**Comment by pizzystrizzy** [comment]
Nice work.

**Comment by selquest** [comment]
Hadn't seen #1483 when I made this one, or I wouldn't have made a duplicate.
