### ISSUE TITLE
Macros are slower than they could be because of roll options parsing

### ISSUE THREAD

**Issue by nmeier** [RPTools/maptool#2119]
**Describe the bug**

The MapToolLineParser kicks of an option roll parsing for every line item like so

`[option, option, option: block]`

The goal here is not to parse the same thing over and over (as we did for caching of expression parsing results in #1898). IF we have to parse, don't compile regex Patterns. They can be compiled once.

Additionally there's a call to MapTool.useToolTipsForUnformatedRolls() for every bracket-block to determine a default roll expansion as per user preferences. The call is expensive.

My results right now

```
[h: t1 = json.get(getInfo("server"),"timeInMs")]
[h, count(10000), code: {
	[h: v = roll.count]
}]
[h: t2 =  json.get(getInfo("server"),"timeInMs")]
[r: time = t2 - t1] ms
```

| | current development branch  | my changes| 
|--|--|--|
| avg of 10 runs | 516 ms | 115 ms  |

```
[h: t1 = json.get(getInfo("server"),"timeInMs")]
[h, count(10000), code: {
	[h: v = roll.count] [h: v = roll.count] [h: v = roll.count] [h: v = roll.count] [h: v = roll.count] [h: v = roll.count] [h: v = roll.count] [h: v = roll.count] [h: v = roll.count] [h: v = roll.count] 
}]
[h: t2 =  json.get(getInfo("server"),"timeInMs")]
[r: time = t2 - t1] ms

```

| | current development branch  | my changes| 
|--|--|--|
| avg of 10 runs | 5398 ms | 534 ms  |

**MapTool Info**
- Version: 1.8 development

**Comment by Phergus** [comment]
Pretty significant improvement.

**Comment by Phergus** [comment]
Tests prior to these changes:
```
Count 10k, 1 assignment, Avg of 10 runs:   0.7472 secs
Count 10k, 2 assignments, Avg of 10 runs:  1.3794 secs
Count 10k, 3 assignments, Avg of 10 runs:  2.0791 secs
Count 10k, 4 assignments, Avg of 10 runs:  2.7251 secs
Count 10k, 5 assignments, Avg of 10 runs:  3.3389 secs
Count 10k, 10 assignments, Avg of 10 runs: 6.6332 secs 
```
With these changes
```
Count 10k, 1 assignment, Avg of 10 runs:   0.1119 secs
Count 10k, 2 assignments, Avg of 10 runs:  0.1604 secs
Count 10k, 3 assignments, Avg of 10 runs:  0.2123 secs
Count 10k, 4 assignments, Avg of 10 runs:  0.2589 secs
Count 10k, 5 assignments, Avg of 10 runs:  0.310 secs
Count 10k, 10 assignments, Avg of 10 runs: 0.5573 secs 
```
Nice performance boost.

**Comment by Azhrei** [comment]
Yep, these are some great improvements — thanks, @nmeier!

I'm a little concerned that there may be a _lot_ of changes being dumped onto users all at once, such that framework authors might have a hard time finding where breakage occurred, if there is any.  Maybe there should be some interim beta builds or something so authors have time to make sure these changes didn't have unintended consequences?

**Comment by Phergus** [comment]
Some more testing. 10 runs of 10k.  Average run times in seconds.

| Operation | MT 1.7 | Pre 2122 | Post 2122 |
| :--- | ---: | ---: | ---: |
| JSON Append | 7.344 | 0.1508 | 0.1498 |
| JSON Get | 15.349 | 1.4780 | 0.2151 | 
| JSON Remove | 7.775 | 0.8301 | 0.1968 |

Macro:  [JSON_AGR_Test.mtmacro.zip](https://github.com/RPTools/maptool/files/4996544/JSON_AGR_Test.mtmacro.zip)

Looping through larger arrays and data structures should be noticeably faster over 1.7.0 it seems.

**Comment by Phergus** [comment]
@Azhrei - just as soon as we get the build file setup to do so.

**Comment by Phergus** [comment]
Testing with various macros has not revealed any problems.

**Comment by adventuremagic123** [comment]
Exciting isn't even enough of a word for this.  Great work!
