### ISSUE TITLE
Save background map texture as default for new maps

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#212]
When the user selects _Map -> New Map..._ from the menu, a dialog labeled **Map Properties** opens.  The various settings on this dialog could be stored in Java Preferences or the campaign so that new maps would default to the same values.

Discussion is needed about whether they should be campaign defaults or user defaults (I can see pros and cons both ways).

**Comment by Phergus** [comment]
I would think user default would be good as that way it can affect the default map background when you start MapTool.

I don't typically have a lot of maps with the same background within any given campaign and when I do it is probably the default grass.

**Comment by JamzTheMan** [comment]
How about user prefs unless you have a campaign file open which then uses campaign defaults?

**Comment by JamzTheMan** [comment]
I would say it probably only saves to the campaign after you use it. If you are in a campaign file and it doesn't exist use user defaults.

Also has to cover if there is a change in the dialog. So if we did campaign defaults may have to have dialog very or...

**Comment by JamzTheMan** [comment]
The downside if saving defaults, u have to track changes no matter what. Like say we add a new grid type. Now the radio group array has changed...

**Comment by Azhrei** [comment]
Hm.  MT always has a campaign open and always has a server running.  So you're going to base the "campaign check" on whether the campaign has been saved then, I presume?  I guess I'm fine with that, but it means that until the campaign is saved, any changes are going into the user prefs... 🤔

I think we should store the text string that each control tells us to save (so the radio button group tells us to save "HexH", then that's what we write).  That way we can save and restore without updating our code even if the list of values changes.  If a preference for a particular control doesn't match any controls we have when restoring, we ignore it and choose a builtin default.

Is that reasonable, or did I leave something out?

**Comment by JamzTheMan** [comment]
Sounds about right. I'd say it's. Low priority enhancement though.

**Comment by Azhrei** [comment]
Yep, but an easy one for a newcomer, most likely. 🙂

**Comment by Phergus** [comment]
The original user comment on Discord was about the map background that is used at MapTool startup and not about the default used when doing a Map -> New Map.    All other default map settings that affect both the startup map (which is of course a New Map itself) and maps created through Map -> New Map can be found on Edit -> Preferences -> Interactions ->Maps.   So what is missing for that requirement is just a background texture selection widget on the preferences dialog.   As these preference settings are always user prefs, I'm not sure where in the UI a campaign only widget would be added except on the Edit -> Campaign Properties dialog but now you are duplicating all of the map settings UI in that dialog.  How else will a user be able to tell what they are changing, the global default or the campaign default?

**Comment by Azhrei** [comment]
> The original user comment on Discord was about the map background that is used at MapTool startup and not about the default used when doing a Map -> New Map.

But isn't that the same thing?  If the code that implements the _New Map_ functionality is the same code that is used by MT when it starts, then whatever defaults are used by the panel would be the defaults used for the initial map.  (I'm not saying the code is the same, but I can't see any reason why it wouldn't be.  And if it isn't, it probably should be. 🙂)

Although I suppose it can't be named `Grasslands`, in that case.  Perhaps the generic and boring `Initial Map` instead?

> How else will a user be able to tell what they are changing, the global default or the campaign default?

That was my point about trying to put it in two places.  I suppose the _New Map_ dialog could have a checkbox/switch that says to use defaults from user prefs or campaign prefs — that way there's no need for another UI panel — but that seems a little kludgey.

Perhaps they shouldn't be saved anywhere?  The first time you use _New Map_, you select the values you want, then they are saved in memory for the next time the panel is used.  But they're not persisted anywhere.  Or maybe they should default to the settings used for the current map?

Lots of options.  Hence the necessary discussion.

**Comment by Azhrei** [comment]
Okay, how about this...

The panel remembers the last settings used, but there’s a button to copy the settings of the current map.

**Comment by Phergus** [comment]
Are you referring to the New Map dialog or the New Map settings in the Preferences dialog?

**Comment by Azhrei** [comment]
Sorry, I meant the _New Map_ dialog.

I'm looking at all of these map fields...

Why is Movement Metric under the "Maps" section in Preferences when it's a server setting?  (And why _isn't it_ a true per map setting?)  And if the Preferences dialog is going to have defaults for four of the fields (cell type, distance per cell, pixels per cell, and vision distance), why not the other three (background texture, fog texture, and map)?

It seems that the way map properties are managed needs to be cleaned up.  But that's a larger scope than this issue.  I think if someone wants to implement the settings in the _New Map_ such that the recently used values are used as defaults for new maps, then I'm good with that, but there's no need to modify anything else.  (The Preferences dialog would then contain values that are only used for the first _New Map_.)

**Comment by JamzTheMan** [comment]
All valid.

**Comment by JamzTheMan** [comment]
How about this...

Personally I find the New Map menu with the default 10 or so tiles sort if useless and never use anything other than black (is it just me?)

So we could remove those and instead show a most Recent list?

And/or on new map, just throw a * setting that marks it as a Favorite.

The menu then shows favorites, separator, Most Recent (or some such)?

**Comment by Azhrei** [comment]
I think the 10 default textures is good for beginners to give them ideas of what they can do with the tool.

But I agree that they could simply be on the default tab that opens ("Samples"), and other tabs _should_ include "Recently Used" and/or "Currently Used" (by other maps within the same campaign), and maybe a "Favorites".

"Recently Used" would require keeping track somewhere and we're back to "should they be saved in user prefs or campaign props?"

**Comment by Phergus** [comment]
> Why is Movement Metric under the "Maps" section in Preferences when it's a server setting? (And why _isn't it_ a true per map setting?) And if the Preferences dialog is going to have defaults for four of the fields (cell type, distance per cell, pixels per cell, and vision distance), why not the other three (background texture, fog texture, and map)?

All good questions.  Having a default map doesn't make much sense but having a preference for the background and fog texture defaults is reasonable.  The background is why we are here.

> I think if someone wants to implement the settings in the _New Map_ such that the recently used values are used as defaults for new maps, then I'm good with that, but there's no need to modify anything else. (The Preferences dialog would then contain values that are only used for the first _New Map_.)

Well the preferences dialog would need to be updated to include the ability to set the default background texture.

**Comment by Phergus** [comment]
re: Quick Map textures.  I rarely use them but I have used a few of them.  An equivalent Recent or Favorites would be handy I think.

**Comment by Azhrei** [comment]
> Well the preferences dialog would need to be updated to include the ability to set the default background texture.

That's because you're referring to the OP from the Discord channel that wanted the initial map background to be different.  But exactly how often does one use the initial map?  It's only used once per campaign, right?

That's one reason why I changed this issue to be saving settings from _New Map_ automatically.  Create one map and those are the defaults for all future maps (during that MT session, anyway).

I suppose if you never create a campaign and just use MT on the fly for all of your games, then those defaults could be a little annoying.  But given the various settings available as campaign properties — and given that most people are not going to want to make those changes every time they open MT — it seems less likely that the initial background texture is very important.

Just my $0.02

**Comment by Phergus** [comment]
How often does one use the initial map?  Maybe never if the default texture is fixed at the wrong one.  However, if there is a user-chosen default maybe that goes up to 50% of the time or more.  

By adding it to the Preferences this would also let the New Map dialog start with this default.  I believe that most folks are likely to have a favorite and whether they are creating a new campaign or adding a map to an existing campaign, that default would have the best chance of being the one they want for a new map.

Having the new map automatically use the settings of the last map created might be the wrong choice more often than night.  If I've got several underground maps, some above ground town maps, a few wilderness maps and a sea map, the next map could be any of those types or a completely different one.  In this situation, and many others, the earlier suggestion of pulling the settings from the current map would easily allow the user to start a new one based on any of the maps already in the campaign. 

I don't now where you are headed with the last paragraph.  What does any of this have to do with campaign properties?

**Comment by JamzTheMan** [comment]
Yea, the "new map on new campaign" seems silly to fix.

Or rather, it should be fixed by not starting with a map but rather a "starting page" we talked about a couple years ago on slack :)

And I agree, a better dialog with recent textures and colors and fog etc shown would be a step forward.

As for saving, I would think local would be fine. But as soon as I say that someone probably works in a campaign file on multiple computers so campaign would be better for them...

**Comment by Jaggeroth** [comment]
This all sounds like a lot of work for minimal returns :(

**Comment by JamzTheMan** [comment]
Abillie forms? Ack. No. I wouldn't touch this until 2.0. hopefully preferences will be clearer and easier to store then as well...

**Comment by Azhrei** [comment]
Yeah, I agree.  It turned into something that’s too much hassle with a UI revamp on the horizon...

**Comment by JamzTheMan** [comment]
So why did you close this? Are you keeping issues only for 1.4.x?

I'd create a DEFERRED tag or some such.

Also, do you guys want to use a GitHub project to organize issues? I find it handy. We could organize issues by priority? (I think I have my current as low/medium/high/deferred/done/todo

**Comment by JamzTheMan** [comment]
I don't know about anyone else but currently I'm just rewriting current functionalality including UI unless I know we want to change said UI it it makes sense to me.

For instance, I very most likely would have just recreated the new map dialog in FX as is until this issue popped on my radar.

Now whether I remember this by the time I get to that UI is another matter :)

Someone should probably at least keep a list of things we want to change (and said list could point to issues or docs for more info)

And said list should track if it needs to go for 2.0 or a later 2.x phase.

Sorry, this is probably a hijack of this thread but...ya.
