### ISSUE TITLE
Java 11 features are being used

### ISSUE THREAD

**Issue by ebudai** [RPTools/maptool#2136]
Specifically, String::isBlank() and String::repeat()

I can write utility methods for these in StringUtil, or you can change the minimum requirements to Java 11.

**Comment by Phergus** [comment]
The requirements need to be changed.

**Comment by ebudai** [comment]
If Java 11 is used, jdk.packager.services.UserJvmOptionsService is removed.

**Comment by ebudai** [comment]
Also now getting java.lang.ClassNotFoundException: sun.reflect.Reflection, removed in JDK 11

**Comment by ebudai** [comment]
This was solved and I can get MT running by updating JIDE to the latest version.

**Comment by Phergus** [comment]
@ebudai   Are you saying that there isn't a problem and this issue can be closed?

**Comment by ebudai** [comment]
I can run without doing anything extra now.  As a side question: Intellij wants me to change large switch and if/else into java 14 switch expressions.  I agree with it - it reads easier to me.  Can I go ahead and do that where I feel it improves readability?

**Comment by Phergus** [comment]
I'm going to take that as a yes.

The next release will be packaged with Java 14 so I don't see any reason not to use Java 14 style switches.
