### ISSUE TITLE
Java problems on iMac 

### ISSUE THREAD

**Issue by OronirL12** [RPTools/maptool#214]
![error_nerps1453_editmacro](https://user-images.githubusercontent.com/45273824/48922602-22c43300-eea8-11e8-80a9-cd897a8a20db.jpeg)
This is the error I am getting every time I want to edit a macro, very annoying and makes experimenting with macros a hassle. The problem does NOT occur with the regular map tool 1.4.1.8.

**Comment by Azhrei** [comment]
Yeah, pretty sure he's said he's using Jamz' fork; this error doesn't apply to the official release so I'm closing this.

**Comment by OronirL12** [comment]
Hey guys

Yes a Nerps version. Where should I post it then? I just followed Phergus’s advice.
Thanks

**Comment by Azhrei** [comment]
I think it’s at JamzTheMan/maptool (you can probably just edit the URL directly).
