### ISSUE TITLE
Bug: Function isNumber returns 1 for the empty string

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#2152]
**Describe the bug**
On develop, the function `isNumber` returns `1` instead of `0` for the empty string `""`.

**To Reproduce**
1. Type `[r: isNumber("")]`
2. Notice it returns `1` instead of `0`.

**Expected behavior**
It should returns `0` for the empty string, as it does in 1.7.0 and in previous versions.

**MapTool Info**
- Version: develop (8/5/2020)
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

This is due to the behavior of `isNumeric` in StringUtils library from org.apache.commons.lang.

**Comment by Merudo** [comment]
This could be fixed by updating to a more recent org.apache.commons library in gradle.

From the [change notes](https://commons.apache.org/proper/commons-lang/article3_0.html),

> StringUtils.isAlpha, isNumeric and isAlphanumeric now all return false when passed an empty String. Previously they returned true.

**Comment by Merudo** [comment]
PR #2154 fixes this.

**Comment by Phergus** [comment]
Tested.  Function returns false for an empty string.
