### ISSUE TITLE
Allow specific PickOnce table entries to be reset

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2157]
**Is your feature request related to a problem? Please describe.**
When using PickOnce tables to represent a draw pile in a card game, it is often the case that specific discarded cards should be "shuffled back in", while specific other cards (still in a player's Hand, for instance) are not.  The `resetTablePicks()` function is currently all-or-nothing, meaning a follow-on macro is required to identify retained cards and re-select them from the table to exclude them from the reset draw pile.

**Describe the solution you'd like**
Add optional parameters to the `resetTablePicks()` function allowing a String List or JSON Array containing the indices of specific table entries to reset.

Specifically:
* `resetTablePicks(tblName)` - reset all entries on the table (current behavior)
* `resetTablePicks(tblName, entriesToReset)` reset specific entries from a String List with "," default delimiter
* `resetTablePicks(tblName, entriesToReset, delim)` - use custom delimiter
* `resetTablePicks(tblName, entriesToReset, "json")` - entriesToReset is a JsonArray

**Additional context**
It's important to note that PickOnce tables behave a bit differently than regular tables - entries are identified and selected by list index, and do not take configured ranges into account when selecting or identifying entries.

**Comment by selquest** [comment]
Wiki page for `resetTablePicks()` updated to reflect changes coming in 1.8.

I'm also going to add some notes on the wiki about Pick Once tables using list indexing instead of ranges, since adding a place where those ids can be used increases the opportunities for confusion.

**Comment by Phergus** [comment]
Tested.  Working as described.
