### ISSUE TITLE
Attempting to use a server name already in use should produce an error

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#2159]
**Describe the bug**
As reported via Discord, when a server name matches an existing server name, no error is generated but players are sent to the wrong IP address and port.

**To Reproduce**
1. Start a server with a name that matches an existing name (in the RPTools Alias field).
2. Note that there's no error message.

**Expected behavior**
A name that is already in use should produce an error message.

**MapTool Info**
- Version: 1.7 (all)

**Additional context**
The implementation will probably require that MapTool generate a GUID that is stored in the registry along with the server name.  This allows a given instance of MapTool to uniquely identify itself.

However, if MapTool were to crash, it should use the same GUID when it starts back up so that it can replace any existing server name with a new one.  This means it can't simply be a random number.  Perhaps it creates a random GUID that is stored under **~/.maptool-rptools/** and once created, the same file contents are reused.  Other implementations are possible as well.

**Comment by kwvanderlinde** [comment]
Looking at the history, this was done as part of the registry change back around 1.8. If you try this today you will get an error message:
![image](https://github.com/RPTools/maptool/assets/7492219/afc07d7f-0feb-416d-955e-4529da46f365)

And looking at the registration request, each client sends along its persisted unique ID, so this seems to all be accounted for.
