### ISSUE TITLE
Java 14 Startup Options

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2174]
**Describe the bug**
Unfortunately the packager/installer for Java 14 does not have the same flexibility for specifying start up options. This leads to problems under Mac OS and Linux when trying to modify the startup configuration file.

**MapTool Info**
- Version: 1.8

**Comment by Phergus** [comment]
Tested under Windows.  Working as expected.

Any Mac/Linux users want to chime in?

**Comment by Phergus** [comment]
Testing for other platforms to happen on release.
