### ISSUE TITLE
Chat output when using macroLink() is not styled as regular chat output

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#2177]
**Describe the bug**
When calling a macro via `macroLink()` that has a default chat output (i. e., not via `broadcast()`), the chat output is styled like before the changes from #1318.

**To Reproduce**
1. Open the attached campaign file.
2. Run the macro “Test.” It simply outputs “Test” in the chat.
3. Run the macro “macroLink.” It outputs a link (“Click here!”) to the chat.
4. Click the link in the chat. It calls upon the macro “Test.”
5. The chat output is not styled according to the changes from #1318. 

**Expected behavior**
I expect the chat output to be the same, regardless of whether the macro is run directly or called via `macroLink()`.

**Screenshots**
<img width="849" alt="Bildschirmfoto 2020-08-26 um 19 01 55" src="https://user-images.githubusercontent.com/40534855/91334023-ae31cd00-e7ce-11ea-8221-900009e62cef.png">
<img width="849" alt="Bildschirmfoto 2020-08-26 um 19 02 04" src="https://user-images.githubusercontent.com/40534855/91334038-b12cbd80-e7ce-11ea-84fd-29a1d07214a8.png">
<img width="373" alt="Bildschirmfoto 2020-08-26 um 19 01 40" src="https://user-images.githubusercontent.com/40534855/91334045-b38f1780-e7ce-11ea-9b37-bfb1155f34ad.png">

**MapTool Info**
- Version: 1.7.0
- Install: Upgrade 1.6.X

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.5

**Additional context**
[macroLink Chat Output.cmpgn.zip](https://github.com/RPTools/maptool/files/5131270/macroLink.Chat.Output.cmpgn.zip)

**Comment by Irarara** [comment]
Working on this.

**Comment by Phergus** [comment]
That is something much talked about but hasn't coalesced into action yet.  Ideally there would be user-editable CSS instead of all the various bits of formatting embedded in the code in different places.

**Comment by Phergus** [comment]
Tested.  Working as expected.
![image](https://user-images.githubusercontent.com/34379254/101993865-0fe14e80-3c7b-11eb-8add-81eb21889443.png)
