### ISSUE TITLE
On develop, token opacity does not work

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#2178]
**Describe the bug**
On develop, the token opacity does not work. Regardless of the opacity settings of the tokens, it remains 100% opaque on the map.

The opacity is correct in the token editor and states are transparent as well.

**To Reproduce**
1. Open a new campaign.
2. Add a token.
3. Edit the opacity of the token. Turn it down to 5%.
4. Close the editor. The token is not transparent.

**Expected behavior**
The token should be almost completely transparent with an opacity of 5%.

**MapTool Info**
- Version: 1.8.0 Snapshot-193d2d4
- Install: New

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.5

**Additional context**
I played around with the OpenGL and Direct3d settings, to no avail.

**Comment by ebudai** [comment]
This is caused by the same code I reverted to fix #2151 .  I have a PR incoming which fixes this issue by combining reverted and new code.

**Comment by Phergus** [comment]
@ebudai   Your change makes all non-figure PC/NPC tokens invisible.

**Comment by ebudai** [comment]
Looking at the code, it's obvious why now.  I messed up negating the figure/visibility when reducing the structure.  

`token.getShape() != TokenShape.FIGURE || !token.isAlwaysVisible()` should be `token.getShape() != TokenShape.FIGURE && !token.isAlwaysVisible()`

I have a PR incoming to fix it as soon as I test my theory.

**Comment by ebudai** [comment]
On the assumption I incorrectly reduced the if structure, I restored the original, and applied the opacity fix, and everything seems to work ok, but for one issue I see in the attached map: three doors don't disappear when you deselect the hero token on player view.
[DonjonMapTest180alpha.zip](https://github.com/RPTools/maptool/files/5139519/DonjonMapTest180alpha.zip)

**Comment by Phergus** [comment]
Talking about the 3 doors up by the Mage token?   Deselecting the Hero token would be the party view and those three doors are in visual range of other PCs.  The problem is that a check for the whether or not the area has been exposed is apparently missing.

**Comment by Phergus** [comment]
Testing shows that the issue with VoFoW tokens being show in Party View even if not in an exposed area occurs in 1.6.1 and 1.7.0 as well.

Token opacity appears to be working correctly.
