### ISSUE TITLE
Lock Movement toggle also changes Owner Permissions

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2184]
**Describe the bug**
Toggling the Lock Movement option on the Initiative Panel's dropdown interferes with the Owner Permissions setting.

**To Reproduce**
1. On the Initiative Panel, click the drop-down menu and note the state of the Owner Permissions option.
1. Click on 'Lock Movement'
1. Note that 'Owner Permissions' state is set to the inverse of 'Lock Movement'.

**Expected behavior**
These settings should toggle independently.

**MapTool Info**
- Version: 1.7

**Additional context**
This appears to have just been a copy/paste error in the code, but if it was for some reason actually the intended behavior then we should presumably be enforcing it on the Owner Permissions toggle too...

**Comment by selquest** [comment]
I'll take care of this while making other incremental improvements to initiative.

**Comment by Phergus** [comment]
Tested.  Changing Lock Movement no longer toggles state of Owner Permissions.

**Comment by Phergus** [comment]
Documented on [Intro to Initiative](http://www.lmwcs.com/rptools/wiki/Introduction_to_Initiative) wiki page.
