### ISSUE TITLE
Feature Request: the ability to remove a drawing via a macro

### ISSUE THREAD

**Issue by euank** [RPTools/maptool#2188]
Currently, macros are able to get information about drawings, change their properties, move them around, etc.

They're not able to create or delete them however. Creating drawings is definitely more convenient by hand, so it's understandable for a drawing to not be create-able via a macro, but they should be delete-able.

For a concrete example of how this might help:
In our D&D campaign, we use the drawing tool to draw the AOE for fireballs and the like.
It would be convenient if the macro that prints fireball damage could also then delete the AOE since it's been fully resolved.

**Describe alternatives**

Setting opacity. It clutters up the draw explorer list to use this workaround.

**Additional context**

This request is proxied over from this forum thread someone else posted: https://forums.rptools.net/viewtopic.php?f=26&t=28823&p=276549

**Comment by Phergus** [comment]
Tested.  `removeDrawing(MapName, DrawingID)` working as expected.
