### ISSUE TITLE
Null pointer exception in 'movedOverDrawing' when moving over a template

### ISSUE THREAD

**Issue by euank** [RPTools/maptool#2192]
**Describe the bug**

Calling the `movedOverDrawing` macro function for a template drawing + a path that intersects it results in a null pointer exception.

**To Reproduce**
1. Open maptool on the default 'Grasslands' map.
2. Turn on 'show coordinates', draw a radius template at 0,A
3. In the draw explorer, get the drawing GUID
4. Run the macro command: `[r: movedOverDrawing("Grasslands", "<GUID from step 3>", '[{"x": 0, "y": 0}, {"x": 50, "y": 50}]')]`

Observe a null pointer exception like so: `java.lang.NullPointerException: Cannot read field "curves" because "rhs" is null error executing expression movedOverDrawing("Grasslands", "<GUID>", '[{"x": 0, "y": 0}, {"x": 50, "y": 50}]')`.

**Expected behavior**

It should return the coordinates of the path since the path does overlap.

**MapTool Info**
- Version: current develop commit (cd482937)

**Desktop (please complete the following information):**
 - OS: NixOS

**Additional context**

This was also reported by another user in the forum: https://forums.rptools.net/viewtopic.php?f=21&t=28824

The source of this NPE is that `movedOverDrawing` uses `getArea` to calculate path intersection, but the RadiusTemplate `getArea` returns null:

https://github.com/RPTools/maptool/blob/6d193e3f5cc635aed30730ec09fde2a210870054/src/main/java/net/rptools/maptool/model/drawing/RadiusTemplate.java#L128-L131

Most (all?) of the other template types don't implement `getArea` either.

I've already started working on this, and I expect to have a pull request before too long.

**Comment by Phergus** [comment]
Testing.  No longer produces an exception but it also does not return the correct values.

Two square drawings and a square template on map.  The first square drawing was done with snap-to-grid and the second free-hand.  Template drawn normally.  Tokens placed on left side of drawings and dragged to right side. Starting and ending outside of the drawings.  Like so:

![MovedOverDrawingBug1](https://user-images.githubusercontent.com/34379254/92334153-a680ec80-f048-11ea-9a35-044521bef444.png)

Results of `getLastPath()` for each token and then `movedOverDrawing()` using those paths.

![MovedOverDrawingBug2](https://user-images.githubusercontent.com/34379254/92334173-d16b4080-f048-11ea-928c-10f86bcc3745.png)

For the Blue Path, `movedOverDrawing()` returns the starting point which is outside of the drawing as well as the three cells within the drawing.

For the Red Path, `movedOverDrawing()` returns the correct set of points.

For the Green Path (over the template drawing), `movedOverDrawing()` returns the starting point which is outside of the drawing as well as the three cells within the drawing.

No idea why `movedOverDrawing()` is returning two sets of points {x1,y1} and {x2,y2} or what the second set is intended to be used for.

Campaign File (remove `.zip` from end):
[MovedOverDrawing3_161.cmpgn.zip](https://github.com/RPTools/maptool/files/5180218/MovedOverDrawing3_161.cmpgn.zip)

The incorrect return values also happen in 1.6.1 and 1.7.0.
