### ISSUE TITLE
getMatchingProperties is returning property names converted to lower case

### ISSUE THREAD

**Issue by LarryWoestman** [RPTools/maptool#2194]
getMatchingProperties returns property names in lower case rather then their original case.

**Comment by Azhrei** [comment]
Thanks for the bug report, but there's a template to follow when filling out bug reports!  (Granted this one is pretty simple, but still. 🙄)  I won't close this one (I'll let you do it), but consider filling out a new one and choosing the "Bug" template.  Thanks.

**Comment by LarryWoestman** [comment]
Sorry, I forgot about the template.  I'll try not to do that again.
