### ISSUE TITLE
Release builds fail with JDK14/jpackage if they contain -rc/-beta/-alpha etc in tag name.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2197]
**Describe the bug**
The builds fail when trying to upload assets to GitHub if the tag names contain anything other than numeric x.y.z version number.

**To Reproduce**
Create a tag such as 1.8.0-rc1 and watch the build fail.

**Expected behavior**
Build should complete successfully and assets should be uploaded to GitHub release.

**Comment by Phergus** [comment]
Tested.  MapTool 1.8.0-beta.2 release produced all platforms with appropriate names.  The Mac and Windows installers are working.  No reports on other platforms so far.
