### ISSUE TITLE
Rotating Object VBL of non-square image doesn't draw vbl properly

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#220]
Issue reported here: http://forums.rptools.net/viewtopic.php?f=86&t=27926

If the image is set to native size then it draws the vbl properly when rotated, but not for the other size options for non-square images.

* Also, VBL drawn doesn't cover bottom pixel when generated. Video shown in link.

**Comment by Phergus** [comment]
Unable to reproduce.  Possible fixed by other changes in the past year.
