### ISSUE TITLE
Improve efficiency of onTokenMove when multiple tokens selected

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2205]
**Is your feature request related to a problem? Please describe.**
When moving multiple (visible) tokens, the `onTokenMove` event handler is called for each token.  As currently implemented (in 1.7 and dev), this performs a re-scan of Library tokens between each selected token.

**Describe the solution you'd like**
Lookup the relevant handler once, and execute it for all selected tokens.

**Additional context**
Encountered this while working on #2201, but didn't want to fix without its own issue.

**Comment by Phergus** [comment]
Tested.  Events `onTokenMove` and `onMultipleTokensMove` working as expected.
