### ISSUE TITLE
www.nerps.net certificate (used by Gradle) is broken

### ISSUE THREAD

**Issue by duckinator** [RPTools/maptool#2210]
**Describe the bug**

When running `./gradlew build` command, it tries to download files from https://www.nerps.net/ , which has a certificate that's only valid on https://nerps.net.

**To Reproduce**

1. Clone the repository
2. Run `./gradlew build`

Or

1. Navigate your browser to https://www.nerps.net/

**Expected behavior**
The certificate was valid.

**Screenshots**

![Screenshot_20200908_205800](https://user-images.githubusercontent.com/39698/92542150-02e53700-f216-11ea-9e28-55fa99eafac4.png)

**MapTool Info**
- Version: git, 1.8.0-beta.2 branch
- Install: N/A, trying to build it

**Desktop (please complete the following information):**
 - OS: Fedora (Linux)
 - Version 31

**Additional context**
Ideally, the certificate would work, but in the meantime this diff will allow you to pretend everything is fine:

[issue-2210-patch.txt](https://github.com/RPTools/maptool/files/5191998/issue-2210-patch.txt)

**Comment by Phergus** [comment]
There was something wrong with his DNS/domain earlier.  He updated his A record and as soon as it propagates out to you it should be working.  Couldn't have done the 1.8.0 release if it wasn't.

**Comment by duckinator** [comment]
Alright, I'll go ahead and close this issue then. :+1:

**Comment by Phergus** [comment]
If it isn't working for you soon let us know.

**Comment by JamzTheMan** [comment]
Oh, i just added an ssl cert to the sight as well. Http should redirect to https now as well.

@cwisniew should host this jide as well for a backup? Any other alternatives?
