### ISSUE TITLE
1.8.0-b2 creates a visible "${sys:appHome}" folder in user's Home

### ISSUE THREAD

**Issue by Gnomasz** [RPTools/maptool#2220]
**Describe the bug**
On launch, MapTool creates a **${sys:appHome}** folder in the user's Home directory, where it stores logs.

**To Reproduce**
1. Install MapTool v. 1.8.0-beta.2 on Linux using a .deb package.
2. Launch MapTool.
3. Open your Home directory and check the list of folders.

**Expected behavior**
Logs should be saved under /home/[user]/.maptool-rptools/logs

**MapTool Info**
- Version: 1.8.0-beta.2
- Install: New, .deb package

**Desktop:**
 - OS: Linux Mint Tricia
 - Version 19.3
 (base: Ubuntu 18.04 bionic)

**Additional context**
Debug info:
==== MapTool Information ====
MapTool Version: 1.8.0-beta.2
MapTool Home...: /home/tomek/.maptool-rptools
MapTool Install: /opt/maptool/lib/app
Max mem avail..: 476 MB
Max mem used...: 89 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: /opt/maptool/lib/runtime
Java Vendor....: Azul Systems, Inc.
Java Version...: 14.0.2
Java Parameters: 
  -Djava.library.path=/opt/maptool/lib/app:/opt/maptool/bin
  -Djava.launcher.path=/opt/maptool/bin
  -Xss8M
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED

==== OS Information ====
OS Name........: Linux
OS Version.....: 5.4.0-47-generic
OS Architecture: amd64
PATH...........: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Number of Procs: 2

==== User Information ====
User Name: tomek
User Home: /home/tomek
User Dir.: /home/tomek

==== Network Interfaces ====
Display Name..: wlp2s0
Interface Name: wlp2s0
Address...: fe80:0:0:0:35be:ccda:a573:caf5%wlp2s0
Address...: 2a02:a311:803c:c680:d5ad:29c8:8925:156%wlp2s0
Address...: 2a02:a311:803c:c680:fb95:775d:7aaf:eaa4%wlp2s0
Address...: 192.168.0.199

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.0.1

==== Locale Information ====
Country.: Poland
Language: Polish
Locale..: Polish (Poland)
Variant.: 

==== Encoding Information ====
Default Locale:   pl_PL
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1366x768(-1)

==== Internet Gateway Devices ====
	No IGDs Found!

Created logfile:
[maptool.log](https://github.com/RPTools/maptool/files/5209223/maptool.log)

**Comment by Tdue21** [comment]
For the record, this is not the case on Windows.

**Comment by Phergus** [comment]
Appears to be a log4j configuration error.

**Comment by Phergus** [comment]
MT 1.8.0-beta.2 isn't creating logs at all under Windows as the path spec causes an error:
```
2020-11-25 07:13:46,427 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy for element DefaultRolloverStrategy: java.nio.file.InvalidPathException: Illegal char <:> at index 5: ${sys:appHome}/archive java.nio.file.InvalidPathException: Illegal char <:> at index 5: ${sys:appHome}/archive
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
```

**Comment by Phergus** [comment]
Once the PR is merged, if someone on Linux and MacOS can test the change it would be helpful.

**Comment by Phergus** [comment]
@Gnomasz @kayila  did the change help under Linux?

Logging under Windows when run from IntelliJ is still broken and is going to `${MAPTOOL_DATADIR}\.maptool-rptools\logs` under the project directory.

**Comment by Gnomasz** [comment]
@Phergus 
Same for me on Linux Mint on the package from 18 days ago. I cannot tell how it is on current Github version, building from source is a bit too much for me atm.

Or, more elaborately:
**Fix failed** on build MapTool 1.8.0 Beta 2b, .deb on Linux Mint Tricia Version 19.3 (base: Ubuntu 18.04 bionic):
- MapTool no longer creates a **${sys:appHome}** folder in the user's Home directory

_however_
- MapTool creates a **${MAPTOOL_DATADIR}** folder in the user's Home directory upon first launch and stores logfiles under /home/[user]/${MAPTOOL_DATADIR}/.maptool-rptools/logs/

**Comment by Phergus** [comment]
Not following you as you originally said it was broken on 1.8.0-Beta.2b and so it only makes sense that it is still broken in that same version.

The change is only in the dev code right now but I suspect it is still broken for all platforms.  You would have to run/build from current dev code.

**Comment by Gnomasz** [comment]
Not exactly the same build. Original post was on  beta 2 (which i shortened to b2), now I checked on beta 2b. I know, I was confused myself.
As I said, building from source is a bit too much for me atm (never done it before). Still, the behavior is like you mentioned under Windows, so all platforms quite probably.

**Comment by Phergus** [comment]
This has been fixed in the next beta.
