### ISSUE TITLE
Menu launcher has OpenJDK icon instead of MapTool's

### ISSUE THREAD

**Issue by Gnomasz** [RPTools/maptool#2221]
**Describe the bug**
MapTool launcher has OpenJDK icon. The file /opt/maptool/lib/MapTool.png represents the icon.

**To Reproduce**
1. Install MapTool v. 1.8.0-beta.2.
2. Open your system "start menu".
3. Search for MapTool.
4. See error.

**Expected behavior**
The icon should be the RPTools MapTool icon.

**Screenshots**
![maptool icon bug](https://user-images.githubusercontent.com/58573071/92931701-255c9780-f444-11ea-85a6-b1313c5890ac.png)
![maptool icon bug 2](https://user-images.githubusercontent.com/58573071/92931707-27bef180-f444-11ea-9424-f55a5eb64dea.png)

**MapTool Info**
- Version: 1.8.0-beta.2
- Install: New, .deb package

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 19.3 Tricia
(base: Ubuntu 18.04 bionic)

**Comment by JamzTheMan** [comment]
@Phergus this may be a case title issue? Maybe jpackage is looking for maptool.png vs MapTool.png?

**Comment by Phergus** [comment]
Could be.  Seems weird that it somehow gets the OpenJDK icon.

**Comment by Phergus** [comment]
That's probably what it is.  jpackage instructions have this for linux:
`imageOptions += ['--icon', 'package/linux/' + project.name + developerRelease + '.png']`

The project name is, of course, `maptool` but the png file is `MapTool.png`

**Comment by Phergus** [comment]
Shouldn't this have affected Mac users as well?

**Comment by kayila** [comment]
Hey, folks... Mind if I take this one? I messed with this stuff a while to fix this issue, and I'm curious what caused it to break again... I definitely had it working with Archlinux, and I can throw together a Mint system to test.

**Comment by kayila** [comment]
So, interestingly, this issue is from before I fixed it in https://github.com/RPTools/maptool/pull/2238 I'll verify that the PR fixed it later today and maybe we can close this.

**Comment by Phergus** [comment]
Fine by me.  We can either fix the case in the build.gradle file or rename the icon to match the project name.

**Comment by kayila** [comment]
Good news! This is indeed fixed with the latest build of Maptool!

![image](https://user-images.githubusercontent.com/925235/100301548-5b4ee980-2f66-11eb-9e16-0f6d1dbc92ee.png)

This was fixed by #2238
