### ISSUE TITLE
onCampaignLoad no longer suppresses output

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2223]
**Describe the bug**
Since #2201, the `onCampaignLoad` event is no longer suppressing output when executed automatically.

**To Reproduce**
1. Create `onCampaignLoad` macro that does not hide its own output
2. Save & reload campaign
3. Observe output in chat

**Expected behavior**
Prior versions of MT suppressed output from automatically-executing `onCampaignLoad`

**MapTool Info**
- Version: 1.8beta-2

**Additional context**
When refactoring to unify the macro event infrastructure, I failed to account for this behavior.  I'll fix it :)

**Comment by Phergus** [comment]
Tested.  Output from `onCampaignLoad` macros no longer sent to chat during campaign load.  Output is still seen when manually running macros as it was before.
