### ISSUE TITLE
xpath erorrs with values that contain commas

### ISSUE THREAD

**Issue by dbirchbauer** [RPTools/maptool#2228]
Looks like I've just found a possible glitch with XPath. when it returns a stringlist its not properly escaping values with , which means that when you then iterate over it, "Restoration, Lesser" becomes "Restoration", and "Lesser".

**Comment by Phergus** [comment]
Use the provided templates.

**Comment by dbirchbauer** [comment]
Which are provided where? there isn't any documentation associated with that either http://www.lmwcs.com/rptools/wiki/herolab.XPath or http://www.lmwcs.com/rptools/wiki/How_to_use_HeroLab_Functions#Using_herolab.XPath
