### ISSUE TITLE
getOverlayNames()

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2230]
**Is your feature request related to a problem? Please describe.**
There is currently no way to obtain the names of all registered overlays. As overlays become more common, overlay management will require the ability to obtain the names of currently registered overlays.

**Describe the solution you'd like**
a function that will return a list/array of the overlays currently registered
getOverlayNames(["json"])

**Describe alternatives you've considered**
maintaining a list of overlay names in a property

**Comment by Azhrei** [comment]
Perhaps an option to getInfo() instead, since that function already exists?  It could return not just overlays, but all frames as well, with a flag indicating the status of the panel (open/closed/pinned), its initialization string, and it’s current settings (width/height).  It would be excellent if the content of the frame/overlay could be retrieved, too (for debugging/logging purposes).

**Comment by bubblobill** [comment]
I like that idea, particularly the inclusion of frames with their status. Any point in adding dialog?

**Comment by Azhrei** [comment]
Since their modal, I don't see much point unless someone else can think of a reason...

**Comment by Phergus** [comment]
Not in the usual sense of the term.  You can have multiple Dialogs open at a time and continue using MT normally.  Because you can drag Dialogs outside of the MT main window it's possible folks could "lose" track of them.

**Comment by Azhrei** [comment]
Lol, shows how much I know about the frame/dialog differences!  Everything I've been doing has been frame5 stuff.  Sounds like you're agreeing with @bubblobill though and saying they should be included...

**Comment by Phergus** [comment]
I think it seems reasonable to include them in with overlay and frames.

**Comment by selquest** [comment]
I added dialogs, frames, and overlays to the `getInfo("client")` output using the existing `getFrameProperties()` (and corresponding) output.  Frame & dialog properties didn't include `visible` or `docked` indicators, so I added those (`docked` only for frames, of course).

Sample `getInfo("client")` output excerpt:
```json
{
  "dialogs": {"Testing":   {
    "width": 390,
    "height": 212,
    "temporary": 0,
    "title": "Testing",
    "visible": 1,
    "value": ""
  }},
  "frames":   {
    "PlayMat - Hammer Bot":     {
      "width": 839,
      "height": 382,
      "temporary": 0,
      "title": "PlayMat - Hammer Bot",
      "visible": 1,
      "docked": 1,
      "value": ""
    },
    "Option Cards - Hammer Bot":     {
      "width": 800,
      "height": 600,
      "temporary": 0,
      "title": "Option Cards - Hammer Bot",
      "visible": 1,
      "docked": 0,
      "value": ""
    }
  },
  "overlays":   {
    "TimingReference":     {
      "name": "TimingReference",
      "zorder": 0,
      "visible": 0
    },
    "partyOverlay":     {
      "name": "partyOverlay",
      "zorder": 0,
      "visible": 1
    }
  },
}
```

Is there any other information it makes sense to include for any of these?

**Comment by bubblobill** [comment]
position? Handy for identifying when it is off-screen.
Frame: autohide/pinned; default position/size/etc.; last position/size/etc.; scrollreset 
Dialog: input; temporary; noframe; closebutton; scrollreset; passed size; user size;

Don't know if they have unique Ids, if they do, throw that in for potential future use.
In an ideal future world, I want to be able to change the content of an overlay with controls in a frame, so any information that can be returned, or that could be used in future functionality would be best built into it now.

**Comment by Phergus** [comment]
The window position information is going to be specific to the clients display configuration (number of monitors and resolutions) which you won't have.  So that's a new issue for adding more general client information like number of screens and resolution and which one MT is running on.  Also need to know if a client is running full-screen or not.

**Comment by selquest** [comment]
I added some more properties to the getProperties methods for frames and dialogs, and by extension to `getInfo("client")`.

At this point all properties (except for *scrollReset*, which is a behavior and not a property) that can be specified when creating them are included in the getProperties output.  HTML5 indicator is also included.
 
> Don't know if they have unique Ids, if they do, throw that in for potential future use.

The names are unique IDs for dialogs/frames/overlays.  Attempting to create another one with the same name (and type) overwrites the existing one.

**Comment by Phergus** [comment]
Tested.  Various properties of Dialog, Dialog5, Frame, & Frame5 windows plus Overlays now show in the output of `getInfo("client")`.
