### ISSUE TITLE
MBL Macro Functions: drawMBL, eraseMBL, getMBL

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#2234]
**Is your feature request related to a problem? Please describe.**
I want to be able to erase or draw MBL with macros, like I can with VBL.

**Describe the solution you'd like**
I want the same macro functionality that VBL enjoys with `drawVBL()`, `eraseVBL()`, and `getVBL()`.

**Describe alternatives you've considered**
- Using a movement-blocking token and moving that around programmatically. Limited because it blocks a whole cell, but it works OK.
- Letting tokens contain MBL like they do VBL would effectively solve the issue and would be nice for other reasons (whole maps with VBL/MBL entirely contained on a token! Would be great for hot-swapping levels of a building!), but doesn't bring MBL to macro parity with VBL topology.
- Adding a flag to the existing functions to get/draw/erase VBL, MBL, or VBL+MBL ("v", "m", "mv"/"vm"). Not pretty and doesn't make for great nomenclature, but might be efficient.
- A generic function might be a good alternative:
   - `get/erase/drawTopology(type, shapesList* ...)`, or 
   - `get/erase/drawBL(*type, shapesList* ...)`

**Additional context**
There may be a way to change MBL programatically, but I don't know what it is.

**Comment by kwvanderlinde** [comment]
I was experiment with adding these for the sake of my wall imports, and I stumbled on an interesting tidbit while wading through the code: `drawVBL()` / `eraseVBL()` do not necessarily affect the VBL, but may also affect the MBL depending on the current topology mode. It depends on the state of the toolbar button, so these functions act as if a user were doing the drawing. This obviously doesn't solve the particular feature request, but it does mean that we technically already have MBL drawing as part of the VBL functions.

(btw, this is my simple test drawing that makes it really obvious. Try changing between VBL/MBL/VBL+MBL and running this command: `[h: drawVBL('[{"shape": "rectangle", "x": 0, "y": 0, "w": 1000, "h": 1000, "fill": 1}]')]`)

**Comment by Azhrei** [comment]
Wow, if that's really what's happening, this needs to be fixed!  The script functions cannot be operating differently based on a UI button state!  I suppose that means creating appropriately named functions for manipulating MBL, too...

**Comment by melek** [comment]
Alternatively, with functions to get/set the state of that tri-state button we could do something like this:
```
[vCurrentMode = getBLMode()]
[setBLMode("M")]
[drawVBL( ... )]
[setBLMode(vCurrentMode)]
```

Not the 'right' way perhaps, but maybe it could work something like this under the hood for VBL (and new MBL) functions for a quick solution.

**Comment by kwvanderlinde** [comment]
I have a working prototype of `drawMBL()`, `eraseMBL()` and `getMBL()`. The implementation is shared between VBL and MBL, and can also handle both at the same time. That means it could be replaced with a more generic `drawTopology()` etc., without much in the way of code changes.

I can clean it up and make sure it follows the guidelines if you'd like to see a PR for it.

**Comment by Phergus** [comment]
Tested.  All three functions working the same as their VBL counterparts.
