### ISSUE TITLE
Too much network debugging information is being output with new build when run from gradle

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2244]
**Describe the bug**
There is too much network debugging information being output when run from gradle, the gradle run task should be changed so that it does not do this by default (it can get quite spammy...).

**To Reproduce**
gradlew run

**MapTool Info**
- Version: 1.8.x
- Install: Run from gradle only

**Desktop (please complete the following information):**
 - OS: Any

**Comment by Phergus** [comment]
Tested.  Now had less network debugging info.
