### ISSUE TITLE
Javascript continues to run on closed Overlay

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2249]
**Describe the bug**
When an overlay is closed the javascript continues to run. Running the overlay again does not replace the prior javascipt resulting in multiple sets of coding running to no purpose.

**To Reproduce**
Run this macro [meteor.mtmacro.txt](https://github.com/RPTools/maptool/files/5308969/meteor.mtmacro.txt) and you get a meteor storm. Each frame writes the frame number to chat(console.log).

Close the overlay 
`[closeOverlay("Weather")]`

The frame numbers continue in chat.
Rinse and repeat.
Watch your MapTool choke.

Haven't tested with Frame5/Dialog5.

**Expected behavior**
Javascript should stop execution on closing the Overlay

**Screenshots**

**MapTool Info**
- Version: 1.7.0

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Workaround found: before closing the overlay, write a blank script to the overlay.
```
[h:name = "Weather"]
[overlay(name, "zorder=-1"): {
<script>
[r:'


']
</script>
}]

[h:closeOverlay(name)]
```

**Comment by kwvanderlinde** [comment]
This seems straightforward to fix. I can take this on.

**Comment by Phergus** [comment]
Tested.  Closing overlay terminates running JS.
