### ISSUE TITLE
Change error message when attempting to load map as campaign

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#225]
The error message is the text from the exception (an inability to cast the PersistentMap type to the campaign type) and it would be better to just tell the user to import the map instead.  Of course, if the Open Campaign dialog displayed **.map** files, that’s the first thing to correct...

**Comment by Phergus** [comment]
By default the silly Open Campaign dialog views all file types and will attempt to open all file types.  IT has a filter for .cmpgn files but it isn't set as the default.

**Comment by Merudo** [comment]
PR #605 set .cmpgn filter as default, and change error message.

**Comment by Phergus** [comment]
Tested.  Campaign filter is default.  Attempting to load other MT file types no longer throws exception.
