### ISSUE TITLE
HTML5 data: URIs not working in Frame5, Dialog5, or Overlay

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2256]
**Describe the bug**
The [data: URI](https://en.wikipedia.org/wiki/Data_URI_scheme) allows embedding the data for an element rather than a link to the data.

Using code like 
`[h: imgSrc='"data:image/png;base64,'+picCode+'"']`

I should be able to use images like this:
**CSS** `{background-image:url('+imgSrc+');}`
**HTML** `<img id="img" src='+imgSrc+' alt="I see nothing" width="500px" height="500px">`
**JS** `document.getElementById("img").src="'+imgSrc+'";`

**To Reproduce**
- Take this file [test2.html.txt](https://github.com/RPTools/maptool/files/5327194/test2.html.txt)
- Copy file contents
- Rename to .html
- Test by opening in browser.
- Paste into HTML5 macro function, e.g.
`[dialog5("Weather"): {
    [r: strformat('
      
    ')]
}]`
- Run macro.
- Look at the ugly.

**Expected behavior**
Images should be displayed as they would in a browser.

**Screenshots**
Attached HTML used in dialog5()
![image](https://user-images.githubusercontent.com/45483160/95077169-9b9fa180-0745-11eb-8542-443ef40a9e5c.png)
Attached HTML viewed in browser
![image](https://user-images.githubusercontent.com/45483160/95077330-e6211e00-0745-11eb-8fa3-d00cd42c23c1.png)

**MapTool Info**
- Version: 1.7.0

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by dat-adi** [comment]
Hey!
I'd like to look into this issue, but, I don't know where to start.
Which file should I look into in order to resolve this?

**Comment by cwisniew** [comment]
@dat-adi 

Check [HTMLWebViewManager.java](https://github.com/RPTools/maptool/blob/200bf60dc1db1855a6fc6e99ea6996bda2df267c/src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java#L162)

The Content-Security-Policy determines what can be loaded and probably needs to be modified to allow data:

**Comment by bubblobill** [comment]
Can we assume that MT is an unlikely vector for the security concerns?

quote:The data URI can be utilized to construct attack pages that attempt to obtain usernames and passwords from unsuspecting web users. It can also be used to get around cross-site scripting (XSS) restrictions, embedding the attack payload fully inside the address bar, and hosted via URL shortening services rather than needing a full website that is controlled by a third party.[8] As a result, some browsers now block webpages from navigating to data URIs.[9]

**Comment by dat-adi** [comment]
@cwisniew thanks for pointing that out.
I'll try looking into it.
Also, @bubblobill I didn't quite get that, but, what I do understand is that you mean that the data:uri component is vulnerable?

**Comment by dat-adi** [comment]
I'm not able to get my javafx to work on my system unfortunately, but I want to test something out T_T
In the [HTMLWebViewManager.java](https://github.com/RPTools/maptool/blob/200bf60dc1db1855a6fc6e99ea6996bda2df267c/src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java#L162), adding the below line allowing the image should fix it?
```java
+ " img-src 'self' data: ;"
```
I'd test it out, but, like I've mentioned earlier, the JavaFX module is proving to be painful to deal with.

**Comment by Phergus** [comment]
You should review the guide for development.  https://github.com/RPTools/maptool/wiki/Contributor-Setup-Instructions-For-MapTool

All PRs and development are done against the develop branch.

See https://github.com/RPTools/maptool/blob/main/doc/Code_Style_and_Guidelines.md also

**Comment by dat-adi** [comment]
Thank you for your response.
I'll attempt to test it out again.

**Comment by dat-adi** [comment]
Closing PR.

**Comment by Phergus** [comment]
With changes the example given produces this:
![image](https://user-images.githubusercontent.com/34379254/95659520-de170480-0ade-11eb-8690-4ccd12239ca8.png)

Appears to be working as expected.

**Comment by Irarara** [comment]
This change seems to have made it so that local images (via asset://) won't display in form5/dialog5/overlay, at least on my end. Can anyone else confirm?

**Comment by Phergus** [comment]
Confirmed.

@dat-adi you want to look at this?

**Comment by dat-adi** [comment]
I'll look into it.
However, I haven't worked with that area. 
How do you display local images exactly?
Did the local images work before this development?

**Comment by Phergus** [comment]
You can link to images in HTML frames/dialogs/overlays using syntax like this:
```
[overlay("Image"):{
	<img src=[r: getImage('c7')]>
}]
```
Works in 1.8.0-beta.2 but not in current code.  Broken for `frame5()`, `dialog5()` and `overlay()` but working for older `frame()` and `dialog()`.

**Comment by Irarara** [comment]
Adding `asset:` to the img-src CSP directive might fix it? (ie `img-src * asset: ;`)

**Comment by Phergus** [comment]
That would do it.  Go ahead and put in a PR with the fix.

**Comment by dat-adi** [comment]
Glad to see that the issue has been sorted, will @Irarara be taking over now?

**Comment by Irarara** [comment]
@dat-adi Oh, I wasn't really intending to, but I don't mind if you'd prefer. I was just offering that as a suggestion. The issue made me curious, so I looked into it a little, and that seemed like it might be the right direction, but I haven't really done any thorough testing or anything.

**Comment by Phergus** [comment]
@dat-adi @Irarara Still waiting on a PR to fix this.

**Comment by dat-adi** [comment]
Oh, my bad. I'll work on it.

**Comment by dat-adi** [comment]
@Phergus I've looked into it, but, the assets don't seem to load up even after the addition of the `asset:`.
I'm not sure as to whether I'm running the right command, can you direct me to working with frame()/overlay()?

**Comment by Phergus** [comment]
Overlays are described here:  https://wiki.rptools.info/index.php/overlay_(roll_option)
frame5() is documented here: https://wiki.rptools.info/index.php/frame5_(roll_option)

This code will work for both (just change *overlay* to *frame5*).
```
[overlay("Image"):{
	<img src=[r: getImage('someTokenOnTheMap')]>
}]
```

**Comment by Phergus** [comment]
@dat-adi were you going to finish this?

**Comment by dat-adi** [comment]
I apologize, I will not be working on this.

**Comment by Phergus** [comment]
@Irarara  would you test and confirm that the change restored functionality re: local images (via asset://) won't display in form5/dialog5/overlay?

**Comment by Irarara** [comment]
@Phergus Everything seems to be working now. 👍

That said, one thing I'm actually noticing is since this change (and I mean, since the change was made to allow data: URIs, not since fixing use of asset:) is that you can now use images from external sources where you couldn't before. I got the impression that blocking (most) external resources was by design, so does this need fixing too?

**Comment by Phergus** [comment]
Hmm.  Maybe that change for allowing data should have just been `" img-src data: asset: ; "` instead.

Whether or not to allow images from any source is probably a discussion to be revisited now.  @cwisniew @Azhrei

**Comment by Irarara** [comment]
> Hmm. Maybe that change for allowing data should have just been `" img-src data: asset: ; "` instead.

Yeah. Actually, I swear I tried that before and it wasn't working for some reason, but it seems to do the trick. 💦

**Comment by Azhrei** [comment]
> Whether or not to allow images from any source is probably a discussion to be revisited now.

Craig's attitude has always been that campaign files should be self-contained as much as possible.  I tend to agree.

We do have access to external resources now through the whitelisted CDNs and the REST functions, and many frameworks are supporting the retrieval of data dynamically for creating tokens and such, so it's clear that the user community wants to be able to access that data.  The idea of requiring users to build their own MapTool binary with additional CDNs is not practical.

Notebooks will not assuage this desire either, as the underlying goal is access to dynamic data.

I suppose as long as it's clear that such resources are NOT saved with the campaign, maybe an argument could be made.  Sort of a "You do this at your own risk" disclaimer.  And maybe saving the campaign should produce a warning that external resources will not be saved?  We could easily track whether any such resources were used and set a flag...  Maybe a discussion on Discord is warranted?

**Comment by Phergus** [comment]
Short term I think changing it to only allow `data:` and `asset:` sources is probably for the best until we can have further discussion about this.  I also am strongly in favor of campaigns being self-contained.

**Comment by bubblobill** [comment]
Adding `data:` constitutes no real change in policy/paradigm and is the easiest choice provided you accept the caveat over security risks as mentioned in the 4th post.
What are the hazards of permitting external access? If you limit it to images you will only get people crying out for access to CSS, the font I want, JS libraries, etc. Could I use external access to run something malicious with potential access to the local file system or creating an evil bot-net?

**Comment by Azhrei** [comment]
> What are the hazards of permitting external access?

Primarily denial-of-service attacks:  excessive use of network bandwidth, excessive use of persistent storage (the assetcache, for example), macros that open an excessive number of panels, and infinite macro loops (such as a macro invoking itself).  There are probably more, but those come to mind immediately.

While allowing static images to be loaded _shouldn't_ be an issue, as JS and MTscript become more intertwined, there are likely to be cracks in the control that MapTool can take over content in an effort to mitigate the above attacks.

**Comment by Phergus** [comment]
This will most likely be changed to only allow `data:` and `asset:` sources for 1.8 release.  Whether with that change or with current code, the original issue is resolved.
