### ISSUE TITLE
Crash with "malloc(): corrupted top size" error on start on ubuntu

### ISSUE THREAD

**Issue by dschwilk** [RPTools/maptool#2259]
**Describe the bug**

Linux executable installed from 1.7.0 deb file results in:

```
/opt/MapTool/MapTool
14:10:54.560 (MapTool.java:1550) [main] INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
14:10:54.663 (MapTool.java:1551) [main] INFO  net.rptools.maptool.client.MapTool - **                                                                            **
14:10:54.665 (MapTool.java:1552) [main] INFO  net.rptools.maptool.client.MapTool - **                              MapTool Started!                              **
14:10:54.665 (MapTool.java:1553) [main] INFO  net.rptools.maptool.client.MapTool - **                                                                            **
14:10:54.665 (MapTool.java:1554) [main] INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
14:10:54.666 (MapTool.java:1555) [main] INFO  net.rptools.maptool.client.MapTool - AppHome System Property: /home/schwilk/.maptool-rptools/logs
14:10:54.666 (MapTool.java:1556) [main] INFO  net.rptools.maptool.client.MapTool - Logging to: /home/schwilk/.maptool-rptools/logs/maptool.log
14:10:54.666 (MapTool.java:1563) [main] INFO  net.rptools.maptool.client.MapTool - getting MapTool version from manifest: 1.7.0
14:10:54.667 (MapTool.java:1568) [main] INFO  net.rptools.maptool.client.MapTool - getting MapTool vendor from manifest:  rptools
14:10:54.732 (MapTool.java:1638) [main] INFO  net.rptools.maptool.client.MapTool - MapTool version: 1.7.0
14:10:54.733 (MapTool.java:1641) [main] INFO  net.rptools.maptool.client.MapTool - MapTool vendor: rptools
malloc(): corrupted top size
Aborted (core dumped)
```

**To Reproduce**

See above

**Expected behavior**

Program should open the main maptool window

**Screenshots**
NA

**MapTool Info**
- Version: 1.7.0
- Install: New via deb

**Desktop (please complete the following information):**
 - OS: [Kubuntu]
 - Version [20.04]

**Additional context**

`/opt/MapTool/MapTool --reset` has no effect, nor does increasing memory settings in `~/.local/net.rptools.maptool.client/packager/jvmuserargs.cfg`

**Comment by Azhrei** [comment]
Is this a VM or bare metal?  How much physical memory is installed on this system?  Is this system fully up to date?

That error is coming from the C code embedded in the Java runtime, not from any Java code.  This implies a system-level issue.  A quick Google search hasn't turned up any particular Kubuntu 20.04 bugs in regards to memory issues.  I may install a Kubuntu VM for testing, but I'll need more machine specifics from your machine (physical RAM, number of cpus, type of graphics card).

**Comment by dschwilk** [comment]
Weird. No VM, just kubuntu up to date.   It is intermittent problem I think. This first happened on friday right before a game and I did a reinstall and that fixed it (but probably had nothing to do with the reinstall since this is not in maptool itself?). Then it happened again today when I tried to open maptool (first time since Friday).  It did not work from my shortcut nor from a terminal as shown. I tried a new terminal now and it opened again so I'm confused.

I'm using openjdk 11:

```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

**Comment by dschwilk** [comment]
Don't make this any priority as now I can't reliably reproduce the issue!  Sorry.

**Comment by Azhrei** [comment]
Yep, I just tried it on a fresh install (of the OS and the .deb package) and I can't recreate it either.  I'm closing this, but if it comes back you can file another issue.

**Comment by kwvanderlinde** [comment]
I have exactly the same crash with MapTool 1.7 installed via deb on Linux Mint 20 (also based on Ubuntu 20.04). It's really inconsistent whether or not it shows up. Some days I need to run MapTool 4 or 5 times before it starts. Other days it works every time.

Whatever is going on it happens really early during the application's lifetime, before the splash screen even shows up. I have never seen such a crash after the splash screen shows up, no matter how long I run MapTool for.

If you'd like me to open another issue I can, but since this is literally the same symptom I figured I would chime in here.

**Comment by dschwilk** [comment]
I still have this as well. The symptoms are exactly the same as those described by @kwvanderlinde. I just keep trying until it works. Once opened, it works fine every time. Should we open another issue?

**Comment by Azhrei** [comment]
I did some more searching; the error appears to be in the C code in the Java runtime.  There's nothing we can do to fix this.  I'm going to leave this one closed and we'll see if the bug is still in the Java 14 runtime that MT 1.8-beta is using (if you can test the new beta build by installing it and running it, that would be helpful; pick a different directory to install it into so it doesn't conflict with your 1.7 installation).

**Comment by kwvanderlinde** [comment]
Sounds like a plan. I should really be testing out 1.8 anyways!

**Comment by kwvanderlinde** [comment]
It's been a few weeks now of using the 1.8 beta and I have not once encountered this issue again. Looks like it may be a thing of the past after all!
