### ISSUE TITLE
Windows jumping around

### ISSUE THREAD

**Issue by Zag24** [RPTools/maptool#2265]
**Describe the bug**
After about 15 minutes of use, the Visible Windows are jumping around crazily.  This includes menu drop down as well as all the visible views.  This is single user, just editing maps, not connected.

**To Reproduce**
I've only seen this after loading a campaign using File, Recent Campaigns, and selecting.  However, since that's my most common thing I do, it might not be relevant.  Basically, as I'm editing the map, after about 15 minutes or so the windows just start jumping around.  

**Expected behavior**
Not jumping around crazily.  :-)

**Screenshots**
![MapTool bug](https://user-images.githubusercontent.com/8311463/96348639-e5ef1f80-106f-11eb-8cee-bf74844971af.png)

**MapTool Info**
- Version: 1.7.0.  (I couldn't find a build number.  It was the latest last April or so when I installed it.)
- Install: Upgrade

**Desktop (please complete the following information):**
OS Name	Microsoft Windows 10 Home
Version	10.0.18363 Build 18363

**Gather Debug Information Output**
==== MapTool Information ====
MapTool Version: 1.7.0
MapTool Home...: C:\Users\zag\.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 308 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\Program Files\MapTool\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
PATH...........: C:\Program Files\MapTool\app;C:\Program Files\MapTool
Number of Procs: 16

==== User Information ====
User Name: zag
User Home: C:\Users\zag
User Dir.: C:\Program Files\MapTool\app

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Killer E2600 Gigabit Ethernet Controller
Interface Name: eth3
Address...: 192.168.1.150
Address...: fe80:0:0:0:399c:fdc:6c56:729e%eth3

Host Address...: 192.168.1.150
Default Gateway: 192.168.1.1

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 2560x1440(32)

==== Internet Gateway Devices ====
Device Name.: ZagNet
Model Name..: WRT1200AC
Manufacturer: Linksys, LLC
Model Number: WRT1200AC
Model Desc..: Simultaneous Dual-Band Wireless-AC Gigabit Router
Firmware....: Linux/3.10.39, UPnP/1.0, Portable SDK for UPnP devices/1.6.19
External IP.: 66.68.63.225

**Comment by Azhrei** [comment]
This is probably due to interactions with the Windows video driver.  Try turning off various combinations of Direct3D and OpenGL in Preferences and see if the issue goes away.  If it does, please report back and we'll close this issue.  Thanks.

**Comment by Zag24** [comment]
It checked 'Disable Direct3d Pipeline' and 'Initialize AWT before JavaFX' and I haven't seen the problem past the point that I would have expected to.  I assume it was the first one.  Thanks for the note and the product in general!

**Comment by Phergus** [comment]
@Zag24 the Initialize AWT... option only applies to MacOS so you can turn uncheck it or leave it.

Closing as resolved.
