### ISSUE TITLE
HTML5/Javascript Canvas - WebGL compatibility

### ISSUE THREAD

**Issue by Devviedehm** [RPTools/maptool#2269]
**Is your feature request related to a problem? Please describe.**
Canvas 2D context works, but it doesn't allow for 3D (WebGL) context.

**Describe the solution you'd like**
WebGL natively available in MapTool when using frame5, dialog5, etc. (HTML5 components with a Canvas on them).

**Describe alternatives you've considered**
After Azhrei's reply, I've looked at a few things.
There's an experimental (maybe abandoned?) repository for VFXWebKit which I think achieves this by "sharing memory" with a child process that does render WebGL, from what I understand.
The successor to VFXWebKit seems to be NativeFX, which should have performance improvements, which is an integration made for "JavaFX 13 and beyond".
One other option I read about would be to integrate Chromium as a web renderer, but that would probably lead to many problems with high memory usage.
GwtGL and LIBGDX seem to also offer support for WebGL inside Java.

**Additional context**
Playing around with the relatively recent HTML5 things in MapTool.
It's working pretty well, and the 2D canvas works, but there doesn't seem to be any support for WebGL as of yet (and I'm still getting used to the peculiar way MapTool likes to handle what I'm writing on it... Like having curly braces after an 'if' inside a script tag, or being unable to put CSS directly due to the colon symbol).

I understand this wouldn't run well on older computers or ones without a GPU, but for groups that are using MapTool and have those capabilities I believe this would enable an extra layer of polish and customizability.
I had in mind implementing a 3D Dice Roll overlay on top of the map view for the connected players in my campaign, for example.

However I understand if this is entirely out of the current scope of the project, or if it would require too much rewriting of the currently used HTML5 components to work. Still, hadn't seen anyone mention it yet, so I wanted to add the suggestion here. Sorry if this isn't the appropriate place or if I'm writing this all wrong as I rarely contribute to things online anymore.
(edited to try to fit the feature request template)

**Comment by Azhrei** [comment]
(There's a template to use when making bug reports or feature requests.  Please follow the templates. ;) )

MapTool uses the current JavaFX library so whatever it supports is what MapTool supports. :)

There are a few things that are not supported by the WebKit software that is part of JavaFX that MapTool is built against (CSS perspective is an example, as well as some SVG controls), so when the JavaFX libraries include that support, so will MapTool.  There's not much else we can do about it, unfortunately.

**Comment by Devviedehm** [comment]
Ah, I'm sorry, I'll edit the comment to fit the template. ^^;

Also looked a bit into what WebGL support can be implemented in JavaFX - seems like NativeFX is a good starting point to figure out if it's doable, but it seems like it would be a lot of work for just a bit of extra functionality, so I'd consider my feature request to be very low priority. 😅

**Comment by bubblobill** [comment]
If you dig _deep_ into the web, there are JS libraries for rendering 3d objects on 2d canvas.

**Comment by Azhrei** [comment]
List of options (but read the caveat at the top):  https://gist.github.com/dmnsgn/76878ba6903cf15789b712464875cfdc

**Comment by cwisniew** [comment]
Sadly JavaFX doesn't support WebGL so this is not viable (even trying any of the above/linked options).
I am adding browser-based-client tag, but given I got shouted down on such an options its likely to never happen and just get tagged as wont fix.
