### ISSUE TITLE
CampaignPropertiesDialogTest > importPredefinedButton() FAILED

### ISSUE THREAD

**Issue by irisiflimsi** [RPTools/maptool#2279]
**Describe the bug**
CampaignPropertiesDialogTest > importPredefinedButton() FAILED
    org.opentest4j.AssertionFailedError at CampaignPropertiesDialogTest.java:33

**To Reproduce**
1. Use german i18n environment
2. ./gradlew build
4. See error, build failed

**Expected behavior**
Build succeeds

**MapTool Info**
- Version: develop branch current

**Comment by irisiflimsi** [comment]
Pull request https://github.com/RPTools/maptool/pull/2281

**Comment by Phergus** [comment]
No change to build under EN-US. Presumed working now under DE.
