### ISSUE TITLE
Immediate improvement of readme.md

### ISSUE THREAD

**Issue by irisiflimsi** [RPTools/maptool#2280]
The **readme.md** should contain a reference to the wiki. This may legitimately be considered a feature request, but let's reserve that for a more thorough improvement. At this point, important information is only in the wiki. Close this bug, once a reference is in the develop and main branch.

**Comment by Phergus** [comment]
@irisiflimsi Don't close issues.

**Comment by Phergus** [comment]
Change made to readme.md file.
