### ISSUE TITLE
Add SVG support

### ISSUE THREAD

**Issue by irisiflimsi** [RPTools/maptool#2283]
**Is your feature request related to a problem? Please describe.**
We should be able to use SVGs as button images. The existing images (e.g. on the ribbon) do not scale and are hard to extend.

**Describe the solution you'd like**
Maptool should support more image formats, in particular SVG.
https://github.com/haraldk/TwelveMonkeys provides even more formats, although most are legacy.

**Describe alternatives you've considered**

- We could stick with the raster image approach.
- We could use apache batik directly and write our own SPI.

**Additional context**
This discussion was active several times. This issue will give it a footprint in Github.

**Comment by irisiflimsi** [comment]
Current support (from the pull request) is rendering in native scale as resolution, i.e. units = pixels. That is sufficient for almost anything.

Getting SVG to correctly scale in maptool would require a complete remake of the maptool core, rendering (non-icon size) SVGs is performance heavy and we haven't addressed the links (and other foreign XML-namespaces) yet.

**Comment by Phergus** [comment]
SVG files can be dropped onto maps but cannot be accessed through Resource Library.  Images come in at the height/width called out in the SVG file.

Implementation incomplete.

**Comment by Phergus** [comment]
Tested:  SVG images now supported via Resource Library.

**Note:**  when brought into MapTool this way they come in as bit-mapped images at the size specified in the SVG file.

*Example:*
```
<svg xmlns="http://www.w3.org/2000/svg" width="255" height="240" viewBox="0 0 51 48">
<title>Star</title>
<path fill="#00f" stroke="#000" d="m25,1 6,17h18l-14,11 5,17-15-10-15,10 5-17-14-11h18z"/>
</svg>
```
When dragged out of the Resource Library or via drag-n-drop from the desktop/file explorer the image will be 255x240 pixels and any resizing is done on that fixed image.
