### ISSUE TITLE
Export Dialog NPE

### ISSUE THREAD

**Issue by irisiflimsi** [RPTools/maptool#2287]
**Describe the bug**
The current develop branch has a NPE when exporting a screenshot (including Export as...).

**To Reproduce**
1. Start maptool 
2. Menu export screenshot
4. See NPE error box

**Expected behavior**
Choices GUI box appears

**MapTool Info**
- Version: develop latest (as of today)

**Additional context**
It seems the order of get... and setExportDialog in AppActions.java was changed. I'm not really sure, but without an instance variable to back this behavior the code fails. I'd probably just insert that instance variable, but I am not sure about the original intentions of not having one..

**Comment by Phergus** [comment]
Working in 1.7.0 and broken in 1.8.0-beta.2.   Both Export Screenshot and Export Screenshot As... are broken.

**Comment by Phergus** [comment]
The ExportDialog changes were made in #2148 .  Need to review those changes to see why they aren't working.

**Comment by ebudai** [comment]
This is fixed in pull request [2293](https://github.com/RPTools/maptool/pull/2293)
