### ISSUE TITLE
Non alphanumeric characters in the key of a String Property with just one element cause the getStrProp not to find the element

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#2288]
**Describe the bug**
Non alphanumeric characters in the key of a String Property with just one element cause the getStrProp not to find the element

**To Reproduce**
```
[r:getStrProp("a 1=1", "a 1", 0)]
0
```

but 

```
[r:getStrProp("a 1=1; sentinel=0", "a 1", 0)]
1
```

**Expected behavior**
The key should be found.

**Screenshots**
N/A

**MapTool Info**
- Version: 1.7.0
- Install: Upgrade

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
N/A

**Comment by Phergus** [comment]
Interesting.  Works if the space is replaced by `_` or `.` but non of the other punctuation symbols work that I tried.  As this is a regex search that kind of makes sense as many of them have meaning in regex. 

While the space works if the source string has more than one property the use of other punctuation symbols still fails.

**Comment by emmebi** [comment]
Found what seems to be the problem; line 96 in StrPropFunctions:

```

**Comment by Phergus** [comment]
Tested. `getStrProp()` working as expected when keys have spaces in them.
