### ISSUE TITLE
Impersonate not working as documented

### ISSUE THREAD

**Issue by Netskeh** [RPTools/maptool#2290]
**Describe the bug**
I was trying to have a GM macro call a lib macro to change a few settings on it. To be clear on what has happened I would like to have that token picture in the chat - that's where impersonate() comes into play. I found the documentation to it but I it is not behaving as written.

**To Reproduce**
1. Go to https://wiki.rptools.info/index.php/impersonate
2. Copy example into one of your macros
3. Run macro
4. See Wolf making all the noise,

**Screenshot**
(yes the other 3 Tokens exist)
![maptool_impersonate](https://user-images.githubusercontent.com/777136/97801071-613cfd80-1c3a-11eb-9e38-4ae37f2d6dfc.PNG)

**Expected behavior**
For me, the documented behaviour would be ideal - starting where I have impersonate() I would like to have that chat picture until I change it. The way it is currently working is neither logical nor documented. Having impersonate("") at the very end should also only remove impersonation from the caller, not have an effect on the whole previous macro output.

**MapTool Info**
- MapTool Version: 1.7.0
- Install: Upgrade from 1.5.14 (I think)

**Desktop (please complete the following information):**
 - OS: Windows 64bit
 - Version 10

**Additional context**
==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: G:\MapTool\runtime
Java Version: 10.0.1

**Comment by Phergus** [comment]
This is because the output of a macro happens after execution for the entire macro is complete. At that time the current impersonation state (i.e. the last impersonate() call made) is what is used to format the output.  The output has a single context that applies to all of the output.

The normal workaround for this is to use `broadcast()` and format your output as desired.

**Comment by Netskeh** [comment]
ok thanks, that's good enough for me as I was unaware of that call. 

Yet the documentation is still wrong compared to the behaviour. Either one should be updated imho.

**Comment by Phergus** [comment]
I've updated the documentation to hopefully make it a bit clearer.

Just FYI, doing this in a macro does produce the expected output:
```
/im Hero :Hi!
/im Elf :Hi!
/im Mystic :Hi!
/im Wolf :Burp!
```
![image](https://user-images.githubusercontent.com/34379254/97906261-96ac1e80-1d00-11eb-9227-0cb003d5d8b9.png)

**Comment by Netskeh** [comment]
ok thanks.

Regarding the /im command, that is then a somewhat unexpected behaviour to me. I would expect /im & impersonate() to have a similar functionality, which they do, yet still differ ;)
Can /im also work with a variable in a macro, such as a token id?

**Comment by Phergus** [comment]
> Can /im also work with a variable in a macro, such as a token id?
Not as far as I know.

The slash commands are actually chat commands and using them in macros can lead to other unexpected behaviors.
