### ISSUE TITLE
Multiple types of vision not working

### ISSUE THREAD

**Issue by flynncrosby** [RPTools/maptool#2307]
**Describe the bug**
I am trying to give 2 shapes overlapping on the same sight type (circle and cone)

**To Reproduce**
Edit a sight type in Campaign properties to have 2 shapes, then hit okay, only 1 shape gets used the other is erased from the line

**Expected behavior**
for 1 sight type to have 2 shapes overlapping

**Screenshots**

**MapTool Info**
- Version: 1.8
- Install: New

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - Version [10, 18.04]

**Additional context**
From MapTool, paste info from menu Help -> Gather Debug Information...
You can also attach files (drag and drop here) such as log files or paste a file sharing link.

**Comment by Phergus** [comment]
Sight definitions only support a single shape.

**Comment by Jmr3366** [comment]
Not a bug and should be closed.  If still desired it should be requested via Feature Req.
