### ISSUE TITLE
MT1.8 build 2 bug in movedOverToken

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#2311]
This works in 1.7 and not in 1.8:
[h:padName = "InterPad Boston Globe"]
[h:lastPath	= '[{"x":2100,"y":300},{"x":2200,"y":200},{"x":2200,"y":100}]']
[r:teleporterTriggered = movedOverToken(padName,lastPath)]

error message:
java.lang.ClassCastException: class com.google.gson.JsonArray cannot be cast to class java.lang.String (com.google.gson.JsonArray is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap') error executing expression teleporterTriggered = movedOverToken(padName,lastPath).
Error trace : chat

you'll need a ínterPad Boston Globe' on the map and another token that is impersonated to test this. Copy paste into chat to test.

**Comment by Phergus** [comment]
@wolph42 please follow the provided templates for Bugs or Feature Requests.

**Comment by MeloDub** [comment]
I'm working on this.

**Comment by Phergus** [comment]
Tested.  Working with following code:
```
[h:padName = "mine05_50"]
[r:lastPath = getLastPath()]<br>
[r:teleporterTriggered = movedOverToken(padName,lastPath)]
```
