### ISSUE TITLE
Refactor/clean up chat output generation

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2314]
Presently, some of the code for generating the HTML output for chat messages is duplicated across multiple places resulting in each needing to be updated if changes are made. This could be resolved by having everything for generating the final output in one place that other bits of code would call out to. This would help prevent issues like #2177 and make things like #2273 simpler.

This would also be a good opportunity to clean up the output itself a little, using CSS classes where it makes sense. This would make it simpler to tweak things, and I recall it being mentioned that the idea of user editable CSS for the chat has been floated around so this could be a step towards that as well.

To be precise, I propose:
1. Moving code for formatting different types of messages to separate methods (something like `getFormattedSay()`, `getFormattedEmote()`, etc.) and putting them all in a single class (`MessageUtil`? Something else?) The biggest offender is probably Say messages, but I feel like it would probably make sense to include simpler things and stuff that is only used in one place for consistency, and in case that ever changes. (Likely ones include /say, /emote and /emotes, /emit, /ooc, /whisper, /gm, /self, and system messages (connected, disconnected, etc.).)
2. Removing inline styling and tags like `<b>`, `<i>`, etc. and replace them with CSS classes to be used by MessagePanel.

**Comment by Azhrei** [comment]
+1

Refactoring also allows for the addition of unit tests for those new methods, as well as future tweaks regarding formatting (such as an option to use markdown as chat input instead of the more cumbersome HTML).

**Comment by Phergus** [comment]
Tested.  Output from roll display options and chat commands working as expected.
