### ISSUE TITLE
Mouse pointer incorrectly changing to Hand pointer

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#232]
On an empty map, with no objects, the mouse pointer is changing to the Hand symbol when it should stay as an arrow.

Seen in 1.5.0.0 pre-release and  Nerps 1.4.4.0, 1.4.5.4.  Jar versions.
Java 10
Windows 10 x64

How to reproduce:
- Start MapTool pre-release.
- Observe that pointer is changed to Hand while moving pointer over map area.
- Load attached map file.
- Click on Info object and observe that pointer changes back to arrow once pointer is no longer over Info object.
- Move pointer around map but not over Elf token.  Pointer has correct arrow image.
- Move point over Elf token.  Pointer reverts to hand symbol and stays there.

[Map file to show issue.](https://github.com/RPTools/maptool/files/2852120/PointerIssue232_rpmap.zip)

**Comment by JamzTheMan** [comment]
Roger that.

**Comment by Phergus** [comment]
Note it also does this on populated maps and once in a while will go back to the arrow but changes back to that hand after moving near/over tokens/objects.
