### ISSUE TITLE
Players can't view/select owned NPC tokens without 'Individual Views'

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#2321]
**Describe the bug**
This appears fixed in 1.8b2, but the issue exists in the latest stable release (1.7) so I'm filing this report for others with the issue to see so they don't need to report it.

As title states, 1.7 players connected to a server with 'Individual Views' unchecked cannot see/select NPC tokens they own.

**To Reproduce**
Steps to reproduce the behavior from a fresh campaign:
- Ensure map is visible to players
- Set map vision to 'Day' or 'Night'
- Add a token
  - Set type to 'NPC'
  - Check 'Has sight'. I leave set sight to 'Normal' per the default.
  - Check 'Owned by all'
- Start Server, leaving 'Use Individual Views' **Unchecked**
- Connect with second instance of MapTool
- See error; token not visible to player instance on the map or the Map Explorer, and player cannot select the token with the Selection pane buttons.

**Expected behavior**
The player-owned token should be visible to their owners regardless of type.

**Screenshots**
Here is an example where ownership was explicitly provided, but the error occurs either way:
![image](https://user-images.githubusercontent.com/220149/100300338-a78c3080-2f4a-11eb-97f9-1cb788ae5654.png)

**MapTool Info**
- Version: 1.7
- Install: Install alongside many other versions

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This error reportedly does not occur if 'Use Individual Views' is checked.
Having a player owned token nearby can provide vision of the NPC token, but clicking on the NPC token immediately hides the token and all others until it is deselected. 

Here is a .gif of that issue:
![SightIssue2](https://user-images.githubusercontent.com/220149/100300668-5e88ac00-2f4b-11eb-83d4-8ad67e895840.gif)

**Comment by Phergus** [comment]
Tested in 1.8.0 beta.  Issue no longer occurs.

**Comment by melek** [comment]
I duplicated this issue on 1.8b2 and the dev branch by adding a PC token to a map. If a PC token is present, NPC tokens will not appear unless they are in the sight range of the PC token. 

GM View: (No fog, all tokens have vision, 'Individual Views' unchecked):
![image](https://user-images.githubusercontent.com/220149/103234430-84abbe00-48f4-11eb-8e21-7d399791cff0.png)

Player View: (Highlighting PC token view to demonstrate issue)
![image](https://user-images.githubusercontent.com/220149/103234492-ab69f480-48f4-11eb-8189-2afa2cd5c452.png)

Player view if all PC tokens are removed from map:
![image](https://user-images.githubusercontent.com/220149/103234565-dbb19300-48f4-11eb-826a-cd498bd776eb.png)

Sorry to reopen an issue we thought was done with!
