### ISSUE TITLE
Missing i18n string for whisper reply error message

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2325]
**Describe the bug**
The error message given when attempting to use `/reply` (in `WhisperReplyMacro.java`) when you have yet to receive any whispers is lacking an i18n string and is simply hard coded. The string is "You have no one to which to reply.".

Also, the wording seems a bit odd. Something like "You do not have anyone to reply to." might be a bit clearer.

**To Reproduce**
N/A? Should be observable when switching languages though.

**MapTool Info**
Development branch

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Note that under 1.8.5 this was also returning `Player "null" is not connected.`
