### ISSUE TITLE
Trying to display an image in HTML with a bad size parameter causes client to hang

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2334]
**Describe the bug**
The way the size parameter/suffix (the `-##` value attached asset IDs used to scale them when displaying them in HTML) is processed results in the client hanging if the value cannot be parsed as an integer. Additionally, if the parameter is very large the client will also throw an exception and hang (there's no positive constraints on the value).

**To Reproduce**
1. Open a new campaign
2. Drop the Dragon token on the map
3. Enter `<img src="[r:getImage("Dragon")]-foo">` into the chat. The client will hang on an exception.
4. Repeat the above, but enter `<img src="[r:getImage("Dragon")]-100000">` instead. The client will again hang on an exception.

**Expected behavior**
The client handles the bad input without hanging.

**MapTool Info**
- Version: Development branch (1.8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

A thought, it might be easier to simply only allow images to be scaled down this way, rather than having to set an arbitrary constraint (the client already seems to handle dropping images that are excessively large). Is scaling images up something people regularly end up doing? (I didn't even know images _could_ be scaled up that way until mucking around.)

**Comment by Phergus** [comment]
Limiting the size to native image size or less seems reasonable.  Certainly going beyond 2x is of questionable utility.

**Comment by Phergus** [comment]
Tested.  Passing text for image size or integers out of range no longer cause an exception.
