### ISSUE TITLE
Displaying an image in HTML using the cp protocol will cause the client to hang if it points to an invalid resource

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2335]
**Describe the bug**
If the the src attribute in an img tag uses the `cp` protocol and points to an invalid resource the client will hang.

**To Reproduce**
1. Open a new campaign
2. Enter `<img src="cp://foo">` into the chat. The client will hang on an error message.

**Expected behavior**
The client handles the bad input without hanging.

**MapTool Info**
- Version: Development branch (1.8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Tested.  No longer hangs client with invalid resource.
