### ISSUE TITLE
Trusted prefix colors will not show up in client and changing trusted prefix colors doesn't work properly

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2343]
**Describe the bug**
These are really two entirely separate issues, but they warrant being fixed together.
1. The CSS used for the trusted prefix does not in work within Maptoool (Swing does not seem to support the element.class selector, despite documentation not seeming to indicate this!).
2. Only the red component from the color picker is set when changing the "Trusted Prefix Background" and "Trusted Prefix Foreground" settings.

**To Reproduce**
For 1:
1. Create a campaign macro that just outputs some text.
2. Start the server, joining as a player.
3. Click the campaign macro that was created. Observe that you can mouse over your name and see the source of the macro but the trusted prefix colors are not applied.
(Bonus, if you save the chat log, the colors will show up when viewed in a browser).

For 2:
1. Open up preferences.
2. Open the color picker for "Trusted Prefix Background" and go to the RGB tab.
3. Enter 0 for all the RGB values.
4. Confirm out of the dialog and then out of preferences.
5. Open preferences again and go back into the color picker for "Trusted Prefix Background" and check the RGB tab. Only the red value will be 0.
6. Repeat the above with "Trusted Prefix Foreground".

**Expected behavior**
The trusted prefix color should be visible and colors should be properly set.

**MapTool Info**
- Version: Development branch

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Huh.  Is that what those colors are for?   Never paid them any attention.

Are you going to work on this @Irarara ?

**Comment by Irarara** [comment]
Same here, haha. I only really noticed what they're actually supposed to be doing because I've been mucking around with the chat output. 

And yeah, it's a quick fix.

**Comment by Phergus** [comment]
Tested.  Preferences now changes and saves both foreground and background colors. Chat output now uses trusted prefix colors.
