### ISSUE TITLE
Show player name instead of current impersonation for /ooc and /whisper

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2345]
**Is your feature request related to a problem? Please describe.**
Presently, OOC and whisper messages display the sender's current impersonation, but given that they are channels used for communication between players (as opposed to being from a character, etc.) it feels like it would make more sense to display the player name instead (as with /gm, which already shows player name).

**Describe the solution you'd like**
Switch the name shown for these types of messages from current impersonation to player name.

I'll work on this if nobody has strong feelings about it staying the way it is.

Edit: After some discussion, limiting this to just /ooc.

**Comment by Phergus** [comment]
I definitely agree on the OOC messages.  Not so sure about whisper.  I've definitely used it in the past to have NPCs whisper to PCs so would want to use the impersonated character's name.  But if it is used for inter-Player communication then you would want the Player and not the Character.  Hmmm.

**Comment by Azhrei** [comment]
In my current game, I'm frequently whispering to another player and have to use their char name.  That's kind of annoying.  I also have to type in their entire name (such as "Bob the Barbarian") and there's no way to embed spaces in the name, or if there is, I've never been above to divine the approach to use.

I'd like to be able to use either player name or char name, and I'd like to be able to specify just enough letters of the name be unique, and if necessary, perhaps allow "+" or "_" to act as a space (the "+" would be similar to URL encoding, and the underscore would look similar to a space).

It would be fine with me to use a prefix of "char:" or "player:" (shortened to just "c:" and "p:") to identify which is which, with the default being char (or player; I don't much care which is the default).

Extra points if the /alias command could be used to create a shortcut so that "/wb" could do "/whisper c:bob", or maybe "/wp" could be "/whisper p:" with the following word being the player name.

**Comment by Irarara** [comment]
For the record, I don't feel thaaat strongly about whisper. I just kind of threw that out there also because it's a sort of similar situation and I was curious how people felt about it. It's admittedly much more ambiguous, since it can easily be used for both OOC chatter and IC/roleplay purposes (I've used it in all those ways personally). 

One thing about it that has always felt funny to me though is that the messages are different depending on whether you're sender or recipient. How the sender sees "You whisper to [player]" and the recipient sees "[Identity] whispers". Kind of a small detail (nitpicky, even), but it has always stuck out to me.

The more I think about it, it feels like it might be best to leave it as is or go all in and have something like separate IC and OOC whispers, either by doing it like Azhrei brought up or as separate commands.

**Comment by Phergus** [comment]
@Azhrei 
> In my current game, I'm frequently whispering to another player and have to use their char name.

Whisper only works for player name and not character name.  Would be good if you could use either player name or character name.  I feel that if it just checked for player names first and then token names (or vice-versa) that would work.

>  ...and there's no way to embed spaces in the name, 

You put quotes around the name.  `/w "John Dillinger" Don't go to the theater tonight.`   Also, you can right-click on the player in the Connections window and get a whisper command output to the chat window so you don't have to type in the name.

**Comment by Azhrei** [comment]
> You put quotes around the name.

Hm, I tried a lot of variations; I’m surprised I didn’t find such a simple/obvious solution.  Thanks for pointing it out.

**Comment by Phergus** [comment]
> The more I think about it, it feels like it might be best to leave it as is or go all in and have something like separate IC and OOC whispers, either by doing it like Azhrei brought up or as separate commands.

Currently if the you are impersonating a token that is the name that goes out to the recipient.  With no impersonation, the message uses your player name.   So maybe it doesn't need to be changed to handle IC/OOC.  Being able to address by character name or player name might be handy.

**Comment by Irarara** [comment]
>So maybe it doesn't need to be changed to handle IC/OOC.

Yeah, it just feels like you'd only be losing functionality by making whisper only use player name, since it's not really a problem that it doesn't. Easy enough to tell when something is OOC (and yeah, you could always drop impersonation to make it explicit).

This discussion has gotten me thinking some sort of IC/token whisper whisper could still be interesting though. A separate command, or just different behavior in /w when the target is a token name, that sends a message to the token's owners and GMs (which would solve a slight problem whisper has where if a GM is resolving something with another player over whispers, if there are multiple GMs they can't see what is going on. This would also work in a situation where two players wanted to resolve something IC privately.) Could be handy.

...Also occurred to me that with that, if you had a token with that had multiple players with ownership, whispering to that token could basically act like a chat channel for a subset of players. 🤔

**Comment by Azhrei** [comment]
I'd never considered multiple GMs.  Perhaps any whispers by a GM should just include all GMs.  Each GM still has a login name so the whisperee (not a word, I think) could still tell which GM is sending the message, just as the other GMs could.

**Comment by Irarara** [comment]
Yeah, that could be a useful thing in general.

Regarding the original issue of player names or no though, sounds like yes for /ooc, no for /whisper. So I'll go with that.

**Comment by Phergus** [comment]
Tested.  `/ooc` now uses player name.
