### ISSUE TITLE
Add shortcut key to flip tokens horizontally

### ISSUE THREAD

**Issue by MeloDub** [RPTools/maptool#2349]
**Is your feature request related to a problem? Please describe.**
I've seen many people asking for a faster way to flip tokens horizontally for RP purposes as doing that by right-clicking could be a little frustrating, especially if it's done very often.

**Describe the solution you'd like**
Hit the F key while having one or more tokens selected with the pointer tool to flip them horizontally.

**Comment by EthanBehar68** [comment]
Can I suggest adding a shortcut for vertical flip as well.

**Comment by MeloDub** [comment]
Yes, I think that a shortcut for flipping tokens vertically could be handy too.

**Comment by Phergus** [comment]
Any reason not to apply this on Hidden, Object and Background layers?

**Comment by EthanBehar68** [comment]
From a user standpoint, no. As a DM setting up maps I could see it being useful to flip tokens around quickly if I'm laying out a design. 

Just to be crystal clear since we have a double negative here - I'm for having these hotkeys work for tokens on the Hidden, Object, and Background layers.

**Comment by Phergus** [comment]
@MeloDub you want to extend this functionality?

**Comment by MeloDub** [comment]
Sure, I assumed that the flip key already worked for every layer but I just noticed that there is no pointer tool in object, hidden and backgroud layers. 

What's the best practice here? Should I move the key listeners to DefaultTool or is there a more suitable class for this kind of functionality?
Do I keep them as private classes or I make their own class file in the model package like it's already done with ViewMovementKey?

**Comment by Phergus** [comment]
Off the top of my head, I would say move them to the DefaultTool as I believe that is where the movement keys that affect all layers are located when moving tokens/objects/stamps.

**Comment by Phergus** [comment]
Retested.  Flip  keys now work on all layers.

**Comment by Phergus** [comment]
Updated: https://wiki.rptools.info/index.php/Shortcut_Keys#Token_Related
