### ISSUE TITLE
Add Macro Editor Syntax Highlighting for Campaign Properties

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2352]
**Is your feature request related to a problem? Please describe.**
When editing macros, direct edits to defined token properties is very convenient - but sometimes trips people up when they don't realize they've used a defined property as a local variable name.

**Describe the solution you'd like**
Defined properties can be highlighted in the macro editor to better distinguish between them and normal local vars.

**Additional context**
Ideally this syntax highlighting would be accompanied by context-dependent tooltips and/or other indications... but that would require additional functionality in the Macro Editor, whereas syntax highlighting is low-hanging fruit.

**Comment by selquest** [comment]
*Before*:
![Before - No highlighting for token properties](https://user-images.githubusercontent.com/2325887/102669513-ca31f380-415c-11eb-9041-b0e199c99829.png)
*After*:
![After - Token property highlighted in macro editor](https://user-images.githubusercontent.com/2325887/102669529-d1f19800-415c-11eb-801c-49d2f676e77f.png)

**Comment by Phergus** [comment]
Cool.  I was thinking about the same thing earlier when the discussion came up on Discord.

**Comment by selquest** [comment]
Just checking in to see if there are any particular concerns holding up the PR, or if things are just delayed at the moment?  Making sure it doesn't slip through cracks.

**Comment by Phergus** [comment]
We're on a bit of a code-freeze while there is some core infrastructure being worked on.

**Comment by bubblobill** [comment]
Just one thing @selquest. You are too subtle. Any chance you could alter the highlight from orange colour to super-bold strikeout red flashing at the correct rate to induce seizures.

**Comment by bubblobill** [comment]
Q: Does this pick up properties from all defined property types?

**Comment by selquest** [comment]
> Q: Does this pick up properties from all defined property types?

Yes.  As mentioned in the PR description, I briefly explored the idea of restricting highlighted properties to those applicable to the actual type of the token holding the macro, but there are enough downsides to doing so (Lib:macros, `switchToken()`, Apply to Selected, etc.) that I didn't think it would actually be desirable... and it would require far more disruptive changes to make Type information available at the right spot in the current code path anyway.

> Any chance you could alter the highlight from orange colour to super-bold strikeout red flashing at the correct rate to induce seizures.

Heh.  Well fortunately I didn't have to make actual styling choices - the syntax highlighting is a built-in feature of the 3rd party editor panel that MT uses, I just made it aware of some more keywords and picked a highlighting category that wasn't already in use.  In fact, the specific styling you'll see is actually dependent on your platform (and possibly UI theme?).

**Comment by bubblobill** [comment]
Would there be value in extending this to Bar and State names?

**Comment by selquest** [comment]
> Would there be value in extending this to Bar and State names?

I don't personally see a lot of value to that - or at least, not the same kind of value.  The goal with this particular change is to provide a visual indicator to help macro authors avoid mistakes when directly modifying token properties (deliberately or not).  States and Bars have to be accessed via the `state.name` or `bar.name` constructions, so there's not really the same risk of accidental collisions with local variables.

It might make sense to include states & bars in a more wholistic "what should be highlighted and how" review of the macro editor, but I'd recommend saving that until we see what's going on with 2.0.

**Comment by Phergus** [comment]
Tested.  Working as expected.
