### ISSUE TITLE
MapTool hangs for a while when crossing certain VBL boundaries

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2355]
**Describe the bug**
When entering a VBL "box", MapTool hangs for several seconds (or more) before the token moves and the application becomes responsive again.

**To Reproduce**
1. Draw a 3x3 box using the VBL poly line tool
2. Add a token to the map, dropping it outside of the box.
3. Using the pointer tool, move the token into the box.
4. Wait...

**Expected behavior**
The token should move immediately, and the application should not become unresponsive.

**Screenshots**
This is what the map looks like at Step (2).
![image](https://user-images.githubusercontent.com/7492219/102699135-66a8d400-41f7-11eb-97c1-9f82cc22977d.png)
And after Step (4):
![image](https://user-images.githubusercontent.com/7492219/102699154-83450c00-41f7-11eb-88c9-6741a1ec6d8b.png)

**MapTool Info**
- Version: 1.7.0
- Install: New

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Additional context**
The pause only happens when entering the box. Moving the token back out of the box is instantaneous. It seems to generally impact any situation where the token starts in area not bounded by VBL, or an area that is very large even if it is bounded by VBL. Provided the token starts inside a small VBL boundary, I can move it anywhere.

At first I ran into this with VBL+MBL, and I assumed that the pause was just a side effect of trying to pathfind in an unsolveable situation. I thought maybe the reverse action of leaving the box might be faster because the algorithm fails more quickly with a more restricted set of possible spaces. I just decided to accept the pause as it doesn't come up terribly. What surprised me is that it also affects plain VBL, suggesting that something other than pathfinding is the culprit.

**Comment by Azhrei** [comment]
You have the AI token movement turned on and it’s searching for a route into that area.  It times out and gives up after X seconds (ten, I think).

it might be nice in this case if it started from the other end as it could easily determine that there’s no route, but there’s no way to know that in the general case.

**Comment by kwvanderlinde** [comment]
:facepalm: I did not even realize those buttons existed - I must have inadvertantly turned them on (or are they on by default?) I definitely did not think that VBL could block movement, but I guess that is for backwards compatibility (and I see now that it can be disabled separately).

I don't know how the pathfinding works (nor do I really know about pathfinding algorithms in general), but is it possible/practical/worthwhile to do a two-sided approach which performs the same regardless of direction?

**Comment by Azhrei** [comment]
> I don't know how the pathfinding works (nor do I really know about pathfinding algorithms in general), but is it possible/practical/worthwhile to do a two-sided approach which performs the same regardless of direction?

Not really.  The purpose of pathfinding is to identify the least costly route.  Exhaustive evaluation of all routes is just the nature of the beast.  (Sort of like how a chess program has to examine all possible moves because even one that looks dumb at the outset could be the key to checkmate.)  Maybe there could be some tweaking to the algorithm currently used to more quickly eliminate impossible moves, but, as the saying goes, "the needs of the many outweigh the needs of the new."

**Comment by kwvanderlinde** [comment]
I've recently looked at this again, and discovered that there is such a thing as bidirectional A*. Apparently it can have some performance benefits, though I'm sure those come with some tradeoffs. It should also be able to treat the source and target cells more symmetrically. E.g., it won't matter if the source is outside and the target inside, or vice versa, it should be able to fail quickly in either case. Of course there are still other situations that will trigger timeouts, but the number of those cases should be smaller.

I'm looking at what it will take to update the A* walker with bidirectional support. There is some unfortunate coupling between the A* implementation details and the rendering logic, which makes some of it a little tricky, but there should be a way to clean that up. I'm also doing some perf tests to make sure that the bidirectional algorithm won't be slower than the existing unidirectional algorithm.

**Comment by kwvanderlinde** [comment]
I had put together a prototype bidi A* implementation. While it was satisfying to see it work, I would not call the resulting code "nice"/"maintainable"/"debuggable". I'm not going to bother submitting that code as I think it's more trouble than it's worth.

I've taken a step back and come up with a new and much simpler strategy. The weakness with A* is that it doesn't terminate when the search space is unbounded and no valid path exists (i.e., no robust failure case). But if we have a bound on the search space, then A* is always guaranteed to terminiate. A bound can be provided manually by the user, by drawing MBL around the interesting part of the map. But we can also do it automatically by generating a bound around:
- All MBL/VBL
- All terrain mod tokens
- The start and end cells

Then we just need some extra padding beyond that, to allow pathfinding around the outside of everything. Unless this bound is quite large (say, a couple hundred cells across), A* can actually terminate well under timeout when no valid path exists (system-dependent, of course).

**Comment by cwisniew** [comment]
I like it, that will work well in most cases (the really huge maps being an outlier) for the buffer you can use 2 * token size to extend the bounding box, that way you don't have to worry about special case where VBL extends out of a grid cell. 

This would really solve the problem for 95%+ cases so definitely worth it.

**Comment by Phergus** [comment]
Sounds good to me.

**Comment by Phergus** [comment]
Tested.  Dropping tokens into closed areas from open ones is now instantaneous.
