### ISSUE TITLE
Add ability to scroll around the map with just the keyboard

### ISSUE THREAD

**Issue by matejdro** [RPTools/maptool#2360]
**Is your feature request related to a problem? Please describe.**

MapTool currently allows moving tokens with arrows keys and then pressing D to confirm.  However, this only works when the token is in view. If user wants to move token around larger area with just a keyboard, he/she is out of luck. There is no way to scroll the map with the keyboard

**Describe the solution you'd like**

I would like a way to scroll the map with the keyboard. One solution might be Ctrl + arrow keys (and/or numpad).

**Describe alternatives you've considered**

Alternative solution would be to lock the current token in the center of the screen when user is using arrow keys + D (so the map will auto-scroll). But this might not always be desirable (for example if GM does not want users to scroll the map), so it should be configurable.

**Additional context**

I've made sample implementation of the Ctrl solution here: https://github.com/RPTools/maptool/pull/2359

**Comment by matejdro** [comment]
@Phergus why am I being assigned to this? What can I do to move this PR forward?

**Comment by Phergus** [comment]
You were assigned to it as you did the work on it.  The outstanding feature request PRs will get merged into develop shortly.

**Comment by Phergus** [comment]
Tested.  Map panning with Ctrl and arrow keys or Ctrl and numpad keys working as expected.  Using arrow keys for token/object/stamp movement still working normally.  No issues when fullscreen.

**Comment by Azhrei** [comment]
Hm, I must've missed this one when it was proposed.  Using the Ctrl key will be problematic on macOS as it uses Ctrl-left and Ctrl-right to switch virtual desktops (I'm not sure if Linux uses the same keystrokes).

Seems like we really need support for programmable keystrokes!

**Comment by Phergus** [comment]
Can't use Alt or Shift.  Can put in the OS specific hack to catch it for MacOS and look for Cmd instead.  No idea about Linux.

**Comment by Azhrei** [comment]
Okay, thanks.  There's already a field somewhere (maybe I18N?) that holds the "meta key" used for the platform; that would be the way to check.

**Comment by Phergus** [comment]
@matejdro you got this?

**Comment by matejdro** [comment]
Sorry, I do not have a Mac so I can't test it. Patch was made and tested on Linux though, so it works.

**Comment by Phergus** [comment]
Up to the Mac users then.
