### ISSUE TITLE
Getting an error on startup

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#2364]
**Describe the bug**
Whenever I start up 1.8 Beta 2, I get the following error: 
![image](https://user-images.githubusercontent.com/2953375/103816660-a24ff480-5065-11eb-92cc-3aa07dbda756.png)

Apparently, the MappTool.cfg file is in use and thus the process cannot gain access. 
I realize that this is most likely something local, but being pretty Java illiterate, I'd better throw it up here. 

I acknowledge the dialog, and the application starts up, apparently without problems. 

If I remove the file (rename it), the application will not start. 

**MapTool Info**
- Version: 1.8 beta 2
- Install: New (side-loaded with 1.7).

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Tdue21** [comment]
This seem to have been resolved with the 1.8.3 release.

**Comment by Phergus** [comment]
That's because it doesn't try to copy the cfg file anymore.  This issue is why the startup parameters have to be set manually now.
