### ISSUE TITLE
Improve tooltips and error messages for starting a server

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2366]
**Is your feature request related to a problem? Please describe.**
New users unfamiliar with networking in general or the MapTool model in particular may be confused by some of the options on the Start Server dialog, and by some error messages that can appear when attempting to start a server.

**Describe the solution you'd like**
While some degree of learning curve is unavoidable, we should make sure to use informative tooltips and helpful error messages to help cut down on confusion wherever possible.

Current additions include:
- tooltip for `Use UPnP` checkbox
- tooltip for `RPTools.net Alias` text box
- more helpful error message when UPnP utility fails to find a compatible router

**Describe alternatives you've considered**
Some users may find a more guided-wizard approach more helpful.  Definitely wouldn't recommend completely replacing the current single-dialog interface, but providing an alternative that includes a bit more explanation of each option and step in the process might help improve the new user experience.

**Comment by Phergus** [comment]
@selquest you have a PR incoming on this?

**Comment by selquest** [comment]
I knew there was something waiting for my dev branch to be unblocked...

Pretty small change here, but hopefully will help a few folks.

**Comment by Phergus** [comment]
Tested.  New text is considerably more helpful.
