### ISSUE TITLE
Allow spawning web workers from blob: URLs

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2371]
**Is your feature request related to a problem? Please describe.**
In JavaScript-heavy HTML contexts (overlays, frames, dialogs) it can be useful to offload work from the main thread. The tool to do this is Web Workers. Unfortunately, `blob:` URLs are blocked by the `Content-Security-Policy`, meaning we can't spawn a worker using literal JavaScript code.

**Describe the solution you'd like**
Do not block `blob:` URLs when spawning web workers.

**Describe alternatives you've considered**
Since a Web Worker must be spawned using a filename or URL pointing to JavaScript, the only current alternative is to host our worker code on one of the whitelisted CDNs. I wouldn't really call this an true alternative since we can't test the code locally.

Another way to allow web workers would be to allow loading JavaScript code stored in a macro or elsewhere. This is quite a feature in its own right (especially if done generally for use with imports, etc), but I would say `blob:` URLs would still be useful for self-contained scripts.

**Additional context**
This should be as simple as adding `worker-src blob: ;` to the CSP,  but I don't think JavaFX's WebView respects it. One of the fallbacks like `child-src` should do the trick though.

**Comment by cwisniew** [comment]
Unlikely to be fixed.
See #3419
