### ISSUE TITLE
lmwcs.com redirects to ads

### ISSUE THREAD

**Issue by craigmccauley** [RPTools/maptool#2378]
I think either the wiki server was compromised or control of the lmwcs.com domain was lost.
http://lmwcs.com/ redirects to wellnesszap

**Comment by craigmccauley** [comment]
Ah I see the wiki moved to https://wiki.rptools.info/
The links should be updated in the application and the readme.

**Comment by Azhrei** [comment]
We need a way of doing this automatically without updating the application, but it gets complicated.  Well, more tedious instead of complicated...

**Comment by Phergus** [comment]
README.md and Help menu links were both updated for 1.8.3 release.
