### ISSUE TITLE
When used with more than one token, function moveTokenToMap moves the token in a wrong position, if source and target map have different distance per cell

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#2382]
**Describe the bug**
Function moveTokenToMap, when called with more than one token, will place the first token in the (X, Y) point provided, and the other in wrong positions. 

This happens only if the source and target maps have different Distance Per Cell.

The issue is present both for moveTokenToMap and moveTokenFromMap

**To Reproduce**
1. Load the attached campaign moveTokenToMap_issue
2. Go to map5; on that map there are two tokens, Eagle and Dragon
3. Click on reset macro in the campaign window to ensure that both tokens have the same position at the center of the screen
4. Click on move macro in the campaign window
4. Enter map10 as the target map
5. Switch to map10
6. Check the positions of Eagle and Dragon: they are different, even though they should be set to the same position

**Expected behavior**
The expected behavior is that all the tokens are moved in the same (x, y) position.

**Screenshots**
No screen shot available

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.7, dev

**Additional context**
Issue is caused by https://github.com/RPTools/maptool/blob/6d193e3f5cc635aed30730ec09fde2a210870054/src/main/java/net/rptools/maptool/client/functions/TokenLocationFunctions.java#L207-L209 as the previous (x, y) is used to calculate the position of the next token; of course, after the first one, this will not work.

**Comment by emmebi** [comment]
[moveTokenToMap_issue.cmpgn.zip](https://github.com/RPTools/maptool/files/5937643/moveTokenToMap_issue.cmpgn.zip)

**Comment by dorpond** [comment]
I'm curious if this solution will help or resolve this issue as well?
https://github.com/RPTools/maptool/issues/2260

**Comment by Phergus** [comment]
@dorpond - This doesn't fix that issue.

**Comment by Phergus** [comment]
Tested.  Using `moveTokenToMap()` between maps with different Distance per Cell values and multiple tokens no longer puts them in the wrong place.
