### ISSUE TITLE
MapTool refuses to start if you have changed the theme and deleted the .maptool-rptools directory (windows)

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2392]
**Describe the bug**
If you have selected a look and feel theme in MapTool on windows and delete the .maptool-rptools directory next time you install MapTool it will fail to start when looking for the theme.

**To Reproduce**
Set the look and feel theme, delete the .maptool-rptools directory and restart MapTool

**Expected behavior**
It shouldn't fail :)

**Screenshots**
![image](https://user-images.githubusercontent.com/73173/108057890-281e8100-70a3-11eb-95b3-b4ff99fd21c9.png)

**MapTool Info**
- Version: 1.5.? +

**Desktop (please complete the following information):**
- Windows only, preferences are stored in registry for windows, other systems they are stored in a file in the .maptool-rptools directory.

**Additional context**
Work around is to unzip the following file into <UserDir>\.maptool-rptools
[themes.zip](https://github.com/RPTools/maptool/files/5988324/themes.zip)

**Comment by Phergus** [comment]
Tested.  Missing theme file produces a dialog on startup alerting user to missing theme.  Preference setting updated to use default theme.

For reference the preference is stored in: `Computer\HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\/Map/Tool\ui\theme`
