### ISSUE TITLE
Player can log in as GM using the player password.

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#2394]
**Describe the bug**
Players can log in as a GM using the player password or log in as a player using the gm password.

**To Reproduce**
Log in as GM using the player password.

**Expected behavior**
You shouldn't be able to log in as GM without the GM password.

**MapTool Info**
- Version: 1.8.3

**Comment by Akaku-Keninari** [comment]
This also works the other way around: a player can log in as a player with the GM password.

**Comment by Phergus** [comment]
Tested.  Using Player password to connect logs client in as Player.  Using GM password logs client in as GM.

**Comment by Phergus** [comment]
It is logging an error message as the init for the role combo box is still being called.

**Comment by Phergus** [comment]
@cwisniew  PR pushed to remove combobox init functions from ConnectToServerDialog.java.

**Comment by Phergus** [comment]
Retested.  No longer produces errors in log.
