### ISSUE TITLE
Macro Editor Auto-Completion

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#240]
Turn on RSyntaxTextArea's auto-completion which adds word completion for Macro function names and display a short description + summary of the function.

Also add a few short hands for if/for/switch

**Comment by JamzTheMan** [comment]
The framework is done and ready to add descriptions.  Will create another issue to track adding in descriptions.

**Comment by Azhrei** [comment]
Periods are treated as non-identifier characters so that `son.sort` doesn't autocomplete properly.  @JamzTheMan already found the fix, so I'll submit a PR shortly.

**Comment by JamzTheMan** [comment]
Thanks!

**Comment by cwisniew** [comment]
Moving this to post Nerps fix as it isn't critical for the release hasn't been addressed for 4 days

**Comment by Azhrei** [comment]
This has been merged.
