### ISSUE TITLE
Startup Preferences dialog will some times still try to write to configuration file.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2408]
**Describe the bug**
Focus/defocus on controls in the startup tab of the the preference dialogs can trigger MapTool into thinking the configuration file has changed and needs to be written out in some environments.

**Expected behavior**
There should be no way to trigger update to configuration file until #2174 is resolved.
 

**MapTool Info**
Version 1.8.3

**Comment by Phergus** [comment]
Until a solution is found for #2174 here are the settings normally accessed from preferencs:

**Startup Config for MT 1.8.3**
Locate the maptool.cfg file under the app folder in your MapTool install directory.  _The following are examples._  You shouldn't need to add or change ANY of them excepting language for those in different locales.

Under `[JavaOptions]` you can add/set the following:
`-Xmx4G` - set max heap to 4G
`-Xms1G` - set min heap to 1G
`-Xss10M` - set stack size to 10M
`-Dsun.java2d.d3d=false` - disable Direct3D
`-Dsun.java2d.opengl=true` - enable OpenGL 
`-Djavafx.macosx.embedded=false` - initialize AWT before JFX (MacOS only)
`-Duser.language=en` - set MT locale to English

**Comment by Phergus** [comment]
Will need a proper, versioned build to test.
