### ISSUE TITLE
Using playStream() raises a MediaException: Could not create player!

### ISSUE THREAD

**Issue by Penaz91** [RPTools/maptool#2413]
**Describe the bug**
I have been trying to add more depth to my campaigns by adding sounds and ambiance, but reproducing from a remote source doesn't output any sound, while reproducing from a local file raises a MediaException.

**To Reproduce**
This can be reproduced with a simple command like the following ones:
`[playStream("https://freesound.org/data/previews/388/388340_4451356-lq.mp3", 1, 1)]` (this is silent)
`[playStream("file:///home/penaz/Multimedia/DnD_Sounds/DungeonAmbiance.mp3", 1, 1)]` (this raises the exception)

**Expected behavior**
The ambiance sound chosen should play.

**MapTool Info**
- Version: 1.7.0 and 1.8.3 are both affected
- Install: 1.7.0 installed via AUR, then updated to 1.8.3 with the Arch package from GitHub

**Desktop (please complete the following information):**
 - OS: Artix Linux (ArchLinux Derivative) - Kernel 5.10.16

**Additional context**
My system JDK is OpenJdk 15.0.2.u7 and I have java-openjfx 15.0.1.u1 installed (having or removing openjfx doesn't change the output).

I added some files with further information.

[info.txt](https://github.com/RPTools/maptool/files/6018125/info.txt)

[exception.log](https://github.com/RPTools/maptool/files/6018126/exception.log)

Thank you very much for your work and exceptional virtual tabletop.

**Comment by Penaz91** [comment]
Using `playClip()` raises a similar exception that I will paste here, no matter if I use a local file or something online:

```
Exception in thread "Thread-22" com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:295)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer.play(NativeMediaAudioClipPlayer.java:319)
	at com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer.clipScheduler(NativeMediaAudioClipPlayer.java:112)
	at com.sun.media.jfxmediaimpl.NativeMediaAudioClipPlayer$Enthreaderator.lambda$static$0(NativeMediaAudioClipPlayer.java:85)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Merudo** [comment]
I can't reproduce with Windows 10. The following works fine:

`[playStream("https://freesound.org/data/previews/388/388340_4451356-lq.mp3", 1, 1)]`

**Comment by Merudo** [comment]
Could be related to #2358

**Comment by Penaz91** [comment]
I can confirm that the problem is indeed related to the ticket cited earlier, installing `ffmpeg-compat-55` from AUR indeed fixes the issue.
Weirdly enough, I did install it before filing this ticket and it didn't work, after doing a clean install everything works.

Thank you kindly, feel free to close this ticket if necessary.

**Comment by Phergus** [comment]
Thanks for confirming the solution.
