### ISSUE TITLE
UDFs no longer picked up by code-completion/syntax highlighting in editor

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#2422]
**Describe the bug**
User-defined functions (UDFs) are no longer listed in suggestions by code-completion and are not highlighted by syntax highlighting.

**To Reproduce**
1. Add a macro to the Campaign panel named `Test`.
2. From chat (or in a separate macro) run `[r: defineFunction("test","Test@Campaign",0)]`
3. Verify UDF is working from chat with `[r: test()]`
4. Add another macro to Campaign panel and edit it.
5. Type in `[r: tes` and hit `ctrl-space`.  UDF `test` does not appear in suggestions.
6. Complete the call to `test` in the macro ( `[r: test()]`).  Note `test` is not highlighted as a UDF.

**Expected behavior**
Was working in 1.7.0

**MapTool Info**
- Version: 1.8.3
- Install: New

**Desktop (please complete the following information):**
 - OS:  Windows
 - Version:10

**Comment by selquest** [comment]
The root cause here is that UDFs are no longer actually added to the parser, but looked up directly from the UserDefinedMacroFunctions instance - see #2100.

Easy enough to add back to syntax highlighting and auto-completion, PR coming momentarily.

**Comment by Phergus** [comment]
Tested.  Auto-complete now includes UDFs and shows correct highlighting in macro code. 

At some point however the adding of tooltip text to the description in auto-complete was broken.  Checked 1.6.1 and 1.7.0 and it was broken in both.

See #440
> Autocomplete for UDF's now show "Token " + lib token UDF is defined for and **if the macro has a ToolTip, it will be displayed as the help text for the UDF! (Thanks to @source-knights for this PR)**

**Comment by selquest** [comment]
> At some point however the adding of tooltip text to the description in auto-complete was broken. Checked 1.6.1 and 1.7.0 and it was broken in both.

Not sure if you meant this was still broken after this change, or whether you're noting that this change fixed this... but it was definitely the intention here that the "description" on autocompletion should show the macro's location, and the "summary" should show the tooltip contents, if any.  (It should be noted that the auto-complete data is only reinitialized on the first editor window opened after a new UDF has been defined... changing the tooltip after the fact won't be reflected until the list of parseable functions changes again.)

**Comment by Phergus** [comment]
Sorry, misspoke.  I meant the summary field and just commenting that it was and still is broken.  Don't know when it stopped working but I'm pretty sure it was working at some point in the past.

**Comment by Phergus** [comment]
Going to open a new ticket for the tooltip/summary issue.

**Comment by Phergus** [comment]
Original issue has been addressed.

**Comment by selquest** [comment]
![MT-2422-ShortDescAndSummary](https://user-images.githubusercontent.com/2325887/110216272-35e24d80-7e7c-11eb-9750-383e751592ea.png)
Ahh, I see the confusion.  Looks like the description/tooltip extractor are relying on the UDF pointing at a token macro, not a Campaign macro.
