### ISSUE TITLE
Changing token states in onInitiative events breaks the initiative list's synchronization

### ISSUE THREAD

**Issue by selquest** [RPTools/maptool#2424]
**Describe the bug**
When an `onInitiativeChangeRequest` or `onInitiativeChange` handler modifies a token on the Initiative List, the Initiative List stops updating on connected clients.

**To Reproduce**
1. Create an `onIniativeChange` handler on a Lib:token containing a macro like:
```
[h: newToken = json.get(json.get(macro.args, "new"), "token")]
[h: setState("Other", 1, newToken)]
```
2. Add several tokens to Initiative
3. (with a server running, and at least 1 connected client) use the next button to advance initiative a few times
4. Observe that the GM initiative panel updates, but the connected client's initiative is out of sync

**Expected behavior**
Initiative List should remain in sync

**MapTool Info**
- Version: 1.8.3

**Additional context**
Problem comes within the InitiativeList.update() method.  The IniativeList uses a counter to track pending changes so that the updated list is only distributed once all changes within an operation have completed.  When a token is updated (receives a new State, for instance), that counter is incremented but never decremented... this logic was written before it was possible for a token state to change *during* an initiative change, and needs to be updated to account for the initiative events.
https://github.com/RPTools/maptool/blob/b951263b4fb17001da802ad18b7c0939b77129cd/src/main/java/net/rptools/maptool/model/InitiativeList.java#L446-L448

**Comment by selquest** [comment]
I should have a fix for this tomorrow.  Because this bug effectively renders the `onInitiativeChange` events useless, strongly recommend including in 1.8.4.

**Comment by Phergus** [comment]
The goal for 1.8.4 is to get what was broken between 1.7.0 and 1.8.3 fixed so this definitely qualifies.

**Comment by Phergus** [comment]
Tested.  Next, Previous and Hold functions are seen on clients and events are functioning.
