### ISSUE TITLE
Cannot invoke "java.ioFile.exists()" because "f2" is null

### ISSUE THREAD

**Issue by Blodhundur** [RPTools/maptool#2429]
Hey, I wanted to update MapTool and this error kept popping up. I updated Java, I uninstalled it and then reinstalled it several times, but I still get this issue. How can I fix this? :(

![help](https://user-images.githubusercontent.com/79946787/109728439-2dd89400-7b84-11eb-9de8-1c55decfc709.PNG)

- Version: 1.8.3
 - Windows 10, 8 RAM, Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz 2.81 GHz

**Comment by cwisniew** [comment]
See #2392  there is a file attached you can unzip, but if you had another custom theme you will need to place that in the directory structure created.
