### ISSUE TITLE
closeOverlay, isOverlayRegistered and overlay can get out of sync

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#2435]
**Describe the bug**
It is possible to reach a state in which you have the overlay on the screen, and yet the isOverlayRegistered returns 0. 

**To Reproduce**

Add the following macro to a library token (I don't see why it should make a difference, but I have tested it in that context).

```
[h: myContent = "this is a test"]

[h, if(isOverlayRegistered("Test") == 1), code: {
	[log.info("The overlay is open, and I am going to close it")]
	[closeOverlay("Test")]
}]

[log.info(strformat("isOverlayRegistered expected to be 0 and it is %s", isOverlayRegistered("Test")))]

[overlay("Test", 100):{
<html>

<head>

</head>
<body>
<div>
[r:myContent]
</div>
</body>
</html>
}]
[log.info(strformat("isOverlayRegistered expected to be 1 and it is %s", isOverlayRegistered("Test")))]

```

The macro, as you can see, is very simple:
- it checks if a specific overlay is already present
- if it is, it closes it
- then it re-creates the overlay
- then reports it's status.

The first run reports the following:
```
2021-03-06 09:24:01.379 INFO  macro-logger - isOverlayRegistered expected to be 0 and it is 0
2021-03-06 09:24:01.380 INFO  macro-logger - isOverlayRegistered expected to be 1 and it is 0
```

The second is even more interesting:
```
2021-03-06 09:24:24.596 INFO  macro-logger - The overlay is open, and I am going to close it
2021-03-06 09:24:24.596 INFO  macro-logger - isOverlayRegistered expected to be 0 and it is 1
2021-03-06 09:24:24.596 INFO  macro-logger - isOverlayRegistered expected to be 1 and it is 0
```

**Expected behavior**
isOverlayRegistered should report a proper state of the overlay, as it is run in the same macro. If this is not feasible, we should document this behavior.

**MapTool Info**
- Version: 1.8.3
- Install: Upgrade from 1.7.0

**Desktop **
 - OS: Windows
 - Version: 10

**Additional context**
Looking at the code I suspect the problem being in the fact that the overlay and the closeOverlay are all executed as runLater, while the isOverlayRegistered is a synchronous operation.

**Comment by cwisniew** [comment]
Overlays and macros run on different threads this is something that is likely not going to be fixable as synchronisation between those two threads would cause worse problems than this l.

**Comment by emmebi** [comment]
@cwisniew I agree on the fact that fixing this would be a major problem/undertaking; maybe we could add a note in the documentation? Willing to add a couple of notes, if needed.

**Comment by Azhrei** [comment]
Yes, that's a great idea.  Do it. :)
