### ISSUE TITLE
Auto-complete Summary field not showing Tooltip contents for UDFs

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#2436]
**Describe the bug**
The tooltip from the macro should be shown in the summary field for a User-Defined Function (UDF).  See #440.

**Only broken for macros not on Tokens.**

**To Reproduce**
1. Load attached Campaign file.
2. Click on Define macro.
3. Edit Call Test macro (or create new one) and place cursor after `test` but before the left parens.
4. Hit Ctrl-Space to see autocomplete information note lack of tooltip in summary.

**Expected behavior**
Expect to see contents of Tooltip from macro in summary.

**Screenshots**
![image](https://user-images.githubusercontent.com/34379254/110215665-37a21600-7e68-11eb-92af-53ea85d4cbe4.png)

![image](https://user-images.githubusercontent.com/34379254/110215692-543e4e00-7e68-11eb-93d8-8f847d502749.png)

**MapTool Info**
- Version: Broken as far back as 1.6.1.
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
See #2422 as well.

Remove `.zip` from end of name.
[MacroTooltipSaveTest 1.8.3.cmpgn.zip](https://github.com/RPTools/maptool/files/6095822/MacroTooltipSaveTest.1.8.3.cmpgn.zip)

**Comment by selquest** [comment]
The `UserDefinedMacroFunctions#getFunctionTooltip()` method doesn't account for UDFs pointing at Campaign macros instead of token macros.  I'll expand it to work with other panels, and that'll fix the tooltip output in autocompletion (after #2422 fix) and in `getInfo()`.

**Comment by Phergus** [comment]
Sounds good.

**Comment by selquest** [comment]
Example campaign including UDFs defined pointing at several sources, including some invalid definitions: 
[MT-2436-udfTooltipSummaryTest.cmpgn.zip](https://github.com/RPTools/maptool/files/6096245/MT-2436-udfTooltipSummaryTest.cmpgn.zip) (remove .zip extension)

Expected output of the `getDefinedFunctions("", 1)` command:
> zHero - Greet@Hero - Summary not available for "Greet@Hero": Macros from other tokens are only available if the token name starts with "Lib:". 
> zMissing - MissingMacro@Lib:Missing - Summary not available, target not found for "MissingMacro@Lib:Missing". 
> zRoar - Roar@Lib:Dragon - Roar like a Dragon!
> zSoar - Soar@Lib:Eagle - Summary not available for "Soar@Lib:Eagle": Duplicate "Lib:Eagle" tokens found.
> ztest - Test@Campaign - <html>This is the tooltip for <b>Test@CAMPAIGN</b>.</html> 
> ztestGM - TestGM@GM - <html>This is the tooltip for <b>Test@GM</b>.</html> 
> ztestGlobal - Test@Global - Summary not available, target not found for "Test@Global".

Corresponding tooltip text also loads into autocomplete summaries.

**Comment by Phergus** [comment]
Testing.  Description/summary is now seen for UDFs with tooltips defined in the return from `getDefinedFunctions()` as well as in the autocomplete.

For valid macros on Campaign/GM panels that lack a tooltip, `getDefinedFunctions()` does not return the "Summary not available..." message and in the auto-complete popup the "No description available." message is not shown.

Those messages should probably be consistent and both either use *description* or *summary*.

**Comment by selquest** [comment]
Since the "No description available" message is coming from within the 3rd party library, I'll change those new messages to say "description" instead (even though the code in that 3rd party library is what is referring to it as "summary" 😛)

Did we want `getDefinedFunctions()` to say "No description available" if the tooltip is blank?  The warnings I'd added were more intended to highlight actual instances of broken configurations (in cases where the UDF won't work, not just where there's not a tooltip), but maybe some consistency would be nice.  Alternatively, maybe those error messages just need to actually say something like "Error loading description" instead of just "not available"?

**Comment by Phergus** [comment]
> Since the "No description available" message is coming from within the 3rd party library, I'll change those new messages to say "description" instead (even though the code in that 3rd party library is what is referring to it as "summary" 😛)

Of course it does.

> Did we want getDefinedFunctions() to say "No description available" if the tooltip is blank? 

Seemed inconsistent that broken UDF configs had the "Summary not available" message but valid UDF configs that lack a tooltip/summary/description did not.

If either the macro name or the source token/panel of the macro is invalid when defining a function then by definition there won't be a tooltip so maybe we don't need to state the obvious in that case?

- So, if the config is broken, no need to mention the missing summary.
- If the config is valid but summary is missing, show nothing as it currently does.
- If the config is valid and has summary, show it.

Don't feel particularly strongly about this one way or the other.

**Comment by selquest** [comment]
> If either the macro name or the source token/panel of the macro is invalid when defining a function then by definition there won't be a tooltip so maybe we don't need to state the obvious in that case?

Right now those messages are stemming from caught parser exceptions when trying to lookup the tooltips.  We could go back to returning null or blank descriptions in those catch blocks, but it seems to me that if we have an opportunity to tell someone in advance that trying to call their defined UDF is going to throw a parser exception, it makes sense to do so.  Especially in the context of autocomplete, it seems reasonable to give the user a heads-up that they're about to autocomplete to code we already know won't work. Actually, ideally the `defineFunction()` method should be applying some sort of sanity check when first defining the UDF - but that gets into a whole rabbit hole of race conditions with `onCampaignLoad` processing (where UDFs are typically defined)... and is beside the point for the moment anyway.

I think my inclination if there are no objections:
- Valid UDFs pointing to existing macros, with tooltip: show it.
- Valid UDFs pointing to existing macros, with no tooltip: "No description available" (to match message from autocomplete library)
- Broken UDFs get a description that more clearly indicates an error: "Error retrieving description: target not found", etc.

**Comment by Phergus** [comment]
That works for me.

**Comment by Azhrei** [comment]
> * Valid UDFs pointing to existing macros, with no tooltip: "No description available" (to match message from autocomplete library)

Does the library localize those messages?  Do you have a way to access that ResourceBundle so you can use the same message?

**Comment by selquest** [comment]
> Does the library localize those messages? Do you have a way to access that ResourceBundle so you can use the same message?

The "No description available" message is localized within the "AutoCompleteDescWindow" resource bundle, so I should be able to just load the string from there.  I'm not sure that the translations provided by the library include quite the variety that MT has - do the Crowdin translations apply to 3rd party resource bundles, or just the MT ones?  I don't know enough about how that works.

Especially if we do load the "No description available" message from the autocomplete library though, I think I'd prefer we leave `getDefinedFunctions()` returning an empty string when the tooltip is empty.  I maintain that exposing error conditions there is a good idea, but a bunch of "No description available" messages in the results gets pretty cluttered pretty quickly, and I think serves to take attention away from the actual error messages.  If we load the message from autocomplete, then we also have a separation of concerns issue - no reason for the UserDefinedMacroFunctions class to know anything about autocomplete, so I'd rather insert that message higher up the call stack (and only for autocomplete).

**Comment by Azhrei** [comment]
I was hoping we could inject our own ResourceBundle so that we could add those keys to are translation file(s).  Well, whatever makes sense...

**Comment by Phergus** [comment]
> I maintain that exposing error conditions there is a good idea, but a bunch of "No description available" messages in the results gets pretty cluttered pretty quickly, and I think serves to take attention away from the actual error messages. 

I agree and that's why for invalid UDFs there is no point in saying there is no description.  Of course there is no description as the definition itself is wrong.
