### ISSUE TITLE
getMacroProps returns the wrong "key" for maxWidth

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2468]
**Describe the bug**
Typo
getMacroProps returns the "key" for maxWidth as maxWith

**To Reproduce**
3. If macro related, sample macro code '....'

**Expected behavior**

**Screenshots**

**MapTool Info**
- Version: 1.5.?
- Install: New, Upgrade [previous version], or JAR [Java Version]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux [Ubuntu, Debian, CentOS, etc], MacOS]
 - Version [10, 18.04]

**Additional context**
From MapTool, paste info from menu Help -> Gather Debug Information...
You can also attach files (drag and drop here) such as log files or paste a file sharing link.

**Comment by Phergus** [comment]
Incomplete.  Closing.
