### ISSUE TITLE
AppHome and log directory end up in two separate directories

### ISSUE THREAD

**Issue by TLATER** [RPTools/maptool#2471]
**Describe the bug**

When launching maptool, it will create two directories in my home directory:

```
01:31:44.330 (MapTool.java:1533) [main] INFO  net.rptools.maptool.client.MapTool - AppHome System Property: /home/tlater/.maptool-RPTools/logs
01:31:44.330 (MapTool.java:1534) [main] INFO  net.rptools.maptool.client.MapTool - Logging to: /home/tlater/.maptool-rptools/logs/maptool.log
```

Clearly one is a typo.

**To Reproduce**

1. Start maptool
2. See two directories

**Expected behavior**

One directory is created.

**MapTool Info**
- Version: 1.8.3
- Install: Manually built, "new"?

**Desktop (please complete the following information):**
 - OS: Linux, NixOS
 - Version 20.09.20210311.6be212c (Nightingale)

**Comment by TLATER** [comment]
On second reflection, maybe this was missed because some file systems are case-insensitive. To be clear, the problem is that the log file is written to `~/.maptool-**rpt**ools`, rather than `~/.maptool-**RPT**ools`.

**Comment by Phergus** [comment]
Everything should be going to `.maptool-rptools`.

**Comment by Irarara** [comment]
@TLATER Out of curiosity, are you running from a dev environment (or well, specifically I mean via `gradlew run`)? Or is still showing `.maptool-RPTools` in the log when you aren't?

**Comment by TLATER** [comment]
@Irarara I'm running a jar produced by `./gradlew build`, I'm not sure to what degree that will match a dev environment.

Neither the released jar nor packages work for me, so I can't confirm if these are produced if I don't manually build.

**Comment by Irarara** [comment]
@TLATER Gotcha, thanks!

**Comment by TLATER** [comment]
Ah, thank you @Irarara, I tried to figure out where that was coming from but didn't think to look in the build scripts :)

**Comment by Phergus** [comment]
Reviewed.  No longer creates folder with mixed case letters.
