### ISSUE TITLE
Installer should not require accepting the license

### ISSUE THREAD

**Issue by emaliom** [RPTools/maptool#2473]
**Describe the bug**
The windows installer require users to accept the license. However according to the AGPL acceptance is not required in order to use the program. Other MapTool installers are possibly affected too but I have not tested them.

**To Reproduce**
1. Run the installer MapTool-1.8.3.exe.
2. When it displays "End-User License Agreement" do not accept the license.
3. Attempt to continue installing the program.
4. The installer provides no way to install the program.

**Expected behavior**
I expected to be able to install the program without accepting the license.

**Screenshots**
None

**MapTool Info**
- Version: 1.8.3
- Install: New

**Desktop**
 - OS: Windows
 - Version 10, 20H2

**Additional context**
Relevant section of the license as displayed to the user by the installer:

> 9. Acceptance Not Required for Having Copies.
> You are not required to accept this License in order to receive or run a copy of the Program.

**Comment by Azhrei** [comment]
Check out the fact available at gnu.org, in particular this one https://www.gnu.org/licenses/gpl-faq.html#ClickThrough:

> **Can software installers ask people to click to agree to the GPL? If I get some software under the GPL, do I have to agree to anything?** (#ClickThrough)
>
> Some software packaging systems have a place which requires you to click through or otherwise indicate assent to the terms of the GPL. This is neither required nor forbidden. With or without a click through, the GPL's rules remain the same.
>
> Merely agreeing to the GPL doesn't place any obligations on you. You are not required to agree to anything to merely use software which is licensed under the GPL. You only have obligations if you modify or distribute the software. If it really bothers you to click through the GPL, nothing stops you from hacking the GPLed software to bypass this.

I'm not sure you should actually hack the installer, though 😉 as I don't know whether `jpackage` embeds anything that has a restrictive license on it.  If it does, you may be liable for said hacking under the laws of various governments (although perhaps not yours!).
