### ISSUE TITLE
Inline Expansion of URLs doesn't stop at whitespaces

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2480]
**Describe the bug**
Presently, when URLs are turned into clickable links in the chat whitespace is not treated as a boundary, meaning if there's a URL in a message (almost) any text after the URL also gets incorporated into it. Not only does this behavior result in a link to a bad URL, but clicking on a link that includes a space in the URL simply doesn't work (though, this itself is a separate issue).

**To Reproduce**
1. Enter `https://www.rptools.net/ some text` into the chat
2. Observe that "some text" gets incorporated into the link, and that clicking on the link will pop up an error and fail to open the link in a browser.

**Expected behavior**
Whitespace characters act as boundaries for URLs.

**MapTool Info**
- Version:  Current develop (and virtually every past version I've used, I think)
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Tested.  Links for URLs in raw text properly stop at trailing whitespace.
