### ISSUE TITLE
playStream failing on MacOS

### ISSUE THREAD

**Issue by Scubba** [RPTools/maptool#2482]
**Describe the bug**
playStream is failing for all the mac users in our gaming group.  It is succeeding for the Windows users.

**To Reproduce**
1. Double check that audio streams are enabled in Preferences... > Sounds > Play Clips and Streams
2. Double check that the MT audio playback is not muted and that the volume slider is 100%
3. Double check that system audio is not muted and set to a comfortable level for other sounds

4. Enter this in the chat window `[r: playStream("https://www.myinstants.com/media/sounds/yesss_1.mp3")]` and hit return
5. Audio will not play.  `1` will be returned in the chat window.

**Expected behavior**
Audio should play.

**MapTool Info**
- Version: 1.8.3, 1.8.4 (same behavior)
- Install: Upgrade from 1.8.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version:  issue seen on 11.2.1, 10.15.7

**Additional context**
We were using the Beta (1.8.0 beta 2) previously and I'm pretty sure it was failing then too.  We were too busy playing to check it out.
I've included Debug Info from one of the problematic systems:
[DebugInfo 1.txt](https://github.com/RPTools/maptool/files/6176162/DebugInfo.1.txt)

**Comment by Scubba** [comment]
Happy to help out with testing, and if given some context for our Java audio playback I might be able to aid in code debugging (I've cloned the repo).

**Comment by pizzystrizzy** [comment]
Also true for linux

**Comment by Phergus** [comment]
Received confirmation it is working on Linux.
https://discord.com/channels/296230822262865920/494598206626463755/840369295580987402
