### ISSUE TITLE
Configure spotless to change formatting options

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#249]
There's an Eclipse config file under `build-resources` that is used by spotless to control reformatting parameters and it contains an option to turn off formatting for block comments (separate from reformatting JavaDoc comments, which I'm in favor of).

Use this issue to discuss any other formatting options you might want to see used by spotless.  Eventually, spotless will be used during every release build to ensure all files are formatted consistently, including ensuring that an up to date license file is included in every source file.

**Comment by JamzTheMan** [comment]
Now that spotless has matured I'm ok with updating it. Comments for sure.

FYI I had tabs as default so if you all want it back to spaces you need to do that. I won't fight it. I can use tabs all day and let spotless put it back...

**Comment by Azhrei** [comment]
I prefer spaces so that files look good when viewed with `less` or `more`, and I can configure my editors as necessary, but I think Craig prefers tabs.

**Comment by Jaggeroth** [comment]
My pitchfork is in the spaces camp ;)

**Comment by Phergus** [comment]
I prefer spaces for much the same reason as Azhrei.  If I want to paste a code snippet somewhere, I don't want 3 levels of indent taking up the equivalent of 24 spaces.

**Comment by Azhrei** [comment]
Alright, here are the options I'm proposing for the spotless configuration:

Block comments will not be reformatted, but JavaDoc block comments will be.
Line length will be set to 80 characters for all formatting.
Comments containing *@formatter:on* and *@formatter:off* will be used.
Multi-line line comments (i.e., those starting with `//`) will be reformatted just as block comments.

Comment here and let me know if you don't like any of the above.  Note that the current Eclipse configuration has a 200-char line length because that's what Trevor liked, so there may be a massive first check in when these changes are made.

**Comment by Jaggeroth** [comment]
Yes, please don't drop to 80. No one uses 80 any more. 100 at least, 120.

**Comment by JamzTheMan** [comment]
at least 120 please, 100 min :)
Wide screens are the shit lol

While you do this, I suggest go ahead and change spotless to space vs tab. Obviously Craig's change to spaces didn't apply to my fork so when I merged back.....

I assume you'll be checking in the eclipse xml for this?

**Comment by Azhrei** [comment]
Argh.  I guess I need to keep my terminal windows wider than 80, huh?  I've never thought about it, tbh.  I just don't like to have to scan so far from left to right! ;)

Yes, I've set the Gradle line to use 4 spaces, but I should check to see if the config file has a setting as well.

Okay, I'll put this in a separate branch and merge it either Sat or Sun, depending on any other input...

**Comment by JamzTheMan** [comment]
k.

All in all, it doesn't matter too much. I'll usually tweak my eclipse formatting anyway so as I code, hit macro to reformat code. Spotless puts it back...

So really, we're just looking for spotless to keep things uniformed in GH for compares and online views.  It's NOT to tell each developer how they should view code AS they develop.

**Comment by Jaggeroth** [comment]
Can't we just use an industry standard. There are two, Oracle and Google.
Most people use the Google Java standard these days.
That would be my preference and you can get eclipse, checkstyle and spotless files for it.
Same for Oracle really, but because Oracle's style has been around since 97 there are loads of different versions.

**Comment by cwisniew** [comment]
I second the call for using an industry standard it makes things much easier as

1. Most of the decisions have already been made and we don't need to waste time discussing.
2. It's already documented so we don't have to waste time documenting it.
3. Settings will already exist for all major IDEs/Text editors.
4. We don't have to maintain spotless config.
5. When a new better tool comes along then someone will have already configured it for the style.

Lets just go for the Google Java style guide -- as it seems to be better maintained than the Oracle one -- and be done with it.

**Comment by JamzTheMan** [comment]
👍

**Comment by Azhrei** [comment]
As long as we agree we're using the (Google Java style guide)[https://google.github.io/styleguide/javaguide.html] only for formatting (§4 and §7, and excluding §4.8.7, for example) and that the last example for formatting comments is just _wrong_ (§4.8.6.1).

I'll get the spotless config set up but won't run it and let @JamzTheMan do it when he does the next RC build (or he might beat me to it; see (this page for the spotless config)[https://github.com/diffplug/spotless/tree/master/plugin-gradle]).  All PRs up to that point will need to be resubmitted because of formatting changes.

**Comment by Azhrei** [comment]
Just saw that Google's style guide recommends 2 spaces for each block level indent and +4 spaces for line continuation.  Is everyone fine with that?  I think 2 is a little small, but as @JamzTheMan pointed out, you can format however you want when editing and just allow **spotless** to "make it all right" again later.  We just need to make sure we tell people they need to run `gradlew spotlessApply` before submitting a PR...

**Comment by Jaggeroth** [comment]
I am fine with that. That's what I use at work.

**Comment by JamzTheMan** [comment]
yep, i'm fine with that as well.
And the CI will fail and yell at you if you don't do a spotless so as long as we reject such PR's until it's fixed...

**Comment by thelsing** [comment]
Noting done for three years closing. Spotless config can be change any time if needed.
