### ISSUE TITLE
Images with size parameter don't scale correctly in HTML5 panels

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2493]
**Describe the bug**
An asset fetched with the `-#` suffix normally scales the largest side of an image to the given value and maintains its aspect ratio. In HTML5/JFX panels (Frame5/Dialog5/Overlay), it scales both dimensions to that size instead.

**To Reproduce**
1. Drop a token (for the following macro, I used the Elf Token in the resource library)
2. Run the following in the chat:
```
[frame("Frame"): { <img src="[r:getTokenImage(100,"Elf")]"> }]
[frame5("Frame5"): { <img src="[r:getTokenImage(100,"Elf")]"> }]
```
3. Observe how in the frame5 the image is stretched.

**Expected behavior**
Images should display the same way across different types of panels.

**Screenshots**
![2021-03-26_16-24-37](https://user-images.githubusercontent.com/59770924/112689245-65b7bc00-8e50-11eb-8dd6-638d8d886b73.png)

**MapTool Info**
- Version: Current develop
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
The source of this issue is that in [`AssetURLStreamHandler.getInputStream()`](https://github.com/RPTools/maptool/blob/a3cbf627869c7926ff719e70829ec0abb1d2e3b8/src/main/java/net/rptools/maptool/client/AssetURLStreamHandler.java#L55) the size value is assigned to both `scaleW` and `scaleH` (which the image is scaled to later if either is > 0). 

I can work on this, but beyond simply fixing the bug, what I'd like to do is add a utility method to handle this stuff to ensure the behavior is consistent (something to just parse the asset URL, maybe scale, and return an image). If there's no objection to this, there's one thing I was wondering about. 

`AssetURLStreamHandler.getInputStream()` uniquely supports height and width query parameters. If support for these is kept, then other HTML panels would support that too (well, without an extra argument to ignore parameters). This seems undocumented and I couldn't find anything internal that takes advantage of this. Left to my own devices I'd opt to just keep the functionality just in case (though, it doesn't strike me as especially useful), but if anyone has any particular feelings about it, let me know.

**Comment by Phergus** [comment]
I don't see any reason to remove the ability to scale width/height independently even if it isn't used currently.  Certainly need to get the HTML5 handling correct.  Moving the scaling ops to a utility method sounds like a good idea to me.

**Comment by Irarara** [comment]
Since we're keeping the query parameters, I was thinking about tweaking the behavior a little bit (also keeping in mind #2334, making it so images are only scaled down). The current behavior in (in `AssetURLStreamHandler`) is a little funny, for instance, ignoring the issue of how `size` is being handled, the query parameters override `size` individually (ex. if you set width=150, but have `100` for `size`, the image will scale to 150x100). Even if you probably wouldn't normally want to be mixing them it seems a little unintuitive (and then there's how 0 and -1 for the query params do different things).

My thought right now is that if `size` and query params are both present (for some reason), the query params will take precedence over `size`, but fall back on `size` if they're invalid. All parameters will expect a value between 1 and the native size of the image (the largest side, in the case of `size`), any parameter that is invalid gets ignored, and aspect ratio will always be maintained unless width and height are both set.

**Comment by Phergus** [comment]
That all seems reasonable to me.

**Comment by Azhrei** [comment]
I love the idea of parameters!  A different issue was filed for a way to render a token with all states and/or health bars included, and a parameter that allows for that would make creating such images easy (and useful for character sheets or custom initiative panels).  I can also see overlays or underlays being future options as well.

I'm wondering if invalid parameters (such as a string when a number is expected) would be better represented as the "broken" image.  Otherwise, it might be difficult to determine why an image isn't being shown the way the scripter expects.  Opinions?

**Comment by Irarara** [comment]
> I'm wondering if invalid parameters (such as a string when a number is expected) would be better represented as the "broken" image. Otherwise, it might be difficult to determine why an image isn't being shown the way the scripter expects. Opinions?

@Azhrei I was kind of wondering that myself. My initial thinking was just that it'd be nice if things just worked uhh, smoothly, so you still get something out even if there are some bad values, but it's definitely true that it's less obvious when something is wrong (and what is wrong). On top of that, like the `size` param they probably wouldn't be parameters people would normally be using by hand (I assume), so the input could be validated in macro functions that use them if necessary, so maybe it would be better if a broken image was just returned if any are invalid. 

One exception to that though would be the max value of the scale params (though I dunno if you were this when thinking of invalid parameters). I was kind of thinking it'd make sense to only allow scaling down (because there needs to be some positive constraint, and the alternative is setting some arbitrary one, plus the scaling algorithm doesn't scale things up that nicely*), but if a scale value greater than the native size of the image would make it return a broken image, there would be some issues. I guess, after all, the simplest answer would be just to return the unscaled image if the scale width or height are too large. 

\* Though, this could be improved a bit I think.

**Comment by Azhrei** [comment]
> plus the scaling algorithm doesn't scale things up that nicely

The algorithm can YAP (yet another parameter).  That at least lets the script writer decide which one they want...

**Comment by Irarara** [comment]
True! That'd be very doable. Though in this case, for nicer upscaling it feels like it'd be enough to just use bicubic interpolation exclusively when scaling up (if scaling up was kept).

**Comment by Phergus** [comment]
Tested.  Images scale correctly in HTML5 frames/dialogs/overlays now.
