### ISSUE TITLE
An asset with an empty ID ("") will be stuck as transferring

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2506]
**Describe the bug**
If the `src` of an `img` points to an asset URL that is empty (ie a string of just `asset://`) the asset will get stuck as transferring and never update. This will also make `ImageManager.getImageAndWait()` hang.

**To Reproduce**
1. Enter `<img src="asset://">` into the chat window.
2. Observe that it displays `TRANSFERING_IMAGE` (the question mark), indicating that it is stuck transferring.

**Expected behavior**
An asset with a empty ID should be marked as broken, like any other invalid ID.

**MapTool Info**
- Version: Current Develop
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
The issue is ultimately because of this:
https://github.com/RPTools/maptool/blob/98cdf98188d2eb6de7724199af7af2c53b9a9d9e/src/main/java/net/rptools/maptool/server/ServerMethodHandler.java#L440-L443

Doing an early exit if the id is empty causes the asset to never update to broken. The simplest fix would be to just remove that part of the condition, and as far as I can tell does not introduce any issues (trying to fetch something with an ID of `""` will resolve the same way any other invalid ID does).

**Comment by Phergus** [comment]
Reviewed.
Before:
![image](https://user-images.githubusercontent.com/34379254/113294058-c6615180-92b3-11eb-849e-675e6726cc50.png)

After:
![image](https://user-images.githubusercontent.com/34379254/113294318-104a3780-92b4-11eb-8f99-20eede944506.png)
