### ISSUE TITLE
Unreachable servers in IP check list can cause long delays in starting servers

### ISSUE THREAD

**Issue by dorpond** [RPTools/maptool#2509]
**Describe the bug**
If one of the servers located in ip-check.txt is off-line or unreachable, MT server start time or client connection times become delayed at the same interval as the website timeout, so if the website timed out in 20 seconds, the client connection would take 20 seconds longer.
https://github.com/RPTools/maptool/blob/develop/src/main/resources/net/rptools/maptool/client/network/ip-check.txt

My Journey to determine this:
I noticed that when I started a server at my corporate workplace, the server start process was delayed - I would start the server, and it would take about 20 seconds for the "Server started; please wait for map to refresh" to display in chat. That was the first out of the ordinary observation that something felt wrong. 

The second observation was when I tried connecting to that host via a client (Host and Client on the same PC) via LAN and I clicked the OK button to connect; the button would just show depressed, like MT was locked up, and 20 seconds later, the connection window would finally close and it would then tell me I connected. 

I did an IP Lookup against all those servers listed in ip-check.txt, and all but one were reporting my IP instantly; this one was timing out, unable to contact the server :
http://bot.whatismyipaddress.com/

Other people on the team were able to contact that server fine however, but for some reason, that site didn't like my current network, and timed out.

As a test, I put this entry into my hosts file (below), which is pointing bot.whatismyipaddress to the ip address of the http://checkip.amazonaws.com/ site, and by eliminating that timeout, Maptool works just fine, without any delays.

18.233.3.145	bot.whatismyipaddress.com

**To Reproduce**
Force a failure of one of the server IP Lookups, by adding this entry into your Hosts file:
1.3.5.4		bot.whatismyipaddress.com
(Be prepared to wait 4 minutes for the server to start and 4 minutes to connect to the server, but this will give you a clear picture on how MT stalls, especially when connecting to a host).

**Expected behavior**
MT should be smarter when checking against that list. Currently our server connectivity speed depends on the integrity of several servers we have no control over, so we need to make MT a little more smarter when checking against the ip-check.txt list.

MT just chokes currently until the website times out, like it is locked, so maybe should we have a message "please wait while we try to connect to that server" or have a spinning wheel showing that MT is trying to connect, instead of acting like it is locked up?

Phergus stated the following in Discord:
"Currently it goes through the full list but isn't doing any actual comparisons against previous results the last successful check is the one that is used.  Should probably just bail out once it gets a valid result."

Azhrei stated the following in Discord: 
"obvious solution is to do all queries in parallel and use the first successful return."

**MapTool Info**
- Version: 1.8.3 and 1.8.4 (problem does no exist with 1.5.6 or 1.7.0). I am unable to test any other versions.
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version [20h2]

**Comment by Irarara** [comment]
This is the same issue as #2684, right? So this should be fixed with #2685.

**Comment by Phergus** [comment]
OBE - Fixed by #2685.
