### ISSUE TITLE
setTablePickOnce() without doing resetTablePicks() causes an error

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#2510]
I took a table created before this feature and ran setTablePickOnce() to it. I could no longer access the table with the Edit button and when running `[H: table(tableName)]` it gave me the following error
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "entry.picked" is null error executing expression table("Harrow Data").
```
The problem fixed itself when I ran resetTablePicks()

I'm thinking once one of the Pick Once functions is ran for an uninitialized table, it should reset the table automatically to avoid this error and locking out the client from the table.

**Comment by Phergus** [comment]
Please follow the templates.

**Comment by aliasmask** [comment]
fyi, the template page didn't come up for me. I clicked new Issue, then it had me log in, then it sent me to issue entry without any templates.

**Comment by Phergus** [comment]
If you follow the sign-in link from that pop-up it bypasses the template chooser.  Will have to check if Github has a issue open for this.
