### ISSUE TITLE
"return(0,0)" does not return if "macro.return=1" has been set by a previous statement or macro/udf call.

### ISSUE THREAD

**Issue by SherbanWisperwald** [RPTools/maptool#2513]
**Bug Description**
The following code snippet aborts with "must not happen" but should never reach the assert:

```
[h: macro.return = 1]
[h: return(0, 0)]
[h: assert(0, "must not happen")]

```
This is not real code, but a boiled down sample of minimum lines to show the error.

**MapTool Info**
Version 1.8.4 (new install) shows this bug, 1.8.3 works as expected.

**Desktop**
 - Linux [Gentoo]

**Additional Info**
Replacing the first line with  `[h: macro.return = 0]` or `[h: macro.return = 2]` or `[h: macro.return = "anything not == 1"]` or replacing it with a call to another macro/UDF (wich does not set macro.return=1) works as I expect, i.e not failing with "must not happen".

**For the curious**
The real code which runs into this error is:

```
[h: '<!-- ==== void switchToCurrent() ==== -->']
[h, if(she_isDebug()): she_debug(getMacroName())]

[h: currentKey = "activeName_" + getPlayerName()]

[h: "<!-- check Library -->"]
[h: selected = getLibProperty(currentKey, "Lib:sheSettings")]
[h, if(she_hasTokenRights(selected)), code: {
    [switchToken(selected)]
    [return(0, 0)]
};{}]

[h: "<!-- check Impersonated -->"]
[h: selected = getImpersonated()]
[h, if(she_hasTokenRights(selected)), code: {
    [switchToken(selected)]
    [setLibProperty(currentKey, selected, "Lib:sheSettings")]
    [return(0, 0)]
};{}]

[h: "<!-- check Selected -->"]
[h: selected = getSelected()]
[h, if(listCount(selected) == 1 && she_hasTokenRights(selected)), code: {
    [switchToken(selected)]
    [setLibProperty(currentKey, selected, "Lib:sheSettings")]
    [return(0, 0)]
};{}]

[h: assert(0, "Kein Token verk&ouml;rpert oder ausgew&auml;hlt!")]
```

The UDF `she_hasTokenRights(selected)` returns true (by setting its macro.return=1), the "true" branch of the if gets executed, but `return(0,0)` did not return. In fact all "true" branches get executed, all `return(0,0)` get executed but did nothing and finally the assert throws its error. This was quite tricky to pin down ;-), because if any other macro/UDF (e.g. `she_debug("something")`) which does not return "1" is called before `return(0,0)` everything works. I assume that's because the UDF "she_debug" does not set "macro.return" at all and thus apparently clearing it.

**Comment by MeloDub** [comment]
I'm working on this.

**Comment by Phergus** [comment]
Quick and dirty test campaign.
[Return Function Test.cmpgn.zip](https://github.com/RPTools/maptool/files/6288826/Return.Function.Test.cmpgn.zip)

**Comment by MeloDub** [comment]
I've tested your campaign file both with and without my fix. It seems that everything works as in version 1.8.3, the only difference is that when return(0) is called it doesn't throw any error in chat (as it was meant with the fix for issue #2441).

**Comment by Phergus** [comment]
My results in 1.7.0 and 1.8.4.

Macro | Code | MT 1.7 macro() | UDF | MT 1.8.4 macro() | UDF
-- | -- | -- | -- | -- | --
T1 | `[r: return(0)]` | Null | NPE | null | NPE
T2 | `[r: return(1)]` | 1 | 1 | 1 | 1
T3 | `[r: return(0,"T3 Ret Value")]` | T3 Ret Value | T3 Ret Value | T3 Ret Value | T3 Ret Value
T4 | `[r: return(1,"T4 Ret Value")]` | 1 | 1 | 1 | 1
T5 | `[h: macro.return = "t5 return"][r: return(0)]` | Null, `macro.return` undefined | NPE | Null, 0 | NPE
T6 | `[h: macro.return = 1][r: return(0,0)]` | 0,0 | 0,0 | “”, 1, Didn't return | "", 1, Didn't return

As you can see the T1 case in both MT versions is wrong.  T5 & T6 cases are the problems reported in this issue.  Have not tested against your fix.

**Comment by MeloDub** [comment]
These are the results after my fix:

| Case | macro() | UDF |
| ------- | ------------- |-----|
| T1       | null               | NPE |
| T2       | 1                   | 1 |
| T3       | T3 Ret Value | T3 Ret Value |
| T4       | 1                   | 1 |
| T5       | null               | NPE |
| T6       | 0, 0               | 0, 0 |

In the T5 case I'm not really sure how to see what's in the `macro.return` variable, i tried to modify the `Call T5` macro adding `[macro.return]` and a pop up appears asking the user to enter the `macro.return` value, I don't know if it's a valid test.

**Comment by Phergus** [comment]
Putting `[macro.return]` after the macro call is the only way to test and the pop-up is telling us that it is undefined.  I would expect that any time a macro uses `return(0)` to exit prematurely that `macro.return` should be set to either 0, the optional return value or if `macro.return` has already been set then that value.

Currently it appears to be pretty inconsistent as to whether `macro.return` will be set and what that value will be.  Depending on the continue parameter you might get 0, 1, an empty string or sometimes the value that `macro.return` was set to in the called macro.

**Comment by Phergus** [comment]
@MeloDub are you going to be able to get a fix in for the NPEs when used in UDFs?  Expecting to release 1.8.5 tomorrow.

**Comment by MeloDub** [comment]
I didn't have much time to look into that, but after a quick inspection, it seems that the error is thrown at line 147 of `UserDefinedMacroFunctions`:

`String stripOutput = output.replaceAll("(?s)<!--.*?-->", ""); // Strip comments`

Since `return(0)` doesn't have any output, `output` is null and a NPE is thrown. This does not happen if I modify the T1 macro as `return(0, 0)` because then "0" is returned as the output of the function.

A possible fix I've tried is to check if `output` is null before the replaceAll() call and return an empty string in that case. 

This fixes the NPE and the UDF ends without errors, do you think this is an acceptable solution or may there be cases in which this is not a correct choice?

**Comment by Phergus** [comment]
> This fixes the NPE and the UDF ends without errors, do you think this is an acceptable solution ...

Getting rid of the NPEs is at least a workable solution and if different return values are needed they can be dealt with after this.

**Comment by Phergus** [comment]
Tested.  Original issue with with `return(0,0)` not returning if `macro.return` was set to `1` has been corrected.  No NPEs seen with any of the test cases from above.   Same tests run directly in chat run without error and produce same results as macro buttons.

Some output is inconsistent between `macro()` and UDF calls (yellow).  Having `macro.return` undefined after call to a macro with `return()` may cause issues for some uses.
