### ISSUE TITLE
Windows installer removes other versions of MapTool

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2522]
**Describe the bug**
The windows installer removes the old version of MapTool making it impossible to use it to install more than one version at the same time.

**To Reproduce**
Use the installer it install a different version than the one you currently have installed.

**Expected behavior**
The installer should not remove the old version but allow the new version to be installed alongside it.

**Desktop (please complete the following information):**
Windows

**Comment by Phergus** [comment]
Tested.  Builds get new UUIDs now.
