### ISSUE TITLE
Deprecation warning when starting experimental webapp server. 

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2524]
**Is your feature request related to a problem? Please describe.**
The experimental webapp server is deprecated and users that use it should be informed this is the case. 
Users should also have more visible feedback that the server will be started.

**Describe the solution you'd like**
A new popup dialog to be displayed letting the user know that the webapp server will be started and allow them to cancel before the server is started. This dialog should also contain information about the deprecation (as well as this information being sent to the chat window).

**Additional context**
A Discord channel has been set up to collect information from users that use this functionality to discuss what they use it for so that we can incorporate this into a future replacement. The message should contain a link to this channel

**Comment by JoeRLDuncan** [comment]
It would be nice to keep at least some of this functionality. 

I'm working on a "lib:session" macro module for JUH alpha 3 that provides key/value pair nosql storage based state for maptool, using the WebAPI and RESTful functions.

**Comment by Phergus** [comment]
Starting the webapi brings up a warning dialog and also sends additional information to chat.
![image](https://user-images.githubusercontent.com/34379254/115943664-7dde2380-a46e-11eb-91cf-c79976b2708d.png)
Chat:
![image](https://user-images.githubusercontent.com/34379254/115943674-99492e80-a46e-11eb-89d2-6416da621683.png)

**Comment by Phergus** [comment]
Tested.  Webapp server starts and functions as before.
