### ISSUE TITLE
Add Icons representing non picture asset types.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2526]
**Is your feature request related to a problem? Please describe.**
Add icons for supported non picture asset types that are dragged on to the map.

**Describe the solution you'd like**
When supported non picture assets are dragged on to the map they should be represented with an icon indicating their type rather than a large red X.

**Comment by Phergus** [comment]
Supported types from #2528 :
-  audio/*
-  text/html
-  text/markdown
-  text/plain
-  application/pdf
-  text/javascript?
-  text/css

**Comment by Phergus** [comment]
Icons like these or something more MapToolish?
![FileTypesIconPack](https://user-images.githubusercontent.com/34379254/115088753-2409b680-9ece-11eb-94fb-9274778ffc5e.png)
https://www.deviantart.com/txusmetal4ever/art/File-Types-Icon-Pack-739291476

**Comment by Phergus** [comment]
Entirely with CSS?
![icons](https://user-images.githubusercontent.com/34379254/115089429-71d2ee80-9ecf-11eb-8dfc-67254e3a5fd3.png)

https://github.com/colorswall/CSS-file-icons

**Comment by FullBleed** [comment]
I think these rectangular icons on a map would be pretty ugly and would feel out of place in MT.  Using the default MT gear icon with a standard three character identifier in the center on a color-coded background (if desired) would look better.  I'd could go ahead and put together the needed icons if desired (providing a .psd for easy future file type add-ons.) 

That said, the only base image files for the RPT logo I have are here though: https://forums.rptools.net/viewtopic.php?f=6&t=23235&p=238231#p237261

I assume that there is a base, gear-only, image without the interior images somewhere.  If not I can recreate or strip one of these out.

**Comment by Phergus** [comment]
> Using the default MT gear icon with a standard three character identifier in the center on a color-coded background (if desired) would look better.

Agreed.  I think we have the base gear image around somewhere.  Will have to take a look tomorrow.

**Comment by michaelperino** [comment]
Is this the gear psd you were looking for? Or did you want the actual filled in one from the top of the website (https://www.rptools.net/wp-content/ata-images/header/RPTools.png)?

https://github.com/RPTools/TokenTool/blob/main/other-resources/Overlay%20Templates/Gear%20Overlays.psd

**Comment by FullBleed** [comment]
Was looking for the PSD, thanks for the links.  :)

**Comment by FullBleed** [comment]
So first draft of a template for an asset icon.  Thoughts?

![MT-PDF-screen (wip)](https://user-images.githubusercontent.com/37131742/118088953-d3cf2880-b395-11eb-8bb0-909756589eeb.jpg)

**Comment by michaelperino** [comment]
Sorry I couldn't track down a gear psd with better than 256x256 size!

I see where you're coming from about the style difference, but I also think there's a certain bloat involved with maintaining an image library for each file type instead of something that could be more easily generated. Someone could easily add something like CSV support to the list Phergus supplied above and then someone needs to spend time figuring out how you represent a CSV with an image and then the licensing for whatever image they find online. 

Something for your consideration that I found while searching was this image. Not positive on the licensing and one without a d20 would be needed anyway, but I think the style would fit in nicely for many campaigns.

https://www.deviantart.com/darthiraecorpus/art/Dungeons-and-Dragons-Golden-d20-Leather-Folder-Ico-710911224

**Comment by FullBleed** [comment]
256x256 might actually be more rez than is desired.  But that is a up for consideration.  The 256x256 PNG of the image shown above is 61kb.  100x100 comes in at 19kb.

I expected to make the PSD "template" available, so producing new file type icons should be pretty easy.  Drop an image into the gear (or use a supplied generic one), apply a common layer style to it, then merely edit existing text.  Should be pretty quick.

But any image can be used--like the folder you found.  Though, that will still offer the same "bloat" if you have a variant for each file type.  And whether that variant has a standard file type icon on the folder or just standard text  (i.e. "PDF") is simply a matter of effort.  I do like that folder image... but, it is a folder (which generally indicates a link to a group of files, not just one.) *shrug*

I opted to keep the gear asset icon pretty neutral, but it's still a chrome gear and will stand out on anything organic.  Nothing is going to work perfect for everyone's campaign and we need to keep in mind that if someone doesn't like any default image they can certainly change it to something better suited to their sensibilities.

We can also get more custom for each file type if desired.  But I think something fairly standardized works for most of those file types... with the exception of maybe a musical note for audio, a book for PDF, and something like a sheet of paper or scroll for plain text.

Anything is better than the red X or one of those generic desktop icons.  ;)

**Comment by Phergus** [comment]
Pretty sure that PSD is something that Jamz "reverse-engineered" from one of the PNG logo files and converted for TokenTool.  The originals were created by Eddy "mosat" Anthony and though folks have searched for the PSD files I don't believe they have been found.  The PNG versions can be found here:

https://github.com/RPTools/rptools-logos

We should probably move to lossless WebP for the images included with MapTool as that will cut file size down quite a bit.

**Comment by Azhrei** [comment]
I got in touch with RPMiller (who did the originals) and he has found his original multilayer PSD files.  I've asked him to chime in here, but if he doesn't, I will follow up with him by email to get a zip file.

**Comment by RPMiller1** [comment]
Hello everyone! Long time no participate in RPTools fun. I do indeed have all my original artwork and PSD files and would be more than happy to put some icons together for you. I work full time as an Implementation Engineer for a software company, so my availability tends to be kind of all over the place depending on if I am traveling or working remotely. But, I do have bouts of "downtime" where I can work on this.

**Comment by Phergus** [comment]
@RPMiller1  Long time indeed.  If you like, the GitHub repo for the logos is linked above and you could push up any files you think we should have.

**Comment by RPMiller1** [comment]
Is there a list of the file types that you would like icons for? What resolution would you like them to be?

**Comment by Phergus** [comment]
#2527 has lists of asset types that are supported for drag-n-drop so that's a pretty good start.

**Comment by RPMiller1** [comment]
What pixel size do you want for these?

**Comment by RPMiller1** [comment]
![RPTools_HTML_Logo](https://user-images.githubusercontent.com/29924417/118200657-84770f80-b40a-11eb-9f91-bca5887877d5.png)
Yes, no, maybe with modifications? Let me know.

**Comment by Phergus** [comment]
> What pixel size do you want for these?

My opinion is that they should be at least 256 px but they do need to be recognizable when used on grid sizes down to 100 or even 50 which is still the default for MapTool.

**Comment by RPMiller1** [comment]
> > What pixel size do you want for these?
> 
> My opinion is that they should be at least 256 px but they do need to be recognizable when used on grid sizes down to 100 or even 50 which is still the default for MapTool.

Unfortunately, I don't have MapTool setup on either of my machines. Can someone test the above and see if they work at the smaller sizes? Those were made at 150 pixels/inch at the size is roughly 400x400 px.

**Comment by RPMiller1** [comment]
![RPTools_Plaintext_Logo](https://user-images.githubusercontent.com/29924417/118206062-9b236380-b416-11eb-8c6d-fe32a8d52b07.png)

This one was a little tough, strangely enough. I'm not sure I like it 100%, so feel free to offer criticism. If anyone has a better black SVG file for a plain text logo, I would be happy to use it.

**Comment by Phergus** [comment]
Here they are on a 50px grid and also sized at 100px.  Definitely hard to make out at 50 but usable at 100 except for the text icon.  Maybe fewer but heavier lines?  I think this is why you see so many icon sets incorporate a text label as well in the image.

![image](https://user-images.githubusercontent.com/34379254/118206425-bba3eb80-b41f-11eb-97a0-1215c5922f59.png)

**Comment by Phergus** [comment]
BTW, one of the nice things about the current MapTool releases is that they have their own Java bundled in with them so you don't have to do anything but install them.

**Comment by RPMiller1** [comment]
I can slap a text label on them as well like you have in the icon pack you posted above. Want me to give that a go? Maybe centered at the bottom on top of the gear?

**Comment by RPMiller1** [comment]
> BTW, one of the nice things about the current MapTool releases is that they have their own Java bundled in with them so you don't have to do anything but install them.

Very nice! I'll have to check it out. Been forever since I've played in a VTT.

**Comment by Phergus** [comment]
> I can slap a text label on them as well like you have in the icon pack you posted above. Want me to give that a go? Maybe centered at the bottom on top of the gear?

Probably bottom or offset like in Full Bleed's example above.

I'm also thinking that maybe it is just time for MapTool to make the default grid size 100 and make that the target for "readability".

**Comment by RPMiller1** [comment]
![RPTools_PDF_Logo](https://user-images.githubusercontent.com/29924417/118212908-cb243400-b421-11eb-9e17-8660355469d6.png)

Label makes a difference.

**Comment by RPMiller1** [comment]
![RPTools_Markdown_Logo](https://user-images.githubusercontent.com/29924417/118213620-2acf0f00-b423-11eb-87ea-a5dabe3780c6.png)

**Comment by RPMiller1** [comment]
![RPTools_HTML_Logo](https://user-images.githubusercontent.com/29924417/118213912-b47edc80-b423-11eb-9fd6-b75777f1a26d.png)

**Comment by Azhrei** [comment]
+1 to all of the above (100px default grid, text label, fewer/darker lines for Plain Text).

These are looking great, and the text in the corner definitely helps. :)

**Comment by RPMiller1** [comment]
![RPTools_Plaintext_Logo](https://user-images.githubusercontent.com/29924417/118214969-974b0d80-b425-11eb-87d2-66cda038cf0d.png)

**Comment by RPMiller1** [comment]
![RPTools_JSON_Logo](https://user-images.githubusercontent.com/29924417/118215850-3cb2b100-b427-11eb-9dea-b0dd72571dcd.png)

**Comment by Phergus** [comment]
Much more readable even on the current default of 50px.
![image](https://user-images.githubusercontent.com/34379254/118275517-c09a8680-b483-11eb-9e3b-532e04d71bca.png)

**Comment by RPMiller1** [comment]
Thanks for the preview Phergus. I'm hoping to finish up the rest today as I have a couple blocks of time.

**Comment by Phergus** [comment]
Looking forward to seeing them.

**Comment by RPMiller1** [comment]
![RPTools_JS_Logo](https://user-images.githubusercontent.com/29924417/118300415-be8df300-b496-11eb-964a-bc58f3f84435.png)

**Comment by RPMiller1** [comment]
![RPTools_FileType_Logos](https://user-images.githubusercontent.com/29924417/118301571-15e09300-b498-11eb-80fb-55c2c21b4d26.png)

**Comment by RPMiller1** [comment]
![RPTools_MP3_Logo](https://user-images.githubusercontent.com/29924417/118318427-3ca9c400-b4ae-11eb-9236-b8dadff850ec.png)

**Comment by RPMiller1** [comment]
![RPTools_Ogg_Logo](https://user-images.githubusercontent.com/29924417/118323314-45ea5f00-b4b5-11eb-8df2-ce3ee3026fac.png)

**Comment by RPMiller1** [comment]
![RPTools_M4A_Logo](https://user-images.githubusercontent.com/29924417/118325523-7384d780-b4b8-11eb-8a48-39a2c30c1b4c.png)

**Comment by FullBleed** [comment]
Is there a reason we should have multiple icons for various sound file types?

I think a single "Musical Note" symbol would be best for them.  I don't think we need to use the Gear ring for that.  It's more on-brand for the other file types that would otherwise looks alien, but not a musical note.

And that a GH issue should go up for a functional pull of the file types associated with a token asset:  Something like getAssetType()

(i.e. We should also get a getAsset() function that will pull the ID of a non-image function since using the getImage() "hack" should be associated with/limited to image types.)


PS:  I'd also like to make a couple other aesthetic suggestions because I think it makes these look a lot better on map.

a) Set the background colors to 40% Opacity (for a total of 60% transparency.)
b) Slip the token type Icons behind the central highlight (you might need to cut down on the highlight intensity by at least half.)

I think this makes that central "eye" look like glass and grounds the icon to the page better.

**Comment by RPMiller1** [comment]
By the way, I'm just picking random colors for these if there isn't an "official" color for me to pull from, so feel free to ask for different colors. Also, I'm trying to use the "official" logos if I can find one, and if I can't find one, I'm just tossing something in that will work. So, just like with the colors, if you prefer a different logo, send me something to use instead. These three are not official logos.

![RPTools_M4A_Logo](https://user-images.githubusercontent.com/29924417/118326028-340abb00-b4b9-11eb-8b3c-17bd6ed97f22.png)
![RPTools_WAV_Logo](https://user-images.githubusercontent.com/29924417/118331411-77ffbf00-b4bd-11eb-9daf-971c415d6d19.png)
![RPTools_AIFF_Logo](https://user-images.githubusercontent.com/29924417/118333142-12610200-b4c0-11eb-9fed-64198747fbac.png)

**Comment by RPMiller1** [comment]
> Is there a reason we should have multiple icons for various sound file types?

I was wondering that same thing, but just going off the list Phergus pointed me to.

> I think a single "Musical Note" symbol would be best for them. I don't think we need to use the Gear ring for that. It's more on-brand for the other file types that would otherwise looks alien, but not a musical note.

So, just the note by itself?

> a) Set the background colors to 40% Opacity (for a total of 60% transparency.)

There is actually solid color behind the central color, so I'll need to punch a hole through it. I'm assuming you are looking to have the map elements be semi-visible behind the "eye"?

> b) Slip the token type Icons behind the central highlight (you might need to cut down on the highlight intensity by at least half.)
> 
> I think this makes that central "eye" look like glass and grounds the icon to the page better.

You are 100% correct, and I don't know why I didn't notice that sooner. I thought that that was the way I was making them years ago, but apparently I accidentally dragged the layer group up. That's an easy fix and I can make that when I make my next pass through these. I wanted to bang these out for feedback. Thank you for those suggestions!

**Comment by Phergus** [comment]
I meant to leave a note about using a single icon for audio files but it apparently never made it out of my head and down to the keyboard.

Then you did several and I was like well maybe folks would like a visual cue to distinguish between audio file types.  But if going for a single icon style, I would prefer the double 8th note version.  Seems more active.

**Comment by FullBleed** [comment]
> There is actually solid color behind the central color, so I'll need to punch a hole through it. I'm assuming you are looking to have the map elements be semi-visible behind the "eye"?

I  was hoping it was it's own layer and just required a single 40 opacity set.  So doing it is up to you.  I think it looks pretty slick.

Here is my png mock for comparison if you want to move it around and see what I mean.

![MT-PDF (wip)](https://user-images.githubusercontent.com/37131742/118336326-70e9a880-b4df-11eb-9642-f4444fd46ea4.png)

Oh, and FYI, I don't know if there is some universal color code for file types/groups.  The coder types may have a preference.

**Comment by RPMiller1** [comment]
> I was hoping it was its own layer and just required a single 40 opacity set. So doing it is up to you. I think it looks pretty slick.

It shouldn't be difficult to make happen. I'll do one and see what you think.

> Here is my png mock for comparison if you want to move it around and see what I mean.
> 
Saw this above. Looks good. I see now that you have a gradient on the text background and an outline on the letters. Looks sharp.
> 
> Oh, and FYI, I don't know if there is some universal color code for file types/groups. The coder types may have a preference.

For the colors, I used a color(s) from the official source if there was one--such as a background color or logo color. Others were just a random choice to try to spread out the colors a bit. But as I said, I'm happy to make any adjustments you all want me to make.

**Comment by RPMiller1** [comment]
> I meant to leave a note about using a single icon for audio files but it apparently never made it out of my head and down to the keyboard.
> 
> Then you did several and I was like well maybe folks would like a visual cue to distinguish between audio file types. But if going for a single icon style, I would prefer the double 8th note version. Seems more active.

So, do you want just the music note, or do you still want it in the gear? And for the label make it "AUDIO"?

**Comment by FullBleed** [comment]
I don't think it needs the label for audio.

**Comment by Phergus** [comment]
> So, do you want just the music note, or do you still want it in the gear? And for the label make it "AUDIO"?

Personally I like having it with the gear but others may feel differently.  Don't know that we need a label but it wouldn't bug me to have one either.

@cwisniew @Azhrei  @rkathey - Opinions?

**Comment by RPMiller1** [comment]
I put in the transparency and removed the audio label and moved the highlight layer back to where it should be. Let me know what you think.

![RPTools_Audio_Logo](https://user-images.githubusercontent.com/29924417/118337976-db8fe980-b4c9-11eb-813f-2f219e5e3d2f.png)

**Comment by Azhrei** [comment]
My only input is to keep color blindness in mind.  That's one reason why I like the little text overlay in the corner.

**Comment by FullBleed** [comment]
Can't see any transparency... I think you lost it during flattening or something.

**Comment by FullBleed** [comment]
> 
> 
> My only input is to keep color blindness in mind. That's one reason why I like the little text overlay in the corner.

Unless someone comes along and indicates that color categories are important for grouping of certain asset types I don't think the color choices matter.  I do see three obvious groups (Audio, Text, Application) ... but there may be other groupings that people want... or a desire for each to have a unique color....

At any rate, here are some color blind friendly palettes :  http://mkweb.bcgsc.ca/colorblind/palettes.mhtml#page-container

**Comment by RPMiller1** [comment]
> Can't see any transparency... I think you lost it during flattening or something.

That's odd. I didn't do any layer flattening or anything. And just checked in PS and it is still transparent. The only thing I did was export as a PNG. Is it transparent around the outside? Then it should be on the inside.

**Comment by RPMiller1** [comment]
> Unless someone comes along and indicates that color categories are important for grouping of certain asset types I don't think the color choices matter. I do see three obvious groups (Audio, Text, Application) ... but there may be other groupings that people want... or a desire for each to have a unique color....

I'll take whatever suggestions you all want. If you want me to color by type or whatever, just let me know what you want to see.

**Comment by FullBleed** [comment]
> > Can't see any transparency... I think you lost it during flattening or something.
> 
> That's odd. I didn't do any layer flattening or anything. And just checked in PS and it is still transparent. The only thing I did was export as a PNG. Is it transparent around the outside? Then it should be on the inside.

Then you might need to merge visible and toss out extraneous layers before you export to PNG.  I always do that to test how final compositing looks.  There is no transparency inside the ring on current export.

**Comment by RPMiller1** [comment]
Found the problem. Not sure how or when it happened, but apparently I reset the opacity back to 100% at some point on the texture layer. All fixed now.
![RPTools_Audio_Logo](https://user-images.githubusercontent.com/29924417/118344749-d4c2a000-b4e4-11eb-911a-78c3953a87df.png)

**Comment by RPMiller1** [comment]
I'll do another export of all the above once you all approve the icons, colors, etc. I will be available tomorrow, but Sunday I'll be busy preparing to travel, and then I likely won't be available again until Thursday or Friday of next week.

**Comment by FullBleed** [comment]
I'd like the musical note to stand out more.  Should probably be a different color.  For some reason I keep seeing something on the bluish spectrum in my mind's eye, but white will work if neutrality is desired.  Black it's really not discernible on most maps I've tested it on (unless it's a really light background.)  I don't care much about the other icons being black since they have text and the pictures are somewhat arbitrary... the sound icon, however, is likely to be the most common icon of the bunch.

Don't suppose you have a black chrome gear do you?  I wonder what that would look like with white/blue for the sound icon.


On the spec side:
Adding that transparency blew the size of the png up 3 fold (from 137K to 373K).  It looks better to me, but not sure if the footprint is an issue.

And, we might want to go with a more standard size (400x400 instead of 403 x 403).

**Comment by michaelperino** [comment]
I think the most recent variation is pretty solid. While it doesn't necessarily pop out, it's pretty clearly a music note on most backgrounds IMO. Plus, if there is all black icons and then a random blue sound icon, that will look extremely odd. 

![image](https://user-images.githubusercontent.com/33206261/118354480-dfa32200-b530-11eb-8679-5c2bca6c0da3.png)

As for getting it to 400x400 there's some extra pixels on all sides to work with if you wanted to crop them yourself. If any are removed they should probably be taken from the right since the gear center might currently be based on the shadow.

![image](https://user-images.githubusercontent.com/33206261/118354654-afa84e80-b531-11eb-957e-4b4de9a39bde.png)

**Comment by Phergus** [comment]
Maybe changing the background of the audio icon to a light blue would let it pop more.  Without the transparency it stood out just fine.

re: file size - we'll probably go to WebP for the images which drops the transparent audio icon down under 100k.

re: image dimensions - getting them to a consistent 400x400 with the gear centered would be best and it seems like there is plenty of space to do that.

**Comment by RPMiller1** [comment]
Yup. Easy to do whatever you all are thinking. Just need some decisions. I can easily change any aspect of it. Everything is on their own layers and I use adjustment layers and masks to make nearly everything, so pretty easy to make adjustments with minimal effort.

**Comment by RPMiller1** [comment]
I've made the following changes:

- resized to 400x400
- changed the background to blue
- saved it to a more compressed size
- reduced the highlight opacity to allow the icon to come through more

![RPTools_Audio_Logo](https://user-images.githubusercontent.com/29924417/118373752-34fd2480-b56d-11eb-80a3-46e57562233f.png)

**Comment by RPMiller1** [comment]
I've made the following changes:

- Resized to 400x400
- Changed the background to blue
- Saved it with the smallest file size
- Reduced the highlight in the top left to allow the icon to come through more
![RPTools_Audio_Logo](https://user-images.githubusercontent.com/29924417/118374242-d1c0c180-b56f-11eb-8d22-4fab6ec3d8f6.png)

**Comment by Phergus** [comment]
I think the reduced highlight is a good choice.  Was a bit overwhelming before.

The darker shade of blue probably works the best when put on the various default MT textures.

**Comment by FullBleed** [comment]
Sample on typical "mid-tone" map.

Asset token inside and outside FoW.

![mapuse](https://user-images.githubusercontent.com/37131742/118376496-3131c800-b596-11eb-953d-cf206d752ba8.jpg)

**Comment by RPMiller1** [comment]
Would you like me to go back and adjust the other tokens in this same fashion?

**Comment by Phergus** [comment]
Yes, please.

**Comment by RPMiller1** [comment]
For the colors, do you want the lighter or darker version of the color?

**Comment by Phergus** [comment]
Darker is my vote.

**Comment by RPMiller1** [comment]
I made a couple more adjustments and wanted your feedback. Let me know what you think regarding the text label on this. Does it look better or worse than it was? I applied the same effects to it that are applied to the other white fills on the other icons I did for "sameness," but let me know if it is better just flat white. I also added a black outline to the text because I liked that look on FullBleed's example above.

Also, looking at the icons, I'm thinking maybe we can have a consistent color for the type of file? Thoughts?

- Text - Red
- Application - Green
- Audio - Blue

![RPTools_Plaintext_Logo](https://user-images.githubusercontent.com/29924417/118381035-b79cd880-b59b-11eb-84b9-9bc489844fd7.png)

**Comment by Phergus** [comment]
I like that!  The helps the label stand out.

Color coding the file types sounds like a good idea.  I'd probably swap the Red & Green so Text is green and Application is red.

**Comment by RPMiller1** [comment]
You got it. I'll make those color changes and post up all the icons.

**Comment by RPMiller1** [comment]
![RPTools_Audio_Logo](https://user-images.githubusercontent.com/29924417/118381865-65ac8080-b5a4-11eb-9bf1-195a1a5abc99.png)
![RPTools_FileType_Logos](https://user-images.githubusercontent.com/29924417/118381866-68a77100-b5a4-11eb-89b0-7ff7c7c2a86c.png)
![RPTools_HTML_Logo](https://user-images.githubusercontent.com/29924417/118381868-6b09cb00-b5a4-11eb-99d2-55296b6508cb.png)
![RPTools_JS_Logo](https://user-images.githubusercontent.com/29924417/118381870-6d6c2500-b5a4-11eb-8408-6b8a96be1787.png)
![RPTools_JSON_Logo](https://user-images.githubusercontent.com/29924417/118381873-6fce7f00-b5a4-11eb-9873-967d807c633c.png)
![RPTools_Markdown_Logo](https://user-images.githubusercontent.com/29924417/118381874-71984280-b5a4-11eb-8318-2be7d163190f.png)
![RPTools_PDF_Logo](https://user-images.githubusercontent.com/29924417/118381877-73fa9c80-b5a4-11eb-9d06-16074b762260.png)
![RPTools_Plaintext_Logo](https://user-images.githubusercontent.com/29924417/118381881-7957e700-b5a4-11eb-9a0c-8b076721a4e2.png)

**Comment by Phergus** [comment]
Looks good!

**Comment by FullBleed** [comment]
Going red and green is like the worst color scheme for colorblind people though.

**Comment by FullBleed** [comment]
I grabbed the 8 color palette since we're only talking about 3 colors here.

For the most variation I'd go with:

Audio: Honolulu Blue/Summer Sky (you guys seemed to like the dark more, so probably HB)

With Application and Text being Bamboo/Paris Daisy or the inverse.

![8color](https://user-images.githubusercontent.com/37131742/118388152-a7fbaf00-b5f0-11eb-85ba-cc8752bdaf7a.jpg)

**Comment by rkathey** [comment]
All this looks great @RPMiller1. Thanks for helping out. 

My OCD wants the audio file labeled as well even though it isn't needed much. 

@Phergus is the plan to have these be the default ICONS when a file is dropped? If so, will the icon be changeable once it's on the map?

**Comment by FullBleed** [comment]
> @Phergus is the plan to have these be the default ICONS when a file is dropped? If so, will the icon be changeable once it's on the map?

1) You'll get these icons for those file types instead of the current red X we get for previously "unknown" file types.

2) You will be able to change out the graphics because the image is just a token associated with the asset.

And when we get a function to pull a token's asset type we'll even be able to automate any kind of custom default graphics we want for these.  I currently sort tokens by way of token labels in my current framework control sheet, and I certainly expect to do the same with these asset types, too.

**Comment by Phergus** [comment]
> @Phergus is the plan to have these be the default ICONS when a file is dropped?

Yup.

> If so, will the icon be changeable once it's on the map?

God willing and the creek don't rise.

**Comment by Phergus** [comment]
@FullBleed 
> **Edit: I think I'd just change the Application category to Paris Daisy and call it the day.**

Fine by me.

As these are partially transparent they are going to end up as shades of their base color depending on the background which may help.

**Comment by FullBleed** [comment]
Not sure if the image part of this has been finished yet, but I think it's important that the PSD used to build these images be stored somewhere so additional types can be easily created for future need.

Are we looking for a dev to step in and produce the "deploy X graphic when Y file type is dropped" bit now?

**Comment by RPMiller1** [comment]
![RPTools_JSON_Logo](https://user-images.githubusercontent.com/29924417/120053124-5df5ce80-bfdd-11eb-948c-3948df63cf91.png)
![RPTools_PDF_Logo](https://user-images.githubusercontent.com/29924417/120053131-61895580-bfdd-11eb-8ee6-467f7d6de7e6.png)
Here are the Application category icons using Paris Daisy.

**Comment by Phergus** [comment]
Thanks @RPMiller1.

I believe that Craig has started the code to handle recognition of the supported file types.

**Comment by Phergus** [comment]
@cwisniew  Where do we want to put the PNG images for inclusion in MapTool?
1. packed into the jar under with the missing and unknown images?
2. in with the Default resources?
3. both?
4. somewhere else?

The current files at 400x400 are a bit heavy (2.8 mb for the 8) so do we want to perhaps drop them down to 200x200?  Would cut the total down to ~50%.

If we go to WebP we can drop that down even further.

**Comment by Phergus** [comment]
@RPMiller1 could you get the PS files to @Azhrei so that we can get them into the proper repo?  Thanks.

**Comment by RPMiller1** [comment]
Done. I've emailed it to him.

**Comment by Azhrei** [comment]
I have them.

I'm thinking they go in maptool-resource (?) but I'll check tomorrow to make sure and put them whoever they go.

Thanks to @RPMiller1 for creating (yet another) set of artwork for MT. 🙂

**Comment by cwisniew** [comment]
> @cwisniew Where do we want to put the PNG images for inclusion in MapTool?
> 
> 1. packed into the jar under with the missing and unknown images?
> 2. in with the Default resources?
> 3. both?
> 4. somewhere else?
> 
> The current files at 400x400 are a bit heavy (2.8 mb for the 8) so do we want to perhaps drop them down to 200x200? Would cut the total down to ~50%.
> 
> If we go to WebP we can drop that down even further.

Probably best place for them is in the maptool repo create a new directory "filetypes" under src/main/resources/net/rptools/maptool/client/image and place them there. If 200x200 looks fine then it might be the way to go, and I think update to the library used to read images that was made recently handles WebP if so I see no issues with converting to WebP.
