### ISSUE TITLE
Filter out Assets that shouldn't be included when drag and dropped on to MapTool

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2527]
**Describe the bug**
MapTool allows many file types to be dragged and dropped which are added to the campaign even if MapTool could never use them.

**To Reproduce**
Drag and drop a zip file or ebook on to MapTool and examine the campaign. It will be added to the map as the broken image (large red X) but the asset will be added to the campaign. 

**Expected behavior**
MapTool should not add the file and should inform users that the file can not be added.

**MapTool Info**
Version info: Probably all of them

**Additional context**
Since some people are using this to add audio/text to the campaign the fix should not stop this from occurring. Since this is not adding new functionality to support storing these types there is no requirement to change the red X to something else, that can be done as part of #2526

**Comment by Phergus** [comment]
Testing on Windows 10 shows that the `Files.probeContentType()` in `TransferableHelper.java` does not recognize WebP, TGA, JP2, PSD or PCX images when images are dropped onto map.  The content type recognition for that function is also very system dependent.  Perhaps move to Apache Tika's `detect()` function instead.

Images in previously saved campaign files do load as do the same images dragged from the Resource Library.  

This impacts #2494 as well.

**Comment by Phergus** [comment]
Allowed non-image types:

- [ ] audio/* - MP3, AIFF, FLAC, OGG, WAV
- [ ] text/html
- [ ] text/markdown
- [ ] text/plain
- [ ] application/pdf
- [ ] application/json
- [ ] text/javascript?
- [ ] text/css

**Comment by thelsing** [comment]
I think it would be nice to go in a different direction: Just make it possible to drag every file to a map. We could have new token type "ressource". For those tokens we could get the icon associated with the extension for display. On doubleclick or on "Show Handout" we could just let the OS open the file with whatever program the OS thinks is best. Then you could put videos, Word, Excel Documents, Rulebooks etc into the campaign.

**Comment by Phergus** [comment]
- [ ] image/bmp
- [ ] image/gif
- [ ] image/ico
- [ ] image/jp2
- [ ] image/jpeg
- [ ] image/pcx
- [ ] image/png
- [ ] image/psd
- [ ] image/svg
- [ ] image/tga
- [ ] image/tif

**Comment by Azhrei** [comment]
Has anyone considered the DOS attack here?  Any client could drop a 2GB file onto a map and suddenly the server starts pushing it out to everyone.

A full permission scheme has been discussed in the distant past, but in the short term perhaps there should be a per-client flag as to who may or may not drop files onto the map.  Or maybe a size limit?  (Maybe server startup options to specify these defaults?)

**Comment by Phergus** [comment]
They could always do that.  At least now there is a mandatory password which will somewhat limit the potential risks to just those you chose to give the player password to.

**Comment by FullBleed** [comment]
I'd just as soon be able to toggle on/off player added assets.  My regular players are not in the habit of doing so, and that suits me fine.  I like have complete control over what ends up in game.  In fact, I think most don't even realize they can.

It might be an entirely other can of worms playing with unfamiliar players whose motivations could become, under the wrong circumstances, malicious.

Would be nice to be able to lock the drawing tools, too. ;)

**Comment by Phergus** [comment]
I'm with you on having greater ability to limit player client actions like using drawing tools or drag-n-drop.

**Comment by FullBleed** [comment]
Is there any way to check a token for what kind of asset it's connected to?

**Comment by Phergus** [comment]
Nope.  Not yet.
