### ISSUE TITLE
Upgrade to Java 16

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2538]
**Is your feature request related to a problem? Please describe.**
Java 14 is 2 releases old and is no longer receiving bug fixes / patches.
Some issues (like #2214) are corrected in later Java run times so we should upgrade to the most recent version.

**Describe the solution you'd like**
Upgrade the build + package process to the latest Java Runtime (16 at this time)

**Comment by Phergus** [comment]
Tested with 1.9.0-alpha.9 and current develop.  No problems seen so far.
