### ISSUE TITLE
Transfer VBL to Token As a Token Properties Button

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#254]
Currently, there is an MTScript function to transfer the VBL under a token onto the token itself. This request is to add this functionality to the Edit Token->VBL sub-panel so this can be done without resorting to MTScript.

**Comment by Phergus** [comment]
Would suggest that this be two buttons:

- Transfer **From** Token to VBL layer
- Transfer **To** Token from VBL layer.

**Comment by JamzTheMan** [comment]
So, question, should it be a "copy" or "transfer"? In other words, should it erase the VBL from the map/token upon transfer? Or should that be another option?

4 Buttons? 2 Buttons + checkbox? 2 Buttons plus dialog? Any other ideas?

Also, should this also be a right-click context menu option on the token?

**Comment by Phergus** [comment]
IMO, checkbox or maybe radio-buttons for copy vs transfer.  And then two buttons for To VBL/From VBL.

**Comment by rkathey** [comment]
We should not need an option for this on the already crowded pop up menu. It’s a fairly advanced function that belong on the token VBL tab.

**Comment by JamzTheMan** [comment]
So, checkbox labeled "Erase Source VBL" and when unchecked buttons are:

[Copy VBL From Map]
[Copy VBL To Map]

and when checked they are labeled:

[Transfer VBL From Map]
[Transfer VBL To Map]

And a proposed reason to add to the pop-up menu would be so you could select multiple tokens (like you copied a dozen columns" and want to transfer them all to the map?

It would be GM only, although with 4 options.... Maybe IF we add a context menu it would be a single menu option "Transfer VBL" which then props a dialog to get further options like radio buttons for To/From map and Copy/Transfer?

Although I could skip the context menu for now then and leave for later (as you can macro this)

**Comment by JamzTheMan** [comment]
Or should it be:

[Move VBL From Map]
[Move VBL To Map]

as that aligns with typical OS copy/move nomenclature?

**Comment by rkathey** [comment]
I think copy/move is clearer although either is acceptable.

**Comment by JamzTheMan** [comment]
I'll use "Move" then as that implies cut/paste and leave "Transfer" as ambiguous and could mean either copy or move, which the function does both (and later use Transfer VBL as well for context menu if that is added later.)

**Comment by rkathey** [comment]
If you’re considering the pop up you might also consider adding generate VBL and whatever ‘Always Visible’ becomes.

**Comment by JamzTheMan** [comment]
"Always Visible" is already there and will be renamed via the i18n change (other issue opened for that)

I'm a little hesitant on generate VBL.  I'm not totally happy with it's results as it does generate some "complicated" VBL which can be extremely laggy if overused...

**Comment by Azhrei** [comment]
I’m not a fan of adding to the context menu — it’s already pretty crowded — but I do see the point about selecting multiple tokens and not _requiring_ the use of a macro.

Terminology is up to you, although copy/move seems to make more sense.

**Comment by JamzTheMan** [comment]
ya, that's fine, it is a pretty long menu already. I hope to fix that in FX (I'm hoping a round menu control I found will look/work well, we'll see)

The only reason menu vs macro is because I suspect 80+% of users don't know how to use macros. There's probably 1 per gaming group that grasps them. BUT, since there is still a UI way of doing it, I'm ok skipping the menu.
