### ISSUE TITLE
Enable Delete Button on Draw Explorer

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#255]
This request is to utilize the Delete Key for deleting drawings on the Draw Explorer window rather than resorting to the right-click->Delete from the pop-up window.

**Comment by oliver-szymanski** [comment]
Happy to take this, but not clear to me how the user would select what he wants to delete?

Are you meaning he still has to select via the draw explorer but then can use a button somewhere instead of the right click?

**Comment by Jaggeroth** [comment]
If you open up the Draw Explorer window you can see a tree view of drawing element.
Right click and you get a menu option to delete, but just hittiing the delete key at that point does nothing.
Should probably bring up a yes/no dialog.
I think else where I may have piggybacked on a delete- yes/no dialog with a "click to not show this again" option. So if you can find that, great :)

**Comment by Jaggeroth** [comment]
Actually, maybe the delete key should always bring up a yes/no ?

**Comment by rkathey** [comment]
Maybe a decision for JFX?

**Comment by Jaggeroth** [comment]
Yeah. For pre-JFX lets let oliver-szymanski make the choice :)

**Comment by oliver-szymanski** [comment]
Same seems to be missing for the Map explorer

**Comment by oliver-szymanski** [comment]
I implemented both, Draw explorer and Map explorer.

Fix in https://github.com/RPTools/maptool/pull/307

**Comment by rkathey** [comment]
Tested.  I like it!
