### ISSUE TITLE
Don't add internally sent commands to the chat's command history

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2550]
**Is your feature request related to a problem? Please describe.**
Certain functionality within Maptool works by sending text commands to the chat, such as impersonating tokens or auto executing macros, and these commands get added to the chat command history the same as regular user input. This can make it  annoying when trying to get back to something you entered yourself, and it feels like the history should be reserved for text input submitted by a user.

**Describe the solution you'd like**
Don't add internally sent commands to the chat's command history.

**Describe alternatives you've considered**
None.

**Comment by Phergus** [comment]
I'd agree with that.  Especially annoying when you are using a mix of macro buttons and hand-entered macro calls in chat.

**Comment by Phergus** [comment]
Tested.  Chat command history only shows commands/text entered in chat.
