### ISSUE TITLE
Certain actions will clear the content of the chat's text area

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2551]
**Describe the bug**
When performing certain actions (such as, impersonating and unimpersonating tokens, clicking an auto executing macros, using Speech on a token, etc.), any text currently entered into the chat's text area is cleared. This can easily result in something a user is in the middle of typing being lost and is rather unexpected behavior. 

**To Reproduce**
1. Place a token.
2. Type anything into the chat text area.
3. Impersonate the token (by the right click menu, impersonate window, etc.)
4. Observe that the text area is now empty

2-4 can be repeated with different actions instead of impersonating. Unimpersonating, running an auto executing macro, or using speech from a token's context menu all have the same behavior.

**Expected behavior**
The content of the text area should be preserved.

**MapTool Info**
- Version: Any
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
This issue is because certain things work by submitting commands to the chat. In most cases, this means setting the text of the chat's text area to the command and then calling `commitCommand()`, overwriting whatever was in the text area. There is already `quickCommit()` that has the option to preserve the current input, but it's not widely used and when used the text is sometimes explicitly not preserved. Genuinely curious if there's a reason to want to clear the user's input.

The simplest way to address this would be simply to use `quickCommit()` when submitting commands. This works fine. An alternative however would be just skipping the middleman and allowing commands to be passed directly to `commitCommand()`, with the parameterless `commitCommand()` just passing in the content of the text area. This would also easily allow for different behavior when submitting from the chat vs something internal (useful for, say, #2550).

**Comment by Phergus** [comment]
Tested.  Described actions and others (Starting a Server) no longer clear the Chat entry field.
