### ISSUE TITLE
GM name of tokens visible in initiative after disconnect

### ISSUE THREAD

**Issue by fishface60** [RPTools/maptool#2554]
**Describe the bug**

After GM disconnected from the server, was left with a partially loaded campaign, including tokens in the Initiative panel including their GM name.
The File menu showed the start and connection information options as greyed out and Disconnect from server was selectable, only after the selection of which was the client returned to the default campaign.

**To Reproduce**
1. Attempt to connect to a server that has not yet started, that will be started on the same externally visible IP address.
2. Start a server and give a token a GM private name
3. Connect a client to the server via the matchmaking server.
4. Add the token to initiative.
5. Have the server disconnect.

**Expected behavior**

Campaign data from a server the GM has disconnected from should be cleared and returned to Grasslands.

**Screenshots**

![MapToolBug](https://user-images.githubusercontent.com/8304293/115305068-afe54200-a15d-11eb-9238-01f19c60d607.png)

**MapTool Info**
- Version: 1.8.5
- Install: Upgrade 1.8.4

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 10

**Additional context**
```
==== MapTool Information ====
MapTool Version: 1.8.5
MapTool Home...: /home/richardmaw/.maptool-rptools
MapTool Install: /opt/maptool/lib/app
Max mem avail..: 1 GB
Max mem used...: 637 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: /opt/maptool/lib/runtime
Java Vendor....: AdoptOpenJDK
Java Version...: 14.0.2
Java Parameters: 
  -Djava.library.path=/opt/maptool/lib/app:/opt/maptool/bin
  -Djava.launcher.path=/opt/maptool/bin
  -Xss8M
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED


==== OS Information ====
OS Name........: Linux
OS Version.....: 4.19.0-16-amd64
OS Architecture: amd64
PATH...........: /home/richardmaw/.cargo/bin:/home/richardmaw/bin:/home/richardmaw/bin:/home/richardmaw/.dotfiles/public/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
Number of Procs: 4

==== User Information ====
User Name: richardmaw
User Home: /home/richardmaw
User Dir.: /home/richardmaw

==== Network Interfaces ====
Display Name..: wlp3s0
Interface Name: wlp3s0
Address...: fe80:0:0:0:aca:6ff:8e3b:d609%wlp3s0
Address...: 192.168.0.26

Display Name..: enp0s25
Interface Name: enp0s25
Address...: fe80:0:0:0:4c3c:4a9d:cfec:8f12%enp0s25
Address...: 192.168.0.46

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: Failed

==== Locale Information ====
Country.: United Kingdom
Language: English
Locale..: English (United Kingdom)
Variant.: 

==== Encoding Information ====
Default Locale:   en_GB
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(-1)

==== Internet Gateway Devices ====
	No IGDs Found!
```

**Comment by Phergus** [comment]
>  After GM disconnected from the server, was left with a partially loaded campaign...

Are you saying the GM wasn't hosting the server but was instead connected to a player hosted server?

**Comment by fishface60** [comment]
> > After GM disconnected from the server, was left with a partially loaded campaign...
> 
> Are you saying the GM wasn't hosting the server but was instead connected to a player hosted server?

Sorry, I forget that feature exists and should have been more explicit.
The GM was hosting the server.

If it may be relevant, the hosting GM was located on the same physical network but my client was connected via the address returned by the matchmaking server.

**Comment by Phergus** [comment]
Okay.  I'm unable to reproduce given the steps above.  Once the GM shuts down the server the client gets the confirmation dialog that the server has disconnected. Clicking on OK and the player client resets to the default grasslands map with nothing in the init window.

**Comment by fishface60** [comment]
:/ that's unfortunate. Feel free to close the ticket and I can come back if it ever happens again.

**Comment by Phergus** [comment]
Definitely let us know if it happens again or you find a way to reproduce it reliably.
