### ISSUE TITLE
Dockable frames don't use localized titles

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2555]
**Describe the bug**
Dockable frames still use their English title regardless of Maptool's current language.

**To Reproduce**
1. Run Maptool in a language besides English
2. Observe that frame names are still in English

**Expected behavior**
Frame names should use their localized names.

**MapTool Info**
- Version: Current develop
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
I understand there are some issues with just trying to set the frame title to the localized name up front (based on the comment in [`i18n.properties`](https://github.com/RPTools/maptool/blob/cb513fb3a6963c4644c8e58c22dda126ca8da815/src/main/resources/net/rptools/maptool/language/i18n.properties#L1862)), but after the frames are created and the layout is loaded, the title(s) of the frames can be set to their localized versions and this seems to work fine.

Edit: Also, should I remove the associated comments if this is an acceptable solution?

**Comment by Phergus** [comment]
Yeah.  Didn't see your question till now.  The comment in the `i18n.properties` file about not being used should be removed.

**Comment by Phergus** [comment]
Tested.  Dockable frames now use their translated names.
