### ISSUE TITLE
Drawing Foreground/Background Texture Select Using Resource Library Directory

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#256]
When selecting a drawing texture on the draw widget, the images shown in the initial window are from the directory selected on the Resource Library, not the directory selected on the Popup select window.

**Comment by Phergus** [comment]
These really need to be decoupled.  It's really annoying to have the Resource Library change location because you select a new drawing texture and vice-versa.

**Comment by JamzTheMan** [comment]
yea, one of those low priority things that's annoying none the less.

**Comment by emmebi** [comment]
I plan to work on this on the next week or so. Feel free to assign it to me.

**Comment by Phergus** [comment]
That's great!

**Comment by Phergus** [comment]
Tested.
- Created new maps with background textures
- Created new maps with map images
- Created new maps with background textures and map images
- Using drawing tools and selected fill/draw textures

All worked as expected and Resource Library stayed at the same location without changing.

**Comment by Phergus** [comment]
Closing.
