### ISSUE TITLE
Layer names lack i18n support

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2560]
**Describe the bug**
Layer names are hardcoded and cannot be translated, when it should be possible.

**To Reproduce**
N/A? The names are missing from `i18n.properties` and hardcoded in `Zone.java`.

**Expected behavior**
Layer names should be provided by entries in `i18n.properties`.

**MapTool Info**
- Version: Any
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Azhrei** [comment]
During testing, be sure to save a campaign, change your locale, then try to load it.  That will ensure layer names are being saved correctly in the campaign file.  (Since they're enums, I would expect they're saved as integers, but I haven't looked.)

**Comment by Phergus** [comment]
Tested with Spanish locale and Spanish layer names.  Worked as expected.
