### ISSUE TITLE
getLabel() creates an error when used in a token without a label

### ISSUE THREAD

**Issue by dark-ether** [RPTools/maptool#2571]
to reproduce run [r:getLabel()] with the Apply to selected Token while impersonating a token without a label,
this is problematic as there isn't a function to check if the label is empty

**Comment by Phergus** [comment]
Please follow the issue templates when posting issues.  Thanks.

**Comment by Phergus** [comment]
Closing.

1. Didn't use template.
2. Unable to reproduce.
