### ISSUE TITLE
Coordinates are off between server and client after a newly added map is resized

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#2582]
**Describe the bug**
This bug shows when you add a map from a different client as a background token, and then you resize it. The coordinates become disconnected between the client and the server. 

**To Reproduce**
1. Start a server
2. Start a client, and connect it as GM to the server
3. Create a new map from the client
4. Add a map as a background token in the client
5. Resize the map in the client
6. Add a token in the client

Now you can observe that the token is not in the same position in the client and the server; interestingly, if you hover on the token on the client and the server, the same position is reported.

**Expected behavior**
The coordinates remain in sync between the client and the server

**Screenshots**

The token on the server screen (note the coordinates)

![token_on_server_screen](https://user-images.githubusercontent.com/1532349/116056473-bdc32780-a675-11eb-8ede-29caa051dd9c.png)

The token on the client screen (note the coordinates)

![token_on_client_screen](https://user-images.githubusercontent.com/1532349/116056572-d7646f00-a675-11eb-8419-e08627532dcf.png)

**MapTool Info**
- Version: 1.8.5
- Install: Upgrade from 1.8.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

Another issue which I found while doing this was that I clients were unable to download the campaign anymore. I am unsure if this happened before I reloaded the campaign or after, however.

**Comment by Phergus** [comment]
I'm not able to reproduce this.

1. Start Server with new campaign
2. Log in to server from 2nd client as GM.
3. Add new map.
4. Drop map image onto background at 0,0.
5. Resize map.
6. Drop image onto token layer.

I get the token displayed at the same position on the map with the same coordinates on both server and gm client.

Saved campaign and stopped server.  Selected New Campaign.  Reloaded saved campaign. Started server. Logged in with player client with no issues.

If this was a big map image did you wait a few seconds before resizing?  On big images, if you immediately reposition or resize it will get reset after the image has been copied to the cache.

**Comment by Phergus** [comment]
Unable to reproduce.
