### ISSUE TITLE
Assert prints a stack trace when called from a macro executed by a macro link

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2596]
**Describe the bug**
Reported by Full Bleed on discord. Basically just what the title says, `assert()` isn't supposed to print a stack trace, but it does when it's behind a macro link.

**To Reproduce**
1. Add the following campaign macro named `assert`: 
`[h: assert(0, "Macro aborting here.", 0)]`
2. Enter the following into the chat: `[r: macroLink("click", "assert@campaign")]`
3. Click the link in the chat
4. Observe that a stack trace is printed after the assert message.
5. Click the `assert` macro button and observe that the message is printed without a stack trace.

**Expected behavior**
A stack trace shouldn't be printed with the assert message.

**MapTool Info**
- Version: Current develop
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Tested.  Working as expected.
