### ISSUE TITLE
Trying to run maptool on Ubuntu VM via x11 proxy

### ISSUE THREAD

**Issue by nowrap** [RPTools/maptool#2610]
Hello,

i installed the maptool_1.8.5-amd64.deb with all required dependencies on a Ubuntu 20 LTS VM via SSH.

I can start maptool:
nowrap@rpg:/opt/maptool/bin$ ./MapTool
```
WARNING: Unknown module: javafx.web specified to --add-opens
WARNING: Unknown module: javafx.web specified to --add-opens
15:40:03.527 (MapTool.java:1528) [main] INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
15:40:07.838 (MapTool.java:1529) [main] INFO  net.rptools.maptool.client.MapTool - **                                                                            **
15:40:07.839 (MapTool.java:1530) [main] INFO  net.rptools.maptool.client.MapTool - **                              MapTool Started!                              **
15:40:07.839 (MapTool.java:1531) [main] INFO  net.rptools.maptool.client.MapTool - **                                                                            **
15:40:07.840 (MapTool.java:1532) [main] INFO  net.rptools.maptool.client.MapTool - ********************************************************************************
15:40:07.840 (MapTool.java:1533) [main] INFO  net.rptools.maptool.client.MapTool - AppHome System Property: /home/nowrap/.maptool-rptools/logs
15:40:07.841 (MapTool.java:1534) [main] INFO  net.rptools.maptool.client.MapTool - Logging to: /home/nowrap/.maptool-rptools/logs/maptool.log
15:40:07.841 (MapTool.java:1541) [main] INFO  net.rptools.maptool.client.MapTool - getting MapTool version from manifest: 1.8.5
15:40:07.841 (MapTool.java:1546) [main] INFO  net.rptools.maptool.client.MapTool - getting MapTool vendor from manifest:  RPTools
15:40:07.908 (MapTool.java:1608) [main] INFO  net.rptools.maptool.client.MapTool - argument passed via command line: -v=1.8.5
15:40:07.908 (MapTool.java:1612) [main] INFO  net.rptools.maptool.client.MapTool - overriding MapTool version from command line to: 1.8.5
15:40:07.909 (MapTool.java:1619) [main] INFO  net.rptools.maptool.client.MapTool - MapTool vendor: RPTools
```

I am using as ssh client MobaXterm which is capable of proxing x11 programms.

On my desktop i am only getting a small Java Windows with the message: internal error
https://owncloud.nowrap.net/s/Ld6YrboT5JLRagW

Is there a chance to get more debug output in order to get a clue what causes this internal error?

Regards
nowrap

**Comment by Azhrei** [comment]
You can turn on DEBUG level logging for every part of MT using the `-d` command line option.

Given the first two lines in the log, I’m guessing you have a separate Java installed that doesn’t include JavaFX (and it’s selected via an env var such as JAVA_HOME).  MapTool comes with an embedded JRE that works, so…  You can try cleansing the env and trying again.

**Comment by Azhrei** [comment]
Oh, and issues posted here should follow the templates provided.  Otherwise, they’re likely to be summarily closed.  (Sorry, I missed that in my original message.)

**Comment by nowrap** [comment]
Hello @Azhrei,
thx for your replies. The question template seeme

On this VM there is no seperated java installed:
```
nowrap@rpg:/opt/maptool/bin$ java

Command 'java' not found, but can be installed with:

sudo apt install openjdk-11-jre-headless  # version 11.0.11+9-0ubuntu2~20.04, or
sudo apt install default-jre              # version 2:1.11-72
sudo apt install openjdk-13-jre-headless  # version 13.0.4+8-1~20.04
sudo apt install openjdk-14-jre-headless  # version 14.0.2+12-1~20.04
sudo apt install openjdk-8-jre-headless   # version 8u292-b10-0ubuntu1~20.04
```

The output with the -d parameter only adds this line:
`16:05:18.497 (MapTool.java:1608) [main] INFO  net.rptools.maptool.client.MapTool - argument passed via command line: -d`

So maptool should use it's own java version, i guess.

Regards
nowrap

**Comment by Azhrei** [comment]
I'm closing this issue.  Please refile it and use the Bug Report template.  I have some additional information to add once you do so.  Thanks.
