### ISSUE TITLE
Ngon drawing tool

### ISSUE THREAD

**Issue by talmaru** [RPTools/maptool#2616]
**Is your feature request related to a problem? Please describe.**
When using the circle draw tool and addPathToVBL you can get some very odd results.

![image](https://user-images.githubusercontent.com/6321213/116874040-4265f680-abde-11eb-8623-bd0756780174.png)
Merge the drawings into this
![image](https://user-images.githubusercontent.com/6321213/116874059-498d0480-abde-11eb-92e6-ed64ea053efd.png)
Use AddPathToVBL 
![image](https://user-images.githubusercontent.com/6321213/116874097-5d386b00-abde-11eb-8585-7bda8319614e.png)
Result
![image](https://user-images.githubusercontent.com/6321213/116874113-6295b580-abde-11eb-94b6-26666bd39523.png)

**Describe the solution you'd like**
I would like a Ngon drawing tool. Define the center point, radius, number of sides, rotation offset.

https://www.cs.princeton.edu/courses/archive/spr15/cos126/docs/Ngon.java

**Comment by kwvanderlinde** [comment]
It looks like this bug with vision has been fixed at some point in the past. Given that the motivation was to workaround the bug, I'm going to close this.

@talmaru (if you're still around) if theres another reason this would be useful, we can always reopen it or open a new request that focuses on the feature in its own right. If the bug still exists, a bug report should be opened for it so it can be fixed.
