### ISSUE TITLE
Overlay not being unloaded on campaign switch

### ISSUE THREAD

**Issue by spydyrsbyte** [RPTools/maptool#2621]
**Describe the bug**
Overlay kept though not showing after a campaign switch.

**To Reproduce**
1. Start a campaign.
2. Create an overlay with a setInterval that calls a form - to submit some token macro
3. Switch campaigns

**Expected behavior**
Overlay layer completely wiped clean after campaign load or unload.

**Screenshots**

**MapTool Info**
- Version: 1.8.4
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10, 20H2 - 9042.928

**Comment by kwvanderlinde** [comment]
This is the same underlying issue as #2249, which will be fixed in 1.9.0.

**Comment by Phergus** [comment]
As Kenneth said, this has been fixed.
