### ISSUE TITLE
Add "None" to "New Map Grid Type" under Preferences

### ISSUE THREAD

**Issue by taustinoc** [RPTools/maptool#2630]
Preferences has a drop down to set the default grid type for new maps that includes both types of hex, square and isometric, but not no grid. It seems like it should be easy to add the additional option for those of use who normally don't use a grid.

**Comment by Irarara** [comment]
Nice coincidence, I was thinking about this just recently. Can't see why it shouldn't be an option there. I'll work on this.

**Comment by Phergus** [comment]
@taustinoc please use the provided issue templates in the future.

**Comment by Phergus** [comment]
Tested: No grid option now shows in preferences and, if selected, new maps are created with no grid.
