### ISSUE TITLE
Recursive deferrals in execLink and execFunction resolve unintuitively without regard to scope.

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#2633]
**Describe the bug**
When I defer a function which itself defers another function, the recursive deferral is scheduled at the end of all other deferrals in the call stack up to that point, rather then at the end of the function itself. This may not be a bug per se, but it leads to unintuitive (and hard to account for) issues with order of operations when using functions which may want to nest deferrals and where the order of resolution matters.

The [documentation](http://wiki.rptools.info/index.php/execLink) says "If you defer a series of links, they will be queued in order and executed after the currently running macro." This doesn't specify that the deferrals will not have any nested behavior, so it is a bit ambiguous (at least to me).

For instance, here is a pseudocode sample where I use 'D2' as shorthand for a exec call with Defers a 'Broadcast 2' function. Recursively, 'DD2' is shorthand for an exec call which defers a function which itself defers a 'Broadcast 2' function, and so on.
```
CODE                  DEFERRED STACK             OUTPUT 
Broadcast 1           DD2 -> D2                  1
DD2                   D3 -> Broadcast 3          3
D3                    D2 -> Broadcast 2          2
```

**To Reproduce**
Steps to reproduce the behavior (to be done on a library token, let's suppose it is called "Lib:TestDefer"
1. Write a macro "3" which broadcasts '3', and a macro "D3" which simply defers a call to '3'.
2. Write a macro "2" which broadcasts '2' then a macro "D2" which defers that macro, then a third "DD2" which defers that one.
3. Write a macro with the following code:
```
[h: broadcast("1")]
[h: execLink(macroLinkText("DD2@Lib:TestDefer"), 1)]
[h: execLink(macroLinkText("D3@Lib:TestDefer"), 1)]
```
4. See erroneous output:
```
1
3
2
```

**Expected behavior**
I expect a called function or macro to *fully* complete after the current macro. That is, the macro itself and then any deferred macros. This makes for a predictable order in the case of UDFs/macros which utilize defferals.

In other words, I believe that the above example should produce:
```
CODE                  DEFERRED STACK             OUTPUT 
Broadcast 1           DD2   -> D2                1
DD2                    ↳ D2 -> Broadcast 2       2
D3                    D3    -> Broadcast 3       3                                               
```

**MapTool Info**
- Version: 1.8.5
- Install: All the upgrades, alongside old versions

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Additional context**
I'm using functions which defer eachother quite a lot under the hood in order to work around REST call timeouts and ensure things happen in the correct order. 

This behavior may be intentional right now, so this might be considered a 'Feature request' - but I feel like the current behavior makes UDFs that use deferred functions extremely hard to manage and predict.

**Comment by melek** [comment]
I want to add that in my use case, I actually want deferrals inside my UDFs to happen after the UDF main function - NOT the macro I'm calling the UDF with. In other words, I want this to work as I expect:

```
[h: librat.getRESTUpdates()]     // Runs a bunch of deferred functions, sometimes nested.
[h: librat.cacheVersions()]      // Needs to run after the prior function finishes, including deferred functions.
```

so following the format in my OP, here is what I would most prefer:
```
Call Stack:                                   Broadcast Output:
Main Macro Runs: "Broadcast 1"                1
                 Defer DD2                    .
                 Defer D3                     .
Main Macro Deferrals Run:                     .
↳ DD2 Runs: Defer D2                          .
   DD2 Deferrals Run:                         .
    ↳ D2 Macro Runs: Defer "Broadcast 2"      .
    ↳ D2 Deferrals Run:                       .
      ↳ "Broadcast 2" macro runs.             2
↳ D3 Runs: Defer D2                           .
   D3 Deferrals Run:                          .
    ↳ D3 Macro Runs: Defer "Broadcast 3"      .
    ↳ D3 Deferrals Run:                       .
      ↳ "Broadcast 3" macro runs.             3
```

**Comment by melek** [comment]
Wanted to provide this macro/UDF workaround I'm now using to sidestep this issue:

```
[h: "<!-- Usage: defer(function, args, num_deferrals)      -->"]
[h: "<!-- Re-defers a function to control execution order. -->"]
[h: vFunction   = arg(0)]
[h: vArgs       = arg(1)]
[h: vDeferLevel = arg(2)]

[h, if(vDeferLevel == 0), code: {
    [execFunction(vFunction, vArgs)]
};{
    [execFunction("defer", json.append("", vFunction, vArgs, vDeferLevel - 1), 1)]
}]
```

**Comment by cwisniew** [comment]
A deferred function gets added to the call stack to be called after your macro relinquishes the thread. This can be done in one of two ways
	1) Your macro ends.
	2) Your macro pauses waiting for input.

Since the deferred call happens on the UI thread (as do all macros unfortunately, but it is what it is). This could mean that the UI has queued up things to run that will get run before your deferred macro. Since the intention of this functionality is to be able to perform some work then let the GUI do something, then perform the rest of the work after that (and several Macros out there rely on this behaviour) its not something that would be changed. Doing so would mean many macros that change tokens after they are copied or moved to another map will fail.


I would consider this to be only a documentation bug in that it should be spelt out clearer.

**Comment by melek** [comment]
So would this be best characterized as a technical limitation?

It sounds like the best next steps are to clarify that deferred macros are always added to the same queue regardless of whether they are deferred from the main body of the macro or a called macro/UDF.

I'll give updating the documentation a shot, and I'll attach my "deep deferrment" macro as a workaround in case others run into the problem I have.

**Comment by Phergus** [comment]
@melek should I close this or leave it open until you can update the wiki?

**Comment by melek** [comment]
Thanks for the push, I've had my fingers in the wiki lately so I'll post here once I've updated it.

**Comment by melek** [comment]
Got around to adding a small note on [exe function](https://wiki.rptools.info/index.php/execFunction) and [execLink](https://wiki.rptools.info/index.php/execLink). I forwent an example of a workarounds for a link to this discussion.

Sorry for the close/open, the GitHub app makes it very easy to close by accident (I thought I was closing a modal screen...)

I copied the text between the two pages, so if you see a typo in one it is in both!

**Comment by Phergus** [comment]
Seems fine to me.  Go ahead and close if there is nothing more you wish to add.
