### ISSUE TITLE
Tree in Draw Explorer does not display items correctly

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2637]
**Describe the bug**
Presently, the way items are displayed in the tree in the Draw Explorer is the opposite of how it should be, single drawings are treated as branch nodes (they all have a folder icon and a + next to them, despite having no children) and groups are treated as leaf nodes (they get an icon and cannot be expanded to view the members of the group).

**To Reproduce**
1. Draw something with one of the drawing tools..
2. Observe that in the Draw Explorer that the icon is a folder and there's a + next to it.
3. Draw something else and then group both drawings. (Select both in the panel, right click, and then Group Drawings)
4. Observe that it displays the icon that corresponds with the the last/bottom most drawing the was grouped.

**Expected behavior**
Single drawings should be leaf nodes and groups should be branch nodes in the tree.

**Screenshots**
![MapTool_2021-05-09_12-25-35](https://user-images.githubusercontent.com/59770924/117579612-b5310f00-b0c1-11eb-9b9f-c3f60dbada42.png)

**MapTool Info**
- Version: Current develop
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by Phergus** [comment]
Tested.  Drawings and groups are portrayed correctly.
![image](https://user-images.githubusercontent.com/34379254/117727924-eedb4600-b1a5-11eb-8d7b-a62dd558eec2.png)
