### ISSUE TITLE
Fix Window Size Memory

### ISSUE THREAD

**Issue by damccull** [RPTools/maptool#265]
When you close maptool it remembers the last window size it had, which is great, except when it's maximized while being closed. If it's maximized while being closed it records the full monitor resolution as its size and the next time you launch it, it's not maximized but it is the same size as the monitor. That means parts of it hang off the screen. It's honestly just annoying and can be easily worked around, but it'd be nice to see it only record non-maximized window sizes, and also to remember if it was maximized last time and launch maximized.

**Comment by JamzTheMan** [comment]
To b e honest we'll probably wait and fix this for 2.0 since we're doing a lot of UI work then.
I've marked it as deferred for that reason.

**Comment by damccull** [comment]
👍

**Comment by oliver-szymanski** [comment]
I have a fix for that cause this is really annoying ;)

**Comment by oliver-szymanski** [comment]
Fix in https://github.com/RPTools/maptool/pull/308
