### ISSUE TITLE
getMapVisible returns the strings "1" and "0"

### ISSUE THREAD

**Issue by aRTy42** [RPTools/maptool#2652]
**Describe the bug**
The function `getMapVisible()` returns the strings "1" and "0". This means checks like `assert(getMapVisible(), "map is not visible to players")` will always continue as if the map were visible.

**To Reproduce**
1. Run the following macro on a map that is not visible to players:
```
<br>[getMapVisible()]
<br>[assert(getMapVisible(), "map is not visible to players")]
<br>[3+getMapVisible()+3]
```
2. First line returns 0. The assert falsely evaluates to 1 and continues. The expected addition concatenates to 303 instead, indicating that the returned 0 is a string.

**Expected behavior**
Return the data type that matches similar functions (boolean or int?) as it is documented on the wiki.

**MapTool Info**
- Version: 1.8.5.
- Install: Upgrade [1.8.4]

**Desktop:**
 - OS: Windows
 - Version 7

**Additional context**
Already looked into the files and found the issue. Will do a PR.

**Comment by Phergus** [comment]
Tested.  `getMapVisible()` now returns either `0` or `1` as a number.
