### ISSUE TITLE
Abeille download taken down

### ISSUE THREAD

**Issue by michaelperino** [RPTools/maptool#2654]
**Is your feature request related to a problem? Please describe.**
The site linked within the documentation no longer allows you to download the Abeille Form Designer. See https://github.com/RPTools/maptool/blob/7664101b1a426c68f76723bf57a8db61e5f4eccb/doc/How_To_Setup_UI_Tools.md

**Describe the solution you'd like**
If someone knows a spot that has a legitimate download link, providing that would be appreciated. Or, if we are allowed to host it ourselves, could it be placed within the repository?

**Describe alternatives you've considered**
It is technically possible to edit the XML files manually based on old examples, though not efficient.

**Comment by Phergus** [comment]
The Abeille-2.1.0_M3.zip file is currently attached to a message on the MapTool Discord server:

https://discord.com/channels/296230822262865920/494598206626463755/668129898510155787

Perhaps we can find a place to put it in the repo.

**Comment by Phergus** [comment]
Abeille zip file has been added to the wiki page (#2680).
