### ISSUE TITLE
Map not syncing well with client when GM edits map properties

### ISSUE THREAD

**Issue by michaelperino** [RPTools/maptool#2656]
**Describe the bug**
I believe that in 1.8.5 and develop, editing the map settings on a server while players are looking at it will change the map due to the ZoneRenderer being removed. It's possible this is an issue on my machine if preferences got messed up when working on them in a development branch.

**To Reproduce**
1. Open a server on 1.8.5
2. Connect to the server with a different client
3. On a campaign with multiple maps, enforce GM (server) and Player clients to the same map
4. Edit any of the map's fields using Toolbar -> Map -> Edit Map on the GM screen

**Expected behavior**
Let me know if others expect different behavior, but I expect that the player client will re-open to the edited map like what happens on the GM's client.

**MapTool Info**
- Version: 1.8.5 through develop, probably older as well (unless it's my develop preferences that are messing with the older version)
- Install: Upgrade 1.84 -> 1.85 -> develop

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
![video as seen in disc](https://cdn.discordapp.com/attachments/494598206626463755/843778916585046026/2021-05-17_04-12-19.mp4)

**Comment by FullBleed** [comment]
This is a bug (or, at least, not what should be expected.)

Looks like that Map Display Name feature you're working on is paying some additional dividends.  ;)

**Comment by Phergus** [comment]
This behavior dates back to at least 1.3.b76 (October 2010) and probably further.  It was never considered a particularly serious issue as it rarely makes sense to change core map properties during a session.  More likely to be done during session prep when there would be no disruption.

**Comment by FullBleed** [comment]
> 
> 
> This behavior dates back to at least 1.3.b76 (October 2010) and probably further. It was never considered a particularly serious issue as it rarely makes sense to change core map properties during a session. More likely to be done during session prep when there would be no disruption.

Not surprised.  This issue was particularly painful to me because of how my framework character sheets and map switching macros work... so I'm looking forward to anything that (hopefully) keeps the players on the map after a map edit.

**Comment by Phergus** [comment]
Tested.  Clients on a map now stay on the map after Edit Map has been used by a GM.  Clients on maps other than the one that was changed are not effected.
