### ISSUE TITLE
Stream Audio Source Property Wrong

### ISSUE THREAD

**Issue by MahChaa** [RPTools/maptool#2658]
**Describe the bug**
When using `getSoundProperties()` after an audio/track has been defined or played, a list of objects with the sounds' properties is returned. One of the properties is `currentTime`. It's an important property to keep track of the progression of an audio/track while it's playing. A stream has a start and a stop time offset. When a stream is played to its entirety, it stops at the stop time and remains in memory. When played again, the `currentTime` property is completely wrong; it will always be equal to the stop time. For any stream, when replayed after having reached its stop time previously, the `currentTime` property breaks. A fix is to use `stopSound()` with the second parameter being `1` to remove that audio source from memory. That's an inefficient workaround.

**To Reproduce**
1. Play a stream to its entirety, the stop time can be arbitrary, but it has to reach it.
   example: `playStream("https://dl.dropboxusercontent.com/s/cam791owzf6rsh0/ravenholm_1.mp3?dl=0")`
   The URI above is used as an example, it will eventually expire. Test with a short audio or set a short stop time.
2. While the audio above is playing, call `getSoundProperties()` for the URI used in step 1. You will see property `currentTime` between the start time and the stop time. If you managed to call it twice, you will see it increase. For a better ouptut, use `json.indent()` with `getSoundProperties()`.
   example: `<pre>{json.indent(getSoundProperties())}</pre>` with the URI as an argument if there are more than one audio source.
3. Re-do step 1.
4. While the sound is replaying, call `getSoundProperties()` again for that URI. `currentTime` will be equal to the stop time and by calling it another time while the audio is playing, you will see that it remains the stop time.
5. When the audio finished, call `getSoundProperties()` again and see that `currentTime` is now 0 or whatever start time you had set for that URI. When the sound is stopped, `currentTime` equals the start time, and if the sound is playing, `currentTime` will be the stop time.
6. Call `stopSound()` to remove the audio from memory.
7. Re-do step 1 and 2.

**Expected behavior**
`currentTime` should always represent where the audio is currently at. It should vary from the start time to the stop time.

**MapTool Info**
- Version: 1.8.5
- Install: Clean install, windows 10 installer

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10, version 1909, build 18363.1500

<details>
<summary><b>Additional context</b></summary>

==== MapTool Information ====
MapTool Version: 1.8.5
MapTool Home...: C:\Users\Mahdi Chaari\.maptool-rptools
MapTool Install: D:\Folder\Software Utilities\MapTool 1.8.5\app
Max mem avail..: 1 GB
Max mem used...: 230 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: D:\Folder\Software Utilities\MapTool 1.8.5\runtime
Java Vendor....: AdoptOpenJDK
Java Version...: 14.0.2
Java Parameters: 
  -Djava.library.path=D:\Folder\Software Utilities\MapTool 1.8.5\app;D:\Folder\Software Utilities\MapTool 1.8.5
  -Djava.launcher.path=D:\Folder\Software Utilities\MapTool 1.8.5
  -Xss8M
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PATH...........: D:\Folder\Software Utilities\MapTool 1.8.5\app;D:\Folder\Software Utilities\MapTool 1.8.5
Number of Procs: 8
</details>

**Comment by Phergus** [comment]
When streams are played again after they have reached their stop time the `currentTime` returned by `getSoundProperties()` is now set correctly.
