### ISSUE TITLE
Changes made to drawings are not immediately reflected on map

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2661]
**Describe the bug**
When manipulating drawings through the context menu in the Draw Explorer panel, such as changes to their order (Bring to Front/Send to Back) or pen settings (through Set Properties) the changes are not reflected until one of the following things happens:
1. The zoom level is changed
2. A drawing on the same layer is added
3. A drawing on the same layer is deleted
4. A drawing is moved to or from the same layer (this is really just 2 and 3)

This goes for the client the action is originating from and any connected clients.

**To Reproduce**
1. Add a drawing
2. Set a different fill color
3. In the Draw Explorer right click on the drawing and select "Set Property"
4. Observe nothing happens
5. Zoom in or out (or do any of the other things mentioned above) and observe that the drawing updates to the new fill color

For order, just do the above but layer two drawings and use Bring to Front and Send to Back from the context menu. There will be no update until one of the things mentioned is done.

**Expected behavior**
Changes to drawings should be reflected on all clients without any extra user input.

**MapTool Info**
- Version: Current develop
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Tested.  Both server and client update immediately upon changes to drawings via the Draw Explorer.
