### ISSUE TITLE
Using a name for macro frame that matches one of the default frames should return a meaningful error

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2675]
**Is your feature request related to a problem? Please describe.**
Presently, if you try to make a frame (via the `frame` or `frame5` roll options) using a name that matches one of the default MT frames it returns a generic error that does not indicate the source of the problem. While this is likely to only very rarely be an issue, it would still be nice to return something more clear.

Ex (running `[frame("DRAW_TREE"): {}]` in chat):
```
Error in body of roll.
  Statement options (if any): frame("DRAW_TREE")
  Statement Body : {}
```

**Describe the solution you'd like**
Return a more meaningful error, something like `Roll option "frame": "DRAW_TREE" is a reserved name.` (open to suggestions here if that could be made clearer).

**Describe alternatives you've considered**
N/A

**Additional context**
While this is a pretty minor issue on its own, catching name conflicts early also helps with a solution I was toying around with for #2485 (because this is something that needs to be explicitly caught and handled for that anyway).

**Comment by Phergus** [comment]
Tested.  Attempting to use a reserved name now returns:
```
Roll option "frame": "INITIATIVE" is a reserved name.
Error trace : chat
```
Note this only applies to the use of the internal enum names and not the title seen at the top of the frame.
You can do:
`[frame5("Campaign"): {I am frame}]`
but not:
`[frame5("CAMPAIGN"): {I am frame}]`

**Reserved Names:**
- CONNECTIONS
- TOKEN_TREE
- DRAW_TREE
- INITIATIVE
- IMAGE_EXPLORER
- CHAT
- LOOKUP_TABLES
- GLOBAL
- CAMPAIGN
- GM
- SELECTION
- IMPERSONATED
