### ISSUE TITLE
MapTool determines the external address by hitting every configured site.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2684]
**Describe the bug**
A MapTool client can take a very long time to connect to a server, if any service used to determine the external IP address of the server is slow to respond. This can take so long that MapTool appears to hang. A similar issue exists with the Connection Details dialog, though that can be closed without impacting other MapTool functionality. 

**To Reproduce**
Since this is a matter of handling unreliable external resources, reproducing the issue relies on one of the configured sites to be having issues. In that case, the issue can be seen by opening the Connection Details dialog and observing how long it takes to determine the external address. Alternatively, a server can be started and a client then connects to it, and the client will appear to hang.

**Expected behavior**
MapTool should use the result of the fastest service and should ignore other responses.

**Screenshots**
This is what a user sees when trying to find their connection details:
![image](https://user-images.githubusercontent.com/7492219/120048602-61348e80-bfcc-11eb-9092-016c1fd3d813.png)
A thing is true for the Connect to Server dialog, but in that case the IP address discovery blocks the UI completely.

**MapTool Info**
- Version: 1.8.3, also reproduced on `develop`.
- Install: New

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Additional context**
In my particular case, I was having trouble with only one service: `http://icanhazip.com/`. Incidentally, this is the last service on the list (found in `ip-check.txt`). So MapTool went through four good services, got the same IP address four times, but still contacted this service as well and waited for it to respond.

**Comment by Azhrei** [comment]
Weez call thats a bug! 😉  It also does them sequentially instead of in parallel (and just taking the first result that comes back).

**Comment by kwvanderlinde** [comment]
I pretty much have a solution put together. Will have a PR up shortly.

**Comment by Phergus** [comment]
Tested.  Disconnecting from the network and attempting to get connection info (File -> Connection Information) times out after 30 seconds instead of seemingly hanging.

**Comment by Azhrei** [comment]
Now just need some feedback in the UI somewhere…  One area is when starting the server and the other is on the **File > Connection Information…** dialog.

**Comment by FullBleed** [comment]
My internet was down for a bit and I was doing some work on my framework when I noticed that MT would kind of "freeze" when any of my preset sound files were called.  And I got to wondering if people might be experiencing that when there is any kind of disruption to sound calls.

Will this fix help with that?

**Comment by Phergus** [comment]
This fix was only about connecting to the services that return your computer's/router's external IP address.  No overlap in the code for that and playing sound from network URIs.
