### ISSUE TITLE
New Version of execMacro() for frame/javascript output.

### ISSUE THREAD

**Issue by Akaku-Keninari** [RPTools/maptool#2695]
**Is your feature request related to a problem? Please describe.**
execMacro() uses nonstandard characters in it's output likely for 'security'. As you could just make the exact style show up programmatically aside from it reading the client preferences, a gm making the code should be able to override that functionality. It makes it unusable putting it in a html5 frame via javascript calls.

**Describe the solution you'd like**
An alternative to the function that spits out the formatting/output in plain html. Possibly with a minor style difference.

**Describe alternatives you've considered**
Complicated regex and string manipulation after the fact to find those specific codes and replace them with standard html sequences.

**Additional context**
Example string(base64'd to preserve formatting) outputted by execMacro()
QXdvbyBhbHNvIB4BAjFkNCA9IDMfMx4gbGlnaHRuaW5n

**Comment by cwisniew** [comment]
I am not sure what this request is asking for, you can remove all the roll makers and get plain text by using the [r: ] roll modifier

E.g.  [r: execMacro(" you rolled a [r: d6]")]

The formatting comes from the [] passed to execMacro() not execMacro itself, so if you want no formatting you need to make sure the macro you call doesn't format. Adding an option to get execMacro() to strip any formatting you asked the macro to do will be error prone.

**Comment by Phergus** [comment]
So what you're seeing is: `Awoo also 1d4 = 33 lightning`
In NP++
![image](https://user-images.githubusercontent.com/34379254/120555654-9ec45d80-c3b8-11eb-9e98-97f9a6a09bb4.png)

Which sounds a lot like what is happening in #2339. and indeed if I do this:
`[r,s: execMacro(" you rolled a [r,s: d6]")]`
I get this:
`you rolled a r,s3«  »`

So we need an example from you of the call to `execMacro()` that produces the issue.

**Comment by Akaku-Keninari** [comment]
That string was "Awoo also [1d4] lightning"

**Comment by Akaku-Keninari** [comment]
The workaround wasn't as complicated as I feared...

```
[h: instring = arg(0)]
[h: evilregex = "\\x1e\\x01\\x02(.*?)\\x1f(.*?)\\x1e"]
[h: outstring = replace(instring, evilregex, '<div class="f5roll">\$2<span class="f5roll_tooltip">\$1</span></div>')]
[h: macro.return  = outstring]
```
It seems 'roll' is predefined in maptool and probably shouldn't be used.

**Comment by Phergus** [comment]
> That string was "Awoo also [1d4] lightning"

Sigh.  That was the decoded content of your base64 string as rendered by GitHub's message engine while the image is how NotePad++ shows it.

> It seems 'roll' is predefined in maptool and probably shouldn't be used.

Easily seen by looking at the list of macro functions: https://wiki.rptools.info/index.php/Category:Macro_Function
