### ISSUE TITLE
Parameter inconsistency

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#270]
There are some table functions that **aliasmask** reported as having inconsistent parameter types.  I've tried to represent his comments, but I likely messed it up.  Hopefully, it can be discussed in Discord and then clarified here.

1.  `addTableEntry()` should have option to add image but does not. http://lmwcs.com/rptools/wiki/addTableEntry
1.  `createTable()` and `setTableEntry()` have an option to add image, but it takes image ID (32-char string) but not assetID (the URI).  _(And speaking of these, we should define the terminology.  I'd prefer "asset URI" or "asset URL" to refer to the strings that have the `asset://` prefix, but I don't know what the 32-char string should be called.  Maybe his term, **image ID**, works because it's the same format as the token ID?)_ http://lmwcs.com/rptools/wiki/createTable and http://lmwcs.com/rptools/wiki/setTableEntry
1.  `setTableImage()` appears to add an image to an entry in a table, but how to set the actual table image? http://lmwcs.com/rptools/wiki/setTableImage

**Comment by Azhrei** [comment]
I'd like the macro API to be settled before we produce 1.5.0-final, but I'm not sure how to denote that using GitHub labels and/or projects and/or milestones...

**Comment by JamzTheMan** [comment]
By macro API, what do you mean? This issue?

My thought and how I was doing things for a release is add the issue to the Project.
We should not produce a release until that Project is completed. All the issues should be completed or deferred before the final release is complete.

If this is one of those issues, add it to the Project.

**Comment by Azhrei** [comment]
If we're going to change the way script authors call macros (in terms of parameters to be passed, naming convention, etc) then it would obviously be nice to settle on those before we release 1.5.  Otherwise, we should wait until 1.6/2.0 to make changes.  If resolving this issue (parameter types) is going to happen, should it be in 1.5?  This is something that, IMO, shouldn't change from 1.5.0 to 1.5.1, since it changes the API script authors use...

If we're not going to change this until 1.6, then this issue can be deferred (if I understand your usage of the Project settings).

**Comment by Jaggeroth** [comment]
When I worked on the table macros I noticed that how macros in general handled assets was inconsistent. So I picked one as was done. 

I think I did it better with the drawing macros, so I will go back and address this. But I will look at all macros that use assets. 

Feel free to assign this to me. 

ps: don't think this should delay Jagged's birthday release ;)

**Comment by Azhrei** [comment]
Haha, alright.  This is the first that table macros will be in MT “official”, right?  We can say the table API is in flux and may change in 1.6 so people should write any macros using tables with that in mind.

We _should_ be able to code the functions so that either image ID or asset URL will work (that should be pretty easy), but we won’t guarantee it at this point.  And if we do need to break compatibility, it’ll be in 1.6 and not 1.5.x.  Sound good?

**Comment by Jaggeroth** [comment]
Agreed. That's what I meant when I said I did it better with the drawing functions, they accept both IDs and URLs.

I will do some testing tonight, but with the exception of the asset handling I don't think the table functions are that inconsistent. More that the wiki was wrong.

Anyway, I won't tell anyone the functions were introduced in 1.4.0.1 if you don't :D

**Comment by Azhrei** [comment]
Oh, were they?  Shows how well I keep up with the scripting side of things!

Okay, thanks.  I’ll assign this to you and leave it as part of the “merging Nerps” Project; if it turns out to be a big deal, we’ll defer to it until later.

**Comment by Jaggeroth** [comment]
See PR #273

**Comment by JamzTheMan** [comment]
@Jaggeroth It looks like this is/has been working like this for a few releases? I've marked it low and deferred it for that reason. I'd assign it to @Jaggeroth but he hasn't accepted the Org invite yet. :)

Once someone "assigns" this to themselves to work on it, we'll get it on the release schedule.

**Comment by Jaggeroth** [comment]
I believe this can be closed as I have done a Pull Request.

**Comment by JamzTheMan** [comment]
Got it, didn't know #273 fixed all concerns here or not. I'll close it.

Helpful hit, put a # before the number in the PR and it'll link it. I see now you had put "Fixes issue 270"

**Comment by Jaggeroth** [comment]
I did put a hash in front of the number. :(
See its up there *points upwards*

**Comment by JamzTheMan** [comment]
Wierd, I see it now. Wonder why GH didn't reference it like it did when I did it?

Maybe u have to be in the RPTools org?
