### ISSUE TITLE
Pathfinding performance significantly degrades in the presence of complex MBL.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2716]
**Describe the bug**
When dragging a token through complex MBL on a moderately sized map grid, pathfinding is slow and can easily time out.

**To Reproduce**
1. Open the attached maze map, that has lots of MBL.
2. Drag the token from the maze entrance, straight up to the centre area. Gives a path length ~730.
3. Wait for some time. Depending on system specs and maybe the phase of the moon, it may complete after a few seconds or take long enough to time out.

**Expected behavior**
The pathfinding should be relatively quick.

**MapTool Info**
- Version: 1.8.3, `develop`
- Install: New

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Additional context**
Pathfinding spends a significant amount of time checking whether movement is allowed from one cell to the next. While individually these checks are not very heavy, they are performed so many times that they are the bulk of the pathfinding cost when moving through complex MBL.

The way the MBL check is done is that a line segment is "drawn" between the centers of each cell, and then JTS is asked whether the line intersects with the MBL. Thankfully, repeated intersection against a given geometry is a case that is optimized by JTS. It just requires moving to `PreparedGeometry` instead of `Geometry`.

Maze map (rename to `labyrinth.rpmap`): [labyrinth.zip](https://github.com/RPTools/maptool/files/6619428/labyrinth.zip)

**Comment by Phergus** [comment]
Tested against supplied labyrinth map.  Significantly faster and more responsive than with MT 1.8.5 and no timeouts.  Also tested against 100x100 cell random dungeon without issue.  

Seeing some issues with more complex cave maps but need more testing.  Will get back to this later today.

**Comment by Phergus** [comment]
@kwvanderlinde  if you want a map to really test performance try this one:
https://www.dropbox.com/s/hhtwe4v3sdja3kc/50x50%20Cave%20100px.7z?dl=0

It's 50x50 @ 100px/grid random cave from Dungeondraft.

**Comment by kwvanderlinde** [comment]
Thank @Phergus, that map is brutal! It already helped me to find some easy performance gains, and hopefully it helps find more yet.

**Comment by kwvanderlinde** [comment]
I've followed up with #2729 to address this more complicated case.

**Comment by Phergus** [comment]
Excellent.  Considering this complete.
