### ISSUE TITLE
Memory bar isn't wide enough to display the text

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#272]
As the subject says. :)

**Comment by Phergus** [comment]
A screenshot might have been nice.

This is what it looks like on Windows 10.  A bit cramped but enough room to display it.
![MemBarOrig](https://user-images.githubusercontent.com/34379254/71143868-553e7d80-21d9-11ea-80f0-74183f5efbcd.png)

Added code to set the size based on the font used plus some padding for breathing space.
![MemBarUpdate](https://user-images.githubusercontent.com/34379254/71143911-7606d300-21d9-11ea-8b94-c7904ddce4e7.png)

So larger fonts also work now:
![MemBarUpdateBigFont](https://user-images.githubusercontent.com/34379254/71144048-e6155900-21d9-11ea-82b2-43105fd6a101.png)

That what you are looking for @Azhrei ?

**Comment by Azhrei** [comment]
> A screenshot might have been nice.

You're right.  I was being cute, but that wasn't helpful. 😐

> That what you are looking for @Azhrei ?

Yep, that looks good.  When I open the current MT — and without loading a campaign — there's plenty of space.  But since we're using a font with variable-width characters, something like `888 MB/888 MB` will likely be the widest string.  As long as it look good with a string like that, I'd say it's good enough. 🙂

**Comment by Phergus** [comment]
I used `9.99 MB/9.99 MB` as the "calibration" string.

**Comment by Phergus** [comment]
@Azhrei  PR #1011 has fix.

**Comment by Phergus** [comment]
Fixed. Closing.
