### ISSUE TITLE
MT Discord and Reddit links in Help.

### ISSUE THREAD

**Issue by FullBleed** [RPTools/maptool#2723]
TSIA.

**Comment by Phergus** [comment]
What does the Texas Success Initiative Assessment have to do with MapTool?

Issues that don't follow the templates have a high likelihood of being summarily dismissed.

**Comment by FullBleed** [comment]
> What does the Texas Success Initiative Assessment have to do with MapTool?
> 
> Issues that don't follow the templates have a high likelihood of being summarily dismissed.

I'll get over it.

But, I agree, I certainly did not keep with the template on this one.  I saw, and still see, no need for something so trivial and obvious.
