### ISSUE TITLE
Allow tokens to carry MBL, like they can with VBL.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2730]
**Is your feature request related to a problem? Please describe.**
Tokens are able to block vision, and they are also able to block pathfinding, but only if the AI is set to pathfind around VBL. This means a token cannot block movement without requiring everything else to pathfind around VBL as well.

**Describe the solution you'd like**
I would like tokens to be able to store MBL, in the same way they store VBL. The "Edit Token" dialog would be extended to allow adding MBL, either separately from VBL or in concert (much like MBL/VBL can be drawn on the map separately or together). 

The following macro functions would also be added so that macros can manipulate token MBL analogously to how they can manipulate token VBL:
- `getTokenMBL(id)`
- `setTokenMBL(vbl, id)`
- `transferMBL(value)`, `transferMBL(value, delete)`, `transferMBL(value, id)`, `transferMBL(value, delete, id)`

**Describe alternatives you've considered**
Tokens can already block movement by setting their terrain modifier to "Block". This is quite a blunt option, though, as the token then blocks entire cells. This makes it unsuitable for representing a glass door on a grid line, for example. It also doesn't allow freely placing irregularly shaped terrain, since the token always blocks its entire footprint. Also, Free Size / Native Size tokens cannot block movement this way.

Regarding the macro functions, another option would be to define generic topology functions that can work equally well with VBL and MBL. Given that we already have VBL-specific functions and some MBL-specific functions, it makes the most sense to at least expand the MBL functions to support token MBL. Generic topology functions would then be redundant, and could even be built as UDFs if desired.

**Additional context**
This is somewhat of a follow up to #2234 that added functions for drawing MBL on the map. This FR seeks to expand on that and bring parity between MBL and VBL.

Not all VBL functionality requires MBL equivalents. For example, the "Is Visible over FoW" option and the related `setAlwaysVisible()` macro function are more about a token's relationship with Fog of War than they are about the VBL _per se_, and there isn't an analogous use for MBL.

**Comment by Phergus** [comment]
Tested various iterations of `get`, `set` and `transferMBL`.  Worked as expected.
