### ISSUE TITLE
Players able to "flip" unowned tokens.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#2758]
**Describe the bug**
Players can flip unowned token images using new F key functionality. 

**To Reproduce**
1. Login as player to MT server
2. Select an unowned token.
3. Hit F key.

**Expected behavior**
Lightning bolt from sky to strike meddlesome player.
(Or not being allowed to flip image.)

**MapTool Info**
- Version: 1.9.0, 1.9.1, 1.9.2
- Install: New

**Desktop (please complete the following information):**
 - OS: All

**Additional Context**
Reported on Discord by Walda#3832.

**Comment by MeloDub** [comment]
Whoops, this was an oversight by me, I'll fix it!

**Comment by Phergus** [comment]
Tested.  Players can no longer flip unowned tokens.
