### ISSUE TITLE
Introduce a getTokensAsList method in ModelChangeEvent class

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#2760]
**Is your feature request related to a problem? Please describe.**
ModelChangeEvent class can bring either a single token or multiple tokens; the code to check what is actually here is dispersed in multiple place in the code.

**Describe the solution you'd like**
Introduce a getTokensAsList method which allows you to get single token or multiple tokens as a list, and modify all the callers to use it instead.

**Describe alternatives you've considered**
None was clear

**Additional context**
This is the type of code I would like to get rid of with this change

```
        if (event.getArg() instanceof List<?>) {
          @SuppressWarnings("unchecked")
          List<Token> list = (List<Token>) (event.getArg());
          for (Token token : list) {
            flush(token);
          }
        } else {
          flush((Token) event.getArg());
```

**Comment by Phergus** [comment]
Testing hasn't revealed any issues with this change.
