### ISSUE TITLE
Connected players can't turn off tools in full screen mode

### ISSUE THREAD

**Issue by Xeddar** [RPTools/maptool#2764]
**Describe the bug**
Normally, it's possible to toggle "Enable tools in full screen mode". However, when a client is connected to a server the option is greyed out.

**To Reproduce**
1. Start Maptool, note the "Enable tools in full screen mode" under "view" can be toggled
2. Join a server on that client
3. Note the "Enable tools in full screen mode" under "view" is greyed out

**Expected behavior**
Given it's a client-based setting, it should be toggleable

**MapTool Info**
- Version: 1.9.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Phergus** [comment]
Tested.  Clients can now toggle tools on/on when connected to server and in full-screen mode.
