### ISSUE TITLE
When closing MapTool, don't ask to save a blank campaign

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2774]
**Is your feature request related to a problem? Please describe.**
When my 1.5 year-old niece gets a hold of a mouse, she has a nack for opening 43 instances of MapTool with blank campaigns. Closing them all is tedious since each one asks to save the campaign and requires clicking the "No" button on the dialog.

**Describe the solution you'd like**
When the campaign is blank, there is no prompt to save the campaign when closing MapTool.

**Describe alternatives you've considered**
- Unchecking "Save reminder on close" is good for those who are just players. As a GM it's dangerous to leave that unchecked.
- Not letting my niece be in the same house as a computer.

**Additional context**
Several of the operations that can discard the current campaign already check for a blank campaign prior to asking for confirmation from the user (loading campaigns, MRU loading campaigns, connecting to servers). Exiting is not one of those operations, so it always asks for confirmation. I've also just noticed that creating a new campaign will also always ask for confirmation even if the current campaign is blank.

**Comment by Phergus** [comment]
Is it just a matter of checking `MapTool.isCampaignDirty()` before showing the prompt?

**Comment by kwvanderlinde** [comment]
That should be it, yeah.

**Comment by Phergus** [comment]
Tested.  MT prompts to save after:

- Token added
- New map added
- MT .rpmap imported
- UVTT  map imported

Does not prompt however after changing Token Properties in Campaign Properties.

Will do more testing later.

**Comment by Phergus** [comment]
Considering finished with bug noted above.
