### ISSUE TITLE
Server Option to Remove or Disable "Map Select" UI from Clients.

### ISSUE THREAD

**Issue by FullBleed** [RPTools/maptool#2777]
**Is your feature request related to a problem? Please describe.**
We can create a much better Map Select feature for ourselves in our frameworks with macros.  For example, I can make some maps visible to some players and not to others.  But even if we do, the built-in one is there and makes us have to ask players not to use it or ignore it.  In my case, in order to "disable" the built-in Map  Select I have to make all the maps "Not Visible to Players."  Which means I have to have a permanent "Map not Visible to Players" banner across the top of my maps all the time, even though the map is visible to them if they are on it.

*Describe the solution you'd like**
I would like to be able to remove or disable the built in "Map Select" from clients.  I assume this would be a server setting, but there may be other options I'm not aware of.

**Describe alternatives you've considered**
We can do as I'm doing and make all maps not visible to players.  But, if this is going to be the only solution, then I would like to have a way to disable the "Map not visible to Players" banner across the screen.

![Map is Visible](https://user-images.githubusercontent.com/37131742/122721904-29251200-d23f-11eb-8b5d-975002ad096d.jpg)

**Comment by perkinslr** [comment]
Adding a flag to hide that banner should be pretty easy.  Line 901 in ZoneRenderer.java would need to check for the setting.  Then just need to add the setting to the preferences dialog.  Hiding the `Map Select` button could similarly be done via preferenes.  Hiding it automatically when the GM wants it hidden would be somewhat more complicated, but could probably be set via a campaign property rather than a preference.  The check for it would be line 181 of `ToolbarPanel.java`.  I really don't like touching the GUI code, but if someone gets me the checkboxes added, I can program the backend easily enough.

**Comment by FullBleed** [comment]
I framed the issue as being a server setting because that's when I figured the setting would be "pushed" to clients.

Was I off the mark in that assumption?

**Comment by perkinslr** [comment]
For hiding the button from clients, server settings would probably be a good choice.  A flag on the campaign file marking that a framework has control over map selection could arguably also work.  I don't have a strong opinion between them.

For hiding the banner, that should be a client-local setting, which goes with other client-local settings, on one of the preferences tabs.

**Comment by FullBleed** [comment]
Ok, so checkbox location and syntax is open for consideration.

My initial thoughts are are:

"Hide Default Map Selector" in **Start Server>Options**.
"Hide 'Map not visible to players' Warning" in **Edit>Preferences>Application>Map Visuals**.

@michaelperino has indicated a willingness to handle the UI checkboxes.

**Comment by michaelperino** [comment]
Love me some swing :) I'll take a look when I can!

**Comment by michaelperino** [comment]
Took longer than I expected, but I think I figured it out. If something is especially bad about my implementation I could easily walk back everything except the UI and pass those UI changes to perkins.

**Comment by Phergus** [comment]
Testing

- The setting says to hide map select UI from **players** but it also hides it from the GM.
- The other Map Select button is still available in full-screen mode.

Otherwise the options are working as described.

**Comment by michaelperino** [comment]
Technically it has the button for players but does not create any entries for them to click on. I see your point though, I'll get that taken care of. Also, I had thought that was the intention for the GM but that can easily be altered. Would a macro to show and hide the map select button for trusted macros be appreciated instead?

![image](https://user-images.githubusercontent.com/33206261/139553739-63c00343-cf7a-4f35-8a23-29d9bd505bc2.png)

**Comment by michaelperino** [comment]
I also changed the server policy to add options like in #3073. I'll format this for the wiki later.

« getInfo("server")              = getInfo("server") = {"tooltips for default roll format":0,"GM              reveals vision for unowned tokens":1,"players can reveal":1,"auto              reveal on movement":1,"movement locked":0,"token editor              locked":0,"restricted impersonation":0,"individual              views":1,"individual fow":1,"strict token management":1,"players              receive campaign macros":1,"hide map select ui":1,"movement              metric":"ONE_TWO_ONE","using ai":1,"vbl blocks              movement":1,"timeInMs":1635617819237,"timeDate":"2021-10-30              14:16:59","gm":["Mike"],"hosting server":1,"personal              server":0,"useWebRTC":0,"usePasswordFile":0,"server name":"","port              number":21135} »

**Comment by Phergus** [comment]
> Technically it has the button for players but does not create any entries for them to click on. I see your point though, I'll get that taken care of. 

It didn't click with me that the button on full-screen wasn't showing the map names for players but it is probably better if it is either hidden or disabled.

> Also, I had thought that was the intention for the GM but that can easily be altered.

Hiding it from the GM seems like an unnecessary step and could potentially be an issue if a problem with the custom macros for handling map switching keeps the GM from doing so mid-game.

> Would a macro to show and hide the map select button for trusted macros be appreciated instead?

Can't think of a reason to not have one.

**Comment by michaelperino** [comment]
-Fixed map select UI being hidden for GMs. 
-Hid button in fullscreen instead of just hiding entries. 
-Renamed internal method to more closely match others. 
-Introduced [toggleMapSelectButton()] to allow GMs to hide their map select button. Returns 0 or 1.

If all those changes sound good as is, I'll submit a PR when I get home. The more I look at it the more I think I should just have setMapSelectButton(flag) instead of toggling but I'm open to opinions.

**Comment by Phergus** [comment]
That sounds good and I agree that the more explicit function of `setMapSelectButton()` would be preferred.

**Comment by Phergus** [comment]
Tested.

- Select Map button no longer hidden for GMs.
- Select Map button now hidden on full screen view for players.
- `setMapSelectButton()` function working as expected.
