### ISSUE TITLE
Comment inside loop 

### ISSUE THREAD

**Issue by JambonII** [RPTools/maptool#2778]
**Describe the bug**
Some character in comment inside loop brock the code

Apostrophe '
Double prime "

```
[r, if( 1 == 1), CODE:
	{
		<!--- it's broken --->
		Hello world !
	}
]
```

```
[r, if( 1 == 1), CODE:
	{
		<!--- This one work --->
		Hello world !
	}
]
```

**Comment by FullBleed** [comment]
It's the apostrophe.

You need to be careful how you use single and double quotes in MT script.

One of the many reasons you should comment like this:

`[r, if( 1 == 1), CODE:
	{
		[h: ""]
		Hello world !
	}
]`

**Comment by Phergus** [comment]
MT script doesn't have comments.  Everything is treated as code and run through the parser.
