### ISSUE TITLE
Mousewheel events do not reach HTML overlays like other mouseevents do

### ISSUE THREAD

**Issue by BlackwingNL** [RPTools/maptool#2779]
**Describe the bug**
Within the HTML5 overlays it's possible to attach event-listeners to mouse events with the javascript contained within the overlay. mouse events like mousemove and mousedown event listeners work in the javascript, but wheel events are never triggered. The wheel events never reach the overlay.

**To Reproduce**
1. create a macro createEventOverlay with the following contents:
```
[overlay("event_test"): {
<html>
<head>
</head>
<body id="body">
<p>event text: <span id="eventtext"></span></p>

<script type="text/javascript">
	document.getElementById("body").addEventListener("mousemove", onMouseMove);
	document.getElementById("body").addEventListener("mousedown", onMouseDown);

	<!-- DOES NOT WORK. wheel event seems to be captured before reaching the overlay -->
	<!-- onWheel is never triggered. -->
	document.getElementById("body").addEventListener("wheel", onWheel); 
	
	function onMouseMove(event) [r: "{"]
		<!-- finally show the link we have just used in the eventtext in the left-upper corner -->
		document.getElementById("eventtext").innerHTML = "Mouse move event triggered";
	[r: "}"]

	function onMouseDown() [r: "{"]
		document.getElementById("eventtext").innerHTML = "Mouse down event triggered";
	[r: "}"]

	function onWheel() [r: "{"]
		<!-- onWheel is never triggered. -->
		document.getElementById("eventtext").innerHTML = "Mouse Wheel event triggered";
	[r: "}"]
		
</script>
</body>
</html> 
 } ]
```
2. activate the macro
3. In the map area move the mouse around. In the top left corner it should say "event text: Mouse move event triggered"
4. Without moving the mouse click somewhere in the map area. In the top left corner it should say "event text: Mouse down event triggered"
5. Whilst over the map-area, use the scroll-wheel. Notice the text "Mouse Wheel event triggered" never appears, which should happen if the `onWheel()` attached to the wheel event would be executed. The zoom factor (if using the wheel up or down) does change showing the action does reach Maptool itself.
6. After verifying the above create another macro containing just the following line of code: `[h: closeOverlay("event_test")]` and run that macro to clean up the overlay.

**Expected behavior**
When using the mousewheel in the map region the a javascript listener for the "wheel" event should be triggered.

**MapTool Info**
- Version: 1.9.2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version [10, 20.04]

**Additional context**
I have already found the source of the problem in the Maptool sources. I have created a fix for the problem an would like to contribute that.

**Comment by kwvanderlinde** [comment]
I think this is essentially the same as #2357. Wheel events and non-left-clicks never reach the overlay, and even left clicks depend on `--pointermap` (which defaults to `pass` for most elements).

**Comment by BlackwingNL** [comment]
I have just tested with 1.9.2:
- mousedown/mouseup events reach the overlay just fine for left, middle and right button
- click event only functions for left (primary) mouse button. See [https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event), actually works in Maptool for middle (scrollwheel) button
- The cause for wheel event not being transmitted to the overlay is that in JavaFX these are actually scroll events and not mouse events and only mouse events for filtered through.

**Comment by Phergus** [comment]
@kwvanderlinde so does this address everything in issue #2357.

**Comment by kwvanderlinde** [comment]
Not entirely. Scrollable elements can now be scrolled with the mouse wheel, but that also zooms the map. I think `--pointermap` should still be updated to allow blocking wheel and other mouse events from being passed to the zone.

**Comment by Phergus** [comment]
@BlackwingNL  Using your macro code above I'm not seeing a mouse-down event for the middle mouse button.  Should I?

Left and right come through as does the wheel when scrolling.

**Comment by BlackwingNL** [comment]
@Phergus Its should, and it does here.

It could be that your mousedown event is immediately followed by a mousewheel event if you have a free-running mousewheel (mine I can switch between stepped and free).

Remove the event listeners for mousemove and wheel events and leave just the listener for mousedown. Then (re)create the overlay and press _only_ the middle mouse button. This should get you the "Mouse down event triggered" text

**Comment by Phergus** [comment]
Hmm.  It's an older MS mouse that is stepped.  MMB works in other apps.

Added `event.button` to the output and the left & right show up as `0` & `2` immediately. I have to hold down the MMB for short bit and then I get the `1` for the MMB.  Probably just something weird about this old MS mouse.  I'll have to try a different one.

**Comment by Phergus** [comment]
Grabbed a newer mouse from the laptop bag and the MMB on it registers immediately.

**Comment by BlackwingNL** [comment]
Odd, but at least it works

**Comment by Phergus** [comment]
Tested that right, left & middle mouse-buttons events and scroll events are received by overlays.  Still able to pan and zoom map as well as select and move tokens.  Right mouse-button menu working on tokens.
