### ISSUE TITLE
Conversion from AWT geometry to JTS geometry is not robust.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2783]
**Describe the bug**
An AWT `Area`'s `PathIterator` can yield near-zero length segments that are seen as self-intersections by JTS. This can cause surprising behaviour for nested polylines, as JTS cannot consistently identify the interior and exterior of a shape. It also makes VBL/MBL sensitive to changes in the JTS implementation.

**To Reproduce**
JTS 1.16.1 appears to be relatively lax about the sort of geometry we send it. I haven't been able to reproduce the issue unless on JTS 1.18.x.

1. Check out commit `c82be16e2f7d75471debb377fe55f15b6cb89e32`.
2. Run MapTool: `./gradlew run`
3. Import this DungeonDraft map: 
[50x50 Cave 100px.dd2vtt.zip](https://github.com/RPTools/maptool/files/6704800/50x50.Cave.100px.dd2vtt.zip)
4. Draw a hollow rectangle of MBL around the entire map.
5. Place a token inside the caves.
6. Try dragging the token. Notice that the path length remains at 0.

**Expected behavior**
It should be possible to use AI navigation with polylines under JTS 1.18.

**Screenshots**
By converting the JTS geometry back to AWT geometry, we can see that JTS considers the caves to be solid: ![broken-jts-geometry](https://user-images.githubusercontent.com/7492219/123167259-2ab32d80-d42b-11eb-99ea-c258125a17c4.png)

We should expect that the caves are actually hollow like this: ![expected-jts-geometry](https://user-images.githubusercontent.com/7492219/123167323-3e5e9400-d42b-11eb-9952-6def02b81e8b.png)

**MapTool Info**
- Version: develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Additional context**
This issue was revealed after an attempt to upgrade to JTS 1.18.1 in #2589, and that was reverted shortly after in #2759. Fixing this will allow upgrading to future versions of JTS.

**Comment by Phergus** [comment]
Tested with JTS 1.18.1.  Pathfinding is working again on large, complex maps with the upgraded JST lib.
