### ISSUE TITLE
Macros moved/copied between Macro Groups & Panels are always player-editable

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#2785]
**Describe the bug**
When moving a macro between a macro group, or when copying a macro from one panel to another, the 'Allow Players to Edit Macro' checkbox is always reset to 'checked'.

**To Reproduce**
1. Create a campaign macro and edit it so 'Allow Players to Edit Macro' is **unchecked**. Rename `Locked` or similar.
2. **Copy to Token Error**: Create a token.
3. Drag the `Locked` macro to the token's Selection panel. It will copy. 
4. Edit the copied `Locked` macro on the token.
5. See error: 'Allow Players to Edit Macro' is **checked**.
2. **Move to Group Error**: Create a second campaign macro in a new macro group from the first.
3. Drag the `Locked` campaign macro to the new macro group. It will move from one group to another (neat!).
4. Edit the moved `Locked` macro on the campaign panel.
5. See error: 'Allow Players to Edit Macro' is **checked**.

**Expected behavior**
All settings of the moved/copied macros are the same.

**MapTool Info**
- Version: 1.9.2
- Install: Upgrade 

**Desktop (please complete the following information):**
 - Windows 10
 
**Additional context**
- Duplicating a macro from the macro button context menu works correctly / does not do this.
- The current behavior is arguably reasonable for players connected to a server when dragging macros from the Campaign Panel to their own token panels. It is complicated here - players shouldn't be able to view the code of locked/trusted macros, but they also shouldn't be able to put a trusted macro on a token it wasn't intended for.

**Comment by adyoungblood** [comment]
Ah. That would be my fault, I'm the one who made moving the default. I'll look into it right now!

**Comment by Phergus** [comment]
I bet Melek has his preferences set to Players Can Edit Macros.

**Comment by adyoungblood** [comment]
This is interesting, the code is already written to use the Players Can Edit Macros setting when creating a new macro, instead of whatever the setting was on the original macro. In that sense, I think this issue would be more of fix than a change?

**Comment by adyoungblood** [comment]
> players shouldn't be able to view the code of locked/trusted macros, but they also shouldn't be able to put a trusted macro on a token it wasn't intended for.

Looking at the code, it should be possible to stop players from even moving trusted macros, while fixing the original issue and retaining intended functionality. The only question is how to convey to a player that that macro cannot be moved (I'm thinking some kind of exception).

**Comment by cwisniew** [comment]
A dialog with a message (from the i18n property file of course) is much more preferable then an exception message

**Comment by adyoungblood** [comment]
One last thing to iron out, what should be done if a player has Players Can Edit Macros set to false? At the moment, it does what is technically correct and allows them to create "(new)" macros that they cannot edit or delete. That might be a separate issue, but at this point I'm going over everything to do with macro editability in the scope of this fix.

**Comment by Phergus** [comment]
My opinion is that if a GM is copying or moving a macro the original state of the setting should be preserved no matter the destination.

If a Player connected to a server with the Allow Players To Edit Macros preference _disabled_:
1. attempts to move a macro between groups on an owned token - currently allowed
2. attempts to move a macro between owned token(s) - currently allowed via Selected panel
3. attempts to copy a macro on their owned token(s) - currently allowed with ctrl-drag - leave as is
4. attempts to copy a macro on the Campaign panel - should be blocked with warning - **currently can do this**
5. attempts to move a macro on or from the Campaign panel - should be blocked with warning - **currently can do this**
6. attempts to copy a macro from the Campaign panel to owned token(s) with regular drag - not currently allowed 
7. attempts to copy a macro from the Campaign panel to owned token(s) with regular drag - not currently allowed 
8. attempts to copy a macro from the Campaign panel to owned token(s) with ctrl-drag - currently allowed
- In all cases the state of Player Can Edit setting should be preserved.

Cases 4 & 5 are particularly problematic as the Campaign panel on the player client shows the change but not the GM client.
![image](https://user-images.githubusercontent.com/34379254/123335484-c1521e00-d501-11eb-823f-a68b97855a1b.png)

Cases 7 & 8 - one or the other is wrong.  I don't think either should be allowed.  A player dragging a macro to their token is assuming that the campaign macro isn't going to be changed by the GM at some point.  If the Campaign macro is nothing more than a call to a UDF/macro on a lib:token then that may be a safe assumption but maybe not.  At the very least the GM should get a notice when a player copies a campaign macro to their token.

If a Player connected to a server with the Allow Players To Edit Macros preference _enabled_:
- I'd argue it should be the same as above.

**Comment by adyoungblood** [comment]
Macro behavior is now consistent with Phergus's list, although the discrepancies between the Campaign panel and other panels is a separate issue (#2788). Would anyone happen to know where I should document these changes (i.e. any important wiki pages)?

**Comment by Phergus** [comment]
I don't believe we have a section anywhere dedicated to the movement of macros between panels.  Perhaps it should go in a sub-section of the Panels  section of the Intro to Macro Writing  page:

https://wiki.rptools.info/index.php/Introduction_to_Macro_Writing#The_Macro_Panels

What do you think @melek ?

Maybe it's own section immediately following called _Managing Macros In Panels_?

**Comment by Phergus** [comment]
Tested.  Dragging macros within panels and between panels working as described.  State of `Allow Players to Edit Macro` preserved on copy/move.

**Comment by melek** [comment]
I think that for documentation, *Managing Macros In Panels* or *Dragging Macro Buttons* could be its own niche page that we link to from a couple places. I would reference this from

* https://wiki.rptools.info/index.php/MapTool_User_Interface#Macro_Panels
* https://wiki.rptools.info/index.php/Introduction_to_Macro_Writing#The_Macro_Panels
* https://wiki.rptools.info/index.php/Trusted_Macro

@adyoungblood if you want to try to create the basic page (pick the name you think is most appropriate) let me know and I'll do the crosslinking. If you don't have time let me know and I'll put a basic page up.

**Comment by bubblobill** [comment]
Don't know if this is related. When a player drags a token onto the map, the permissions are reset. On the surface this is the same issue. Does the fix also fix this issue?

**Comment by adyoungblood** [comment]
My initial reaction is no, although you'll have to be more specific. Is the player dragging a .rptok file onto the map? If that's the case, I'm not sure how permission data is saved if at all. If they're dragging an image into a map to create a new token each time, then no, permissions wouldn't be saved there either.

And yeah, Melek, I'll create a wiki page in the morning, probably named _Managing Macros In Panels_ like you said. The topic definitely bears explaining in depth.

**Comment by bubblobill** [comment]
Yep. When dragging .rptok files onto the map, the _Allow Players to Edit Macro_ value in the file is not preserved **for players**.
Works fine for GMs, but gets altered for players.

**Comment by Phergus** [comment]
Confirmed.  Was working correctly in 1.7.0 and broken in 1.8.5.  This should go to a new issue.

**Comment by Phergus** [comment]
Issue #2805 opened for dropped token issue.

**Comment by adyoungblood** [comment]
I've created the documentation [here](https://wiki.rptools.info/index.php/Managing_Macros_in_Panels), and added the links to the pages Melek mentioned.

**Comment by Phergus** [comment]
Succinct and complete.  If users need more later it can be added.  Thanks!
