### ISSUE TITLE
Macros added to Campaign/GM panel (new or moved) do not show up for others until a change is made

### ISSUE THREAD

**Issue by adyoungblood** [RPTools/maptool#2788]
**Describe the bug**
Title. Whether a macro is created with the New Macro button or moved/copied into the Campaign/GM panel, it will not be visible to other players (or even the GM!) until that macro or another one is edited. I believe the trigger to sync up again (i.e. become visible) is a call to the save() method in MacroButtonProperties.java (and subsequently the saveMacroButtonProperty method in Campaign.java).

**To Reproduce**
1. Open up two clients
2. Have one host a server, have the other join that server
3. With the GM client, create a new macro in the Campaign panel
4. (Bug) observe that in the player client, that macro does not show up
5. Open the GM client, open the newly created macro, then click OK
6. Observe that in the player client, the macro now shows up
7. Repeat steps 3 through 6 except instead of creating a macro inside the Campaign panel as the GM, actually drag any macro into the Campaign panel and observe the same results

**Expected behavior**
The Campaign panel (or any panel, for that matter, although I haven't tested any others) should sync no matter what kind of update happens to the buttons inside of it.

**MapTool Info**
- Version: 1.9.2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Irarara** [comment]
This is essentially the same issue as #1745, right?

**Comment by Phergus** [comment]
The same except we have a GM panel now (I think it was added after that issue) so the problem has grown.

**Comment by adyoungblood** [comment]
Oh, thanks for the catch. I'll close this one, then.
