### ISSUE TITLE
Drawing Macro Features (getDrawings, renameDrawing)

### ISSUE THREAD

**Issue by quantumqic** [RPTools/maptool#2801]
I would like to see a pull request for all the available drawings that do and don't have a name by returning a list of drawing ids.
I would like to see the ability to rename drawings using their drawing id.

**Is your feature request related to a problem? Please describe.**
There is currently no ability to do the two requested options through macros.

**Describe the solution you'd like**
I would like a function, possibly named getDrawings(layer, mapName), that returns a json array of drawingIDs cooresponding to all drawings on that layer and on that map so that drawings without a name can be found and modified.

I would also like a function, possibly named renameDrawing(DrawingID, name, mapname) or nameDrawing(DrawingID, name, mapname), which allows one to set the name of a given DrawingID on a map.

**Describe alternatives you've considered**
There isn't alternatives through macros since the getDrawingProperties macro currently does not return something in an editable state.

**Comment by Phergus** [comment]
Reworking `findDrawings(mapName, name[, delim])` so that passing `"*"` for the drawing name will return all drawings on the map.

Adding `setDrawingName(map, guid, name)` to add/rename a drawing.

**Comment by quantumqic** [comment]
Sweet! thank you very much.

**Comment by Phergus** [comment]
Documentation added/updated.
[findDrawings()](https://wiki.rptools.info/index.php/findDrawings)
[setDrawingName()](https://wiki.rptools.info/index.php/setDrawingName)

**Comment by Phergus** [comment]
No further comments. Closing.
