### ISSUE TITLE
GM Name for Map visible to players

### ISSUE THREAD

**Issue by michaelperino** [RPTools/maptool#2802]
**Describe the bug**
User within RPTools forum described an issue where players received spoilers by seeing the GM name in the map loading screen.

**To Reproduce**
Look while maps are loading with lots of assets.

**Expected behavior**
Players will not see GM name.

**MapTool Info**
- Version: 1.9.2
- Install: Unsure

Feel free to assign this to me.

**Comment by Phergus** [comment]
Tested.  With fix applied Players only see the Display Name while the GM sees the GM Name while maps are loading.
