### ISSUE TITLE
Macros on Player-dropped Tokens have Can Edit flag set to True.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#2805]
**Describe the bug**
If a player drops a token containing macros onto a map the Allow Players to Edit Macros flag is set to TRUE.

**To Reproduce**
1. Start server.
2. Start second client and connect as player.
3. On player client drop token with macros onto map. (see attached example token)
4. Observe that Can Edit flag is set to TRUE.

**Expected behavior**
Expect settings to be preserved.

**MapTool Info**
- Version: 1.8.5+
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Token with two macros. One with edit permission and one without.  (Remove `.zip` from filename.)
[Permissions Test.rptok.zip](https://github.com/RPTools/maptool/files/6721708/Permissions.Test.rptok.zip)

Originally reported in comments of #2785 .

**Comment by cwisniew** [comment]
This is in intentional. Preserving then as false would allow players to create trusted macros by saving tokens as GM (not attached to server) and then saving tokens and later drag and drop on to map

Players should never be able to create macros where allow players to edit is false
