### ISSUE TITLE
Bad data dir paths result in an unhelpful error message when launching Maptool

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#2812]
**Describe the bug**
If `MAPTOOL_DATADIR` is set to a bad path or the data dir otherwise can't be created the user gets the message "Failed to launch JVM" when launching Maptool and no other information. Exceptions during launch are already supposed to be handled so that more meaningful errors are returned (#1678), but in this case they slip through.

**To Reproduce**
1. In `MapTool.cfg`, set the `-DMAPTOOL_DATADIR` System Property to a bad path (something with an illegal character or that you don't have write access to, etc.)
2. Launch Maptool
3. Observe that "Failed to launch JVM" pops up.

**Expected behavior**
A meaningful error message should be displayed.

**Screenshots**

**MapTool Info**
- Version: develop/1.9.2 (but probably basically any)
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Irarara** [comment]
I have a fix for this, but in testing it I noticed that it will show the error message but not actually exit, it will just continue to run in the background. Seeing as an exception caught at that point is probably a fatal error, it seems like it should just explicitly exit at that point. Is there any reason this might be a bad idea?

**Comment by Phergus** [comment]
I can't think of a reason to leave it running at that point.  Explicitly exiting would seem to be the correct action.

**Comment by Phergus** [comment]
Tested. Error message is shown and MT exits as it should.

**Comment by Azhrei** [comment]
Apparently `!This*Can't@be(valid)` is a valid directory name on macOS.  MapTool created that under my home directory and populated it with data.  Changing to a name that is guaranteed to fail does, in fact, fail.

The error message uses the phrase "environment variable" and that's incorrect; `MAPTOOL_DATADIR` is only recognized as a Java system property (although using an env var makes a _LOT_ of sense).  I suggest changing the message until such time as it becomes an actual env var (if ever).

**Comment by Phergus** [comment]
We also shouldn't use contractions like `can't` in error messages.

Error message ID:  msg.error.unableToCreateDataDir
> Can't create the data directory "{0}".  Try manually specifying the data directory by setting the environment variable "MAPTOOL_DATADIR".  Search our forums for that name if you need help.

Maybe:
> Unable to create the data directory "{0}".\n\nCorrect the definition for the system property "MAPTOOL_DATADIR" in the MapTool.cfg file.  Go to the RPTools forums or MapTool Discord server for help.

**Comment by Azhrei** [comment]
Tested on Ubuntu 18.04 and it fails properly.

**Comment by Phergus** [comment]
Tested on Windows, macOS and Linux.
