### ISSUE TITLE
Multiple strings missing from translation file

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#2837]
**Describe the bug**
The token editor dialog is missing multiple keys in the properties file.  (Not sure I got the tags right for this issue.)

**To Reproduce**
Steps to demonstrate missing keys:
1. Start MapTool
2. Turn on debugging for the I18N module via `[setLevel("net.rptools.maptool.language.I18N", "DEBUG")]`
3. Drag an image to the map and double-click it.
4. The log file will show which keys are not being found.

**MapTool Info**
- Version: 1.9.2 (and probably 1.5+; all that have token VBL or HeroLab support)
- Install: New

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.4 (Big Sur, fully updated)

**Additional context**
These are the keys found by scanning the `maptool.log` content.  The order shown here is the order they appear in the log file, but sorting them shows some strings occur multiple times (the empty string, `Enter raw text...`, `Expression: `, `Find`, and `Search the statblock...`).
```
Cannot find key 'Image' in properties file.
Cannot find key 'propertiesTable' in properties file.
Cannot find key 'VBL Preview' in properties file.
Cannot find key '' in properties file.
Cannot find key 'Adjust the sensitivity to the color match that will be used to generate VBL, values 0-255 with 0 being an exact color match.' in properties file.
Cannot find key 'ownerShipLabel' in properties file.
Cannot find key '' in properties file.
Cannot find key '' in properties file.
Cannot find key '' in properties file.
Cannot find key '' in properties file.
Cannot find key 'MULTIPLY' in properties file.
Cannot find key '' in properties file.
Cannot find key '100%' in properties file.
Cannot find key 'Charsheet' in properties file.
Cannot find key 'Layout' in properties file.
Cannot find key 'Portrait' in properties file.
Cannot find key 'HTML' in properties file.
Cannot find key 'XML' in properties file.
Cannot find key 'TEXT' in properties file.
Cannot find key 'Images' in properties file.
Cannot find key 'Expression: ' in properties file.
Cannot find key 'Enter raw text, a regular expression or an xPath expresstion to search the statblock for.' in properties file.
Cannot find key 'Find' in properties file.
Cannot find key 'Search the statblock using the expression provided.' in properties file.
Cannot find key 'xmlStatblockRTextScrollPane' in properties file. 
Cannot find key 'Find' in properties file.
Cannot find key 'Search the statblock using the expression provided.' in properties file.
Cannot find key 'Expression: ' in properties file.
Cannot find key 'Enter raw text, a regular expression or an xPath expresstion to search the statblock for.' in properties file.
Cannot find key 'textStatblockRTextScrollPane' in properties file.
Cannot find key 'Set as Token Handout' in properties file.
Cannot find key 'Set as Token Image' in properties file.
Cannot find key 'Set as Token Portrait' in properties file.
Cannot find key 'EditTokenDialog.label.hero.portfolio ' in properties file.
Cannot find key 'summaryText' in properties file.
Cannot find key 'portfolioLocation' in properties file.
Cannot find key 'lastModified' in properties file.
Cannot find key 'Ally?' in properties file.
Cannot find key '' in properties file.
Cannot find key '<html>Refresh data from Hero Lab<br/>
```

**Comment by FullBleed** [comment]
I saw someone show a screen shot from a non-English version and noticed that the "Map not visible to players" screen flag was all in English.  It was the only English on the screen so I suspect that may be missing from the translation file, too.

**Comment by ChrisCookOC** [comment]
I'm having a go at this one currently.

**Comment by ChrisCookOC** [comment]
Might be worth considering whether we should be logging the cases where we fail to find a translation for the empty key. I'm not entirely convinced the empty-string should ever be calling internationalisation code though, so perhaps this should be handled at the root cause.

**Comment by Irarara** [comment]
For some of these strings like "summaryText", "lastModified", etc., are these actually visible to users? Because they look like internal names that are getting processed because they're part of a form, not like strings that should be localized.

**Comment by Phergus** [comment]
More strings added to translation file.  Fixes for protobuf initialization issues.
