### ISSUE TITLE
Has Sight always ticked for PC tokens

### ISSUE THREAD

**Issue by Xeddar** [RPTools/maptool#2849]
**Describe the bug**
When a token is set as a PC in the top right of the properties and saved, it automatically ticks "Has Sight" for the token every time the properties window is closed. This used to occur when the token was first set to PC, but it was possible to untick "Has Sight" and leave it off. Now, it appears to be ticking "Has Sight" regardless and it's not possible to has it off. This makes maps with manually revealed fog of war impossible to use

**To Reproduce**
1. Create a new campaign and token
2. Note that "Has Sight" is unticked
3. Change the token to be a PC
4. Save the properties, reopen the properties and note that "Has Sight" is ticked
5. Untick "Has Sight", save and close the properties
6. Reopen the properties, note that "Has Sight" has reticked itself - this is the bug

**Expected behavior**
"Has Sight" should remain unticked once it has been unticked

**MapTool Info**
- Version: 1.9.2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
@Irarara I think this broke with your change adding i18n support for types.

**Comment by Irarara** [comment]
OK, I'll look into it.

**Comment by Phergus** [comment]
Looks like line 610:
`    token.setType((Token.Type) getTypeCombo().getSelectedItem());`

Is going to force any PC token to have sight on close of the dialog overriding the state of the checkbox.

**Comment by Irarara** [comment]
So it is. I wasn't aware setting that flag was a side effect of `setType()`, whoops. Easy fix then.

**Comment by Phergus** [comment]
Tested.  Has Sight setting on PCs & NPCs tokens behaving as expected when exiting Edit Token dialog.  Macro functions for Sight working as expected.
