### ISSUE TITLE
Unexpected Error when add a Bar

### ISSUE THREAD

**Issue by HUGO753** [RPTools/maptool#2861]
**Describe the bug**
It happens when you add a bar, maybe it's the translation (PT-BR)

**To Reproduce**

1. Get the translation (Brasil)
2. Go to 'Editar'
3. Go to 'Propriedades de Campanha...'
4. Go to 'Barras'
5. Just add any Name(Nome), Tipo: Two Tones
6. Click at Adicionar (Add)
7. See error

**Expected behavior**
Just to add a bar

**Screenshots**
![image](https://user-images.githubusercontent.com/42175321/125542262-0a336498-2503-42d4-8dc5-969e9175b58b.png)
You can see the: net.rptools.maptool.client.ui.token.BarTokenOverlay.Side.SUPERIOR <-- This shoudn't happen at translation

**MapTool Info**
- Version: 1.9.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by kwvanderlinde** [comment]
You're right about the language, or rather the fact that the translated text is not the same as the internal enum constants. This happens to work in English but will fail for other languages. We can even trigger it English by modifying the translated text.

Looking in the history it seems to go back to this change where the campaign properties dialog was updated to use translation  strings: aece9909cdfec0d1b386ea81e26689071ca89c55.

**Comment by Phergus** [comment]
Tested.   Bar locations with translations no longer cause an exception.
