### ISSUE TITLE
input() does not allow Cyrillic chars

### ISSUE THREAD

**Issue by Oreolek** [RPTools/maptool#2864]
add this as a new macro:

```
[h: Status = input(
  
"tab0 | Атрибуты | | TAB |",
"B|" + B + "|Имя",
"A|" + A + "|PC или NPC|CHECK"
)]
[h: abort(Status)]
```

and there will be ???? characters instead of Cyrillic text

maptool 1.9.3, ubuntu linux 20.04, maptool installed from DEB package

**Comment by Phergus** [comment]
@Oreolek please follow the templates when creating issues.

I believe you mean `input()` instead of `abort()`.  `abort()` doesn't display or output anything.

**Comment by Oreolek** [comment]
Since this bug is [apparently 7 years old](https://forums.rptools.net/viewtopic.php?t=25275) I'll just copy the workaround:

- Make a new Lib:Cyrillic token
- Set one of its properties to `hi=Привет;bye=Пока` or something, no quotes
- use the JSON parser like this where `dictionary` is your property:
```
[h: strings = json.fromStrProp( getProperty("dictionary", "Lib:Cyrillic") )]
[h: Status = input(
  
"tab0 | " + json.get(strings, "attr") +" | | TAB |",
"B|" + A + "|" + json.get(strings, "name"),
"A|" + B + "| "+ json.get(strings, "pc") + " |CHECK"
)]
[h: abort(Status)]
```

**Comment by Phergus** [comment]
I fixed the subject for you.

**Comment by Phergus** [comment]
This is a known limitation of the current macro parser and is not likely to get fixed in the near term.  The workaround above and similar ones can be used until the parser is replaced.
