### ISSUE TITLE
PR #283 merge breaking existing macros that use abort()

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#287]
It seems that macros that call `abort()` are causing a popup from the MapToolVariableResolver when the Java code tries to reference the `macro.catchAbort` variable.  Since the variable resolver has a parameter now to turn off those prompts, the code should probably be using that.

**Comment by JamzTheMan** [comment]
Beat me lol

@oliver-szymanski I opened up my existing campaign and got a 
![image](https://user-images.githubusercontent.com/8051654/54087350-f1208c00-431f-11e9-98b7-9fbda28d1d48.png)

**Comment by oliver-szymanski** [comment]
Will check and fix

**Comment by oliver-szymanski** [comment]
Fix in https://github.com/RPTools/maptool/pull/290

**Comment by Azhrei** [comment]
PR merged

**Comment by Azhrei** [comment]
This merged code is throwing NPE when the `macro.catchAbort` is set to 1 and the `abort` function is called with an empty roll option.  It appears that the code is trying to create a tooltip from the output and there isn't any, hence the NPE.  Put this into a macro and run it; when the popup appears, enter `1` and it works, but enter `0` and it throws an NPE.
```
[macro.catchAbort = 1]
[t: abort(var)]
<br>
More text...
```

**Comment by oliver-szymanski** [comment]
on it

**Comment by oliver-szymanski** [comment]
Sadly I have to raise a new PR as I deleted the nerps fork and so cannot reuse the original PR.
Fix in https://github.com/RPTools/maptool/pull/294

**Comment by JamzTheMan** [comment]
Are we reverting this PR for this release or merging #294? I honestly don't know where we are with the testing?

**Comment by Azhrei** [comment]
AFAIK, aliasmask was happy with the proposed API but didn't have a build that he could use to test it.  IMO, it should be merged and s build done so he can try it out.  It's pretty easy to click the Revert button if it doesn't work out...

**Comment by JamzTheMan** [comment]
k, I'll merge it and create a build so testing can be done
