### ISSUE TITLE
RESTful functions do not allow headers except when passed as literal strings.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2875]
**Describe the bug**
When adding headers to [REST.*](https://wiki.rptools.info/index.php/Category:RESTful_Function) functions, the headers must be supplied as a string to the function call. Passing a variable or the results of [JSON functions](https://wiki.rptools.info/index.php/Category:JSON_Function) causes CCEs to be thrown.

**To Reproduce**
1. Create a new global macro called "REST headers" with a `REST.get()` call to a known endpoint with extra headers:
   ```
   <pre>
   [r: json.indent(REST.get('http://google.ca/', '{"Accept": ["application/json"]}', 1), 2)]
   <pre>
   ```
2. Click on the "REST headers" button and observe good results being sent to chat.
3. Edit the macro to first store the headers in a variable:
   ```
   <pre>
   [h: headers = '{"Accept": ["application/json"]}']
   [r: json.indent(REST.get('http://google.ca/', headers, 1), 2)]
   <pre>
   ```
4. Click on the "REST headers" button and observe a CCE being printed in chat:
   ```
   java.lang.ClassCastException: class com.google.gson.JsonObject cannot be cast to class java.lang.String (com.google.gson.JsonObject is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap') error executing expression json.indent(REST.get('http://google.ca/', headers, 1), 2).
   Error trace : REST headers@global
   ```
5. Edit the macro to try `json.set()`/`json.append()` for building the headers:
   ```
   <pre>
   [r: json.indent(REST.get('http://google.ca/',
                            json.set('{}', 'Accept', json.append('[]', 'application/json')),
                            1),
                   2)]
   <pre>
   ```
6. Click the "REST headers" button and again observe a CCE:
   ```
   java.lang.ClassCastException: class com.google.gson.JsonObject cannot be cast to class java.lang.String (com.google.gson.JsonObject is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap') error executing expression json.indent(REST.get('http://google.ca/', json.set('{}', 'Accept', json.append('[]', 'application/json')), 1), 2).
   Error trace : REST headers@global
   ```

**Expected behavior**
Headers should be able to be stored in variables or built using JSON functions before being passed to the RESTful functions and should function as if a literal JSON string was passed to the functions.

**MapTool Info**
- Version: 1.9.3
- Install: Upgrade [1.9.2]

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Comment by Phergus** [comment]
@kwvanderlinde would you verify that the functions are working as expected with current develop code.

**Comment by kwvanderlinde** [comment]
Looks good. I've verified that all `REST.*` functions now work with headers being supplied as
-  literal strings
- strings stored in variables
- JSON function results stored in variables
- inline JSON function calls

**Comment by Phergus** [comment]
Thanks!
