### ISSUE TITLE
Add macro functions for token Flipped X/Y/Iso settings

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#2879]
**Is your feature request related to a problem? Please describe.**
Currently lacking functions to get the status and flip tokens on the X/Y axis as well as for Iso grids.

**Describe the solution you'd like**

- isFlippedX() - gets Token property for flipped on X axis
- isFlippedY() - gets Token property for flipped on Y axis
- isFlippedIso() - gets Token property for flipped for Iso grids
- flipTokenX() - flips token on X
- flipTokenY() - flips token on Y
- flipTokenIso() - flips token for Iso grids

All functions to work on current token or with token id and optional map name.

**Describe alternatives you've considered**
None.

**Comment by Phergus** [comment]
@melek  I think you brought this up.  Comments?

**Comment by melek** [comment]
It is often desirable to store how a token looks so that you can reset its position later, or to otherwise set up a token's visual appearance with macros.

Flipped status is one of the only, if not the only, visual token parameter that doesn't have corresponding macro functions. Exposing flipping to macros may also enable some cool uses of flipping that we haven't thought of. :)

**Comment by Phergus** [comment]
So the functions as described are good enough?

Note that the flipToken functions toggle whatever the current setting is just like the right-click menu options because they call the same code.  If you want to explicitly set the flipped status then I'll have to add some new methods and update types to the Token class.

**Comment by melek** [comment]
Interesting - I think a common pattern for me would quickly emerge:

```
[if(isFlippedX() != MyStoredFlipStatus): flipTokenX()]
```

So, in that case, `flipTokenX( MyStoredFlipStatus )` would be a nice little shortcut - not at all necessary, but nice. Perhaps it could work like this:

```
flipTokenX() --- Toggle flip
flipTokenX("") --- Toggle flip
flipTokenX(0) --- Unset flip if flipped
flipTokenX(1) --- Flip token if not flipped
```

Then Token ID and Map could be second and third optional paramters, like most other similar functions.

**Comment by melek** [comment]
Regarding the overall suite of functions, the basic getting and setting stuff is all there, and even if I have to check flip status before flipping with an if statement, these would do great to expose the flip settings.

If setting the flip status explicitly were an option, I don't know if separating toggling and flipping (like a `flipTokenX` and `setTokenFlipX`) would be better than a scheme like I proposed in my last comment; I kind of like using the same function for both to reduce the amount of functions, but it would work a little differently than other functions so I would trust whomever implements it to make a call.

**Comment by Phergus** [comment]
I was thinking about having both toggle flip and explicit set flip functions but decided against it to avoid the bloat of extra functions.  They can be added later if needed.

For now simple `if()` checks like you mentioned:
```Java
[h, if(isFlippedX() == 1):flipTokenX()]
```
will explicitly unflip and changing `1` to `0` will flip.

So all 6 functions will look like this:
```
flipTokenX([token name/id [, map name]])
```

**Comment by Phergus** [comment]
Wiki docs added:
[flipTokenX()](https://wiki.rptools.info/index.php/flipTokenX)
[flipTokenY()](https://wiki.rptools.info/index.php/flipTokenY)
[flipTokenIso()](https://wiki.rptools.info/index.php/flipTokenIso)
[isFlippedX()](https://wiki.rptools.info/index.php/isFlippedX)
[isFlippedY()](https://wiki.rptools.info/index.php/isFlippedY)
[isFlippedIso()](https://wiki.rptools.info/index.php/isFlippedIso)

**Comment by Phergus** [comment]
No further comments.  Closing.
