### ISSUE TITLE
Change Campaign Properties Light Help Text

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#288]
Change from 

> shape: An optional shape for the light emanation. Can be circle (default), square, or cone (cones also have an arc=angle field). Shapes apply from the point they are included in the definition until the end of the definition or until another shape is specified. This means multiple light shapes can be created under a single name and turned on or off as a unit.

to

> shape: An optional shape for the light emanation. Can be circle (default), square, cone (cones also have an arc=angle field), or grid (for systems like Pathfinder if you want to see exactly which grid cells are affected by a Light/Aura). Shapes apply from the point they are included in the definition until the end of the definition or until another shape is specified. This means multiple light shapes can be created under a single name and turned on or off as a unit.

**Comment by Azhrei** [comment]
The extensive docs that appear on the Campaign Properties dialog's **Sight** and **Light** tabs should be externalized to the properties file.

The docs for the **Sight** tab also need updating, for example (there are five shapes supported, Square, Circle, Grid, Hex, and Cone, but only three mentioned in the help panel).

**Comment by Phergus** [comment]
Externalizing the text can wait for 2.0.

**Comment by Phergus** [comment]
@rkathey   Please test with 1.5.2 and close if good.

**Comment by JamzTheMan** [comment]
sorry, this will be 1.5.3, it was merged after release branch created

**Comment by Phergus** [comment]
Fix in 1.5.3.  Closing.
