### ISSUE TITLE
Include Map Display Name in map export file

### ISSUE THREAD

**Issue by VagruariesOfFate** [RPTools/maptool#2881]
**Is your feature request related to a problem? Please describe.**
The Map Display Name is not exported with a map export. 

**Describe the solution you'd like**
I would like the Map Display Name included in the export file

**Describe alternatives you've considered**
Map Display Name can be set manually or by macro

**Additional context**

**Comment by Phergus** [comment]
Maps exported with 1.9.3 have the info:
![image](https://user-images.githubusercontent.com/34379254/128943572-83922978-5cf1-4153-8383-6f48ee2b2e85.png)
And it comes back in on import.
![image](https://user-images.githubusercontent.com/34379254/128943598-fdcb8e2a-0c20-41fb-883d-abeefa9b1982.png)

**Comment by VagruariesOfFate** [comment]
> Maps exported with 1.9.3 have the info:
> ![image](https://user-images.githubusercontent.com/34379254/128943572-83922978-5cf1-4153-8383-6f48ee2b2e85.png)
> And it comes back in on import.
> ![image](https://user-images.githubusercontent.com/34379254/128943598-fdcb8e2a-0c20-41fb-883d-abeefa9b1982.png)

I'll update.  I also might not have looked under that tag :)
