### ISSUE TITLE
Ability to show Token name in speech/thought bubble

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2885]
**Is your feature request related to a problem? Please describe.**
Some time in the past I believe -- or have been lead to believe -- the speech and thought bubble used to have the impersonated token name instead of the players name. This is more useful for some people when they want to display these during roleplaying sessions.

**Describe the solution you'd like**
We should add another token attribute that allows a user to specify a name for the Token that should be displayed for speech/thought bubbles.

1) If mouse is hovering over a token with this new attribute then initiating the speech/thought bubble should use the name in this attribute (as long as the player is an owner of this token)
2) If the player has a token impersonated with this attribute and the mouse is not hovering over another token with hovering over a token with this attribute then the value for the impersonated token should be used
3) If neither of the above is the case the players name should be used for the speech / thought bubble

This will depend on where the mouse is at time the speech / though bubble is initiated and does not change as its moved around. 

Question: Should the arrow / finger pointer also use this value or the players name?

**Describe alternatives you've considered**
Not having the new attribute and defaulting to impersonated name which some people may not want this change from current behaviour.

**Comment by Phergus** [comment]
I think someone is imagining things in regards to MT having done this in the past.  I checked multiple 1.3 versions back to 1.3.b43 and they all used the player name.  1.2 didn't have impersonation.

It seems like a good idea in any case.

I think of the arrow & finger pointers as being OOC actions.  The GM or players pointing out locations/objects/tokens to each other.  Maybe for players?

**Comment by Azhrei** [comment]
How are you going to handle stacked tokens?  My party has a mage with a telepathic familiar and this would be a cool feature, but the Tiny familiar occupies the same square as the mage so I don't see how this would be usable for both tokens...

**Comment by Phergus** [comment]
Tested.  Player Name or Speech Bubble Name appears in the speech/thought bubbles depending on the situation.  See #2895 for details.

@Azhrei 
![image](https://user-images.githubusercontent.com/34379254/130237938-54f54c8f-02c4-4222-8292-4e86d68b5f97.png)
![image](https://user-images.githubusercontent.com/34379254/130238018-364c6262-96a0-4b5f-a6c7-f692295022b8.png)

**Comment by Azhrei** [comment]
It looks like Craig replied in the PR, not here.  But based on the images he attached there, I'd say the approach towards stacked tokens should work. 👍
