### ISSUE TITLE
Speech and Thought bubble too small for long names.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2888]
**Describe the bug**
Speech and Thought bubbles are not resized when users name is too large to fit within the imae.

**To Reproduce**
Connect to MapTool with a user that has a long name (or even dont start server and use the default "Anonymous User") when using shit + space or control + space the thought/speech bubble image will not be large enough to contain the name.

**Expected behavior**
Both bubbles should be sized dynamically so that they are large enough to 

**Screenshots**
<img width="137" alt="CleanShot 2021-08-15 at 14 03 42@2x" src="https://user-images.githubusercontent.com/73173/129467269-3e744d2f-ef18-4b8c-99b4-a9b787abc70d.png">

**MapTool Info**
- Version: All of them for a long time...

**Comment by Phergus** [comment]
Tested.  Bubbles resize to hold name.
![image](https://user-images.githubusercontent.com/34379254/130239082-4c632ba9-987c-4712-a08e-c456a64b0a81.png)
