### ISSUE TITLE
token opacity slider needs preview

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#289]
The **Token Opacity** slider on the token editor dialog's **Config** tab doesn't have a preview.

We could use the token image in the upper left?  The **Layout** image seems kind of small for this, and the **Portrait** doesn't necessarily match the token image at all, so...

**Comment by JamzTheMan** [comment]
We probably should also cache that image in the token class maybe. Or rather set it as the current image and store the original as well.

Right now the render as to render opacity each time. It seems fast be it's a performance tweak that could be done at the same time.

**Comment by oliver-szymanski** [comment]
On it, have a preview already, just looking into what the cache requirement means

**Comment by oliver-szymanski** [comment]
Ok, you cannot cache this, cause it is not the image that has opacity itself, it is the way it is painted on top whats under it (which makes sense). So caching is not really possible, so the always just draws the image by using an alpha composite in the java Graphics 2d. I will just commit a fix for the preview therefore

**Comment by oliver-szymanski** [comment]
fix in https://github.com/RPTools/maptool/pull/306

**Comment by JamzTheMan** [comment]
It would require change to the Token Class. Add another image "asset". Then during render, if there is opacity, grab that image asset instead of the regular token image asset. It would probably need to be checked further up the renderer but it should be possible.

We can break that up into it's own issue though.

**Comment by oliver-szymanski** [comment]
I found it in the zone renderer, will probably add that cache later

**Comment by oliver-szymanski** [comment]
Cache added to the PR

**Comment by Phergus** [comment]
Is this done?

**Comment by Phergus** [comment]
Apparently it was.  Closing.
