### ISSUE TITLE
Add public / private key support to player data

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2915]
**Is your feature request related to a problem? Please describe.**
Add public / private key support in user account database as part of #2673

**Comment by Phergus** [comment]
MT expects `.maptool-rptools\config\keys` to exist when adding public keys to accounts in the database.
![image](https://user-images.githubusercontent.com/34379254/135757364-01290d0e-e1e7-4737-a319-4c170139c296.png)

**Comment by Phergus** [comment]
Tested with new fixes.  Adding, deleting, editing of players in database now working without errors.
