### ISSUE TITLE
Connect to Server dialog for client needs a "use public key" checkbox.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2916]
**Describe the bug**
As part of #2673 players can connect to a server using a public/private key pair, currently specifying a username that the server expects to use a public key will work but the user needs to specify a dummy password as the password field can not be empty.

**Expected behavior**
There should be a "use public key" check box that the player can select which disables the password entry and allows users to proceed even if its empty.

**Comment by Phergus** [comment]
Checkbox present and disables password field when selected.
