### ISSUE TITLE
Support for "raw" asset fetching.  

### ISSUE THREAD

**Issue by FullBleed** [RPTools/maptool#2919]
**Is your feature request related to a problem? Please describe.**
There is, currently, difficulty in fetching and using certain desirable assets types that are supported in MT in various places.  Case in point: animated gifs.  MT can, reportedly, display them in chat and frames if they are fetched from external resources.  The current hurdles required has dissuaded usage of animated gifs and projected an erroneous perspective that MT has no support for them. 

**Describe the solution you'd like**
It would be much better if we could store and access said assets from standard local locations (from tables, tokens, maps, etc) using more standard/established methods.

**Describe alternatives you've considered**
New functions that clearly detail the method and limitations of inserting certain asset types might help people utilize the full capabilities of MT.  i.e. getAnimatedGif()    

**Additional context**
It's unclear what additional asset types a "raw" fetch method might open up.  Local storage/serving of sound?  Additional video format support via the html5 video tag? (The video controls come up when using the tag... just can't seem to get anything to them to test what formats they actually might play.)

EDIT: Noticed that my message was being clipped at my video tag.

**Comment by thelsing** [comment]
@FullBleed Could you add your test cases for gifs in frame5?

**Comment by FullBleed** [comment]
> @FullBleed Could you add your test cases for gifs in frame5?

Is this what you want?

[Gif Test Case.cmpgn.zip](https://github.com/RPTools/maptool/files/7074504/Gif.Test.Case.cmpgn.zip)

**Comment by FullBleed** [comment]
Btw, it is probably worth mentioning that in the sample campaign file above where you can see that a remote animated gif will play in a frame5 and the same gif pulled from a table won't work... the remote pull is clipped.

You can go directly to the supplied link and you'll see that the gif playback in the frame5 is actually being clipped:

https://media.giphy.com/media/Hg6oLYiF7KEFi/giphy.gif

Seems like only 1 second of playback?

**Comment by thelsing** [comment]
I can't do anything about the clipping in frame5, but asset loading from token and imagetabel works with #2929

**Comment by FullBleed** [comment]
> 
> 
> I can't do anything about the clipping in frame5, but asset loading from token and imagetabel works with #2929

Nice.

Any idea why frame5 might be clipping?

**Comment by Phergus** [comment]
Tested with GIF anim from token and table on Overlay, Frame & Frame5.  Animation loaded and played on Frame5 & Overlay. As expected, loaded only first frame of animation on old-style Frame.
