### ISSUE TITLE
Update URLs in the Help menu

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#292]
The **Documentation** and **Tutorials** URLs used in the **Help** menu point to locations that are no longer correct and don't redirect to the right place (and they're about 8+ years old, so that's no surprise).

Verify all of these URLs and update as necessary (URLs are stored in the **i18n.properties** file; perhaps some day they should be read from our server and cached for future use, that way we could update them, if needed).

**Comment by oliver-szymanski** [comment]
on it. As far as I can see only the first 2 links are wrong (to general documentation and tutorials are wrong)

**Comment by oliver-szymanski** [comment]
fix in https://github.com/RPTools/maptool/pull/305
