### ISSUE TITLE
Ability to read/write/create/delete/etc. GM, Campaign, and possibly Global macro properties

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2926]
**Is your feature request related to a problem? Please describe.**
Macros on tokens can be edited and updated using get/setMacroProps(), similarly they can be created and deleted. This functionality does not exist for macros stored in other locations such as GM & Campaign panels. This requires things like library tokens to contain macros that need to be dragged to the appropriate panels which complicates matters and confuses users.

**Describe the solution you'd like**
Extend the functionality of createMacro, removeMacro, get/setMacroProps, etc. to macros stored in other locations.

**Describe alternatives you've considered**
Extend macro properties to include their "home" display panel.

**Additional context**

**Comment by melek** [comment]
Huge +1. I've meant to file a similar one forever and am too lazy.

**Comment by Tdue21** [comment]
Huge +1 from me here. This is especially needed with addon libraries as they do have a token to put the macros *on* in the first place. 
So, it would be immensely helpful to be able to create macros in one or more of the GM, Campaign and Global panels. 
Or even a new panel "Addon macros" that will contain macro created by addons. Once there, they can be dragged to where the gm wants them.
