### ISSUE TITLE
The spotless gradle plugin fails on some common Java 16 syntax

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2931]
**Describe the bug**
Even though MapTool targets Java 16, the spotless plugin 5.2.0 does not support some common Java 16 syntax. This causes the plugin to error out as though invalid syntax was encountered, even though it is valid Java. E.g. `instanceof` patterns like this:
```
if (object instanceof String string) {
   ...
}
```
This prevents the use of some Java 16 features in MapTool.

**To Reproduce**
1. Add an `instanceof` patterns to the codebase.
2. Run `spotlessCheck` from gradle.
3. Observe an error message with the cause `error: ')' expected`

**Expected behavior**
`instanceof` patterns and other Java 16 syntax is accepted so it can be used in MapTool.

**MapTool Info**
- Version: develop
- Install:

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Additional context**
We're using spotless plugin version 5.2.0, but there is already version 5.14.3 available which seems to support Java 16 syntax.

**Comment by Phergus** [comment]
Tested described instanceof pattern issue.  Now passes spotless.  No other issues seen.
