### ISSUE TITLE
Add WebRTC selection to Server Startup Dialog

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2944]
**Is your feature request related to a problem? Please describe.**
After the pilot/beta phase of WebRTC the option for using a WebRTC connection should be moved from the help menu to the server start up dialog.

**Additional Context**
Since the server registry will be used for the signalling server there is no requirement for the clients to specify they need to try a WebRTC connection as this information can be obtained from the server registry.

Depends on RPTools/maptool-server-registry#9

**Comment by Phergus** [comment]
Completed by #3006 .
