### ISSUE TITLE
Support multiple Graalvm Javascript Scopes

### ISSUE THREAD

**Issue by perkinslr** [RPTools/maptool#2960]
# Is your feature request related to a problem? Please describe.
Currently, all javascript code executed in the main thread (via `js.eval` or similar) reuse a single context.  This means variables left in the global namespace affect future javascript fragments.  This is mitigated by wrapping the javascript fragment in an anonymous function, which cleans up function-scoped variables automatically.  Variables which are supposed to be retained can be stored on a persistent object (typically the top level object, which is bound to `this` *within* the anonymous context).  While this works, its behavior is not obvious to people unfamiliar with javascript.

# Describe the solution you'd like
A better approach is to create script contexts on-the-fly.  The current `js.eval(<fragment>, <args...>` function would create a new *anonymous* context which is cleaned up immediately after `js.eval` returns.  This avoids the problems associated with accidentally leaving variables after returning from javascript, but does *not* allow creating persistent data structures or classes inside javascript (which means re-parsing the javascript sources each invocation, which is often not ideal).  This is solved by creating a new `js.evalNS(<namespace>, <fragment>, <args...>)` function, which creates persistent, *named* contexts.  If the same namespace is used a second time, the context is reused.  The contexts need to be cleaned up automatically when loading a new campaign.  Additionally, an explicit `js.closeNS(<namespace)` function can clean up and close a namespace.  This is included for completeness, but is unlikely to see much use, as anything which should be cleaned up should probably just use an anonymous context.  

# Describe alternatives you've considered
## Point `js.eval` to a default context

to preserve backward compatiblity with Nashorn.  We cannot preserve perfect backward compatibility anyway (`atob` and various other functions are unavailable now, but can be worked around with minimal work), so *now* is the best time to break compatibility.  Re-enabling the previous functionality is possible with a search and replace from `js.eval(` to `js.evalNS("default", `.

## Continue with a single context.  

This, functionally, is *fine*, but it is a bit weird for people not used to javascript's odd behavior.  Additionally, different frameworks are more likely to have name collisions.  Currently, to get a name collision, the global variables used need to have the same name.  With named contexts, both the context name *and* the global variable name must collide to cause name collisions between frameworks.

**Comment by cwisniew** [comment]
@perkinslr 
The PR for #2963 adds a method for fetching JavaScript (well any text file really) from lib:token macros/properties via a lib:// URL. 
It may make life easier for people if this the js.eval* functions can use that as well (java code for doing so is below)

What I don't have is a check for trusted (i.e. is it not player editable) if you need that let me know.

You can use the following java code to fetch the info (should be safe to run on any thread... possibly famous last words there)

```java
Optional<Library> library = new LibraryManager().getLibrary(url).get();
if (library.isPresent()) {
  String jsString = library.get().readAsString(url).get();
  // Do something interesting here
}
```

This might also be applicable to #2961

**Comment by perkinslr** [comment]
Not *directly* applicable to either one, I don't think, but trivially easy to implement at the same time, and a good idea to support.

**Comment by Phergus** [comment]
New function pages on Wiki:
https://wiki.rptools.info/index.php/js.evalNS
https://wiki.rptools.info/index.php/js.createNS
https://wiki.rptools.info/index.php/js.removeNS

New Category page on Wiki:
https://wiki.rptools.info/index.php/Category:Javascript_Function

Additional pages on JavaScript in MapTool:
https://wiki.rptools.info/index.php/js:MapTool
https://wiki.rptools.info/index.php/js:MTScript

**Comment by Phergus** [comment]
Should be tested by someone that uses Javascript.

**Comment by perkinslr** [comment]
I agree.  That someone should be other than me, as I wrote the initial code.  I know of 1 other group that uses Javascript, and have reached out to their GM for input, but not heard anything yet.
