### ISSUE TITLE
Graalvm Javascript-based UDFs

### ISSUE THREAD

**Issue by perkinslr** [RPTools/maptool#2961]
**Is your feature request related to a problem? Please describe.**
Currently, persistent javascript functions can be created by attaching them to the top level object in the single javascript context.  They can then be linked through to a UDF.  This requires calling `makeFunction(<udf-name>, <mtscript-macro>)`, where the macro referenced by `mtscript-macro` is something like `[r: js.eval("return someFunc(args)", macro.args)]`.  The problem is `macro.args` takes all the arguments to the UDF and puts them into a single json object, so unpacking `args` inside the javascript turns into something of the general form `let myArg = JSON.parse(args[0])[0]`, which is not particularly elegant.  Also, chasing the definition down requires at least 3 different places.

**Describe the solution you'd like**
#2960 allows the creation of multiple, persistent, javascript contexts.  Javascript functions can "visit" the Java side inside callable Graalvm `Value` wrappers.  This means javascript functions can be called directly from the Java side.  They remember their context automatically.  Adding a new `MTScript.createFunction(funcName, jsFunction)` javascript function would allow registering these javascript objects *directly* as UDFs.  Arguments to the jsUDFs automatically get unpacked; invalid numbers or types of arguments automatically raise appropriate errors, and the registration of the UDF can immediately follow its implementation, which means only 1 place per UDF.  

**Describe alternatives you've considered**
Continue using the current mtscript UDF shim.

**Additional context**
The javascript UDFs can be easily prefixed when used in MTScript, so all javascript UDFs appear as `js.someFunc` to avoid collisions with built-in functions or other UDFs.  I am unsure if this is a good idea, or if letting them use any name is better.

**Comment by perkinslr** [comment]
I believe I have the documentation added to the [wiki](https://wiki.rptools.info/index.php/js:MTScript#MTScript.registerMacro.28.29_Function).

**Comment by Phergus** [comment]
Documentation for new Javascript-related macro functions can be found here:  [Javascript Functions](https://wiki.rptools.info/index.php/Category:Javascript_Function)

**Comment by Phergus** [comment]
Unless someone else steps up to test the new functionality it will go out as is.
