### ISSUE TITLE
Add a way for HTML Frame/Dialogs/Overlays to fetch CSS/JS from Lib: tokens

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2963]
**Is your feature request related to a problem? Please describe.**
Its currently difficult to access CSS or JavaScript from a Frame5/Dialog5/Overlay or CSS in Frame/Dialog. There needs to be an easier way to include these that is both consistent with how these are usually included for web pages and allow the same scheme to be used for Lib:Token replacements going forward.

**Comment by cwisniew** [comment]
Adds url scheme to fetch from lib:tokens
Scheme is
- lib://*&lt;tokename&gt;*/macro/&lt;macro name&gt;
- lib://*&lt;tokenname&gt;*/property/*lt;property name&gt;*

**Things to note:**
- *&lt;tokenname&gt;* is the name of the lib:token without the "lib:" part.
- Since the WebView component does its own internal caching which cant be influenced by the usual methods in the JVM for turning off caching of certain urls a work around needed to be introduced.  To ensure that JavaScript/css picks up the latest version the query string `cachelib=false` needs to be used and the code will do some finagling to ensure it turns into a URL that wont be cached (see below example)
- The macro name can contain / characters making it appear to be a directory path + file

example usage
```html
<html>
<head>
	<link rel="stylesheet" href="lib://Test/macro/test/test.css?cachelib=false">
</head>
<body>
	<h1>This is a test</h1>
	<div id='test1'/>
	<script>
		document.getElementById('test1').innerHTML = '...This is a test!';
	</script>
	<script src="lib://Test/macro/test/test.js?cachelib=false"></script>
	<img src="asset://87f4e9bfa4f1f3db250b57b3599fa4e9"/>
</body>
```

Se attached campaign file for examples.

[test-fw-ext-cmpgn.zip](https://github.com/RPTools/maptool/files/7147848/test-fw-ext-cmpgn.zip)

**Comment by cwisniew** [comment]
Changed to require setting a checkbox to be selected on token dialog before a token can be accessed via URL, to stop sticky nosed players :) 
Players should be able to select for their own lib tokens but obviously not the GMs :)

also added 2 functions details in appropriate issues


<img width="687" alt="CleanShot 2021-09-12 at 20 32 46@2x" src="https://user-images.githubusercontent.com/73173/132985118-bbbd3520-0c8c-47e9-be1e-aeb5e62a83d6.png">

**Comment by Phergus** [comment]
Leaving open for now.

**Comment by Phergus** [comment]
Tested.  URI access is controlled by `Allow URI Access` checkbox state and using URIs in HTML as shown in posts above works as expected.
