### ISSUE TITLE
Layout Profiles

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#297]
Implement Layout Profiles as a way to save layouts for use and distribution to Players.

MapTool has a huge UI with a lot of options for new users. As a GM, I would like to set a player layout profile as the default for a campaign so my players get the view I define for them upon connection to a server. This, of course, could be overridden by the player as needed. 

Other use cases could include a Design Profile vs. a Game Profile for the GM so the campaign designer could easily switch between Game Day mode and Map Design mode. In this use case, you might also want to include Edit->Campaign Properties, Edit->Preferences, and Map/View options to speed map development and ensure the proper settings for Game Day. It might also be used for such things as defining a landing map for each Layout Profile.

**Comment by Tdue21** [comment]
Oh yes, this would be extremely useful. 

I would love to be able to have support for multiple layout. This would help keeping the interface clean. 

With such an option it would be possible to have one layout for when I am working on the campaign, and another for when playing. 

There are several tool windows which are necessary for the one situation, but superfluous in the other.

**Comment by thelsing** [comment]
Same as #1510 which has more information. Closing this one.
