### ISSUE TITLE
Token mouseover event

### ISSUE THREAD

**Issue by Akaku-Keninari** [RPTools/maptool#2978]
**Is your feature request related to a problem? Please describe.**
With the adding of overlays and the general oldness of the statsheet, it'd be nice to be able to react to things that are being moused over without having to resort to calling macros via the statsheet.

**Describe the solution you'd like**
A event like "onTokenHover()" that gets passed the token id plus ideally the x and y coordinates of the mouse when hovering over a token in the object or token layer. That way one could draw interactive pointers on map objects AND do their own statsheet-style popups.

**Describe alternatives you've considered**
The 'fake event' method listed https://wiki.rptools.info/index.php/onMouseOverEvent

**Comment by Akaku-Keninari** [comment]
Though if it's going to be a real event, I suppose it'd be best to be 2 events, one for mouse-in and one for mouse-out.

**Comment by JoeRLDuncan** [comment]
This functionality is part of my long-term post-beta functionality for my JUH macro libs. Would be nicer to have it built-in though.

With a bit of work, it should be doable with lib:JUH.mouse though.

Essentially you just need to send "shadow tokens" (data on token locations) to update the mousepad overlay every time the viewport zooms or pans (disable the hovers while zooming or panning, obviously).

Then you just proxy the hover events from the "shadow tokens" that are overlayed on your actual tokens to whatever macro callback you like.

**Comment by Jmr3366** [comment]
@Phergus I think this one is good to be closed.

**Comment by Phergus** [comment]
Yup.
