### ISSUE TITLE
More options for the macro editor

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#298]
I love the new macro editor in MapTool 1.5, I have a small request though. It would be really nice, if it was possible to define font and font-size. 

The font size is a bit smallish for my eyes, and there are several monospace fonts out there that I personally like a lot better that what appears to be Courier New :)

**Comment by rkathey** [comment]
Would it be acceptable if it honored the Edit->Preferences->Accessibility->Chat Font Size or would you want two separate font sizes, one for chat one for the macro editor?

**Comment by Jaggeroth** [comment]
I would prefer to be able to specify a separate font & size for the macro editor.
However I suspect that may need to wait for the FX branch.

**Comment by Tdue21** [comment]
I would prefer that font and size were separate. I may not want a monospaced font in the chat, as I would definitely want a monospace for the macro editor. 
Same goes for the sizes. I realize that it may not be practical at this point in the process, in which case I would be able to accept that the font size was shared for now.

**Comment by JamzTheMan** [comment]
That may be a quick hit after 1.5...

**Comment by JamzTheMan** [comment]
FYI It has the ability to have "themes" which include the colors as well. I will check on what format those themes are and see if they are human editable easy enough as well.

Adding a theme selector may be a way to go if that includes font choices. There are also several Included IIRC.

**Comment by Tdue21** [comment]
That would be a perfectly acceptable solution for my part 😄

**Comment by JamzTheMan** [comment]
Ok, so themes are XML as I expected (been over a year since I last looked at themes). We wouldn't put any sort of "theme editor" anytime soon probably, but could support picking up themes from your .maptool folder and add them to the list of current themes available and let you choose a theme.

The DTD is here:
https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/resources/org/fife/ui/rsyntaxtextarea/themes/theme.dtd

Supplied themes are here:
https://github.com/bobbylight/RSyntaxTextArea/tree/master/RSyntaxTextArea/src/main/resources/org/fife/ui/rsyntaxtextarea/themes

The files are pretty simple. Lots of color choices really.
The current theme in "use" is: https://github.com/RPTools/maptool/blob/merge-from-nerps/src/main/resources/net/rptools/maptool/client/ui/syntax/themes/nerps.xml

**Comment by rkathey** [comment]
We could ship with a few themes (like larger font size, dark color pallet) to help with accessibility then maybe help folks who need some specialization.

**Comment by JamzTheMan** [comment]
Absolutely.  Eventually we could open that up as a "resource" that people can view/add. Like getting a list of community themes from RPTools.net or such.  But lets not get ahead of ourselves :)

We still need to evaluate if we're keeping RSyntaxArea in FX. It's still a Swing component after all...

**Comment by Phergus** [comment]
How about we bump up the font size to 18 or 20 for the current release?

**Comment by Azhrei** [comment]
I don't see font size in the existing XML as an option; it just has colors.  However, the wiki docs say that the font size and style can be set on each individual token style (so IDENTIFIERS, DIGITS, etc) and they _don't_ use a base font, meaning they would all have to be set.  If I can find an easy way to do that, I will.

**Comment by Azhrei** [comment]
Hm, must’ve searched for “font” and missed the capitalized version.  In that case, it seems pretty easy.  Have you tried changing it?

**Comment by Phergus** [comment]
Yup.  Works great at 20 for my tired old eyes.

**Comment by Phergus** [comment]
In my fork:
https://github.com/Phergus/maptool/blob/merge-from-nerps/src/main/resources/net/rptools/maptool/client/ui/syntax/themes/nerps.xml

**Comment by Tdue21** [comment]
So, how to use this? Is it enough put an xml somewhere, or does it need to be compiled into the jar?

**Comment by Phergus** [comment]
It currently has to be compiled into the jar.  On the next update perhaps we can get it pulling a theme file from the user dir and perhaps even a UI to choose a theme.

**Comment by JamzTheMan** [comment]
I was going to say, I saw it in the DTD. And ya, looks like each Identifier can also overload the base font/style.

**Comment by Azhrei** [comment]
@Phergus Are you going to submit a PR for the change?

**Comment by Phergus** [comment]
@Azhrei  Sure. Assuming we get our internet back sometime today. I won't be back to the house till late so it may be tomorrow.

**Comment by Azhrei** [comment]
Thanks.  I'm teaching this week and time is at a premium, but I'll have some more of it on Friday to get back into this stuff.

**Comment by Phergus** [comment]
Themes added with #445.

**Comment by Phergus** [comment]
Themes can be selected via preferences.  Default themes are found in:
`C:\Users\<username>\.maptool-rptools\themes\syntax`
