### ISSUE TITLE
URI access denied for players if containing token is unowned.

### ISSUE THREAD

**Issue by perkinslr** [RPTools/maptool#2986]
**Describe the bug**
URI access (via `js.evalURI`, `html.frame5` and so on) fails if the `Lib:` token is unowned.  Even with `Allow URI Access` checked.

**To Reproduce**
1. Create a `Lib:` token with 2 macros.
2. Macro 1 is a javascript fragment, something like `MapTool.chat.broadcast('abc')`
3. Macro 2 is `[h: js.evalURI("test", "lib://MyLib/macro/Macro1")]`
4. Log in as a player and run macro 2.
**Expected behavior**
Macro 2 successfully calls macro 1

**MapTool Info**
- Version: 1.10.0
- Install: New, from [github](https://github.com/perkinslr/maptool/releases/tag/1.10.0-JS-Preview-0)

**Desktop (please complete the following information):**
 - OS: Linux [gentoo]
 - Version [17.1]

**Comment by Phergus** [comment]
Tested.  Now works when run by a player on lib:token without an owner.

Note that specifying an invalid lib:token name in the URI produces an error that references a non-existent I18n string `libUIr.invalidLibToken`.  Will open a bug ticket for this #3001
