### ISSUE TITLE
Reserve namespaces for future RPTools libraries

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2994]
**Is your feature request related to a problem? Please describe.**
With the addition of lib:// URIs we should reserve some namespaces so we can add builtin/standard libraries in the future and not have to worry about conflicts.

**Describe the solution you'd like**
The following lib:tokens should not allow players/GMs to set the allows URI access flag.

Lib tokens with the following names (after the lib: part)
* rptools
* maptool
* maptools (because people often call it maptools)
* internal
* builtin
* standard

Lib tokens starting with the following names (after the lib: part)
* rptools.
* maptool.
* maptools. (because people often call it maptools)
* tokentool.
* net.rptools.
* internal.
* _
* builtin.
* standard.
* .

Lib:Tokens with these names would still function as they currently do so that we don't create any compatibility issues, but should not work for lib:// functionality (and possibly other future functionality)

**Describe alternatives you've considered**
Not reserving the names which will lead to problems in the future if we want to use them.

**Additional context**
Once library are more flexible and offer more functionality we will probably want to include standard ones with MapTool, it also provides a clear indication if it's a standard library from the RPTools team.

**Comment by Azhrei** [comment]
Quite a long list.  Why not just require the library tokens that will be used as URIs to be prefixed with `lib:URI:` or `lib:user.` or similar?  Just curious as to the thought process.

**Comment by cwisniew** [comment]
> Quite a long list.  Why not just require the library tokens that will be used as URIs to be prefixed with `lib:URI:` or `lib:user.` or similar?  Just curious as to the thought process.

The thought process was to reserve namespaces for internal use. I don't see any need for requring users to start all their URIs with lib://user. to achieve this.

Same goes for Lib:URI: but with the added drawback of using a URI reserved character

**Comment by Phergus** [comment]
Should `tokentool` on it's on be added to the first list?

**Comment by Phergus** [comment]
Testing.  Using listed namespaces in the token name disables the Allow URI Access checkbox.

However, if Allow URI Access is already set on `lib:foo` and it is then changed to `lib:maptool`, the checkbox remains set but is disabled.

**Comment by Phergus** [comment]
re: previous comment

URI checkbox gets cleared after exiting the Edit Token dialog if name is invalid.

**Comment by Azhrei** [comment]
> > Quite a long list.  Why not just require the library tokens that will be used as URIs to be prefixed with `lib:URI:` or `lib:user.` or similar?  Just curious as to the thought process.
> 
> The thought process was to reserve namespaces for internal use.

That’s a conclusion, not a review of how you came to that decision.

In the interests of spirited debate, and because this issue was followed within minutes by a PR, meaning there was no time for input from concerned parties (users, framework authors, and contributors), I’d like some clarity on how you came to this choice.

For example, Java reserves two, java. and javax.  C++ reserves std.  C and POSIX reserve anything starting with an underscore.  And so on.  In each case, a rationale is presented as to why those prefixes were carved out.

I’ll ask again:  why so many reserved prefixes?  Isn’t “rptools.” enough?  Or “rpt.” or “sys.” or …?  Why is there a need for a half-dozen or more?
