### ISSUE TITLE
Token Drift on Non-Square Grids

### ISSUE THREAD

**Issue by Jaggeroth** [RPTools/maptool#300]
When dragging tokens on grid types other than "Square" you get very inconsistent behaviour.

You typically see an initial "jump" when you grab the token i.e. it is suddenly displaced to a different cell.

Then as you drag the token, its positions appears to drift from where you believe the cursor to be. This is difficult to confirm (See Issue #299 ) but when you release the tokens, the cursor will reappear far from where the token has been placed.

**Comment by Phergus** [comment]
I believe the displacement is related to Hex Grid tokens having their position referring to the center of the image and not the top-left corner as in square (all other?) grids.  It is essentially half the width and height.

**Comment by Phergus** [comment]
I believe this has been fixed by changes for #487.  Code can be found in 1.5.3-rc1.

**Comment by Phergus** [comment]
This should be addressed by changes made under #487.  Closing.
