### ISSUE TITLE
Update WebRTC checkbox so that it is part of the start server/connect to server dialog

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3006]
**Is your feature request related to a problem? Please describe.**
The experimental WebRTC functionality is currently exposed as a check menu item under the help menu. This should be moved to the connect to server / start server dialog boxes. 

**Describe the solution you'd like**
1) Removal of use WebRTC check menu item from the help menu
2) Addition of use WebRTC check box to the Start Server Dialog
3) Addition of use WebRTC check box to the Connect to Server Dialog

**Describe alternatives you've considered**
Leave it where it is?

**Additional context**
Although the WebRTC functionality added in #2943 is still experimental it should be part of the Start Server / Connect to Server flow.

In addition to the above changes, the following also needs to be changed.
* The WebRTC box checkbox should not be selectable if there is no RPTools Alias in the server in the Start Server Dialog, likewise if no Server Name is specified in the connect to server dialog it should not be selectable. 
* If connecting to local host with a server alias and the Use WebRTC is selected in the connect to server dialog there is no need to warn user they may not be able to connect as WebRTC should be able to handle this.

**Comment by thelsing** [comment]
Can you please open a new issue and attach logs of client and server? I think comments in closed issues will most likely go unnoticed.
