### ISSUE TITLE
Wiki needs to be moved/converted.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#301]
At the moment the RPTools wiki at https://lmwcs.com/rptools/wiki/Main_Page needs to be moved to something else as we can't allow user creation without getting a lot of spam and every time the hosting service updates PHP we have to move to a newer version of media wiki and more of the plugins being used no longer work.

This is to discuss alternatives / ideas / plans etc..

**Comment by Tdue21** [comment]
Seems to me, that it would be fairly easy to simple convert all wiki pages to markdown and then push them to the github pages repo. 
Question is, of course, whether to change the overall format or keep it as is, so to speak. I mean the overall layout of pages etc. 
To be perfectly honest the wiki as it is today, strikes me as somewhat... old fashioned.

Another possibility would of course be to use the github wikis, but I do not think those are as easily accessed, in that they do not support custom domains. Not that I have been able to determine at least. 

All in all, I think the best option would simply be to move the content of the current wiki to github pages. Of course, a certain level of organisation is still required, if nothing else, then for linking information together.

**Comment by Azhrei** [comment]
The wiki uses way more functionality than is provided by markdown; color and font control being the two biggest, followed by special CSS styling of "note", "stub", and others.

We will probably move them to GH pages, but that means extracting the relevant HTML portions, not the MediaWiki source.  I've got code that does that (had to do it for the macro editor help) so the majority is done.  Now it just remains to extract the pieces we want and format them as we wish.  For example, we may choose to leave out all of the "stub" pieces.

If you wish to see what the resulting HTML looks like, [click this link into the source code](https://github.com/RPTools/maptool/blob/develop/src/main/resources/net/rptools/maptool/language/macro_descriptions/i18n.properties).  (If that's too cumbersome, I can post a sample.)

**Comment by Tdue21** [comment]
I get that. It would be easier to maintain, if the content was in markdown format, but I realize that may not be completely doable. It does seem that GH pages support both markdown and html, so maybe it is possible to mix them? 

I am thinking that maybe it was possible to design a custom theme for jekyll and then keep the content of the wiki in markdown? I can recall any pages right now, that couldn't be made to work in markdown. Some will of course require a bit of work, but it seems to me that it should be possible. 

It all depends on how much of the current layout and style must be transferred as well. I am thinking that the content is the most important, and (no offense to anyone), but the style and layout of the wiki could stand an upgrade. 

In my opinion.

**Comment by Azhrei** [comment]
Yeah, mixing them might work.  Craig was thinking of Jekyll templates as well.  The most difficult aspects will likely be syntax highlighting for MTscript examples and the CSS, both of which can be solved easily with JavaScript and a global stylesheet, assuming both of those are supported.  (I have looked.)

**Comment by JamzTheMan** [comment]
FYI: Right now wiki is also our source for the Macro Editor which doesn't support markdown...

**Comment by Phergus** [comment]
Nifty markdown example: http://scribe.pf2.tools/

Another one:  http://scribe.pf2.tools/

**Comment by kayila** [comment]
That's the same link twice...

**Comment by Phergus** [comment]
Oops.  Fixed.

**Comment by cwisniew** [comment]
Wiki moved to new host wiki.rptools.net
