### ISSUE TITLE
Update Website to Reflect 1.5 Release

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#302]
I've started modifying the web site to remove/alter the 1.3 and 1.4 language to reflect the release of 1.5.
Part of this may involve modifying the download page to point to Github for downloads.

**Comment by JamzTheMan** [comment]
How do you want to do the look and feel? FYI: For the "latest" releases I used big buttons that seemed to work well to drive people the the proper downloads.

The assets I used are here: https://github.com/JamzTheMan/MapTool/tree/gh-pages/assets/images

If you want to use the OS logo's and what not, can change colors and what not.

**Comment by JamzTheMan** [comment]
The other magic is here: https://github.com/JamzTheMan/MapTool/blob/gh-pages/_layouts/default.html

But that is a gh site page which uses site tags available to determine proper links for latest release based on tags.

**Comment by rkathey** [comment]
I'm thinking big buttons for the web site. I have a download reusable block for the site that, when we change it, will change on all the pages and posts. I can use the images you provided. I also have the trademarked versions. I like yours since we can just add a little text to them, as needed. 

I'm wondering about the design/name of the Download page. It was cool when people used a bunch of different versions but it uses some custom javascript to pull files from the rptools.net file system. I'd like to get away from that if we can.

I would hope we can drive most users to 1.4 final and 1.5 dev. Maybe we change Download to Archive and just give them buttons in the sidebar. My plan is to include download links in each post going forward.

Please let me know your thoughts.

**Comment by Azhrei** [comment]
I'm fine with pointing people to GH, but the GH "releases" page is _yuck!_  So if you can find a way to use Jamz' GH Pages approach and make it look good, I'd prefer that.

I want to make sure the reminder to macOS users about how they need to Ctrl-click/right-click and choose Open is somewhere that they'll see it; i.e., no deep linking directly to the download file unless the reminder texts appears first.

If you want to do some kind of dynamic page content, let me know.  We can build up some JS code, if needed.  (Like maybe the first click on the macOS **.pkg** link brings up the reminder box, then from there they can click the link to download it...?)

**Comment by Azhrei** [comment]
Oh, and changing **Download** to **Archive** sounds like a good idea to me, along with a blurb about how future updates will take place directly at GitHub.

**Comment by JamzTheMan** [comment]
@rkathey Once we have a GH page up that Craig is working on, we should be able to "embed" that into RPTools.net site where ever you need to. We can modify that page so it doesn't have a Header so it flows with the current WP pages. People wouldn't even know they are viewing a GH page really at that point. (In theory this should all be possible)

And I agree with Azhrei, the default Releases page is yuck, it's straight up for devs only...

I'd like to see a "Fork me on GitHub" flag somewhere as well. A lot of sites use that corner banner/flag? Just a thought, anything to drive developers towards contributions!

**Comment by rkathey** [comment]
I like all of those ideas. Hopefully, we can put it in a reusable block we can change once and have displayed everywhere as we find better ways of doing things.

**Comment by Azhrei** [comment]
+1

The idea of embedding the GH Page into the WP site is great!

**Comment by JamzTheMan** [comment]
https://help.github.com/en/articles/setting-up-a-custom-subdomain

**Comment by JamzTheMan** [comment]
https://help.github.com/en/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site

**Comment by rkathey** [comment]
So I'm assuming this will allow us to create downloads.rptools.net and doc.rptools.net and redirect them to our Github pages.

**Comment by Azhrei** [comment]
So... we want a sudomain to point somewhere?  If someone wants to give me the particulars, I'd be happy to add them.

**Comment by JamzTheMan** [comment]
lets start with a maptool.rptools.net so a CNAME record to rptools.github.io (it's uername so I assume org name here)

We then place the CNAME "file" with "maptool.rptools.net" in master branch (and this may change location based on how craig sets up the GH pages but CNAME "record" will stay the same I believe.

**Comment by JamzTheMan** [comment]
@rkathey FYI: We may need separate "pages" for maptool & tokentool downloads? I dunno, maybe we can do one?

**Comment by Azhrei** [comment]
Well, it's not a CNAME, but I've added a 301 (permanent) redirect from "maptool.rptools.net" to "rptools.github.io".  It looks like it's working.

**Comment by cwisniew** [comment]
The correct file has been created but it wont work until the CNAME record has been added to the DNS until then you will get too many redirects error.

**Comment by rkathey** [comment]
To have them on the same page I guess we would need to have a new GitHub page at this level https://github.com/RPTools/ to automagically gets the links for both of the current tools from GitHub automation. Perhaps then we could have that pointed to/linked from rptools.net.

For this release (1.5) we should just link to the individual OS installables with a link to the release page for the jar and source (with a Fork Me button maybe).

We can fancify on the next release.

**Comment by cwisniew** [comment]
I have pointed www.rptools.dev to the github pages. According to the github pages it could take up to 24 hours for the certificate to be generated so there may be problems visiting the site until then.

**Comment by JamzTheMan** [comment]
Cool cool

**Comment by rkathey** [comment]
Are we 'good enough' on this one?

**Comment by Phergus** [comment]
Minor typo in sidebar:
> or **Dowload** MapTool and TokenTool via
> DriveThru RPG using Pay What You Want 

Didn't see anything else that needed updating.
