### ISSUE TITLE
Frame5/Dialog5/Overlay are not able to resolves relative URL on Lib://Token

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3023]
**Describe the bug**
You can't refer to URLs from Frame5/Dialog5/Overlay using relative paths, you should be able to

**To Reproduce**
Using the attached campaign run any of the macros in the "New Macros" group on Lib:Test

**Expected behaviour**
If I have a set up like the following
![image](https://user-images.githubusercontent.com/73173/136484689-96297e07-9446-48ba-9416-1c9d44e2856e.png)

All of my "files" have the same path test/... So I should be able to do something like the following
```html
<html>
<head>
	<link rel="stylesheet" href="./test.css?cachelib=false">
</head>
<body>
	<h1>This is a test</h1>
	<div id='test1'/>
	<script>
		document.getElementById('test1').innerHTML = '...This is a test!';
	</script>
	<script src="./test.js?cachelib=false"></script>
	<img src="asset://87f4e9bfa4f1f3db250b57b3599fa4e9"/>
	<a href="./test2.html">test2</a>
</body>
```

And have the CSS/JavaScript pulled in correctly as well as the link working correctly.

**MapTool Info**
Current develop branch

**Desktop (please complete the following information):**
Any

**Additional context**
This will only work for the new html.frame5/dialog5/overlay macro functions, there is no way to set up the base URL correctly for the roll options, also for non HTML5 versions the support will only be partial. Anyone wanting to use this functionality should migrate to HTML5 versions

[test-fw.cmpgn-2.zip](https://github.com/RPTools/maptool/files/7315609/test-fw.cmpgn-2.zip)

**Comment by Phergus** [comment]
@cwisniew  None of the anchors (`<a>`) examples in the attached campaign above work.  Both the CSS and JS are pulled in with relative paths but not the `<a href="./test2.html">test2</a>`.

**Comment by Phergus** [comment]
That slash at the start of the name was hard to see!  Any way to catch that the requested URL wasn't available and report if from the webview?  I can see others having similar issues with types in their macro names.
