### ISSUE TITLE
Disable polyglot.engine.WarnInterpreterOnly to avoid log spam

### ISSUE THREAD

**Issue by perkinslr** [RPTools/maptool#3025]
The issues I reported above have been resolved with the recent PR.  I did notice that there is a *lot* of log output.  It seems that every `js.eval()` command run produces this:

```
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] WARNING: The polyglot context is using an implementation that does not support runtime compilation.
The guest application code will therefore be executed in interpreted mode only.
Execution only in interpreted mode will strongly impact the guest application performance.
For more information on using GraalVM see https://www.graalvm.org/java/quickstart/.
To disable this warning the '--engine.WarnInterpreterOnly=false' option or use the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
[AWT-EventQueue-0] INFO org.reflections.Reflections - Reflections took 9 ms to scan 1 urls, producing 5 keys and 12 values 
```
Potential for huge logs I imagine.

Not sure if it was always producing the warning about running interpreted instead of using runtime compilation.

_Originally posted by @Phergus in https://github.com/RPTools/maptool/issues/2519#issuecomment-937734255_

It *had* been posting that once, when the javascript engine first initialized.  Or maybe once per context creation.  It is now rather spammy.  Not sure what changed, but the solution would seem to be to add `-Dpolyglot.engine.WarnInterpreterOnly=false` to the default JVM args in build.gradle.  We know it's interpreted mode, but that's fast enough for anything reasonable anyway.

**Describe the solution you'd like**
Add  `-Dpolyglot.engine.WarnInterpreterOnly=false` to the default JVM args in build.gradle.

**Describe alternatives you've considered**
Set that flag via Java somewhere during initialization.
Pass the `--engine.WarnInterpreterOnly=false` on the command line.
Redirect the warning output elsewhere.

**Comment by Phergus** [comment]
@perkinslr  no worries.  I got it.

PR #3027 disables the warning.
