### ISSUE TITLE
getImpersonatedName() does not work inside dialog or frame scopes

### ISSUE THREAD

**Issue by mudpyr8** [RPTools/maptool#3041]
This works as expected: 
`[h: idName = getImpersonatedName()]
[dialog5(idName, "width=1050; height=950; temporary=0; closebutton=0"): {
 ... `

This generates an Input dialog asking for the value of idName:
`[dialog5(idName, "width=1050; height=950; temporary=0; closebutton=0"): {
[h: idName = getImpersonatedName()]
 ... `

getImpersonated() works fine inside the dialog (or frame)

**Comment by kwvanderlinde** [comment]
Please use the Bug Report template when reporting a bug.

Also, this is expected behaviour. In the second code snippet, you're using the `idName` variable before assigning a value to it. This isn't specific to dialogs or frames. E.g., compare with this working example:
```
[dialog("some name", "width=1050; height=950; temporary=0; closebutton=0"): { 
	[h: idName = getImpersonatedName()]
}]
```
