### ISSUE TITLE
Allow tokens to carry Hill and Pit VBL, just as they can carry Wall VBL.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3052]
**Is your feature request related to a problem? Please describe.**
Tokens are able to carry Wall VBL, but Wall VBL hides what is underneath it. Hill VBL and Pit VBL on tokens would allow (parts of) a token to not be hidden by the vision blocking.

**Describe the solution you'd like**
I would like tokens to be able to store Hill and Pit VBL, in the same way they store Wall VBL. The "Edit Token" dialog would be extended to allow manipulation of Hill and Pit VBL, either automatically or by transferring to/from the map.

The following changes would be made to the **Edit Token** dialog:
1. The **Generate Token VBL** button is capable of generating Wall, Hill or Pit VBL as desired.
2. The **Move VBL To Map** button is capable of copying any of the token's Wall, Hill or Pit VBL to the map as desired, respecting the **Erase Source VBL on Move** option.
3. The **Move VBL From Map** button is capable of copying any of the map's Wall, Hill or Pit VBL to the token as desired, respecting the **Erase Source VBL on Move** option.
4. Any use of the word "VBL" can either apply to all types of VBL or is qualified as either "Wall VBL", "Hill VBL" or "Pit VBL".

The following macro functions would also be added so that macros can manipulate token Hill and Pit VBL analogously to how they can manipulate token Wall VBL:
- `getTokenHillVBL(id)`
- `setTokenHillVBL(vbl, id)`
- `transferHillVBL(value), transferHillVBL(value, delete), transferHillVBL(value, id), transferHillVBL(value, delete, id)`
- `getTokenPitVBL(id)`
- `setTokenPitVBL(vbl, id)`
- `transferPitVBL(value), transferPitVBL(value, delete), transferPitVBL(value, id), transferPitVBL(value, delete, id)`

**Describe alternatives you've considered**
It is already possible to add Wall VBL to a token and then mark it as **Is Visible over FoW**. The effect is quite good:
![image](https://user-images.githubusercontent.com/7492219/137372040-f142452d-2b2b-4be4-b688-f093458cd5dd.png)
But this doesn't work for some other situations. For example, sometimes it is handy for the map to actually be a background stamp carrying VBL. In that case, we can't selectively have certain parts of the map be visible over FoW. Also, **Is Visible over Fow** only approximates the effect of Hill-with-Pit VBL, and can't approximate only Hill VBL or only Pit VBL.

**Additional context**
There is a related feature request in #2730 for adding Token MBL. If we go forward with either of these features, the Edit Token Dialog should be updated in a way that would easily support the other feature.

**Comment by kwvanderlinde** [comment]
I've updated the wording of this feature request to reflect the final state of the new VBL options. I.e., instead of "terrain VBL" vs "regular VBL" it's "Hill VBL", "Pit VBL" and "Wall VBL".

**Comment by kwvanderlinde** [comment]
(Semi-replying to a comment by @FullBleed on #3377) 

The internal changes needed to support token Hill/Pit VBL functionality is not too bad. It's a bit of a grind as it's pretty much just copying-and-pasting code in a bunch of places, but other than that it is nothing too notable. Basically just ensuring that Hill/Pit VBL on a token is used everywhere that token Wall VBL is used (e.g., rendered on the map if needed, merged into MBL for pathfinding). Same goes for defining the macro functions, nothing much to note.

The _interesting_ part of this feature is going to be figuring out how exactly to modify the **Edit Token** dialog so that all types of VBL (and MBL) can be supported without making it cumbersome.

**Comment by kwvanderlinde** [comment]
My own testing shows that Pit VBL does stll work, but not all topology changes are being respected by the vision algorithm. I must have messed up the topology caching somehow. I'll take a look at fixing this later today hopefully.

**Comment by kwvanderlinde** [comment]
I literraly missed one line of code :sweat_smile:

**Comment by Phergus** [comment]
That did it.  Doing some more testing on exposing with/without lights just in case.

**Comment by Phergus** [comment]
No other issues found.
