### ISSUE TITLE
Type-o in default Player name

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#3059]
**Describe the bug**
Before a server is started when you get the player name, it's spelled "Pllayer"

**To Reproduce**
1. Start a New Campaign with no server
2. type [r: getPlayerName()] in chat

**Expected behavior**
Default name is misspelled and should be "Player". I had to put on my reading glasses to make sure I wasn't seeing double.

**Screenshots**
![image](https://user-images.githubusercontent.com/43827071/137568172-a87258e0-40ee-40e7-9ae2-e4afca1ff5e3.png)

**MapTool Info**
- Version: 1.9.3

**Comment by Phergus** [comment]
Edit -> Preferences -> Application tab -> Default Username

**Comment by aliasmask** [comment]
I'm assuming the default name there was something else and I put in the misspelled name and then immediately forgot that this option existed.
