### ISSUE TITLE
Add initial support for "Add-On" libraries.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3077]
This is a [ZenHub](https://www.zenhub.com/) Epic

**Summary of the Epic.**
Add support for "Add-On" libraries. 
This will allow GMs to include add-ons in the campaign that can contain MT macro script, JavaScript, HTML, CSS, Images, Text files etc.

This epic is the initial steps and doesn't encompass the JavaScript API also required for a more complete add-on solution, which will be added in subsequent version (these things take time).

**Describe the solution**
See attached issues (via [ZenHub](https://www.zenhub.com/) or plug in)for further information

**Additional context**
See attached issues (via [ZenHub](https://www.zenhub.com/) or plug in)for further information

**Comment by Phergus** [comment]
Initial work completed.
