### ISSUE TITLE
Hang during import of new Assets in 1.11 Alpha 1

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3093]
**Describe the bug**
MapTool 1.11 alpha 1 hangs when trying to import new assets from a campaign file if they don't already exist in the asset cache.

**To Reproduce**
Clear asset cache then load a new campaign file.

**Expected behavior**
It should work just like it did before!

**MapTool Info**
MapTool 1.11 Alpha 1

**Desktop (please complete the following information):**
All

**Comment by Phergus** [comment]
Tested.  Existing campaigns now load correctly without error even after purging the assetcache.
