### ISSUE TITLE
Update Universal VTT import to make Object LOS map to Terrain VBL

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#3098]
**Is your feature request related to a problem? Please describe.**
Current Object LOS blocking is imported from the Universal VTT files as regular VBL.  This means the FoW doesn't get exposed and the "object" can't be seen as would be case if it was a real object token flagged as VoFoW.

**Describe the solution you'd like**
Changing the VBL to Terrain VBL will let the object imagery embedded in map be visible to players but still block vision past that point.

**Describe alternatives you've considered**
Suggested players user their imagination instead.

**Additional context**
Related to #2755 

DD2VTT file with Object LOS: [ObjectsBlockingLight.zip](https://github.com/RPTools/maptool/files/7393742/ObjectsBlockingLight.zip)

**Comment by melek** [comment]
Now with Pit and Hill VBL (thank you @kwvanderlinde !!!), imported maps will need to have both the new types overlapping to get the same effect as the original Terrain VBL enhancement.

**Comment by kwvanderlinde** [comment]
Was this completed with #3194 or is there still some more to be done?

**Comment by Phergus** [comment]
It was completed.
