### ISSUE TITLE
JS: Token.setProperty cannot take numerical value

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#3102]
**Describe the bug**
The Token.setProperty method does not take a number as a value; instead it issues an error.

**To Reproduce**
1. Make a new macro on a token: `[h: js.eval('MapTool.tokens.getSelected().setProperty("HP", "200")')]`
2. Run macro. Observe that the token's HP property is now 200.
1. Make a new macro on a token: `[h: js.eval('MapTool.tokens.getSelected().setProperty("HP", 999)')]` (unquoted value)
2. Run macro.
3. See error, HP is not updated and the following message is in chat:
```
com.oracle.truffle.polyglot.PolyglotEngineException error executing expression js.eval('MapTool.tokens.getSelected().setProperty("HP", 999)').
```

When run via a registered JS function, the error is more explicit: 
```
org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (setProperty) on net.rptools.maptool.client.script.javascript.api.JSAPIToken@15a41497 failed due to: Cannot convert '1'(language: Java, type: java.lang.Integer) to Java type 'java.lang.String': Invalid or lossy primitive coercion. error executing expression js.setHP10(currentToken()).
```

**Expected behavior**
Numbers should work fine with Token.setProperty.

**Screenshots**

**MapTool Info**
- 1.10.3 - Uninstalled older versions then installed

**Desktop (please complete the following information):**
 - Windows 10

**Comment by Phergus** [comment]
Campaign used for evaluation and testing.  Remove `.zip`.
[Issue3102 SetPropAsNumber.cmpgn.zip](https://github.com/RPTools/maptool/files/9353953/Issue3102.SetPropAsNumber.cmpgn.zip)

**Comment by Phergus** [comment]
@melek  please confirm that this issue has been resolved with beta 3.  Thanks.

**Comment by melek** [comment]
Tested and working, thank you!
