### ISSUE TITLE
java.lang.IllegalArgumentException:  when multiple backup campaigns have same time stamp

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3112]
**Describe the bug**
When there are multiple backups of the campaign in the backup directory it causes the following exception.
java.lang.IllegalArgumentException: Comparison method violates its general contract

**Expected behavior**
The exception shouldn't occur :)

**MapTool Info**
All current versions, and probably long way back into the past as well...

**Desktop (please complete the following information):**
All

**Additional context**
The comparison for the list sorting needs to be changed so that it produces a consistant sort order when timestamps are the same.

**Comment by Phergus** [comment]
Could not reproduce and no issues seen after change.
