### ISSUE TITLE
Macro Editor Help needs update for macro.catchAbort & macro.catchAssert

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#313]
As it says.  The editor isn't recognizing `macro.catchAbort` & `macro.catchAssert`.

**Comment by Azhrei** [comment]
Ah, good catch (pun intended).  The editor dynamically finds function names, but not variables.  I think variable names are hard-codes instead of being discovered.  Should be an easy fix assuming there’s an iteration available for finding all variable names.

**Comment by oliver-szymanski** [comment]
Done in https://github.com/RPTools/maptool/pull/320
