### ISSUE TITLE
[Bug]: Campaign Bars can't be added or edited if Language settings are set to German. 

### ISSUE THREAD

**Issue by flaedda** [RPTools/maptool#3140]
### Describe the Bug

In Maptool 1.10.2 & 1.10.4 I'm not able to add or modify Campaign Bars when the Language in Maptool is set to German. Setting the Language to English solve the Problem. 

### To Reproduce

Open  Maptool 1.10.4 with Language set to german. 
Go to Campaign Settings and to the Bars Tab.
Try to add a new Bar.

### Expected Behaviour

I expect a new Campaign Bar after clicking add. 

### Screenshots

![image](https://user-images.githubusercontent.com/77189248/140339296-e0bc401d-1fe8-473b-9170-1e66a0a8c8b9.png)

### MapTool Info

1.10.4

### Desktop

Wi8ndows 10 (German Version)

**Comment by Phergus** [comment]
Problem will occur in any language where the Bar Type has been translated such as Italian and Portuguese.
