### ISSUE TITLE
[UI Update]: Campaign settings - Token properties

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#3149]
### Feature Request

as discussed here: https://discord.com/channels/296230822262865920/902998164951400510/902999222314467380

https://cdn.discordapp.com/attachments/902998164951400510/902999220691288084/unknown.png
the property tab could use an overhaul to make it more user friendly

### The Solution you'd like

A mockup (update):
![image](https://user-images.githubusercontent.com/19568714/140944071-ff9d3619-a81b-4676-b5c9-d9e0e16b5975.png)

- Clicking New/Add should create a new entry with a unique incremental name e.g. 'property12'
- Two headers: Show Statsheet and Show PropertySheet under those two headers each 3 checkboxes:
 +GM
 +Owner
 +All or Others or Rest (with 'others' you could arguably consider to explicitly NOT show this to gm and owner(s) if those are not checked; with 'all' it would not matter whether gm and owner are checked).
 +optionally: EBP with tooltip: 'editable by player', however if this does not show up on the property sheet this would be covered as well. 

- Basic dropdown: list of available property types where this property fall under. Changing the dropdown will change the list of properties below
- Delete will delete selected property
- 'some preset' is the 'import DD/PF/Cthulhu/Whatever'
- 'replace' replace current set with import
- 'append' is ok or 'merge' 'add' or such
- the text fields are known
- the 'type' is to set it to json object so it shows properly on the property sheet, at the core this dropdown would be:
  + json
  + free
 Optionally replace free for
 + text or string
 + number integer
 + number decimal or real
 + ??

**Comment by wolph42** [comment]
I just realised that the 'tokensheet' part of the screenshot is actually an extra feature request. If we just limit this to a functional redo that part should be ignored.

**Comment by cwisniew** [comment]
This does not include the type for property as thats a whole different kettle of fish due to MTScript being type hostile
