### ISSUE TITLE
[Bug]: Allow URI Access flag is reset on server start

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3159]
### Describe the Bug

The new Allow URI Access setting for lib:token is reset when a new server is started. 

### To Reproduce

1. Create a lib:token
2. Edit the lib token and set Allow URI Access
![image](https://user-images.githubusercontent.com/73173/141027736-6db18c5f-86e5-4935-9625-3e4895d397e0.png)
3. Start the server
4. Edit the lib:token to check the setting, and just like magic its gone
![image](https://user-images.githubusercontent.com/73173/141027926-e6e2711c-3a70-486e-8989-c5bb4abb0aba.png)

### Expected Behaviour

Starting a server should not reset this setting.

### MapTool Info

1.10.0 through to 1.10.4

### Desktop

And and All

**Comment by Phergus** [comment]
Tested.  Starting server no longer resets _Allow URI Access_.
