### ISSUE TITLE
[Feature]:  Add a method to read static data from Add-Ons

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3164]
### Feature Request

Add-Ons can contain files which are useful for storing static data (json file(s) with look up tables or SRD information for example). There needs to be a way to get this file.

### The Solution you'd like

A new Macro Function "data.getStaticData(namespace, path)" which returns the information contained in the file that is at the specified path. 

If the macro function is run from the add-on it should be able to access any file, if it is not run from the token then it should only be able to access files in the public/ directory and only if the URI access flag is set.

### Alternatives that you've considered.

Not doing it and drowning under a sea of feature requests.

**Comment by Phergus** [comment]
Tested.  Working as described.
