### ISSUE TITLE
[Feature]: Make it easier to read static data from within an add on

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3171]
### Feature Request

The new MacroScript function `data.getStaticData()` allows macros to retrieve static information from add-ons.
This should be easier for add-ons that are retrieving data from themesleves

### The Solution you'd like

@this is used in many places for macros that want to access other macros or data from themselves, we can extend this behaviour to the data.getStaticData function as below

 data.getStaticData("@this", "/path/to/data")]

### Alternatives that you've considered.

Creating another function, but that seems a little too much.

### Additional Context

This will also help when add-on developers want to test multiple versions of their add on by using different names.

**Comment by Phergus** [comment]
Tested.

Working as expected.
