### ISSUE TITLE
[Bug]:  onFirstInit does not trigger when importing if a addon library with the same namespace was imported previously

### ISSUE THREAD

**Issue by dark-ether** [RPTools/maptool#3173]
### Describe the Bug

onFirstInit does not trigger when importing if a addon library with the same namespace was imported previously, also it does not trigger even if the previously imported library was removed via macros with library.removeAddOn or library.removeAllAddOns

### To Reproduce

1. create or download a valid addon library with a onFirstInit event (included is a valid mtlib file named with zip)
[test.zip](https://github.com/RPTools/maptool/files/7532622/test.zip)
2. import the library 
3. change the name field in the library.json object 
4. import the library again 
5. notice that if the prompt of this namespace already exists appears then the onFirstInit event won't trigger
6. remove the library with macros
7. import it again 
8. the onFirstInit event won't happen

### Expected Behaviour

every time a addon library is imported it's onFirstInit event should be triggered even if it is replacing another library

### MapTool Info

1.11 alpha 4

### Desktop

archlinux

**Comment by Phergus** [comment]
Complete.
