### ISSUE TITLE
[Bug]: On Campaign Load not firing consistently in 1.11 Alphas

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3174]
### Describe the Bug

On Campaign Load does not fire consistently in the 1.11 alphas, this is due to timing/race issue where library tokens are not registered in time sometimes. 

### To Reproduce

Keep loading a campaign with an onCampaignLoad and eventually it wont run (more complicated tokens will run into it sooner).

### Expected Behaviour

The onCampaignLoad macro should be triggered consistently. 

### MapTool Info

1.11 alphas

**Comment by Phergus** [comment]
Unable to reproduce original complaint and no issues seen after code change.
