### ISSUE TITLE
[Bug]:  Exception on deleting lib:token in 1.11 alphas

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3175]
### Describe the Bug

Deleting a library token raises an exception stating that the lib:token is no longer valid.
The token is still deleted but it also unfortunately also raises an error.

### To Reproduce

Create a lib:token and delete it :)

### Expected Behaviour

No error should occur.

### Screenshots

![image](https://user-images.githubusercontent.com/73173/141685744-1e0c49a1-2152-417e-87bc-6fe4eea228d9.png)

### MapTool Info

MapTool 1.11 alphas

**Comment by Phergus** [comment]
Tested.  Deleting a lib:token no longer causes an exception.
