### ISSUE TITLE
[Bug]:  Lib Properties that are numbers not being returned correctly

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3176]
### Describe the Bug

Lib Properties that are numbers in 1.11 are not being returned correctly, they are being returned as strings

### To Reproduce

Create a lib:token with a number in the property field and try to treat the return of getLibProperty() as a number

### Expected Behaviour

A number should be returned not a string

### MapTool Info

MapTool 1.11 alphas

**Comment by Phergus** [comment]
Tested.  Numeric properties retrieved with `getLibProperty()` or `getProperty()` are returned as numbers.
