### ISSUE TITLE
[Bug]:  Exporting a lib:token as an add on fails when running under windows

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3183]
### Describe the Bug

When running latest alpha on windows attempting to export a lib token as an add on fails.

### To Reproduce

Right click on a lib:token and attempt to export

### Expected Behaviour

It should work as it does on non windows systems

### MapTool Info

1.11 Alpha

### Desktop

Windows

**Comment by Phergus** [comment]
Tested.  Export no longer fails on export.
