### ISSUE TITLE
[Feature]: Support `XMLHttpRequest`s inside HTML5 Javascript

### ISSUE THREAD

**Issue by perkinslr** [RPTools/maptool#3190]
### Feature Request

Currently, the native `XMLHttpRequest` class in HTML5 Javascript is non-functional.  It can neither fetch external resources (even from whitelisted CDNs), nor acess `lib:` or `macro:` URIs.  The current solution is to create dynamic `<form>`s, which can call MTScript macros, but cannot read the result, and then *in the called macro*, call back to javascript via `runJSFunction`.  This functions, but is not intuitive to frontend Javascript writers.

### The Solution you'd like

Implement a MT-specific version of XMLHttpRequest which includes a javascript component to hide internal implementation details.  This allows Javascript fronted devs to pretend they are making perfectly normal `XMLHttpRequest`s, which should reduce the friction in learning the MapTool javascript environment.

### Alternatives that you've considered.

* Fix the native `XMLHttpRequest` and then hijack it to only read from the whitelisted CDN.  -- Hard to see how to do that given it fails silently.
* Write a native-java-only request class.  -- Cannot match the builtin API, so there would be more friction for learning it.
* Write a javscript-only layer above the existing form/`runJSFunction` system.  -- The form system is fragile, and when it breaks it often is hard to diagnose.  Also, while synchronous XMLHttpRequests can only be used with extreme care, they *can* be supported with the native Java implementation, but could *not* be via the form-submission hack.  And the return from the form submission requires userspace boilerplate, which at best means cluttering up both the javascript and MTScript namespaces further.

**Comment by Phergus** [comment]
Complete.
