### ISSUE TITLE
[Bug]: getMapDIsplayName can be run from untrusted contexts, and errors on hidden map names from PC clients even from trusted contexts.

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#3199]
### Describe the Bug

`getMapDIsplayName()` will not work with a hidden map name for a connected player client, even from a trusted macro or UDF.

### To Reproduce

1. Make a new campaign with a hidden map named "GM Map".
2. Create the following campaign macro button (campaign macros are trusted): `[r: getMapDisplayName("GM Map")]`
3. Click the macro button. Output should be "GM Map".
4. Start a server, connect to the game as a player, and click the macro button from the PC client
5. **See Error**: `getMapDisplayName: indicated map in first parameter not found.` (should have worked)
6. Run the macro from chat on the PC client.
7. **Possible Error**: The error repeats, instead of denying usage of the function entirely in untrusted contexts (like `getAllMapNames`).

### Expected Behaviour

I expect this function is useless to players for any normal purpose, and shouldn't work at all from untrusted contexts. 

On the flip side, I expect the macro to function normally from trusted contexts on my players' clients, like `getAllMapNames` does.

### MapTool Info

MT 1.10.3

### Desktop

Windows 10

### Additional Context

As it is, the function has limited usefulness, as it behaves unexpectedly (erroring on legitimate map names because they are hidden from players) even from UDFs. I have a system where players need to be able to see some hidden map names when fetching old versions of their tokens, and this function could help make things easier.

**Comment by melek** [comment]
@michaelperino I meant to tag you, since I think you built the display name system :)

**Comment by michaelperino** [comment]
You're correct, I'll take a look if you want to assign me

**Comment by Phergus** [comment]
Tested.  `getMapDisplayName()` now works correctly when run from a trusted macro by a Player client.
