### ISSUE TITLE
[Feature]: Add an easier way to manage public key connections.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3200]
### Feature Request

Currently adding using a public key to connect to a server involves the player sending the public key for their MapTool instance to the GM who then has to create an entry in the player database and paste in the public key.

There should be an easier way for the players public key to be added to the sever.

### The Solution you'd like

There should be a way for the GM to approve connections from a player client that will then create the password database entry and add the public key.

This will require some method for the GM to identify the connection is actually from the player.

### Alternatives that you've considered.

Other third parties and methods for transferring the public key between  players and GM.
There may still be an opportunity to do this in the future with a server registry update.

**Comment by cwisniew** [comment]
### Activating the Change
This change comes into affect when the server is started with the "Use Map Tool Easy Connect" check box is selected.
Selecting easy connect also selects the "Use MapTool password file" option and it can not be deselcted.
![image](https://user-images.githubusercontent.com/73173/142751571-f363f196-7f75-44ce-8c66-65bfc65f21de.png)


### The Player Connects using Public Key
![image](https://user-images.githubusercontent.com/73173/142751722-4f2a0158-14c4-42da-8ec9-1a1622e3a120.png)


###

**Comment by Phergus** [comment]
Player will see this when the request has been sent to the server.
![Connection Request](https://user-images.githubusercontent.com/34379254/142766938-33160c3b-f8a5-4e7f-874f-723c8bc27350.png)

GM will see Pending connections on the Connections panel.
![Connections Pending](https://user-images.githubusercontent.com/34379254/142766974-9983f305-898d-4b55-a348-80ce3f1933a8.png)

**Comment by cwisniew** [comment]
Hmm how odd, I had a lot more details and screen shorts in the above comment but they seem to have been lost. I will update it again when I get the chance

**Comment by FullBleed** [comment]
Bravo!

Really nice work Craig.

**Comment by Phergus** [comment]
Tested.  Working as described.
