### ISSUE TITLE
[Bug]: I8n issues

### ISSUE THREAD

**Issue by irisiflimsi** [RPTools/maptool#3204]
### Describe the Bug

This is from the i8n over at crowdin. I don't know, whether this is monitored, so I'll relay the comments from there:

**library.export.information**
English is strange "extract export"?

**data.error.removingData**
English version does not make sense. What is the intention?
(This includes an opening/closing bracket mismatch.)

**ServerDialog.tooltip.useEasyConnect**
This is bad. Why isn't the field responsible for line breaks in the long text? It is hard to estimate where they will fall convenient for a translation. Is there a reason for using <br/> and <br> in the same paragraph? It is unclear, whether all players use the same PIN or individual PINs. I have tried to keep that ambiguity, but it is harder in German, because a singular/plural-identifying pronoun must be used. There is also a stray "and" towards the end of the text. Only by ignoring it, did it make sense to me. Also a blank seems missing in "filefor".

### To Reproduce

1. Read the english text for the properties in question.

### Expected Behaviour

Expressive english sentences. :-)

### Additional Context

This is the current state over at crowdin. I only looked at my own most pressing comments, there a lot of others. I also have no idea which releases are affected.

**Comment by cwisniew** [comment]
I have fixed the problem with library.export.information and data.error.removingData

For ServerDialog.tooltip.useEasyConnect I have cut out most of the text, its probably better we rely on documentation to address this.

**Comment by Phergus** [comment]
Problem text reworked.
