### ISSUE TITLE
[Bug]: MapTool hangs when creating or loading macro buttons with images that reference non-existent assets.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3211]
### Describe the Bug

When a macro button attempts to load an asset image, but the asset identifes by the `asset://` URL does not exist, MapTool will hang forever and can't be closed by normal means.

### To Reproduce

1. Open a new campaign.
2. And a new macro to the Campaign panel.
3. Edit the macro
4. Change the macro label to `<img src="asset://doesnotexist">`
5. Click `Apply...` or `OK`
6. Witness MapTool hanging.

### Expected Behaviour

A macro button should display the iconic red X when an asset does not exist. MapTool should not hang.

### Screenshots

In MapTool 1.10.4, this does not hang but instead shows a red X like this:
![image](https://user-images.githubusercontent.com/7492219/143324269-0dd3516f-9f55-4090-bbdc-fc8d35374c0f.png)

### MapTool Info

latest develop, run via gradle

### Desktop

Linux Mint 20.2

**Comment by kwvanderlinde** [comment]
I bisected the breakage to 438ada9f1568343ee5b89fc51227e06f415d36b5, but I haven't looked into why this is an issue.

**Comment by cwisniew** [comment]
The problem was readResolve is returning the wrong name for bad assets, so in the parts of the code that have get and wait for asset when the server was sending the asset to the client the name was not matching so it was just waiting forever.

**Comment by Phergus** [comment]
Tested.  No longer hangs if a bad assetid is provided for the src: image.
