### ISSUE TITLE
[Feature]:  UI for managing Add-Ons

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3212]
### Feature Request

For 1.11 there needs to be a user interface to manage add ons

### The Solution you'd like

For 1.11 there needs to be a user interface to manage add ons. 
This should at the very least support
 * Listing Campaign Add-Ons and displaying summary details
 * Adding and Add-On
 * Removing and Add-On

### Alternatives that you've considered.

Having all this nice new functionality that can not be used... not a great alternative though.

**Comment by cwisniew** [comment]
Documentation available at https://rptools-doc.craigs-stuff.net/docs/add-ons/index

**Comment by bubblobill** [comment]
Either an extension of this issue or possibly a new one.

- Ability to edit add-on code inside MT.
- Ability to edit add-on settings inside MT.
- Ability to export add-ons from MT.

TBH, I am unlikely to embrace the new paradigm until I can fiddle the code in a live instance.

**Comment by Phergus** [comment]
Complete.  Any changes to be handled in future issues.
