### ISSUE TITLE
[Bug]: Restore Layout malfunctioning, showing empty macro frames from past games on right side

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#3215]
### Describe the Bug

In 1.10.3+, when I use 'Restore Layout', I'm getting unpopulated frames with titles from macro-generated frames created during prior sessions in a tabbed panel on the right hand side. I have not tested on older versions.

In 1.11.0a5 I get the Campaign panel tabbed with the Library panel on the top left, I think this is correct in 1.11.x thanks to #3135.

### To Reproduce

1. Open a new campaign on a computer which has had prior sessions which generated macro frames.
2. Select Window →  Restore layout.
3. See error - right-hand side is occupied by a panel with tabs for old frames.

### Expected Behaviour

I expect the restore layout button to behave consistently regardless of prior macro panels opened on the computer.

### Screenshots

![image](https://user-images.githubusercontent.com/220149/143614142-c799bcf7-82f6-457e-a159-604a1382b2ca.png)

Here is a partial list of the tabs that come up (I closed about half so you could see the titles:
![image](https://user-images.githubusercontent.com/220149/143614370-342198b2-15a8-44d2-903d-877284a1533a.png)

### MapTool Info

1.10.3, 1.11.0a5, each installed in their own directory.

### Desktop

Windows 10

### Additional Context

Still hoping for #2712 and #1510 ... :)

**Comment by bubblobill** [comment]
I only had 25 empty frames when I found this
[discord conversation #hacktoberfest 24/9/2021](https://discord.com/channels/296230822262865920/890765834442665984/890796310729478235)

**Comment by Irarara** [comment]
Just noticed this. This is something that got missed when fixing #2485. I have something for it.

**Comment by Phergus** [comment]
@melek  -  test the fix when you get a chance please

**Comment by melek** [comment]
After much consternation trying to build 'develop', indeed I can confirm that 'Restore Layout' works without creating the weird empty frame + tabs. 

Success!

**Comment by Phergus** [comment]
Thanks!
