### ISSUE TITLE
[Bug]:  Alpha 1.11.x old campaigns where asset is not in the asset cache freezing on load

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3216]
### Describe the Bug

When trying to load a pre 1.11 campaign with the 1.11 Alphas the load will freeze if the assets are not already in the asset cache.

### To Reproduce

Clear asset cache then load a pre 1.10 (or earlier campaign)

### Expected Behaviour

It should work :)

### MapTool Info

1.11 alphas

### Desktop

Any

**Comment by kwvanderlinde** [comment]
This sounds similar to #3211.

**Comment by cwisniew** [comment]
> This sounds similar to #3211.

Sadly not, the fix for this does not fix #3211 :(

I did take a look at that one while doing this but was not able to resolve it, and its 5am and sleep calls :)

**Comment by Phergus** [comment]
Tested.  Older campaigns correctly load after a cleared asset cache. Life is good.
