### ISSUE TITLE
[Bug]: Random Graphical bug on first time install.

### ISSUE THREAD

**Issue by KIllerbee1577** [RPTools/maptool#3222]
### Describe the Bug

The program acts normally until at a random point the UI begins to overlap itself and randomly draw parts of the windows and their contents at random locations.

Only closing and reopening the program stops the issue, until it happens again.

I have tried to use the .exe of 1.10.4 and 1.10.3 and the installer versions. Aswell as multiple installs of the program. All have the presisting bug.

### To Reproduce

1) Open program
2) wait
3) Bug occurs

### Expected Behaviour

Open the program, begin doing things then the bug occurs.

### Screenshots

![image](https://user-images.githubusercontent.com/21069480/143844005-7901727f-26a7-4801-9242-745abd6416a8.png)

### MapTool Info

First time install. 1.10.4

### Desktop

Windows 10 Version 21H2

**Comment by Phergus** [comment]
Known issue with buggy display drivers.  You'll need to disable Direct3D in the Maptool `maptool.cfg` file.

See https://wiki.rptools.info/index.php/MapTool_Preferences#JVM_Memory_Settings

In specific, add this line `-Dsun.java2d.d3d=false` under the `[JavaOptions]` section.

**Comment by KIllerbee1577** [comment]
Thanks, Apprichiate the reply. I added the code you provided to the file you pointed out. It worked for a time but then it happened again. The page you linked does refer to a OpenGL Pipeline toggle, but I cannot find the "Advanced menu it mentions"

Just for info My drivers are up to date and no graphical problems before using MapTools.

**Comment by Phergus** [comment]
Sorry.  You're using MT 1.9.3+ so you need to modify the line as it says in the instructions.

`java-options=-Dsun.java2d.d3d=false`

Don't touch the OpenGL option.

**Comment by KIllerbee1577** [comment]
I think that's got it. Didn't want to say anything too early in case it did it again. Thank you
