### ISSUE TITLE
[Bug]: Starting a server sets all tokens to size medium (1.11.0)

### ISSUE THREAD

**Issue by SterLovesFood** [RPTools/maptool#3225]
### Describe the Bug

New issue with 1.11.0 -- when I start a server it changes the token size of all snapped to grid tokens to medium on all existing maps (doesn't happen to free-sized tokens). Does it again when I disconnect server.

### To Reproduce

1. Place a token on the map.
2. Set it to Large size
3. Start a server
4. The token will reset to medium
5. Set it to large size
6. Disconnect the server
7. The token will reset to medium

### Expected Behaviour

Tokens stay the same size

### MapTool Info

1.11.0

### Desktop

Problem replicated on both Windows and Linux

**Comment by Azhrei** [comment]
Confirmed on macOS (fully updated) as well.

**Comment by timgstewart** [comment]
Some additional information on this, I experience it as well on Linux, but while playing today with my players who connect remotely to the server I re-adjusted the size of my tokens on the map (Gelatinous Cubes -> Large), however my players never saw them as anything other than Medium size on their side.  We didn't realize the discrepancy until it became strange that they were being engulfed but the creature didn't appear to be on top of them.

Anyhow, just wanted to add that the remote client seems to not receive a resized token.  I don't know if you consider that a separate issue or part of the same, but it seemed like a continuation of this problem.

**Comment by Phergus** [comment]
Tested.  Token sizes persist through server start/stop and are correctly shown on all clients.

**Comment by Phergus** [comment]
A variant of this problem has shown up with tokens from campaigns from prior to 1.11 all loading as Medium instead of the sizes there were saved at.  Once set in 1.11.2 and saved the sizes are kept on subsequent campaign loads.

**Comment by Phergus** [comment]
Tested. #3248 fixes issue.  Tokens, on any layer, that were set to a specific named size are now loaded correctly.  Free-size or manually-sized tokens were and still are loading correctly.
