### ISSUE TITLE
[Bug]: Token "Move VBL to map" no longer honors the current VBL draw mode

### ISSUE THREAD

**Issue by timgstewart** [RPTools/maptool#3226]
### Describe the Bug

I typically build a map using an image and in GIMP I will create a second layer for VBL and a third for MBL.  Then I'll use GIMPS color select tools, etc to draw the VBL and MBL transparent layers.

I was excited to try the new PIT and HILL blocking layers, so I made versions of those too on the map I was creating.

The process in maptool, is to drag the token onto the map on the background layer, align it with the map using snap-to-grid, then edit the token and highlight the VBL (which for the VBL/MBL/etc layers is the black area).  I'll then use the Move VBL to Map to make it permanent.

Prior to version 1.11.0, I could select the MBL or VBL draw mode before I did the "Move VBL to Map", and it would move the token's vbl as that type of draw mode.  For example, if I had MBL selected as the draw mode, and did "Move VBL to Map" from the token, it would create an MBL layer.

With version 1.11.0 it does not seem matter if I select W H P or M as the VBL draw mode.  Anything token on which I "Move VBL to Map" creates a new Wall area.  I'm not sure at this point how to easily create vision blocking layers other than Wall outside of maptool and import them into map tool, but the change in behavior I would consider a bug. 

### To Reproduce

1. Create a transparent PNG with some black area.
2. Select the MBL draw mode under vision blocking so that we can create some MBL.
3. Back at the Interaction Tools, select the Background layer
4. Drag your PNG into maptool to create a token
5. Edit the token
6. Select the VBL color, and generate the token VBL
7. Click "Move VBL to map".  Clear the VBL from the token or not, doesn't matter.
8. Delete the token.
9. Check the VBL draw modes
10. Observe that it was not imported as MBL, but rather as Wall

### Expected Behaviour

I expect the behavior prior to 1.11.0 to be maintained. When I'm in draw mode for HILL and I move a token's VBL to the map, I expect that to be HILL area.  Similarly for MBL, Wall, Pit.

### MapTool Info

1.11.0

### Desktop

Linux Ubuntu

**Comment by FullBleed** [comment]
@kwvanderlinde to the rescue! ;)

**Comment by FullBleed** [comment]
@timgstewart You might want to take a look at the discussion at https://discord.com/channels/296230822262865920/494598206626463755/915409780212891708 regarding this issue report.

**Comment by FullBleed** [comment]
> Thanks, I was able to access the server, but how do I get access to the channel?

Not 100% on this... but try going to #role_selections and choose the "Core Development" role... I think that will give you access to the channel.

**Comment by VagruariesOfFate** [comment]
A note in case this comes up again.  To enter discussion areas follow the instructions in the welcome paragraph and click the reaction at the end to show you are not a bot.

**Comment by timgstewart** [comment]
So the drawXXX functions provided a suitable workaround for my use case.  I think since my tokens are the same size of the map, positioning and size of the transfered VBL works out fine.  This was from the discord chat, and I ended up with four macros that do something like:

[r: drawHillVBL(getTokenVBL(getSelected()))]

**Comment by timgstewart** [comment]
However, I'm now seeing something else strange that might be a new issue.  When I drag my token onto the map and I create the token VBL, I then transfer it to the map.  Afterward I delete the token.

The next token I pull in, even if it is a player or NPC token or a token intended for VBL transfer, has the VBL from the previous token.

**Comment by Phergus** [comment]
Obsoleted by changes made for #3052 by #3444.  Edit Token Dialog now allows user to select topology modes.
