### ISSUE TITLE
[Bug]:  getLibProperty() for Lib:Token Properties fail when they start with [ but are not valid JSON

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3229]
### Describe the Bug

The getLibProperty() function fails for Lib:token properties if they start with [ and are not valid json as it tries to parse them as such.

### To Reproduce

Create a property and set it to  "[doh!"  and then use getLibProprty() to retrieve it.

### Expected Behaviour

It should not fail, in fact it should not convert it to JSON even if it is valid as this was not happening pre 1.11 and could cause compatibility issues

### MapTool Info

1.11.0

### Desktop

Any

**Comment by Phergus** [comment]
Tested.  Properties with leading `[` or `{` but not closed are returned as strings without attempting to convert to JSON.
