### ISSUE TITLE
[Bug]: Token image problems

### ISSUE THREAD

**Issue by Nightshade525** [RPTools/maptool#3232]
### Describe the Bug

If you attempt to drag and drop multiple tokens to a map, all but one of them fails out into Red X's.  In addition, after that, all further tokens will fail out into Red X's until you reload the program (_not_ the campaign--the full program).  

### To Reproduce

1, Open Maptool and go to a map.
2. Find two or more tokens in a folder elsewhere, and drop them on the map.
3. All but one of the tokens should display as a red X.  All additional tokens placed after this will also display as red Xs.
4. If the program (not just the campaign) is reloaded after saving the campaign, the tokens will display correctly, as will all additional ones applies one at a time.

### Expected Behaviour

Multiple tokens dragged and dropped should display in a stack, and look normally once separated.

### MapTool Info

Maptool v. 1.11.0

### Desktop

Windows 10 Home, Build 19043.1348

**Comment by Phergus** [comment]
>  All additional tokens placed after this will also display as red Xs.

I don't see that behavior.  All single image drops work just fine either before or after a multi-image drop.

Token files (`.rptok`) won't display their images after a drop until a restart/reload of MT because MT already has flagged it as missing.

**Comment by Nightshade525** [comment]
Odd.  It did that with me repeatedly.  Out of curiosity, did you use different tokens, or the same?  I deleted the failed ones and tried to import the same ones manually; perhaps that made the difference for some reason.

**Comment by Phergus** [comment]
Used new, never-before-used tokens for each drop and since I erased my asset cache 2 days ago I know for a fact they weren't in it.

**Comment by Nightshade525** [comment]
Probably it, then; Maptool must have kept the data from the tokens in a cache somewhere, so my putting new ones down didn't change anything; whatever convinced it they had no assets was still there, even though they were technically new.

**Comment by Phergus** [comment]
@cwisniew  pr #3240 fixes the multiple image drop on the server side but when a player client drops 1 or more images on the player client the server gets a red X.  Tested from both Resource Library and File Explorer.

When an image or token file is dropped on the server the player client briefly sees the red question mark but is quickly replaced by the correct image.

**Comment by cwisniew** [comment]
> When an image or token file is dropped on the server the player client briefly sees the red question mark but it is quickly replaced by the correct image.

The ? mark is MT place holder image for "asset is loading/being fetched". I wonder if the asset creation process is slower enough now that its more noticable due to how much more it has to do.

**Comment by Phergus** [comment]
Could be.  Isn't happening now so maybe the last change made it better.

**Comment by Phergus** [comment]
Tested.  Dropping single or multiple tokens or images working as expected.  Images on both player and server clients appear as expected.
