### ISSUE TITLE
[Bug]: Moving a token through a Pit VBL shows no movement count

### ISSUE THREAD

**Issue by timgstewart** [RPTools/maptool#3233]
### Describe the Bug

When a player token enters a hill or pit VBL, the view seems to work well, but the pathing showing movement count is gone and the token only shows 0 movement.

### To Reproduce

1. Create a pit (or hill) VBL area.
2. move a player token into the pit area
3. When moving within the pit area, observe that there is no movement line, but when you start movement outside the area there is, also crossing into the pit from outside the pit has a 0 movement with no line.

### Expected Behaviour

I expect the pit not to affect movement, only to affect vision outside of the pit.  I expect hill not to affect movement within the hill, only to affect vision.

### Screenshots

![image](https://user-images.githubusercontent.com/3614630/144285560-815a850d-a052-4fc0-8a9e-30c52af25bbe.png)
![image](https://user-images.githubusercontent.com/3614630/144285675-6b86b6a2-91a4-4f67-a2d9-24d269f7e3e0.png)
![image](https://user-images.githubusercontent.com/3614630/144285742-2ffe2c34-6d33-42a5-8eca-466a7762e8ff.png)

### MapTool Info

1.11.0

### Desktop

Linux Ubuntu

**Comment by kwvanderlinde** [comment]
Can you verify whether you have this option enabled: 
![ai-movement](https://user-images.githubusercontent.com/7492219/144292186-463e0aaa-8a22-4ab0-afcb-39bbde318d2f.png)

If so, this is expected behaviour. You can disable it to allow movement through VBL and instead use MBL to block movement.

**Comment by timgstewart** [comment]
That works, just need to make sure I have MBL where I have Wall (unless it is an illusionary wall, I guess).  Pits and hills are actually intended to be movement blocking (all vbl types are movement blocking with that option enabled).  Understood, thanks.

**Comment by Phergus** [comment]
Working as designed.
