### ISSUE TITLE
[Bug]: XMLHttpRequest invalid UTF-16 response from lib://

### ISSUE THREAD

**Issue by perkinslr** [RPTools/maptool#3235]
### Describe the Bug

The new `XMLHttpRequest` implementation improperly decodes `lib://` responses as UTF-16, which produces gibberish output.

### To Reproduce

In a frame5, execute this script, with any text data in the target URI

```js
    const x = new XMLHttpRequest()
    x.open("GET", "lib://Test/macro/test.json")
    x.onreadystatechange = () => {
        console.log(x.readyState)
        if (x.readyState == 4) {
            console.log("XMLHTTPRequest Response:" + x.response)
        }
    }
    x.send()
```

### Expected Behaviour

The content of `test.json@lib:Test` should be broadcast to the chat box.
Instead, a string of gibberish text is broadcast.
```XMLHTTPRequest Response:笢景漢㨠㌲�```

### MapTool Info

develop branch from github

### Desktop

Gentoo Linux

**Comment by Phergus** [comment]
Assumed to be working.
