### ISSUE TITLE
[Bug]: HTML5 cannot pass `{body:` to `fetch`

### ISSUE THREAD

**Issue by perkinslr** [RPTools/maptool#3236]
### Describe the Bug

The `fetch` API uses `Request` objects internally, which return a promise for their body argument.  This promise argument is passed directly to the underlying `xmlhttprequest.send` call, which is then serialized as `[object]` to the macro's body.

### To Reproduce

In an html5 frame, call
```js
async function test() {
  let x = await fetch("macro:myMacro@myLib", {body: "some body", method: "POST"})
  await x.text()
}

test()
```
In `myMacro@myLib`, `macro.args` is `[object]` instead of `"some body"`.

### Expected Behaviour

In the target macro, `macro.args` is `"some body"`

### MapTool Info

develop branch from github

### Desktop

Gentoo

**Comment by Phergus** [comment]
Assumed to be working.
