### ISSUE TITLE
[Bug]: Some older formats for .rptok files produce red X for image and or portrait in 1.11.0

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3239]
### Describe the Bug

In MapTool 1.11 rptok files that use older formats fail to add the token image and or portrait images to the asset manager or adds them as "empty" images resulting in a lot red X's...

### To Reproduce

Drag one of the standard tokens from the resource library onto a map (they use a really old format)

### Expected Behaviour

These old tokens should work, images for portrait and token image should be added to the asset manager.

### MapTool Info

1.11

### Desktop

Any

### Additional Context

Part of this is an old bug that has existed for a long time but seems to be occurring a lot more often in 1.11 due to interaction with other changes, and part is due to really old format containing the image imbedded in the Asset file rather than as a seperate file.

The old existing bug is one where some times an empty asset can be added to the asset map overwriting a good asset.

**Comment by Phergus** [comment]
Tested.  Token image, portrait and handout appearing correctly.  Loading/saving of `.rptok` files working.
