### ISSUE TITLE
[Bug]: Health Bars dissapearing for players

### ISSUE THREAD

**Issue by RogorStuff** [RPTools/maptool#3243]
### Describe the Bug

After updating to maptools 1.11, players aren't able to see other tokens healthbars, wether they're pcs or npcs. The health bars are toggled to show (hide checkbox unmarked) and appear in the DM screen, but players can't see these healthbars. Additionally, when a player sets their own hp bar to show manually, after it updates it becomes hidden again.

### To Reproduce

1. Start a server.
2. Log into the server as a player.
3. Set health bars to show, and see how the player's client won't show health bars.
4. Additionally, health bars modified client-side by the player won't appear to the DM's client.
5. If you have any hp bar showing, moving the token will make it dissapear.

### Expected Behaviour

The health bars should stay the same on everyone's client, with the same values, and without dissappearing when they're set to show, even if the token is moved.

### MapTool Info

Version 1.11.0

### Desktop

Windows 7

### Additional Context

==== MapTool Information ====
MapTool Version: 1.11.0
MapTool Home...: C:\Users\Roger\.maptool-rptools
MapTool Install: C:\Users\Roger\AppData\Local\MapTool\app
Max mem avail..: 5 GB
Max mem used...: 4 GB
Custom Property: -DMAPTOOL_LOGDIR=C:\Users\Roger\.maptool-rptools\logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: C:\Users\Roger\AppData\Local\MapTool\runtime
Java Vendor....: Eclipse Foundation
Java Version...: 16.0.2
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  -Djpackage.app-path=C:\Users\Roger\AppData\Local\MapTool\MapTool.exe

==== OS Information ====
OS Name........: Windows 7
OS Version.....: 6.1
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
PATH...........: C:\Users\Roger\AppData\Local\MapTool;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\TDM-GCC-64\bin;C:\Program Files (x86)\Intel\UCRT\;C:\Program Files\Intel\UCRT\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_221\bin;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Gradle\gradle-6.6.1\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Go\bin;C:\Program Files\MATLAB\R2020b\bin;C:\Users\Roger\anaconda3;C:\Users\Roger\anaconda3\Library\mingw-w64\bin;C:\Users\Roger\anaconda3\Library\usr\bin;C:\Users\Roger\anaconda3\Library\bin;C:\Users\Roger\anaconda3\Scripts;C:\Modeltech_pe_edu_10.4a\win32pe_edu;C:\Users\Roger\AppData\Local\GitHubDesktop\bin;C:\Users\Roger\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Roger\AppData\Roaming\npm;C:\Program Files (x86)\Nmap;C:\Users\Roger\go\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2\bin;;.
Number of Procs: 12

==== User Information ====
User Name: Roger
User Home: C:\Users\Roger
User Dir.: C:\Users\Roger\AppData\Local\MapTool

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: VirtualBox Host-Only Ethernet Adapter
Interface Name: eth4
Address...: 192.168.56.1
Address...: fe80:0:0:0:85d2:dfdc:6d7f:99bd%eth4

Display Name..: Intel(R) I211 Gigabit Network Connection
Interface Name: eth5
Address...: 192.168.1.50
Address...: fe80:0:0:0:d485:fc2b:6e3f:df41%eth5

Display Name..: Npcap Loopback Adapter
Interface Name: eth6
Address...: 169.254.70.104
Address...: fe80:0:0:0:5cee:7d7d:9e4c:4668%eth6

Host Address...: 192.168.56.1
Default Gateway: 192.168.1.1

==== Locale Information ====
Country.: Spain
Language: Spanish
Locale..: Spanish (Spain)
Variant.: 

==== Encoding Information ====
Default Locale:   es_ES
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 1920x1080(32)
Display 2: 1920x1080(32)

==== Internet Gateway Devices ====
	Error scanning for IGDs.
	No IGDs Found!

Also, the campaign is using bag of tricks

**Comment by Phergus** [comment]
Tested.  Health bars enabled show on both server & player clients and stay enabled when tokens moved by either Player or GM.
