### ISSUE TITLE
[Bug]: onInitiativeChange macros on lib tokens are not running on 1.11.2

### ISSUE THREAD

**Issue by jadams533** [RPTools/maptool#3245]
### Describe the Bug

My onInitiativeChange macros on lib tokens are not running properly.
onInitiativeChangeRequest macros are running.

### To Reproduce

Create a lib: macro with an onInitiativeChange macro.
Start Initiative with at least one token.
Click "Next" for initiative.

### Expected Behaviour

At least one macro I have expects to turn off an aura.
Expecting a chat output of "It worked!"

### MapTool Info

v1.11.2, installed via msi package

### Desktop

Windows 11

**Comment by Phergus** [comment]
@jadams533 using this campaign I am seeing both initiative events in 1.11.2.

[Initiative Events 1.10.4.cmpgn.zip](https://github.com/RPTools/maptool/files/7654965/Initiative.Events.1.10.4.cmpgn.zip)

Can you test this on your end?

**Comment by cwisniew** [comment]
This error is occurring if the lib:token has an onInitativeChange() but no onInitativeChangeRequest(), I have submitted a fix, but in the mean time as a work around you can add a onInitativeChangeRequest() to the lib:token to have it working again.

**Comment by Phergus** [comment]
Ah.  Never mind @jadams533

**Comment by cwisniew** [comment]
Attaching a test campaign file
[initTest.cmpgn.zip](https://github.com/RPTools/maptool/files/7654970/initTest.cmpgn.zip)

**Comment by Phergus** [comment]
I just needed to remove the ICR event off my test campaign.

Fix tested.  Event working as expected now.

**Comment by jadams533** [comment]
Looks like the test campaign is working.

**Comment by jadams533** [comment]
And with a onInitiativeChangeRequest added to my lib, it works in my campaign.

**Comment by Phergus** [comment]
Let us know if you come up with a scenario where it does fail.
