### ISSUE TITLE
[Bug]: Display Name field needs to be blank

### ISSUE THREAD

**Issue by michaelperino** [RPTools/maptool#3247]
### Describe the Bug

Creating a new map has the display name "Grasslands" by default instead of being blank.

### To Reproduce

1. Map new map
2. Read Display Name field

### Expected Behaviour

Display name field blank when not in use

### Screenshots

![image](https://user-images.githubusercontent.com/33206261/144726940-7b4ccc29-ddaf-41b9-b2ef-a95e88d21528.png)

### MapTool Info

Version 1.11.2

### Desktop

All

**Comment by Phergus** [comment]
Why does it need to be blank?

**Comment by michaelperino** [comment]
Makes it more obvious that people don't need to change it. Also, if you set the name to something else on creation instead of renaming it later, the display name will be grasslands with the GM Name being different.

**Comment by Phergus** [comment]
> Also, if you set the name to something else on creation instead of renaming it later, the display name will be grasslands with the GM Name being different.

Actually if you set the GM name and don't touch the Display Name field it gets set to the GM name.

**Comment by FullBleed** [comment]
> Actually if you set the GM name and don't touch the Display Name field it gets set to the GM name.

That's good.  But it doesn't make much sense for the Display Name to say "Grasslands" if it's going to take on the (GM) Name.  Better to have it blank in that case, imo.  Would be even better if there was a way to have it mirror the "Name" field entry if blank, but not if it has has any kind of manual input.  Not sure that's possible though.

**Comment by Phergus** [comment]
The Display Name could be updated to match when the GM Name is changed to get the visual confirmation of the change.

**Comment by bubblobill** [comment]
Not a fan of the Display Name. I agree that it should be blank unless specifically set

**Comment by Phergus** [comment]
Display Name is now blank.
