### ISSUE TITLE
[Bug]: impossible to reference macros in subdirectories of addon with macro links

### ISSUE THREAD

**Issue by dark-ether** [RPTools/maptool#3259]
### Describe the Bug

macro links with / don't work , and neither does escaping them.

### To Reproduce

1. create addon with a subdirectory containing a macro
2. try to reference it with a macro link
3. see that it doesn't work

### Expected Behaviour

macros in addons should be able to be linked even if in subdirectories

### MapTool Info

1.11.3

### Desktop

arch linux

**Comment by emmebi** [comment]
The problem appears to be in [the regular expression](https://github.com/RPTools/maptool/blob/d02f3ab57f97ddd9b966375a8aa51f2e74a496a9/src/main/java/net/rptools/maptool/client/functions/MacroLinkFunction.java#L380) used to parse the macro links.

In a link like
```
macro://jukebox/playAllClient@lib:bizland5e/all/Impersonated?281_Escape_from_Shadow.mp3
```
the above regular expression will match `jukebox` as the macro name, with no qualification, causing the macro to fail with an error like
```
Must specify a location for the macro jukebox
```

**Comment by emmebi** [comment]
Assign this to me, I will give it a try at fixing as suggested in [the discord chat ](https://discord.com/channels/296230822262865920/915297924605423636/1081691760775938148)

**Comment by emmebi** [comment]
Uploading the following two files to expose the problem. The add on exposes a macro in the `folder1` folder called `hello` which takes a parameter.

There is a macro in the Campaign window of the campaign which will call the add-on. This doesn't work with MapTool 1.12.2, but works with the fix applied.

[maptool-test-addon.zip](https://github.com/RPTools/maptool/files/10948908/maptool-test-addon.zip)
[bug3259.zip](https://github.com/RPTools/maptool/files/10948909/bug3259.zip)
