### ISSUE TITLE
[Bug]: getTokenMap incorrectly returning two map names 

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3263]
### Describe the Bug

In this campaign --> [Dropbox Link](https://www.dropbox.com/s/7nq4kq09fjv9cna/JUHv0.2a_Rev%20update%20V12.cmpgn?dl=0)

This code
```
[h: tkn = findToken(getMacroLocation())]
[h: map = getTokenMap(tkn)]
[broadcast(map)]
```

Produces --> **Main Event,CampsiteJUHa1**

There are no duplicate tokens (code is running on lib token)
There are four maps with no dodgy names, deleting one or two maps will stop the behaviour.

### To Reproduce

1. Download campaign
2. Go to map "Main Event"
3. Select token "lib:timer"
4. Click macro "_onCampaignLoad"
5. Move mouse over map. (much error text will spew forth)
6. Click macro "KILL_CLOCK"
7. The code producing the error lives in macro group **4. Sample Mouse Action** and is called **objectHover**

### Expected Behaviour

Only one map name should be returned.

### MapTool Info

1.10.3

### Desktop

Win10

**Comment by kwvanderlinde** [comment]
The reason for multiple maps being returned is that there are two tokens with the same ID (`CE828059C6F344D0A887CFC69DD23F9F`). The first is `lib:timer` on the map `Main Event`, and the second is `lib:timer_alpha0.1` on the map `CampsiteJUHa1`.

**Comment by bubblobill** [comment]
Okay, that's a little less obvious for me to notice.
I presume it is not a bug then

**Comment by bubblobill** [comment]
Not a bug. An accurate result from an inobvious cause.
