### ISSUE TITLE
[Bug]:  MapTool Server is currently pushing the full asset instead of allowing client to pull

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3271]
### Describe the Bug

MapTool Server is currently pushing the full asset instead of allowing client to pull, this bypasses the sending of assets in chunks. Which could cause more noticeable lag on s server with slow connection and big assets.

### To Reproduce

It just happens, you don't need to reproduce it.

### Expected Behaviour

The asset should be sent as an empty array will result in  the client will fetch the asset via getAsset which will then be sent in chunks.

### MapTool Info

1.11.3

### Desktop

All

### Additional Context

The code for pushing the asset is still in MapTool but its pushed with an empty array. This is so we can in the future push smaller assets which it doesn't make much sense to ask the client to fetch if they dont have it.

**Comment by cwisniew** [comment]
This has been fixed

**Comment by Phergus** [comment]
@cwisniew you flagged the PR for this as a draft.  It's still open.

**Comment by cwisniew** [comment]
@Phergus  yeah the protobuf changes addressed the problem since that was happening at roughly the same time so I didn't complete the PR. I will delete it.
