### ISSUE TITLE
[Bug]: Hero Lab token drag and drop from Library window onto map appears to be broken

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#3274]
### Describe the Bug

Drag and drop a token from a Hero Lab POR file for a PF1e token causes the following exception:

<img width="353" alt="error message" src="https://user-images.githubusercontent.com/50708405/145700342-176ede7b-784f-4111-a99b-158a86d1868f.png">

### To Reproduce

1. Use File menu "Add Resource to Library" feature to add the attached "Barmaid.por" file (below) to the library.

[Barmaid.zip](https://github.com/RPTools/maptool/files/7698118/Barmaid.zip)

2. From the Library window, drag the "Barmaid" token to the map.

3. You'll get an unexpected exception with the message shown in the "Describe the Bug" attachment.

### Expected Behaviour

The token should appear on the map without any error messages.

### MapTool Info

MapTool 1.11.4

### Desktop

Windows 10

### Additional Context

I use this feature all the time.  It's critical to my campaigns.

**Comment by adventuremagic123** [comment]
With the same Hero Lab POR file (see attachment above) for the Barmaid.por file, this procedure works in MapTool 1.10.4.

**Comment by adventuremagic123** [comment]
There might be licensing issues with the Barmaid.zip file, so try this one if you have trouble.  It only requires the core rules which comes with the basic PF1e license purchase for Hero Lab.  You might have to open and resave the Fred.por file for it to work in the Library window of MapTool.

[Fred.zip](https://github.com/RPTools/maptool/files/7708478/Fred.zip)

**Comment by cwisniew** [comment]
> There might be licensing issues with the Barmaid.zip file, so try this one if you have trouble. It only requires the core rules which comes with the basic PF1e license purchase for Hero Lab. You might have to open and resave the Fred.por file for it to work in the Library window of MapTool.
> 
> [Fred.zip](https://github.com/RPTools/maptool/files/7708478/Fred.zip)

I have never used the functionality before,  before I submit a fix do you mind checking the below screen shots to see if thats what you expect from Fred.por?


![image](https://user-images.githubusercontent.com/73173/145939650-a61d0b1b-7af5-4508-b1d3-24d7bdd21c74.png)

![image](https://user-images.githubusercontent.com/73173/145939657-256db228-ae4a-419e-aecd-1f6a013333db.png)

![image](https://user-images.githubusercontent.com/73173/145939667-8fd35015-84c8-4cab-bad7-1f4c1f7d963e.png)

![image](https://user-images.githubusercontent.com/73173/145939679-d1d58254-4a52-4b0d-a3fc-5d278a671168.png)

![image](https://user-images.githubusercontent.com/73173/145939685-39eb10a1-f5d7-4e25-a3f7-40628a33ea2c.png)

**Comment by adventuremagic123** [comment]
Yes, I think that's right.

**Comment by adventuremagic123** [comment]
I didn't test to see if that character would reproduce the problem.  I assumed it would, but perhaps I was too cavalier.

**Comment by adventuremagic123** [comment]
A work-around for this problem is to use MapTool 1.10.4 to create tokens from Hero Lab(R) POR files -- and then use those tokens in MapTool 1.11.4, for example.

**Comment by adventuremagic123** [comment]
BTW, thank you very much about a thousand times for working on that.

**Comment by kwvanderlinde** [comment]
(just for future reference since this is already fixed)

Tokens created via `createToken()` can have the same problem of having a null `sizeMap`... except it's more serious because such tokens can also be saved as part of the campaign file. Trying to reopen a campaign with such tokens is impossible due to the deserailization errors.

Considering I just did this to my own campaign today, I'm pretty happy the issue willl be fixed in 1.12.0 :smile:

**Comment by kwvanderlinde** [comment]
The fix for this appears to be working as intended. It currently requires a patch to the protobuf code in PR #3443, but with that change present everything seem to function correctly.

I am seeing one exception in the console the first time I start a server or connect to one:
```
08:44:40.953 (ImageManager.java:428) [pool-9-thread-1] ERROR - BackgroundImageLoader.run(/home/kenneth/Nextcloud/Personal/RPGs/tools/MapTool/Resource Packs/Ken's Customizations/Fred.por/1/Fred,html, 969a799d95503b2c52b7ea25df7ba258): image not resolved
java.io.IOException: Could not load image /home/kenneth/Nextcloud/Personal/RPGs/tools/MapTool/Resource Packs/Ken's Customizations/Fred.por/1/Fred
	at net.rptools.lib.image.ImageUtil.bytesToImage(ImageUtil.java:316) ~[main/:?]
	at net.rptools.maptool.util.ImageManager$BackgroundImageLoader.run(ImageManager.java:424) [main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
This doesn't seem to do any harm, nor does it really seem related to this issue. Just looks like an "expected" result of the Hero Lab statblock being returned alongside all the image assets when trying to load the token images.

**Comment by Phergus** [comment]
Presumably this only happens if the Library pane is pointing at a folder with `.por` files in it.
