### ISSUE TITLE
[Bug]: WebRTC is not resilient to temporary disconnections

### ISSUE THREAD

**Issue by fishface60** [RPTools/maptool#3298]
### Describe the Bug

If the WebRTC connection becomes disconnected then the client connection stops sending messages even after WebRTC reconnects.

### To Reproduce

Contrive for a WebRTC client to spend a period of time not sending heartbeat messages and observe the client stops receiving messages.

For the test code that I found this with, start a server with WebRTC and EasyConnect enabled and alias TESTSERVER, then run the code below, and observe it works as far as reporting the PIN and allowing you to accept the user, but when the client pauses to decrypt the private key so it can decrypt the authentication challenge the server disconnects, but then reconnects and the MapTool server receives the challenge response, but then does not send the success response.

```bash
git clone https://gitlab.com/richardmaw/dca.git
cd dca
git checkout 36ca8b2a64b3cef972041a2c579c83e63c685b79
cargo run client name "Test User"
cargo run client key generate
cargo run server kind set TESTSERVER registry-web-socket
cargo run hello-world TESTSERVER
```

### Expected Behaviour

WebRTC peer connections are designed to be resilient to temporary disconnections, and a connection only becomes failed if it is unable to reconnect.

### MapTool Info

1.11.4

### Desktop

Linux[Debian]

**Comment by Phergus** [comment]
@fishface60 can you test if this is fixed with the 1.12.0 alpha release?

**Comment by fishface60** [comment]
Sorry I didn't reply sooner. I didn't test the alpha because the beta came out before I got around to it, this seems to be fixed, I at least can't cause it to happen the way I used to.

**Comment by Phergus** [comment]
@fishface60 no worries.  Thanks for the feedback!
