### ISSUE TITLE
[Bug]: getTokens() by ownership

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3304]
### Describe the Bug

Providing a JSON array of ownership types as a condition in getTokens() returns nothing.

### To Reproduce

1. place some tokens on the map with various ownership states
2. test with single string arguments
3. [r: getTokens("json", json.set("", "owned", "byall"))] --> works
4. [r: getTokens("json", json.set("", "owned", "none"))]--> works
5. [r: getTokens("json", json.set("", "owned", "self"))]--> works
6. test with JSON array
7. [r: getTokens("json", json.set("", "owned", json.append("", "byall", "none", "self")))]--> big empty

### Expected Behaviour

Expected JSON array of tokenIds.
Array should allow use of multiple ownership types as documented in the wiki.

### MapTool Info

1.11.4

### Desktop

Win10

**Comment by Azhrei** [comment]
I believe it’s working [as documented](https://wiki.rptools.info/index.php/getTokens]m):

> `owned` - A JSON Array containing player names. All tokens that have at least one of the listed players as owner will be returned. Alternatively, a string containing one of the following options:

The JSON array must contain player names.  **Alternatively**, it can contain one of the strings you used.  The JSON may not contain those strings itself.

If you’re proposing that it should work differently, that’s a separate discussion for a feature request but not a bug per se.
