### ISSUE TITLE
[Bug]: Missing message for Player Already Connected.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#3311]
### Describe the Bug

If a player tries to connect a second time the error dialog shows the key and not that message.

### To Reproduce

1. Start server
2. Start 2nd client and attempt to connect with same username
3. Get error message (see screenshot)

### Expected Behaviour

Expect to see proper error message.

### Screenshots

![unknown](https://user-images.githubusercontent.com/34379254/147885108-39bb952e-5216-4b61-83cb-b4adb663d9b1.png)

### MapTool Info

MT 1.11.4

### Desktop

Any

### Additional Context

Reported by Kolifarr on Discord.
https://discord.com/channels/296230822262865920/296657960720007169/927211287203692554

**Comment by kwvanderlinde** [comment]
Verified that the message "That player name is already connected." is now displayed instead of a translation key.
