### ISSUE TITLE
Make empty string evaluate to false in macro language.

### ISSUE THREAD

**Issue by Wyrmwood** [RPTools/maptool#3314]
My code is littered with 
```
if (id == ""): id = 0
if (id): something = doSomethingWithId(id)
```
because if throws a null pointer exception instead of evaluating to false.

**Comment by Phergus** [comment]
Failed to follow template.

**Comment by Wyrmwood** [comment]
Where's the template?

**Comment by melek** [comment]
Click new issue and then select feature request.
