### ISSUE TITLE
Allow multiple and setting of color for personal lights

### ISSUE THREAD

**Issue by oliver-szymanski** [RPTools/maptool#332]
I have a PR to allow a GM setting color for Sight type (personal light source) in campaign. E.g. Darkvision could be showing as red, etc. Also you can define multiple personal lights.

So you can use it as:
Darkvision: circle scale r60#FF0000
Darkvision: circle scale r60#FF0000 r100#00FF00

**Comment by oliver-szymanski** [comment]
Done in https://github.com/RPTools/maptool/pull/334

**Comment by JamzTheMan** [comment]
how about a black/white/greyscale filter, that;s Darkvision in Pathfinder? 😄 
Thanks for the PR!

(on my wish list, probably a 2.0 thing, FX may make it easier)

**Comment by oliver-szymanski** [comment]
we can haggle about it ;) i might have a look about darkvision when I find time

**Comment by rkathey** [comment]
This came from one of our users. Adding for context.

> Ran in an issue with one of my players this week playing D&D 5th edition. In 5e dark vision is “you can see in dim light within 60 feet of you as if it were a bright light and in darkness as if it were dim light.” But any token with Darkvision sight is always as if it’s in bright light. Is there a way to change DV to look dim??? The idea in 5e is that a player with a torch can see better within 20ft, then a player with DV and no torch, but my players forget that because DV doesn’t really emulate that

**Comment by oliver-szymanski** [comment]
it could at least now be shown with a personal color setup for the personal light source. So it shows different (just not as grayscale)

**Comment by oliver-szymanski** [comment]
you could use more then one personal light with color from light gray to black

**Comment by rkathey** [comment]
Tested. While light and sight settings were never my strong suit, it appears to be working. I placed multiple visions and light sources on the map and was able to get the desired effect.
