### ISSUE TITLE
[Bug]: Numbers stored in Add-On Library properties are Strings.

### ISSUE THREAD

**Issue by Pmofmalasia** [RPTools/maptool#3322]
### Describe the Bug

When a number is stored in the properties of an Add-On library, it is instead stored as a string. So, `[h:setLibProperty("Whatever",0,"Lib:AddOnLib")]` becomes `"0"` instead of `0`.

### To Reproduce

1. Create an Add-On Library
2. Use the setLibProperty() function to store a number in any property
3. `[r:getLibProperty()+1000]` should return "x1000" instead of (x+1000)

### Expected Behaviour

That numbers would be numbers.

### MapTool Info

1.11.4

### Desktop

Windows 10

**Comment by Pmofmalasia** [comment]
[Debugging Addons.zip](https://github.com/RPTools/maptool/files/8443998/Debugging.Addons.zip)

Campaign file + addon for debugging

**Comment by Phergus** [comment]
@Pmofmalasia please test with the beta 1 release.

**Comment by Phergus** [comment]
@Pmofmalasia please confirm that this issue has been resolved with beta 3.  Thanks.

**Comment by Pmofmalasia** [comment]
Resolved for me in beta 3
