### ISSUE TITLE
MapTool 1.5.0 is missing logging options that used to be in the launcher

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#335]
I believe there was discussion about adding a GUI interface to allow logging to be turned on/off from inside MapTool without restarting, but until we get to that point, some way to turn on logging (particularly for macro execution logging) that is equivalent to what the launcher provided would be helpful for macro authors.

**Comment by JamzTheMan** [comment]
Ya, I never got a chance to dive into that.  I would think log4j2 would allow us to dynamically change the logging needed.

I did find a program/lib that read log4j2 log files but only in XML format IIRC (was looking to see if there was a lib already for viewing log4j2 files).

Maybe a simple panel could be whipped up...

**Comment by Azhrei** [comment]
I'd like to be able to find all classes registered with log4j and present a list box with checkboxes for each one.  Then it's an easy select all/deselect all.

Minimum would be some way to turn on a particular set of logging classes from the command line, but that could get messy; I'd prefer the GUI approach.

**Comment by JamzTheMan** [comment]
Hmm, via the log manager? Could possibly do that but that could be a pretty long list...

I picture a UI as well with a filter. But let's start with the basics if just dynamically turning debug mode on/off I guess.

**Comment by rkathey** [comment]
BTW: A command line option would be fine to fill the gap until a better solution is put in place.

**Comment by JamzTheMan** [comment]
Fixed in #433
