### ISSUE TITLE
[Bug]: Using addons prevents players from connecting to server

### ISSUE THREAD

**Issue by Pmofmalasia** [RPTools/maptool#3359]
### Describe the Bug

Using an addon in a campaign file prevents players from joining if that addon is not already "loaded in" to their current campaign file. They receive an "Incorrect Password during handshake" error when attempting to join. Adding the same addon to an empty grasslands campaign allows the player to connect.

### To Reproduce

1. Create an addon and add it to the campaign
2. Start a server
3. Have someone try to join the server - they will receive an error.
4. Send the .mtlib file to the player you want to join and have them add it to an empty campaign
5. Have that player try joining again - they will be able to join.

### Expected Behaviour

The connecting player should not need to pre-install any addons to join.

### MapTool Info

1.11.4

### Desktop

Windows 10

**Comment by thelsing** [comment]
@Pmofmalasia  Can you add an example campaing that I can use for debugging please?

**Comment by Pmofmalasia** [comment]
[Debugging Addons.zip](https://github.com/RPTools/maptool/files/8437435/Debugging.Addons.zip)

Sure - the zip has the campaign file and the addon, since you'll need the addon to connect as the other player. Since the example campaign just needs _an_ addon and the content doesn't really matter, I went ahead and made one that will work for some other issues as well. Will upload to the relevant issues also.

**Comment by Pmofmalasia** [comment]
Note: Connecting via LAN on the same machine DOES appear to work - noticed this when making the debugging campaign. Got a friend on another computer to try it out and confirmed that they were unable to connect.

**Comment by dark-ether** [comment]
i seem to have encountered this problem, but having the player add the addon before entering allowed to connect. i am fairly certain its the same problem,as i reproduced the bug with a empty campaign by adding only the addon.

**Comment by Phergus** [comment]
Needs testing by someone who can have an external client connect.

**Comment by kwvanderlinde** [comment]
Tested via LAN. Player client was on a clean machine without the addon installed or cached. Was able to connect to the GM client  with no noticeable issues. `onInit` event was run upon connecting. I was also able to add a library to an already running server and it was picked up by the player client.

Everything appears to be functioning correctly.

**Comment by Pmofmalasia** [comment]
LAN was working previously in 1.11.4. I might be able to test with a friend on another network today, but neither myself nor him are capable of putting together the dev build.

**Comment by kwvanderlinde** [comment]
I thought that was just LAN on the same machine that was working previously?

**Comment by Pmofmalasia** [comment]
Oh, I apologize, I was reading too quickly and missed that bit about the separate machine. You're correct, it was the same machine before.
