### ISSUE TITLE
[Feature]: Upgrade handshake cipher to AES CBC

### ISSUE THREAD

**Issue by fishface60** [RPTools/maptool#3360]
### Feature Request

The handshake process requires decrypting, stripping a prefix from and reversing the challenge, then re-encrypting it.
The cipher used is "AES" which means "AES/ECB/PKCS5Padding".
"ECB" ciphers are disrecommended in-general because they are vulnerable to replay attacks, chosen plaintext attacks and are easier to build a code-book for.
This means such ciphers aren't always available in cipher suites, which makes interoperability more difficult, and while I know of no vulnerability upgrading may be a useful precaution.

### The Solution you'd like

Change the cipher to "AES/CBC/PKCS5Padding", which involves changing the handshake to include exchanging IV parameters.

### Alternatives that you've considered.

De-scope password support from my hobby client, or find another library that will accept ECB upstream.

**Comment by Phergus** [comment]
@thelsing you've tested this change?  If so, add `tested` label.
