### ISSUE TITLE
[Feature]: Add a function impersonate(no one)

### ISSUE THREAD

**Issue by Lector** [RPTools/maptool#3373]
### Feature Request

There is a function for impersonate(). There should also be a function to remove impersonation.

### The Solution you'd like

I would like you to add ether a function called removeImpersonation() or make it possible to call impersonate() with 0 or -1 as a parameter to clear the impersonated token. When you have a token impersonated there is a red X in the chat window. This function i want should exactly work like this button.

**Comment by kwvanderlinde** [comment]
I believe this already exists in the form of `impersonate("")`, though it isn't documented.

**Comment by Lector** [comment]
Thats true and resolves my issue.
Thank you!
