### ISSUE TITLE
[Feature]: All types of VBL on tokens (not just Wall)

### ISSUE THREAD

**Issue by henczati** [RPTools/maptool#3377]
### Feature Request

MT v1.11.5 token VBL-to-map and VBL-from-map functionality seems to completely ignore VBL types other than Wall.

### The Solution you'd like

Would it be possible for **token VBL-to-map and VBL-from-map to handle all VBL types**?

### Additional Context

**E.g.** it would be great to be able to put **Hill-VBL on door tokens.**

**Comment by FullBleed** [comment]
Yes.  Kind of strange that we can't.

This may be non-trival.  @kwvanderlinde (the author of hill and pit vbl) might have more insight.

**Comment by kwvanderlinde** [comment]
This is covered by #3052 (though I had to update it just now to avoid outdated wording). We should use that issue to discuss this feature (and I'll give an answer there).
