### ISSUE TITLE
[Feature]: Better light source overlap

### ISSUE THREAD

**Issue by henczati** [RPTools/maptool#3378]
### Feature Request

Light sources in MT v1.11.5 it seems like are actually darkness emitters. Overlapping light radii make the wrong effect: the intersections are darker instead of lighter.

### The Solution you'd like

Use a more precise lighting model to get the correct overlap patterns.

I imagine something like adding them up at the intersecting areas and cropping at 1.0 (or 0xff) per channel.

E.g. a purely theoretical idea for the light interference:
1. Have an axis-aligned bounding-box (very fast intersection check) around each light source, obviously square, with a side of `outermost_radius * 2`.
2. Check if any 2 bounding-boxes intersect.  First you can try with checking all possible pairings---easy to implement but very inefficient.  Using some type of bounding-volume-hierarchy would be much better to limit necessary checks, but more work to implement.  They are frequently used for collision detection.  Choose a fitting preexisting 2D type, consider that you only have static objects, and all of them are circles.
3. If the bounding-boxes do intersect, do the slower `sqrt( (x2-x1)^2 + (y2-y1)^2 ) < r1 + r2` distance-of-circles calculation per pair.
4. If the outermost light circles really do intersect, mark them for a common group.
5. For all separate groups of intersecting light sources add them up into a dynamically created (possibly cached) transparent image of the size of the axis-aligned bounding-box of the whole intersecting group.
6. After appropriately positioning the group image on the MT map, override darkness with the non-transparent parts of the dynamically created light-group image.  Do this for every non-intersecting group of light sources.

### Alternatives that you've considered.

I considered taking the max of the light values, which would probably still look better than the current solution for grayscale light sources, but would still be incorrect and would screw up colored lights.  So not good enough.

### Additional Context

See bad behavior on the image.  The overlapping areas should strengthen the luminance, not weaken.

The thin squares over the rubble represent holes in the cave ceiling and have light sources of `Hole in ceiling: circle 8 12#aaaaaa 14#666666 15#333333 21#111111 35#000000` intended to show an effect of close-to-exponentially attenuating sunlight shining in.  The last component is meant to be the ambience (dnd dim light) the others are just meant to be visual effect / eye candy.
![MTv1 11 5_lightsource_overlap_bug](https://user-images.githubusercontent.com/5007476/156309906-e3e273b1-c441-497c-8719-7bb864398a39.png)

**Comment by Phergus** [comment]
Duplicates multiple other issues particularly #2094 & #3391.
