### ISSUE TITLE
Need ISSUE template in the repo

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#338]
There is currently no template for creating new issues here on GitHub.

**Comment by Tdue21** [comment]
Those are really easy to set up. I can whip a couple of suggestions, if you'd like?

**Comment by Azhrei** [comment]
Sure; then I don’t have to do the research. :)

At a minimum, it should include the type of MT install (exe, dmg/pkg, jar, whatever), and if jar, then the version of Java being used (the others come with a JRE prepackaged).

Perhaps look at the Help > Gather Debug Info and include other pertinent fields?  Memory settings, locale, and encoding come to mind.  Maybe screen resolution and scaling (given the recent issue that might involve scaling)...?

Maybe whether the problem appeared only after running a server, or only if certain Start Server options are selected.

Obviously, some things might be important to ask explicitly and others we can let users describe in the issue description; tough part will be deciding how far to go in playing “20 questions”...

Once we have a basic outline, we can pass it around the devs to see if they can think of anything else.

Thanks!

**Comment by cwisniew** [comment]
Don't go overboard most of that stuff listed above will be irrelevant most of the time and getting a huge questionnaire will just put people off

**Comment by JamzTheMan** [comment]
The templates are already in develop from my fork and will take affect once I get develop merged to to master soon(tm)

**Comment by Tdue21** [comment]
Hm. I didn't realize that. I have just submitted a PR for the bug report (#342).

**Comment by Azhrei** [comment]
> Don't go overboard most of that stuff listed above will be irrelevant most of the time and getting a huge questionnaire will just put people off

Lol, you'll have to tell @JamzTheMan to delete everything in his existing template then. 😁

We'll keep all of it.  People can (and will) leave blank anything they don't feel like filling in.  We can certainly tell them that they should only fill in what they can/want to.

**Comment by JamzTheMan** [comment]
Well master is getting rebased so, ya. ;)

**Comment by cwisniew** [comment]
Jamz's template is fine, the questions are more relevant and not based on "the last issue we saw"

**Comment by Phergus** [comment]
@Azhrei The template has been added.  Can this be closed?

**Comment by JamzTheMan** [comment]
closing!
