### ISSUE TITLE
[Bug]: Auras with multiple ranges appear as a single color

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3426]
### Describe the Bug

Although aura definition share the same syntax as for lights, an aura with multiple ranges will always render as a single color despite the same not being true for lights.

### To Reproduce

1. Add the following to the campaign lights:
    ```
    Aura Test
    ----
    light: circle 10 20#000000 30#555555 40#aaaaaa 50#ffffff
    aura: aura circle 10 20#000000 30#555555 40#aaaaaa 50#ffffff
    ````
2. Add two tokens to the map, equiping one with "light" and the other with "aura"
3. Observe the rendering differences between the two.

### Expected Behaviour

Auras should render each range according to the specified color, just as is done with lights. 

### Screenshots

This shows the differences between how a light and an aura are rendered despite having the same properties:
![image](https://user-images.githubusercontent.com/7492219/170891354-30681735-d3c2-4473-a76a-f6844af00868.png)

### MapTool Info

1.11.5

### Desktop

Linux Mint

**Comment by kwvanderlinde** [comment]
It's not obvious from the screenshot or details, but what's actually happening is that all of the aura's colors are being drawn at the largest distance. So the result is the same as what you would get by equipping 5 different auras that are all 50' but with a different colors.

**Comment by Pmofmalasia** [comment]
The copied aura from the example works correctly for me in 1.13.2:

![image](https://github.com/RPTools/maptool/assets/79408871/68223755-3314-47a0-a7a5-6fbfdbedea6a)
