### ISSUE TITLE
[Feature]: lockZoom()

### ISSUE THREAD

**Issue by FullBleed** [RPTools/maptool#3438]
### Feature Request

The ability to "Lock Zoom" is in the menu bar under **Tool>Lock Zoom**.  I would like to be able to trigger it on clients via a function: lockZoom().

Some use cases:

- Improve the ability to create a more fully featured custom UI overlay.
- Lock Zoom on specific maps where that might be desired when clients switch to them (using custom map selectors).
- Allows us to temporarily Lock Zoom when scaled overlay animations are being used.

### The Solution you'd like

lockZoom(lockState)

**Parameters**

    lockState - The state of Lock Zoom, true(1) or false(0).

### Additional Context

It would be nice to be able to do it on a "per map" basis, but that would be added functionality and I don't want to make the feature more complicated than it needs to be.

Also of note is that Lock Zoom is currently a "per client" setting, so clients will be able to "unlock" the zoom if it creates a problem for them.  I could, however, make the argument that there may be situations where a GM might want to set up something that is at a particular zoom level and location and being able to lock the zoom without allowing override might be desirable.... but I don't want the basic feature request to be derailed so, for now, just being able to trigger the lock with a function will provide some new functionality.

**Comment by cwisniew** [comment]
Just a friendly reminder that this feature request discusses functionality not supported (overlay animations synchronised with map),  see #3419.

I won't close the issue as other valid reasons for it were raised. I would suggest anyone implementing it do not lock the user out from unlocking it via the menu option; repeating background patterns can cause unease for some people, and if they get locked into one they cant zoom in and out to make them less problematic for them it would be an issue.

**Comment by AAUCrisp** [comment]
Sorry if this is not the place to do this. Will gladly move this, if needed.

Not for the same thing, but an option to lock all maps to a certain (grid dependant) size would be incredible.

For those of us using MapTool on a TV on/in the gametable (especially using minis on top of it), it would have us not worry about finding the corrects zoom everytime there's a map change.

Doesn't need to be DM forcing Client for this... just the option. And then the option to ignore it on individual maps (guess via the current Lock Zoom)

**Comment by kwvanderlinde** [comment]
Tested. `setZoomLock(1)` locks the zoom, and `setZoomLock(0)` unlocks it. The Tool menu shows the current state whether set via the menu or macros. After calling `setZoomLock(1)`, the menu can still be used to unlock it.
