### ISSUE TITLE
[Feature]: Add an issue template for code cleanup and performance improvements

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3439]
### Feature Request

Whenever there is room for improvement in the code base (code cleanup, performance, etc.), I find myself having to fill in the "Bug Report" form for something that is not really a bug. Several of the "Bug Report" fields aren't generally meaningful in this case (e.g., reproduction steps, screenshots, desktop, additional context) nor does the template guide a person in opening a good issue. Also the "bug" label is automatically added and needs to be replaced by something more appropriate.

### The Solution you'd like

A new "Codebase Improvement" issue template is added that captures the following information:
- A summary of the problematic part of the current codebase.
- How the codebase can be improved.
- Expected benefits after the improvement. E.g., performance benefits, maintenance benefits, etc.

Issues opened with this template will have the "code maintenance" label added automatically.

### Alternatives that you've considered.

- Continue filing bug reports, using **Describe the Bug** to explain the deficiency and **Expected Behaviour** to explain the improvement
- Add more than one new template. E.g., one specialized for performance, one for maintainability, etc.

**Comment by Phergus** [comment]
Refactor template shows as option for New Issue.  Closing.
