### ISSUE TITLE
[Bug]: Vision broken on clients when a UVTT map is imported after server start

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3440]
### Describe the Bug

After importing a UVTT map on an already running server, player clients do not receive the VBL/MBL or light tokens of the map. As a result, players with vision can see everything on the map without regard for lighting or vision blocking. After saving and reloading the campaign, clients function as expected.

### To Reproduce

1. Open a MapTool instance.
    1. Start a server
    2. Import a UVTT map with VBL and lights
    3. Ensure vision is enabled and the map is visible to players.
2. Open a second MapTool instance to act as a client
    1. Connect to the server
    2. Add a token to the map. Ensure the token has vision.
    3. Observe the entire map being on display.

### Expected Behaviour

Player clients should respect the vision and lighting properties of the imported UVTT map. This should be the case for maps imported at any of these times:
- Prior to starting a server
- After starting a server but before players connect
- After players connect to the server

### MapTool Info

1.9.3, 1.10.4, 1.11.5, develop

### Desktop

Linux Mint 20.3

### Additional Context

This has the same symptoms as #3434 but is reproduced differently, appears to have a different cause, and goes back at least as far as 1.9.3 (I think it actually goes back as far as the UVTT importer itself).

I have done some investigation on #3434 (thinking it was the same issue) and discovered that `DungeonDraftImporter` directly adds VBL/MBL and light tokens to the `Zone` that belongs to the original `Campaign`, but it does not issue any server commands to sync these changes to the clients.
- https://github.com/RPTools/maptool/issues/3434#issuecomment-1149582891
- https://github.com/RPTools/maptool/issues/3434#issuecomment-1150291893

**Comment by Phergus** [comment]
So this probably goes back to the zone being added early in the import process triggering it's transfer to the player clients but the VBL is added after that without using server commands.

**Comment by Phergus** [comment]
Tested on UVTT maps with/without lights.
- Importing after server started and after client connected.
- Importing after server started but before client connected.
- Importing before server starts.

Tested exposing FoW in all three cases.

No problems seen.
