### ISSUE TITLE
[Feature]:  Add the ability to drag and drop .mtlib files into MapTool

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3453]
### Feature Request

While developing add ons having the ability to drag and drop the .mtlib file from file explorer/finder/etc would remove some of the friction when making/testing multiple changes. Dragging and dropping is much quicker and less fiddly than going to menu, opening up the add on dialog,  navigating to the add on in the  file dialog.

### The Solution you'd like

Simple drag and drop of mtlib. It should create or replace the add on.

### Alternatives that you've considered.

Not doing it?

**Comment by Phergus** [comment]
Tested.  D-n-d added library to MapTool.  Updating version of library, repackaging library and dropping in a second time updated version info shown in Add-On Libraries dialog. Tested Library functions working as expected.
