### ISSUE TITLE
[Bug]: VBL precision problem.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3466]
### Describe the Bug

When there are slight cracks in VBL, MapTool sometimes doesn't know how to process it correctly leading to broken vision.

### To Reproduce

1. Download the test campaign file and rename to remove the .zip extension: [Why can't pcs see themselves.cmpgn.zip](https://github.com/RPTools/maptool/files/9074820/Why.can.t.pcs.see.themselves.cmpgn.zip)
2. Open the campaign file. Notice the PC in the "house".
3. Hover the mouse over the PC. Notice the lack of vision lines.
4. Change to player view (**View** > **Show As Player**). Notice the PC disappear.

### Expected Behaviour

The PC should be able to see the interior of the house but not outside of it. In general, vision should work reasonably even in the precense of subtle VBL features.

### Screenshots

Notice the VBL encompasses the entire house, but the interior is wide open:
![image](https://user-images.githubusercontent.com/7492219/178064279-0412eeec-4c00-4541-93ab-95676d259157.png)

Zooming in by a lot shows the culprit crack in the VBL at the interior corner of the south-east side of the door:
![vbl-crack](https://user-images.githubusercontent.com/7492219/178064379-3e4f374e-696d-43ea-9981-3e077919713d.png)
This crack does not run all the way through the door, it is actually a very short length.

When we mouse over the token, we should see the white vision lines around the interior like this:
![expected-vision](https://user-images.githubusercontent.com/7492219/178065608-6cdff732-cd71-4bfd-a5f2-21a4e3ab7652.png)

### MapTool Info

1.11.5, develop

### Desktop

Linux Mint 20.3

**Comment by Phergus** [comment]
So probably an issue with line of sight data for the wall not quite matching up with the door line-of-sight because of fractional pixel locations.

**Comment by FullBleed** [comment]
Also, if you fire up a server>client and give the client ownership of the token you'll see that the client can not see the owned token in the current state (something you noted using "Show as Player".  But the interesting thing is that if you punch even a tiny hole in the VBL (not necessarily where you've noted the crack, but anywhere along the perimeter) the token becomes visible and the visibility lines appear.

**Comment by kwvanderlinde** [comment]
> So probably an issue with line of sight data for the wall not quite matching up with the door line-of-sight because of fractional pixel locations.

Yeah, its ever so slightly off.

I've debugged this issue, and what I've found is that `AreaMeta` is not able to correctly decide whether the interior subpath is a hole (ocean). The exterior subpath is handled correctly and is not considered a hole (island).

This slight crack show a weakness in the approach `AreaMeta` uses for calculating holes: it adds up the angles of all the turns made by the ring and check whether - in total - the turns are more clockwise or more counter-clockwise. Because `PathIterator` returns holes in a clockwise order, a clockwise turn should indicate a hole. But when it comes to that small crack, the wrong angles get calculated: +90°, then +179.9995, then +90°. That second angle _should_ be a negative angle, but its so close to 180° that it could go either way. If we were to correct this angle to be negative, then the VBL does in fact function correctly.

**Comment by Phergus** [comment]
For that particular map the VBL information is constructed from LOS info in the Dungeondraft UVTT file.  Just spitballing but what if we just round up fractional locations on import?

**Comment by kwvanderlinde** [comment]
That could help some situations like this one, but it wouldn't be a general solution. Even with integer endpoints lying exact on pixels, we can still make line segments that have very small angles between them. But at least they wouldn't be combined with extremely close points.

But I always hesitate to tweak inputs and would rather fix the algorithm. I've tried out two ideas already and wil be coming with a PR soon:
1. We are reading `float`s from the `PathIterator` :grimacing:, but if we instead read `double`s instead that is enough to fix the angle detection in this case.
2. JTS has a more robust and precise orientation algorithm that we could use - it also gives the correct results, even when still reading `float`s from the `PathIterator`. This would avoid the instabilities associated with the angle calculations.
 
Applying both these changes, I don't think we'll see a failed hole detection on any reasonable topology.

**Comment by Phergus** [comment]
Testing supplied campaign.  Now works as expected.
