### ISSUE TITLE
MapTool 1.5.0 keyboard shortcuts not working on map view

### ISSUE THREAD

**Issue by batalyx** [RPTools/maptool#347]
When working in the map view, GM or player, some shortcuts, like `Cmd-G` or `Shift-Cmd-P` do not work, but some, like `Cmd-N` do.  But if the macro editor is open and active, the shortcuts like `Cmd-G` etc. start to work.  I tested this only on macOS 10.14.3, but with different keyboard layouts and with both laptop & external keyboard. Layouts or external keyboard didn't help.

**Comment by Azhrei** [comment]
Confirmed — it happens for me as well.  Strange that it doesn't work prior to opening the macro editor window.

When I type Cmd-G, for example, I can see the **View** menu flash quickly to indicate that an element was activated, but it has no effect.  I'll try setting some breakpoints to see if any code is actually being triggered.  (We know that at least one keystroke in the macro editor overlaps with a menu entry; maybe this is related somehow?)

**Comment by Azhrei** [comment]
I cannot replicate this in 1.6.0-alpha6, i.e., Cmd-G works both before, during, and after opening the macro editor window.  If no one reports the issue still occurs, I'll close it.

**Comment by Phergus** [comment]
Closing.  Appears to have been resolved in later versions.
