### ISSUE TITLE
[Bug]: Non GMs are able to drag and drop add-ons and they shouldn't be allowed to

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3481]
### Describe the Bug

Non GMs are able to drag and drop add-ons and they shouldn't be allowed to

### To Reproduce

As a non GM drop a mtlib onto the map

### Expected Behaviour

it should tell you that you can't do it it	

### MapTool Info

Development branch

### Desktop

All

**Comment by Phergus** [comment]
Tested.  Non-GMs are no longer able to drag-n-drop an Add-On.
