### ISSUE TITLE
[Request] Base64 encoding/decoding in macros

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#349]
With the new REST functions, it is possible to integrate with a lot of services, incl. Github. I am investigating the possibility of a framework/library for integrating a campaign, or library tokens with Github. 
This will need base64 decoding and encoding capabilities though. 

As far as I can determine this is not currently possible, and thus I am submitting this request. I am willing to attempt implementing it myself, but my Java skills are very rusty, and there may be issues I am not aware of.

Thus, I would like some developer feedback on this.

**Comment by JamzTheMan** [comment]
If approved this should be in this months release.

I created and successfully tested creating new files in GitHub via REST API using the new MapTool functions utilizing the new base64 functions.

https://github.com/JamzTheMan/maptool-github-lib/tree/feature-test/libs/Lib:GitHubAPI

**Comment by Tdue21** [comment]
Nice.

**Comment by cwisniew** [comment]
approved and merged into develop branch :)

**Comment by JamzTheMan** [comment]
Thanks!
