### ISSUE TITLE
Can't resize token manually

### ISSUE THREAD

**Issue by krevett62** [RPTools/maptool#3495]
In recent version 1.11.4 and 1.11.5, I can't set a token size to "free" and resize it manually (but if moved to another layer that works), only get the option for "native" size.
Is this intended behavior? If I remember previously it was possible to resize token freely?

**Comment by Phergus** [comment]
Items on the Token layer have never been freely resizable.

**Comment by krevett62** [comment]
Thanks for the answer I haven't been using MT for quite some time and don't know why, I was persuaded it was possible ^^
Sorry for the issue then ;)

**Comment by Phergus** [comment]
No worries.  In general the forums or MT discord server are best for these kinds of questions.
