### ISSUE TITLE
[Bug]: Add-On import fails if there are additional fields in the library.json file.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3498]
### Describe the Bug

If there are addition fields in the library.json file the add on import fails. It should just ignore unknow fields (or make them quarriable by the add on some how.

### To Reproduce

Create an add-on with an additional field in library.json

### Expected Behaviour

It should just ignore unknow fields (or make them quarriable by the add on some how.

### MapTool Info

1.11 and 1.12-alpha

### Desktop

All

**Comment by Phergus** [comment]
Tested.  Add-On with unexpected fields in library.json file now load without error.
