### ISSUE TITLE
Did You Know dialog

### ISSUE THREAD

**Issue by joshsziegler** [RPTools/maptool#35]
_Moving this [from the forums](http://forums.rptools.net/viewtopic.php?f=7&t=26329) to GitHub Issues seems like the right thing to do (easier for me to track at least). Let me know if I'm wrong. I still don't have a good handle on how you all like to operate._

Ok, I've done a few documentation pull requests (based on existing info from the forums) and the one on UPnP discoveryTimeout. Now I'd like to tackle the hopefully easy "Did You Know" popup box ([issue 34 in the Google Spreadsheet](https://docs.google.com/spreadsheets/d/1K0dTjnxQ9a213nFyO1XqMZFDRa4kPb4Exu-95YYJaL0/edit#gid=276252974)). 

I used Abeille for the UPnP UI, but that was because the Setting UI already existed. Going forward, how should I create the UI for this Did You Know feature? I see open issues for an HTML and/or JavaFX based UI? I also see Swing is being phased out. Can I get some guidance?

Thanks!

**Comment by Jaggeroth** [comment]
For the time being I would stick with Abeile.

While I am quite eager for us to move onto Java FX, I think it will take a significant amount of work and I have read worrying comments about mixing Swing and FX. So I think we should hold off adding FX elements until we have an agreed plan.

**Comment by joshsziegler** [comment]
I updated the forum post with a few questions on implementation: http://forums.rptools.net/viewtopic.php?f=7&t=26329

**Comment by Azhrei** [comment]
My understanding is that problems with integrating Swing and FX are just that:  integrating the two of them in the same control, ie. JDialog or JFrame or JWindow.  However, I'll be the first to admit that my knowledge of JFX is pretty old, circa JFX 1.1 (and a little 1.2).

**Comment by JamzTheMan** [comment]
My contribution:
- TIL if you hold "control" key down while drawing a "template" you can move the template around before placing it...

**Comment by Phergus** [comment]
OBE.  See #3154.
