### ISSUE TITLE
[Bug]: createTable fails

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#3510]
### Describe the Bug

[h: createTable("Test",1,1)] should create a table named "Test" however it results with "java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.entryList" is null error executing expression createTable("Test",1,1)."

### To Reproduce

[h: createTable("Test",1,1)]

### Expected Behaviour

Table named "Test" is created

### MapTool Info

1.12 alpha

### Desktop

Windows 10

### Additional Context

This works in 1.11.5 without failure

**Comment by Irarara** [comment]
This is another #3254 related NPE. I've got a fix for this.

**Comment by Phergus** [comment]
Tested.  Function now creates empty table as before.
