### ISSUE TITLE
[Bug][1.12.0 alpha]: setAllStates() function no longer works

### ISSUE THREAD

**Issue by Pmofmalasia** [RPTools/maptool#3514]
### Describe the Bug

When used, the setAllStates() function gives the following error:

> java.lang.ArrayIndexOutOfBoundsException error executing expression setAllStates(0).

This persists when opening a blank campaign and dropping a generic image as the token.

This worked fine in 1.11.4 (and probably 1.11.5, though I skipped that one).

### To Reproduce

1. Make new campaign
2. Drop image on campaign
3. Impersonate token
4. Run [setAllStates(0)] in the chat
5. Error message

### Expected Behaviour

For the function to work properly.

### MapTool Info

1.12.0 alpha

### Desktop

Windows 10

**Comment by Phergus** [comment]
Tested.  Working as expected.
