### ISSUE TITLE
[Feature]: include UI language in e.g. getInfo("client")

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#3515]
### Feature Request

Library tokens and add-ons are rarely, if ever, localizable. This is understandable for a lot of reasons. Not least of which it is not possible to get the UI language currently in use by MapTool. 
It would help a lot towards localizations of macros and user functions, if it was possible to get the UI language. 

### The Solution you'd like

I would think the prettiest solution would be to expand the client information returned from `getInfo("client")` to include a property containing the ISO 639-1 code for the selected language. 
This should of course be propagated to the javascript interface as e.g. `MapTool.clientInfo.userLanguage()`.

**Comment by Phergus** [comment]
Tested.  Two-letter language code is returned via MTScript using `getInfo("client")` or JavaScript using `js.eval('return MapTool.clientInfo.userLanguage()')`.
