### ISSUE TITLE
Enhancement: Map snapshots

### ISSUE THREAD

**Issue by tlhonmey** [RPTools/maptool#352]
I keep running into circumstances (large vehicles, crystal balls, balconies, etc) where having the ability to create a "viewport" that shows a certain area on a different map (or the same map in a different place) would be handy (Without it I have to shuffle things back and forth between maps and try to keep everything synchronized so nothing gets lost.

I rather assumed that such a feature would be too complicated to implement as it would require adding the ability to have multiple maps loaded at the same time.  But then it hit me...

If there were a macro function that would create an image snapshot of a particular section of a map at a specifiable output resolution, everything else necessary to automate slapping that image into a token is already there...  

And all of a sudden the characters standing on the balcony can get reasonably quick updates on what the characters in the courtyard are doing, meanwhile the characters in the courtyard can still be where they can see the ground-level stuff.  

Characters can move in and out of large vehicles with multiple decks, and characters standing on the dock can see the people on the deck as the boat pulls in and those on the deck can see the dock that the boat is pulling up to only without having to carefully move the entire boat and all its sections to every new town map and then deal with the boat and the character tokens being on different layers and yet needing to move in sync, or all the trouble one can run into with trying to stuff too many different kinds of things into too few layers.

This seems like it could be a pretty powerful feature...  Is grabbing an image of a section of map at all feasible?  Even if you had to move the view area there to do it, that could be scripted pretty easily with current functions.  Having the captured area not depend on the screen layout of the one running the macro would be better for obvious reasons, but I'd take whatever I can get.

**Comment by JamzTheMan** [comment]
Is there a reason you can't use setViewArea, setZoom, setCurrentMap?

You could also create a token (on the for even) with specific ownership and vision to limit/reveal what is needed.

ttp://lmwcs.com/rptools/wiki/setViewArea

**Comment by Jaggeroth** [comment]
When it comes to maps with several levels I use the technique of having the levels all on the same map and use shadow tokens to represent tokens on different levels. Not always possible but works in many situations.

Example:
https://forums.rptools.net/viewtopic.php?f=13&t=23398#p238958

**Comment by tlhonmey** [comment]
@JamzTheMan Those functions let me set the viewport to show a particular section of the map, yes.  But that's not what I'm talking about.  I'm looking for more like what Jaggeroth is saying, only with better automation.

@Jaggeroth That's basically what I've been doing, but having to move tokens in a synchronized manner in multiple places is cumbersome.  The player on the bottom level moves their token, I then have to move the shadow token on the top level to match.  Automation of this must be set up per-token and calibrated to compensate for any differences in perspective or scale.  It's...  annoying.  

If, instead, I could trigger a macro function that would take a snapshot of the bottom level section of the map (including any tokens, drawings, or other assorted scribbles) that snapshot could then just get scaled and slapped into a background token for the top level.  The view syncing no longer has to be set up per token, whatever gets done on the lower-level section of the map gets automatically inserted into the view from the upper-level section of the map.  Synchronization only has to be set up per area, not per token and doesn't have to be turned on and off when tokens enter and leave the area.

If I'm really consistent about how I set things up I could do this with existing macros and an external screenshot program, but that's extremely hackish and totally non-portable between machines.

**Comment by Jaggeroth** [comment]
Ugh, that sounds horrible. No offence. 

The example to which I linked automates by name. So when any token gets moved the script looks for any tokens with the same name but ending in "shadow"  and moves them accordingly.

**Comment by tlhonmey** [comment]
Using an external program for it would be pretty horrible.  If there were a way to just have maptool create an image out of a map region then it becomes a simple snap, swap image, and maybe reset the size of the destination token.  Doesn't matter how many tokens are in the area,  captures drawings too,  doesn't need to be set up and torn down per token, and could also be used to show arbitrary moving, rotating scenery say around a vehicle based on where its external token goes with only a modicum of math.

**Comment by thelsing** [comment]
As Jaggeroth meetioned desired functionality can be done with shuffling larger token around.
