### ISSUE TITLE
[Bug]: Tokens with a portrait interrupt onMouseOver events for overlays 2-parts

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#3539]
### Describe the Bug

This one is difficult to describe.
Part 1: 
When using onMouseOver events that include placing an overlay on top of the token the overlay refresh / onMouseOver event does NOT refresh once the token portrait is drawn in the window (and the bug is likely more broad than this example), 

The focus appears to change to the portrait and will not revert back to the token for onMouseOver refreshing.
The 6 block overlay should be the same size as the selected token.  The 6 block overlay each "block" is clickable to run a macro.
![image](https://user-images.githubusercontent.com/100969108/184498077-07df3238-86b4-4b65-835a-66aa5301beaf.png)

Part 2: 
For tokens that do NOT have a portrait, the onMouseOver refresh is drawn as expected however clicking on defined pointermaps in the overlay being drawn will not work.  
The 6 block overlay draws correctly as you zoom in / out, however the 6 block overlay is not clickable even though mouseover the 6 block will work.
![image](https://user-images.githubusercontent.com/100969108/184498166-d20b2dd5-e9e5-4923-9cd0-8b0eb955c9c1.png)

In 1.12 alpha - I'm also getting an odd flashing refreshing issue anytime I mouse over a token without a portrait (this doesn't happen in 1.11.5)

### To Reproduce

See the notes above

### Expected Behaviour

Part 1:  Overlay should should refresh via onMouseOver regardless of a token portrait.

Part 2: Overlay should be clickable regardless of a token having a portrait.

### Screenshots

see above

### MapTool Info

1.12 alpha, v1.11.5

### Desktop

Windows 10

### Additional Context

[onMouseOver_Overlay-bug.cmpgn.zip](https://github.com/RPTools/maptool/files/9331576/onMouseOver_Overlay-bug.cmpgn.zip)

**Comment by cwisniew** [comment]
So a couple of things here, the onMouseOver is not an actual event; it's a kludge someone has come across that is "use at own risk" no mouse events were ever designed to work with it, so it is not surprising that issues arise with subsequent mouse events. 

Second, for alignment of icons, see
https://github.com/RPTools/maptool/issues/3419

With regards to the above link, this is specifically one of the scenarios called out as while we are not going to intentionally break it there is a high chance of it  breaking as we upgrade libraries / add new functionality.

I will leave this open for a week or two, if no one wants to pick it up I will label as wont fix and close

**Comment by Jmr3366** [comment]
Some of the techniques used in the campaign are not directly supported and will be closed
