### ISSUE TITLE
[1.12.0 beta] Not Work SetTokenImage()

### ISSUE THREAD

**Issue by juan0286** [RPTools/maptool#3542]
Describe the Bug
Can´t use seTokenImage() it's break null pointer exception. 
.

To Reproduce

Use setTokenImage() to change token image to a token. Can use setTokenImage("image:tokenname")  or setTokenImage("asset://bfcb3b05576dde5427f689dc3e9a0b77")

.
Expected Behaviour
Change image to the Token current

Screenshots
I do not have

MapTool Info
1.12.0.beta

Desktop
Windows 10

Additional Context
I return to MapTool 1.11.5  and did work good in this version.

**Comment by Phergus** [comment]
@thelsing when you updated TokenImage.java you put in a String cast but you still end up with a `null` being passed and so in UpdateToken the first `setStringValue()` call fails.

```
  private static void setImage(Token token, String assetName) throws ParserException {
    MD5Key md5key = getMD5Key(assetName, SET_IMAGE);
    MapTool.serverCommand()
        .updateTokenProperty(token, Token.Update.setImageAsset, (String) null, md5key.toString());
  }
```

```
  public void updateTokenProperty(Token token, Token.Update update, String value1, String value2) {
    updateTokenProperty(
        token,
        update,
        TokenPropertyValueDto.newBuilder().setStringValue(value1).build(),
        TokenPropertyValueDto.newBuilder().setStringValue(value2).build());
  }
```

**Comment by thelsing** [comment]
Is there an easy way to reproduce this? I don't really use macros.

**Comment by Phergus** [comment]
This campaign has macros for testing this bug.  Remove the `.zip` extension.
[setTokenImage Error i3542.cmpgn.zip](https://github.com/RPTools/maptool/files/9353992/setTokenImage.Error.i3542.cmpgn.zip)
.
