### ISSUE TITLE
[Request] larger tooltip field in macro editor

### ISSUE THREAD

**Issue by JakeVDTS** [RPTools/maptool#355]
The new macro editor is great, but the tooltip field, now on the details tab, seems even smaller than it was on the old system. Given that a tooltip can take quite a bit of info, it'd be nice if it had a larger field to input info into and see it without having to copy and paste from another source. 

The details window is fairly large, so unless a bunch of new details are going to be added, it seems the window has plenty of room for a larger tooltip box.

**Comment by Azhrei** [comment]
I have this on my todo list.  I need to add toggle buttons for Find and Replace popups, so I'll enlarge the tooltip field.

**Comment by rkathey** [comment]
@JamzTheMan I'm confused as to how feature logging in #433 fixes this.

**Comment by JamzTheMan** [comment]
Ooops, wrong one...

**Comment by Phergus** [comment]
Feature complete in 1.5.2
