### ISSUE TITLE
Select Map doesn't handle large numbers of maps well

### ISSUE THREAD

**Issue by JakeVDTS** [RPTools/maptool#356]
I think this has been an issue from the begginning, just never bumped into it myself until I ran this sandbox campaign.

Currently, while you can make as many maps as your system can handle. You can have more maps than your screen can 'stack' vertically, but maptool does nothing to help navigate to those other maps. 

Maptool needs to either prevent you from making more maps than its menu can navigate, or better yet, allow you to scroll through the maps down the side. A possbly more complicated feature like a search could possibly also be great.

I know one can just export/import maps to manage large numbers of maps, and its probably the better way. But feels like a bug for the program to have a list that gets too big to properly display.

**Comment by Azhrei** [comment]
+1

This should be fixed.  How hard can it be to put the buttons into a JScrollPane or similar?

**Comment by Merudo** [comment]
PR #723 implements this.

![scrollBar](https://user-images.githubusercontent.com/7371085/65253988-2b35cc00-dac1-11e9-9434-82a103492db8.png)

**Comment by JamzTheMan** [comment]
That will make several people happy. It's been an issue floating in Reddit lately...

**Comment by Merudo** [comment]
I saw the complains in Reddit - that's what got me to make the fix.

**Comment by Phergus** [comment]
Tested.  Working as described.
