### ISSUE TITLE
[Feature]: getIllumination()

### ISSUE THREAD

**Issue by Lector** [RPTools/maptool#3565]
### Feature Request

In my framework, you can assign multiple types of light/dark-sources to a token. When attacking a token, i want to calculate how bright the target is illuminated and determine a modifier for the attack roll according to this value. Since there are multiple light sources in my campaign with different modifiers i would also like to get the lumens of the illumination or the brightest light source, that is illuminating my target.

### The Solution you'd like

I would like to call getIllumination(token) to get the lumens of the brightest light-source or the brightest light-source that is illuminating the token.

### Alternatives that you've considered.

Since my framework does not support magical darkness yet, i used to determine the illumination manually with 2 scripts. All my light-sources have 4 Parts in 4 different Radii (e.g. "Torch 1", "Torch 2", "Torch 3", "Torch 4"). The lights are turned on/off by a custom UI so when using a Torch all the technically lights "Torch 1-4" are turned on/off at once. My scripts look like this:

getIllumination():
```[h: target = arg(0)]

[h: info = json.indent(getInfo("map"), 2)]
[h: visiontype = json.get(info, "vision type")]

[h,if(visiontype == "NIGHT"),Code:
{
	[h: newTarget = copyToken(target)]
	[h: tokens = getTokens("json", json.set("",
		"layer", json.append("[]", "token", "object", "background"),
		"range", json.set("", "token", newTarget, "from", 0, "upto", 24),
		"light", json.set("", "value", 1, "category", "DSA")
	))]
	[h: brightness = 4]
	[h,foreach(tok, tokens),Code:{
		[h: newTok = copyToken(tok)]
		[h: setHasSight(true, newTok)]
		[h: setSightType("Normal", newTok)]
		[h: isTargetVisible = json.length(canSeeToken(target, newTok))]
		[h,if(isTargetVisible > 0): brightness = min(brightness, getBrightnessFrom(target, tok))]
		[h: removeToken(newTok)]
	}]
	[h: removeToken(newTarget)]
	[h: macro.return = brightness]
};
{
	[h: macro.return = 0]
}]
```

getBrightnessFrom():
```[h: target = arg(0)]
[h: illuminator = arg(1)]
[h: distance = getDistance(illuminator, 1, target, "NO_GRID")]
[h: lights = getLights("DSA", "json", illuminator)]
[h: radius = 0]
[h: currentLight = ""]

[h,foreach(light, lights),Code:{
	[h,if(endsWith(light, "4") == 1 && currentLight == ""): currentLight = light]
}]

[h,if(currentLight != ""),Code:{
	[h: cmp = json.indent(getInfo("campaign"), 2)]
	[h: dsalights = json.get(json.get(cmp, "light sources"), "DSA")]
	[h,foreach(light, dsalights),Code:{
		[h: lname = json.get(light, "name")]
		[h,if(lname == currentLight): radius = json.get(light, "max range")]
	}]
};{}]

[h,if(radius == 0),Code:{
	[h: macro.return = 0]
};{
	[h: width = scale(getSize(target)) / 2.0]
	[h: steps = (distance - width) / (radius / 4.0)]
	[h: brightness = max(0, min(4, floor(steps)))]
	[h: macro.return = brightness]
}]
```

This works almost fine. One problem occurs when a light-source is not hitting the center or corner of the target. In this case canSeeToken() does not work but thats fine. Whats more problematic is the magical darkness that i wanted to add support for in my framework. I would like to add negative lumen lights for this case. This works well for the visuals in the map. But the calculation of the illumination modifier when attacking a token should get very complicated at this point.

Since maptool should internally know more details about the illumination of a token i think its easier for framework-devs to get a function for all this.

**Comment by Lector** [comment]
I very much appreciate that this request finally gets my long-awaited attention :)

Since it has been almost a year since i posted this request im going to add an updates version of my workaround macro. This has been updated to the 1.13.0+ lighting system and now supports magical darkness. The script itself seems to return the correct values but it can cause a bit of trouble because it has to copy some tokens temporarily. This can result in a flickering when clicking the attack button, which is pretty ugly, especially when my players are connected...

`[h: target = arg(0)]
[h: viewer = arg(1)]


[h: sight = hasSight(viewer)]
[h: sightType = getSightType(viewer)]
[h: setSightType("Magiesinn", viewer)]
[h: setHasSight(true, viewer)]
[h: visiblePoints = canSeeToken(target, viewer)]
[h: setHasSight(sight, viewer)]
[h: setSightType(sightType, viewer)]



[h: cmp = json.indent(getInfo("campaign"), 2)]
[h: campaignLights = json.get(json.get(cmp, "light sources"), "DSA")]
[h: campaignLights = json.sort(campaignLights, "desc", "name")]

[h: map = json.indent(getInfo("map"), 2)]
[h: visiontype = json.get(map, "vision type")]
[h: grid = json.get(map, "grid")]
[h: cellWidth = json.get(grid, "cell width")]
[h: cellHeight = json.get(grid, "cell height")]
[h: targetSize = scale(getSize(target)) / 2.0]
[h: width = round(cellWidth * targetSize)]
[h: height = round(cellHeight * targetSize)]




[h,if(visiontype == "OFF"): return(0, 0)]

[h,if(visiontype == "NIGHT"): lightValue = 0; lightValue = 4]
[h: darkValue = 0]
[h: lightOutput = "{}"]
[h: darkOutput = "{}"]
[h,foreach(point, visiblePoints),Code:
{
	[h: lightOutput = json.set(lightOutput, point, lightValue)]
	[h: darkOutput = json.set(darkOutput, point, darkValue)]
}]


[h: pointDict = json.set("",
"CENTER", "[h: offsetX = 0] [h: offsetY = 0]",
"TOP_LEFT", "[h: offsetX = -width] [h: offsetY = -width]",
"TOP_RIGHT", "[h: offsetX = width] [h: offsetY = -width]",
"BOTTOM_LEFT", "[h: offsetX = -width] [h: offsetY = width]",
"BOTTOM_RIGHT", "[h: offsetX = width] [h: offsetY = width]"
)]


[h: tokens = getTokens("json", json.set("",
	"layer", json.append("[]", "token", "object", "background"),
	"range", json.set("", "token", target, "from", 0, "upto", 24),
	"light", json.set("", "value", 1, "category", "DSA")
))]

[h,if(getLights("DSA", ",", target) != ""): tokens = json.append(tokens, target)]


[h: lightSources = "[]"]
[h,foreach(lightSource, tokens),Code:
{
	[h: lights = getLights("DSA", "json", lightSource)]
	[h: lights = json.sort(lights, "desc")]
	[h: lightSources = json.append(lightSources, json.set("", "token", lightSource, "light", json.get(lights, 0)))]
}]
[h: lightSources = json.sort(lightSources, "desc", "light")]

[h: lightest = 0]
[h: darkest = 0]


[h: i = 0]
[h: campaignLight = json.get(campaignLights, i)]
[h,foreach(lightSource, lightSources),Code:
{
	[h: illuminator = json.get(lightSource, "token")]
	[h: light = json.get(lightSource, "light")]

	
	[h,while(light != json.get(campaignLight, "name")),Code:
	{
		[h: i = i + 1]
		[h: campaignLight = json.get(campaignLights, i)]
	}]

	[h: radius = json.get(campaignLight, "max range")]
	
	[h: segments = json.get(campaignLight, "light segments")]
	[h: firstSegment = json.get(segments, 0)]
	[h,if(json.get(firstSegment, "lumens") < 0): sign = -1; sign = 1]
	[h: radiusStep = radius / json.length(segments)]

	
	[h: sight = hasSight(illuminator)]
	[h: sightType = getSightType(illuminator)]
	[h: setSightType("Lightsource R"+radius, illuminator)]
	[h: setHasSight(true, illuminator)]
	[h: illuminatedPoints = canSeeToken(target, illuminator)]
	[h: relevantPoints = json.intersection(illuminatedPoints, visiblePoints)]
	
	[h: setHasSight(sight, illuminator)]
	[h: setSightType(sightType, illuminator)]

	[h: illuminatorSize = scale(getSize(illuminator)) / 2.0]
	
	[h,foreach(point, relevantPoints),Code:
	{
		
		[h: evalMacro(json.get(pointDict, point))]
		
		[h: offsetX = offsetX + round(illuminatorSize * cellWidth)]
		[h: offsetY = offsetY + round(illuminatorSize * cellHeight)]
		[h: x = getTokenX(1, target) + offsetX]
		[h: y = getTokenY(1, target) + offsetY]
		[h: distance = getDistanceToXY(x, y, 1, illuminator, "NO_GRID", 1)]
		[h: lumens = 5 - ceil(distance / radiusStep)]
		[h: lumens = sign * max(0, min(4, lumens))]
		
		[h,if(distance <= radius && lumens > 0):
			lightOutput = json.set(lightOutput, point, max(json.get(lightOutput, point), lumens))]
		
		[h,if(distance <= radius && lumens < 0 && illuminator != viewer):
			darkOutput = json.set(darkOutput, point, min(json.get(darkOutput, point), lumens))]
	}]
}]


[h: lumens = 0]
[h,foreach(point, visiblePoints),Code:
{
	[h: lumens = max(lumens, json.get(lightOutput, point) + json.get(darkOutput, point))]
}]


[h: illumination = min(4, max(0, 4-lumens))]
[h: macro.return = illumination]`

**Comment by kwvanderlinde** [comment]
The only thing I would change compared to what is requested is to generalize it by accepting a position instead of a token. I.e., `getIllumination(x, y)` instead of `getIllumination(token)`. The token's center or other position can be passed in to get results for the token. Maybe also add in a map name / ID to have some more control.

I'd like some feedback on this, but the way I see it a good first version of this function would assume no sight magnifiers and would not include personal lights. I.e., it would only consider "real" lights at their normal ranges. That would make this feature pretty straightforward, and we can always expand it in the future.

**Comment by Lector** [comment]
getIllumination(x, y) with coordinates seems like a good idea to me. I could definitely use that to simplify my macro so that I don't have to modify any light sources, which currently results in an ugly flickering effect. The only temporary change I would need to make is to set the visibility of the current token to a value that ignores the illumination in order to determine the visible points that I need to check for brightness. Since the runtime doesn't increase with the number of light sources in this case, I hope to finally eliminate the flickering.

**Comment by Lector** [comment]
Can I expect this in the upcoming v1.14? If so, I would like to thoroughly test it with the new version before its release.

**Comment by kwvanderlinde** [comment]
I basically had this put together and then hit a busy time and promptly forgot about it :grimacing: But yes, I can wrap it up pretty quick now and it should make it into 1.14.

**Comment by Lector** [comment]
Nice to hear about this. Let me know when the next RC for 1.14 including this feature is available so i can rework my framework and make some testing. If everything works like expected ill release the next version of my framework for MT 1.14.

**Comment by Lector** [comment]
I replaced my huge and laggy workaround code by this and it works:

```[h: target = arg(0)]
[h: viewer = arg(1)]

<!-- Here we get the width/height of the target in pixels, according to the map settings -->
[h: map = json.indent(getInfo("map"), 2)]
[h: visiontype = json.get(map, "vision type")]
[h: grid = json.get(map, "grid")]
[h: cellWidth = json.get(grid, "cell width")]
[h: cellHeight = json.get(grid, "cell height")]
[h: targetSize = scale(getSize(target))]
[h: width = round(cellWidth * targetSize)]
[h: height = round(cellHeight * targetSize)]

<!-- Without vision, we cannot determine any sight hindrance and abort the process. -->
[h,if(visiontype == "OFF"): return(0, 0)]

<!--
Here we check which points are visible from the observer's point of view.
For this, we temporarily set the vision to magical vision so that only walls and obstacles restrict vision.
-->
[h: sight = hasSight(viewer)]
[h: sightType = getSightType(viewer)]
[h: setSightType("Magiesinn", viewer)]
[h: setHasSight(true, viewer)]
[h: visiblePoints = canSeeToken(target, viewer)]
[h: setHasSight(sight, viewer)]
[h: setSightType(sightType, viewer)]

<!-- Here we iterate through the visible sample points and check the highest Illumination of those visible points -->
[h: maxLumens = -1000]
[h,foreach(point, visiblePoints),Code:
{
	[h: x = getTokenX(1, target)]
	[h: y = getTokenY(1, target)]
	[h,switch(point),Code:
		case "CENTER":
		{
			[x = x + (width / 2.0)]
			[y = y + (height / 2.0)]
		};
		case "TOP_LEFT":
		{
		};
		case "TOP_RIGHT":
		{
			[x = x + width]
		};
		case "BOTTOM_LEFT":
		{
			[y = y + height]
		};
		case "BOTTOM_RIGHT":
		{
			[x = x + width]
			[y = y + height]
		}
	]
	[h: lumens = getIllumination(x, y, getCurrentMapName(), "[]")]
	[h: maxLumens = max(maxLumens, lumens)]
}]

<!-- When its daytime and there is no magical darkness (Lumens < 0) we can see clearly and set lumens to maximum -->
[h,if(visiontype == "DAY" && maxLumens >= 0): maxLumens = 100]

<!-- Here we map our value of 0-100 to a malus between 0 and 4 -->
[h: macro.return = min(4, max(0, 4 - (maxLumens / 25.0)))]
```

Thank you very much for that little magic. This helps me a lot. No more flickering and all sight modifiers are automatically calculated on DAY & NIGHT maps even with support for magical darkness.
