### ISSUE TITLE
[Bug]: Title bar and frame border color in dockable windows does not change with the new themes

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#3582]
### Describe the Bug

What the title says. The preview images in the theme selector show the title bar color changing to match the theme, but on Windows (at least) they remain the same color across all themes, gray (unfocused)/blue (focused). This makes the dockable windows look rather unattractive when using dark themes, and makes it so the window titles are illegible in all themes when they're not focused (as opposed to only when using light themes).

### To Reproduce

Use a dark theme and look at any dockable window.

### Expected Behaviour

The theming should apply to frames. 

### Screenshots

![](https://i.imgur.com/i6wwImG.png)
![](https://i.imgur.com/7qTH8NP.png)

### MapTool Info

develop branch

### Desktop

Windows 10

**Comment by Irarara** [comment]
I was poking around and it turns out the white border I mentioned in the title has nothing to do with the windowing system (oops) and can just be addressed in code. Happy to make a PR for that, unless you already got to it, @cwisniew.

**Comment by cwisniew** [comment]
I have been working through the list of issues and fixing them, and this is what it currently looks like, selected and non-selected.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/73173/188769519-62141d8a-b07b-49c3-a34d-521f7baa5f5f.png">

<img width="220" alt="image" src="https://user-images.githubusercontent.com/73173/188769612-6ffdf929-99a6-4ab1-afa5-00516a060d03.png">

**Comment by cwisniew** [comment]
And with a light theme
<img width="213" alt="image" src="https://user-images.githubusercontent.com/73173/188770116-b0561797-23ac-438e-aaca-d6c2d9c71d3c.png">

<img width="213" alt="image" src="https://user-images.githubusercontent.com/73173/188770133-fad3361d-eec2-4666-8337-acd77fe39fb2.png">

**Comment by FullBleed** [comment]
Looks a lot better... if a bit subtle.

Any chance the "selected" window could bold the name of the window?

**Comment by cwisniew** [comment]
> Looks a lot better... if a bit subtle.
> 
> Any chance the "selected" window could bold the name of the window?

Sadly the look and feel settings for the dockable frames use the same font for selected and non-selected. So they can both be bold or non bolded but no mixture.

**Comment by FullBleed** [comment]
> Sadly the look and feel settings for the dockable frames use the same font for selected and non-selected. So they can both be bold or non bolded but no mixture.

Too bad.  Well, my vote would be to bold the font for both then.  That should still create a bit more pop and contrast with the slightly different color fonts between selected/non-selected windows and the in-window text.

**Comment by Phergus** [comment]
@Irarara how does this fix look for you?

**Comment by Irarara** [comment]
Looks excellent over here, this addresses everything and some. 👍
