### ISSUE TITLE
[Bug]: Visual artifacts when dragging dockable windows over map

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#3583]
### Describe the Bug

When moving dockable windows around over the map the area under the path of the dragged element is not getting repainted, resulting in a black trail (as well as sometimes entire chunks just getting drawn black?).

This behavior seems to have come with #3580.

### To Reproduce

Drag a window around over the map.

### Expected Behaviour

There should be no visual artifacts when moving windows.

### Screenshots

![](https://i.imgur.com/Ls7K5nf.png)

### MapTool Info

develop branch

### Desktop

Windows 10

**Comment by Phergus** [comment]
@kwvanderlinde oopsie

**Comment by kwvanderlinde** [comment]
Interesting. Happens on Linux too ... if I move it using the title bar and not my usual technique of alt/win key + dragging the window. Will investigate this.

It's reminiscent of something else I've seen with overlays. When elements are hidden (e.g., menus), sometimes they leave black areas behind. Might be the same thing and I've just made it worse, or could be something entirely different :shrug:.

**Comment by kwvanderlinde** [comment]
Ah, I've accidentally used the clip bounds for the buffer image size but then always drew the result at (0, 0) rather than the clip bounds coordinates. I could fix this particular error in logic, but a better approach performance wise would be to size the buffer according to the component and apply the clip to the buffer as well. PR to come shortly.

**Comment by Phergus** [comment]
Got a PR inbound?

**Comment by kwvanderlinde** [comment]
Yep :smile:

**Comment by Phergus** [comment]
Now if I can just get Github to cooperate.

**Comment by Phergus** [comment]
Tested.  Artifacts are gone now.
