### ISSUE TITLE
[Feature]: Title bar for windows NOT active need more contrast to be legible

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#3588]
### Feature Request

The title bars for windows that are not active are hard to read.  Would like more contrast.

### The Solution you'd like

Title bars for windows that are not active should be easy to read.

### Alternatives that you've considered.

Activating windows for which I want to read the title bar.

### Additional Context

Below is an example of a window that is not active (on the left) for which the title bar is hard to read.  With a little more contrast, it would be fine.

![Screenshot 2022-09-03 200230](https://user-images.githubusercontent.com/50708405/188292738-73a0f343-38e2-481f-ae91-e5e9fa0aa347.JPG)

**Comment by adventuremagic123** [comment]
I was using the "Solarizesd Light Contrast (Material)" theme, I think.

**Comment by Phergus** [comment]
Tested.  Title bars have more contrast now.
![image](https://user-images.githubusercontent.com/34379254/189169184-05543bdb-dbd0-48f2-927b-7861829a6c54.png)

Waiting for more feedback from testers.

**Comment by Phergus** [comment]
@adventuremagic123 please confirm that this issue has been resolved with beta 3. Thanks.
