### ISSUE TITLE
[Bug]: Poor contrast for text in chat and other (non-WebView) HTML contexts with some themes

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#3589]
### Describe the Bug

Themes seem to set the default text color for Swing HTML documents, and with dark themes this results in difficult to read text when set against light backgrounds (such as with the chat panel or HTML frames, etc.).

### To Reproduce

1. Set a dark theme (Such as Arc Dark)
2. Enter a message in the chat and observe how the user name appears in a very light color
3.  Enter `[frame("test"),code: { test }]` in the chat and see how the text color in the frame is the same

### Expected Behaviour

The default text color should be black for these parts of the UI.

### MapTool Info

develop branch

### Desktop

Windows 10

**Comment by Phergus** [comment]
Tested.  Chat text and default text in dialogs/frames is now black in all themes.
