### ISSUE TITLE
Add info from getInfo() to Sentry logs

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#359]
The info from `getInfo("server")` and `getInfo("campaign")` can be useful in error reports and should be added.

Currently, some of the information is there (like basic memory info) but the campaign info includes other configuration settings that can be useful for diagnosing stack traces.

**Comment by xdy** [comment]
Calling getInfo("server") works, but not sure how to call getInfo("campaign") from MapToolEventQueue.reportToSentryIO so as to avoid permission problems.
Any suggestions?

**Comment by Phergus** [comment]
Code merged.  Will see if info shows up in the Sentry reports.
