### ISSUE TITLE
[Bug]: GM Macros disappearing on server start for 1.12 beta

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3603]
### Describe the Bug

When starting a server in 1.12 betas the GM macros disappear		

### To Reproduce

Empty Campaign, create new GM macro, start the server and watch the macro disappear.

### Expected Behaviour

The macro shouldn't dissapear 

### MapTool Info

1.12 Beta

### Desktop

All

**Comment by Phergus** [comment]
Tested.  GM panel macros persist across Server start now.

**Comment by Pmofmalasia** [comment]
Confirming that GM panel macros persist across server start in the 1.12.0 beta 3 release
