### ISSUE TITLE
[Bug]: checkDoors@Lib:SimpleDoors has exception in MapTool 1.12.0 Beta 3 but not MapTool 1.11.5

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#3611]
### Describe the Bug

As the GM, click a door to open it.  Instead of opening, you get an exception in the Chat window:

java.lang.NullPointerException: Cannot invoke "net.rptools.lib.MD5Key.toString()" because "md5key" is null error executing expression setTokenPortrait("").
Error trace : checkDoors@Lib:SimpleDoors <<< macroLink

### To Reproduce

melek#4527 (Discord) is the author of Lib:SimpleDoors.

1. Start MapTool 1.12.0 Beta 3.
2. Start the serve with the following options:

![Screenshot 2022-09-06 203150](https://user-images.githubusercontent.com/50708405/189466254-ae695114-88e7-4945-8ef7-fb21c92bcefb.JPG)

3. Open the test2a_1.11.5_version.cmpgn (you'll have to unzip test2a_1.11.5_version.cmpgn.zip):

[test2a_1.11.5_version.cmpgn.zip](https://github.com/RPTools/maptool/files/9539468/test2a_1.11.5_version.cmpgn.zip)

4. Click on a door to try to open or close it (I forget which but either way will probably do) and you'll get the following exception in the Chat window:

java.lang.NullPointerException: Cannot invoke "net.rptools.lib.MD5Key.toString()" because "md5key" is null error executing expression setTokenPortrait("").
Error trace : checkDoors@Lib:SimpleDoors <<< macroLink

5. The log does not appear to contain anything useful:

[maptool.log](https://github.com/RPTools/maptool/files/9539470/maptool.log)

6. If you retest this issue in MapTool 1.11.5, you'll have no problem.  Observe what happens to the VBL/MBL when you open and close doors.

### Expected Behaviour

There should be no errors and the VBL/MBL should disappear and reappear as appropriate when opening or closing a door.

### MapTool Info

1.12.0 Beta 3

### Desktop

Windows 10

**Comment by Phergus** [comment]
This is an issue with `setTokenPortrait()` and also `setTokenHandout()` as a result of the protobuf migration.
