### ISSUE TITLE
[Bug]: Theme problems take 3

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3613]
### Describe the Bug

The following theming issues still exist
1)  Editing “Min Width” on a macro button set to "default" font colour shrinks the button to a few pixels. 
2)  Preferences>Application>File Sync Directory isn't theming properly in Dark themes.
3)  Many combinations of font colour and min-width for macro buttons produce black text and no width change

### To Reproduce

1) Change min-width on a macro button with the default font colour and watch it shrink
2) Open the preferences dialog
3) Change a macro button font colour to white in the drop-down and enter 200 as the min-width, the button text will turn black

### Expected Behaviour

Min Width on macro buttons should not shrink the buttons or change the font colour. 
The Preferences>Application>File Sync Directory text box should be themed correctly.

### MapTool Info

1.12 Beta 2

### Desktop

All

**Comment by Phergus** [comment]
Tested.  Minimum width setting now works with default font color (and others).  All font colors working now.  File sync dir widget now uses theme colors.
