### ISSUE TITLE
[Bug]: Macro button font color ignored in MapTool 1.12.0 Beta 3

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#3619]
### Describe the Bug

The font color setting is ignored for macro buttons -- black is always used.

![Screenshot 2022-09-10 125641](https://user-images.githubusercontent.com/50708405/189495851-55dff7dd-6bf3-4089-87ce-c7fa4b66498c.JPG)

### To Reproduce

1. Edit macro button properties.
2. Change the font color and notice that it is always displayed as black.

### Expected Behaviour

The selected font color should be displayed.

### MapTool Info

MapTool 1.12.0 Beta 3

### Desktop

Windows 10

**Comment by Phergus** [comment]
This was the same as an issue reported in #3613.
