### ISSUE TITLE
[Bug][1.12 beta 3]: Errors on first attempt to start server

### ISSUE THREAD

**Issue by Pmofmalasia** [RPTools/maptool#3622]
### Describe the Bug

Starting with 1.12 beta 2, I have had errors preventing me from starting a server with my framework in particular. The first time I attempt to start a server with the campaign file open, I get a string of error boxes popping up that stop the server from running. Errors detailed in the 'Server Starting Errors Log 1' file attached.

The second time I attempt to open a server, it appears to go through smoothly (Log 2 file attached). This holds for a while, persisting through restarts of MapTool. Then eventually I start getting this error again and the cycle repeats.

[Starting Server Logs 1.log](https://github.com/RPTools/maptool/files/9543597/Starting.Server.Logs.1.log)
[Starting Server Logs 2.log](https://github.com/RPTools/maptool/files/9543596/Starting.Server.Logs.2.log)

### To Reproduce

Not sure how to replicate currently without posting the framework, which contains WotC copyrighted information. Will try to narrow down the source of the error and post a template campaign.

### Expected Behaviour

Server starting the first time without error.

### MapTool Info

1.12.0 beta 3

### Desktop

Windows 10

**Comment by Phergus** [comment]
Try a different port number.

**Comment by cwisniew** [comment]
@pmofmalasia   Is this on a new PC or did you clear out your asset cache?
This looks very similar to an a long existing problem where there is an image on a macro button but that image is not in the asset cache.

**Comment by Pmofmalasia** [comment]
This is the same PC, and I do not believe I cleared my cache - though I suppose it is possible that I double clicked on the cache icon on the status bar to clear it. That being said, I do have a single token with image macros, which is not present in the test campaign.

I tried using a different port number, I have not gotten this error with a new port number yet but given the inconsistent nature of the error it may require more attempts.

**Comment by Phergus** [comment]
You have two errors in your logs.  The missing or bad asset comes first and then you get the failure to open the socket.

For some reason Windows has started randomly using port 51234 for some service or another but it is pretty infrequent.  Retrying or just changing the port will normally get around the issue.

You might check your `assetcache` folder for asset `5e8ac451c191bb6d87c8e48c8c7d9047`.  It may just be corrupted.  Also check in `imageThumbs` and `previewPanelThumbs` if you don't find it in the cache.

**Comment by Pmofmalasia** [comment]
Changing the port seems to have fixed the issue - unsure what Windows is using 51234 for but I haven't had an issue when using a different port number. 

For the asset, it doesn't appear to be in any of those locations (or the campaign file, for that matter) so I'm at a loss as to where this asset is coming from - but it doesn't appear to be an issue with MT itself because I don't get it with a blank campaign.

This issue can probably be closed with any further troubleshooting done on discord, if you would prefer.

**Comment by Phergus** [comment]
Sounds good.  Closing.
