### ISSUE TITLE
[Bug]: Context menu "Move" does not work for Map Explorer selection

### ISSUE THREAD

**Issue by henczati** [RPTools/maptool#3624]
### Describe the Bug

Changing e.g. the facing of multiple tokens by context menu on picked (selected) tokens from the Map Explorer works, but moving only moves whatever was already selected on the map (if anything) and ignoring those selected in the Map explorer.

When I chose the "Move" action from the context menu in the Map Explorer when tokens are selected there, the Move actions is instead applied to the selection which was made by dragging the mouse on the map.  So if there were previous tokens selected, those are moved, if there was no selection beforehand, nothing is moved.

This bug was already present in MT 1.11.5.

### To Reproduce

A) Nothing is moved:
1. Have some tokens on the map on any layer and have nothing selected.
2. Select one or multiple tokens in the Map Explorer listing.
3. Open context menu on the Map Explorer selection and choose "Move".
4. Move mouse and observe that nothing is moved.

B) Previous selection is moved:
1. Have some tokens on the map on any layer and have some of it selected.
2. Select one or multiple **different** tokens in the Map Explorer listing.
3. Open context menu on the Map Explorer selection and choose "Move".
4. Move mouse and observe that the original (on-map) selection is moved.

### Expected Behaviour

When I select something in the Map Explorer and choose an action from the context menu of that selection, I expect it to be performed on said selection.  Just as when I choose the "Set Facing" action under the same circumstances, which seems to work correctly.

Actually, I cannot decide whether having the Map Explorer selection and the map selection decoupled is a bug or a feature in the first place...

### MapTool Info

Version: 1.12.0b3, 1.11.5  (both installed from .deb, purge-uninstalling the other version first and manually switching (renaming) config dirs, so each used its own)

### Desktop

OS: Linux [LUbuntu 18.04]

**Comment by Kasbr305** [comment]
> ### وصف الخطأ
> يعمل تغيير ، على سبيل المثال ، مواجهة الرموز المتعددة من خلال قائمة السياق على الرموز المميزة المنتقاة (المحددة) من مستكشف الخرائط ، ولكن نقل كل ما تم تحديده بالفعل على الخريطة (إذا كان هناك أي شيء) وتجاهل تلك المحددة في مستكشف الخريطة.
> 
> عندما اخترت إجراء "النقل" من قائمة السياق في Map Explorer عند تحديد الرموز المميزة هناك ، يتم تطبيق إجراءات النقل بدلاً من ذلك على التحديد الذي تم إجراؤه عن طريق سحب الماوس على الخريطة. لذلك إذا كانت هناك رموز مميزة سابقة محددة ، فسيتم نقلها ، وإذا لم يكن هناك تحديد مسبقًا ، فلن يتم نقل أي شيء.
> 
> كان هذا الخطأ موجودًا بالفعل في MT 1.11.5.
> 
> ### لإعادة إنتاج
> أ) لا شيء يتحرك:
> 
> 1. اجعل بعض الرموز المميزة على الخريطة في أي طبقة ولم يتم تحديد أي شيء.
> 2. حدد رمزًا مميزًا واحدًا أو أكثر في قائمة Map Explorer.
> 3. افتح قائمة السياق في تحديد Map Explorer واختر "نقل".
> 4. حرك الماوس ولاحظ أنه لا شيء يتحرك.
> 
> ب) تم نقل التحديد السابق:
> 
> 1. اجعل بعض الرموز المميزة على الخريطة في أي طبقة وحدد بعضها.
> 2. حدد رمزًا مميزًا واحدًا أو عدة رموز **مختلفة في قائمة Map Explorer.**
> 3. افتح قائمة السياق في تحديد Map Explorer واختر "نقل".
> 4. حرك الماوس ولاحظ أن التحديد الأصلي (على الخريطة) قد تم نقله.
> 
> ### سلوك متوقع
> عندما أحدد شيئًا ما في Map Explorer واختر إجراءً من قائمة السياق لهذا التحديد ، أتوقع أن يتم تنفيذه على التحديد المذكور. تمامًا كما هو الحال عندما أختار إجراء "Set Facing" في نفس الظروف ، والذي يبدو أنه يعمل بشكل صحيح.
> 
> في الواقع ، لا يمكنني تحديد ما إذا كان اختيار Map Explorer وفصل تحديد الخريطة هو خطأ أو ميزة في المقام الأول ...
> 
> ### لقطات
> _لا يوجد رد_
> 
> ### معلومات MapTool
> الإصدار: 1.12.0b3، 1.11.5
> 
> ### سطح المكتب
> نظام التشغيل: Linux [LUbuntu 18.04]
> 
> ### سياق إضافي
> _لا يوجد رد_

**Comment by Phergus** [comment]
Tested.  Context menu Move option from Map Explorer now moves the tokens selected in Map Explorer.
