### ISSUE TITLE
[Bug]: Lock Player Movement and Lock Player Token Editor tooltips missing in Start Server dialog

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#3631]
### Describe the Bug

When starting a new server, the 'Lock Player Token Editor' and 'Lock Player Movement' options don't have valid tooltips, showing the values `action.toggleTokenEditorLock.tooltip` and `action.toggleTokenMovementLock.tooltip` respectively.

In the Tools menu, both of these options show their tooltip correctly.

### To Reproduce

- Open the 'Start Server' dialog.
- Mouse over the 'Lock Player ...' options. 
- Observe missing tooltip values / placeholder values.

### Expected Behaviour

The tooltips should match the ones in the 'Tools' menu. 

### Screenshots

![image](https://user-images.githubusercontent.com/220149/190866673-c6f079a2-9883-49ac-85d0-23a49629b2ab.png)
![image](https://user-images.githubusercontent.com/220149/190866689-9988977e-020c-4ffa-8353-1997fce98303.png)

### MapTool Info

I tested in 1.11.4 and 1.12b3

### Desktop

Windows 10

**Comment by Phergus** [comment]
Tested.  Appears to be working as expected.
