### ISSUE TITLE
Error loading a campaign file that does load in v1.4.5.4.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3646]
Similar error loading a campaign file that does load in v1.4.5.4.

![image](https://user-images.githubusercontent.com/16145329/191137208-54d8af35-d1f9-4095-b5bd-93df3e5e63d6.png)

Campaign File (272MB): https://www.dropbox.com/s/cpbw260aotk70ym/PoA%20for%20MT.zip?dl=1

Windows 10

_Originally posted by @hmarcbower in https://github.com/RPTools/maptool/issues/3645#issuecomment-1251680825_

**Comment by Phergus** [comment]
Tested with 1.4.0.5 campaign that errors on loading in 1.12.0.  No longer produces NPEs when loaded.
