### ISSUE TITLE
[Bug]: Performance regression for token rendering on 1.12.0

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3652]
### Describe the Bug

On 1.12.0, tokens that take up a significant portion of the viewport (e.g., maps as background stamps) cause map rendering to be quite choppy.

### To Reproduce

1. Open the performance logs (_Tools_ > _Collect Performance Data_)
2. Open a new campaign.
3. From the default resource library, drag the "Denoleran Enclave" map onto the **Background** layer.
4. In the performance logs, observe high `tokenlist-7` times.

### Expected Behaviour

Background stamps and other tokens should be able to take up the whole screen while still rendering smoothly.

### MapTool Info

1.12.0

### Desktop

Linux Mint 21

### Additional Context

I am seeing >70 ms for `tokenlist-7` with only the one background token on the map. Although my example uses the background layer, the issue equally affects tokens on other layers as well. The numbers I've provided were with **Image Scaling Quality** set to **Low (Fastest)**.

This performance regression appears to be caused by the new image quality change (#1971). If I just comment out the new cubic interpolation in `renderTokens()`, then `tokenlist-7` reduces to ~1 ms (won't even register in the vanilla performance logs).

<details>
<summary>
Debug information
</summary>
<pre>
==== MapTool Information ====
MapTool Version: 1.12.0
MapTool Home...: /home/kenneth/.maptool-rptools
MapTool Install: /opt/maptool/lib/app
Max mem avail..: 5 GB
Max mem used...: 476 MB
Custom Property: -DMAPTOOL_LOGDIR=/home/kenneth/.maptool-rptools/logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: /opt/maptool/lib/runtime
Java Vendor....: Eclipse Adoptium
Java Version...: 17.0.1
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  --add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
  -Djpackage.app-path=/opt/maptool/bin/MapTool

==== OS Information ====
OS Name........: Linux
OS Version.....: 5.15.0-47-generic
OS Architecture: amd64
PATH...........: /home/kenneth/.local/bin:/home/kenneth/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kenneth/.local/share/JetBrains/Toolbox/scripts
Number of Procs: 6

==== User Information ====
User Name: kenneth
User Home: /home/kenneth
User Dir.: /home/kenneth

==== Network Interfaces ====
Display Name..: ztzlgjggbh
Interface Name: ztzlgjggbh
Address...: fe80:0:0:0:44f6:e7ff:fecd:96b%ztzlgjggbh
Address...: 10.144.224.214

Display Name..: zthnhauxdb
Interface Name: zthnhauxdb
Address...: fe80:0:0:0:547f:6fff:fe98:c47a%zthnhauxdb
Address...: 10.147.18.47

Display Name..: zt44xpuk3a
Interface Name: zt44xpuk3a
Address...: fe80:0:0:0:cd4:7eff:fec1:189b%zt44xpuk3a
Address...: 10.147.17.47

Display Name..: wlp4s0
Interface Name: wlp4s0
Address...: 2001:569:5585:1900:9f80:165c:409d:3050%wlp4s0
Address...: fe80:0:0:0:ce3c:aef8:5ac:aca6%wlp4s0
Address...: 2001:569:5585:1900:14dd:248a:b63b:fabc%wlp4s0
Address...: 192.168.1.74

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.1.254

==== Locale Information ====
Country.: Canada
Language: English
Locale..: English (Canada)
Variant.: 

==== Encoding Information ====
Default Locale:   en_CA
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 5120x1440(-1)
Display 2: 2560x1440(-1)

==== Internet Gateway Devices ====
Device Name.: Actiontec xDSL Router
Model Name..: T3200M
Manufacturer: Actiontec
Model Number: 1.0
Model Desc..: (null)
Firmware....: Custom/1.0 UPnP/1.0 Proc/Ver
External IP.: 162.156.118.146
</pre>
</details>

**Comment by cwisniew** [comment]
I will create a fix for this for 1.12.1 as it looks like other scaling things may also need tweaking

**Comment by Phergus** [comment]
Tested.  Using test case described above, with scaling quality set to high:
![image](https://user-images.githubusercontent.com/34379254/192107940-41eb0565-49b3-4e25-9fe7-c6845850e709.png)

With quality set to low (fastest):
![image](https://user-images.githubusercontent.com/34379254/192107962-3b56c61a-8c79-49d0-b8df-f0caec96a991.png)
