### ISSUE TITLE
[Bug]: state and !state not working

### ISSUE THREAD

**Issue by AaronCSchmitz** [RPTools/maptool#3655]
### Describe the Bug

**I see now this has already been reported. My bad.**

Don't see anything in the changelog about this, but states seem to be bugged:
For example, `[state.Prone]` will **always** return 0, and `[!state.Prone]` will **always** return 1, regardless of whether the token does/doesn't have the state. By extension things like `[state.Prone=!state.Prone]` will always set to the state to active.

### To Reproduce

1) Impersonate a Token
2) Type `[state.Prone]` and/or `[!state.Prone]`

### Expected Behaviour

`[state.Prone]` should return 1 _or_ 0 depending on if the token has the state active or not, and `[!state.Prone]` should return the opposite

### Screenshots

![screenie](https://user-images.githubusercontent.com/22008070/191616118-851bce2f-40f8-4d6a-bf9d-b0d4418729c3.png)

![screenie 2](https://user-images.githubusercontent.com/22008070/191616323-65c66561-dc6f-4f43-85e1-1a46ec09e074.png)

### MapTool Info

Version 1.12.0

### Desktop

Windows 10

**Comment by AaronCSchmitz** [comment]
**I see now this has already been reported. My bad.**

**Comment by FullBleed** [comment]
> **I see now this has already been reported. My bad.**

You can close your own report.
