### ISSUE TITLE
[Bug]: Default scaling quality should be set to low due to performance issues some are having.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3660]
### Describe the Bug

Some people experience performance issues when the scaling factor is not set to low. Also, people running pixel-art games are asking why their maps are suddenly blurry as pixel-art does not scale well.

### To Reproduce

The performance issues are hard to reproduce, primarily as some are unrelated to the scaling.
The pixel art scaling issues are easier to see, though you can create a map with pixel art images and see the blurring.

### Expected Behaviour

Setting default scaling to low means that the default will be the rendering quality and speed of 1.11 (other non-scaling-related performance issues aside).

### Screenshots

![image](https://user-images.githubusercontent.com/73173/192063485-8335312e-5cff-40ce-af94-62d37b273b11.png)

### MapTool Info

1.12.0 and 1.12.1 Beta 1

### Desktop

All

### Additional Context

We really need a good way to point out new features to users...

**Comment by Phergus** [comment]
Tested.  Default scaling quality setting is Low (Fastest).
![image](https://user-images.githubusercontent.com/34379254/192108616-12bcdeed-e01b-418c-bea6-4e11299214cd.png)
