### ISSUE TITLE
[Bug]: The Edit Token Dialog is too large for lower resolution screens.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3662]
### Describe the Bug

When trying to display the edit token dialog it is too large for screens with a low vertical resolution and the buttons at the bottom are cut off.

### To Reproduce

Open up the dialog box on a netbook with a low vertical resolution.

### Expected Behaviour

The dialog box should be altered so that it is not as tall.

### MapTool Info

All versions but is worse in 1.12 due to new themes

### Desktop

All

**Comment by Phergus** [comment]
Tested.  With new layout the height of the dialog can be reduced to about 800 pixels before the Okay/Cancel buttons start becoming hidden which should be good enough for the majority of displays.
Topology tab takes up the most space still.
![image](https://user-images.githubusercontent.com/34379254/192108431-6c897441-0af7-4af8-8f1d-8f2a362a90f4.png)
![image](https://user-images.githubusercontent.com/34379254/192108486-612d8c08-53fc-47ca-9b9e-24f07256bfbc.png)
