### ISSUE TITLE
[Bug]: FoW outline is rendered when vision is Off on 1.12.x, even though FoW is not rendered.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3688]
### Describe the Bug

When FoW is enabled on a map, and the vision is set to Day or Night, then soft FoW is rendered with an opaque black border. This border is also rendered when vision is set to Off, even though in that case the transparent part of soft FoW is not rendered.

### To Reproduce

1. Open this campaign file: [do-vision-lines-render-without-hovering.cmpgn.renamedto.zip](https://github.com/RPTools/maptool/files/9677079/do-vision-lines-render-without-hovering.cmpgn.renamedto.zip)
2. On the only map there, make sure the vision is set to "Off". Without hovering over any tokens, see the the black FoW outline being rendered and things look bad.
3. Change the vision to "Day" and see that Soft FoW is now rendered things look right.

### Expected Behaviour

Soft FoW should not render at all when vision is set to Off.

### Screenshots

1.11.5:
![image](https://user-images.githubusercontent.com/7492219/193090866-23976f7e-cebe-47fe-9c98-ed3260ff8ed3.png)

1.12.1:
![image](https://user-images.githubusercontent.com/7492219/193091049-fb94d326-7957-43f4-bb80-bfadeed8b96e.png)

### MapTool Info

1.12.0, 1.12.1

### Desktop

Linux Mint 21

**Comment by Phergus** [comment]
Tested.  Soft FoW is no longer rendered on maps with Vision set to off.
