### ISSUE TITLE
[Bug]: Soft FoW opacity is ignored when no sight is present.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3689]
### Describe the Bug

The opacity of Soft FoW depends on whether any sighted area is present on the map. If there is any sight, the opacity from preferences is used, but if there is no sight than another opacity is used.

### To Reproduce

1. Open preference, and set FoW opacity to a high value like 240 (this just makes the difference obvious).
2. Start a new campaign.
3. Set the map vision to Day and enable FoW.
4. Add a PC token with Normal sight. Right click and **Expose** > **Visible Area** to expose some FoW.
5. Draw a small area of Wall VBL next to the token. Observe that the area of VBL and beyond is encased in Soft FoW.
6. Edit the PC token and remove sight from it. Observe that the whole map is now encased in Soft FoW, but the opacity is much less.

### Expected Behaviour

The opacity of Soft FoW is respected in all cases.

### Screenshots

This is when the PC token has vision (with my very opaque Soft FoW):
![image](https://user-images.githubusercontent.com/7492219/193127747-2f640a86-97b7-402f-adbf-a0477876b0bb.png)

This is when the PC vision is removed:
![image](https://user-images.githubusercontent.com/7492219/193127912-a2f295f3-c931-466f-9731-2013eca6e1ae.png)

### MapTool Info

1.11.5

### Desktop

Linux Mint 21

### Additional Context

I tried this on 1.11.5, but it equally effects 1.12.x and many earlier versions of MapTool as well.

I also tried this as a GM on a personal server, as well as with a player connected. The same basic behaviour applies in all cases on all clients.

**Comment by Phergus** [comment]
Tested.  Soft fog opacity setting is now used even when no tokens with sight are present.
