### ISSUE TITLE
[Bug]: Line cell template is cut off at certain zoom levels

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#3692]
### Describe the Bug

The line cell template (5th template tool from the left) fails to render properly at certain zoom levels, leaving part of the template cut off.

### To Reproduce

1. Draw a line using the tool
2. Zoom in and out and observe parts of the template will be cut off

### Expected Behaviour

The entire template should be displayed.

### Screenshots

![java_2022-09-30_01-25-24](https://user-images.githubusercontent.com/59770924/193197262-4c302beb-9f1c-41fe-a4e0-2a87f6fe6b1f.png)
![java_2022-09-30_01-25-29](https://user-images.githubusercontent.com/59770924/193197274-e0cbd99b-cac0-4e36-8ca9-d4b95c9ad548.png)

### MapTool Info

develop branch (and earlier)

### Desktop

Windows 10

### Additional Context

I _suspect_ the issue is the [bounds](https://github.com/RPTools/maptool/blob/55df8810f4946dd0aa125296538bdc69dabd8f5d/src/main/java/net/rptools/maptool/model/drawing/LineCellTemplate.java#L388 ) are being calculated incorrectly, but it's been awhile since I looked at any of this stuff.

Also, thanks to Ao for bringing it up on discord, cause I forgot about this one. 😅

**Comment by Baaaaaz** [comment]
Tested in 1.16.0.rc-2 and looks fixed to me.  Thanks!
