### ISSUE TITLE
[Bug]: Templates disappear after renderer update after a period of time has passed

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#3693]
### Describe the Bug

If you draw a template, wait for a period time, and then trigger a renderer update in some way (zoom in or out, draw something new, etc.), the template will disappear from the map. It will still be listed in the draw explorer, but it won't render in the drawing viewer there either. There's also nothing illuminating in the log when this occurs.

### To Reproduce

1. Draw a template
2. Wait 3 minutes or so without causing a renderer update
3. Draw another template and watch the other one disappear

### Expected Behaviour

Templates should remain visible.

### Screenshots

Before: 
![MapTool_2022-09-30_02-43-19](https://user-images.githubusercontent.com/59770924/193207503-31b7dd0f-58d4-4379-9ec5-d70dc770aa6e.png)
After:
![MapTool_2022-09-30_02-44-32](https://user-images.githubusercontent.com/59770924/193207523-9e7acfc6-871f-4ac5-92b1-45f4c127a9dc.png)

### MapTool Info

develop branch, but also present in 1.11.5

### Desktop

Windows 10

**Comment by kwvanderlinde** [comment]
Given the time scale it sounds like something related to auto-save.

I tried to reproduce this on my currently installed version (1.13.2) but did not have success. @Irarara Are you able to confirm whether this issue is still valid?

**Comment by Irarara** [comment]
@kwvanderlinde Sorry for the late response, missed this! Just tested with 1.14.3 and I am no longer able to reproduce it either. Seems fixed.

**Comment by kwvanderlinde** [comment]
Hey, I'm in no rush :smile: Thanks for confirming this!
