### ISSUE TITLE
[Request] Code completion documentation for UDF

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#370]
I realize that this will not make it into MT before 2.0, at the earliest, if at all. But it would be awesome, if there was a way to document an UDF, so that code completion in the macro editor would show hints and arguments etc. 
Not unlike JavaDoc, or  /// in C#.

**Comment by JamzTheMan** [comment]
Ya, I would love to have that as well.  The editor is hot right now so who knows?

Maybe at least a way to let you define the HTML docs/help file for it.  We use a .properties file to pull in the docs for the regular functions, perhaps we could pick up a user .properties file in the .maptool dir. Would be a quick "fix" although I'd prefer it to be defined in MapTool somehow and go with the campaign file...

Maybe a phase 1/phase 2 approach...

**Comment by Azhrei** [comment]
Ideas for how to do it?  The "/" commands only work in a macro when they're on the first line.  Maybe some kind of `/doc "..."` that the macro processor picks up and embeds in the metadata?  But then the macro would have to be executed for this to show up.  An alternative would be to enter the docs into a separate field in the macro editor (likely a separate tab), but that's terrible because it would require switching tabs.  And we would want @aliasmask's RPedit plug-in to work seamlessly with the new approach...

**Comment by JamzTheMan** [comment]
Or we add a json parm to defineFunction and you pass the encoded html as a parm when you define your UDF.

Another option, something like css macros? You have a macro with the same name + ".html"? (or .doc? or ?) and we just pick up whatever text is in that macro? (strip other macro code?)

so you have a function that calls macro named "importFromStatBlock" you would document it in "importFromStatBlock.html"?

Just spitballing

Last option: We simply add a "docs" field on all macros. This is another tab. It accepts HTML (in FX there's even a nice HTML wysiwyg editor) and you can put any text you want in there, handy for actually documenting other random notes about the macro you wrote at 2am last year. IF you define this function in a UDF then it'll pick up and display the doc/notes from here.

I sort of like the last option as I typed it.  May be handy to have a "notes" section for all my macros I write...

**Comment by aliasmask** [comment]
Keep it simple and just show the macro button tip the UDF is calling. I don't think many people will take the time what a macro/udf takes for input and note its output. RPEdit can easily update the tooltip with the @PROPS@ line.

**Comment by JamzTheMan** [comment]
I like that idea for now, simple and exists already!

Combine with the other request to show tooltip input as multiline textarea...

**Comment by Phergus** [comment]
This was added as part of #355 in MapTool 1.5.2.
