### ISSUE TITLE
[Bug]: seHalo("None") not wokring

### ISSUE THREAD

**Issue by StefanoMarina** [RPTools/maptool#3719]
### Describe the Bug

As of 1.12.1, calling `setHalo("None")` on a token returns a NullPointerException:

``
Java.lang.NullPointerException: Cannot invoke "java.awt.Color.getRGB()" because "haloColor"  is null
``

### To Reproduce

1. Impersonate a token
2. write `{setHalo("None")}`

### Expected Behaviour

Should clear the Halo

### MapTool Info

1.12.1

### Desktop

Linux [Linux Mint 19]

### Additional Context

==== MapTool Information ====
MapTool Version: 1.12.1
MapTool Home...: /home/ste/.maptool-rptools
MapTool Install: /opt/maptool/lib/app
Max mem avail..: 1 GB
Max mem used...: 450 MB
Custom Property: -DMAPTOOL_LOGDIR=/home/ste/.maptool-rptools/logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: /opt/maptool/lib/runtime
Java Vendor....: Eclipse Adoptium
Java Version...: 17.0.1
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  --add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
  -Djpackage.app-path=/opt/maptool/bin/MapTool

==== OS Information ====
OS Name........: Linux
OS Version.....: 4.15.0-167-generic
OS Architecture: amd64
PATH...........: /home/ste/.local/bin:/home/ste/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Number of Procs: 4

==== User Information ====
User Name: ste
User Home: /home/ste
User Dir.: /home/ste

==== Network Interfaces ====
Display Name..: wlp3s0
Interface Name: wlp3s0
Address...: fe80:0:0:0:6352:69d9:bdef:7503%wlp3s0
Address...: 192.168.0.102

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.0.1

==== Locale Information ====
Country.: Italy
Language: Italian
Locale..: Italian (Italy)
Variant.: 

==== Encoding Information ====
Default Locale:   it_IT
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 1366x768(-1)
Display 2: 1366x768(-1)

==== Internet Gateway Devices ====
Device Name.: TD-W8970
Model Name..: TD-W8970
Manufacturer: TP-LINK
Model Number: 3.0
Model Desc..: 300Mbps Wireless N Gigabit ADSL2+ Modem Router
Firmware....: Linux/2.6.30, UPnP/1.0, Portable SDK for UPnP devices/1.6.19
External IP.: 192.168.1.2

**Comment by Phergus** [comment]
@thelsing this is another case where a null is being passed to the token update functions to indicate that the halo (in this case) should be turned off.

**Comment by Phergus** [comment]
Tested.  `setHalo("None")` no longer throws NPE and clears halo.
