### ISSUE TITLE
[Feature]: Move the checkbox to use themes for  the chat box to the top of the window

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3723]
### Feature Request

A lot of people on discord are asking if it is possible for the chat box to use the theme colors instead of the white background. This obviously means that the location of the check box to do this is not obvious and needs to be moved to a place where is easier for the user to find.  

### The Solution you'd like

Move the check box that determines if the chat window should use the color scheme from the theme or not to the top of the window where it will be a lot more evident. 

### Alternatives that you've considered.

Creating a discord bot to answer the question, but that is probably not a great user experience

**Comment by Phergus** [comment]
Tested.  Checkbox for chat window color now at top next to theme name.
