### ISSUE TITLE
[Bug]: MapTool window sometimes starts as fullscreen despite having the non-fullscreen UI.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3739]
### Describe the Bug

Sometimes when starting MapTool the window is in fullscreen (no titlebar, unable to resize or move, and can't get at my taskbar). But the UI looks like it should when not in fullscreen mode (standard toolbar, all panels visible, etc.)

When in this state, I can switch to fullscreen (**View > Fullscreen mode**). This makes the UI look as expected in fullscreen (no panels, fullscreen toolbar), but the window itself becomes non-fullscreen and I can move and resize the window (but it doesn't have a titlebar). Leaving fullscreen puts the UI back into the windowed mode, but the window itself goes back to fullscreen.

If this happens once, it consistently happens on every start afterwards.

### To Reproduce

I don't know what actually causes this as it seems really random when it shows up. As far as I'm aware, I'm not doing anything special that causes it to happen.

To see the same symptoms, these steps can be used:
1. Start MapTool inside of Cinnamon.
2. Run this command: `wmctrl -r ':ACTIVE:' -b toggle,fullscreen`
3. Close MapTool
4. Open MapTool and it should still be in the fullscreen state.

### Expected Behaviour

MapTool should always open in windowed mode and should only end up in fullscreen mode when requested.

### Screenshots

Here is the initial state of the window. Note the panels, etc., of windowed mode, but no toolbar
![image](https://user-images.githubusercontent.com/7492219/201610166-5be3f340-2670-45a6-92e9-63beffb9e19a.png)

And here is what "fullscreen mode" looks like:
![image](https://user-images.githubusercontent.com/7492219/201610324-98c1c3bd-1a2d-49ec-9c8b-238c4e767f36.png)

And I can now resize the window:
![image](https://user-images.githubusercontent.com/7492219/201610514-2af2e04b-1af0-4aa2-a8f2-ce246904ed94.png)

### MapTool Info

1.12.2

### Desktop

Linux Mint 21 Cinnamon 

### Additional Context

I haven't seen this on any version of MapTool until very recently, so it feels like a change to my system and not an issue with MapTool. But I also don't see this happen to any other application, so maybe there's something unusual about our window set up in particular that could explain this?

I've only seen the issue start on 1.12.2, but I also don't use any other version frequently enough to see the problem show up. What I do know is that once the problem happens, it will at least affect new 1.11.5 windows as well.

Debug info:
<details>
<pre>
==== MapTool Information ====
MapTool Version: 1.12.2
MapTool Home...: /home/kenneth/.maptool-rptools
MapTool Install: /opt/maptool/lib/app
Max mem avail..: 5 GB
Max mem used...: 180 MB
Custom Property: -DMAPTOOL_LOGDIR=/home/kenneth/.maptool-rptools/logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: /opt/maptool/lib/runtime
Java Vendor....: Eclipse Adoptium
Java Version...: 17.0.1
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  --add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
  -Djpackage.app-path=/opt/maptool/bin/MapTool

==== OS Information ====
OS Name........: Linux
OS Version.....: 5.15.0-52-generic
OS Architecture: amd64
PATH...........: /home/kenneth/.local/bin:/home/kenneth/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kenneth/.local/share/JetBrains/Toolbox/scripts
Number of Procs: 6

==== User Information ====
User Name: kenneth
User Home: /home/kenneth
User Dir.: /home/kenneth

==== Network Interfaces ====
Display Name..: ztzlgjggbh
Interface Name: ztzlgjggbh
Address...: fe80:0:0:0:44f6:e7ff:fecd:96b%ztzlgjggbh
Address...: 10.144.224.214

Display Name..: zthnhauxdb
Interface Name: zthnhauxdb
Address...: fe80:0:0:0:547f:6fff:fe98:c47a%zthnhauxdb
Address...: 10.147.18.47

Display Name..: zt44xpuk3a
Interface Name: zt44xpuk3a
Address...: fe80:0:0:0:cd4:7eff:fec1:189b%zt44xpuk3a
Address...: 10.147.17.47

Display Name..: wlp4s0
Interface Name: wlp4s0
Address...: 2001:569:5585:1900:9f80:165c:409d:3050%wlp4s0
Address...: 2001:569:5585:1900:994a:7c2b:8864:3317%wlp4s0
Address...: fe80:0:0:0:ce3c:aef8:5ac:aca6%wlp4s0
Address...: 192.168.1.74

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.1.254

==== Locale Information ====
Country.: Canada
Language: English
Locale..: English (Canada)
Variant.: 

==== Encoding Information ====
Default Locale:   en_CA
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 3840x1080(-1)
Display 2: 1920x1080(-1)

==== Internet Gateway Devices ====
Device Name.: Actiontec xDSL Router
Model Name..: T3200M
Manufacturer: Actiontec
Model Number: 1.0
Model Desc..: (null)
Firmware....: Custom/1.0 UPnP/1.0 Proc/Ver
External IP.: 162.156.118.146
</pre>
</details>

**Comment by Azhrei** [comment]
> I haven't seen this on any version of MapTool until very recently, so it feels like a change to my system and not an issue with MapTool.

Agreed, particularly since modifying the window manager settings can reliably trigger it.  It’s probably some interaction between Cinnamon and Java.  There’s likely some setting (controllable by an XM_* env var) that needs to be set in order to force Cinnamon to do The Right Thing.

**Comment by kwvanderlinde** [comment]
In an attempt to see what was happening, I first tried to subvert the `MapToolFrame` initialization and instead create an empty test frame. Using this approach, I was _not_ able to reproduce the same behaviour. So this tells me there is something particular we are doing that is causing my system to exhibit this behaviour (not saying MapTool is to blame, just that there's something there).

So I had to find out what was different between `MapToolFrame` and my test frame. I took a scalpal to the project, removing chunks until `MapToolFrame` had barely anything left in it. What I found along the way was two culprits that cause new windows to end up full screen.

The first is the restoration of `DockingManager`. We save the window layout which apparently includes whatever state is necessary to cause this issue. So if we ever end up in this weird fullscreen state, the docking manager will restore that problematic state on each future start. For reference, it's this line in `MapToolFrame` that effects the state restore: `getDockingManager().loadLayoutDataFromFile(AppUtil.getAppHome("config").getAbsolutePath() + "/layout.dat");`.

But I also got rid of the docking manager in the end and found I could still reproduce the issue. Turns out, our `WindowPreferences.restorePreferences()` does a similar thing by storing window properties in user preferences. But better than the docking manager, I could more easily debug what was happening. So here it is: if the restored position is (0, 0), the restored width is the width of my screen (1920 in my case), and the restored height is the height of my screen _plus the height of the title bar_ (1080+28=1108 in my case), and also the stored `"maximized"` value is `false`, then the issue occurs. If `"maximized"` is `true`, the issue is fixed. For reference, when `"maximized"` is `true`, it is this line that executes and fixes the issue: `((JFrame) window).setExtendedState(Frame.MAXIMIZED_BOTH);`.

As far why I sometimes get these exact dimensions saved, I don't have a clue. It's probably got something to do with the fact that my auto-hiding taskbar happens to be exactly the same height as my title bar, and that somehow sometimes adds extra to a window for ... reasons.

Anyhow, I think this investigation just shows that MapTool is behaving reasonably and it's definitely Cinnamon or mutter or something else on my system that's to blame.

**Comment by Phergus** [comment]
Great sleuthing!

**Comment by irisiflimsi** [comment]
I have this problem on my two Ubuntus and consider Maptool at fault here, because it is in some kind of full screen mode, I can't get it to leave. Usually there are ALT-* (https://askubuntu.com/questions/18243/moving-windows-from-the-keyboard) options for windows that misbehave , but nothing works and even when I open the window manager menu, everything reasonable is greyed out. That leaves only closing and removing the "layout" files. It only happens every 10th start or so, so it is nothing pressing. But Maptool is the only application that ever shows this behavior.
I am using 1.13.2 mainly; other versions not often enough to notice (or remember) it. A good fix would be a (e.g.) "Shift-Esc" to get it out of that situation.

_Ed.:_ Actually, removing all the config files doesn't get me out of this. The only way I can get out is changing the screen resolution to high-res while it is maximized in low-res. That means:
1) stop MT
2) change res to low res
3) start MT
4) change res to high res
