### ISSUE TITLE
Last Save Location Isn't Remembered

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#375]
**Describe the bug**
The last saved path isn't retained when saving a token or a campaign. They seem to take on the last save path for an exported map. This was really irritating until I discovered the workaround.

The path is retained for maps, macros, and campaign prefs.

**To Reproduce**
1. On a new instance of MapTool, drop some tokens.
2. Save a token to a different directory than the default.
3. Save another token. Notice the save path didn't change from the last save.
4. Repeat for the campaign.
5. Export a map via Map->Export Map. Put it into another directory
6. Repeat saves for Token and Campaign. Notice they now default to the rpmap save dir

**Expected behavior**
The last save location for both campaigns and tokens should be the last save location for those file types.

**Screenshots**
None

**MapTool Info**
- Version: 1.5.1
- Install: Upgrade

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04.2

**Additional context**
==== MapTool Information ====
MapTool Version: 1.5.1-rc.3
MapTool Home...: /home/rkathey/.maptool-rptools
Max mem avail..: 4,096M
Max mem used...: 4,294,967,296M
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: /opt/MapTool/runtime
Java Version: 10.0.2
Result of executing 'java -version':
............: OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
............: OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

==== OS Information ====
OS Name........: Linux
OS Version.....: 4.15.0-46-generic
OS Architecture: amd64
PATH...........: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Number of Procs: 2

==== User Information ====
User Name: rkathey
User Home: /home/rkathey
User Dir.: /opt/MapTool/app

==== Network Interfaces ====
Display Name..: eth3
Interface Name: eth3
Address...: 2605:6000:101f:c233:0:8257:4ee0:4458%eth3
Address...: 2605:6000:101f:c233:8949:6d69:3400:8944%eth3
Address...: 2605:6000:101f:c233:290e:1bd8:dc3f:e673%eth3
Address...: 2605:6000:101f:c233:6c9b:34b8:67ad:bf5d%eth3
Address...: 2605:6000:101f:c233:dd19:4d51:d1df:c869%eth3
Address...: 2605:6000:101f:c233:ddaa:3fd0:959c:8750%eth3
Address...: fe80:0:0:0:73b9:c5b0:eab4:eb3a%eth3
Address...: 2605:6000:101f:c233:e017:75bc:6d22:8259%eth3
Address...: 2605:6000:101f:c233:39af:37ab:9a8a:828b%eth3
Address...: 2605:6000:101f:c233:515d:9506:92ae:41a9%eth3
Address...: 192.168.1.128

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.1.1

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(-1)

==== Internet Gateway Devices ====
	No IGDs Found!

**Comment by rkathey** [comment]
I disagree with the feature tag. This is a bug in my opinion.

**Comment by emmebi** [comment]
Assign this to me, I will work on this in the coming week.

**Comment by emmebi** [comment]
I am back working on this; I assume that Token and Campaigns are going to have separated save directories.

**Comment by emmebi** [comment]
Looking at the original code, it looks like the code tried to keep things in the same directory, but in some case it didn't. 

I will try to see if keeping this behavior is feasible.

**Comment by emmebi** [comment]
Reading the bug report, the report explicitly says that the last saved location should be distinguished for:
- tokens
- campaigns
- maps

So I will keep this behavior.

**Comment by Phergus** [comment]
Tested with develop.  Save dialog remembers last location per type when saving Tokens, Maps and Campaigns.
