### ISSUE TITLE
[Bug]: Pathfinding is enabled based on locally selected layer

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3754]
### Describe the Bug

When on a server with multiple clients, all clients perform pathfinding for moving tokens, even ones being dragged on other clients. But pathfinding is not done when the selected layer is anything other than tokens. That's fine locally, but it means that when another client is dragging a token on the Token layer, but a second client has, say, the Hidden layer selected, then the second client will not see pathfinding even though the token is on the Token layer and should pathfind.

### To Reproduce

1. Create a new map.
2. Add a bit of MBL to the map to serve as an obstacle.
3. Add a snap-to-grid PC token to the map owned by All Players.
4. Start a server
5. With the pointer tool active, change the layer to Hidden.
6. On a second MapTool instance, connect to the server as a player.
7. On the second instance, drag the token so it pathfinds around the MBL.
8. On the first instance, observe the token moving through the MBL.

### Expected Behaviour

Tokens should pathfind based on which layer they are on, or based on the selected layer of the client that is performing the move. The locally selected layer should not be used unless that client is the one performing the move.

### Screenshots

Player instance doing the move:
![image](https://user-images.githubusercontent.com/7492219/204127902-9d8af98d-f1a7-4359-8074-d7a52aa9f996.png)

What the GM instance on the Hidden layer sees:
![image](https://user-images.githubusercontent.com/7492219/204127967-1f406649-f70d-4e48-8e25-f88ea61b405a.png)

### MapTool Info

1.12.2

### Desktop

Linux Mint 21

**Comment by Pmofmalasia** [comment]
Fixed for me in 1.13.2:

![image](https://github.com/RPTools/maptool/assets/79408871/3a263cb7-cd47-417c-8c92-2d190bc46e57)
