### ISSUE TITLE
[Bug]: Player selection is cleared when someone else moves their token

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3759]
### Describe the Bug

If a player has a token selected locally, and then the GM remotely moves that token, the token is deselected for the player. The same is true if another player moves the token.

If a player has multiple tokens selected, any moved tokens will be deselected while the others remain selected.

### To Reproduce

1. Start a server for a campaign with a map that has tokens.
2. Have a player connect to the campaign and select a token.
3. As the GM, move the token.
4. Watch the player's selection be cleared.

### Expected Behaviour

Unless the token is deleted, players should keep their selection even if other people are moving or otherwise interacting with the token.

### MapTool Info

1.12.2

### Desktop

Linux Mint 21

**Comment by Pmofmalasia** [comment]
Appears to be fixed for me on 1.13.2.
