### ISSUE TITLE
[Bug]: Startup settings for changing language override is not changable

### ISSUE THREAD

**Issue by Cragsand** [RPTools/maptool#3771]
### Describe the Bug

I'm trying to change the default language from Swedish to English but the option in settings are grayed out.
Searching for more info on the topic this seems to be a bug fixed in other forks.
Cheers

### To Reproduce

1. Run windows version on language other than English
2. Go into Settings - > Startup
3. Language Override box is grayed out and can not be changed. It also says "English" when this is not the case.

### Expected Behaviour

The setting box for language should be selectable.

### Screenshots

![bild](https://user-images.githubusercontent.com/49168045/206861337-e3eaffaa-88e1-42bf-ad3f-9c67ff791c32.png)

### MapTool Info

MapTool v1.12.2

### Desktop

Windows

**Comment by Cragsand** [comment]
Workaround instructions to force change language for MapTools for the not so tech savvy:
![bild](https://user-images.githubusercontent.com/49168045/206861714-1e91a54d-9de7-4230-9566-90a619d8ec39.png)
1. Open the file **MapTool.cfg** in the folder **\MapTool\MapTool-1.12.2\app**
2. Make sure you use a plain text editor like Notepad.exe or Notepad++
3. Scroll down to the section named [JavaOptions]
4. Add the following line as such: `java-options=-Duser.language=en`
![bild](https://user-images.githubusercontent.com/49168045/206861809-2adfb439-0eee-4df1-a435-2c414683bce9.png)
5. Restart MapTools to update the language.

Hopefully this helps as I couldn't find any basic explanations when searching.

**Comment by Phergus** [comment]
Not a bug.  The interface is disabled as the current launcher keeps a lock on the config file while MT is running.

Instructions for accessing the config file are right there in the Prefs dialog you have in your screenshot.

![image](https://user-images.githubusercontent.com/34379254/207919821-c157f984-d932-4341-a759-ba51c26e76cf.png)
