### ISSUE TITLE
[Feature]: Consistent map IDs

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3781]
### Feature Request

I've made a library for organizing my maps and associating them with different parts of the campaign, e.g., where they fit in a larger atlas. As part of this, I need to be able to store references to maps that are reliable. This is easy if the maps have constant IDs similar to tokens, which I can almost get via the `"zones"` field of `getInfo("campaign")` and the `"id"` field from `getInfo("map")`. But that ID changes whenever a server is started, meaning I can't actually rely on it.

### The Solution you'd like

Maps would be assigned IDs in a way that is consistent over time and across clients. Starting or stopping a server would not result in different IDs, and each client would agree on a single ID to associate with a given map. Exporting and importing a map would not be expected to keep the same ID.

An added perk would be directly supporting map IDs in macro functions, so that map IDs can be retrieved without digging in `getInfo()`, and so that map IDs can be used in places where map names are currently expected.

### Alternatives that you've considered.

Instead of using IDs, I could use map names to refer to maps. The various functions expect map names, so it is necessary to some degree to rely on names anyways. But it's not uncommon for me to change either the display name or GM name for some maps, and that would create a dangling reference.

What I actually do right now is add a specially named token to each map. This token just stores a randomly generated ID in it (actually it can do more, but that's all I use it for now). This works, but it has a couple downsides:
1. The token can get in the way. It's not meant to be interacted with (by players or GM), but is just like any other token. An accidental deletion is all too easy to do and messes everything up.
2. I have to maintain the IDs. Assigning them isn't too bad, though it does have some overhead in terms of generating a random string in MTScript and making sure the special token is present when needed. But the biggest thing is when loading the IDs from the maps - it doesn't take many maps before that can get sluggish. It can be mitigated with some caching, but that also adds more complexity to it.

**Comment by cwisniew** [comment]
I have also added the bug label as this is a bug, the maps should have the same ID after starting the server.  This is likely to be an error in one of the copy constructors where it's not copying across the id where it should be.

**Comment by Phergus** [comment]
We had this same problem with tokens changing IDs after a server was started and that was fixed a while ago.  May be a similar situation.

**Comment by FullBleed** [comment]
Glad this is being looked at.  Relying on names was always problematic (though having display names mitigated some of that.)

I take it that all functions that can use map names will need to be updated?

And can we get a better function name than findMap() to get a map ID?  ;)

**Comment by kwvanderlinde** [comment]
Campaign IDs also change. Presumably that should be fixed too.

**Comment by bubblobill** [comment]
+1 FR - Trying to do map management things fails with maps having duplicate names.
+1 BUG - With two maps having identical names, only one is displayed in campaign info -> zones
e.g. from getInfo("campaign") 
{"Cobblestone":"C3F8D5D506344B8AAB43D941FFB1704F","Grasslands":"80B946EA0AC74D77AF5264EFA6BA7380"}
![image](https://user-images.githubusercontent.com/45483160/213125216-347ab01a-5f40-4e15-8696-f5152e514e3d.png)
