### ISSUE TITLE
[Feature]: Allow tooltips to use '@this' to call macros

### ISSUE THREAD

**Issue by Pmofmalasia** [RPTools/maptool#3788]
### Feature Request

Currently, because the location for code run in macro tooltips is just `Tooltip` (based on `getMacroLocation()`), it appears that they cannot use `@this` to call to macros on the same token - since the location of `Tooltip` is not the same as the token. I would like to be able to do this, and it shouldn't break any old code as currently it simply fails. Since `currentToken()` correctly identifies the actual token it is running on (instead of just identifying `Tooltip`) this may be feasible somehow - though attempting to `switchToken()` first still fails.

### The Solution you'd like

Allow `@this` to work like it does in the macro command. The output from `getMacroLocation()` probably shouldn't change.

### Alternatives that you've considered.

Not doing this, I suppose.

**Comment by bubblobill** [comment]
does this work with @token?

**Comment by Pmofmalasia** [comment]
Well now I feel like a fool. `@token` works - though didn't realize that about `@this`, I've definitely seen that documented but I've been able to use it without issue (until now) on regular tokens.
