### ISSUE TITLE
[Bug]: Fullscreen initiative button has no tooltip

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3806]
### Describe the Bug

Each button has a tooltip in fullscreen display mode except initiative

### To Reproduce

Enter fullscreen mode
Hover over initiative button

### Expected Behaviour

Tooltip required for button

### MapTool Info

1.12.2

### Desktop

Win10

**Comment by emmebi** [comment]
Can someone assign this to me? I added the missing tooltip.
