### ISSUE TITLE
[Feature]: getInfo("map") Vision Distance

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3809]
### Feature Request

Writing my own "can I see it" function that accounts for token layout scaling, offsets, and actual image boundaries.
Would be nice to dynamically set the range limit of tokens to check against based on the map limitation of Vision Distance.

### The Solution you'd like

Please add Vision Distance to the getInfo("map") object

**Comment by bubblobill** [comment]
PR #3835 addresses this feature

**Comment by kwvanderlinde** [comment]
Tested. The following always agrees with the value set in the **Map Properties** dialog:
```
[r: json.get(getInfo("map"), "vision distance")]
```
