### ISSUE TITLE
[Bug]: Add-on property becomes broken if set as "" for the first time

### ISSUE THREAD

**Issue by StefanoMarina** [RPTools/maptool#3819]
### Describe the Bug

When setting data on add-ons using `setLibProperty` , if the value is initialized as "" the first time, it becomes *unavailable*, as in:

- The variable name shows using `getLibPropertyNames`;
- Any further call of `setLibProperty` will not change the empty value;
- getLibProperty will always return empty.

This does **not** happen if the variable has been initialized with a non-empty value - variable may be set as empty or any other value without issues. 

### To Reproduce

1. load any add-on or create an empty one (try to attach one as a screenshot).
2. try `{setLibProperty("dummyVar", "", "Lib:Test")}` (replace *Lib:Test* with addon);
3. try `{setLibProperty("dummyVar", "This should be printed", "Lib:Test")}`;
4. try `{getLibProperty("dummyVar", "Lib:Test")}`

### Expected Behaviour

Variable should be changed just like Lib:Tokens

### MapTool Info

1.12.2

### Desktop

Linux [Ubuntu]

### Additional Context

[testlib.zip](https://github.com/RPTools/maptool/files/10434710/testlib.zip)

Test library, initializes some variables called `methodA` (full), `methodB` (empty) (rename to .mtlib)

**Comment by emmebi** [comment]
Assign this to me, I will investigate it.

**Comment by emmebi** [comment]
Checked the behavior for Library token; I will mimic the same behavior here.
