### ISSUE TITLE
[Feature]: Do not update map while macro is running

### ISSUE THREAD

**Issue by Lector** [RPTools/maptool#3821]
### Feature Request

I have a macro that determines the level of illumination for a specific token. As there is no specific function for this, I have created a complex mechanism. I temporarily replace every token that serves as a light source with a token that has a specific view type and check if this light source can see the target. This is not the most elegant solution, but no one on Discord could provide a better approach. To summarize, my code works well, but the generation and removal of a large number of temporary tokens results in a lot of flickering for all players and the GM.

### The Solution you'd like

To solve this problem, I suggest updating the map only after a macro has finished executing. This would not only solve my problem, but it could also help improve the performance of other macros that generate or delete multiple tokens.

### Alternatives that you've considered.

I'm not sure if my suggestion would have any side effects. If it does, it would be beneficial to give macro developers the opportunity to start something like a transaction. This way, we could call beginUpdate() and endUpdate(). During this time, MapTool would not redraw the map. It is important that canSeeToken() would still work for temporary tokens during the transaction.

**Comment by kwvanderlinde** [comment]
I'm surprised to hear this. I thought long-running macros held up the GUI thread and prevented redraws among other things. Guess I'm mistaken...

**Comment by Lector** [comment]
Maybe it's case dependent. My macro only runs for 1-2 seconds when there are a lot of light sources. However, I understand that long-running macros can be a problem if the application becomes unresponsive in the meantime. In this case, I believe the best solution would be what I suggested as an alternative.

**Comment by FullBleed** [comment]
Does this have something to do with the update to copyToken to make it so that some updates to the token could be made to the copied token during a macro?

**Comment by Lector** [comment]
Not at all. This problem also occurs even without using copyToken() at all. I managed to rebuild my algorithm so that each lightSource checks if the target is visible by changing the same token. It still works, but it also results in each light flickering when calling the macro.

```
	[h: sight = hasSight(illuminator)]
	[h: sightType = getSightType(illuminator)]
	[h: setSightType("Lightsource R"+radius, illuminator)]
	[h: setHasSight(true, illuminator)]
	[h: illuminatedPoints = canSeeToken(target, illuminator)]
	[h: relevantPoints = json.intersection(illuminatedPoints, visiblePoints)]
	[h: setHasSight(sight, illuminator)]
	[h: setSightType(sightType, illuminator)]
```

What I want to do is minimize UI updates during my loop. Since this is the only case in my framework, I am also open to alternative solutions. Additionally, I mentioned that the flickering is mostly visible for other players, especially when the internet connection is a bit slow.

**Comment by Lector** [comment]
Since you added getIllumination() in v1.14.2 i consider this issue as closed.
