### ISSUE TITLE
[Feature]: Fix MTScript (MapTool's macro language) to support more levels of nesting to help framework developers

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#3828]
### Feature Request

A long time ago (in a galaxy far, far away :), there was talk about creating a new scripting language.

Hasn't happened.  I suggest focusing on increasing MTScript's capability to process deeper nesting levels.  This is very much needed by framework developers -- and you should provide it if you want frameworks that can compete with Foundry VTT game systems.

### The Solution you'd like

I would like to have at least 4 levels of nesting -- without any special exceptions.  More levels would be gravy.

For some special cases, it is currently possible to get 3 levels.

Writing MTScript is currently too encumbering for framework developers.  Therefore, it is too difficult to develop MapTool frameworks capable of competing with Foundry VTT game systems -- but my experience has been that MTScript performance is fast enough to do it if only it was easier to write more complex code.

### Alternatives that you've considered.

I'm under pressure to use Foundry VTT for my games because players like it so much.  I hate it because everything you do there is throw-a-way.  

They change the code so much and have great difficulty upgrading legacy data to work with recent code changes that you can really only:

1. Stop upgrading while running a campaign.
2. After upgrading either the game system (say, a few versions) or Foundry VTT, you really must throw your campaigns away and start over because they are broken.
3. Thus, you can't do any campaign development in advance -- and what's the fun in that.

MapTool has none of these problems, but we have to develop sexy, complex HTML pages and, therefore, ultimately need to more easily write complex MTScript code.

**Comment by FullBleed** [comment]
While not technically "supported" you can go to more than 2 levels if you want (Wolph has indicated he's gone 9 levels deep before.)

I've probably only felt the need to do this a few times in my own framework but it works fine.

The wiki page for this has its formatting all messed up but you can see the original forum post about this here: https://forums.rptools.net/viewtopic.php?p=229036

**Comment by Akaku-Keninari** [comment]
you could also write all your handler code in javascript using graavl or whatever, that lets you do standard javascript things.

**Comment by adventuremagic123** [comment]
> While not technically "supported" you can go to more than 2 levels if you want (Wolph has indicated he's gone 9 levels deep before.)
> 
> I've probably only felt the need to do this a few times in my own framework but it works fine.
> 
> The wiki page for this has its formatting all messed up but you can see the original forum post about this here: https://forums.rptools.net/viewtopic.php?p=229036

Unless something has changed in the current releases, that did not work for me.  The script just fails.  I did that probably around MapTool 1.5.x.

**Comment by FullBleed** [comment]
> Unless something has changed in the current releases, that did not work for me. The script just fails. I did that probably around MapTool 1.5.x. I know in odd cases me and another developer have been able to go 3 levels deep -- but we need something that's reliable in all cases NOT just the odd case that scores a record.

Nothing has changed.  Please share your failed code.  I've never had an issue when using it correctly.  I know I did it "wrong" the first time I tried it a long time ago and went years before trying it again.

You can also check out the updated wiki article that has a slightly more explicit example that might be clearer (using the method I use that I hope is more obvious regarding what needs to be done): 
https://mtwiki.hyperbooks.com/wiki/index.php/working_With_Two_CODE_Levels

I'm not saying having MT "just work" with more levels wouldn't be nice... but the consequences of doing it or the hurdles required must be an issue because people have been asking for this since the advent of mtscript.  But this works for every case I've tried if the "rules" are followed (e.g. have all single quotes paired, have else statements, and place the extra '' lines in the correct locations.) 

@wolph42 might have more to add on the subject, but he doesn't frequent the git and should be pinged on the discord if you'd like his feedback.

**Comment by adventuremagic123** [comment]
> > Unless something has changed in the current releases, that did not work for me. The script just fails. I did that probably around MapTool 1.5.x. I know in odd cases me and another developer have been able to go 3 levels deep -- but we need something that's reliable in all cases NOT just the odd case that scores a record.
> 
> Nothing has changed. Please share your failed code. I've never had an issue when using it correctly. I know I did it "wrong" the first time I tried it a long time ago and went years before trying it again.
> 
> You can also check out the updated wiki article that has a slightly more explicit example that might be clearer (using the method I use that I hope is more obvious regarding what needs to be done): https://mtwiki.hyperbooks.com/wiki/index.php/working_With_Two_CODE_Levels
> 
> I'm not saying having MT "just work" with more levels wouldn't be nice... but the consequences of doing it or the hurdles required must be an issue because people have been asking for this since the advent of mtscript. But this works for every case I've tried if the "rules" are followed (e.g. have all single quotes paired, have else statements with if(), and place the extra '' lines in the correct locations.)
> 
> @wolph42 might have more to add on the subject, but he doesn't frequent the git and should be pinged on the discord if you'd like his feedback.

The wiki page says it all.  I'm asking for more levels than those provided by that description.  I no longer have a working example.

**Comment by adventuremagic123** [comment]
I prefer MapTool to any other VTT, but my players are forcing me to use Foundry VTT.  I thought of the features I just created that I thought would help reposition MapTool to provide things that GMs and players are looking for.

**Comment by FullBleed** [comment]
> I suggest taking that simple example, add more levels to it, and do some testing. You should notice problems. Should be obvious problems.

I've done 4 levels without problems... but I always aim to code for 2 if possible.  Wolph has indicated he's done up to 9.  *shrug*  I'm just letting you know what you can do if you think it is substantially holding you back right now.

**Comment by adventuremagic123** [comment]
Ok.  That was not my experience in MapTool 1.5.x.  Being partially involve with the effort to improve performance in MapTool 1.8.x, I was not aware of any changes on this issue at that time.  Hopefully, this issue goes through some sort of review process before being closed.

**Comment by FullBleed** [comment]
> You all should also make sure you understand exactly what @wolph42 is saying before committing to something so fully based on something that may be misunderstood. I'm talking from MTScript macro development experience.

And what is he saying?

**Comment by adventuremagic123** [comment]
> > You all should also make sure you understand exactly what @wolph42 is saying before committing to something so fully based on something that may be misunderstood. I'm talking from MTScript macro development experience.
> 
> And what is he saying?

So far, he's said nothing.  You're engaging in hearsay.  I'm doing my best to help the MapTool community -- so stop fighting with me.  I'm speaking from my own experience.

**Comment by FullBleed** [comment]
I don't even understand what's going on in the conversation anymore... This is a fight? 

What "hearsay" am I engaging in?

You indicated that I should "make sure you understand exactly what @wolph42 is saying before committing to something so fully based on something that may be misunderstood"... and I don't know what that means.  Maybe there is a language barrier here that I'm unaware of.  Wolph posted that hack more than a decade ago (not hearsay) and I took the time to find the post and share the link with you... he also wrote the article in the wiki (not hearsay) and I took the time to find the link on the new wiki and help taustinoc update the code so it would, hopefully, be easier to understand.

You've illustrated a common problem and this is, currently, one of the available solutions.  That is standard operating procedure for when people ask for things that have existing workarounds.

I agreed that it would be nice if MT supported more code levels and was just providing a way you could get around the issue now because I have little faith that we're going to get additional code levels any time soon.  For the record, I hope I'm wrong.

Even if you don't like the option, it doesn't mean that someone else looking to use more code levels won't appreciate learning about it.  It's a good tool to have in the toolkit.

**Comment by adventuremagic123** [comment]
Guys, I'm done with this.

**Comment by adventuremagic123** [comment]
It's just a problem of the other VTTs constantly advancing their feature set.

**Comment by Phergus** [comment]
This has been discussed many, many times in the past.  It is very unlikely that MTScript will updated to provide more levels of nesting.  The code that executes macros is essentially a large, complex and fragile regex expression and is not a real interpreter or compiler.  Allowing more levels would increase stack usage exponentially.

The new Add-On functionality allows you to use Javascript to handle complex scripting.

**Comment by adventuremagic123** [comment]
Okay.  Thank you.  I have not explored using the Add-On functionality.  I did not know you could write Javascript code to manipulate token properties directly.  I thought MTScript was still required.

**Comment by wolph42** [comment]
interesting chain... I can't really recall having said anything more than what I've said in the wiki. It IS possible to have multiple code{} levels, but you need to follow a strict rule. I've been using that for over a decade now and save some obscure coding sessions, in 99% of  the cases you can easily have multiple code layers, by simply using two single quotes '' just before each closing }. 
e.g.
```
[h,for(i,1,3),CODE:{
	[if(1), CODE:{
		[for(x,1,3), CODE:{
			[if(1), CODE:{
				[broadcast("hi")]
			''};{''}]
		''}]
	''};{''}]
''}]
```
works fine and has three code levels

**Comment by adventuremagic123** [comment]
I've tried 3 levels like that and it didn't work for me.

**Comment by adventuremagic123** [comment]
I've had 3 levels sometimes by using switch.

**Comment by adventuremagic123** [comment]
Anyway, it's been kind of a frustrating conversation for me.  I apologize for the tone of some of my comments.

Today, we used the VTT that was desired by my player (and we think players we will try to recruit).  We used it 2 years ago.  I stopped using it because of issues like we had today.  I did something as the GM to my map, and it went crazy in my player's web browser.  After an hour of researching his machine (he's visually impaired so it takes time), I verified he had plenty of memory so his machine was not thrashing and his GPU was able to provide hardware support for WebGL2.  The real answer, we're sure, is that when that happens he needs to refresh (F5) is browser to get out of a bad state.  2 years ago we had similar problems on all our machines (up to 4 of us).  It's just that things get messed up and you have to F5.

I've always had a preference for the stability I got from MapTool and the advantages of being a native app such as better performance, smoother operation when I need to interact with my file system to access files, etc.  I prefer MapTool but regardless of all the problems and additional effort my players like Foundry VTT better.  It's all the features and smoothness of the appearance of a single-page web application.  So, they overlook all the problems.

**Comment by adventuremagic123** [comment]
When I have time, I'll do a test to confirm or deny this issue.  As I said, my previous experience was that it didn't work and there was no doubt -- but that was a long time ago (but not in a galaxy far, far away).
