### ISSUE TITLE
[Bug 1.11.5+]: Initiative Tracker shows ... at round 10 and beyond

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#3833]
### Describe the Bug

When advancing the initiative to round 10 it will show ... instead of the round value.

Original Report: https://forums.rptools.net/viewtopic.php?p=279405#p279401

Follow up report: https://forums.rptools.net/viewtopic.php?t=29636

### To Reproduce

I personally can't reproduce. I tried various techniques changing the MT theme and scaling with no luck. I think it could be language related.

### Expected Behaviour

Values of 10 and above should been shown instead.

### Screenshots

Original Report has a screen shot.

### MapTool Info

1.11.5

### Desktop

Windows 11

**Comment by taustinoc** [comment]
This is apparently not a universal thing. For me, it shows correctly in 1.11.5.

Maybe it has to do with themes? The ... thing is often a sign (in Windows, at least) that there wasn't enough room to show the field. A larger font might do that.

![image](https://user-images.githubusercontent.com/64111404/218287574-8bba1d73-53bb-4be2-814b-4886e8e662c6.png)

**Comment by aliasmask** [comment]
Yeah, I tested with different themes and different Windows Scaling and I could not duplicate, but now that more than one person reported the same bug I thought I'd post it.

**Comment by bubblobill** [comment]
I could only get ellipsis when I went past 99.
With changes I showed over 100 with no troubles. Hopefully this will work for other setups.

Initial width of numeric field set to " 99", changed to "WWW". 
PR #3835
