### ISSUE TITLE
[Feature]: Add themes with (a) different font sizes, and (b) less flatness

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3836]
### Feature Request

There have been complaints from numerous users that the new themes due to FlatLAF are (paraphrasing) unattractive and hurt their eyes.
Additionally the lack of font size control make it difficult for the vision-impaired to use MT.

### The Solution you'd like

I have developed a new theme "Aah" which is closer to the previous MT colour scheme and friendlier to eyes.
There are three additional variations on the theme that adjust the default font size property (small, large, and extra large).

**Comment by kwvanderlinde** [comment]
I tried out the various Aah variants. Everything seems to be in order and does indeed feel more "classic".
