### ISSUE TITLE
[Bug]: Token Movement overlay is off on a hex grid

### ISSUE THREAD

**Issue by Piglit** [RPTools/maptool#3838]
### Describe the Bug

The movement-highlight of the grid tiles is a half tile off when dragging a token around on a hex-grid.
See Screenshot.
It starts to occure on new maps as soon as the server is started. When the server is stopped it still occures on the used map, but not on new maps created after the server was stopped.
When a new map is created on a running server, the bug does not occure until the server is stopped; but immediately after stopping the server.

### To Reproduce

1. Create a new Map with a hex grid (the bug occures on both orientations)
2. Create a Token
3. Drag the Token around with mouse or keyboard. Token position, blue line and grey highlighted tiles are displayed correctly now.
4. Start Server
5. Drag the Token around with mouse or keyboard. Token position and blue line are still correct, but the path highlight is half a tile off to the right.
6. Stop the server
7. Drag the Token around with mouse or keyboard. The path highlight is still half a tile off to the right.

### Expected Behaviour

I would expect the highlighted tiles to match the grid.

### Screenshots

![Screenshot (696)](https://user-images.githubusercontent.com/34441046/219433706-2b4c632e-c5c4-427f-aa84-70768fc886c3.png)

### MapTool Info

Version: 1.12.2, Installed via msi-Installer, Updated from 1.12.1

### Desktop

Windows 10

**Comment by Phergus** [comment]
This issue wasn't present in 1.11.5.  It shows up in 1.12.1.

After doing an Adjust Grid but not changing anything the behavior is fixed.

**Comment by kwvanderlinde** [comment]
Bisected to 60a2de63e. Problem is a simple typo of `setY()` instead of `setX()` when mapping `Dimension` to protobuf. Using "Adjust Grid" fixes it by setting the local value through non-protobuf means.
