### ISSUE TITLE
Time to Remove Warning for Import Map

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#384]
**Describe the bug**
I don't believe there have been any bugs reported or filed against Import Map for a very long time.  It is probably time to remove the experimental feature warning from it.

Note that the Help button doesn't do anything on the current popup.

**To Reproduce**
1. Select Map -> Import Map
2. See Warning.
3. Do it anyway.

**Expected behavior**
No Warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/34379254/54934957-f6b3cf80-4ee4-11e9-853a-876051ed1a48.png)

**MapTool Info**
- Version: 1.3? forwards
- Install: Any

**Desktop (please complete the following information):**
 - OS: Any
 - Version Any

**Comment by Jaggeroth** [comment]
Agreed. Been using it since it was released.
Never had any problems.

_Fate?_

**Comment by Phergus** [comment]
I'm also going to make it default to **.rpmap** files in the chooser.

**Comment by Phergus** [comment]
Fix commited in PR #402 .
