### ISSUE TITLE
[Bug]: Duplicate map display names are silently ignored

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3858]
### Describe the Bug

When setting a display name for a map, the result will be silently ignored if the display name is already in use by another map.

### To Reproduce

1. Start a new campaign.
2. Add a token to the initial map (just so the map doesn't disappear when we make a new one later)
3. Edit the initial map so its display name is "Map 1". 
4. Create a new map.
5. Edit the new map so its display name is "Map 1".
6. Check the map list. Only the initial map will have the display name "Map 1", while the second map does not have display name.

### Expected Behaviour

The display name should be set to whatever the user requested.

### Screenshots

This is the map selector after the reproduction steps.

![image](https://user-images.githubusercontent.com/7492219/224439033-ef7dd91d-ee4f-4cd0-9555-3daf3204be43.png)

This is what I would expect:

![image](https://user-images.githubusercontent.com/7492219/224439273-d517c924-7432-4fcb-9c8a-82cc2ab4812a.png)

### MapTool Info

1.12.2

### Desktop

Linux Mint 21.1

**Comment by kwvanderlinde** [comment]
I thought about making the **Expected Behaviour** be "show an error dialog" or something else to prevent duplicates while not being silently ignored. But considering that map names aren't even unique, I don't see why display names should be.

If there is a desire to make map names and display names unique, that comes with more considerations. E.g., what to do with existing campaigns, what to do when copying & importing maps, etc. - things that can be discussed in a FREQ if/when someone asks for it. For now I'd just like to see display names be more consistent with non-display names while avoiding the surprising behaviour.

**Comment by FullBleed** [comment]
I would actually be for Map Names needing to be unique, but display names not.

Display Names can be red herrings.  It's ok to confuse players... but GM's need to keep things well sorted.

**Comment by kwvanderlinde** [comment]
I agree in principle that unique map names are better. And for some functionality, it's even required in order to be well-behaved.

... but given how long we've gone with _not_ enforcing uniqueness, I don't know that it would be feasible to do, even if we wanted. There are probably plenty of existing campaigns riddled with duplicates :sweat_smile: 

For reference, a related comment with an example of a functionality issue: https://github.com/RPTools/maptool/issues/3781#issuecomment-1386689149
