### ISSUE TITLE
Command line java version no longer needed in debug info window

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#386]
**Describe the bug**
As MapTool going forward will always be 64-bit the extra info provided by the command line `java -version` call is no longer needed and leads to confusion for users.

**To Reproduce**
1. Start MapTool
2. Go to Help -> Gather Debug Information...

**Expected behavior**
No longer will show the unneeded information.

Will also be slightly faster at showing the info window without the system call.

**Screenshots**
![image](https://user-images.githubusercontent.com/34379254/54954670-d0a42480-4f10-11e9-9a7e-01ba3f493a94.png)

**MapTool Info**
- Version: 1.5.1
- Install: Any

**Desktop (please complete the following information):**
 - OS: Any
 - Version: Any

**Comment by Phergus** [comment]
@Azhrei pointed out that the max memory value being given was incorrectly formatted due to a bug introduced in Nerps fork.

**Comment by JamzTheMan** [comment]
Hey I didn't introduce no bugs! I'm pretty sure I didn't introduce a bug. Did I introduce a bug?
"Hello bug!"

Joking aside, I never touched gather info other than to add the encoding section as far as I can remember.  If it changed it could be due to JVM changes from java 1.6 through java 10?

**Comment by Phergus** [comment]
Somebody touched MemoryStatusBar.java and made a change to how the value was being saved but didn't notice that there was a public method used to access it.  ;)

No worries.  Easy fix.

**Comment by JamzTheMan** [comment]
Man, who did that? You gotta watch that guy lol 😜
