### ISSUE TITLE
[Bug]: listSort does not handle negative numbers correctly.

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#3878]
### Describe the Bug

The `listSort` function does not 

### To Reproduce

1. Run the following macro in the chat box: `[r: listSort("2, -1, 3, 5, -3, -2, -5, -4, 0, 1, 4", "N")]`
2. See incorrect result: `-1, -2, -3, -4, -5, 0, 1, 2, 3, 4, 5`

### Expected Behaviour

The correct result should be `-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5`.

The `json.sort` function achieves this correctly on a JSON array.

### MapTool Info

1.12.2

### Desktop

Windows 10 Pro

### Additional Context

Discovered via https://github.com/melek/lib_elevation/issues/17.

**Comment by taustinoc** [comment]
While I agree it shouldn't be doing that, it is sorting correctly - as a string. Which isn't overly surprising, since listSort is a string function. The solution would be for it to check to see if *all* the content is numeric, then decide how to sort it.

**Comment by melek** [comment]
Reviewing the documentation, i think I understand - the `N-` sorting/ number during in general is meant for numbers as part of similar strings. If that's accurate, then maybe we can just update the documentation.

I see the wiki was migrated again, if you send me a password for my account I'll be happy to update it and then ping here for review.

**Comment by melek** [comment]
Updated the documentation with the following note: 

> Note about numeric lists: String list values are strings, not numbers. This function can sort lists of non-negative numbers correctly with or without prefixes such as "Monster1", "Monster2", etc. Negative numbers cannot be ordered in reverse order since the hyphen is viewed as a string prefix, not as a negation symbol. In other words, the string list "-5, 1, -3, 0" will be sorted to "-3, -5, 0, 1".

> If you want to order a list of numbers, use [json.sort](https://wiki.rptools.info/index.php/json.sort) on a JSON Array. For more information about this limitation, check [the related issue on GitHub](https://github.com/RPTools/maptool/issues/3878).

Link to page: https://wiki.rptools.info/index.php/listSort
