### ISSUE TITLE
[Bug]: Missing tool-tips in token topology tab

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#3882]
### Describe the Bug

When you mouse-over / hover over the differnt BL buttons, there is no tool-tip.
All others seem to exist

### To Reproduce

Open Token Topology Tab
Mouse-over the round BL toggle buttons

### Expected Behaviour

A tool-tip pop-out stateing "<blocking type>"

### MapTool Info

1.12.2

**Comment by kwvanderlinde** [comment]
Tested. The toggle buttons now have tooltips where they didn't before. The text is inconsistent with other uses, but is descriptive enough that we can address it separately.
