### ISSUE TITLE
[Bug]: transeferVBL improper error return

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#3883]
### Describe the Bug

This may impact more than just transferVBL.
If using bad syntax on transferVBL, the error return states the function used was "getTokenVBL".

### To Reproduce

[r: transferVBL('[]', 1, 'not a token')]
returns:
Error executing "getTokenVBL": the token name or id "[]" is unknown.

### Expected Behaviour

Error executing "transferVBL": the token name or id "[]" is unknown.

### MapTool Info

v1.11.5, 1.12.2

**Comment by emmebi** [comment]
Unless someone else is already working on this, assign it to me, and I will give it a go in the coming days.
