### ISSUE TITLE
[Question]: Maptool on NixOS

### ISSUE THREAD

**Issue by trev-dev** [RPTools/maptool#3889]
### Your Question

I am trying to get a working dev environment, then maybe a working package derivation for nixos.  I can get so far as to get Maptool to build with gradle as-is thanks to the use of a filesystem hierarchy shell:

```nix
{ pkgs ? import <nixpkgs> {} }:

(pkgs.buildFHSUserEnv {
  name = "gradle-fucking-protobuf";
  targetPkgs = pkgs: (with pkgs; [
    jdk17
    gradle
    protobuf
    glibc
  ]);
  runScript = "bash";
}).env
```

The build goes smoothly, and the run *appears* to go smoothly, but I get no splash/loader, and no app.

Output:
```
~/Projects/maptool develop [?]  λ nix-shell
[env] ~/Projects/maptool develop [?]  λ gradle run

> Configure project :
Project : => no module-info.java found
Configuring for MapTool-Dev-Release SNAPSHOT-4144494 by RPTools
AppVersion: 0.0.1
OS Detected: linux
Setting Linux installer options

> Task :extractProto
> Task :configSentryRelease UP-TO-DATE
> Task :dicelib:compileJava
> Task :dicelib:processResources NO-SOURCE
> Task :dicelib:classes
> Task :dicelib:jar
> Task :processResources
> Task :extractIncludeProto
> Task :generateProto

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :classes
> Task :configJavafxRun

> Task :run
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
19:06:40.961 (MapTool.java:1562) [main] INFO  - ********************************************************************************
19:06:41.002 (MapTool.java:1563) [main] INFO  - **                                                                            **
19:06:41.003 (MapTool.java:1564) [main] INFO  - **                              MapTool Started!                              **
19:06:41.003 (MapTool.java:1565) [main] INFO  - **                                                                            **
19:06:41.004 (MapTool.java:1566) [main] INFO  - ********************************************************************************
19:06:41.004 (MapTool.java:1567) [main] INFO  - Logging to: /home/trev/.maptool-rptools/logs/maptool.log
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
19:06:41.066 (MapTool.java:1655) [main] INFO  - argument passed via command line: -v=0.0.1
19:06:41.067 (MapTool.java:1659) [main] INFO  - overriding MapTool version from command line to: 0.0.1
19:06:41.067 (MapTool.java:1666) [main] INFO  - MapTool vendor: RPTools!
Gtk-Message: 19:06:41.180: Failed to load module "colorreload-gtk-module"
```

If I drop out of my environment and go into the distribution folder, unpack an archive and run a build, the same thing happens.

I thought perhaps it was the fact that I was running in xmonad with no real "window manager", so I quickly grabbed XFCE, and the results are the same.

System:
```
trev@nixos 
---------- 
OS: NixOS 22.11.3326.a38c914c34f (Raccoon) x86_64 
Host: Dell Inc. 05FFDN 
Kernel: 5.15.104 
Uptime: 28 mins 
Packages: 1131 (nix-system), 5966 (nix-user) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Xfce 4.16 
WM: Xfwm4 
WM Theme: Default 
Theme: Graphite-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: .xfce4-terminal 
CPU: Intel i7-7700HQ (8) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 1050 Mobile 
GPU: Intel HD Graphics 630 
Memory: 4998MiB / 15733MiB 
```

Any advice would be appreciated.

**Comment by thelsing** [comment]
This seems more a java gui on nixos issue that a maptool specific one. I would start getting a simple hello world swing app to run.

**Comment by trev-dev** [comment]
> This seems more a java gui on nixos issue that a maptool specific one. I would start getting a simple hello world swing app to run.

Hmmm,  then maybe this is related? https://github.com/NixOS/nixpkgs/issues/50418

**Comment by Azhrei** [comment]
Yes, that’s going to be it. It looks like there’s some GUI implementation library that is attempting to use GTK and either you don’t have it or the code attempting to use it is making that attempt in error. Either way, this is a Java implementation issue, IMO. (I don’t use or know anything about nixOS so I can’t help.)

**Comment by trev-dev** [comment]
Welp, I tried the `jetbrains.jdk` package, while it is significantly larger than openjdk, it did not resolve the problem.  I also tried to use `oraclejdk` but got blocked by oracle licensing for its dependency of oraclejdk8.

That's it for me util either I or someone else resolves the JDK problem in nix.  Arch is looking pretty good right about now.

**Comment by rhendric** [comment]
It's not built from source, but if you're still interested in a Nix derivation of any variety: https://github.com/NixOS/nixpkgs/pull/232728

(The issue you observed goes away when you use Temurin instead of OpenJDK as your JRE. I did get to an environment where building and running MapTool was possible—more pointers available on request if you want them—but it involved a lot more violence to the `build.gradle` file than I wanted to use for a published derivation given that a JAR was available.)
