### ISSUE TITLE
[Bug]: map cell change breaks lib tokens

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#3908]
### Describe the Bug

When you change the Map - Cell type to anything other than what the campaign map loaded with, lib tokens appear to fail (remove the .zip from the file to test)
[LibBreakOnCellTypeChange.cmpgn.zip](https://github.com/RPTools/maptool/files/11185840/LibBreakOnCellTypeChange.cmpgn.zip)

### To Reproduce

1. Open attached campaign
2. Move the elf token to display chat output
3. Change the cell type via Map - Edit Map - Cell Type to something else
4. Move the elf token - no display in chat output

### Expected Behaviour

lib tokens should function properly

### MapTool Info

v1.13.0, v1.13.0b1

### Desktop

Win 11

**Comment by Azhrei** [comment]
Are you storing the token id for the lib token and trying to reuse it?  There was a recent feature patch to maintain consistent token ids across campaign loads, but Edit Map is essentially deleting the map and creating a new one.  It probably didn't receive the same update...

**Comment by Jmr3366** [comment]
There are two tokens, one is a lib:token (Dragon) with a `onTokenMove` macro.  It has one line `[h: broadcast(getLastPath())]`
If I change the cell type to anything, it no longer broadcasts.
