### ISSUE TITLE
Default Map Preferences doesn't support decimal input for Units per Cell

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#392]
**Describe the bug**
Preferences didn't get updated to handle the new decimal Units per Cell values.

[See report on forum](https://forums.rptools.net/viewtopic.php?f=21&t=28064).

**To Reproduce**
1. Start MapTool
2. Go to Edit Preferences -> Interactions Tab
3. Enter a decimal New Map Units per Cell size such as 1.5.
4. Click OK to close Preferences window.
5. Re-open Preferences and see that only integer portion was retained.

**Expected behavior**
Decimal value should have been retained.

**MapTool Info**
- Version: 1.5.1
- Install: Any

**Desktop (please complete the following information):**
 - OS: Any
 - Version: Any

**Comment by oliver-szymanski** [comment]
Done, PR in #393

**Comment by oliver-szymanski** [comment]
Just to be sure here, does anyone know where the preference settings are saved on the file system? I assume this is per installation. At least I had no conflict in the preferences of my older MT install.

**Comment by JamzTheMan** [comment]
I believe it's still OS specific and for Windows it's still in the registry (I don't think Java has moved it to the app local dir yet as a file, which would be nice...)
