### ISSUE TITLE
[Feature]: Add Lebel field to New Token dialog

### ISSUE THREAD

**Issue by taustinoc** [RPTools/maptool#3972]
### Describe the Problem

The Edit Token dialog shows four names: Name, GM Name, Label and Speech Bubble Name. The New Token dialog, however, only shows three; Label is missing.

### The Solution you'd like

The Label field should be added to the New Token dialog

### Alternatives that you've considered.

The only other option is to drop the new token, then open the Edit Token dailog.

**Comment by kwvanderlinde** [comment]
Tested. "Label" field is now present, editable, and respected on the new token:

![image](https://github.com/RPTools/maptool/assets/7492219/ecd77dd4-7175-4eca-984f-c20a6007a2d7)
![image](https://github.com/RPTools/maptool/assets/7492219/7786e51b-8382-46fc-81d9-6bd83f22131c)
