### ISSUE TITLE
Newlines cannot be inserted except at the end in the Command panel

### ISSUE THREAD

**Issue by kayila** [RPTools/maptool#398]
**Describe the bug**
Newlines in the command panel can only be inserted at the end. of the string.

**To Reproduce**
1. Type something into the command panel
2. Move the cursor somewhere in the middle of the line
3. Press shift-enter

**Expected behavior**
A newline should be inserted wherever the cursor is.

**MapTool Info**
- Version: 1.5.1
- Install: Upgrade, JAR

**Desktop (please complete the following information):**
 - OS: Manjaro linux
 - Version: rolling

**Comment by Phergus** [comment]
Don't see this issue under Win10.  Shift-Enter or Enter both work at any point in the line.  I assume you are referring to the Command editing field of the Macro Editor.

**Comment by Phergus** [comment]
Ohh.  You're talking about the Chat window.

**Comment by kayila** [comment]
Correct. In code, the chat window is the CommandPane class. :)

**Comment by Phergus** [comment]
Figured that out when I looked at your patch. :) That's been like that forever.  A little surprised that no one has asked for the fix before.
