### ISSUE TITLE
[Bug]: Map lighting style is not synced to clients.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3982]
### Describe the Bug

When a client is connected and the map's lighting style is changed on the server, the change is not reflected on the client.

### To Reproduce

1. Open a campaign.
2. Start a server.
3. Connect a client.
4. Make sure the server and client are on the same map and that the map has lights on it.
5. Make sure lights are enabled in the _View_ menu.
6. On the server, edit the map and change the lighting style.
7. Observe the change in light rendering on the server, while the client uses the previous style.

### Expected Behaviour

Clients should render the map using the newly set lighting style.

### MapTool Info

1.13.0-beta.2

### Desktop

Linux Mint  21.1

**Comment by Pmofmalasia** [comment]
Map lighting style correctly updates for a connected client for me on 1.13.2
