### ISSUE TITLE
[Feature]: Alias() macro function

### ISSUE THREAD

**Issue by Akaku-Keninari** [RPTools/maptool#3984]
### Describe the Problem

I'm trying to make it so an add-on project of mine can add in new slash commands to chat. Unfortunatly it seems you can only access 'alias' via a slash command and you can only have a macro send one slash.

### The Solution you'd like

Exposing the alias function as a macro, so basically [h: alias("string_4_alias", "macro_or_eval_or_something")]

### Alternatives that you've considered.

Not using slash commands for this and having a frame with the commands instead. Less keyboard friendly but technically would accomplish endpoint.

**Comment by bubblobill** [comment]
#1691

**Comment by cwisniew** [comment]
Closing as its a duplicate
