### ISSUE TITLE
[Refactoring]:  Update to google format 1.16 for spotless formatting

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#3988]
### Describe the problem

The develop branch has been updated to google format version 1.16, but with release still at 1.11 it makes merges more difficult due to formatting differences.

### The improvement you'd like to see

Update google java format for spotless to 1.16 on release-1.13 branch

### Expected Benefits

Easier to merge back to develop

### Additional Context

Develop branch had to move to an updated version of google format as 1.11 does not work with java 20

**Comment by kwvanderlinde** [comment]
Given the many PRs that have successfully passed since this change, and the agreement in formatting between release-1.13 and develop, this change checks out.
