### ISSUE TITLE
[Bug]: Diamond and Hollow Diamond VBL tools have incorrect tool tip

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#4027]
### Describe the Bug

The Diamond and Hollow Diamond VBL tools have incorrect tooltips and instructions.

### To Reproduce

Hover the mouse pointer over either the Diamond or Hollow Diamond VBL tools

### Expected Behaviour

The tool tip and instructions should refer to diamond rather than rectangle.

### MapTool Info

MapTool 1.13.0

### Desktop

All

**Comment by kwvanderlinde** [comment]
I don't think it's really the tooltip that is wrong here. These tools _do_ draw rectangles, for ISO maps specifcally. Their use on other maps seems very niche given how particular the shape the is.

It would be better to do one of:
1. Enable/disable the tools depending on the map type
2. Update the tooltip to say they are for ISO specifically.
3. Both of the above.

**Comment by kwvanderlinde** [comment]
The _real_ bug IMO is that the drawing tools and FoW tool are both labels as drawing "diamonds" rather than ISO rectangles.

**Comment by cwisniew** [comment]
> The _real_ bug IMO is that the drawing tools and FoW tool are both labels as drawing "diamonds" rather than ISO rectangles.

You are correct I will update the PR

**Comment by kwvanderlinde** [comment]
Tested. The tooltip now refer to "isometric rectangles" as expected.

Separate to that, I noticed that drawing and FOW tools still use the term "diamond". For consistency, I'll make new issues to get those updated too.
