### ISSUE TITLE
[Bug]: Lumens overlay is behind drawings

### ISSUE THREAD

**Issue by Lector** [RPTools/maptool#4034]
### Describe the Bug

The lumens overlay is rendered behind drawings on the map. This is bad because drawings can be used to improvise maps of buildings.

### To Reproduce

Draw a box.
Create a token on the box.
Give this token a light source.
Show the lumen overlay.

### Expected Behaviour

I would like the lumens overlay to be drawn OVER the drawings, not behind.

### Screenshots

https://cdn.discordapp.com/attachments/905157521193455676/1104201673573937253/image.png

### MapTool Info

1.13.0

### Desktop

Windows 10

**Comment by kwvanderlinde** [comment]
This is as designed, so not a bug, though this could be kept as a feature request instead.

Note that the lumens overlay is layered exactly where lights are: behind Token and Hidden drawings, but in front of Object and Background drawings. E.g., here's four drawings, each on different layers:
![image](https://user-images.githubusercontent.com/7492219/236790483-d88541b1-197f-45ba-a39f-2142014276ff.png)

Drawings on the Token and Hidden layers actually cover up a couple other important things, such as the grid and auras. So there's a few reasons to put this kind of drawing on either the Object or Background layers.

**Comment by Lector** [comment]
All right! I was not aware of the possibility to draw on the background layer.
Thanks for the clarification. I close the issue now :)
