### ISSUE TITLE
Manipulating token can lead to duplicate tokens on other maps

### ISSUE THREAD

**Issue by source-knights** [RPTools/maptool#404]
**Describe the bug**
The way MT saved and updates token can lead to duplicate tokens on other maps.
This happens in a lot of places in the code, one example to see the error is under "to reproduce".

I know how and where to fix it if this is wished (already have done it in my extensions).

**To Reproduce**
Use the following macro on any map with a token called "Eagle" while having another map called "anothermap"

`[h: tokenId = findToken("Eagle")]
[h: setProperty("hello", "world", tokenId)]

[h, token(tokenId), code: {
  [h: setCurrentMap("anothermap")]
  [h: setProperty("hello","anotherworld")]
}]`

**Expected behavior**
The original token should have been changed, instead of a 2nd token with same tokenId create on another map.

**Screenshots**

**MapTool Info**
- Version: 1.5.1 and lower

**Desktop (please complete the following information):**
 - happens on all OSs

**Additional context**
-

**Comment by oliver-szymanski** [comment]
I know how and where to fix it if this is wished (already have done it in my extensions).

**Comment by JamzTheMan** [comment]
Lets see if we can replicate it but it sounds like it should be fixed. I. Surprised it hasn't been brought up before.

What is your proposed fix? To allow changes to tokens on other maps via GUID regardless of map or throw an exception if not on the proper map?

**Comment by oliver-szymanski** [comment]
I make a check before any putToken if the zone is the correct zone for the token. If not remember the current zone renderer, change it to the one with the token (that will not change the UI), putToken with correct zone and restore the zone renderer.

Basically change every "putToken" to something like 3-4 lines, of course put in a nice method ;)

**Comment by Azhrei** [comment]
So did you create a static `putToken(tokenID, zone)` or something else?

I suppose this is a worthwhile bandaid on the problem until the renderer is rewritten and the token split work is done.  I think most macro authors are already familiar with this issue, though.  I'd say it's low priority, but a useful fix.

**Comment by Phergus** [comment]
@JamzTheMan I can confirm that the example macro code above does indeed create an evil twin token.

**Comment by oliver-szymanski** [comment]
I do it a bit differently in my extension, cause that is not changing the MT code at all to make updates easier for me. But I think the proper fix would indeed be to replace all the putToken calls

**Comment by JamzTheMan** [comment]
Sounds ok to me, if you want to port it over, submit a PR.

**Comment by Merudo** [comment]
Another option is to take

`MapTool.serverCommand().putToken(MapTool.getFrame().getCurrentZoneRenderer().getZone().getId(), token);`

and replace it with

`MapTool.serverCommand().putToken(token.getZoneRenderer().getZone().getId(), token);`

**Comment by JamzTheMan** [comment]
Why did putToken need the first parm?

**Comment by Merudo** [comment]
For [moveTokenToMap()](https://github.com/RPTools/maptool/blob/9191a135d11d28ebd7e2e8cf122cf08b59ceb139/src/main/java/net/rptools/maptool/client/functions/TokenLocationFunctions.java#L237), where it is necessary to take a token from one map and send it to another map.

I could change this relatively easily with function overloading.

**Comment by Phergus** [comment]
Merudo's suggestion seems like a better way as that ensures that the zone ID passed is going to align with the zone the token is on.

Overloading server command putToken() with one that only takes the token argument would certainly improve code readability.

**Comment by Merudo** [comment]
Commit #555 fixes a few of these issues, including the original example with setProperty.

**Comment by Phergus** [comment]
Closing.  Related issues can be brought up in new tickets.

**Comment by Phergus** [comment]
Tested against current code with macro supplied in issue.
