### ISSUE TITLE
[Bug]: Visible area not being calculated correctly.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4043]
### Describe the Bug

In MapTool 1.12.2 and earlier, lights and other things would only be drawn if a token in the current view could see it. Since 1.13.0, the "visible area" has accidentally been replaced with the "illuminated area", so things are being rendered for players as long as they are illuminated, exposing secret information to them.

### To Reproduce

1. Make a room with a light source in it.
2. Put a PC in the room and expose their visible area.
3. Move the PC out of the room so they can no longer see into it.
4. Check the player view with the PC selected. Notice that the PC can still see the light and light source token inside the room.

This [campaign file](https://github.com/RPTools/maptool/files/11425332/visible-area-now-includes-soft-fow.cmpgn.renamed-to.zip) also demonstrates the problem.

### Expected Behaviour

Tokens, labels, lights, etc., should not be visible to players when their tokens are not able to see them.

### Screenshots

Here is the attached campaign map. The left is a room with a PC, the right is a room with a light source that the PC is not able to see, but that has had FoW previously revealed:
![image](https://user-images.githubusercontent.com/7492219/236941142-058df927-4a30-45d7-8d38-8efaedbe1929.png)

The expectation is that nothing is rendered in that room, except the map with soft FoW:
![image](https://user-images.githubusercontent.com/7492219/236941647-6e4dc79f-a4c7-4940-ba65-76ce37fc353c.png)

### MapTool Info

1.13.0

### Desktop

Linux Mint 21

**Comment by Pmofmalasia** [comment]
Appears to be fixed for me on 1.13.2.
