### ISSUE TITLE
[Bug]: Auras removed from a token are still rendered afterwards

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4057]
### Describe the Bug

Auras assigned from tokens stick around even after being removed from them. They stick around until something "significant" happens (a different light is assigned to the token, another token's view changes, etc).

### To Reproduce

1. Create an aura, any auras
2. Give a token the aura
3. Remove the aura from the token.
4. See the aura still being drawn.
5. Move the token
6. See the aura still being drawn in the original location.

### Expected Behaviour

Auras are no longer rendered as soon as they are removed from the token.

### Screenshots

After removing the aura, the token can be moved away from its old aura:
![image](https://github.com/RPTools/maptool/assets/7492219/d33777e8-2c0c-4369-a4fd-fad69b9dd7ec)

### MapTool Info

1.13.0, 1.13.1-rc1

### Desktop

Linux Mint 21

### Additional Context

This is new behaviour in 1.13. It doesn't seem to matter _how_ the aura is removed (e.g., via _Clear All_, clicking the aura specifically).

The same issue does not exist with normal lights.

**Comment by Pmofmalasia** [comment]
Confirmed fixed in 1.13.2.
