### ISSUE TITLE
Drop Highest Rolls from a Roll of X Dice

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#406]
**Is your feature request related to a problem? Please describe.**
There is not a roll option to roll X die and drop N highest.

**Describe the solution you'd like**
We currently have this for dropping the lowest die/dice.

> XdYdN | drop | Roll X dice with Y sides each, and drop the lowest N dice afterward | /roll 4d6d1 roll four six-sided dice, drop the lowest roll, and presents the total in the chat window

This function would be similar except it would drop the highest dice rolls not the lowest. 

**Describe alternatives you've considered**
You would need to code something in MTScript to get this effect.

**Additional context**
Request from Facebook user Claus Bundgaard Rasmussen

[Dice roll expressions on wiki](http://lmwcs.com/rptools/wiki/Dice_Expressions)

**Comment by Phergus** [comment]
Description is backwards from the title?   Should be **_keep_** in description not _drop_.

**Comment by rkathey** [comment]
I think it's correct. The goal is to drop the highest rolls from a group of dice. 
I updated the description to make it (I hope) clearer.

**Comment by Phergus** [comment]
My bad.  I was confusing the description of existing functionality with what was wanted.

**Comment by JamzTheMan** [comment]
https://github.com/RPTools/dice

**Comment by Phergus** [comment]
Completed with PR #421
