### ISSUE TITLE
[Bug]: Isometric map token paths

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#4077]
### Describe the Bug

When on an isometric map, the token path draws in hex when it should be square

### To Reproduce

Create an iso map
Drag a token to the map
Drag the token to another point

### Expected Behaviour

It should remain square

### Screenshots
Left image is 1.12.1  right image is 1.13.1
![image](https://github.com/RPTools/maptool/assets/100969108/2d557599-1fa0-485e-8fb1-77cc37b657d1)

### MapTool Info

1.13.x

### Desktop

Win 11

**Comment by Pmofmalasia** [comment]
Isometric tokens now show the old square/diamond path underneath the token on 1.13.2 for me.
