### ISSUE TITLE
[Bug]: Increase of memory usage in 1.13.x

### ISSUE THREAD

**Issue by thelsing** [RPTools/maptool#4082]
### Describe the Bug

The memory usage went up quite a bit compared to 1.12

### To Reproduce

Start MT 1.12 open some campaign, not memory usage, repeat the same with 1.13, note the difference.

### Expected Behaviour

Comparable memory usage to 1.12

**Comment by kwvanderlinde** [comment]
Tested on a campaign that - on 1.13 - would routinely climb to over 2GB before settling. On 1.14.0-rc.4, memory is happy to stay well under 1GB.
