### ISSUE TITLE
[Bug]: Older (pre 1.12) campaigns can fail to load due to templates/drawings that have no quadrant,

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#4095]
### Describe the Bug

If an old campaign containing a template or drawing without a quadrant is loaded in 1.13 (and probably earlier) it will fail and the campaign wont load.	

### To Reproduce

Load a campaign with this issue (finding one is easier said than done though)

### Expected Behaviour

The map should load

### Screenshots

![image](https://github.com/RPTools/maptool/assets/73173/74440f63-b70b-4785-8ebb-704c3724a656)

**Comment by cwisniew** [comment]
> Okay, not sure how you ended up with a campaign like this. It would either have to be _really_ old (beyond my visibility) or else our logic messed up somewhere along the way and made this by accident ...
> 
> I tested this by manually hacking the quadrant out of an existing line template and things check out. But if you have a campaign that still has this issue I also can try it on that.

Someone supplied as really old one :) Unfortunately, I can no longer recall who or find the campaign I used to find/test it.

**Comment by kwvanderlinde** [comment]
I'm happy to close this off then. We can revisit if needed.
