### ISSUE TITLE
[Bug]: Token macros do not execute when the current map is not visible.

### ISSUE THREAD

**Issue by Kkrafy** [RPTools/maptool#4100]
### Describe the Bug

When executing a token macro as a player with the current map not visible it will return that error: 

Could not execute the command: "im 777ACDAA38134C1F9F4391599C0FC29F:[r:getCurrentMapName()]", exception = Cannot invoke "net.rptools.maptool.client.ui.zone.ZoneRenderer.getZone()" because the return value of "net.rptools.maptool.client.ui.MapToolFrame.getCurrentZoneRenderer()" is null

Thats because in the execution of Token macros a lot of thing needs the current zone(that is null when the map is not visible) 

### To Reproduce

1:Create a server and add a token with a macro
2:Join the server as a player
2:Select a token with macros
3:As the GM turn the map invisible for players
4:As player execute a macro

### Expected Behaviour

I think when the map is invisible, the tokens should be removed from the selector(to the player), or at least display a more user-friendly error message in the chat. (I also tried disabling the macro buttons, but I think obtaining them would require extensive modifications to the code.)

PS: I have already developed the code to remove the tokens from the selector, and I will pull request it mentioning this issue.

### MapTool Info

1.13

### Desktop

Windows 11

**Comment by kwvanderlinde** [comment]
Tested on 1.14.0-rc.4. Hiding the map as GM removes the token from player selections preventing macro buttons from being clicked. This can be circumvented by using impersonation, as that sometimes allows the macro buttons to still be accessed. Opened #4387 to address the impersonation case.

Also tested running macros via macro links, which gives a good neutral error:
> Unknown macro "test".
> Error trace : test@Token <<< macroLink
