### ISSUE TITLE
[Bug]: new stat-sheets not exclusive between types

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#4150]
### Describe the Bug

Multiple stat-sheets can be shown on screen if they are of different types.

### To Reproduce

have two tokens with different types of stat-sheet. One legacy, one new.
Moving the mouse over the tokens can cause both to be drawn if you get the timing right.

### Expected Behaviour

The most recent token moved over should cause the previous one to disappear

### Screenshots

![image](https://github.com/RPTools/maptool/assets/45483160/3bb4e26f-0a65-4a6f-8663-30b0e9d58345)

**Comment by kwvanderlinde** [comment]
Tested on 1.14.0-rc.4. Only one stat sheet is now displayed at any given time.
