### ISSUE TITLE
[Feature]: Refactor Add On Dialog so that it uses applied theme

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#4154]
### Describe the Problem

The Add On Dialog uses JavaFX, and as such, the user's theme is not applied to it

![image](https://github.com/RPTools/maptool/assets/73173/0595dc7c-aadf-4822-8912-993fc31e8dc3)

### The Solution you'd like

Reimplement the dialog in swing so that the user's theme will be used.

**Comment by kwvanderlinde** [comment]
Tested. The dialog now uses whichever themes was selected when MapTool started.
