### ISSUE TITLE
[Bug]: json.null, json.true, json.false are not JSON values

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4161]
### Describe the Bug

`json.null` is the string `"null"` rather than the JSON value `null`. Similarly, `json.true` gives the string `"true"` and `json.false` the string `"false"`. This makes it difficult to interact with, e.g., JavaScript code that expect the normal values of `true`, `false` and `null`.

### To Reproduce

1. In chat, run this command: `[r: json.append("[]", json.null, json.true, json.false)]`
2. See the output `["null","true","false"]`

### Expected Behaviour

- `json.null` should be the JSON `null` value
- `json.true` should be the JSON `true` value
- `json.false` should be the JSON `false` value

In particular, the above command should result in this JSON: `[null, true, false]`

### MapTool Info

1.13.1

### Desktop

Linux Mint 21.1

### Additional Context

This has been the behaviour since forever as far as I'm aware.

**Comment by remcoros** [comment]
Unfortunate design., but I think if that will be changed now, it will break a lot of campaigns, frameworks, and macros

**Comment by Akaku-Keninari** [comment]
Is it a common thing for people to use specifically json.null/true/false instead of 'true' 'false' 'null'?

**Comment by Azhrei** [comment]
I think a core issue is that MTscript has no way to denote JSON `null`.  Similarly, true and false in MTscript are simply 1 and 0 and not discrete values.

An argument could be made that using the words null, true, and false, in a JSON context could automatically convert to the correct thing, but backward compatibility will be the issue.

Maybe some kind of `MapTool.isNull()` set of functions could help?  They could check for the actual `null` as well the string "null".  It would still be up to the JS developer to realize that this is a problem and code for it.

**Comment by kwvanderlinde** [comment]
> Is it a common thing for people to use specifically json.null/true/false instead of 'true' 'false' 'null'?

From the things I've seen and written, no (not that my experience makes for a good indicator :sweat_smile:). First you have to discover them. Then you find out that they don't do anything different than the strings while also being more longwinded... 

***

> I think a core issue is that MTscript has no way to denote JSON `null`. Similarly, true and false in MTscript are simply 1 and 0 and not discrete values.

It's true, this goes beyond just the constants. If this bug were to be fixed as requested, MTScript would have to consistently treat the values as JSON. But thats less of a limitation and more a choice as we already do exactly that for JSON objects and arrays, both in maintaining the internal JSON representation (GSON) where possible, and in parsing strings as JSON where JSON values are expected. In principle we could do the same for the JSON values `null`, `true`, and `false`.

> An argument could be made that using the words null, true, and false, in a JSON context could automatically convert to the correct thing, but backward compatibility will be the issue.

We do the equivalent for JSON objects and arrays: if a JSON value is needed and a string can be parsed as a JSON object or array, it will be parsed to GSON before being used. Ideally we could do the same for the plain strings `"null"`, `"true"`, and `"false"`.

I have some examples below that show we don't need this for embedded values, it's just when encountering them as top-level values. So this would be a pretty narrow set of behaviours that would change: it applies very specifically to the MTScript strings `"null"`, `"false"`, and `"true"`, and only when passed to a function expecting JSON. The bigger BC impact would actually be the previous point on having MTScript preserving the GSON representation of these values.

> Maybe some kind of MapTool.isNull() set of functions could help? They could check for the actual null as well the string "null". It would still be up to the JS developer to realize that this is a problem and code for it.

The fact that JS (and MTScript!) devs need to realize this is the motivation I had for filing the bug. It's a surprise every time. Even if we had a helper function and everyone knew that they needed it, it means we can't write JS in a natural way. Plus it adds some (mild) ambiguities as the string `"true"` might really be meant as a string or it might be meant as a boolean.

***

Thought it would be interesting to share what we can do today in 1.13.2. If we're willing to write JSON strings directly, we _can_ embed JSON `null`, `true`, and `false` into objects and arrays:
```
[r: json.append("[null]", "a string")]
```
Prints: `[null,"a string"]`, showing that the first parameter is an array with a real JSON `null` in it, as opposed to a string `"null"`.

But if we try to get the `null` out on its own then it gets turned into a string. E.g., this grabs the `null` from the array and then tries to append it to another array:
```
[r: json.append("[]", json.get("[null]", 0))]
```
That reads like it would get us back to `[null]` but it actually prints `["null"]`.

The same examples work equivalently for `true` and `false`.

**Comment by cwisniew** [comment]
Originally, these did return JSON values, somewhere along the way that got broken. From v 1.5 (in MapToolVariableParser)

```java
  @Override
  public Object getVariable(String name, VariableModifiers mods) throws ParserException {

    boolean evaluate = false; // Should we try to evaluate the value.

    switch (name) {
      case JSON_NULL:
        return JsonNull.INSTANCE;
      case JSON_TRUE:
        return new JsonPrimitive(true);
      case JSON_FALSE:
        return new JsonPrimitive(false);
    }
```

I can't remember what version the auto convert in json objects/arrays of null, true, and false occurred. But the above constants exist because we can't change the scemantics of the strings "true", "false" in non JSON objects
e.g.
```
[json.set("{}", "isTrue", "true")}
```
Because it would lead to breaking peoples macros, and despite being the loudest about new features macro writers are the worst at testing new features so we end up having to either revert it in a point release or tell everyone too bad your frameworks no longer work.

So the json.true/false/null were invented.
```
[json.set("{}", "isTrue", json.true)]
```

Generally, bare true, false, null in json objects and types get converted correctly, because it caused an error before we put the auto covert in so it was safe to assume people were not relying on it, outside of json types we have to assume its the actual string otherwise we will break frameworks as people are relying on it.

**Comment by cwisniew** [comment]
I say "auto convert" above, it's more "let the json parser do its job without intervening"... Originally bare true, false, null were converted to string as there was no javascript to pass it to and with only MTScript no way to interact with true/false/null if it wasn't a string

**Comment by kwvanderlinde** [comment]
So I dug into this a bit, the change to not treat `"null"`, `"true"`, and `"false"` as JSON `null`, `true`, and `false` was back in 1.5.11. Compare with the 1.5.10 behaviour:
```
[r: json.append("[]", "null", "true", "false")]
```
Would print: `[null, true, false]`, but since 1.5.11 it prints `["null", "true", "false"]`.

I can certainly see why that change was made, however it had an unfortunate casualty due to the JSON functions eagerly converting `null`, `true`, `false` results to MTScript strings. That made code like this no longer do the "obvious" thing:
```
[r: json.append("[]", json.get("[null]", 0))]
```
In 1.5.10, that would print `[null]`, but since 1.5.11 it prints `["null"]`.

As for the constants, they were also introduced in 1.5.11. But they were already broken back then, and in every released version I've tested between then and now. Although the nature of the broken behaviour is a little different:
- In 1.5.11, `MapToolVariableResolver.getVariable()` returned GSON objects for these constants and something else converted them to strings.
- Since 1.8.1, `MapToolVariableResolver.getVariable()` directly returns strings for these constants, but if it had returned a GSON objects they would have been kept that way and not converted to strings.

**Comment by cwisniew** [comment]
> So I dug into this a bit, the change to not treat `"null"`, `"true"`, and `"false"` as JSON `null`, `true`, and `false` was back in 1.5.11. Compare with the 1.5.10 behaviour:
> 
> ```
> [r: json.append("[]", "null", "true", "false")]
> ```
> 
> Would print: `[null, true, false]`, but since 1.5.11 it prints `["null", "true", "false"]`.
> 

Yeah we had to make a "fix" so that append, set etc, would not convert strings of "null", "true", "false" in the non json object arguments to json null, true, false, due to all the reports of frameworks breaking.

**Comment by kwvanderlinde** [comment]
So @cwisniew, here's how I see this shaping up. Please correct me if I'm wrong, otherwise I'll implement this:

We can modify the constant lookup so that `json.null`, `json.true`, and `json.false` are no longer strings, but are GSON `JsonElement`. Even though they have always been strings in the past, they don't serve their purpose as-is and is hopefully not used many places that need strings.

We _cannot_ modify MTScript behaviour to treat the strings `"null"`, `"true"`, `"false"` as JSON, since that is not always desirable even in JSON contexts.

Open question: `json.get()` and similar functions have similar logic as the constant lookup: JSON objects and arrays are kept as GSON, but `null`, `true`, and `false` are converted to `"null"`, `"true"`, and `"false"`. Should we leave this as-is or change it to match the constants?

**Comment by cwisniew** [comment]
> So @cwisniew, here's how I see this shaping up. Please correct me if I'm wrong, otherwise I'll implement this:
> 
> We can modify the constant lookup so that `json.null`, `json.true`, and `json.false` are no longer strings, but are GSON `JsonElement`. Even though they have always been strings in the past, they don't serve their purpose as-is and is hopefully not used many places that need strings.
> 
> We _cannot_ modify MTScript behaviour to treat the strings `"null"`, `"true"`, `"false"` as JSON, since that is not always desirable even in JSON contexts.

This is how I see it as well.

> 
> Open question: `json.get()` and similar functions have similar logic as the constant lookup: JSON objects and arrays are kept as GSON, but `null`, `true`, and `false` are converted to `"null"`, `"true"`, and `"false"`. Should we leave this as-is or change it to match the constants?

Converting them would sadly run into the same issue, where people have used the previous versions which were strings, so if we change them their code will fail. 

e.g. they are doing something like  
```
[h: open = json.get(door, "open")]
[h: if (open == "true") ...]
```
Which would then fail

**Comment by kwvanderlinde** [comment]
I'll share this in case it is of interest to future readers.

Although we aren't going to modify `json.get()` behaviour, we can write wrapper UDFs that are able to return embedded `null`, `true`, and `false`. Here's one idea for that (only supports looking up a single index from an array, but serves as an example):
```
[h: vJson = arg(0)]
[h: vIndex = arg(1)]

[h: vResult = json.get(vJson, vIndex)]

[h: "Check if vResult should have been null, true, or false and replace it as needed."]
[h: vSubset = json.get(vJson, vIndex, vIndex)]
[h, if(vSubset == "[null]"): vResult = json.null]
[h, if(vSubset == "[true]"): vResult = json.true]
[h, if(vSubset == "[false]"): vResult = json.false]

[h: return(0, vResult)]
```
