### ISSUE TITLE
[Bug]: Missing macro image freezes maptool

### ISSUE THREAD

**Issue by SterLovesFood** [RPTools/maptool#4163]
### Describe the Bug

I have a few left over macros on old tokens that use a missing asset as an image for the macro.
![chrome_jSUHSB5QoP](https://github.com/RPTools/maptool/assets/45277765/34bf059e-d3bc-4c29-95c8-01b06652a901)

This was fine in 1.12.2 and simply displays a red X to indicate the asset is missing.

In 1.13.1 clicking on the token which contains this macro will freeze Maptool to the point of needing to End Task.
Clicking on the macro without the 'Selected' window, thus never displaying the asset, avoids this behavior.

### To Reproduce

1. Make a new macro and paste `<img height=35 width=35 src=asset://1234567890/>` into the label (this asset does not exist)
2. After clicking apply maptool will lock up if the macro is visible to you

### Expected Behaviour

Return to 1.12 behavior in displaying a missing asset image or text

### MapTool Info

v1.13.1

### Desktop

Windows

**Comment by Pmofmalasia** [comment]
Confirming this is fixed in 1.13.2
