### ISSUE TITLE
[Bug]: CME with fetch API

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4179]
### Describe the Bug

Rarely, using the fetch API from an HTML5 context will result in a ConcurrentModificationException, though the only indication of it is a single line chat message that says `135: java.util.ConcurrentModificationException`.

### To Reproduce

1. Open [this campaign](https://github.com/RPTools/maptool/files/11900468/cme-example.cmpgn.renamed-to.zip)
    - It creates a frame5 that repeatedly makes fetch() calls.
2. Wait
3. Eventually see some `135: java.util.ConcurrentModificationException` in chat.

### Expected Behaviour

The CME should be avoided or handled appropriately, and not be presented to the user via chat.

### MapTool Info

MapTool 1.13.1

### Desktop

Linux Mint 21.1

### Additional Context

I managed to set a breakpoint for the CME and it is being thrown in `MTXMLHttpRequest._getResponseHeaders()`, specifically the `responseHeaders.forEach()` call is being complained about in the `JavaFX Application Thread`.

After some quick digging, I believe we're running into a race between [`MTXMLHttpRequest`](https://github.com/RPTools/maptool/blob/develop/src/main/java/net/rptools/maptool/client/ui/htmlframe/MTXMLHttpRequest.java#L112-L121) and [`RequestHandler`](https://github.com/RPTools/maptool/blob/develop/src/main/java/net/rptools/maptool/model/library/url/RequestHandler.java) which both modify the response headers but on different threads. We're also ignoring the result of `thenApply()`, which allows the two `thenApply()` call to be sequenced in the reverse order that they were called.

**Comment by cwisniew** [comment]
@kwvanderlinde do you want to try this one in your setup with the latest from develop? I ran it to see if I could quickly find the error but it has yet to fail (30+ minutes)

**Comment by kwvanderlinde** [comment]
I have reproduced it on latest develop as well. It's very inconsistent and sometimes it happens lots, other times I can go an hour without seeing it.

**Comment by kwvanderlinde** [comment]
Just found a similar intermittent issue about `statusText`. Didn't get a copy of the error, but I'll include a small change to handle an edge case there as well.
