### ISSUE TITLE
Chinese/Japanese characters are not displaying in Menus

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#419]
**Describe the bug**
Selecting either Chinese or Japanese language in the language selector of the Preferences -> Startup Tab results in the missing character square symbol appearing in the menus and other elements of the GUI.

Works as expected on MacOS.

**To Reproduce**
1. Go to Edit -> Preferences -> Startup 
2. Select either Chinese or Japanese in the Language Override
3. Restart MapTool
4. See screenshots below.

**Expected behavior**
Expect to get menus in the appropriate language.

**Screenshots**
![Screenshot 2019-04-06 12 09 20](https://user-images.githubusercontent.com/34379254/55673406-04624100-5865-11e9-8203-8f2a144af57a.png)

**MapTool Info**
- Version: 1.5.1 (also 1.4.0.5, 1.4.1.8, Nerps 1.4.5.4, 1.5.0)
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Starting MapTool from the command line with:
`java -Duser.language=zh -Duser.country=CN -jar MapTool-1.5.1.jar`
Causes some GUI elements to get the correct information but not all and not the menus.
![Screenshot 2019-04-06 12 19 14](https://user-images.githubusercontent.com/34379254/55673531-5fe0fe80-5866-11e9-9255-6d7645331fd0.png)

**Comment by Azhrei** [comment]
Looks like that's a font issue.  There's some code in `MapTool.main()` that specifically chooses a particular font if the language chosen is Chinese.  I don't remember, but it may be Windows-specific code.  If Windows no longer ships that font, it might cause a symptom like this one, but I would expect some kind of "font not found" error (unless there's a predefined fallback available, in which case maybe the library wouldn't throw an exception?).

**Comment by Azhrei** [comment]
I just checked the zh properties file and the menus all have definitions (using the \uxxxx codes) so the fact they don't show up on Windows is further evidence of a font issue on that platform.

Maybe someone on Windows with the source code installed can try uncommenting lines 1630-1633 of MapTool.java and then try your command line?  There's also some code at ~1690 that tries to install a special font when Locale.CHINA is set.  (It might be interesting to set the language without setting country and see what happens, too.)

**Comment by Phergus** [comment]
Yeah. A lot of this was talked about on Discord.  

The fonts are there as you can see in the second screenshot.  One problem is that the special Locale.CHINA hack is only testing for Chinese locale while the Preferences is only setting user.language in the JVM.  So the hack is bypassed which is why the first screenshot has the missing character symbol in some of the visible GUI elements.  Of course that hack would also be bypassed if the user has there locale set to Japan.

**Comment by Phergus** [comment]
> Maybe someone on Windows with the source code installed can try uncommenting lines 1630-1633 of MapTool.java and then try your command line?

After un-commenting, and then fixing the errors, that merely causes it to crash in an unpleasant manner.
`java.lang.NullPointerException: null
        at javax.swing.plaf.metal.MetalSliderUI.installUI(MetalSliderUI.java:151) ~[?:?]
        at javax.swing.JComponent.setUI(JComponent.java:685) ~[?:?]
        at javax.swing.JSlider.setUI(JSlider.java:316) ~[?:?]
        at net.rptools.maptool.client.ui.assetpanel.AssetPanel.getThumbnailPreviewSlider(AssetPanel.java:288) ~[main/:?]`

**Comment by Azhrei** [comment]
Did you try changing the Locale.CHINA into a getProperty("user.language") and see what effect that has?  I don't know much about the locale vagaries for non-Romanized alphabets...

**Comment by Phergus** [comment]
Rather than that I just forced it to always load the font (same as launching it with -Duser.country=CN).  This has the effect seen in the second screenshot.   It appears to be an issue with code that localizes the menus.  Perhaps a different font is being chosen there.  Didn't really have time to chase that down.

**Comment by Azhrei** [comment]
Okay.  Next step will probably be to breakpoint that loop (line ~1690) and see what keys are being iterated over (or just print them out inside the loop).  Then we can look at them to see if he menu fonts are being set.  I can do the same thing on macOS and see what the list prints out.

**Comment by lesser0** [comment]
On my computer (win 10), maptool 1.4.1.8 which I downloaded from rptools website on 2018/7/19 doesn't have this issue, but current 1.4.1.8 has. What is the difference between these?

**Comment by Phergus** [comment]
Is the earlier download an installer (.exe) version?  Are they different in size?

**Comment by lesser0** [comment]
> 
> 
> Is the earlier download an installer (.exe) version? Are they different in size?

The earlier one is a zip including jar and other files.

**Comment by lesser0** [comment]
> 
> 
> Is the earlier download an installer (.exe) version? Are they different in size?

The earlier one:
https://send.firefox.com/download/b0ed9df52064a1a5/#VZhyYMrvmXls8YWwqRzFbg

**Comment by Phergus** [comment]
So the issue is related to the default.theme that is loaded by the look-and-feel manager, TinyLaF.  It calls out the Tahoma font which isn't complete.  Starting up MT with a theme that specifies SansSerif for the font and those UI elements with translations in Chinese and Japanese show correctly.

This zip contains the default theme with the SansSerif font selected.  Extract and then rename them file to `Default.theme` and place in one of the [locations for themes](https://github.com/RPTools/maptool/wiki/Themes-for-MapTool).

[DefaultWithSanSerif.zip](https://github.com/RPTools/maptool/files/3865097/DefaultWithSanSerif.zip)

**Comment by Phergus** [comment]
As a fix for this seems to be to use a theme that doesn't call out a font missing the characters, I'm considering this closed.
