### ISSUE TITLE
[Bug]: Square brackets in macro button tooltip prompts for a value on hover, edit, or run

### ISSUE THREAD

**Issue by Baaaaaz** [RPTools/maptool#4194]
### Describe the Bug

If you include some pure text in square brackets in a macro button tooltip e.g. "[a]", it will prompt for a value for "a" when either:
- hovering over the macro button, and sometimes when editing the macro.
- also, if the macro has been created as a function, this prompt can also occur when editing or running a macro that calls or even defines that function.

If after hovering and you press Okay on the keyboard to accept the prompted value (e.g. 0) the tooltip displays some equation with replacement characters "□□□a = 0□0□"

If some pure number" is used e.g. "[1]", or some text which starts with a number" e.g. [1a] then it does not prompt for a value but the label shows some equation and replacement characters.

Workaround is to wrap the macro button tooptip text in \<html\> tags

### To Reproduce

**Macro Scenario**
1. Create new token (e.g. "Add")
2. Add a new macro on token (e.g. default name "(new)")
3. Add "[a]" to the tooltip
4. Save macro
5. Either: 
i. Hover over the "(new)" button and before displaying the tooltip it with prompt for a value for "a"
ii. Or if quick enough left click to show the context menu without triggering the tooltip, then Edit macro to see prompt before opening the macro editor.

**Function Scenario**
6. Go through steps 1-4 above
7. Convert token to library token (append Lib: to token name)
8. Create a new macro named "defineFunctions" that defines the above macro as a user defined function (e.g. `[defineFunction("thisError","(new)@this"),0,1)]`)
9. Create a macro named "callFunctions" that calls the defined function (e.g. `[thisError(0)]`)
10. When running or editing the callFunctions macro we are prompted for a value for "a"
11. When editing the defineFunctions macro we are prompted for a value for "a"

### Expected Behaviour

If square brackets are used in the tooltip, MapTool should not prompt for a value in either macro or function scenarios and display the tooltip as written, not an equation or with replacement characters.

### Screenshots
![image](https://github.com/RPTools/maptool/assets/131240480/1436532c-155e-475f-a19e-84711b01959e)

### MapTool Info

1.12.2 and 1.31.rc2

### Desktop

Windows

**Comment by Pmofmalasia** [comment]
This is, working as intended - the square brackets indicate that you're trying to run MTScript code.

**Comment by Baaaaaz** [comment]
Thanks and fair enough!  This is new to me and could not find anything related in the wiki about the macro editor tooltip interface.   Following your comment I just did some more digging and found the following line under the [createMacro() function](https://wiki.rptools.info/index.php/createMacro).  

"`tooltip` - The tooltip for the macro button. Tooltips that start with `{` or `[` will be treated as MTscript and executed with the result being used as the content of the tooltip. To embed formatting (bold, italics, etc), ensure that the content of the tooltip ends up starting with `<html>` and contains the HTML3.2 content that produces your desired result."

That info seems a bit buried as I was not scripting creating a macro (I have not had the need/reached that level yet! ;)
