### ISSUE TITLE
[Bug 1.13.1]: Auras inside solid VBL crashes MapTool

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#4203]
### Describe the Bug

Any token with an aura that is moved inside solid vbl causes a render error and the only thing you can do is close MapTool.

Bug discussion: https://forums.rptools.net/viewtopic.php?p=280181#p280174
Included campaign (not needed) and a video (requires log-in to MS) but I converted to mp4 and attached to report.

### To Reproduce

- Open a new campaign. 
- Draw a solid block of VBL. 
- Drop a token outside of block.
- Add an aura to campaign. Edit | Campaign Properties | Light - scroll down copy first aura example and paste in to lights above.
- Turn aura on for token.
- Move token in to solid VBL area
- ERROR. 

### Expected Behaviour

No error expected.

### Screenshots

https://github.com/RPTools/maptool/assets/43827071/91e5af1c-91aa-4b88-92f2-28a3ba5a41db

### MapTool Info

1.13.1

### Desktop

Windows 11

**Comment by aliasmask** [comment]
Fixed in 1.13.2. Should be closed.

**Comment by pizzystrizzy** [comment]
> Fixed in 1.13.2. Should be closed.

What? This is very much not fixed in 1.13.2

**Comment by aliasmask** [comment]
Sorry, got my versions and tickets mixed up. This is fixed in 1.14.0 alpha which hasn't been officially released yet.
