### ISSUE TITLE
[Bug]: ConnectionInfoDialog does not show the active interface

### ISSUE THREAD

**Issue by PeterPeet** [RPTools/maptool#4206]
### Describe the Bug

If there are more then one networkinterface on the local machine, the ConnectionInfoDialog does not show the active interface, but the last one.

### To Reproduce

Goto serverinformation while having more then one ethernet interface while the first interface is active.

### Expected Behaviour

You will get the local address of the last interface.

### MapTool Info

1.13.2

### Desktop

Windows10

**Comment by kwvanderlinde** [comment]
Tested this by bringing different combinations of interfaces up or down.

It appears to be working. If I get one IP address from an interface, then bring that interface down and restart MapTool, I get a different address. Complete verification is hampered by the bug I [mentioned in the sister issue](https://github.com/RPTools/maptool/issues/4207#issuecomment-1787182773), but things appear to be in order for this issue.

An edge case is what happens with all interfaces down. In that case no local address is displayed, not even a loopback, while on 1.13.2 and earlier a loopback would be shown. I wonder if we should still allow lookbacks to be shown in this case? It's certainly very niche, though there are folks who run multiple MT instances on a single PC and may be still benefit from being shown a lookback address.
