### ISSUE TITLE
[Feature]: Safer Installation/Updating.

### ISSUE THREAD

**Issue by FullBleed** [RPTools/maptool#4209]
### Describe the Problem

1)  When installing MT it defaults to installing over the previous version/location.  If the previous version is not removed first, this causes problems with the install.  The previous version at the default location needs to be Uninstalled first.

2)  When Uninstalling MT, everything in the install directory is destroyed.  This causes data loss for users who think the installation directory is safe.

The existing guardrails are not sufficient (as noted by the number of issues people have with failed "Updates" and/or destroying their data.)

I know that some of these issues have been discussed and are the result of limitations of the packaging software, but I hope that more can be done to address the problems.  These issues are fairly common pain-points for new users and do not reflect how most software updates and uninstalls and done.  Please suggest alternatives or more viable solutions if you have them.

### The Solution you'd like

A)  The default installation directory should be based on the name of the MT Version.  This would incentivize new installs to be done in a safer location.

B)  If possible, disallow installation over an existing MT install location.  If that's not possible, perhaps provide a Warning at installation that if an existing version of MT exists at the installation location that it needs to be Uninstalled first (and that the Uninstall will destroy data in the directory.)  People often click through installation instructions believing most of the text to be boilerplate, but warnings at the point of install should be more effective than expecting users to read the readme or release notes. 

C)  If possible, disallow saving any MT specific file (campaign, table, rptok, macroset, etc.) to anywhere in the install directory and inform people during the attempt that they are attempting to save to an Unsafe Location that will be erased when MT is uninstalled.  If the save can't be disallowed, a Warning would be better than nothing.

D)  If possible, have a warning at Uninstall to inform users that all data/assets saved in the install location will be deleted.

### Alternatives that you've considered.

If there is a packaging option that provides either non-destructive uninstalls or more seamless updates over existing installs, then that would be preferable.

If none of the better guardrails mentioned above can be done, perhaps a notice on first run explaining these two issues could be added.  (i.e." "Do not save data to the Maptool Installation Directory."  "Before Updating, Uninstall the previous version of MT.  Please note that this will destroy all data saved in the Maptool Installation Directory.  Do not save data to the Maptool Installation Directory.")

A warning about the perils of Updating at the point of the notice of a new available version could also be displayed:  "There is a new version of MT available.  Before Updating:  1) Make sure that you have not installed any data to the Installation Directory.  If you have--Move It Now.  2) You will need to Uninstall previous versions of MT if you are going to install the update to the same location.  This will result in the destruction of all data you may have saved in that directory.  If you have--Move It Now."

**Comment by bubblobill** [comment]
I'm assuming people run into this issue by saving their data to a default location which is the same as the install location. If so it would be a benefit to change the default save location to somewhere safer, e.g. My Docs on Windows.

**Comment by kwvanderlinde** [comment]
Tested - saving to the installation directory or any child directory is now forbidden and comes with an explanatory dialog. Related issues have been addressed separately.

This should be enough to avoid the issue going forward, and users with existing saves in their installation dir will at least be warned about the situation. New FRs can be opened if there are further enhancements to consider.
