### ISSUE TITLE
Macro auto completion does not show function description if you typed too much

### ISSUE THREAD

**Issue by source-knights** [RPTools/maptool#424]
When the existing text before using CTRL-space is already resulting in a single function no description is shown.

But quite often macro devs want to check the description even for existing code which would have full functions names in it already.

E.g. if you type in the macro editor "abo" and hit CTRL-space it will just auto complete the text to "abort". Not showing any description. I like to change it (quite easy, just one line in code) to do that but also show the description in the usual completion popup. e.g. if you would just have typed "a" and hit CTRL-space

With this feature y you can get function description even if you already typed "too much" of the function name or all of it

**Comment by oliver-szymanski** [comment]
Fix in https://github.com/RPTools/maptool/pull/425

**Comment by JamzTheMan** [comment]
Welcomed addition. As another issue, remembering the this help windows size would help.
