### ISSUE TITLE
[Bug]: copy/paste token forgets stat-sheet settings

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#4240]
### Describe the Bug

Copying and pasting a token with the config options set to show a particular stat-sheet results in the token reverting to the default stat-sheet

### To Reproduce

set a token's stat-sheet config
copy and paste it

### Expected Behaviour

retention of all settings

### MapTool Info

1.14.a3

### Desktop

win10

**Comment by FullBleed** [comment]
Assuming this is with the context menu and keyboard copy/paste?

Should check if this is an issue with copyToken() and the moveToken functions, too.

**Comment by kwvanderlinde** [comment]
Tested on 1.14.0-rc.4. Pasted tokens retain their configured stat sheet,  regardless of whether they were copied or pasted via keyboard or right-click menu. Also verified that the macro functions `copyToken()`, `moveTokenFromMap()`, and `moveTokenToMap()`  also keep the configured stat sheet on the token.
