### ISSUE TITLE
[Bug]: New stat sheets have lots of blue flickering

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4241]
### Describe the Bug

When using the new templated stat sheets, a blue flicker regular appears when the stat sheet opens.

### To Reproduce

1. Open this campaign: [stat-sheet-1.14-with-flicker.cmpgn.renamed-to.zip](https://github.com/RPTools/maptool/files/12337180/stat-sheet-1.14-with-flicker.cmpgn.renamed-to.zip).
2. Hover over the token to show the stat sheet (hover+shift depending on preferences)
3. Observe a blue flicker as the sheet opens.
    - If it didn't show, try again, it might not be 100% of the time

### Expected Behaviour

The stat sheet is rendered with no flickering.

### MapTool Info

develop (2229ec557)

### Desktop

Linux Mint 21.1

### Additional Context

The same issue impacts overlays, but stats sheets seem to suffer from this problem more consistently (at least for me).

**Comment by cwisniew** [comment]
ugh accidental closure, I have reopened

**Comment by Jmr3366** [comment]
I've been testing my overlay heavy campaign with the new stat sheets on 1.14.0rc2 and I have not seen any form of blue or other anomalous flashing. Tested on Win10 and Win11 systems.
