### ISSUE TITLE
[Bug]: Gradle 8.1 does not completely support Java 20 leading to build failures with certain configurations

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#4251]
### Describe the Bug

Gradle 8.1 does not completely support java 20 (you can compile Java 20 code but you can also encounter errors if you try to use java 20 to run the build process).

Building generally works, but if you make changes to the .proto files depending on your set up you may get a message saying that java 20 is not supported in gradle 8.1.

### To Reproduce

It might be harder to reproduce than avoid

### Expected Behaviour

It should just work

### MapTool Info

1.14.x 

### Desktop

Seen it on windows only but cant rule out other OS as well

**Comment by kwvanderlinde** [comment]
The thing I usually run into is the spotless check failing. In that case, I just get shown the error about having the wrong Java version. But if the check passes, everything works with no mention of a bad Java version. It's quite odd.

**Comment by cwisniew** [comment]
> The thing I usually run into is the spotless check failing. In that case, I just get shown the error about having the wrong Java version. But if the check passes, everything works with no mention of a bad Java version. It's quite odd.

Hmmm I just checked that, I have modified my IDE arguments so run is "spotlessApply run" so wasn't running into it (yes I was tired of having to do another commit for spotless fixes :) ).  Its still an issue with 8.2, probably something we have to look at spotless for.
