### ISSUE TITLE
Line Template based on Cell

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#426]
**Is your feature request related to a problem? Please describe.**
Templates should be based on either Grid intersections or start from a Cell to support more game systems. The common templates are Radius, Line, & Cone. Radius now supports both, propose to add Line as well now.

**Describe the solution you'd like**
Pull Request #414 adds the solution to draw the line template starting from a cell. A new "button" will need to be added to the Toolbar to draw the new template which matches current functionality of other template uses/design.

**Describe alternatives you've considered**
New tool bar to split Intersection vs Cell based templates but there are only a couple.
Hot key to toggle while drawing but to many hot keys already exists and this hide the functionality to new users.

**Additional context**

**Comment by Phergus** [comment]
Showing _tool.LineCellTemplate.instructions_ in status bar.

**Comment by Phergus** [comment]
Finished with PR #465
