### ISSUE TITLE
[Feature]: Set default starting map when connecting to a server

### ISSUE THREAD

**Issue by StefanoMarina** [RPTools/maptool#4281]
### Describe the Problem

When I start a server, the starting map seems to be random. Sometimes is the map we are on, sometimes is another map, sometimes I am fixing a token in a map then a player connects and appear on that map. There is no "official way" to control this, it seems.

### The Solution you'd like

A simple checkbox: "start here when hosting" for a map, or a campaign property "starting map". 

### Alternatives that you've considered.

This is achievable by creating a `onCampaignLoad` with a Lib:Token, however changing the map during such times creates issues with `getMacroLocation()` , a macro I call on other Lib:Tokens' `onCampaignLoad` events to define external functions.

**Comment by thelsing** [comment]
Duplicate to #75
