### ISSUE TITLE
Get and Set Terrain Modifier Function for a Token

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#429]
**Is your feature request related to a problem? Please describe.**
A user is attempting to update the terrain modifier on a large number of tokens. 
 
**Describe the solution you'd like**
An MTScript function to get and set the terrain modifier for a token.

**Describe alternatives you've considered**
Doing them all by hand.

**Additional context**
Request from Facebook community member Claus R.

**Comment by rkathey** [comment]
I can see this being useful for game systems that disallow passthrough movement on existing campaigns.

**Comment by JamzTheMan** [comment]
Agreed and a simple function to create. I've marked it up for grabs.

Shall we document a function name and parameters here in case someone wants to claim it?

**Comment by rkathey** [comment]
My cut at it would be 
getTokenTerrainModifier(id)
setTokenTerrainModifier(id)
With id being optional if there is a selected token.

I could see losing the Token part of the name unless we will have a similar function for drawings.

**Comment by Phergus** [comment]
Functions added to Wiki:
http://www.lmwcs.com/rptools/wiki/setTerrainModifier
http://www.lmwcs.com/rptools/wiki/getTerrainModifier
