### ISSUE TITLE
[Bug]: Inconsistent wording in the UI

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#4292]
### Describe the Bug

As reported by **Baaaaz** on [Discord](https://discord.com/channels/296230822262865920/400513604602036234/1152645507865378957):
> The map "Grid Size" under [Map -> Adjust Grid...] seems to be the the same as "Pixels per Cell" under [Map -> Edit Map -> Map Properties] (or when creating a new map via [Map - New Map...]) as changing one changes the other - despite the different names!
>
> https://wiki.rptools.info/index.php/Introduction_to_Mapping#Creating_a_Map states:
> "**Pixels per cell:** this is how many pixels each cell should cover – the default is 100. This is most important for scaling any map images you intend to use."
>
> Therefore I would assume this statement also applies to Grid Size ( could not locate a wiki entry about grids - but there are some youtubes that cover changing them).

### To Reproduce

Open MapTool and look at:

**Map > New Map...** vs.
**Map > Edit Map...** vs.
**Map > Adjust Grid...**.

### Expected Behaviour

The user interface should use the same terminology in any situation where the same values are being discussed.  Or maybe these are not same values?  In that case, the wiki needs updating to clarify the use and differences between the two fields.

### MapTool Info

1.13.2 (and earlier)

### Desktop

Any

**Comment by bubblobill** [comment]
You missed one from preferences
**New Map Grid Size**

**Comment by bubblobill** [comment]
For future reference. 
There is gridSize in the menu which is line thickness. Going to refactor to lineWeight or something handier. 
Other Grid Sizes are grid cell size in pixels. Will refactor to remove ambiguity and edit labels/tooltips to reflect each other.
