### ISSUE TITLE
[Bug]: Changing name of single property type causes exceptions continously

### ISSUE THREAD

**Issue by eldritch-cookie** [RPTools/maptool#4293]
### Describe the Bug

when there is only one property type changing its name causes an exception, additionally an exception is generated multiple times per second if there are any tokens on the map

### To Reproduce

1. Create new campaign
2. Open campaign properties
3. Change name from Basic to anything else
4. Click Ok to confirm
5. If this is reproducible an exception has been generated 
6. Add a token to the map to generate exceptions continuosly

### Expected Behaviour

it should change the name without problems like it happens when i change the name of the default when there are multiple properties

### MapTool Info

Version:1.14 alpha3 installed with the pkg.tar.zst

### Desktop

Linux: NixOS unstable 23.11

**Comment by kwvanderlinde** [comment]
Tested on 1.14.0-rc.4. Able to rename property types without issue regardless of number, with or without tokens in the campaign.
