### ISSUE TITLE
[Bug]: if() parsing error

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#4312]
### Describe the Bug

`[if(1,"a!","")]`
Generates this error `Function 'if' requires exactly 3 parameters; 2 were provided.`
Seemingly if `a` is aA-zZ will cause the failure

### To Reproduce

`[if(1,"a!","")]`
in chat

### Expected Behaviour

No failure and `a!` should output to chat.

### MapTool Info

v1.14.0.rc1

### Desktop

win11

**Comment by kwvanderlinde** [comment]
Tested. Can now freely use letters and `!` in strings without parse errors.
