### ISSUE TITLE
[Bug]: The check to disable load/save from install directory is using parent directory of the install

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#4330]
### Describe the Bug

The check to ensure that you can not save to / load from the install directory is actually checking the parent directory of the install so if for example someone installed into MyDocuments/MapTool, they would not be able to save to MyDocuments/campaigns... 

### To Reproduce

Try to save into the parent directory (or any subdirectory of the parent directory) of MapTool install.

### Expected Behaviour

This should only preclude saving/loading from the install directory and subdirectories of install directory.

### MapTool Info

MapTool 1.14.0-rc.2

### Desktop

Any

**Comment by kwvanderlinde** [comment]
Tested - saving to parent of the installation directory is now possible.
