### ISSUE TITLE
Minimized frame doesn't retain title

### ISSUE THREAD

**Issue by kayila** [RPTools/maptool#434]
**Describe the bug**
If a frame has a title, where the title is different from the frame id, the pinned and minimized tab name reflects the frame ID rather than the title of the frame.

**To Reproduce**
1. Create a macro with the following code:
```
[frame("abcde"): {
<html>
<head><title>Some title</title></head>
<body>Thing</body>
</html>
}]
```
2. Run the macro, observe the created title of the frame.
3. Pin the frame to the side of the MT window
4. Hide the frame, notice that the 'name' of the tab does not reflect the title of the frame.

**Expected behavior**
Minimized frames will keep the same title as when they are opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/925235/56086230-1bce9a80-5e20-11e9-929b-bd661b569e82.png)
![image](https://user-images.githubusercontent.com/925235/56086234-25f09900-5e20-11e9-8294-59b58aa40fc9.png)
![image](https://user-images.githubusercontent.com/925235/56086235-2b4de380-5e20-11e9-8aca-2672cbe76a2b.png)

**MapTool Info**
- Version: 1.5.1
- Install: All

**Desktop (please complete the following information):**
 - OS: Windows, Linux

**Comment by Merudo** [comment]
Could this be an issue with the Jide docking framework?

**Comment by Phergus** [comment]
Seems likely.  Does MT even have code for handling hiding/minimizing of frames?  Thought that was all done by JIDE.

**Comment by Azhrei** [comment]
There may be a call into the JIDE API that allows setting the text that should appear when the panel isn't being displayed and we're probably not calling it.  Or maybe when calling `setTitle()` (or whatever JIDE calls it) there's a second parameter that we're not passing.

It does seem like something that the application should be able to specify...

**Comment by Merudo** [comment]
I found out in the documentation, that setTabTitle(String) needs to be called separately.

Should we have tabTitle as another parameter or should we have tabTitle=title everywhere?

**Comment by Azhrei** [comment]
I'd go with making them the same.  The only issue is that the "tabTitle" should probably be a much shorter string...

**Comment by Merudo** [comment]
My PR #602 implements the following behavior:

- The <title> tag sets both the title and the tabtitle to a value
- By default, a frame will have the same tabbed title as its title
- A new parameter tabtitle is added to frame(). By specifying this and not using <title>, a frame can have a tabbed title different from its actual title

Seems to me like a reasonable compromise between simplicity and flexibility.

**Comment by Merudo** [comment]
Documentation added to https://lmwcs.com/rptools/wiki/frame_(roll_option)

**Comment by Phergus** [comment]
Tested with original macro and with new functionality.  Working as described.
