### ISSUE TITLE
[Feature]: Add macro functions to control the Lock Player Movement option

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4340]
### Describe the Problem

The _Tool > Lock Player Movement_ option is not remembered between MapTool instances. This make it tedious to run a campaign it needs to be remembered and applied manually each time MapTool is started.

### The Solution you'd like

Two new macro functions to control the setting:
- `setMoveLock(true/false)`
- `getMoveLock()`

### Additional Context

I'm adding this retroactively for PR #3951 as it isn't backed by an GH issue.

**Comment by FullBleed** [comment]
Thanks for this... it has always been a bother.

**Comment by kwvanderlinde** [comment]
Thank @Jmr3366!

**Comment by FullBleed** [comment]
> Thank @Jmr3366!

Thanks @Jmr3366!   Thrilled that you're hitting the core code base lately.  :)

**Comment by kwvanderlinde** [comment]
Tested. Calling `setMoveLock(true)` toggles the "Lock Player Movement" option on, and calling `setMoveLock(false)` toggles it back off. The option is synced to clients, and the menu can still be used even if the macro functions have already set it one way or the other.

`getMoveLock()` returns the current client state whether set by menu or macro function.
