### ISSUE TITLE
[Feature]: English localisation not present for non US English

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#4344]
### Describe the Problem

English localisation is not available for non-US speakers

### The Solution you'd like

English translation files should be available for different regions

**Comment by Phergus** [comment]
Wrong.  The MapTool project language is US English.  If you want it localized to the UK create a en_gb (or au or nz or ...) i18n file.

**Comment by bubblobill** [comment]
Okies, I can't see/didn't notice that. Easily enough rectified. Will change FR to add en_au, en_gb.

**Comment by bubblobill** [comment]
Crowdin integration not returning dialect files properly
