### ISSUE TITLE
[Bug]: Inconsistent tooltips for "diamond" / "isometric rectangle" tools

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4352]
### Describe the Bug

The topology tools were [recently updated](https://github.com/RPTools/maptool/issues/4027) to use the term "isometric rectangle" for the diamond-shaped tools. Meanwhile the analogous drawing tool and FoW tool still use the term "diamond" where "isometric rectangle" would be more appropriate.

### To Reproduce

Hover over the rightmost drawing tool and see the tooltip:
> Draw a _diamond_.

Hover over the rightmost FoW tool and see the tooltip
> Expose/Hide a _diamond_ on the Fog of War.

### Expected Behaviour

The cases above should read:
> Draw an _isometric rectangle_.

and

> Expose/Hide an _isometric rectangle_ on the Fog of War.

### MapTool Info

MapTool 1.14.0-rc.4

### Desktop

Linux Mint 21.2

**Comment by Baaaaaz** [comment]
Tried testing in 1.15.0 Beta 1 and could see the tooltip changes from "diamond" to "isometric rectangle".  So a pass from me.

**Comment by kwvanderlinde** [comment]
Thanks for testing this @Baaaaaz!
