### ISSUE TITLE
[Bug]: Non-standard wording for topology types in Edit Token dialog

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4353]
### Describe the Bug

In the **Edit Token** dialog, *Topology* tab, the various toggle buttons in the top row have tooltips that don't use standard terminology for the topology types. This can lead to confusion (and has in the past).

Here are the current tooltips for these buttons.

For Wall VBL:
> Include Wall Blocking Layer (VBL) during move or copy

For Hill VBL:
> Include Hill Blocking Layer (HillVBL) during move or copy

For Pit VBL:
> Include Pit Blocking Layer (PitVBL) during move or copy

For MBL:
> Include Move Blocking Layer (MBL) during move or copy

### To Reproduce

Edit a token, go to the _Topology_ tab, and hover over each of the toggle buttons in the top row.

### Expected Behaviour

The following (or similar) phrasing should be used.

For Wall VBL:
> Include Wall _Vision_ Blocking Layer (_Wall_ VBL) during move or copy

For Hill VBL:
> Include Hill _Vision_ Blocking Layer (Hill VBL) during move or copy

For Pit VBL:
> Include Pit _Vision_ Blocking Layer (Pit VBL) during move or copy

For MBL:
> Include _Movement_ Blocking Layer (MBL) during move or copy

### MapTool Info

MapTool 1.14.0-rc.4

### Desktop

Linux Mint 21.2

### Additional Context

Similar tooltips are present on the toplogy tools in the main toolbar, but they just use the terms Wall VBL, Hill VBL, Pit VBL, and MBL without expanding them. It could be worth aligning these tooltips with the more descriptive tooltips that are now in the **Edit Token** dialog.

**Comment by Baaaaaz** [comment]
Tested in 1.15.0 Beta 1 and could see all four tooltip changes.  So a pass from me!

**Comment by kwvanderlinde** [comment]
Thank you very much @Baaaaaz!
