### ISSUE TITLE
[Feature]: Rename the "Token" group in the Map Explorer

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4360]
### Describe the Problem

The group name "Tokens" in the Map Explorer suggests that anything on the Token layer could be included there. But it's actually restricted to _NPCs_ on the Token layer, with any PCs being put in the "Players" group instead.

### The Solution you'd like

The "Tokens" group would be renamed to "NPCs".

**Comment by Baaaaaz** [comment]
Tested in 1.15.0 and "Tokens" group in map explorer now shows as "NPCs", and handles token allocations to different layers.  That's a pass from me :)

**Comment by kwvanderlinde** [comment]
Thanks @Baaaaaz!
