### ISSUE TITLE
[Question]: Can't Build MapTool

### ISSUE THREAD

**Issue by drcxd** [RPTools/maptool#4364]
### Your Question

I try to build MapTool following the instructions found here: https://github.com/RPTools/maptool/wiki/Contributor-Setup-Instructions-For-MapTool

but when I execute `gradlew run`, I get the following error:

```
PS D:\workplace\maptool> .\gradlew run

> Configure project :
Project : => no module-info.java found
Configuring for MapTool-Dev-Release SNAPSHOT-ec86070 by RPTools
AppVersion: 0.0.1
OS Detected: windows
Setting Windows installer options with upgrade uuid = 49946bb6-4c79-4500-9036-1a97043041eb

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: invalid source release: 20

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scrip
ts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warn
ings in the Gradle documentation.

BUILD FAILED in 7s
5 actionable tasks: 2 executed, 3 up-to-date
```

Here is my project setup, I have double-checked it with the instructions:

![setting](https://github.com/RPTools/maptool/assets/24535087/fdbaa8d6-99e4-4733-ad62-f38e0d60b859)

![ps](https://github.com/RPTools/maptool/assets/24535087/a73c9d39-56ec-410a-bc4c-5445e1a08e9d)

I am new to Java development; can you help me?

**Comment by thelsing** [comment]
You need an java 20 sdk to build maptool. The docs are not up to date. This is my setup, other java 20 jdks work too:
<img width="777" alt="image" src="https://github.com/RPTools/maptool/assets/20617946/fadf21c3-1906-4032-8084-a2204e65b28b">
