### ISSUE TITLE
[Bug]: Resizing snap-to-grid free size stamps drastically increases the token size

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4365]
### Describe the Bug

When dragging to resize a snap-to-grid and free size token, moving the pointer even one pixel will double the size of the token. After that resizing is smooth. But the next time I try to resize the same thing will happen.

### To Reproduce

1. Open a new campaign.
2. Add a token to the Object layer, enabling _Snap to Grid_ and setting the size to _Free Size_
3. Attempt to resize the token.
4. Notice a sharp increase in the token's size.

### Expected Behaviour

The token should be resized in keeping with the movement of the pointer. There should be no sudden changes in size if the pointer is not being moved sharply.

### Screenshots

At the start of the resize drag:
![image](https://github.com/RPTools/maptool/assets/7492219/bbdc5050-7799-4852-967d-8a9cee379f74)

After moving the pointer just one pixel:
![image](https://github.com/RPTools/maptool/assets/7492219/2e43c242-cc45-435f-a515-2b956dc7b3a2)

### MapTool Info

1.13.2

### Desktop

Linux Mint 21.2

**Comment by Jmr3366** [comment]
Along this same vein, if the token is rotated at all and you resize, it will unsnap and resizing "as wanted" is impossible.

https://github.com/RPTools/maptool/assets/100969108/08da1a93-8ac5-459a-8058-a3ee37795be9
