### ISSUE TITLE
[Bug]: setLight seems additive

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#4376]
### Describe the Bug

When using the menu to select lights, it behaves as a toggle.
When using the `setLight` function to set a light, the light adds on top of itself.

### To Reproduce

Campaign or video
[Test.cmpgn.zip](https://github.com/RPTools/maptool/files/13258182/Test.cmpgn.zip)

https://github.com/RPTools/maptool/assets/100969108/cc0d6ac4-31c4-4a0f-8b20-1319015c86bd

### Expected Behaviour

Not to add the light again if it's already there.

### MapTool Info

1.12-1.14rc

### Desktop

Win 11

**Comment by kwvanderlinde** [comment]
For lights proper I can only reproduce this on 1.12 and no later. On 1.13.2 (and later presumably), it just seems to apply to auras.

**Comment by kwvanderlinde** [comment]
Correction, both lights and auras can be added multiple times. But something in how we render lights masks the issue for them but not for auras.
