### ISSUE TITLE
[Question]: Integers keep ruining my stuff, can we refactor them out of most classes without breaking things?

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#4395]
### Your Question

Integers are smaller and their mathematical operations are faster. Understand that.

I have a map, which is an integer size, with an integer unit scale, which is arbitrary, which is scaled to the viewport by a real number, to an integer number of pixels, which are rendered according to mysterious graphics operations like bi-cubic anti-aliasing.

I place a token on this map. The token has a scale, which is a real number, the image has been zoomed by a real number, its image has been offset by integer values in the x & y axes, and it is presented after being fractionally scaled in line with the map. I move the token and set waypoints at arbitrary distances and arbitrary angles. Each step is reduced to an integer location with a non-integer distance.

Cells have integer co-ordinates. This makes sense.
The viewport has an integer number of pixels(probably). This makes sense.
Everything else is a ratio, except that it's not, and it keeps screwing up my stuff.
Examples: CellPoints & ZonePoints & possibly ScreenPoints should not be integer values.

The code is littered with odd comments and functions that are trying to deal with or get around rounding errors.

Can we redefine most of the not-really integer fields to in the core classes to doubles without caning performance?

**Comment by cwisniew** [comment]
Generally, yes, the only thing to look out for is where any of the things you want to change are persisted. 
If you have a list of what you would like to change we can go through it to see if there are concerns.

From a performance point of view, I am not overly concerned with integer vs float/double until we see a significant performance decrease, and if we see it then we can address it only where needed. There are just way too many things to consider before being able to say integers will lead to a large performance improvement.
