### ISSUE TITLE
1-1-1 Movement Looks Bad

### ISSUE THREAD

**Issue by dorpond** [RPTools/maptool#442]
When moving tokens X, Y or -X, -Y, movement looks terrible, but looks fine when moving X, -Y or -X, Y

Jamz, this started once you originally created the AI movement stuff in Nerp’s. I noticed it was still the case in the official MT 1.5.1 version so I thought I’d mention it. It wasn’t until recently that I narrowed it down to movement metric.

**To Reproduce**
Just open Maptool, ensure the movement metric is set to One_One_One In preferences, drop a token on the map, and move it is all 4 directions. You’ll see.

**Expected behavior**
Make it look like it always used to look - like it does when moving X, -Y or -X, Y.

**Screenshots**

![Movement](https://user-images.githubusercontent.com/31480384/56224436-a17b6180-603d-11e9-973a-88dde7b67308.jpg)

**MapTool Info**
- Version: Nerp’s 1.4.5.3 and MT 1.5.1
- Install: All In one EXE version.

** Desktop**
Windows 10 1809

**Comment by Phergus** [comment]
I think you have that backwards.  It behaves correctly when moving -X,-Y and +X,+Y.  It's moving up-and-right - as your image shows - or down-and-left.

**Comment by dorpond** [comment]
Let's try this again then, when moving NE or SW, it looks wonky, like the photo shows. This is how it should look below. Notice how nice it looks when going SE. That is expected.

![20190416_150716418_iOS](https://user-images.githubusercontent.com/31480384/56233274-b9101580-6050-11e9-918f-a1783b64eae5.jpg)

**Comment by dorpond** [comment]
Ugh, it rotated my image CC...

**Comment by Phergus** [comment]
Fix is part of 1.5.3-rc3.  Closing.
