### ISSUE TITLE
[Bug]: Cover VBL Island Edge Case

### ISSUE THREAD

**Issue by ColdAnkles** [RPTools/maptool#4437]
### Describe the Bug

Took this for a spin, there's one edge case that is not working as I would expect: a token in cover will have its vision blocked by the opposite side of an enclosed ocean (hole):
![image](https://github.com/RPTools/maptool/assets/7492219/aacbb1a4-958a-4468-be64-12fd47bc4c2c)

Compare with the case where the "hole" is not completely enclosed, then vision is not obstructed at all:
![image](https://github.com/RPTools/maptool/assets/7492219/2d7325ed-c126-4a85-90bc-990d037edd32)

I would expect the first case to also not block vision either.

_Originally posted by @kwvanderlinde in https://github.com/RPTools/maptool/issues/4299#issuecomment-1813958136_
            

### To Reproduce

Create an island of cover VBL like so:
![image](https://github.com/RPTools/maptool/assets/7492219/2d7325ed-c126-4a85-90bc-990d037edd32)

### Expected Behaviour

The far side of the cover should be blocking vision - be unable to see back into itself

**Comment by kwvanderlinde** [comment]
My quoted comment actually stated the opposite expected behvaiour: if a token is in an island of Cover VBL, the island should not block its vision.

I have in mind Hill VBL, which is the only other VBL case where LOS can start in an island, cross an ocean, and then encounter the same island. For Hill VBL, the second encounter is treated the same as the first, i.e., no blocking is applied. I think it should be the same for Cover VBL.

But I'm open to having my mind changed :smile:  Maybe Hill VBL is in the wrong here ...

**Comment by ColdAnkles** [comment]
I see it as you're in a shrubbery that you can see out of - but that can't be seen into. If it's a hedge shaped shrubbery and you're looking across an open area to the other end of the hedge, you shouldn't be able to see back into it. Something like the leaves form a one-way view inhibitor, and the branches and so on inside let you see whats going on normally.

I think Hill is fine, without some fancier raycasting or elevation systems - if you're on a hill, you can see the tops of all other hills at the same height - should really block at the back edge if and only if a ray cast passes over the front edge first - no idea if even possible with how it's done in Maptool.

**Comment by kwvanderlinde** [comment]
Tested on 1.15.0-rc.2. Behaving as expected - it is no longer possible to see back into Cover VBL.
