### ISSUE TITLE
Halo function behavior with native sized tokens on isometric map

### ISSUE THREAD

**Issue by nemafow** [RPTools/maptool#450]
**Describe the bug**
Halo 'highlight box' is applied to an incorrect grid coordinate when used on a native sized token on an isometric map, it is centered on the token (not the cell the token is standing on) and to its right.

**To Reproduce**
1. Create an isometric map of appropriate size (I use distance per cell:1, pixels per cell: 20)
2. Add an odd shaped token (not square, circle etc) such as a full height man ie rectangle.
3. Ensure the token is set to 'native size'
4. Ensure the token is set to 'figure' shape
5. Apply a halo colour box to the token through the right click menu on the token.

**Expected behavior**
The halo 'highlight box' should be positioned on the tokens grid cell it is standing on. When the token is set to a particular size, ie medium, large etc - function is applied correctly - seems to be the 'native size' calculation is not working as intended.

**Screenshots**
Screenshot showing unexpected behaviour

**MapTool Info**
- Version: 1.5.0

**Desktop (please complete the following information):**
 - OS: Windows 7 64bit

**Additional context**
![bug](https://user-images.githubusercontent.com/49975996/56719199-9df58200-6783-11e9-90fb-ceb239dc640a.png)

**Comment by Jaggeroth** [comment]
I have a fix for the halo position, but I think the whole base positioning is off for native size figure tokens.
This means the vision calculations are off and I have more work to do.
Have to remind myself how this bit works :(

**Comment by nemafow** [comment]
Ahh yes, I just realised the vision isnt working as intended too and came to report :(

**Comment by Jaggeroth** [comment]
Pull Request 454
