### ISSUE TITLE
[Bug]: If a map with templates is copied and the copy's [Map -> Edit map… -> Pixels per Cell] is changed, templates sizes change on the original map

### ISSUE THREAD

**Issue by Baaaaaz** [RPTools/maptool#4526]
### Describe the Bug

If a map with templates is copied and the copy's [Map -> Edit map… -> Pixels per Cell] is changed, templates sizes change on the original map.

### To Reproduce

Create a map and add all 8 template types.
Make a copy of this map.
Change the map scale using [Map -> Edit map… -> Pixels per Cell] to 50.
Select the original map (which should have a Pixels per Cell of 100)
Observe how the original templates have change size (well apart from Burst and Blast templates (which now in this case https://github.com/RPTools/maptool/issues/4524 works in this issue's favour!)

### Expected Behaviour

Changing the grid size on one map should not affect templates on another map (even if they are copies).
Drawing IDs for templates in a campaign should be unique (even if they are copies).

### Screenshots

Original "Grasslands" Map:
![image](https://github.com/RPTools/maptool/assets/131240480/e826ea9a-d2af-493a-8d5b-4ef56ee1a8f0)

"Copy of Grasslands" map with  changed Pixels per Cell = 50.   Templates have changed size (well, apart from Burst & Blast templates)
![image](https://github.com/RPTools/maptool/assets/131240480/09107d9d-28ee-4dab-80d0-c2df32435e93)

Now select original "Grasslands" map, and see how templates have incorrectly changed size 
![image](https://github.com/RPTools/maptool/assets/131240480/a9fb2159-006e-4f56-b1bb-8f4090cf83bc)

### MapTool Info

Occurs in 1.13.2 & 1.14.3

### Desktop

Windows

**Comment by Baaaaaz** [comment]
Also note this bug only seems to be occur by changing the Pixels per Cell of the last of copy of a map.  Does not seem to be occur when changing the scale of the original or intermediate copies.  e.g. 
* take a map with templates on, copy it and then copy the copy.  Changing the copy of the copy map's Pixels per Cell  will also change the respective templates on both the original and copy maps.
* take a map with templates on, copy it and then copy the copy.  Changing the original map's Pixels per Cell does not affect the templates on the copy or copy of the copy maps.
* take a map with templates on, copy it and then copy the copy.  Changing the copy map's Pixels per Cell does not affect the templates on the original or copy of the copy maps.

**Comment by Baaaaaz** [comment]
Also note: Using Draw Explorer we can see that the Drawing ID for a templates are the same across the copied maps, which may be part of the issue here as adding templates to the original after the map is copied are not affected by changing the Pixels per Cell to the copy map.

**Comment by kwvanderlinde** [comment]
This looks like a special case of #2433. But while that more general bug is still present, this particular issue should be fixed in #4753 now that templates no longer hold onto grid size state.

**Comment by Baaaaaz** [comment]
Tested in 1.16.0.rc-2 and looks fixed to me.  Thanks!
