### ISSUE TITLE
Token VBL and AI Pathing Conflict

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#456]
**Describe the bug**
If a token has VBL and the AI button is on, you don't get a path and you cannot revert the last move.

**To Reproduce**
1. Drop a token on the map
2. Edit the token and generate VBL from the VBL tab
3. Ensure AI pathing is turned on
4. Move the token, no path is generated. You also can not revert the last move.

**Expected behavior**
A token with VBL should still generate a path and be able to revert the last move. You should ignore token VBL on the moving token when using AI pathing.

**MapTool Info**
- Version: 1.5.2 rc4
- Install: New

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.4

**Comment by Phergus** [comment]
Confirmed under Win10 and with Nerps 1.4.5.4, and MT versions 1.5.0 and 1.5.1.

**Comment by JamzTheMan** [comment]
But it has to cross it's own vbl which it can't... You trying to move a house? :)

It would need some underlying changes as the tokenVBL is cached so would have to remove tokenVBL, redo cache, move Token, restore vbl, redo cache.

It can be done but not for 1.x

**Comment by rkathey** [comment]
One of the uses of token VBL os to keep players from moving through creature tokens. I understand this is not a small change. Another workaround would be to disable AI for tokens with VBL since it doesn’t work anyway.

**Comment by Phergus** [comment]
While VBL on character tokens has its use, I would think using the Terrain Modifier would be better suited to stop movement through the tokens.

I was thinking VBL on large creatures would nice as they should obscure the view.

Of course, a large creature isn't going to be slowed down by terrain (including puny humans) the same way as it would affect a human-sized figure so does the AI pathing make sense then anyways?

**Comment by JamzTheMan** [comment]
New terrain modifier BLOCK is definitely a better fix, and in Pathfinder land you can still move through enemies at half speed so a MULTIPLY of 2 would be appropriate.

@rkathey  BUT, still a need for maybe machines, constucts, etc. Here'a sample of a Car with VBL moving!

![image](https://user-images.githubusercontent.com/8051654/73083189-5d50a380-3e90-11ea-8bd5-69ce5f31b402.png)

**Comment by Phergus** [comment]
Tested and is working a expected.
