### ISSUE TITLE
[Feature]: Expose JSONPath feature to MTScript framework developers so that we can parse data from modern online tools such as HeroLab Online and PathBuilder 2e

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#4563]
### Describe the Problem

I would like to port my PF1e framework to create a PF2e framework.  My PF1e framework parses character data for player characters (PCs) and non-player characters (NPCs) as XML using, indirecly, XPATH via the HeroLab Classic MTScript API.

PF2e characters, however, are exported as JSON by PathBuilder 2e and HeroLab Online.  So, I would like to process that via JSONPath.

https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html

### The Solution you'd like

I would like to parse JSON data stored in a text file via an MTScript feature based on JSONPath.

### Alternatives that you've considered.

I've thought about dropping this data into a token property and trying to use the existing MTSCRIPT functions to parse it, but I have a strong feeling that's not going to work.

Another possibility is that I've been advocating adding features to MapTool to enable us to play more easily from online character sheets -- but I don't think the concept is getting enough traction.  It also might be too complex for the current resources.

### Additional Context

Don't seem to currently have a manageable way to play PF2e in MapTool.  Doing a customizable framework for MapTool for me is preferred over VTTs such as Foundry VTT due to the hours of character building that would be needed to support all the new NPCs introduced for each of the adventures, D20Pro due the current lack of a HeroLab Online importer, or Fantasy Grounds Ultimate due to their only having NPC stat sheets and requiring data entry also for new characters with no importer for HeroLab Online or PathBuilder 2e as far as I know.

**Comment by Akaku-Keninari** [comment]
Different from https://wiki.rptools.info/index.php/Category:JSON_Path_Function ?

**Comment by adventuremagic123** [comment]
> Different from https://wiki.rptools.info/index.php/Category:JSON_Path_Function ?

That's exactly it.  Thanks.
