### ISSUE TITLE
[Feature]: Auras and Light Through Walls

### ISSUE THREAD

**Issue by ColdAnkles** [RPTools/maptool#4578]
### Describe the Problem

Some systems have effects that do not adhere to line of sight - ie. "all creatures within 60feet" - not "all visible creatures within 60 feet". Auras and lights that would benefit towards assisting with these cases do not exist.

### The Solution you'd like

Auras and Lights gain a new option "PASSTHRU" where VBL is ignored when determining the light area.

### Alternatives that you've considered.

Measuring from every relevant token - but that's not as quick and easy as a visible circle.

**Comment by kwvanderlinde** [comment]
Some recent discussions of related - though more complicated - ideas:
- #4379, regarding types of sight + VBL and their interactions; could also have similar concepts for light + VBL.
- #4562, regarding AOE with some generalized effects.

**Comment by ColdAnkles** [comment]
Yeah, 100% - on board with what I'm seeing in those suggestions. What I've done here is very basic, and perhaps a step towards some of what's required.

**Comment by kwvanderlinde** [comment]
Let's talk names. "PASSTHRU" - or any variation - doesn't convey much unless you're already thinking about VBL. I'd like to see something more explicit, e.g., "ignores-vbl" or something.

**Comment by thelsing** [comment]
How about x-ray?

**Comment by ColdAnkles** [comment]
I decided to go with "ignore-vbl" as it seemed to me the best of clarity and simplicity - When defining a light, the options should be clear - pass through vbl works, but is too long, and as said elsewhere, PASSTHRU is bad language. So "I want this light/aura to ignore vbl".

**Comment by bubblobill** [comment]
Note to self. Update #4549 when this happens
