### ISSUE TITLE
[Bug]: metamacro functions producing Java errors

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#4582]
### Describe the Bug

![image](https://github.com/RPTools/maptool/assets/45483160/4ec90d80-ea30-4fa9-bc41-2da883ee923f)
https://discord.com/channels/296230822262865920/905157521193455676/1188456999755714610

### To Reproduce

use metamacro function without all optional parameters

### Expected Behaviour

should function cleanly

**Comment by kwvanderlinde** [comment]
This change has broken all the functions it touches. E.g., `getMacros()` went from
```java
      if (parameters.get(1).toString().equalsIgnoreCase("campaign")) {
        return getMacros(delim, MapTool.getCampaign().getMacroButtonPropertiesArray());
      } else if (parameters.get(1).toString().equalsIgnoreCase("gm")) {
        return getMacros(delim, MapTool.getCampaign().getGmMacroButtonPropertiesArray());
      } else {
        Token token = FunctionUtil.getTokenFromParam(resolver, functionName, parameters, 1, 2);
        return getMacros(delim, token);
      }
```
to
```java
      if (parameters.size() > 1) {
        if (parameters.get(1).toString().equalsIgnoreCase("campaign")) {
          return getMacros(delim, MapTool.getCampaign().getMacroButtonPropertiesArray());
        } else if (parameters.get(1).toString().equalsIgnoreCase("gm")) {
          return getMacros(delim, MapTool.getCampaign().getGmMacroButtonPropertiesArray());
        }
      } else {
        Token token = FunctionUtil.getTokenFromParam(resolver, functionName, parameters, 1, 2);
        return getMacros(delim, token);
      }
```

So there is now no way to use this function with parameters, unless we happen to use the new `"campaign"` or `"gm"` options.

**Comment by bubblobill** [comment]
> This change broken all the functions it touches. E.g., `getMacros()` went from
> 
> So there is now no way to use this function with parameters, unless we happen to use the new `"campaign"` or `"gm"` options.

Hmmm... that could be problematic. Just a little bit. That being said, it will only break every framework known to man,

**Comment by bubblobill** [comment]
Fixed the fix. Properly this time. Complete with lots of testing to prevent future embarrassment

**Comment by kwvanderlinde** [comment]
Awesome, looks good now!
