### ISSUE TITLE
[Request] Flat movement cost increase option for Terrain Modifier (difficult terrain) tokens

### ISSUE THREAD

**Issue by RicoTheBold** [RPTools/maptool#459]
**Feature enhancement request:**
The terrain modifier token feature applies a cost multiplier.  This is mostly fine, but doesn't work for the Pathfinder 2nd edition Playtest (PF2e) difficult terrain rules.  These are not necessarily the final Patfhinder 2nd edition rules, but it does not seem likely the final rules will change here.

The PF2e rules add a flat 5 or 10 additional feet of movement cost for difficult/greater difficult terrain, without any additional increase for diagonal movement.  Default diagonal movement uses the 5/10/5 alternating diagonal movement cost, and that combination is where the current implementation does not work.

**Current behavior**
_Example using terrain modifier of 2.0 (double cost) to model difficult terrain_
- The multiplier makes it so that the first 5 feet of horizontal or vertical movement costs 10, which is +5, matching what is needed for PF2e difficult terrain.
- Diagonal movement costs 15 for the first square of movement, which is 5 more than PF2e should cost for difficult terrain (default 5 + 5 for difficult terrain).
- The second square of diagonal movement costs 15, which is the same as it would cost for PF2e (10 for second diagonal + 5 for difficult terrain).

The modifier therefore does not model PF2e movement rules on diagonals.

_Example using terrain modifier of 3.0 (triple cost) to model greater difficult terrain_
- The multiplier makes it so that the first 5 feet of horizontal or vertical movement costs 15, which is +5, matching what is needed for PF2e's greater difficult terrain.
- Diagonal movement costs 20 for the first square of movement, which is 5 more than PF2e should cost (default 5 + 10 for greater difficult terrain).
- The second square of diagonal movement costs 25, which is 5 more than PF2e should cost (10 for second diagonal + 10 for greater difficult terrain).

The modifier therefore does not model PF2e movement rules on diagonals.

**Desired behavior**
Add an option (either in campaign properties, or preferences, or on the token itself - just somewhere) to have the terrain modifier option add a configurable flat cost to movement.  Each square of movement would take this additional cost without consideration for the original movement cost.

**Alternatives considered**
- Using the system as-is and mentally adjusting the costs of diagonal movement.
- Ignoring the diagonal movement discrepancy entirely
- Ignoring the terrain modifier feature
- Write macros for movement cost instead of the terrain modifier token feature (might have weird interaction with AI movement feature)

**Additional context**
n/a

**Comment by JamzTheMan** [comment]
I plan to revisit and enhance it. Allow you to put a +/- in for a straight cost adjustment which should work for PF2e then.

Question is if that should use cell units? I enter +5 or +1 and let MT add the cell unit cost in.

**Comment by Phergus** [comment]
So you're thinking that if Distance per Cell is 5 and you put in +1, then it would add 1 x 5 to the normal 5 for moving into that space?   +2 would add 2 x 5 and so on.  Possibly easier for GMs to work with.

Versus just putting in the direct cost and relying upon the map creator to do the math.  An advantage to this is that it would be slightly easier to put in values that weren't integer multiples of Distance per Cell.  Not sure that there are any systems out there where that would apply.

**Comment by Azhrei** [comment]
Obviously, we'll need to wait for the final rules to come out (August, I think).  But the OP also said:

> The PF2e rules add a flat 5 or 10 additional feet of movement cost for difficult/greater difficult terrain, without any additional increase for diagonal movement. Default diagonal movement uses the 5/10/5 alternating diagonal movement cost, and that combination is where the current implementation does not work.

Which sounds like difficult terrain overrides the 1-2-1 movement that normally applies.

**Comment by Phergus** [comment]
No.  Pretty sure he is saying that difficult terrain should _add_ to the movement cost of movement in to that square and not multiply.   So the first diagonal movement into difficult terrain would be a cost of 2 and the next diagonal would be a cost of 3 and then back to 2.   In terms of 5' squares with DpC of 5, that would be 10-15-10 instead of the current 10-20-10.

Maybe it should just be a toggle.
Option A:  Movement Cost for Cell = TM * CurrentCellCost
Option B:  Movement Cost for Cell = TM + CurrentCellCost

**Comment by JamzTheMan** [comment]
Pretty sure PF2e is keeping 1-2-1 except for difficult terrain (no idea why)

So instead of 10-20-10 it would be 10-15-10.

**Comment by RicoTheBold** [comment]
Apparently I did a terrible job of being clear.  Here's the rule from PF2e:

> Moving into a square of difficult terrain (or moving 5 feet into or within an area of difficult terrain, if you’re not using a grid) costs an extra 5 feet of movement. Moving into a square of greater difficult terrain instead costs 10 additional feet of movement. This additional cost is not increased when moving diagonally.

So it's just a flat increase of whatever the normal movement cost would be, either by 5' for difficult terrain or by 10' for greater difficult terrain.  As Jamz noted, for regular terrain, it's 5'/10'/5', for difficult terrain that makes it 10'/15'/10', and for greater difficult terrain 15'/20'/15'.

As for why, I think avoiding a multiplier is probably faster for most people to calculate manually when you're not playing on a virtual tabletop, making it easier to support multiple levels of difficult terrain.

All of this made me curious, so I went back and looked at the Pathfinder 1 and D&D 4e/5e rules for difficult terrain:
- PF 1e: Movement measured in both feet and squares, depending on the specific rule section. Each square of difficult terrain counts as 2 squares, except for diagonals.  Diagonal movement in difficult terrain is _always_ "3 squares" so...it actually was less consistent, as it truly changed the normal 5'/10'/5' diagonal pattern entirely to 15'/15'/15'. System only has one level of difficult terrain.  This doesn't work at all with Jamz's current implementation or what I suggested, and I think would probably require being tied into whatever the flag is already in place for diagonal movement.
- D&D 4e:  Movement always written/measured in squares. No 1/2/1 pattern for diagonals.  Difficult terrain costs 1 extra square. System only has one level of difficult terrain.  This works perfectly with Jamz's current implementation using a 2.0 multiplier, since the edge case of diagonals with variable costs doesn't exist.
- D&D 5e: Every foot of movement costs 1 extra foot.  This works perfectly with Jamz's current implementation using a 2.0 multiplier.  System only has one level of difficult terrain.


**Feature scope creep**
Would it make sense to make movement modifier types/patterns a configurable campaign-level set of properties, like sight or light or the existing 1/2/1 flag?  It would also be cool to be able to designate tokens to completely ignore such movement types in a way that can be toggled (for flying, etc.).

**Comment by Phergus** [comment]
> So it's just a flat increase of whatever the normal movement cost would be, either by 5' for difficult terrain or by 10' for greater difficult terrain. As Jamz noted, for regular terrain, it's 5'/10'/5', for difficult terrain that makes it 10'/15'/10', ...

I thought it was clear.  That is what Jamz and I both said.

**Comment by Phergus** [comment]
New terrain modifier setting ADD implements this.  Tested.

**Comment by Phergus** [comment]
See #1068 and #1136 for details of new functionality.
