### ISSUE TITLE
[Feature]: Add Token Types in getInfo("campaign")

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#4694]
### Describe the Problem

There is no macro based method to determine what token types exist within a campaign

### The Solution you'd like

Include `token types`  in the `getInfo("campaign")` function

**Comment by Baaaaaz** [comment]
"Token Type" in MapTool has two definitions/usages which seems wrong, confusing, avoidable, etc.

1. https://wiki.rptools.info/index.php/Introduction_to_Tokens#Token_Type -> PC or NPC
2. https://wiki.rptools.info/index.php/Introduction_to_Properties#Token_Type -> Basic (the default), and custom others.

It would be good if the Token Properties tab had its use of this term replaced with "Property Type",  "Token Property Type", or something else to remove the ambiguity for new users - or in this case before the ambiguity proliferates into other features.
