### ISSUE TITLE
MT 1.5+ ignores Show Movement Distance setting.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#470]
**Describe the bug**
Movement distance is shown when moving token even when View -> Show Movement Distances is off.

**To Reproduce**
1. Start MapTool and place token on map.
2. Set token to snap-to-grid if not.
3. Un-select Show Token Movement in View menu
4. Token distance is still shown when moved.

**Expected behavior**
When option un-selected, expect movement distance to not be shown.

**MapTool Info**
- Version: 1.5+
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
[Forum post by Taustinoc.](https://forums.rptools.net/viewtopic.php?f=21&t=28120)

**Comment by Phergus** [comment]
Checking something.

**Comment by Phergus** [comment]
Nevermind.

**Comment by Phergus** [comment]
@Merudo - Comment on this if you would.

**Comment by Merudo** [comment]
Sure!
