### ISSUE TITLE
[Bug]: Opening older campaign, text labels move and have invisible  text color

### ISSUE THREAD

**Issue by fw** [RPTools/maptool#4706]
### Describe the Bug

Opening an older campaign (1.12.2) that uses text labels in 1.5.0-beta.1, those positions move and the text color is invisible.

### To Reproduce

I couldn't reproduce this (except moving labels).
Alternatively, I attach the campaign file related to this issue. All tokens except text labels are removed.
[[test] labels-1.12.2.zip](https://github.com/RPTools/maptool/files/14335986/test.labels-1.12.2.zip)
The attached file was saved by version 1.12.2, but created in an even older version (I don't remember it).

### Expected Behaviour

The labels sit in the same position and have readable text color.

### 1.12.2
![image](https://github.com/RPTools/maptool/assets/29275/a82e8368-e720-4cd5-a780-1d51dbd1948b)
### 1.15.0-beta.1
![image](https://github.com/RPTools/maptool/assets/29275/63e3a404-6cca-4a4d-baad-ca9ec0537ab8)

### MapTool Info

1.15.0-beta.1

### Desktop

Windows 11 Pro

**Comment by cwisniew** [comment]
@fw, what version of MapTool was this campaign created in?
I can't create a campaign in 1.13. or 1.14 where text is black in that version but then white in the 1.15rc version

edit: NVM I see its in the description, I should have had coffee before trying to read it :)
