### ISSUE TITLE
[Bug]: Update Token Property window to keep selected property in view when using Move Up and Move Down.

### ISSUE THREAD

**Issue by FullBleed** [RPTools/maptool#4711]
### Describe the Bug

If you have a property list larger than the property display window holds, when you "Move Up/Down" a property it can move out of view. 

### To Reproduce

1) Create enough properties to have some not displayed in the window.
2) Create a new property and Move it up to the top of the list.  It will move out of view.

### Expected Behaviour

Token property Window should update and keep the selected/moving property in view.

### MapTool Info

1.15.0 Beta 1

### Desktop

Windows

**Comment by FullBleed** [comment]
Can make another bug report if wanted... but also when a property list is larger than the display window, when you "Add" a new property it appends to the end of the window... but the window does not refresh and display the new property.  You have to scroll down to the bottom of the list to see that a new property has been added.

**Comment by maltedreschert** [comment]
I implemented a fix for this one.
@cwisniew do you need to assign this bug for a PR
