### ISSUE TITLE
MapTool 1.5.2 Exception thrown when clicked "New Map" for Campaign with no maps

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#474]
**Describe the bug**
I removed all the maps from a campaign, clicked "New Map", and got the following exception. 

```
java.lang.NullPointerException
	at net.rptools.maptool.client.ui.AppMenuBar$1.itemStateChanged(AppMenuBar.java:135)
	at java.desktop/javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:1995)
	at java.desktop/javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2315)
	at java.desktop/javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:458)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:364)
	at java.desktop/javax.swing.AbstractButton.setSelected(AbstractButton.java:341)
	at net.rptools.maptool.client.ui.RPCheckBoxMenuItem.menuSelected(RPCheckBoxMenuItem.java:38)
	at java.desktop/javax.swing.JMenu.fireMenuSelected(JMenu.java:1036)
```

**To Reproduce**
1. Removed all the maps from a campaign.
2. Clicked "New Map".
3. Got exception.

**Expected behavior**
A new map should have been created.

**Screenshots**

**MapTool Info**
- Version: 1.5.2
- Install: ???

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
I've attached the campaign for which this was happening.

[No Maps.zip](https://github.com/RPTools/maptool/files/3189338/No.Maps.zip)

**Comment by Phergus** [comment]
No MT version specified.

Testing with MT 1.5.2 cannot reproduce with supplied campaign or new campaign.

Reproducible steps needed.

**Comment by adventuremagic123** [comment]
My steps are exactly as I said above.

**Comment by Phergus** [comment]
Tested your steps with no exception produced.

The NPE shown isn't in the code for handling selecting New Map from the menu.

**Comment by adventuremagic123** [comment]
Ok.  It's your choice as to whether to drop it.  In 1.5.3, if we see it again, we'll post a bug.

Sorry, but due to all the copyrighted material, I can't give you the complete campaign -- and I think that's why you didn't ask.

**Comment by Phergus** [comment]
Correct.  Posting campaigns with copyrighted material in it would not be a good thing.

In general, having campaigns stripped to the bare minimum needed to reproduce the error is best in any case.

**Comment by Phergus** [comment]
The error is from the code that handles the Map menu and particular the Expose FoW Only at Waypoints selection.  Which is only enabled if there is a valid map and the map has FoW turned on.   So chances are it was a chain of events that produced the error but so far I have been unable to reproduce them.
Thanks for reporting the issue as it is good to know that it can happen.  Will close for now.

**Comment by adventuremagic123** [comment]
Okay.  Sorry, I couldn't figure it out.  Didn't seem to be a serious issue  
because after the error occurred, I was able to click "New Map" and get a  
new map.

On Mon, 29 Jul 2019 10:03:39 -0500, Phergus <notifications@github.com>  
wrote:

>
> The error is from the code that handles the Map menu and particular the  
> Expose FoW Only at Waypoints selection. Which is only enabled if there  
> is a >valid map and the map has FoW turned on. So chances are it was a  
> chain of events that produced the error but so far I have been unable to  
> reproduce >them.
> Thanks for reporting the issue as it is good to know that it can happen.  
> Will close for now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Sincerely,
Mark Young

**Comment by adventuremagic123** [comment]
I use shared FoW and individual FoW but do not use Expose FoW Only at  
Waypoints.

On Mon, 29 Jul 2019 10:03:39 -0500, Phergus <notifications@github.com>  
wrote:

>
> The error is from the code that handles the Map menu and particular the  
> Expose FoW Only at Waypoints selection. Which is only enabled if there  
> is a >valid map and the map has FoW turned on. So chances are it was a  
> chain of events that produced the error but so far I have been unable to  
> reproduce >them.
> Thanks for reporting the issue as it is good to know that it can happen.  
> Will close for now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Sincerely,
Mark Young
