### ISSUE TITLE
[Feature]:  Automaitcally copy Issues labes to PRs

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#4743]
### Describe the Problem

I am forgetful, so I don't always remember to assign the correct label to a PR before merging them.
Since the labels on the PR are the ones used for the release notes, this means the PR gets lumped in the "other changes" if I don't catch it and go back and update.

### The Solution you'd like

Add [copy-issue-labels](https://github.com/marketplace/actions/copy-issue-labels) action to automatically copy labels from issues to PRs.

### Alternatives that you've considered.

Status Quo (and I don't mean the band).

**Comment by kwvanderlinde** [comment]
This has been failing and makes it look like PRs are in a bad state. Here's a message from a currently open PR:
> Run michalvankodev/copy-issue-labels@v1.3.0
> HttpError: Resource not accessible by integration
>     at /home/runner/work/_actions/michalvankodev/copy-issue-labels/v1.3.0/webpack:/copy-issue-labels/node_modules/@octokit/request/dist-node/index.js:66:1
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

https://github.com/RPTools/maptool/actions/runs/8657096814/job/23762204523?pr=4752
