### ISSUE TITLE
[Feature]: Classic Token Properties menu within Campaign Properties OR advanced "Add" feature.

### ISSUE THREAD

**Issue by LKS23** [RPTools/maptool#4768]
### Describe the Problem

Within the new Campaign Properties window, the Token Properties tab now has this neatly ordered and fancy looking menu. While this is arguably way more user friendly than the old text block, it also brings with it some major problems for me.

My first problem: I often need to copy the whole text block of various token properties to be able to edit them in my development documentation, where I can add notes or brainstorm for new features. With the new simplified Token Property menu, I can no longer copy multiple entries.

My second problem: In my campaign I regularly add new properties and remove old ones. This is still possible with the new menu but when adding new properties, I need to click "Move Up" a lot to put the property in the right place which is a quite tedious and time costly task.

I'm in no way against the new menu, as it is way more user friendly and easy to understand. So I'd be happy with some additions instead of a revert.

### The Solution you'd like

For the first problem, add an "export Token Properties" button, where you can export the token properties into a txt file or to the clipboard.
For the second problem, expand the "Add" button, so it adds the new entry above the currently selected property, instead of the bottom.

### Alternatives that you've considered.

Add a text edit option, where you can display the old text block. This would solve both problems with minimal effort.

### Additional Context

The reason I often copy token properties into an external documentation is because it's rather impractical to manipulate and document them within maptool. This could potentially also be handled by a way to comment on various properties. However I don't think that many people would use such a feature and it would probably make things more confusing for the regular user, so I'd prefer my solution suggestions.

**Comment by bubblobill** [comment]
New release has/will have the option to "Copy" a set of token properties. See #4649 
So, for instance, if your monsters and PCs use the same properties, you would be able to set up all your properties for PCs; create a copy with the relevant button; then rename the token type property set to "Monster".
Hopefully this should take out most of the effort for creating multiple token types that use a common core of properties.
