### ISSUE TITLE
[Bug]: Topology tool cursor coordinates

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4772]
### Describe the Bug

When using when of the topology tools (any shape, any VBL or MBL), the cursor coordinates at the bottom of the window are not updated.

### To Reproduce

1. Open a map in MapTool.
2. Using the pointer tool
3. Move the cursor around the map and watch the coordinates be updated.
4. Switch to any topology tool.
5. Move the cursor around the map and watch the coordinates remain at their last value that the pointer tool was used.

### Expected Behaviour

The coordinates should update to show the current cursor position as for the pointer tool.

### Screenshots

Just so no one has to go looking, the `-2, -2` here are the cursor coordinate:
![image](https://github.com/RPTools/maptool/assets/7492219/dfc711d6-158b-4413-b5b8-22943bafd199)

### MapTool Info

1.13.2

### Desktop

Linux Mint 21

### Additional Context

All other toolbar tools seem to update coordinates properly.

**Comment by Baaaaaz** [comment]
Tested in 1.16.0.rc-2 and looks fixed to me.  Thanks!
