### ISSUE TITLE
[Bug]: Importing an existing map results in duplicate token IDs

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4789]
### Describe the Bug

If I export a map with tokens on it, and then import it, the IDs of the tokens on the imported map remain unchanged and duplicate the ones that already exist in the campaign. This makes macro functions more difficult to use since token IDs cannot be relied on as being unique.

### To Reproduce

1. Create a map and drag a token on it.
2. Export the map
3. Import the file created in (2)
4. Compare the ID of the existing token to the imported token.

### Expected Behaviour

Tokens on imported maps should be given new IDs. Or we could relax that a bit and only change the IDs if there is no existing token by that ID.

### MapTool Info

1.13.2

### Desktop

Linux Mint 21.3

**Comment by kwvanderlinde** [comment]
I'm actually on the fence about calling this a bug. On the one hand I really don't like the idea of a GUID being nonunique in a campaign. On the other hand, I can appreciate that an exported map might contain internal references to tokens by ID (e.g., a "light switch" token stores the ID of the "light" token it controls). On the other other hand, I'd be surprised if the possibility of duplicate token IDs is widely considered and handled properly.

**Comment by cwisniew** [comment]
I would call it a bug, and say importing something should give new IDs all the way down. Otherwise we get into trouble in the future when we want to add any feature that refers to a token by its id.
