### ISSUE TITLE
Token set to Snap to Grid no longer snaps to grid when moving

### ISSUE THREAD

**Issue by leowalter** [RPTools/maptool#479]
**Describe the bug**
Token set to Snap to Grid no longer snaps to grid when moving.  When moving the token, the token is moving like it is not snap to grid.  Accidental drop beyond VBL is common.

**Expected behavior**
When moving a snap to grid token, the token should snap to grid when moving.

**MapTool Info**
- Version: 1.5.2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [10, multiple versions.  All players experienced it.]

**Comment by Phergus** [comment]
@leowalter  Please test with 1.5.3-rc3 (or later).

**Comment by Phergus** [comment]
Fix is in 1.5.3.rc3.  Closing.
