### ISSUE TITLE
[Bug]: Incorrect hex grid icons in Edit Map dialog 

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4811]
### Describe the Bug

When using the Rod Takehara icon theme, the Edit Map dialog shows pointy-top hexes where flat-top hexes should be and vice versa.

### To Reproduce

1. Edit the current map
2. Select pointy-top (horizontal) hex option, and click "OK"
3. Turn on the grid and see flat-top (vertical) hexes on the map.

### Expected Behaviour

Pointy-top hexes should have the pointy-top icon, and flat-top hexes should have the flat-top icon.

### Screenshots

On 1.14.3 (these icons aren't present in Rod's theme):
![image](https://github.com/RPTools/maptool/assets/7492219/1970625d-c2cf-4fdf-9b6d-d78e668471e0)

On 1.15.0 RC with Rod's icons:
![image](https://github.com/RPTools/maptool/assets/7492219/bee13215-20b8-456c-b994-4c37db34bfef)

On 1.15.0 RC with classic icons:
![image](https://github.com/RPTools/maptool/assets/7492219/d40bef76-1300-4015-a5aa-9ef15614c40d)

### MapTool Info

1.15.0-rc.3

### Desktop

Linux Mint 21.3

### Additional Context

Comparing the above screenshots shows this is merely an issue of picking the wrong icon. Functionality is in other regards correct.

**Comment by bubblobill** [comment]
le closing?

**Comment by kwvanderlinde** [comment]
Yep
