### ISSUE TITLE
[Bug]: A few dialogs can't be closed via escape key

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4833]
### Describe the Bug

Most of MapTool's modal dialogs can be closed via the escape key, but these few cannot:
- Edit > Preferences
- File > Export > Screenshot
- File > Export > Screenshot As ...

### To Reproduce

1. Use any of the mentioned menu items to open a dialog.
2. Hit the escape key
3. Nothing happens.

### Expected Behaviour

Using the escape key should consistently close dialogs

### MapTool Info

1.13.2, develop

### Desktop

Linux Mint 21.3

**Comment by bubblobill** [comment]
Preferences has no cancel option. All preferences are updated in real time. Cancelling would be a major rewrite of our most complicated dialog as it would require storing everything and committing changes on okay. Not going to touch it.
Both other menu items refer to the same dialog. Have added close on escape to those ones.

**Comment by kwvanderlinde** [comment]
Ah, I never even thought of it as related to cancelling - the Preferences dialog could just close despite having committed changes. But I can also see how that might cause surprises.
