### ISSUE TITLE
[Bug]: Token is offset when dragging with "Snap token while dragging" disabled

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4855]
### Describe the Bug

If the preference **Snap token while dragging** is turned off, a snap-to-grid token will jump by half a cell down and to the right when starting to drag it. This is jarring in itself, but it also makes the whole drag feel off since the token's cell position is based off the top-left corner - the token can visibly be in one cell, but the top-left corner may be in a different cell, leading to confusion.

### To Reproduce

1. Disable the **Snap token while dragging** preference
2. Add a snap-to-grid token to a gridded map.
3. Grab the token anywhere and start to drag it.
4. Notice the token jump half a cell down and to the right as soon as the drag begins.

### Expected Behaviour

The token should not jump at all when the drag begins, and the whole operation should feel smooth for the user. Additionally, the cell that the token occupies should be based on its center, not on the top-left corner.

### Screenshots

In this screenshot, the right hand token was only dragged by a pixel or two, but is offset from the grid much further than that:
![image](https://github.com/RPTools/maptool/assets/7492219/1355745a-340e-40c5-afaf-b5cabba08796)

### MapTool Info

1.14.3

### Desktop

Linux Mint 21.3

**Comment by FullBleed** [comment]
What do you think the fix is for this?  When people understand that the token's cell position is determined by the top left corner the current behaviour kind of makes sense... but it feels and looks off.

Are you going to change the cell position to be cursor based?  Or center of token when dragging?

Are we too far down the rabbit hole to get an option to set a token's cell position as center?

Also (and this is separate issue but should be in sight when looking at this behaviour), when "Hide Mouse Pointer while dragging" is disabled, the cursor is visible during token layer drags, but not on any other layers.

**Comment by kwvanderlinde** [comment]
> What do you think the fix is for this? When people understand that the token's cell position is determined by the top left corner the current behaviour kind of makes sense... but it feels and looks off.
>
> Are you going to change the cell position to be cursor based? Or center of token when dragging?
>
> Are we too far down the rabbit hole to get an option to set a token's cell position as center?
> 
> Also (and this is separate issue but should be in sight when looking at this behaviour), when "Hide Mouse Pointer while dragging" is disabled, the cursor is visible during token layer drags, but not on any other layers.

The only real problem here is that the token image isn't rendered in the right place. If it were a half cell up-and-left from where it currently is, it would look and feel quite natural. The fact that it's offset just messes with expectations of where the token should end up. If we fix that, the token will naturally snap according to its center, which is the same as saying that it will snap to the cell that the token is mostly within (for Medium tokens anyways).

As for options / configurations for this behaviour, we are actually well set up to support that. Internally we already query the token for its "snap point", which today accounts for the token size, grid properties, layer, etc. Details for a configurable alternative would of course depend on the specific FR, but seems feasible.
