### ISSUE TITLE
Restore previous token dragging behavior

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#487]
**Describe the bug**
PR #372 changed the token drag behavior such that the token image doesn't snap to grid and was visibly off from the mouse pointer position by a significant amount.  While the movement path highlighting does indicate where the token would end up, this new behavior still causes confusion.  It also made it very easy to accidentally drop a token inside of VBL.

Token dragging needs to be restored to previous behavior.

**MapTool Info**
- Version: 1.5.2
- Install: Any

**Desktop:**
 - OS: Any
 - Version: Any

**Comment by Jaggeroth** [comment]
I am against this change.
While some people might not like it, I have players that found the previous drag style very difficuilt to use.

**Comment by Phergus** [comment]
Preference settings added to select between snapped and non-snapped dragging modes.  Code tweaked to keep token image better synced with mouse position.

**Comment by Phergus** [comment]
No further feedback or comments.  Closing.
