### ISSUE TITLE
[Bug]: Mismatched grid types in dialog

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#4879]
### Describe the Bug

The hex grid orientation does not match the radio button in the "Edit Map" dialogue.

### To Reproduce

open a map,
set the grid to visible
open the edit map dialogue
set to a hex grid type
notice the difference

### Expected Behaviour

grid types matching selection

### Screenshots

![image](https://github.com/user-attachments/assets/cc787958-a986-41cc-a5c4-0c0341a34402)

**Comment by FullBleed** [comment]
https://github.com/RPTools/maptool/issues/4811
