### ISSUE TITLE
[Bug]: Overlay javascript created forms sometimes don't make it to maptools macros

### ISSUE THREAD

**Issue by Akaku-Keninari** [RPTools/maptool#4895]
### Describe the Bug

Ever since 1.15, many of my frameworks' overlay buttons have stopped working. They functioned just fine in 1.14.3 and I cant seem to isolate exactly why they fail now.

### To Reproduce

1: on sample campaign right click and impersonate the second token Perra on the 'nowhere' map
2: many buttons should appear on the screen via overlay
3: click feature then 'scales of the dragon'
4: it will output the form it's trying to submit via console.log attached to an onsubmit
5: it doesn't actually submit the form
6: click utilities then skill check
7: observe it actually calling a different macro

### Expected Behaviour

When you press scales of the dragon, it should spit out the console log THEN say 'powerBarProcess called' then spit out a power effect the same as if you pressed the macro actually on the impersonate window
[submitbugg.zip](https://github.com/user-attachments/files/16872086/submitbugg.zip)

### Screenshots

![button and console log](https://github.com/user-attachments/assets/0395515d-66fe-4149-b067-ff9d9dd9797f)
![expected output](https://github.com/user-attachments/assets/e08717ee-a408-473a-8968-af00f83da2da)

### MapTool Info

1.15.1rc1 with 1.14.3 uninstalled first

### Desktop

Windows 11

### Additional Context

Display Name..: Marvell AQtion 10Gbit Network Adapter
Interface Name: ethernet_32776
Address...: 
Address...: 

Display Name..: Software Loopback Interface 1
Interface Name: loopback_0
Address...: 0:0:0:0:0:0:0:1
Address...: 127.0.0.1

Host Address...: 
Default Gateway: 

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 3840x2160(32)

==== Internet Gateway Devices ====
	No IGDs Found!

**Comment by kwvanderlinde** [comment]
:confused: I fixed this in 1.14.3, but it looks like the changes didn't make it back into mainline so 1.15 doesn't have them again. Well, at least this will be easy to fix...

**Comment by kwvanderlinde** [comment]
@Akaku-Keninari This should be fixed in 1.15.2.

**Comment by Akaku-Keninari** [comment]
It does appear that it's fixed in 1.15.2 per testing

**Comment by Jmr3366** [comment]
It looks like this one can be closed @Phergus ?
