### ISSUE TITLE
[Feature]: Add hotkey to macro props for createMacro

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#4897]
### Describe the Problem

With the newest version, 1.15.0, it is finally possible to create macros for the GM and Campaign panels. This means it is now possible to wrap an entire framework, if that's what one wants, into an add-on library. 

One thing that is missing for `createMacro`, is the ability to set a hot key. 
Earlier when a framework typically included campaign files, or just a set of tokens, to include, it was, and still is, possible to set a hotkey on a macro. Thus, making it easier to activate key macros. 

This possibility is still lacking for add-ons. 

### The Solution you'd like

I would to have a new property added to the macro props for `createMacro`: hotkey. 
This should do the exact same thing as the macro editor in MapTool, set a hot key for that specific macro. 
If a hot key is already assigned it should simply just reassign it, just as MapTool does today. 

### Alternatives that you've considered.

There is no viable alternative, other than setting hotkeys manually. 
Which is what I don't want.

**Comment by cwisniew** [comment]
I see some problems with this, like what happens when multiple macros set the same hotkey, the outcome will be unpredictable

**Comment by Tdue21** [comment]
Just do as MapTool does now. The last macro setting a particular hotkey wins.

**Comment by cwisniew** [comment]
> Just do as MapTool does now. The last macro setting a particular hotkey wins.

Yeah because no one ever creates seemingly endless discussions about how they don't like the fact that it's undefined which will get run last and win... No sir never happens :)

**Comment by Tdue21** [comment]
Very true.l 😀 

But seriously,  if you assign a hotkey to a macro today  and it is already assigned,  it is simply removed from the previous macro. 

I'd expect the same behavior if I could set it through `createMacro`.
