### ISSUE TITLE
Build Failing on Ubuntu 18.04 with openjdk 1.8.0_212

### ISSUE THREAD

**Issue by totalknowledge** [RPTools/maptool#490]
**Describe the bug**
Build Failing on Ubuntu 18.04 with openjdk 1.8.0_212 with the error:
Could not find method annotationProcessor() for arguments [{group=org.apache.logging.log4j, name=log4j-core, version=2.11.0}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**To Reproduce**
Cloned Repo locally.
checked JDK version openjdk version "1.8.0_212"
installed FX 
sudo apt install openjfx
Ran  ./gradlew wrapper --gradle-version=4.5.1 --distribution-type=bin
Ran ./gradlew build

**Expected behavior**
Builds MapTool

**Screenshots**
![image](https://user-images.githubusercontent.com/2588903/59681842-dec9b000-91a2-11e9-824d-2c25ad1ae869.png)

**MapTool Info**
- Version: master
building

**Desktop (please complete the following information):**
Ubuntu 18.04

**Comment by Phergus** [comment]
Use the develop branch.
Current code/project only builds with Java 10.

**Comment by totalknowledge** [comment]
I get a different build error in the develop branch.

* Where:
Settings file '/home/brycolem/Workspace/maptool/settings.gradle' line: 22

* What went wrong:
A problem occurred evaluating settings 'MapTool'.
> Could not find method gitRepository() for arguments [https://github.com/RPTools/dicelib, settings_62e0yffmymiid0i3s55jeqif1$_run_closure1$_closure2@2da176b1] on object of type org.gradle.vcs.internal.DefaultSourceControl.

**Comment by Phergus** [comment]
Make sure you have gradlew 5.3.1
`./gradlew wrapper --gradle-version=5.3.1 --distribution-type=bin`

**Comment by totalknowledge** [comment]
Now I get:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not target platform: 'Java SE 10' using tool chain: 'JDK 8 (1.8)'.

Which doesn't seem like it should be a fatal error but is.

**Comment by Phergus** [comment]
You have to have JDK 10.

**Comment by Phergus** [comment]
This is the wrong place for getting help with building MapTool.
[Join the Discord server.](https://discord.gg/crpk7FM)
