### ISSUE TITLE
Macro editor doesn’t recognize `set` as a function

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#492]
**Describe the bug**
The `set` function is documented on the wiki but isn’t marked as a function inside the macro editor.

**To Reproduce**
1. Type in “set” to the macro editor and note that it doesn’t turn blue.
2. Profit!

**Expected behavior**
The word should turn blue.

**Screenshots**
N/A

**MapTool Info**
- Version: 1.5.3
- Install: any

**Desktop (please complete the following information):**
 - OS: all (expected, not verified)
 - Version all (expected, not verified)

**Additional context**
There is a wiki entry for `set` so it was somehow also missed during the documentation conversion; most likely the wiki source doesn’t follow the pattern used to select functions out of the wiki dump.

**Comment by Phergus** [comment]
See comments on issue #403 

> They are not defined in the MapToolLineParser. There are handfuls of functions and variables declared in various places. :/

**Comment by Azhrei** [comment]
Closed as duplicated of #403
