### ISSUE TITLE
[Bug]: Token Light Source popup menu items for clearing Light or Auras are duplicated if multiple tokens selected

### ISSUE THREAD

**Issue by Baaaaaz** [RPTools/maptool#4933]
### Describe the Bug

"Clear [Owner/GM] Light/Aura" token popup menu items are duplicated if multiple tokens have these lights/auras and are selected.

### To Reproduce

1. Create a token and given it a variety of lights and auras (inc. Owner or GM types)
2. Copy and paste the token several times.
3. Select all the tokens
4. Bring up the token popup menu and observe duplicated Light Source menu items for clearing lights/auras.
5. Clicking one of these duplicated menu items with clear all appropriate lights/auras of the type clicked from all the selected tokens.

### Expected Behaviour

Popup menu items are not duplicated.

### Screenshots

![image](https://github.com/user-attachments/assets/511edadb-9849-449d-bd11-5ef8715777f6)

### MapTool Info

1.15.0

### Additional Context

https://github.com/RPTools/maptool/issues/4927 already raised for incorrect GUI text.

**Comment by kwvanderlinde** [comment]
Same cause: if you have a bunch of tokens selected, some with lights and some without:
- if you right-click on a token without light sources or auras, you don't get the option to clear any
- if you right-click on a token with light sources or auras, you get the (repetitive) option to clear.

**Comment by Baaaaaz** [comment]
Tested in 1.16.0.rc-2 and looks fixed to me.  Thanks!
