### ISSUE TITLE
[Bug]: Macros resist being moved between certain macro groups in 1.15.2

### ISSUE THREAD

**Issue by Ltheb** [RPTools/maptool#4959]
### Describe the Bug

In 1.15.2, (But not in 1.15.0) Moving macros between macro groups on the same token, or between tokens, cannot be done in certain directions.  There are ways one can click and drag macros, but it operates by strange rules, and the limitations severely limit workflow in copying macros/tokens.

### To Reproduce

1. New fresh instance of a map in 1.15.2
2. Create 2 tokens.
3. Put Macros on at least one token.
4. Select both tokens.
5. Try to move a macro from one token in the Selected Token macro window to another by clicking and dragging the macro from one group to another, or from one to the common macros section.
6. It doesn't happen. Nothing happens.
There seem to be issues moving macros (which share the same name) into the same group as well, even on the same token.  Additionally, duplicating a macro (with the duplicate selected macro right-click function) creates 2 macros in the same group with the same name; they can be separated, but can never again be in the same group if done so.
Further, if duplicated, the duplicate shows up in the common macro section, but isn't replicated on any of the other tokens unless right clicked and duplicated in the common macro section of the selected token window. This results in 3 of the same macro on the first token, and one on the second.

### Expected Behaviour

In previous versions, a macro could be dragged from one token to another, and there seemed to be no issue with 2 macros with the same name in a macro group.

### MapTool Info

1.15.2; Windows Exe Installer

### Desktop

Windows 10

### Additional Context

==== MapTool Information ====
MapTool Version: 1.15.2
MapTool Home...: E:\MaptoolCache
MapTool Install: E:\D&D\Maptool\Maptool9\app
Max mem avail..: 4 GB
Max mem used...: 2 GB
Custom Property: -DMAPTOOL_LOGDIR=E:\MaptoolCache\logs
Custom Property: -DMAPTOOL_DATADIR=E:\MaptoolCache

==== Java Information ====
Java Home......: E:\D&D\Maptool\Maptool9\runtime
Java Vendor....: Eclipse Adoptium
Java Version...: 21.0.1
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss16M
  -Xmx4G
  -Xms2G
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -Djava.util.Arrays.useLegacyMergeSort=true
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  --add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
  -Djpackage.app-path=E:\D&D\Maptool\Maptool9\MapTool.exe

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
PATH...........: E:\D&D\Maptool\Maptool9;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Plantronics\PlantronicsURE\;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Users\[User]\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\[User]\AppData\Local\Microsoft\WindowsApps;;E:\Programs\mitmproxy\bin;E:\D&D\Maptool\Maptool9\app;.
Number of Procs: 8

==== User Information ====
User Name: [User]
User Home: C:\Users\[User]
User Dir.: E:\D&D\Maptool\Maptool9

==== Network Interfaces ====
Display Name..: Realtek PCIe GbE Family Controller-WFP Native MAC Layer LightWeight Filter-0000
Interface Name: ethernet_2

Display Name..: Realtek PCIe GbE Family Controller-QoS Packet Scheduler-0000
Interface Name: ethernet_3

Display Name..: Realtek PCIe GbE Family Controller-WFP 802.3 MAC Layer LightWeight Filter-0000
Interface Name: ethernet_5

Display Name..: WAN Miniport (IP)-WFP Native MAC Layer LightWeight Filter-0000
Interface Name: ethernet_7

Display Name..: WAN Miniport (IP)-QoS Packet Scheduler-0000
Interface Name: ethernet_8

Display Name..: WAN Miniport (IPv6)-WFP Native MAC Layer LightWeight Filter-0000
Interface Name: ethernet_9

Display Name..: WAN Miniport (IPv6)-QoS Packet Scheduler-0000
Interface Name: ethernet_10

Display Name..: WAN Miniport (Network Monitor)-WFP Native MAC Layer LightWeight Filter-0000
Interface Name: ethernet_11

Display Name..: WAN Miniport (Network Monitor)-QoS Packet Scheduler-0000
Interface Name: ethernet_12

Display Name..: Realtek PCIe GbE Family Controller
Interface Name: ethernet_32769
Address...: fe80:0:0:0:a72d:d1bc:1a30:f41c%ethernet_32769
Address...: 192.168.1.2

Display Name..: WAN Miniport (IP)
Interface Name: ethernet_32770

Display Name..: WAN Miniport (IPv6)
Interface Name: ethernet_32771

Display Name..: WAN Miniport (Network Monitor)
Interface Name: ethernet_32772

Display Name..: Software Loopback Interface 1
Interface Name: loopback_5
Address...: 0:0:0:0:0:0:0:1
Address...: 127.0.0.1

Host Address...: 192.168.1.2
Default Gateway: 192.168.1.1

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(32)

==== Internet Gateway Devices ====
Device Name.: Actiontec "Wireless Broadband Router"
Model Name..: "Wireless Broadband Router"
Manufacturer: Actiontec
Model Number: 40.21.24
Model Desc..: Actiontec "Wireless Broadband Router" Internet Gateway Device
Firmware....: Wireless Broadband Router/4.7.5.3.31.2.19 UPnP/1.0
External IP.: [IP Withheld]

**Comment by Ltheb** [comment]
Checked if the bug exists in 1.15.1: Can confirm, bug happens in 1.15.1, but NOT 1.15.0

**Comment by bubblobill** [comment]
Looks like #4888 to resolve #4883 did have unintended consequences.
It exits the relocation where the group name does not change but does not check if it is the same target.
