### ISSUE TITLE
[Feature]: isPathfindingEnabled

### ISSUE THREAD

**Issue by shondoa** [RPTools/maptool#4974]
### Describe the Problem

In my current framework players are denied their movement if it would stop them in MBL. Recently I've also started using EventPads with Bag of Tricks to create one-directional pathways that snap the player back to their last valid square if they try to pass through in the wrong direction.

The issue with these pads is that, normally if I need to allow a player to bypass MBL I can simply turn off AI pathfinding and move them to where they need to be, but these pads trigger regardless of if pathfinding is enabled.

### The Solution you'd like

A simple function, something like isPathfindingEnabled, would allow me to adjust the pads and disable their functionality if pathfinding isn't enforced. There doesn't seem to be any way to get the current state of pathfinding within a macro at the moment, but I think it would be useful to have and simple to implement.

### Alternatives that you've considered.

I've considered adjusting the pads to disable their functionality if a GM is moving the token using isGM, but this isn't really an elegant solution as would cause the pads to not be automatically enforced for NPCs controlled by the GM, meaning the GM would need to make sure they're not accidentally bypassing them.

It would also be possible to create an extra macro that toggles the functionality of the pads, but this is also rather clumsy as it's an extra button that needs to be pressed in addition to the AI pathfinding toggle.

**Comment by kwvanderlinde** [comment]
Not a dedicated function, but it is already achievable:
```
[r: json.get(getInfo("server"), "using ai")]
```

**Comment by shondoa** [comment]
> Not a dedicated function, but it is already achievable:
> 
> ```
> [r: json.get(getInfo("server"), "using ai")]
> ```

Oh perfect! I guess I just didn't think to dig into getInfo to find this. Thank you!
