### ISSUE TITLE
[Refactoring]: Clean up AppPreferences

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#4985]
### Describe the problem

`AppPreferences` has a few problems that make it a bit of a pain to work with:

Most preferences is implemented as two constant (key + default value), a getter, and a setter, possibly with some custom logic.  When adding a new preference, this is enough opportunity to make mistakes, requiring extra care to get right. It also adds up in terms of lines of code: with well over 100 preferences, `AppPreferences` is almost 2000 lines long.

It's also not declarative, and the _how_ completely drowns out the _what_. Looking at the class, it's not clear how many preferences there are, which ones are actually defined. Even search for usage requires checking setters and getters separately, adding to the work if tweaking a preference.

Lastly, there are things in there that aren't even preferences, they are just implemented on top of `Preferences`. E.g., the MRU campaign list.

### The improvement you'd like to see

Define a `Preference<T>` class that can represent an individual preference, including its key, type, and default value. A new could be added by simply instantiating this class and assigning it to a field in `AppPreferences`.

### Expected Benefits

- `AppPreference` code cut in half
- Easier to see the defined preferences.
- Easier to define new preferences.
- Options for general fancy features (e.g., change handlers, consistent validation, etc).

**Comment by thelsing** [comment]
How about changing the way preferences are stored to a json file too? This way it would be easier to store complex data like key maps. And you would get rid of the size limit on windows.
