### ISSUE TITLE
Ars Magica style Stress Dice

### ISSUE THREAD

**Issue by AtelierFox** [RPTools/maptool#500]
**Is your feature request related to a problem? Please describe.**
There is no option to roll Ars Magica style stress dice.

These are D10s.  If 1 is rolled, the die is rolled again and the result doubled (this can recurse, so 1 -> 1 -> 5 = 4x5 = 20). If 0 is rolled, then a number of botch dice is rolled. If there are no further 0s, then the character's result is 0 (plus any relevant boni). If there are *any* zeroes in the botch roll, then the character has botched, and gets a 0 (and no boni can be applied). The more 0s are rolled, the worse the effect of the botch.
A stress die can be specified with no botch dice, in which case a max value is just 0 + boni.

**Describe the solution you'd like**
I propose two formats:

1. SY, where Y is the number of botch dice if a 0 is rolled. This matches the spoken "stress dice with 4 botch dice"
2. XS, to keep with the convention of XdY.

**Describe alternatives you've considered**
You can technically do this just rolling D10s and applying the cases by hand, but having a built-in would speed this up considerably.

**Additional context**
Detailed description of the rules surrounding this mechanic: https://www.redcap.org/page/Stress_die

**Comment by cwisniew** [comment]
@AtelierFox how would you expect the output of the dice to look like (I am asking as I don't play it so honestly no idea of what people would want to see).
Just a final number (as you get with [2d10]) or a breakdown of result/how many botches (something like what you get with [6sr4], but this would mean a string is returned not a number).

**Comment by Phergus** [comment]
From reading the info at the link above and also the info on [Botch die](https://www.redcap.org/page/Botch_die), you would need two totals.  One for the Stress Die total and one for the Botch Die.

**Comment by AtelierFox** [comment]
@cwisniew For normal results, a final sum is okay, however if the initial die rolls a 0, the total is 0 (+ boni), and you must roll the indicated number of botch dice. If *any* of them come up 0, the total of the entire roll is 0 (and boni are forfeit). The number of 0s here indicates the severity of the botch.


As an example, I roll a stress die with 4 botches. I roll 0, so now I have to roll 4d10.
**Case 1**: [4,7,9,1] = No zeroes. This is not a botch. The function should output 0 so that stress + bonus outputs correctly.
**Case 2**: [0,0,3,4] = Botch. The number of zeroes indicates severity. The user gets a 0 (and boni are forfeit).

A workable format may be BS(Bon) (e.g. 4S+7 or 2S-3) where B is the number of botch dice and (Bon) is a bonus, which can be either positive or negative. (N.B. You cannot roll below a 0 in this system).

**Comment by cwisniew** [comment]
I have coded it (should be in an upcoming release)

Format is as follows (its not quite the usual closer to dragon quest format but thats what is required if +/- bonuses are part of the roll). First format is easier for just straight rolling, the second (ANS) is more useful for macro writing. 

AS***n***b#+***b*** / AS***n***b#-***b*** (or as***n***#+***b*** / as***n***#-***b***)
	***n*** = number of botch dice
    ***b*** = bonus + or - must be included

value is returned as a string, e.g "3", "0", "0 (1 botch)", "0 (3 botches)".

ANS***n***b#+***b*** / ANS***n***b#-***b*** (or ans***n***#+***b*** / ans***n***#-***b***)
	***n*** = number of botch dice
    ***b*** = bonus + or - must be included

value is returned as a number, if there are botches the value returned will be negative.  e.g. 3, 0, -1, -3.

**Comment by Phergus** [comment]
Tested.  Both functions appear to be producing correct values based on descriptions above.
