### ISSUE TITLE
[Bug]: Frame5, Dialog5 are not removed

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#5024]
### Describe the Bug

Frame5 and Dialog5 are not removed on a `closeFrame` or `closeDialog` but only set to visible 0.  So if you open any uniquely named frame5 or dialog5, they will remain and only made invisible.

### To Reproduce

In a new campaign, note the output of `[r: getInfo("client")]`
Create a new macro in the GM panel that contains this:
```[h: name = "Test"]
[h: formHTML = "This is ONLY a test"]
[overlay(name,"zOrder=1"): {[r: formHTML]}]
[frame5(name,"title="+name+"; width=440;height=560"): {[r: formHTML]}]
[dialog5(name,"title="+name+"; width=440;height=560"): {[r: formHTML]}]
```
Run the above macro
Not the output of `[r: getInfo("client")]`
Create another one with these contents
```[h: name = "Test"]
[h: formHTML = "This is ONLY a test"]
[overlay(name,"zOrder=1"): {[r: formHTML]}]
[frame5(name,"title="+name+"; width=440;height=560"): {[r: formHTML]}]
[dialog5(name,"title="+name+"; width=440;height=560"): {[r: formHTML]}]
```
Run that macro
Not the output of `[r: getInfo("client")]`
The frame5 and dialog5 you closed are still there, just set to `visible: 0` 

### Expected Behaviour

If you `closeFrame` or `closeDialog` , it should be removed and not set to invisible.

`closeOverlay` performs as expected.

### MapTool Info

1.13.1 - 1.15.2

### Desktop

Win11

**Comment by Jmr3366** [comment]
One update to this is that if you use the `temporary` variable when creating the dialog or frame, the close function _does work_ as expected.
Perhaps an update to the wiki in both the `dialog5` and `frame5` to better show the _use_ for `temporary` and then something in the `closeDialog` and `closeFrame` section to note _**If temporary has not been set to 1, this function only sets the frame/dialog not visible and does remove the frame/dialog**_

**Comment by kwvanderlinde** [comment]
I presume it's also the same if the user closes the frame themselves?

I think it's reasonable to say that closed frames and dialogs shouldn't appear in the client info - conceptually they don't exist anymore. Internally we have to hold onto them, but that doesn't mean we have to expose them.

**Comment by FullBleed** [comment]
If any dev takes look at this... please glance at resetFrame.  In testing this I was getting some buggy behaviour when using it.  At one point it was actually opening an empty frame of the frame it was supposed to be resetting... another it put the frame into a state where it wasn't appearing in getInfo after being closed (which is the opposite of the behaviour that this issue was noting.)  It was almost like it was opening the frame (empty) with a "temporary=1" parameter to "reset" it... but then not closing it properly.

**Comment by Jmr3366** [comment]
> I presume it's also the same if the user closes the frame themselves?
>
Correct. 
I would actually be good with just tweaking the wiki in the two areas.

**Comment by FullBleed** [comment]
> I think it's reasonable to say that closed frames and dialogs shouldn't appear in the client info - conceptually they don't exist anymore. Internally we have to hold onto them, but that doesn't mean we have to expose them.

It's a little odd... and I was inclined to see it removed from getInfo... BUT getFrameProperties() returns the properties of frames that are not visible, too.  And there is a "visible" parameter within each return.  So it might be more odd if it doesn't return the same info.

**Comment by cwisniew** [comment]
> If any dev takes look at this... please glance at resetFrame. In testing this I was getting some buggy behaviour when using it. At one point it was actually opening an empty frame of the frame it was supposed to be resetting... another it put the frame into a state where it wasn't appearing in getInfo after being closed (which is the opposite of the behaviour that this issue was noting.) It was almost like it was opening the frame (empty) with a "temporary=1" parameter to "reset" it... but then not closing it properly.

resetFrame is really only to reset the location of frames that are not visible due to being on a monitor that "disappeared".  For who ever looks at this, probably the sanest choice is for resetFrame to do nothing if the frame is not in an open + visible state

**Comment by Jmr3366** [comment]
I made wiki edits to `frame5` `dialog5` `closeFrame` and `closeDialog` so it is more clear on what temporary does.
If anyone feels this is _not_ sufficient, I will re-open.
