### ISSUE TITLE
FOW functions: add "mapname" as valid argument

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#505]
**Is your feature request related to a problem? Please describe.**
The code in FogOfWarFunctions.java makes it clear that all FOW functions are intended to take "mapname" as an argument, but the feature is not available for some FOW functions because of a bug.

**Describe the solution you'd like**
Fix the bug and allow the argument "mapname" to work as intended.

**Additional context**

The bug can be fixed by replacing

```
private Set<GUID> getTokenSelectedSet(final ZoneRenderer zr) {
    Set<GUID> tokens = MapTool.getFrame().getCurrentZoneRenderer().getSelectedTokenSet();
    Set<GUID> ownedTokens = MapTool.getFrame().getCurrentZoneRenderer().getOwnedTokens(tokens);
    return ownedTokens;
 }
```
by

```
private Set<GUID> getTokenSelectedSet(final ZoneRenderer zr) {
    Set<GUID> tokens = zr.getSelectedTokenSet();
    Set<GUID> ownedTokens = zr.getOwnedTokens(tokens);
    return ownedTokens;
  }
```

in FogOfWarFunctions.java

**Comment by Phergus** [comment]
In the description you said "some FoW functions" which implies more than one.  The PR #506 specifically calls out exposeFOW().  Are there other functions that were impacted and, if so, which ones?

**Comment by Merudo** [comment]
No other functions were impacted by my commits.

exposePCOnlyArea() and exposeAllOwnedArea() are known to take mapname as arguments.

restoreFoW() already has mapname as an argument, even though the wiki doesn't report it.

Only toggleFoW() and exposeFogAtWaypoints() do not take mapname as argument, but it would require a different approach to fix these.

**Comment by Phergus** [comment]
exposeFoW() wiki entry updated.
restoreFoW() wiki entry updated.

**Comment by Phergus** [comment]
Tested exposeFoW() and restoreFoW().  Closing
