### ISSUE TITLE
MapTool preferences incorrectly handles Units per Cell if European notation is used

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#507]
**Describe the bug**
Some locales use a comma for a decimal point but entering a Units per Cell in that format isn't handled correctly.  Entering `5,0` gets turned into `5.0` when saved in Preferences.  When New Map is then invoked, the Units per Cell is shown as `5.0` which turns into **50** not 5.0.

**To Reproduce**
1. Open MapTool with language set to German (or other locale using `,` for decimal point).
2. Select Edit -> Preferences
3. In Units per Cell put in `5,0`.
4. Click on Save.
5. Open Preferences again and note that Units per Cell incorrectly shows `5.0` with a period.
6. Select Map -> New Map to open New Map dialog
7. Note that Units per Cell shows `5.0` and if a map is created with that input, the resulting map has Units per Cell of `50`.
8. Entering `5,0` on the New Map dialog works as expected.

**Expected behavior**
Expect Preferences to save values according to user locale and New Map dialog to correctly use the values.

**MapTool Info**
- Version: 1.5.2
- Install:  Installed

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
See forum post: https://forums.rptools.net/viewtopic.php?f=21&t=28250

Issue also shows up when editing Distance per Cell in Edit Token dialog.

**Comment by Azhrei** [comment]
Just poking my head in to clarify...  The Preferences don't "save values according to locale", as the values are saved in locale-neutral format (i.e., binary).  But they should be displayed in the user's chosen locale and the user's locale should be accepted on input.

I think there are some functions in SwiftUtilities (or similar) called **parseNumber()** (with variants for Integers) and those may be locale-aware as I believe they use a **NumberFormat** object.  But I do't have the code in front of me to easily check...

**Comment by Phergus** [comment]
Yeah.  The problem is the use of Double.toString() in retrieving the stored values which isn't locale aware.  Using NumberFormat should help.

**Comment by wolph42** [comment]
There's an additional problem. Entering 5 results in 50. This is a very confusing result. 
currently the only way to set a correct distance per cell for a map is entering 0.5 which is extra confusing cause it should be 0,5

**Comment by Phergus** [comment]
It's the same problem.  Entering a 5 is like entering 5.0 which of course is equal to 50 in locales that use the period as separator.  Entering `5,0` works.   If you open the Edit Map dialog and leave it showing `5.0` when you close it, the distance per cell will get changed to `50`.
Changing it using `5,0`.
![Screenshot 2020-04-11 07 53 45](https://user-images.githubusercontent.com/34379254/79045765-fe1a4980-7bc9-11ea-9f91-5a9ba305940a.png)
Moving token after change.
![Screenshot 2020-04-11 07 54 03](https://user-images.githubusercontent.com/34379254/79045771-0bcfcf00-7bca-11ea-88b8-0c1b54828331.png)

**Comment by Merudo** [comment]
PR #1692 fixes this.

**Comment by Phergus** [comment]
Tested with German language/locale.  Units per Cell is correctly displayed and if updated using the decimal format for the local, the saved value is correct.

**Comment by wolph42** [comment]
Awesome! Next time use Dutch! It's the better of the two :)
