### ISSUE TITLE
exposeFOW() should take tokens as arguments.

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#509]
**Is your feature request related to a problem? Please describe.**
exposeFOW() doesn't take any arguments, and exposes the FOW for the selected tokens on the current map.

This means macros have to change both the map and the selected tokens to expose the FOW of a given token, which can be undesirable and result in multiple lines of code.

**Describe the solution you'd like**
exposeFOW() should accept up to three arguments:

```
exposeFOW()
exposeFOW(mapName)
exposeFOW(mapName,tokens)
exposeFOW(mapName,tokens, delim)
```

`mapName` - the name of an existing map within the campaign; defaults to current map.
`tokens` - a String List or JSON Array of tokens names or ids for which to reveal the FOW; defaults to the selected tokens.
`delim` - the delimiter used in the String List that is supplied. If the delimiter is "json", then the value for tokens may be a JSON Array instead. 

**Additional context**
Issue discussed in a [forum post here](https://forums.rptools.net/viewtopic.php?f=3&t=28229&p=273399).

**Comment by Phergus** [comment]
Documentation incomplete.

**Comment by Phergus** [comment]
Tested new options and updated wiki page:   http://www.lmwcs.com/rptools/wiki/exposeFOW

**Comment by JamzTheMan** [comment]
Do we need to adjust the other expose fow functions to match? Forget the names but expose owned and expose PC functions? (Maybe those just need the mapname, or maybe they are covered by another issue? So much is going on I can't keep track so just throwing random thoughts out lol)

**Comment by Phergus** [comment]
I hear ya.  It's a bit overwhelming with so many changes under so many issues/PRs.

If the others haven't been extended then they should be.  Will check and open issue if needed.

**Comment by Phergus** [comment]
@JamzTheMan  Yeah.  The others all take mapname as a parameter already.

**Comment by JamzTheMan** [comment]
Cool cool. I guess since they already have token filters embedded, they don't need token params.

In hindsight, extending exposeFoW would have been better than new functions...

**Comment by Phergus** [comment]
I guess they could be re-written now to call exposeFoW() appropriately but they ain't broke so probably best to let them be.

**Comment by JamzTheMan** [comment]
Agreed. For MT2 hopefully we can do a cleanup and have a lot less functions with appropriate params.
