### ISSUE TITLE
[Bug]: Cannot open a campaign saved by 1.16.0-beta.1

### ISSUE THREAD

**Issue by fw** [RPTools/maptool#5090]
### Describe the Bug

Cannot open a campaign saved by 1.16.0-beta.1.
The old version's campaign is openable (1.15.2).

### To Reproduce

1. Save a campaign.
2. Open that campaign.
3. Got the "Error dialog 1"
4. Click "OK" on that dialog, then get the "Error dialog 2"
5. Click "OK" on that dialog, then get the "Error dialog 3"

### Expected Behaviour

Loaded the campaign.

### Screenshots

Error dialog 1
![2024-12-07 (1)](https://github.com/user-attachments/assets/563cd859-eff1-439f-8023-6125edcf3bea)
Error dialog 2
![2024-12-07 (2)](https://github.com/user-attachments/assets/e45db991-ac7c-4fb2-bf51-72556d54ee55)
Error dialog 3
![2024-12-07 (3)](https://github.com/user-attachments/assets/213ecd47-26c5-431b-b2e3-4cb740cb9962)

### MapTool Info

1.16.0-beta.1

### Desktop

Windows 11 Pro

**Comment by kwvanderlinde** [comment]
Same cause as #5091. Will handle them together.
