### ISSUE TITLE
[Bug]: Cannot load a map exported by 1.16.0-beta.1

### ISSUE THREAD

**Issue by fw** [RPTools/maptool#5091]
### Describe the Bug

Cannot load a map exported by 1.16.0-beta.1.
A map exported by an old version (1.15.2) is loadable.

### To Reproduce

1. Export a map.
2. Import that map.
3. Getting an error dialog attached to this post.

### Expected Behaviour

Importing the map successfully.

### Screenshots

![2024-12-07 (4)](https://github.com/user-attachments/assets/fdacdd02-ce75-4949-b4fc-5f0363e10942)

### MapTool Info

1.16.0-beta.1

### Desktop

Windows 11 Pro

**Comment by kwvanderlinde** [comment]
My fault. Actually, no, it's XStream's fault - it works in mysterious ways. Anyhoo, fix incoming.
