### ISSUE TITLE
[Bug]: Campaign becomes unreadable

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#5094]
### Describe the Bug

If you save a file in 1.16.0-b1, you can not open it in -b1 or in 1.15.2.

### To Reproduce

Open 1.16.0-b1.
Save the file.
Try to open the file
You'll get an error:
![image](https://github.com/user-attachments/assets/3c261fae-149b-466d-bd29-73aa73c32c4f)

### Expected Behaviour

1.16.0-b1 should be able to open the file.

It would be good to know if files saved in 1.16.x are known to change the _backward compatibilty_ (eg. beam lights)

### Screenshots
Error from 1.15.2 if attempting to open a 1.16.0-b1 file:
![image](https://github.com/user-attachments/assets/57a9a5b7-53af-4f69-8839-ebe25c41a993)

_No response_

### MapTool Info

1.16.0-b1

### Desktop

Win 11

**Comment by kwvanderlinde** [comment]
The part about opening campaigns in 1.16.0-beta.1, this is a duplicate of #5090 and is fixed in 1.16.0-beta.2.

For the second part of opening a 1.16.0-beta.1 campaign in 1.15.2, I don't think "downgrading" a campaign like this is generally supported / supportable. @cwisniew Do you have opinions on this point?

**Comment by cwisniew** [comment]
> For the second part of opening a 1.16.0-beta.1 campaign in 1.15.2, I don't think "downgrading" a campaign like this is generally supported / supportable. @cwisniew Do you have opinions on this point?

We always do our best to support opening older campaigns in each new version, but when be features are added that require changes to the campaign save format then these saves generally won't be able to be opened with an older version. This has been the expectation for a long time

**Comment by Jmr3366** [comment]
The last dev build (re: 1.16.0-b2) fixes the save/load issues within 1.16.0.
As downgrading may not be possible / supportable, I'm good closing this one out.
