### ISSUE TITLE
[Bug]: Missing single-quote escapes in translations

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#5116]
### Describe the Bug

At some point, all or most of the escaped `''` in translation files were turned into unescaped `'`. This has two downsides when using them with interpolation:
1. The quote gets swallowed and is not present in the interpolated string.
2. Any arguments that follow the quote (unless another `'` shows up first) is treated as literal text. So any referenced parameters are not interpolated.

### To Reproduce

1. Open MapTool in a French locale
2. Drop a PC token on the map and take ownership of it.
3. Add the token to the initiative
4. Advance initiative.
5. See this message in chat "Cest au tour de {0} de jouer."

### Expected Behaviour

The message should be `C'est au tour de Anonymous User de jouer.`

### MapTool Info

1.15.2

### Desktop

Linux Mint 22

**Comment by kwvanderlinde** [comment]
Goes back to #4580 which is an automated import from Crowdin. 

Reading the docs [here](https://support.crowdin.com/developer/configuration-file/#java-properties-file-format), it seems like escaping in these cases should be the default behaviour, and we don't override that in our `crowdin.yml`. Is there some other place this configuration might be set? E.g., on the Crowdin project itself?

**Comment by bubblobill** [comment]
Settings on Crowdin. 
![image](https://github.com/user-attachments/assets/f74a0797-0d44-4fa8-8e1e-3ef19b287233)

**Comment by bubblobill** [comment]
@kwvanderlinde please test again once this is merged and a batch of translations goes through.
