### ISSUE TITLE
Applying change on a macro from another map throws a null pointer exception

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#513]
**Describe the bug**
Applying changes to a token macro from another map throw a null pointer exception. The error originates from save() in [MacroButtonProperties](https://github.com/RPTools/maptool/blob/develop/src/main/java/net/rptools/maptool/model/MacroButtonProperties.java), called by [MacroButtonDialog](https://github.com/RPTools/maptool/blob/develop/src/main/java/net/rptools/maptool/client/ui/MacroButtonDialog.java). [Full error message](https://textuploader.com/1148b).

A similar error occurs if the token is deleted when the edit macro window is open.

**To Reproduce**
1. Edit a macro on a token.
2. Change map or delete token.
3. Click "APPLY" or "OK" on the macro opened in 1.

**Expected behavior**
Changes are applied with no null pointer exception.

**MapTool Info**
- Version: 1.5.3
- Install: New,

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Regardless of the error, all changes appear to be saved.

**Comment by Phergus** [comment]
Missing an important point.  This would only happen if you are editing a macro on a token.
