### ISSUE TITLE
Incorrect tooltip in Preferences:Application:UPnP:Discovery Timeout

### ISSUE THREAD

**Issue by daliin** [RPTools/maptool#522]
MapTool 1.5.3 — In the Application tab of the Preferences pane, the mouseover tooltip for "Discovery Timeout" under UPnP is a duplicate of the one above it (Macro Panels).

**Comment by Merudo** [comment]
What should the tooltip be?

**Comment by Phergus** [comment]
I would go with:
> Timeout period in milliseconds to wait when looking for UPnP gateways.

**Comment by Phergus** [comment]
You got this @Merudo ?

**Comment by Merudo** [comment]
Issue is fixed, we can close this.

**Comment by Phergus** [comment]
Successfully tested.  Closing.
