### ISSUE TITLE
Bugged map - token has vision blocked for no reason

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#528]
**Describe the bug**
On the map, all tokens have their vision blocked.

**To Reproduce**
1. [Download the map](https://www27.zippyshare.com/v/We0JiCNe/file.html) and import it.
2. Check View as Player. See how the token can't see anything.
3. Verify the absence of VBL in the room.

**Expected behavior**
Token should see the room without problem.

**Screenshots**
Picture of the VBL of the map in question: https://i.imgur.com/JUJZRwN.png

**MapTool Info**
- Version: 1.5.3
- Install: Upgrade from 1.5.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Map works fine in 1.5.2

**Comment by Merudo** [comment]
I think it may be related to the 1 degree bug with VBL. Hopefully this bug is very rare and not worth investigating further.

**Comment by Phergus** [comment]
It's definitely connected to the fix for the 1 degree bug. I think I see the issue.  Will submit a fix for it.

**Comment by Phergus** [comment]
I was wrong.  It's more a general VBL issue.  Prior to the fix, tokens with VBL but no facing set (i.e. null) would return -1 for getFacingInDegrees().  The map supplied above has two objects with null facing and VBL: Mur-2-trimmed 1 and Mur-2-Trimmed 2.  Those would be the only ones affected and by having them rotated -1 degrees it changes how their VBL intersect with the others.  Replacing the VBL on those two objects with auto-generated VBL and vision once again works.  Same with drawing single VBL lines on the map under them and then transferring the VBL to the objects.

Filing under weird VBL interactions and won't be spending any more time on it for this cycle.

**Comment by Merudo** [comment]
Thanks Phergus for investigating this. I changed my map as you said and it works fine now.

**Comment by Phergus** [comment]
Closing.
