### ISSUE TITLE
Smileys don't work

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#529]
**Describe the bug**
Smiles don't work, even if "Insert Smilies" is on.

**To Reproduce**
1. Go in preferences and make sure "Insert Smilies" is on.
2. Type any smiley in the chat, such as :P or :)

**Expected behavior**
The smileys are shown as images.

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Smileys are working again.  Closing.
