### ISSUE TITLE
Add function "getViewCenter()" to return the center of a view

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#531]
**Is your feature request related to a problem? Please describe.**
Currently, there are no functions for returning the center of a view. Instead, users have to use getViewArea() and do the calculation themselves.

**Describe the solution you'd like**
Have a function called "getViewCenter()" to return the center of a view. 

getViewCenter()
getViewCenter(pixels)
getViewCenter(pixels, delim)

**Additional context**
I volunteer to add the function.

**Comment by Phergus** [comment]
Not complete.  Documentation needed.

**Comment by Phergus** [comment]
Tested.  Working as described.

**Comment by Phergus** [comment]
Oops.  Still need documentation.

**Comment by Phergus** [comment]
Wiki page added:  http://www.lmwcs.com/rptools/wiki/getViewCenter
