### ISSUE TITLE
FoW functions should return an error message if mapName is incorrect

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#532]
**Is your feature request related to a problem? Please describe.**
FoW functions don't return an error message if the map argument is invalid

**Describe the solution you'd like**
Show an error message.

**Comment by Phergus** [comment]
Tested and confirmed for:
`[exposePCOnlyArea("NoMap")]
[exposeFOW("NoMap")]
[exposeAllOwnedArea("NoMap")]
[restoreFoW("NoMap")]`
