### ISSUE TITLE
Change tableImage() function to return an empty string if no image is found

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#538]
**Is your feature request related to a problem? Please describe.**
Currently tableImage() throws a parser exception if there isn't an image for the requested entry. This aborts the current macro and gives the user no method to recover gracefully.

**Describe the solution you'd like**
Instead, tableImage() should return an empty string which can easily be checked for by the calling macro.

From discussion with Aranginor on Discord server.

**Comment by Merudo** [comment]
aranginor, are you going to reopen your Pull Request?

**Comment by aranginor** [comment]
No.

**Comment by Phergus** [comment]
Tested. Change working as intended.
