### ISSUE TITLE
Need a getTableEntry() to go along with addTableEntry() and setTableEntry()

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#539]
**Is your feature request related to a problem? Please describe.**
Currently no method exists to retrieve a specific table entry's details and get the min, max, value and image assetID for the entry.

**Describe the solution you'd like**
A getTableEntry(tableName, entryNum) macro function that would return the indicated entry as a JSON object.  Perhaps an optional Boolean parameter to indicate absolute entry versus the entry matching a roll of that value.

- getTableEntry("Animals", 3) - Would return entry 4 as a JSON object or an empty string if the requested entry doesn't exist.  An entry with no image returns an empty string for assetid.
  - Example JSON: {"min":3, "max":5, "value": "duck", "assetid":""}

**Comment by Merudo** [comment]
Added requested function.

**Comment by Phergus** [comment]
Wiki page added for [getTableEntry](http://www.lmwcs.com/rptools/wiki/getTableEntry)

**Comment by Phergus** [comment]
Tested - working as requested.
