### ISSUE TITLE
Auto generate jwrapper.xml

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#54]
jwrapper.xml contains hard coded paths and MapTool jar file names (with version number).
This should be generated from the values in gradle properties rather than needing to update the paths in two places and the jar file for each version.

**Comment by JamzTheMan** [comment]
Take another look at the gradle tasks. JWrapper.xml is auto generated via gradle using the jwrapper-template.xml as a base. You should NOT be modifying jWrapper.xml or MT.cfg and letting gradle generate those for you. The only thing you need to change is your gradle.properties file.

**Comment by cwisniew** [comment]
There was a problem in the gradle.build file that was casuing the mt.cfg and the jWrapper.xml file not to be copied from their templates, thus picking up the old one that was there. Fixed now :)
