### ISSUE TITLE
Non Snap-to-grid Tokens don't drag from the mouse-down point

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#540]
**Describe the bug**
Tokens not set to snap-to-grid on Square grid maps are dragging from the top-left corner instead of where the mouse clicked.  Works correctly on other grid types.  Both Top-Down and Round/Square tokens.

**To Reproduce**
1. Drop token on square grid map.
2. Ensure that it is not set to snap-to-grid.
3. Drag token.
4. Note that the token is being dragged by the top-left corner.

**Expected behavior**
Expect token to drag from the point where the mouse-clicked.

**MapTool Info**
- Version: 1.5.3
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Reported on RPTools forums:
https://forums.rptools.net/viewtopic.php?f=3&t=28267

**Comment by Phergus** [comment]
@Merudo - please comment on this issue so you can be assigned.

**Comment by Merudo** [comment]
My pull request solves this and the issue with dragging a snap to grid token on a gridless map.

**Comment by Phergus** [comment]
Closing for release.  Will open new ticket if more work is needed.

**Comment by MrBertoza** [comment]
This happens again in 1.13.2 and newer versions, I have tested it on 1.14.3 and 1.15.0 beta1
But it seems that it happens only on some conditions, like after importing older versions of Campaign Properties
It's a strange error that doesn't happens every time you move an unsnapped token, I am not able to replicate it consistently
Also it changes the snap point to the top left of the token
![2024-Mar-0322-00-48-ezgif com-optimize](https://github.com/RPTools/maptool/assets/5676098/405720ad-840c-4588-99de-8302c403e433)
