### ISSUE TITLE
Functions in TokenImage.java to have mapName as optional parameter

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#541]
**Is your feature request related to a problem? Please describe.**

It is a pain to change properties of tokens on other maps. Instead of having to change the map and possibly create flickering, it would be better to add the mapName as additional optional argument.

**Describe the solution you'd like**
I would like the following functions in TokenImage.java to take a mapName parameter so they could work on tokens in other maps:

getTokenImage
getTokenPortrait
getTokenHandout
setTokenImage
setTokenPortrait
setTokenHandout
setTokenOpacity
getTokenOpacity

**Comment by Phergus** [comment]
Note that Wiki still needs to be updated for all of these changes.

**Comment by Phergus** [comment]
Code changes complete.

**Comment by Merudo** [comment]
Documentation updated:

https://lmwcs.com/rptools/wiki/getTokenImage
https://lmwcs.com/rptools/wiki/getTokenPortrait
https://lmwcs.com/rptools/wiki/
https://lmwcs.com/rptools/wiki/
https://lmwcs.com/rptools/wiki/
https://lmwcs.com/rptools/wiki/
https://lmwcs.com/rptools/wiki/

**Comment by Phergus** [comment]
All functions tested and working as expected.
