### ISSUE TITLE
Macro property to hide macro from players

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#544]
**Is your feature request related to a problem? Please describe.**
Some macros are only designed to be available to GMs. It would be less confusing to players if these macros were automatically hidden from them.

**Describe the solution you'd like**
A macro option "Allow Players to See Macro", that if disabled would outright hide the macro from players.

**Comment by Azhrei** [comment]
Can you describe the use cases for this feature?  I can see the desire to remove clutter from the player view, but why would the GM put a macro on a PC or NPC token and then hide it, compared to putting it in the Campaign macros (or on a Lib token)?

Is there some visual notifier to a player that the token has hidden macros?

Are such macros still saved by the Export Macros function?

Without a server running, there is no specification of GM or Player, so such macros would be visible, I presume?  Will that not confuse players more who want to work on their tokens during non-game times?

Currently, when multiple tokens are selected, the Selection panel shows macros that are common across all selected tokens — will the Player know that there are hidden macros which are/are not common?

Are hidden macros also hidden from the existing functions that can list out all macros?  What about macros that create other macros — is there an API change required that affects backward compatibility?

I would need to see some discussion across these topics to be convinced this is a useful enough feature...

**Comment by Phergus** [comment]
Just FYI Merudo, the contents of the Global macro panel is computer specific which means that macros the GM adds there would only be visible to the GM.  Note they are not tied to the campaign which has pluses and minuses.

**Comment by JamzTheMan** [comment]
I could see a checkbox for Campaign macros to get a "GM Only" to hide them from players, if anything, just so they get a smaller cleaner list. 

But that's the only panel I would see this is needed really.

**Comment by Phergus** [comment]
There would need to be some decoration for the macro button that makes it visibly obvious to the GM or you would get GMs telling their players to press the Green button and the players screaming there is no green button!

While I understand the desire, it's just so easy to put GM specific macros in their own group with a group name like _Z_GM_MACROS_ so that the group sorts to the bottom of the panel, I don't really see a pressing need for the feature.

I could see this being done in MT 2.0 with user-defined macro panels so that an entire panel would be flagged as GM only.

**Comment by JamzTheMan** [comment]
Agreed. Could be as easy as a res border around the button but good point on decorations.

As far as grouping and such, this is going to be very user specific. For you, that may work just fine. For others?

I have a pretty extensive campaign panel and use image for almost all so my campaign panel is going to look a lot different. There are 2-3 panels I would hide out-right. I have a dozen that I wish the players didn't see at all (they adjust secret properties so I had to use runes that they don't know but I have to remember).

But it is also ok to leave for the UI redesign. I would couple this with filter/search capabilities.

**Comment by Phergus** [comment]
Of course another solution that is available right now is to use a frame that only opens for the GM and contains buttons to call macros.  The frame can be docked along with the other UI elements.

**Comment by Phergus** [comment]
> Is there some visual notifier to a player that the token has hidden macros?

@Azhrei - That's an interesting point on its own.  Should there be some kind of visual notifier to players and/or GMs that a token has macros on it for them to use?  Not talking about the Selected window but some kind of decor to the token.

**Comment by Merudo** [comment]
Now that the GM panel has been implemented I don't see much use for this feature.
