### ISSUE TITLE
Functions setName() and getName() to have mapName as optional parameter

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#547]
**Is your feature request related to a problem? Please describe.**
It is a pain to change properties of tokens on other maps. Instead of having to change the map and possibly create flickering, it would be better to add the mapName as additional optional argument.

**Describe the solution you'd like**
I would like the following functions in TokenImage.java to take a mapName parameter so they could work on tokens in other maps:

getName()
setName()

**Comment by Phergus** [comment]
Code changes complete.  Added to giant stack of needed documentation.

**Comment by Merudo** [comment]
Documentation updated:

https://lmwcs.com/rptools/wiki/getName
https://lmwcs.com/rptools/wiki/setName

**Comment by Phergus** [comment]
Tested.  Changes working as described.
