### ISSUE TITLE
Remove redundant Zone.putToken() calls in TokenImage class

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#549]
**Is your feature request related to a problem? Please describe.**
Currently, a lot of functions call both Zone.putToken() and ServerCommand.putToken(). However, ServerCommand.putToken() already calls Zone.putToken(), so the same operation is done twice, which creates pointless slowdowns.

**Describe the solution you'd like**
Remove all Zone.putToken() statement done immediately before or after ServerCommand.putToken().

**Describe alternatives you've considered**
We might also wish to delete ServerCommand.putToken() and keep Zone.putToken() instead in cases where updating other clients isn't wanted.

Please state which function(s) you would like to behave as such.

**Comment by Phergus** [comment]
What's your status on this?

**Comment by Merudo** [comment]
Closed by #542

**Comment by Phergus** [comment]
Functions affected:
- setTokenImage
- setTokenPortrait
- setTokenHandout
- setTokenOpacity

**Comment by Phergus** [comment]
Tested between server/client and with token ID & Map parameters.
