### ISSUE TITLE
Version Number in settings.gradle 

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#55]
Is the version number required in settings.gradle as we already have it in the version.txt (which is checked into git )

**Comment by Jaggeroth** [comment]
If this could be avoided that would be great. Currently in eclipse I have to manually enter the parameter "-Pversion=1.4.0.1-SNAPSHOT" to the gradle commands, or add it as a global gradle parameter. I've done the later, but its still a pain.

**Comment by JamzTheMan** [comment]
I just keep a version # in my gradle.properties or if I need to test versioning in MT i pass a version number via -version=1.4.0.5 (available in 1.4.1.x)

and i'm not seeing a version # in settings.gradle?
