### ISSUE TITLE
Opening and closing the Edit Token dialog on Player Client turns on Visible over FoW for that token.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#551]
**Describe the bug**
The act of simply opening and closing the Edit Token dialog on a player client will cause the token to be set to Visible over FoW.  This can be seen on the GM side.

**To Reproduce**
1. Start a server and place a PC token on default map.
2. Connect with second MT instance as player.
3. Give player client ownership of token.
4. Verify that token does not have Visible over FoW set via the right-click token menu.
5. Open and then close (with OK button) Edit Token dialog on player client.
6. On server observe that token is now flagged as Visible over FoW

**Expected behavior**
Certainly didn't expect that to happen.

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Was able to duplicate this effect several times as well with a combination of the use of setTokenSnapToGrid(1|0) from the server side which is not propagating the change to the clients causing them token to be out-of-sync between the two clients.  Appeared to be triggered by the use of the right-click menu on the Player side and setting Snap-To-Grid to on but couldn't do so reliably.  Could be a matter of forcing a token update from the client side.

**Comment by Merudo** [comment]
The setTokenSnapToGrid() is a believe a separate issue? #552

**Comment by Phergus** [comment]
re: setTokenSnapToGrid() the non-propagation is a separate issue but connected issue.  Once the propagation issue is fixed chances are that reproducing the erroneous setting of Visible over FoW by the client using the right-click menu will be reduced or eliminated.  It's already hard to make happen.  Mostly added the comment under additional context just as a record that it has occurred.

**Comment by Phergus** [comment]
Tested.  Fixed.
