### ISSUE TITLE
Functions not propagating to other clients

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#552]
**Describe the bug**
The following functions do not update the tokens on other clients:

- setGMNotes()
- setNotes()
- setTokenShape()
- setTokenWidth()
- setTokenHeight()
- setTokenSnapToGrid()
- resetSize()  (also not documented on Wiki)

**To Reproduce**
Use any of these functions on a token, then check the properties of the token from another client. 

The token will be unchanged on their client.

**Expected behavior**
The token is changed for every client.

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
There was extensive discussion in #545 regarding a fix. The concern is that currently, tokens can only be updated by sending the entire token to other clients. This can cause performance issues.

It might be preferable to not fix these functions until a better system to update token changes is implemented.

**Comment by Phergus** [comment]
Confirmed issue with all listed functions.

The problem with the functions is that they don't send out a token update to the clients. All of these need to be corrected.  Performance isn't really an issue for these as they aren't called frequently.  For all of these calling the ServerCommand.putToken() method should be sufficient but will need to be tested of course.

**Comment by Phergus** [comment]
resetSize() not documented on wiki.

**Comment by Phergus** [comment]
Wiki page added for setSize().  http://www.lmwcs.com/rptools/wiki/resetSize

**Comment by Phergus** [comment]
All listed functions tested and working.
