### ISSUE TITLE
NPC token names visible over Fog of War.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#553]
**Describe the bug**
The token names for GM controlled tokens under FoW show up if a player client mouse pointer hovers over a token's position or by enabled Show Token Names in View menu.

Reported by Dorpond via Discord.

**Edit for additional detail:**

- Note that it shows up most easily with the Vision for the map set to Off.
- It will also show up with Vision set to Day, if there is no VBL in the way and the player token is in sight range.
- For maps set to Night, the same rules as Day applies plus there needs to be light sources by the tokens that are under the fog.

**To Reproduce**
1. Load attached campaign. (At bottom of issue.)
2. Start Server - Strict Token Ownership, Use Individual Views, Players Can Reveal Vision
3. Start player instance of MT and connect with name Hero.
4. Hover mouse pointer over coordinates:  (2,4), (2,7) and (4,6) and see token names appear.
5. Select Show Token Names from View menu and all the hidden token names appear.

**Expected behavior**
Expect that players would not be able to see the names of tokens that they can't actually see.

**Screenshots**
GM View
![Bug GM View](https://user-images.githubusercontent.com/34379254/62753229-eaf61f00-ba27-11e9-8a05-f29f86855382.png)
Player View hovering over token with mouse
![Bug Mouse Hover](https://user-images.githubusercontent.com/34379254/62753241-f9443b00-ba27-11e9-8b3e-e13bf5e83e48.png)
Player View - View Token Names enabled
![Bug View Token Names](https://user-images.githubusercontent.com/34379254/62753259-0a8d4780-ba28-11e9-95aa-8fec9ad701a3.png)

**MapTool Info**
- Version: 1.5.1, 1.5.3, Nerps 1.4.5.3
- Install: Any

**Desktop (please complete the following information):**
 - OS:  Windows
 - Version:  10

**Additional context**
MapTool 1.5.3 campaign - remove ".zip" ending.
[VisibleUnderFogTest153.cmpgn.zip](https://github.com/RPTools/maptool/files/3484691/VisibleUnderFogTest153.cmpgn.zip)

**Comment by JamzTheMan** [comment]
It's a new feature to support echolocation!

(Ha, that could work as a perception type eh lol)

Seriously though, ya, should be a easy fix. This sort of bug keeps cropping up. :-(

**Comment by Phergus** [comment]
I remember it popping up a while back and thought it even got fixed but I couldn't come up with the right search terms to find it if it really did happen.

**Comment by JamzTheMan** [comment]
I think the other issue was when you moved an NPC token in FoW you would see the name move around. That was an older issue I had fixed in my fork a while back.

Don't know if it's related code wise or not. It was opened by @Dorpond

**Comment by dorpond** [comment]
I believe back around Nerp’s 1.4.4.X (I think you fixed it in 1.4.4.0) we did have an issue where tokens moving around were being seen while they were under hard FOW. You did fix that, and I was extremely happy at the time, lol. Apparently I didn’t test it enough afterwords or it was introduced since then... you may want to check your Nerp’s change logs @Jamz

**Comment by Merudo** [comment]
I would love to see this fixed but I don't really know how [renderTokens()](https://github.com/RPTools/maptool/blob/d9cd344b637982c4bba0745ebf0eb2c674cfae91/src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java#L2802) works. It's about ~750 lines long too.

I don't really understand how the tokens under the fog are not rendered. I think it has something to do with clipping, but I don't really get it. Does anyone have a clue?

**Comment by JamzTheMan** [comment]
It basically just take 6 or so passes. First it writes the background tokens then object, then if gm, the hidden layer then token layer. Next it renders the fog layer and then finally it grabs all the tokens that have visible over FoW and renders those.

Granted, it's been more than a year since I have been in that code and it MIGHT be smart and not render tokens under the fow but Im pretty sure it just renders and clips everything layer by layer.

**Comment by Merudo** [comment]
I did some testing, and the bug only occurs when Map Vision is set to Off.

If you set the Map Vision to Day or Night, the labels no longer appear.

To tell the truth I'm no really sure what the expected behavior is when Vision is turned off.

**Comment by Phergus** [comment]
Vision isn't needed to use Fog of War.  Initially MapTool just had manual Fog of War removal like most other VTTs.   With vision not enabled on the map it should work the same.  Token names should never appear above FoW.

**Comment by Merudo** [comment]
Ok!

But does Vision do then? I don't understand what's the difference between "Off" and "Day".

**Comment by Phergus** [comment]
And the bug does show up on maps with Vision set to Day.  With Vision set to night, if there are light sources by the tokens,  the names also show up.

Off means now constraints on vision including VBL.  Day means VBL and vision limits apply.  Night means you must have light sources or vision allowing sight in the dark.

**Comment by Merudo** [comment]
More testing. I could replicate the bug in two scenarios:

1. Map Vision is set to off.
2. Auto Reveal is set to off, and the token in the FoW would be visible if Auto Reveal was set to on.

**Comment by Phergus** [comment]
It has nothing to do with revealing FoW or auto-reveal on movement.

This is GM (left) and Player(right) views of the map with it set to Day.  Note the token names are visible even though the tokens aren't.

![Screenshot 2019-08-13 13 15 31](https://user-images.githubusercontent.com/34379254/62970444-bccc6280-bdcc-11e9-92f0-5d65c38a5215.png)

**Comment by Merudo** [comment]
Works fine for me when View is set to Day...

https://i.imgur.com/Em2rDnh.png

**Comment by Phergus** [comment]
Did you enable Show Token Names from the View menu like it says in step 5?

**Comment by Merudo** [comment]
Yes, that's why you can see "Hero" under the token

**Comment by Merudo** [comment]
My server settings:

- Strict Token Ownership ON
- Auto Reveal on Movement ON
- Use Individual FOW ON
- Restricted Player Impersonation OFF
- Player Receive Campaign Macros OFF
- Use ToolTips for [] Rolls ON

**Comment by Phergus** [comment]
Or you had the mouse pointer over it.  Did you disable the token's sight?

Mostly the same settings.

![Screenshot 2019-08-13 13 44 01](https://user-images.githubusercontent.com/34379254/62972094-76790280-bdd0-11e9-8591-06d03a4d71f5.png)

**Comment by Phergus** [comment]
I bet the difference is Use Individual FoW.

**Comment by Merudo** [comment]
I set the same settings, with 1.5.3 and your fresh campaign file, and I still don't have the bug you mentioned when Map View is set to day.

**Comment by Phergus** [comment]
The campaign that was attached has the token vision set to short range.  Set it to Normal.

**Comment by Merudo** [comment]
Ok, I do get your result now.

But, if map vision is set to Day and token vision is set to Normal, then all the tokens are within visible range.

It seems to me the bug is with the FoW showing up - not with the token names.

**Comment by Phergus** [comment]
Like I said above, if you have Vision set to Day then the tokens must be in sight range of the viewing token.

> It seems to me the bug is with the FoW showing up - not with the token names.

No.  Fog is valid until is is cleared by exposing the visible area.  If the fog is hiding the token, the name should be hidden.

**Comment by Merudo** [comment]
> No. Fog is valid until is is cleared by exposing the visible area. If the fog is hiding the token, the name should be hidden.

When Map Vision is set to Day, shouldn't Fog be cleared automatically? Seems like the Fog is only clear once the token is moved once.

**Comment by Phergus** [comment]
Not necessarily.  A lot of folks don't use Auto-Reveal and quite a few don't let players reveal.  There are lots of story reasons why a token might start off in a restricted area of exposure before a full reveal is made.  As Show Token Names is a client-side setting, having MT reveal the presence of tokens within the FoW before desired can screw up a GMs plans.

Not too mention it just is wrong to show token names when no token is visible.

**Comment by Merudo** [comment]
Here is my understanding of this issue:

The code tags a token as visible or not, and if tagged visible, the name of the token is drawn.

To tag a token as visible, the code uses Vision (Off -> Always Visible) as well as vision range, VBL, etc. Typically, this work very well.

However, FOW is not taken into account for visibility. That's why if you type in your example

`[canSeeToken("Eagle", "Hero")]`

You'll see that the token is considered visible.

This is problematic when there is FoW over what could otherwise be seen by the token. This typically happens when Map Vision and/or Auto-Reveal on Movement are set to off, but can also occur when the FoW has not been updated to reflect modification to a token's vision.

**Comment by Phergus** [comment]
I believe you have summed up how the code works correctly.

@JamzTheMan said this:

> Next it renders the fog layer and then finally it grabs all the tokens that have visible over FoW and renders those.

Is it possible that the token names are being rendered after the fog layer or without a check for visibility?  Clearly the tokens themselves are being hidden correctly so the same switch(es) that keep a token hidden when it is technically in sight but under FoW should work for them?

**Comment by Merudo** [comment]
Is anyone working on this? I've noticed it has been in the 1.5.4 "to do" list for about 2 weeks now.

**Comment by Phergus** [comment]
Not that I know of.  I took a glance at the code in ZoneRenderer down in the label section around 3427.  Didn't see any checks for whether the label would be in an exposed area or not as is done for the token itself. (See L3188 for an example)

So it's yours if you want to dig in.

**Comment by JamzTheMan** [comment]
Ya, I haven't had the time. Figured I would look at it if no one else did (I usually will assign it to myself in those cases).

Feel free to comment if you want to look at it otherwise...

**Comment by Merudo** [comment]
My PR request #607 fix the token names visible over FoW for the case where either Vision is Off or Auto-Reveal on Movement is off.

Not sure if my solution is efficient  but it seems to work. I do a call to  zone.isTokenVisible(), which is slow because it checks for overlap with the FoW, but I don't think there is any other way to check for visibility when Vision/Auto-Reveal are off.

**Comment by Phergus** [comment]
Tested.   Change does correct the issue.

**Comment by Phergus** [comment]
@dorpond Test when you get the chance.  Will close this for now.
