### ISSUE TITLE
"set" functions to send only the relevant data to other clients (not the whole token)

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#555]
**Is your feature request related to a problem? Please describe.**
Each time a function operating on a token is called, the whole token is sent to other clients through MapTool.serverCommand().putToken().

This can cause heavy slowdowns on tokens with a large number of properties.

Examples of functions affected: setProperty(), setState(), setPC(), etc.

**Describe the solution you'd like**
At least some of these functions should not send the whole token, and instead send the modification to be done on the token.

For example, setProperty() should only send the property and its new value, instead of the entire token.

**Comment by JamzTheMan** [comment]
@CoreDevs should I create a feature branch to merge all the function/putToken changes into or just go straight into develop for testing? I don't think there is much other dev going on but if anyone is uneasy with these changes we can branch off for testing.

**Comment by Phergus** [comment]
I have no significant objection to bring it straight into develop.

**Comment by Azhrei** [comment]
Agreed.

Any structural changes (such as modifying how token updates work) should probably be done separately as I can see lots of little issues cropping up over time.

**Comment by Phergus** [comment]
Following functions tested and are updating clients as expected.
- bringToFront
- moveToken
- removeTokenFacing
- resetProperty
- resetSize
- sendToBack
- setAllStates
- setGMNotes
- setLayer
- setLibProperty
- setNotes
- setNPC
- setOwnedByAll
- setOwner
- setPC
- setProperty
- setPropertyType
- setSize
- setState
- setTokenDrawOrder
- setTokenFacing
- setTokenHeight
- setTokenShape
- setTokenSnapToGrid
- setTokenWidth

**Comment by JamzTheMan** [comment]
So these functions have all been updated? I'm trying to run some tests but it's hard with only 1 or 2 PC's connected.  I really need to do a test on Sunday with a bunch of friends for a full effect but I'll see what I can test.

**Comment by JamzTheMan** [comment]
Having issues getting properties (getting prompt for missing vars in my campaign, not sure what is broken but something is...)

**Comment by Phergus** [comment]
Those were all updated.

re: getting properties - I know changes were made to various get functions to allow getting properties from tokens on other maps.  Haven't had time to test any of that yet.

**Comment by Merudo** [comment]
I found the bug regarding the missing vars.

I forgot a **break;** statement in my code, which results in the token getting a bogus property type when **setstate** is called. This would result in the default properties no longer being defined, resulting in the promp for missing vars.

The bug is fixed in #564. My apologies for the inconvenience.

**Comment by JamzTheMan** [comment]
Cool, glad it wasn't a nasty bug but an easy fix. It wasn't blowing things up in my test so I was worried it was going to be an edge case of forgotten code somewhere. :)

I will retest when I get a chance.

**Comment by Phergus** [comment]
No documentation changes needed.  All modified functions tested across server/client.
