### ISSUE TITLE
Hidden/Object tokens don't show name when no notes present.

### ISSUE THREAD

**Issue by DoggieBert** [RPTools/maptool#558]
**Describe the bug**
When clicking on a hidden/object token when on the token layer a popup is created with the format:
Name field
Notes field
"GM Notes" - GM Name field
GM Notes field

If there is nothing in the Notes field both the notes and the Name are omitted.  If there is nothing in the GM Notes field both the GM Notes and GM Name are omitted.  

**To Reproduce**
1. Make a token on the hidden or object layer.
2. Go to the token layer
3. Click on the hidden/object token

**Expected behavior**
I would expect the Name and GM Name to be present whenever something exists in those fields rather than being tied to the Notes and GM Notes fields.

Perhaps changing the format to:
Name field (GM Name field)
Notes field
"GM Notes"
GM Notes field

This would allow each field to be easily omitted if blank (except the name field, which should always be filled) while preserving all the information that was put on the token.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/53953028/62805642-2e976a00-bab6-11e9-9d7b-11166fb9205e.jpg)
This token has a name, but I can't see it here.

**MapTool Info**
- Version: 1.5.3
- Install: Upgrade [1.5.2]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [10 Pro]

**Additional context**
N/A

**Comment by Merudo** [comment]
Pull request #570 should fix this.

**Comment by Phergus** [comment]
Doesn't quite match the users request.  One of his points was that the  GM name doesn't show if there are only player notes.

For player notes only, should be:

**Token Name (_GM Name_)**
\<player notes\>

Where GM Name and surrounding parenthesis are only displayed for GM's (duh).

In the case of GM notes only:

**Token Name (_GM Name_)**
**GM Notes**
\<gm notes\>

Should suffice.  And for both:

**Token Name (_GM Name_)**
\<player notes\>
**GM Notes**
\<gm notes\>

And of course the player view when there are player notes:

**Token Name**
\<player notes\>

**Comment by Merudo** [comment]
I thought that what I did?

**Comment by Phergus** [comment]
You did.  Apparently the instance of MapTool I was running was off the older code.

Nevermind.

**Comment by Phergus** [comment]
Tested and working as requested.
