### ISSUE TITLE
JWrapper build needs to include version number in generated installs

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#56]
The generated install dmg/exe/tar file needs to contain the version number.

**Comment by JamzTheMan** [comment]
I had gone back and forth on that, personally I didn't want to update the website I had for every build and I created a class to generate a custom "installing... splash" with the version #.

But it makes sense for the main distro, we can simply change the bundle name in the jwrapper-template.xml to:

<BundleName>MapTool-@buildVersion@</BundleName>

**Comment by cwisniew** [comment]
Was not being done due to bug in gradle build script, has been fixed
