### ISSUE TITLE
Add "mapName" to TokenStateFunction

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#563]
**Is your feature request related to a problem? Please describe.**
It would be nice to add a "mapName" argument for functions "getState", "setState", "setAllStates".

**Additional context**
I would be glad to update the wiki but I do not have the permission to do so.

**Comment by Phergus** [comment]
Code changes complete.  Documentation needed.

**Comment by Phergus** [comment]
@Merudo  Send me an email address via direct message on Discord and I'll set up an account for you on wiki.

**Comment by Merudo** [comment]
Documentation updated:

http://www.lmwcs.com/rptools/wiki/getState
http://www.lmwcs.com/rptools/wiki/setState
http://www.lmwcs.com/rptools/wiki/setAllStates

**Comment by Phergus** [comment]
Issue complete.

**Comment by Phergus** [comment]
Functions tested across maps.
