### ISSUE TITLE
getPropertyDefault() and setLayer() undocumented parameters

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#569]
**Describe your question**
The functions getPropertyDefault() and setLayer() have undocumented parameters.

getPropertyDefault() usually returns the default value for the specified property of the current token. However, if the second argument is specified, it instead returns the default value for the given token type (such as "Basic"), and the current token is ignored.

setLayer() takes a third argument (after token) called "forceShape". If set to 0, the setLayer() will not change the shape of the token.

I was wondering what I should do with these extra parameters?

Bug:  NPE error if getPropertyDefault() is used with one parameter and there is no current token

**Comment by Phergus** [comment]
These should get documented on the wiki including examples of their use.

**Comment by Merudo** [comment]
Sure.

About setLayer(), should the extra parameter be moved around? Right now, it's after tokenId, which goes against the convention for the other functions.

**Comment by Phergus** [comment]
Oooh, that's unfortunate.   I suspect that change would break quite a few existing macros so we'll leave it that way.

**Comment by Merudo** [comment]
Updated the documentation:

https://lmwcs.com/rptools/wiki/getPropertyDefault
https://lmwcs.com/rptools/wiki/setLayer
