### ISSUE TITLE
Issues with TokenLightFunctions

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#574]
**Describe the bug**
There are a number of issues with the hasLightSource(), clearLights(), setLight(), and getLights() functions.

1.  hasLightSource(), setLight(), and getLights() give a NPE if the light type entered doesn't exist
2.  The FoW is not updated automatically after running clearLights() & setLight(). Also see #213
3. The functions do not take token id and mapname as parameters
4. The functions send the whole token instead of only sending the property of interest.

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Wiki Updated:
- [ ] hasLightSource()
- [ ] clearLights()
- [ ] setLight()
- [ ] getLights()

**Comment by Merudo** [comment]
> Wiki Updated:
> 
> * [ x]  hasLightSource()
> * [ x]  clearLights()
> * [ x]  setLight()
> * [ x]  getLights()

**Comment by Phergus** [comment]
@Merudo   You could have just clicked the ones in my post.  :)

**Comment by Merudo** [comment]
I tried to, but it wouldn't work.

**Comment by Phergus** [comment]
Well that stinks.  So much for making it easier.  :(

**Comment by Merudo** [comment]
It's fine. I quoted your code, added the xs and remove the quote marks. It was indeed easier :)

**Comment by Phergus** [comment]
All functions tested with optional token ID and map name parameters across client/server.
