### ISSUE TITLE
Add id and mapname to sight functions

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#578]
**Is your feature request related to a problem? Please describe.**
The functions setHasSight() and hasSight() do not take token id as a parameter.
The functions canSeeToken(), getSightType() and setSightType() do not take mapname as an argument.

**Describe the solution you'd like**
All the mentioned functions take token id and mapname.

**Comment by Phergus** [comment]
@Merudo - See comments in response to yours on #320

**Comment by Merudo** [comment]
Documentation added:

https://lmwcs.com/rptools/wiki/setHasSight
https://lmwcs.com/rptools/wiki/hasSight
https://lmwcs.com/rptools/wiki/canSeeToken
https://lmwcs.com/rptools/wiki/getSightType
https://lmwcs.com/rptools/wiki/setSightType

**Comment by Phergus** [comment]
All functions tested with optional token ID and map name parameters across client/server config.
