### ISSUE TITLE
JWrapper test build 1.4.1.0 fails to launch fat jar

### ISSUE THREAD

**Issue by joshsziegler** [RPTools/maptool#58]
I tried the 1.4.1.0 build on your server. It brought up the launcher, but wouldn't launch the `MapTool-1.4.1.0-fat.jar` even after I selected it.

I'm on Windows 10 64bit.

Of note, it works now that I installed Java. I didn't have it installed to begin with. This is supposed to be the self-installer though, correct?

The 1.4.0.3 build works fine (with Java installed).

**Comment by JamzTheMan** [comment]
This should be resolved as of 1.4.1.2
