### ISSUE TITLE
Modifying token no longer updates VBL

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#582]
**Describe the bug**
If a token with VBL is modified by a macro function that changes its VBL such as moveToken() or setTokenFacing(), the VBL is not updated.

**Expected behavior**
The VBL is properly updated to reflect the updated token.

**MapTool Info**
- Version: 1.5.3 Develop branch 8/18/2019
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Bug found by @JamzTheMan at https://github.com/RPTools/maptool/pull/556#issuecomment-522270087

**Comment by Phergus** [comment]
Tested following macro functions with server and player client with multiple tokens with VBL.

- setState
- setAllStates
- setLayer
- setSnapToGrid
- setTokenFacing
- setTokenShape
- moveToken
- setSize
- setTokenHeight
- setTokenWidth

Updates to vision/vbl all happened as expected.

**Comment by Phergus** [comment]
And for good measure...
 - resetSize
 - setHasSight
 - setVisible

**Comment by Phergus** [comment]
@JamzTheMan   Since you reported the bug, I'll let you flag it as **tested** and close it once you are happy.

**Comment by Phergus** [comment]
Too slow.   Closing.
