### ISSUE TITLE
Add macro functions to get Frame/Dialog properties by name.

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#584]
**Is your feature request related to a problem? Please describe.**
I often create frames related to a character. For example, I created a frame to list a character's equipment, another for the character's spells and another for a character's traits.

I don't want a dozen frames open for the same property, so I tend to give a set frameName to a property ('say, "Equipment" or "Spells") that is the same regardless of the character. That way, at most one frame can be opened for each property.

Problem is, it is very hard or near impossible to know which character is being displaying by the frame. This causes issues when I may need to redraw the frame, for example when a character is changed.

**Describe the solution you'd like**
An optional argument "value" for dialog() and frame() that can store arbitrary information into the frame/dialog. The "value" doesn't impact the html or other properties of the dialog/frame, but it can be retrieved by the following functions.

Two functions, named something like 

- getFrameProperties(frameName)
- getDialogProperties(dialogName)

Which return a json with the following properties: width; height; temporary; title; value.

Example JSON: {"width":300, "height":500, "temporary": 0, "title":"Equipment of Bob", "value": "Bob"}

That way it would be able to extract some information (such as the character displayed) from the title. The other properties might come handy too.

**Additional context**
Short discussion with aliasmask: https://forums.rptools.net/viewtopic.php?f=3&t=28194

**Comment by Merudo** [comment]
My PR implements the two functions.

I am unable to return the "temporary" field for the frame, because the property is currently not supported (see #585)

**Comment by Phergus** [comment]
Wiki pages added:

- http://www.lmwcs.com/rptools/wiki/getFrameProperties
- http://www.lmwcs.com/rptools/wiki/getDialogProperties

**Comment by Phergus** [comment]
Should we close this and leave the issue with the "temporary" property for later?

**Comment by Phergus** [comment]
Answering my own question.   Issue #585 deals with the "temporary" property.

Closing.

**Comment by Phergus** [comment]
Both functions tested okay.
