### ISSUE TITLE
Frame property temporary=1 is ignored

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#585]
**Describe the bug**
If a frame is opened with temporary=1; maptool still remembers the window size between openings

**To Reproduce**
1. Use the following macro:

`[frame("Frame Test", "width=300; height=500; temporary=1;"): {A test} ]`

2. Resize frame.
3. Close frame.
4. Run the macro again. The frame has the same size as before.

**Expected behavior**
Maptool doesn't remember the size if temporary is set to 1.

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
I don't remember how to add the WindowListener to clear up the frame properties after clicking the "Close" button. Adding the following to the constructor did not work:

```
   addWindowListener(
        new WindowAdapter() {
          @Override
          public void windowClosing(WindowEvent e) {
            closeRequest();
          }
        });
```

**Comment by Merudo** [comment]
Figured it out. PR #596 fix it fully.

**Comment by Phergus** [comment]
Tested against 1.5.3 and 1.5.4 develop branch.  Working as expected now.
