### ISSUE TITLE
Add json.toVars() function to turn json objects into vars like varsFromStrProp()

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#591]
**Is your feature request related to a problem? Please describe.**
There is no built-in function to turn a json object into variables. Users have to make their own varsFromJson() function. 

**Describe the solution you'd like**
The function varsFromStrProp() could take a "delim" parameter, that if set to json turns a json into variables.

**Describe alternatives you've considered**
Adding another function varsFromJson() or **json.toVars()**. Either of these would be fine really.

**Comment by Phergus** [comment]
Tested.  Working as described.  Still needs wiki entry.

**Comment by Merudo** [comment]
Wiki entry added.

**Comment by Phergus** [comment]
Closing.
