### ISSUE TITLE
Hex map movement doesn't display right

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#594]
**Describe the bug**
For tokens with snap-to-grid on hex maps, (1) the distance numbers partially outside of cells, and (2) there is no blue line forming the path.

**To Reproduce**
1. Create hex map with a token with snap-to-grid.
2. Enable Show Movement Distance
3. Move the token around and notice the numbers show on the hex border and the absence of blue path (compare to square map)

**Expected behavior**
The numbers show up within the hexes, and there is a blue line forming the path.

**Screenshots**
![img](https://i.imgur.com/IeKmSfy.png)

![img](https://i.imgur.com/P5O9OJh.png)

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Yeah.  I guess the numbers could be further inside the hex.  Note that on the iso grid they are completely outside of the grid cell.

**Comment by Merudo** [comment]
What about the blue line? Is the absence of it a bug, or is it something intended only for square grids?

**Comment by Phergus** [comment]
I think it was more that no one using hex grids cared enough to complain.  I don't expect it will be difficult to add in.

**Comment by Merudo** [comment]
My PR #599 fixes this issue. The new movement looks like this:

![img](https://i.imgur.com/2Gx02Gu.png)

**Comment by Phergus** [comment]
Tested new code against both hex types.  Hex grids maintain their superiority to all other types.
