### ISSUE TITLE
Ghost token if map change during token move

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#595]
**Describe the bug**
During a token move, if the user changes map and click on another token, the original token becomes a "ghost" and cannot be moved anymore, and its path is permanently drawn on the map.

**To Reproduce**
1. Start to move a token with the arrow keys, but don't complete the move.
2. Change to another map.
3. Select any token on that map.
4. Return to the original map.
5. The token cannot be moved anymore.

**Expected behavior**
The token can still be moved again.

**Screenshots**
The dragon token cannot be moved anymore, and the path can't be removed:

![img](https://i.imgur.com/pmJKGfG.png)

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
Workaround:   Drag another token onto the starting point of _frozen_ token so as to get the overlapping tokens indicator in the top-right.  Double-click on the overlap indicator and then select the _frozen_ token to move it.

**Comment by Azhrei** [comment]
Wow, good catch.  It amazes me sometimes how people find these kinds of bugs, just the number of permutations that need to be tried...

**Comment by Merudo** [comment]
A lot of the bugs I find, I stumble into them while testing out new code.

This one I found out while taking the pictures for #594 :P

**Comment by Merudo** [comment]
PR #926 fixes this issue.

**Comment by Phergus** [comment]
Tested.  Working correctly now.
