### ISSUE TITLE
Internal methods checkNumberOfParameters() and getTokenFromParam() to be consolidated

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#613]
**Is your feature request related to a problem? Please describe.**
The functions `checkNumberOfParameters` (throws the appropriate exception if the # of parameters is incorrect) and `getTokenFromParam` (get a token from a parameter list) are both pretty handy and are declared multiple times in the code.

It makes maintaining such functions difficult.

**Describe the solution you'd like**
These functions can be consolidated and moved somewhere else, such as in `AbstractFunction`

Related issue: #629

**Comment by Azhrei** [comment]
Thank you!  I've been wanting to do this for a long time!  There's a huge amount of redundancy in some of the macro function code, of which this is a prime example.  It's a massive amount of updates, however; how do we test that the changes don't break something?

**Comment by Phergus** [comment]
On a basic level, as each macro functions class is updated we will need to note all the functions defined in that class and then craft test campaigns that use those macro functions in specified ways so that we can use corresponding macros to test and verify.  Some automation is possible but some will require test monkeys as well to provide visual confirmation.

**Comment by Merudo** [comment]
According to Intellij, all 9 instances of the `checkNumberOfParameters` are identical.

Intellij also reports that 6 out of 7 functions `getTokenFromParam` are identical. Only the one in `TokenLocationFunctions` is different.

So it seems to me the risk of bugs is minimal.

**Comment by Azhrei** [comment]
They only appear 9 times and 7 times?  Much fewer than I expected.

I was thinking the bugs would be from the refactoring of the code around the function calls, not the functions themselves.

The good news is that this should speed up macros.  The JIT compiler will see the function calls combined and probably decide to compile them...

**Comment by Merudo** [comment]
My idea was to simply move the two function somewhere else, delete the duplicates, and keep the exact same function calls.

Not a big project by any mean.

I'm sort of curious what would be the best place to put the two functions though? I noticed `AbstractFunction` is actually in the `parser` package so we might not want to add it to that.

**Comment by Azhrei** [comment]
Yes, I realize that now.  I thought it was going to be a bigger job. :)

You have three choices, I think.
+ put them in AbstractFunction
+ extend AbstractFunction, put them there, then refactor existing code to use the new class
+ create a static “utility” class in the package and put them there.

They don’t require any knowledge of _this_ so I might go with the third option.  We have other classes like this, such as SwingUtil (or whatever it’s called).

Anyone else have a preference?

**Comment by Phergus** [comment]
Option 3 seems like the most straight-forward and makes it more likely for them to get used when others add new functions.

**Comment by JamzTheMan** [comment]
I'm partial to option 3 as well.

There's probably a lot of functions classes that don't have this method defined but do the "check" anyway. One of those "didn't know it existed so copied from a bad example".

**Comment by Merudo** [comment]
There is also a [fourth choice](https://github.com/RPTools/maptool/issues/629#issuecomment-525946427) proposed by @Azhrei : a new class `Param` the extends the List class and holds the parameter values.

**Comment by Phergus** [comment]
Consolidation complete.  No problems noted in testing.  No visible changes for end-users.
