### ISSUE TITLE
Token Selection After Token and Map Move

### ISSUE THREAD

**Issue by dorpond** [RPTools/maptool#616]
**Describe the bug**
If you move a token with the left mouse button, and while continuing to hold that left button, move the map via the right mouse button (to continuing that token movement), the whole token selection process changes, because now we have to select a token first, then click it again to drag it. The problem fixes itself if the map is moved at all. 

**To Reproduce**
Just drop a few tokens on a map, move one of them, and while holding the left mouse button, move the map with the right mouse button. You will immediately notice how token selection behavior changes for the worst. Keep in mind however, that if you scroll the maps at all, the problem fixes itself, so avoid that during testing.

**Expected behavior**
We shouldn’t have to double select a token to move it. We should be able to have token 1 selected and click + move token 2. 

**Screenshots**
N/A

**MapTool Info**
- Version: 1.5.4rc1 and same behavior in 1.4.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 

**Additional context**

**Comment by Merudo** [comment]
I'm not sure if I understand the issue? The right click button just adds waypoints in my version.

**Comment by dorpond** [comment]
Right mouse button (holding it down) also moves the map around. Often times in my sessions, let’s say I grab some tokens and wish to move them far away to another location, I would hold down the left button, then while holding that, hold the right mouse button to pan the map, and continuing moving the tokens. 

Easier to show than explain.

**Comment by Phergus** [comment]
1. Left click and drag a token
2. While continuing to hold left mouse button down, right-click and drag to pan map (also sets waypoint).
3. Release both mouse buttons at the same time.
4. Left-click on a different token. It won't be selected and selection is in an odd state at that point.

**Comment by dorpond** [comment]
[Token Move Issue.zip](https://github.com/RPTools/maptool/files/3538229/Token.Move.Issue.zip)

**Comment by dorpond** [comment]
Not sure how I closed it, but now it is reopened.

**Comment by Merudo** [comment]
> 1. Left click and drag a token
> 2. While continuing to hold left mouse button down, right-click and drag to pan map (also sets waypoint).
> 3. Release both mouse buttons at the same time.
> 4. Left-click on a different token. It won't be selected and selection is in an odd state at that point.

Step #3 was the one I was missing, thanks.

**Comment by dorpond** [comment]
"3. Release both mouse buttons at the same time."

Please note that in my case, I don't have to release both buttons at once because when I drag, pan, drag, pan, the right mouse button is already released at final destination. The only button that is pressed the entire time during the "frog jumping" is the left. The right button you are consistently pressing and depressing, as you are basically frog jumping across the map, so when my tokens are finally in position, only the left mouse button is pressed, so I simply let it go, try to click+move on any one token, but cannot, because the behavior has changed to "select a token first, then click and move it" (click token, release it, then click+move it) for them to work. But if I pan the map at all, this bug fixes itself and I can go back to click+move the tokens, as normal. 

Whew, tough to describe in words. Let me see if I can make another video but one that shows which mouse buttons are being pressed.

**Comment by dorpond** [comment]
Here is an updated video. I hope this helps?

[MT Move Bug.zip](https://github.com/RPTools/maptool/files/3854202/MT.Move.Bug.zip)

**Comment by dorpond** [comment]
So I looked back through history and loaded up many Maptool's all the way back to 1.0.b112, and the problem existed back then as well... (Sad face). I was hoping to have some sort of change log to look back on, but this bug has been here forever it seems.

**Comment by Merudo** [comment]
I found an easy way to reproduce this bug.

1) Make sure a window is docked to the left or right of the map (example: resource library on the left)
2) Select a token, and start dragging them.
3) While dragging the token, pan the map until the token is under the window, and release the pan button.
4) Drop the token anywhere you want.
5) Left-click on a different token. It won't be selected and selection is in an odd state at that point.

IMO the key aspect of the bug, is panning while dragging a token that is under a docked window.

**Comment by Merudo** [comment]
PR #1444 fixes this issue.
