### ISSUE TITLE
sendTokensToBack and bringTokensToFront cancel recent token changes

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#617]
**Describe the bug**
Using the sendToBack and bringToFront option by right clicking on a token can cancel changes to the token done through macros, such as through `setProperty`, `setState`, `moveToken`, etc.

**To Reproduce**
1. Start a fresh campaign, put a Dragon token there
2. Type

`[setState("Dead",1,"Dragon")]`

3. Send the token to back, or bring it to the front by right clicking on it.
4. Dragon token is no longer dead.

**Expected behavior**
The changes to the token are maintained.

**MapTool Info**
- Version: 1.5.4 RC1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
The issue is that `setTokenProperty` that is used by many macros does not update the token on the `server` object. It updates the tokens on every client though (including the host's).

Almost nothing in MapTool makes use of the tokens on the actual `server`. However, `sendTokensToBack` and `bringTokensToFront` do. These two methods send the server's version of the tokens to very client, which erases changes made to a token.

This particularity of `sendTokensToBack` and `bringTokensToFront` explains why [similar bugs occurred in the past](https://github.com/JamzTheMan/MapTool/issues/23).

[RPTools Forum Thread](https://forums.rptools.net/viewtopic.php?f=3&t=28305&p=273759#p273759)

**Comment by Merudo** [comment]
PR #618 fixes this issue.

**Comment by Phergus** [comment]
Tested.  ChangeLog updated.
