### ISSUE TITLE
Edit Map dialog needs a Clear Map option.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#622]
**Is your feature request related to a problem? Please describe.**
If you have created a new map and choose a map image in the process you cannot later remove that map via the Edit Map dialog.

One reason to do this is if you decide it would be better to redraw the map with MapTool drawing tools and you have already created the VBL and positioned various tokens and objects.  Drawing over the top of the existing map image means you wouldn't have to redo all of that work.  Once the new, drawn version is completed, getting rid of the original cuts down on campaign size and transfer times.

**Describe the solution you'd like**
A button or check box to remove the current map image.

**Describe alternatives you've considered**
You can replace an existing map with an empty image or just a smaller image.

**Comment by Tdue21** [comment]
Isn't this issue obsolete? You can remove a map image by clicking the small icon at the top right corner of the preview. 
![image](https://user-images.githubusercontent.com/2953375/107862415-02983a00-6e4d-11eb-84f0-9fd86111b636.png)

**Comment by Phergus** [comment]
Yup.  Was put in under #1270.

**Comment by Tdue21** [comment]
Thought so ;)
