### ISSUE TITLE
1.5.4 RC1 telling me 1.5.3 is more recent

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#627]
**Describe the bug**
The maptool release candidate 1.5.4 RC1 tells us to "update" to 1.5.3

**To Reproduce**
1. Install Maptool 1.5.4 RC1
2. Launch and read the update message

**Expected behavior**
No message to update if you are on the most recent release candidate.

**MapTool Info**
- Version: 1.5.4 RC1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
Is there a way to add a variable to the Manifest so that we can test if the current version is a beta / release candidate or not?

**Comment by Merudo** [comment]
PR #757 solves this issue.

**Comment by Phergus** [comment]
Not sure how to test this until we get a an actual build.  So closing and crossing fingers.

**Comment by Merudo** [comment]
Seems like it's working fine. I'm not getting prompts to update to `1.5.6` when on `1.5.7 RC1`.

**Comment by Phergus** [comment]
Confirmed.

**Comment by JamzTheMan** [comment]
Woot!
