### ISSUE TITLE
Incorrect error message if assert() second parameter is number

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#637]
**Describe the bug**
The error message to `assert` is the following if the second parameter is a number:

> macro.function.assert.mustBeString

It should instead take the correct value from `I18N`

**To Reproduce**
1. Type [assert(0,5)]

**Expected behavior**
The message displayed should be taken from `I18N`.

**MapTool Info**
- Version: 1.5.3, 1.5.4 RC1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
PR #638 solves this issue.

**Comment by Phergus** [comment]
Tested.  Error message is now localized:
`Second argument to "assert": "5" must be of type String.`
