### ISSUE TITLE
Changing token from NPC to PC is automatically enabling vision

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#645]
**Describe the bug**
Editing a token via the Edit Token dialog is automatically enabling vision

**To Reproduce**
1. Drop token on map.
2. Double-click on token to open Edit Token dialog.
3. Change type to PC
4. Click on OK to close dialog.
5. Re-open dialog to see that Has Sight is checked.  This may already have been obvious on the map depending on map settings.

**Expected behavior**
Expected Has Sight checkbox to keep its setting when changing unrelated token settings.

**MapTool Info**
- Version: 1.5+
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by dorpond** [comment]
Is that a bug, @Phergus? I think as far back as I can remember, is that PC’s have vision on by default. I mean, let’s say my default tokens placed on the map as DM is NPC, and I want to make those tokens PC’s, why should I have to go into the vision settings and turn that on also? PC’s automatically have vision - done.

Or am I not understanding this report?

**Comment by Phergus** [comment]
I guess it has always worked that way.  I've just never noticed as it doesn't change the Has Sight checkbox when the NPC/PC toggle is flipped.  Setting it back to NPC does not disable vision which is inconsistent.

So I'll file this as not-a-bug.  When I think of all those milliseconds I lost by manually clicking on Has Sight never to be regained.
