### ISSUE TITLE
Can't pass json data with a form submit

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#650]
When trying to pass a json structure with form input the parser gets confused and truncates the data. 

This is probably a really old issue and has a work around (encode the data first). Probably haven't seen much problem with this because people either probably gave up or just don't use json data.

Original Post: https://forums.rptools.net/viewtopic.php?f=20&t=28318&p=273851#p273850

**Comment by Merudo** [comment]
I think the issue is with how `FormView` reads the data (getFormData) from a form.

**Comment by aliasmask** [comment]
I think we can close this one then. Just chalk it up to an MT quirk.

**Comment by aliasmask** [comment]
Although, a note in the Wiki under form tutorial may be appropriate.

**Comment by aliasmask** [comment]
Found another issue related to the form submit: https://forums.rptools.net/viewtopic.php?f=53&t=26670&p=275588#p275580

If you have a form:
```
[H: link = macroLinkText("process@"+getMacroLocation(),'all')]

[dialog("Test"): {
   <form action="[r: link]" method="json">
      <input type="hidden" name="num" value=1 />
      <input type="submit" />
   </form>
}]
```
And process it
```
[r: macro.args]
```
You get: `{"num":"1"}`

You can see the value of 1 is returned as "1". I'm not really sure what could/should be done with this. If I put value="1" vs value=1 if there is something to distinguish it from a string vs a number. The issue only is an issue because of json updates retaining a string that looks like a number as a string (which is a good thing). Old macros like the DiceBox blow up due to this change.

**Comment by Phergus** [comment]
Looks like the workaround noted by @Merudo above no longer works either.

Tested with `dialog5()` in 1.6.0 alpha 7 with the same results.

**Comment by Merudo** [comment]
Yep, it got broken in MapTool 1.5.12

**Comment by Phergus** [comment]
So looking at `submitData()` in `HTMLPanelFormView` and I see this:
```
} else if (dataStr.length > 2) {
	jobj.addProperty(dataStr[0], dataStr[1]);
}
```
I'm sure there is a reason for it but not sure what it is as the else block that follows would do the same thing if the URL.decoder failed.

So just out of curiosity I replaced it with this:
```
} else if (dataStr.length == 2) {
	if (StringUtils.isNumeric( dataStr[1])) {
	  jobj.addProperty(dataStr[0],new BigInteger(dataStr[1]));
	} else {
	  try {
		double d = Double.parseDouble(dataStr[1]);
		jobj.addProperty(dataStr[0],new BigDecimal(d));
	  } catch (NumberFormatException nfe) {
		jobj.addProperty(dataStr[0], dataStr[1]);
	  }
	}
}
```
And using this macro:
```
[H: link = macroLinkText("process@"+getMacroLocation(),'all')]
[dialog("Test"): {
   <form action='[r: link]' method="json">
      <input type="hidden" name="num1" value=123 />
      <input type="hidden" name="num2" value=3.1416 />
      <input type="hidden" name="num3" value=-9 />
      <input type="hidden" name="notanum" value=-12f3.2 />
      <input type="submit" />
   </form>
}]
```
I get this:
```
{
  "num1": 123,
  "num2": 3.1416,
  "num3": -9,
  "notanum": "-12f3.2"
}
```
So it looks like this is fixable if we just make the fallback in the NFE the contents of the last `else` block.

**Comment by Merudo** [comment]
PR #1351 solves the number appearing as a string, and restores the previous workaround.

**Comment by Phergus** [comment]
Figured there was a better way to do it.  The PR works for my trivial example.  I'll have to find some other examples with forms to test with.

@merudo I assume the same kind of fix will need to be done for the HTML5 support?

**Comment by Merudo** [comment]
@Phergus you are right! Good catch.

**Comment by Merudo** [comment]
PR #1353 adds a similar fix to the HTML5 frames and dialogs.

**Comment by Phergus** [comment]
Tested new PR.  Working as expected.  Could us some testing with more complex form examples.

**Comment by Phergus** [comment]
A slightly more complex form.
![Screenshot 2020-03-05 11 36 58](https://user-images.githubusercontent.com/34379254/76014269-8a07ca00-5ed6-11ea-92c0-d6262c422d98.png)
results in:
```

{
  "element_1": "Now is the time",
  "element_2": 42,
  "element_3_1": 1,
  "element_3_3": 1,
  "element_4": 2,
  "element_5": 3,
  "element_6_1": "Joe",
  "element_6_2": "Blow",
  "element_7_1": 12,
  "element_7_2": 7,
  "element_7_3": 1941,
  "element_8_1": 13,
  "element_8_2": 62,
  "element_8_3": 0,
  "element_8_4": "PM",
  "element_9_1": 999,
  "element_9_2": 555,
  "element_9_3": 1212,
  "element_10_1": "1 Park Place",
  "element_10_2": "Suite Judy Blue Eyes",
  "element_10_3": "Atlantic City",
  "element_10_4": "NJ",
  "element_10_5": 12345,
  "element_10_6": "Azerbaijan",
  "element_11_1": 1,
  "element_11_2": 38,
  "form_id": 101368,
  "submit": "Submit"
}
```
Campaign File with form macros.
[FormWithJSONBug.cmpgn.zip](https://github.com/RPTools/maptool/files/4294533/FormWithJSONBug.cmpgn.zip)

My testing is concluded.

**Comment by Merudo** [comment]
Arrays don't work:

> <input type="hidden" name='[r:"name[first]"]' value="john">
> <input type="hidden" name='[r:"name[last]"]' value="smith">

results in the following `json`:

```{"name[first]":"john","name[last]":"smith"}```

**Comment by Azhrei** [comment]
The array example I posted above should result in an array named “num” that contains two numbers and is inside an object.  It’s a bummer if it doesn’t work.  Oh well.
