### ISSUE TITLE
MapTool 1.4.1.8:  Press <spacebar>+<alt> in some sequence and it dumps the campaign for a new one with no confirmation dialog.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#654]
**Describe the bug**
I've done this twice, now.  In MapTool 1.4.1.8, I pressed the <spacebar> and <alt> key in some sequence and it dumped the current campaign and replaced it with a new campaign.  There was no confirmation dialog.

Also, while trying to reproduce this bug I did at a different time see a confirmation dialog.

You have to press the <spacebar> and <alt> keys together almost randomly to find this problem.  Sometimes it happens and sometimes it doesn't, but seems very easy to reproduce.

**To Reproduce**
Keep pressing the <spacebar> and <alt> keys together randomly.  I'm not sure exactly what sequence creates this problem, but try pressing and holding first the <spacebar> and then the <alt> key and then visa versa.  You may have to do this sort of randomly a few times but I got the issue in less than about 15 seconds of trying.
**Expected behavior**
I would remove this feature and require people to use the File menu's "New Campaign" menu option.  This feature appears to be undocumented and is far too dangerous to keep around.

Alternately, fix it so that it always appears with a dialog AND that dialog must have a default option "No" or "Cancel".

**Screenshots**

**MapTool Info**
- Version: 1.4.1.8
- Install: New

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux [Ubuntu, Debian, CentOS, etc], MacOS]
 - Version [10, 18.04]

Windows 10

**Additional context**
From MapTool, paste info from menu Help -> Gather Debug Information...
You can also attach files (drag and drop here) such as log files or paste a file sharing link.

**Comment by JamzTheMan** [comment]
This bug has already been addressed. Please upgrade.

**Comment by adventuremagic123** [comment]
Ok.  Thank you!
