### ISSUE TITLE
Bring to Front/Send to Back sometimes need to be done twice

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#658]
**Describe the bug**
Sometimes selecting a token and using Arrange -> Bring to Front/Send to Back requires a second attempt before it works.

**To Reproduce**
1. Start a new campaign
2. Drop two tokens on default map.
3. Set both to Large size (makes it easier to select them later)
4. Drag the second token so that it partially overlaps the first.
5. With 2nd token selected, right-click and Send to Back - token goes back behind other token
6. Right-click and Bring to Front - nothing happens
7. Repeat action and token comes to the front.
8. Now select 1st token, right-click and Bring to Front - token comes forward.
9. Right-click and Send to Back - nothing happens.
10. Repeat action and token goes to back.

**Expected behavior**
Should only take one action to bring token forwards/backwards.

**Screenshots**
Positioning of tokens for ease of selection.
![Screenshot 2019-09-05 12 17 55](https://user-images.githubusercontent.com/34379254/64368338-51df0780-cfd7-11e9-94ac-26ecfb4573bc.png)

**MapTool Info**
- Version: 1.5.2+
- Install: New, Upgrade [previous version], or JAR [Java Version]

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
Can't replicate this with 1.5.4 RC1 and the develop branch.

**Comment by Phergus** [comment]
Curious.  It's a 100% reproducible for me on two different PCs.

**Comment by Merudo** [comment]
Ok I experienced the bug. But I'm having trouble reproducing it, most of the time it works just fine.

**Comment by Phergus** [comment]
With existing campaign files with lots of token, some tokens always work while others behave as noted above or sometimes take 3 or more attempts.  The only way I found to reliably produce it for me was the steps noted above on a clean campaign.

**Comment by Phergus** [comment]
I could not reproduce with versions prior to 1.5.2.

**Comment by Merudo** [comment]
Pretty sure my PR #662 fixes it.

**Comment by Phergus** [comment]
Will do.

**Comment by Phergus** [comment]
Tested and working as expected.

**Comment by Merudo** [comment]
Thanks, @Phergus !

The issue was that `getSmallestZOrder` and `getLargestZOrder` rely on an correctly ordered `tokenOrderedList` (the two functions respectively return the first and last entry of that list).

That list was not reordered on the server after the sendToBack / bringToFront. That is ow fixed.
