### ISSUE TITLE
New Server Option: GM Reveal FoW for Unowned Tokens

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#665]
**Is your feature request related to a problem? Please describe.**
Some GM wish to not reveal FoW when moving "enemy" tokens.

**Describe the solution you'd like**
A new Start Server (policy) option to add a checkbox so tokens that have no ownership do not reveal FoW.

**Additional context**
When a GM moves a token that has any ownership (even if it's the client), be it PC or NPC, it will reveal FoW.  But now, if new server option is selected, any token that has no ownership set. those tokens will not automatically reveal FoW when moved or facing is changed.

Players still reveal FoW based on other server options as normal.

Linked issue #663 adds new option to getInfo("server") macro function

**Comment by JamzTheMan** [comment]
This should be tested by @dorpond and @Phergus and any others interested in QA due to FoW changes are potentially game disruptive if improper FoW is revealed.

**Comment by Phergus** [comment]
So far so good on testing.  Exposure seems to be working as expected.  More testing to be done tomorrow.

**Comment by Phergus** [comment]
Testing with new option enabled (GM moved "enemy" tokens expose) appears to be working as expected with some basic testing.  Really only makes sense to me if IFoW is also enabled.  More testing to be done.

**Comment by JamzTheMan** [comment]
Yes.  when using iFoW/iView we ownership doesn't really matter anymore does it? Hence the issue.

Maybe this should be a sub option under iView?

What's the difference again between iView and IFoW? Is the later just the history (so you can see where your friend has been?) But if you just have iView you only see what you currently can see but you share what everyone has seen? Is that about right?

**Comment by Phergus** [comment]
My understanding.

iView
ON - a player sees only what his owned tokens can see
OFF - a player can see what all PC tokens can see

IFoW
ON - Exposed FoW areas are **not** shared between tokens and each token has it's own exposed FoW areas kept in the token object.  Players have no idea where other player tokens are at unless they are within sight of one of their tokens.
OFF - Exposed FoW areas **are** shared and that info is kept in map object.  Every player can see the areas exposed by player tokens.

**Comment by Phergus** [comment]
Wiki page updated.

**Comment by Phergus** [comment]
Tested.  Cry 'Havoc!,' and let slip the dogs of war.
