### ISSUE TITLE
Add playStream / stopStream functions to stream audio from URL

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#667]
**Is your feature request related to a problem? Please describe.**
Music can be immensely useful for setting the right atmosphere. It would be great to have a function to stream music from an URL or a local file.

**Describe the solution you'd like**
New function: `playStream(uri, cycleCount, volume)` where:

`uri`: the url or uri path to the sound, example: 

`[playStream("http://mywebsite/mysong.mp3")]`
`[playStream("file:///C:/mysong.mp3")]`

`cycleCount`: how many times to play the resource. If -1, repeats indefinitely
`volume`: value from 0 to 1 determining the volume level

New function: `editStream(uri, cycleCount, volume)` to change the cycleCount or volume of stream.

Same parameters as `playStream()`

New function: `stopStream(uri, remove)` to stop a stream

`uri`: like above, if not provided or if set to "*" stops all sounds
`remove`: if 1 will remove stream from memory

**Describe alternatives you've considered**
There are other ways to implement sound (check #615 for an extended discussion), but regardless of what other features we implement, streaming sound from a server should always be useful.

**Additional context**
A more narrow version of #615

**Comment by Merudo** [comment]
PR #668 implements the requested change.

**Comment by Phergus** [comment]
A `getPlayingStreams()` function to get a JSON array of stream objects could be handy.

```
[{
    "uri":"uriPath", 
    "cycleCount":#, 
    "volume":#,
    "currentTime":#,
    "currentCount":#
}]
```
Adding optional start and stop times to `playStream()` would be nice for when you have SFX that are perhaps too long or have a lot of padding at the beginning/end.

**Comment by Phergus** [comment]
Should start/stop time be in seconds instead of milliseconds?  Milliseconds might not be very friendly for users.

**Comment by Phergus** [comment]
I see that streams which play to the end still show as PLAYING instead of STOPPED.  This is just what the MediaPlayer returns so maybe a handler needs to be registered for onEndOfMedia to explicitly stop the stream.  Otherwise a user checking if the stream has reached the end will have to compare currentTime to stopTime to know if it is really playing.

May not be important enough to both with.

**Comment by Merudo** [comment]
Sure, I can change both to milliseconds.

The status thing seem to be a [quirk of JavaFX](https://stackoverflow.com/questions/38098496/javafx-mediaplayer-status-stuck-on-playing). I like your fix.

**Comment by Merudo** [comment]
PR #671 implements your suggestions.

**Comment by Phergus** [comment]
A little late now but what might have been nice would have been to give each stream a name or tag.

That way would only deal with ugly URIs once:
```
[h: result = defineStream(name, URI, preload)]
[h: abort(result)]
[h: playStream(name, cycles, vol, start, stop)]
[h: stopStream(name, 0)] <!-- stop but leave cached -->
some stuff happens
[h: playStream(name)] <!-- uses current settings -->
```
Maybe another option to defineStream could be tags so that a stream could be given a string list of tags like ambient, sfx, crowd, fire, wind, etc.

Thoughts?

**Comment by JamzTheMan** [comment]
I've heard worse ideas...

**Comment by Phergus** [comment]
New audio functions playStream, stopStream, editStream and getStreamProperties test.  Worked as expected.

**Comment by Phergus** [comment]
Are you thinking Global as in in available to all macros or just in the context of the audio functions?
