### ISSUE TITLE
Launcher broken for .app 

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#67]
The launcher looks for the mt.cfg and translations in current directory, this will not work for .app (and possibly wrapped windows exe) as the current directory will not be the directory where these programs exist but rather an application support directory.

**Comment by JamzTheMan** [comment]
Is the languages really broken? I moved those into the jar so those are loaded via resource bundle.

**Comment by cwisniew** [comment]
Come to think of the it may just be the string for the dialog box that informs the user that the config file can't be found just has no entry in the properties files.
