### ISSUE TITLE
Add "PropertyType" option for getTokens

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#676]
**Is your feature request related to a problem? Please describe.**

It would be useful to augment `getTokens` to return only tokens of a given property type as defined in Campaign Properties (ex:"Basic").

For example if I get set a property type of "Trap", I could have `getTokens` only return trap tokens.

Not only would it be helpful for getting the right list of tokens, but it could improve the speed of `getTokens` when it is possible to narrow down the property type of the desired tokens.

**Describe the solution you'd like**
An additional field to the `condition` parameter of `getTokens` called `propertyType`, which can be a JSON array of property types, or a single type as a string

**Comment by JamzTheMan** [comment]
That would be a useful addition.

**Comment by Merudo** [comment]
Documentation for `getPropertyType` added to [getTokens()](https://lmwcs.com/rptools/wiki/getTokens)

**Comment by Phergus** [comment]
Tested.  Working as expected.
