### ISSUE TITLE
Very slow getTokens() when distance is specified

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#683]
**Describe the bug**
Compared to 1.4.1.8, Maptool 1.5+ is much slower when using the macro function `getTokens` with a `distance` or `area` argument.

**To Reproduce**
1. Create a map in 1.4.1.8 with a lot of tokens
2. Use `getTokens()` with a distance/area option in `conditions`.
3. Try the same in 1.5+. The search takes between 2 and 3 times as much time.

**Expected behavior**
Performance in 1.5+ that is as good or better than in 1.4.1.8

**Additional context**
I've noticed that the search is actually crazy fast when using the "NO_GRID" metric.

So the problem is most likely related to walkers being slower now.

**Comment by Merudo** [comment]
PR#686 improves the speed with `area` as parameter.

**Comment by Merudo** [comment]
PR #686 fixes this for the `area` option.

**Comment by Merudo** [comment]
@Phergus mentioned that diagonals are problematic in the forum.

I checked and they absolutely are, especially on hex grids.

In fact, for large enough maps, even the Pointer can generate lag if the diagonal distance is big enough.

Here is a map that illustrates the issue: https://mega.nz/#F!aQpHyA6A!z4YFPcz-9YD99snFtGBdBA

If you click on the macro you get a large delay, even though the are only 2 tokens on the map. But, if you move the token at the same distance but in the same row/column, the `getTokens` time is dramatically reduced.

**Comment by Merudo** [comment]
PR #703 improves the speed of `getTokens` by a lot when `distance` is specified.

**Comment by Phergus** [comment]
Doing some testing and the improvement is significant.

Maps have 7680 tokens in range of source token.

Map | Metric | MT 1.5.4 | New Code
-- | -- | -- | --
Hex | 1-2-1 | 5.676 | 0.484
Hex | No Grid | 0.881 | 0.361
  |   |   |  
Square | 1-2-1 | 2.894 | 0.500
Square | No Grid | 0.950 | 0.388

**Comment by Phergus** [comment]
Tested and working as expected.
