### ISSUE TITLE
getDistanceToXY bugged with "NO_GRID" metric

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#684]
**Describe the bug**
`getDistanceToXY` returns incorrect value when the distance metric `NO_GRID` is selected

**To Reproduce**
1. Put an Eagle token immediately to the left of Dragon token
2. Type

`[r:getDistanceToXY(getTokenX(0, "Dragon"), getTokenY(0,"Dragon"), 0, "Eagle", "NO_GRID")]`

3. Look at the answer. It's a weird number close to 10, like

`12.506718194634434`

4. Remove "NO_GRID". Answer is "1".

5. Type

`[r: getDistance("Dragon", 0, "Eagle", "NO_GRID")]`

which also returns "1".

5. Repeat test but this time move Eagle token 2 away from the Dragon. Now with `NO_GRID`, you get something like

`13.26868493860639`

while the two other methods give "2".

**Expected behavior**
`getDistanceToXY` returns the correct distance, equivalent to `getDistance` for a token at the `x,y` coordinates.

**MapTool Info**
- Version: 1.5.4

**Comment by Phergus** [comment]
Did you notice it is dependent upon where the tokens are placed on the map?
Dragon token at 1,0 and Eagle at 0,0:
`0.693108938046538311`
Dragon token at 10,10 and Eagle at 9,10
`13.877319625922002`

**Comment by Merudo** [comment]
Yes, I think the issue is that when "NO_GRID" is selected, the x and y are interpreted as pixels coordinates, while with all other metrics they are interpreted as cell coordinates.

Very confusing to say the least, and contradicting the wiki. I suggest make it cell coordinates as default, with extra parameter to use pixel coordinates.

**Comment by Phergus** [comment]
Note this bug has been there since at least 1.4.0.5.

**Comment by Phergus** [comment]
> Yes, I think the issue is that when "NO_GRID" is selected, the x and y are interpreted as pixels coordinates, while with all other metrics they are interpreted as cell coordinates.
I suppose that makes sense but I'm don't think that a distance of 13.877 is correct on a 50px/grid map.  Should be somewhere in the 50 pixel range if not 50 pixels exactly.

Also the distance between Dragon and Eagle should be the same whether going Dragon to Eagle or Eagle to Dragon which it isn't.  I suspect it's doing upper-left to center which would explain the larger number when going left to right versus right to left.

**Comment by Merudo** [comment]
> > Yes, I think the issue is that when "NO_GRID" is selected, the x and y are interpreted as pixels coordinates, while with all other metrics they are interpreted as cell coordinates.
> 
> I suppose that makes sense but I'm don't think that a distance of 13.877 is correct on a 50px/grid map. Should be somewhere in the 50 pixel range if not 50 pixels exactly.

Is use `x` and `y` as pixel coordinates but returns a distance in cell units...

As I said, very confusing.

**Comment by Phergus** [comment]
Ahh.  I see what you are saying.  Definitely not intuitive.

**Comment by Merudo** [comment]
Also, where from the token should the distance be calculated for large tokens?

From the center of the source token?
From the token's side closest to the target?
From the center of the cell closest to the target?

**Comment by Merudo** [comment]
PR #707 fixes this issue.

**Comment by Phergus** [comment]
As a general comment I would expect distance to be center to center.

**Comment by Merudo** [comment]
So would I. PR #707 implements this.

Previous code calculated distances from the top left corner cell.

**Comment by Merudo** [comment]
I introduced a bug in #707. When the server is started, the default metric should be the server's metric, not the one in user preferences.

**Comment by Merudo** [comment]
Documentation updated: https://lmwcs.com/rptools/wiki/getDistanceToXY

**Comment by Phergus** [comment]
Tested.  Working correctly now.
