### ISSUE TITLE
Empty asset url in <input> HTML locks up MapTool

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#685]
**Describe the bug**
Empty asset URL in <input> tag causes MapTool to sit in an endless loop with no error and UI becomes unresponsive as it waits for macro code to finish:

```<input type="image" name="test" value="test" src="asset://" />```

**To Reproduce**
1. Go to chat and enter: ```<input type="image" name="test" value="test" src="asset://"/>```

**Expected behavior**
A ? should be used, the following works ok ```<img src="asset://" />```

**Screenshots**
Not needed, easy to reproduce

**MapTool Info**
- Version: 1.x
- Install: New, Upgrade [previous version], or JAR [Java Version]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux [Ubuntu, Debian, CentOS, etc], MacOS]
 - Version [10, 18.04]

**Additional context**
From MapTool, paste info from menu Help -> Gather Debug Information...
You can also attach files (drag and drop here) such as log files or paste a file sharing link.

**Comment by Irarara** [comment]
@Phergus This seems to be fixed now (with #2507?). You get a nice big red X now instead of the client hanging.

**Comment by Phergus** [comment]
Bonus bug fix!

Getting an IOException to the log but not locking up is a good thing.

**Comment by Irarara** [comment]
Yeah. I think that always gets thrown the first time it fails to fetch something of a given ID.

**Comment by Phergus** [comment]
That sounds right.

I think this one is complete.
