### ISSUE TITLE
setTableEntry accepts and stores empty assetId

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#687]
**Describe the bug**
setTableEntry lets you pass an empty string "" as the imageId parameter. It then internally stores this as "asset://" which is bad, see issue #685 

**To Reproduce**
1. Create a new table "Test"
2. Run ```[r: setTableEntry("Test", 1, "Test", "")]```
3. Run ```[r: getTableEntry("Test", 1)]```
4. It will return a JSON with "asset://" for assetId

**Expected behavior**
Either throw exception error or store table entry with no string value

**Comment by Phergus** [comment]
PR #819 submitted:

For Table functions addTableEntry, createTable, setTableImage and setTableEntry, passing an empty AssetID string will no longer apply the bad "Asset://" string to the relevant image entry. Also fixed: getTableImage() was throwing an NPE if no table image was set.

**Comment by Phergus** [comment]
Needs testing.
