### ISSUE TITLE
Bugged "Manhattan" metric, metric ignored in distance functions for iso maps.

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#688]
**Describe the bug**
`Manhattan` as default metric gives wrong value for diagonals - as if metric was set to `ONE_ONE_ONE`.

Additionally, argument `metric` is ignored for isometric maps in `getDistance`, `getDistanceToXY`, and `getTokens`.

**MapTool Info**
- Version: 1.5.4
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
PR #690 fixes this.

**Comment by Phergus** [comment]
Tested.  Token dragging distance and distance from macro functions reporting correctly.
