### ISSUE TITLE
PR #691 Breaks Imagepanel Zoom

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#694]
@pnichols04 This change breaks the ability to zoom the images. Using ctrl+mousewheel or the slider sets the images to smallest setting and doesn't zoom after that.

![image](https://user-images.githubusercontent.com/8051654/64926056-91b7a300-d7be-11e9-88c2-1aa321b3c3a4.png)

If you could create Issues for PR's in the future, it would be handy for tracking. Now we have to create a Bug issue to track this to make sure it's fixed or rolled back before 1.5.5.

_Originally posted by @JamzTheMan in https://github.com/RPTools/maptool/pull/691#issuecomment-531589313_

**Comment by JamzTheMan** [comment]
@pnichols04
I can't assign an issue to you unless you created it or you at least comment on it. GitHub is funny that way

**Comment by Phergus** [comment]
Tested.  Zoom working again.
