### ISSUE TITLE
MapTool confuses right-click with right-drag

### ISSUE THREAD

**Issue by pnichols04** [RPTools/maptool#696]
Some users may right-click on a token, intending to open the popup menu, and find that MapTool fails to visibly respond.  

**To Reproduce**
Right-click on a token, preferably with a high-DPI mouse.  Observe that sometimes a menu opens, and sometimes it doesn't.

**Expected behavior**
MapTool should reliably open a the token popup menu when that is a user's intent in right-clicking.

**Screenshots**
Not applicable.

**MapTool Info**
- Version: 1.5.3, .4
- Install: multiple

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Version 10, 18.04, 19.04

**Additional context**
With debug breakpoints at `mouseReleased(...)` in PointerTool.java and DefaultTool.java, it can be observed that MapTool is interpreting *any amount* of movement between the right-mouse press and the right-mouse release as a map drag.  When PointerTool then tries to process the mouseReleased, isDraggingMap has been set, but it will not be cleared until the end of that method, when super.mouseReleased() causes DefaultTool to clear it.

**Comment by Phergus** [comment]
Tested.  Working as expected.
