### ISSUE TITLE
getDistance, metric NO_GRID, snap-to-grid: distance is inconsistent

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#699]
**Describe the bug**
Using getDistance using the NO_GRID metric on snap-to-grid tokens returns the distance based on their hidden pixel coordinates.

This is a problem if `Snap Token While Dragging` is disabled in the preferences.

**To Reproduce**
1. Disable `Snap Token While Dragging` in the preferences.
1. Get a Eagle & Dragon snap-to-grid tokens on a square map.
2. Type

`[r: getDistance("Eagle", 0, "Dragon", "NO_GRID")]`

3. Take note of the number.
4. Now drag and drop the Eagle token to the same cell.
5. Type the distance command again. The numbers don't match up.

**Expected behavior**
The distance stays constant.

**MapTool Info**
- Version: 1.5.4
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
In addition, if `Snap Token While Dragging` is disabled, moving a snap-to-grid token then disabling snap-to-grid causes the token to jump to a different spot.

**Comment by Merudo** [comment]
Issue is also present if using a non-snap to grid token to move a selection including snap-to-grid tokens.

**Comment by Phergus** [comment]
Assuming the first described issue is that two medium tokens on top of each other weren't giving a distance of 0 but instead were giving seemingly random values less than 1.0.

Tested.  Issues described working as expected.
