### ISSUE TITLE
State and a Bar of the same name the activate and deactivate together

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#706]
**Describe the bug**
If you have a State and a Bar of the same name activate and deactivate together

**To Reproduce**
1. Add a State
2. Add a Bar with the same name
3. Turn on (unhide) Bar - see state appear as well
4. Turn off State, see both bar and state disappear

**Expected behavior**
Bars and States should not interact this way.

**Screenshots**

**MapTool Info**
- Version: 1.5.5 beta 3
- Install: Upgrade from 1.5.4

**Desktop (please complete the following information):**
 - Linux Ubuntu
 - Version 18.4.3 LTS]

**Additional context**
Easy workaround but unexpected.

**Comment by Merudo** [comment]
I had no idea until now because I don't use bars, but "bars" are considered to be "states" right now.

**Comment by JamzTheMan** [comment]
I suspected as much as they act pretty much the same way...

**Comment by Phergus** [comment]
I'm curious as to how he created a bar and state with the same name.  In Campaign Properties as soon as you type in a name that is already there, the Add button is greyed out.

**Comment by Phergus** [comment]
Ahh.  You can Update an existing State or Bar with a new name and that isn't blocked.

**Comment by Merudo** [comment]
Should states and bars be split or should we just stop users from renaming in this way?

**Comment by Phergus** [comment]
My thinking is that now is not the time to separate them as that would mandate a campaign version change.

Putting in a check to keep users from creating a bar or state with an existing name should be sufficient for now.  Obviously a warning should be given that the requested name already exists.

**Comment by melek** [comment]
I've added the check to prevent using the Update to duplicate state/bar names in #2354. 

I did not add any kind of warning about why the button disables - in the future it would certainly be friendly to let the user know why a button is disabled in the dialog, but the other conditions don't do that so I kept it simple.

**Comment by Phergus** [comment]
Tested.  Unable to create a Bar with the same name as a State and vice-versa.  Bar & State functions working as expected.
