### ISSUE TITLE
Campaign macro changes not received when connecting to server

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#713]
**Describe the bug**
Campaign macro changes done after the server started but before the player joined are not received by the player.

**To Reproduce**
1. Start a server.
2. Add a campaign macro.
3. Have a player join.
4. The player doesn't see the macro made in step 2.

**Expected behavior**
The player receives the most up-to-date campaign macros.

**MapTool Info**
- Version: 1.5.3, 1.5.4, develop branch
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
PR #714 fixes this issue.

**Comment by Phergus** [comment]
Tested.  Working as expected now.
