### ISSUE TITLE
Missing repository results in exception to the console

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#715]
**Describe the bug**
Opening up a campaign with an invalid repo shows a lengthy exception message to the console.

**To Reproduce**

1. Use gradlew to run Maptool with console
2. Open up the Bag of Tricks or any other campaign with an invalid repo
3. Look at the console, you will see an error message close to this one:

```
(AssetLoader.java:126) [Thread-20] ERROR net.rptools.maptool.model.AssetLoader - I/O error retrieving/saving index for 'https://dl.dropboxusercontent.com/u/9052014/W42-BOT-REPOSITORY/index.gz
java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/9052014/W42-BOT-REPOSITORY/index.gz
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245) ~[?:?]
        at java.net.URL.openStream(URL.java:1117) ~[?:?]
        at net.rptools.lib.FileUtil.getBytes(FileUtil.java:175) ~[main/:?]
        at net.rptools.maptool.model.AssetLoader.getIndexMap(AssetLoader.java:116) [main/:?]
        at net.rptools.maptool.model.AssetLoader.addRepository(AssetLoader.java:65) [main/:?]
        at net.rptools.maptool.model.AssetManager.updateRepositoryList(AssetManager.java:109) [main/:?]
        at net.rptools.maptool.client.MapTool.setCampaign(MapTool.java:954) [main/:?]
        at net.rptools.maptool.client.AppActions$63.run(AppActions.java:2345) [main/:?]
```

**Expected behavior**
The error message show either appear as a Maptool error message, or in the console as a warning.

**MapTool Info**
- Version: 1.5.3, 1.5.4
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
Closed because from inspecting the code, I believe this is the intended behavior.

**Comment by Azhrei** [comment]
Thanks, but I don't think an exception is ever the right choice for the user, even if it's documented.

I'd rather see a pop up that warns the user that the URL is not accessible and offers a checkbox so that the user isn't warned about this URL again.  (Of course, the UI would need some way to turn off that checkbox at some point s well.)

I'm going to reopen so as to allow further discussion.

**Comment by Merudo** [comment]
User doesn't see the exception unless they are using the console.

**Comment by Phergus** [comment]
@Merudo   I think the point is that it shouldn't be throwing an exception to the console (where almost no one will see it) and that it should be letting the user know they have a bad repo in the campaign properties.   Should probably prompt the user to Remove/Ignore the bad repo.

**Comment by pnichols04** [comment]
I'd suggest going one step further, and have the popup say

> This repo doesn't work.  I'm removing it from your list. 
>
>                                                         [ Kthx ]

I don't think remove/ignore is a meaningful choice for the user, and it introduces two new code paths that would have to be maintained instead of just one.

**Comment by Merudo** [comment]
@pnichols04 I think automatically removing the repo is dangerous, especially since web services go temporarily offline every now and then.

**Comment by rkathey** [comment]
I agree. A simple warning should do along with a brief description of how
to remove the offending repository.

**Comment by Azhrei** [comment]
The server should get the prompt I mentioned; the players should get a simple warning, “Repo not available”.  Players may be behind firewalls or otherwise unable to get to a repo, but it should never be turned off completely for a player since they don’t have control over the Campaign object.

**Comment by Merudo** [comment]
Are these error messages adequate:

When hosting server:

![image](https://user-images.githubusercontent.com/7371085/84233477-06064500-aab8-11ea-9a62-99ba2ac4e4c3.png)

For the player:

![image](https://user-images.githubusercontent.com/7371085/84233549-2b934e80-aab8-11ea-99d2-a7fc18abc5ae.png)

**Comment by Phergus** [comment]
Tested.  Exception no longer output to console or log file.  User gets warning that repo isn't accessible.
