### ISSUE TITLE
Easier way to execute macro on another client

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#716]
**Is your feature request related to a problem? Please describe.**
It's relatively tricky for a GM to execute macros on other client. There is `broadcast(execLink())`, but it has the disadvantage of not executing the macro on the current client.

In fact, about half the wiki page for `broadcast` is about how to circumvent the unsatisfying `execLink` solution through the Bag of Tricks function `bot_execAllPlayers`.

**Describe the solution you'd like**
A new function, potentially called `execAllPlayers`, to run a macro on other clients.

**Comment by JamzTheMan** [comment]
Why not just add a third parameter to execlink that accepts gm, all, or name(s)?

**Comment by JamzTheMan** [comment]
I be nice if we could figure out how to call UDF's like this.

**Comment by Merudo** [comment]
PR #721 add the extra third parameter to `execLink`.

**Comment by JamzTheMan** [comment]
Nice.

**Comment by Azhrei** [comment]
Silly question, but...  there's already something in place to prevent players from executing macros on the GM's system, right?  And what about an obnoxious player who uses execLink to cause another player's system to start spamming playStream() or similar functions?  Is there a check to prevent that kind of abuse, too?

**Comment by Merudo** [comment]
`execLink` is a protected function, so only gms can run it.

**Comment by Azhrei** [comment]
Ah, makes sense.  Thanks. :)

**Comment by JamzTheMan** [comment]
Mmm, I have functions expecting on the GM client today... Although I specifically want and need that.

When it's a players turn he can click a next init button which fires off a chain of macros. But I need any pop ups like poison checks and such pop on the GM's client. (This could be a check for the player or the next time in init)

So if that's a bug please do NOT fix it, it'll break my framework logic. :)

Unless I get an onInitiativeChange event.

**Comment by cwisniew** [comment]
> Mmm, I have functions expecting on the GM client today... Although I specifically want and need that.
> 
> When it's a players turn he can click a next init button which fires off a chain of macros. But I need any pop ups like poison checks and such pop on the GM's client. (This could be a check for the player or the next time in init)
> 
> So if that's a bug please do NOT fix it, it'll break my framework logic. :)
> 
> Unless I get an onInitiativeChange event.

Any non player editable "auto exec" (i.e. it executes when clicking the button not just copies text into text box) macro can run trusted functions. Its not only GM that can execute...

**Comment by Phergus** [comment]
Wiki updated by Merudo.

**Comment by Phergus** [comment]
Closing.
