### ISSUE TITLE
Add option "gm-self", "self", & "all" to broadcast

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#718]
**Is your feature request related to a problem? Please describe.**
The macro function `broadcast` only recognize "gm" as a special argument.

Options "gm-self", "self" and "all" would also be useful.

**Describe the solution you'd like**
Have these options work for `broadcast`.

**Comment by Merudo** [comment]
PR #719 implements this.

**Comment by Merudo** [comment]
Documented the changes in https://lmwcs.com/rptools/wiki/broadcast

**Comment by dorpond** [comment]
Not sure if this is related, but I still use /self at the top of my macros, to have the output go to me. 

So whatever changes you make to broadcast, please keep that “slash at the start of the macro” functionality for us ‘simple minded’ macro builders. :p

**Comment by Merudo** [comment]
Don't worry, I only added new functionality. I didn't change the old.

So unless you have "gm-self", "all", "none", or "self" as the second argument of `broadcast`, everything will work the same.

**Comment by Phergus** [comment]
Tested.  New parameters working as expected.
