### ISSUE TITLE
The only option for find/replace in the macro editor is 'Replace All'

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#722]
**Describe the bug**
When performing a Find and Replace in the Macro Editor there is no option to replace the found item, only replace every occurrence of it.

**To Reproduce**
1.Create a new macro
2. place the following text in it
[h:summary="this contains the Skill and Ability descriptions" ]

[h:obj=json.set("","Skill","d4",Ability,"<text deleted>")]
[h:jsonArray=json.append(jsonArray,obj)]
[h:obj=json.set("","Skill","d6",Ability,"<text deleted>")]
[h:jsonArray=json.append(jsonArray,obj)]
[h:obj=json.set("","Skill","d8",Ability,"<text deleted>")]
[h:jsonArray=json.append(jsonArray,obj)]
[h:obj=json.set("","Skill","d10",Ability,"<text deleted>")]
[h:jsonArray=json.append(jsonArray,obj)]
[h:obj=json.set("","Skill","d12",Ability,"<text deleted>")]
[h:jsonArray=json.append(jsonArray,obj)]

3. With the macro editor still open, select Edit->Replace from the main menu bar.
4. The find/replace window will appear. Type in Ability in the find, and "Ability" to replace it with.
5. Click Find to find the next occurrence.
6. The Replace button is greyed out. Only the Replace All button works.

**Expected behavior**
You should be able to 'Find' the next occurrence and replace it one at a time vs. having to replace everything in the macro editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/231042/65245295-f3735800-dab1-11e9-9ed1-3d01d8467b29.png)

**MapTool Info**
- Version: 1.5.5 beta 3
- Install: Upgrade 1.5.4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**

**Comment by JamzTheMan** [comment]
Ok maybe not intuitive then, but press "Find" and it goes to first selection, then Replace should unlock. Clicking that will replace and and go to next selection.

FWIW this dialog is built into and uses the Rsyntax common dialogs so changes (if they were requires) would require changing the upstream lib or making not own.

**Comment by rkathey** [comment]
That's what it doesn't do. The find button never ungreys.

**Comment by Phergus** [comment]
Also closing the search window also doesn't clear the matching highlights.  You have to close the editor.

**Comment by JamzTheMan** [comment]
I wil have to test, it use to work :-/

**Comment by JamzTheMan** [comment]
Make sure you are not on the "last" one as well, as you have direction "down".

Try click the first line of the macro and hit find again?

**Comment by JamzTheMan** [comment]
OK ya, confirmed... this use to work so not sure what happened. Will have to see if that broke in 1.5.0 or after (or before).  Maybe there is an option that enable/disables it or if it's a bug in the root lib... Can update the lib to see if that fixes it or not as well.

**Comment by Phergus** [comment]
Checked this in Nerps 1.4.5.4 and it was broken the same way.

**Comment by Phergus** [comment]
Tested.  Find/Replace now works for single Replace action.
