### ISSUE TITLE
getViewArea and getViewCenter don't return correct pixels

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#724]
**Describe the bug**
The functions `getViewArea` and `getViewCenter` return the "zoomed" pixels, not the actual pixels.

**To Reproduce**
1. Zoom in a map a bunch on (0,0).
2. Type `[getViewArea(1)]` or `[getViewCenter(1)]`.
3. You'll get crazy numbers, such as `startX=7600` even though you zoomed in on the origin.

**Expected behavior**
The functions return the actual pixels. 

**MapTool Info**
- Version: 1.5.3, 1.5.4
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
[Bug identified](https://github.com/RPTools/maptool/issues/649#issuecomment-533213008) by @Phergus

**Comment by Phergus** [comment]
Tested.  Both functions now return pixels in the 1:1 map space and not in the zoomed map image space which couldn't be used for other macro functions that needed map coordinates.
