### ISSUE TITLE
Remove duplicated Initiative info from getInfo("server").

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#739]
**Describe the bug**
_initiative owner permissions_ and _initiative movement locked_ are both in the info returned by `getInfo("campaign")` making returning _initiative owner permissions_ in `getInfo("server")` redundant and it isn't a configuration set on the Start Server dialog.

Should be removed.

**To Reproduce**
1. Run `getInfo("campaign")` and see both initiative settings in the result.
2. Run `getInfo("server")` and see just _initiative owner permissions_.

**Expected behavior**
Only needed in one place.  Remove from server info.

**MapTool Info**
- Version: 1.5.4
- Install:  Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
See discussion in #738

**Comment by xdy** [comment]
My PR https://github.com/RPTools/maptool/pull/980 should fix this.

**Comment by Phergus** [comment]
Tested.   _initiative owner permissions_ no longer included in `server` info.
