### ISSUE TITLE
Modify getTokenNames() to return owned and unowned tokens

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#742]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to return a list of owned or unowned tokens in a single call. You must loop through all the tokens on a map checking for ownership.

**Describe the solution you'd like**
Modify getTokenNames() 'owner' option accept 'any' and 'none' as player names to return all owned tokens when 'any' is supplied and return all unowned tokens when 'none' is supplied. The function will check if a player name is on the Ownership tab or if the 'All Players' checkbox is on to determine whether or not a token is 'owned'

**Describe alternatives you've considered**
Generate a new option for getTokenNames() 'isOwned' set to true or false to generate the list.

**Additional context**

**Comment by JamzTheMan** [comment]
I would still like to see an array option that accepted player names, any, all, & none.

You may need a mixture of ownership. For instance, you may want:
`Give me all tokens that are owned by any or explicitly'  or
`Give me all tokens that are owned explicitly only' or
'Give me all tokens at are owned by all only`

A sample use case: 
> I want to send a dialog prompt to all tokens that have a single owner. If the token is owned by all I can not send a dialog message for that token and do not want it in the list.

**Comment by Phergus** [comment]
And lets not confuse the difference between asked for _all owned tokens_ and _tokens owned by all_ .

**Comment by Merudo** [comment]
> I would still like to see an array option that accepted player names, any, all, & none.

If I pass an array of player names, should it return any token that matches a name, or should it return only the tokens that match every name?

**Comment by Phergus** [comment]
I would assume that matches one or more names.

**Comment by JamzTheMan** [comment]
Good question, man, I could see needing both. But more than anything "match one or more"

What if the current "owned" was expanded to 0|1|ANY|ALL|NONE
And a new "owner" was added that accepted a array list of names

**Combined they could produce:**
Owned: ANY
Owner: Bob, Mike, Marc
Returns a list of tokens that have any of those names as owners

Owned: ALL
Owner: Bob, Mike
Returns a list of tokens that are owned by BOTH Bob & Mike

Owned: ALL
Owner: Bob, Mike, ALL
Returns a list of tokens that are owned by BOTH Bob & Mike & Owned by All

Owned: ANY
Owner: []
Returns a list of tokens that are owned by any one

Owned: ALL
Owner: []
Returns a list of tokens that have "Owned by All" checked

Owned: None
Owner: []
Returns a list of tokens that are not owned by anyone

---

Is that too much? Or? (Enough test cases or missing some?)

**Comment by Azhrei** [comment]
Good discussion!  Keep in mind games that have temporary alliances between players, such as Risk or Diplomacy, where a player may want to select all tokens owned by an ally (or an enemy).  It sounds like the above takes care of that...

The empty case for ALL seems a bit obscure given that specifying names everywhere else means a real name or lack thereof, yet for ALL it means the “owner by all” checkbox specifically.  Dunno, I suppose as long as it’s documented clearly...?

**Comment by JamzTheMan** [comment]
Yea, not sure. I was considering since they are actually several other options, you would see the ALL, ANY, NONE, which would for most cases with the secondary owner array used did more advanced needs?

**Comment by Merudo** [comment]
Maybe have it this way?

`Owned:ANY`- tokens owned by any player
`Owned:BYALL`- tokens owned by all players
`Owned:NONE`- tokens owned by no players
`Owned:SELF`- tokens owned by the current player (equivalent to "1")
`Owned:NOTSELF`- tokens not owned by the current player (equivalent to "0")
`Owned:array` - tokens owned by one or more of the players listed in the array

**Comment by Azhrei** [comment]
Ah, I like the use of the more specific “BYALL” vs “ALL”.  Good idea!

But then how do you specify that you want a list of tokens owned by all of the players in an array?

Perhaps `Owned` should be an object.  One property to specify How (ANY, ALL, BYALL, etc) and another property to specify Who (an array of player names; not used for ALL)?

**Comment by rkathey** [comment]
> `Owned:NOTSELF`- tokens not owned by the current player (equivalent to "0")

Point of clarification: NOTSELF - would it return all the tokens owned by someone but not by the player making the request? I see this as useful.

@Azhrei I'm trying to think of a use case for your final point and am drawing a blank.

**Comment by Merudo** [comment]
> Perhaps `Owned` should be an object. One property to specify How (ANY, ALL, BYALL, etc) and another property to specify Who (an array of player names; not used for ALL)?

I don't think the extra complexity is worth it. Like @rkathey I also struggle to see a use for the option to look for tokens with multiple owners.

**Comment by JamzTheMan** [comment]
Case 1. Multiple owned tokens is a violation, I need to pop those up as a dialog to fix. My framework expects only one owner.

Case 2. Maybe a board game is looking for all tokens that are allied in a specific way?

Really, there must be a reason someone added the ability to add multiple owners? If so, wouldn't there be a reason someone would want to search for those tokens? 

I really don't have good use cases for most. Hell, this is 100% not even needed because it can be solved with a for:each loop and existing functions, but experience has told me, 5 minutes after this goes live someone will ask why it doesn't do it...

**Comment by Azhrei** [comment]
What he said. 😉

I don’t know the rules to every game so I can’t say that a given game would use a given feature, and it’s certainly true that not all games will want/need/use all features, but we’re trying to produce a tool so that others can write their own rules...  It seems counterintuitive to arbitrarily restrict how the tools can be used just because we can’t see an immediate use for them. 🙂

**Comment by rkathey** [comment]
> Really, there must be a reason someone added the ability to add multiple owners? If so, wouldn't there be a reason someone would want to search for those tokens?

I think the general problem with 'Player' is that is can change between session for the same belly button. So the ability to add them under different player names may have been the reason. Also, I'm guessing ownership gets saved with the token so when you reimport them the old ownership comes with it.

Also, I've used multiple owners for NPCs (it takes directions from some but not all).

Seems like a new flag (Owned:BYMULTIPLE?) might do the trick outside of the Alliance use case.

**Comment by rkathey** [comment]
> Perhaps `Owned` should be an object. One property to specify How (ANY, ALL, BYALL, etc) and another property to specify Who (an array of player names; not used for ALL)

I guess more flexibility is better. The array handles the Owned:BYMULTIPLE with more specificity. Although the Owned:BYMULTIPLE may still be worthy of inclusion.

**Comment by Merudo** [comment]
I'm interested in implementing this but there doesn't seem to be a consensus on how to do this. I guess we are at an impasse?

**Comment by Phergus** [comment]
I believe that suggestion you made on the 24th was tacitly accepted.  

`Owned:ANY` - tokens owned by any player
`Owned:BYALL` - tokens owned by all players
`Owned:NONE` - tokens owned by no players
`Owned:SELF` - tokens owned by the current player (equivalent to "1")
`Owned:NOTSELF` - tokens not owned by the current player (equivalent to "0")
`Owned:OTHERS` - tokens owned by other players, but not yourself
`Owned:array` - tokens owned by one or more of the players listed in the array

EDIT: rkathey suggested `Owned:BYMULTIPLE`

Feedback guys?  @rkathey @JamzTheMan @Azhrei

**Comment by Azhrei** [comment]
Agreed; I'm fine with that list. I think it covers most situations and is relatively readable when looking at the code.

There are obviously other possibilities (`Owned:ONLYBY` - tokens owned only by the players in the given list) but I don't think it's worthwhile.  And if I'm wrong, it'll be easy to add in the future without breaking existing code.

**Comment by Phergus** [comment]
@Merudo  Go for it.

**Comment by Merudo** [comment]
What about tokens owned that by all? Should they be returned when these options are specified?

ANY,NONE,SELF,NOTSELF,MULTIPLE,ARRAY

For example if a token is owned by all but doesn't have any explicit owner, should it be returned by ANY, NONE or MULTIPLE?

**Comment by Azhrei** [comment]
I’m trying think of when the OwnedByAll checkbox would be used.  For RPGs, maybe it represents a party-owned item, like a horse cart or a ship or other party loot.  So if I was using ALL, I’d probably want such things included.  If I were using NONE, I’d probably want it left out.  And if I were using ARRAY, it should probably be included.

But what about games other than RPGs?  Card games or war games or board games?  I’m having a hard time seeing OwnedByAll being used in those cases, but the results _might_ be different.

I’m beginning to think including or excluding OwnedByAll should be a separate flag, something like TREAT_OWNEDBYALL_AS_INDIVIDUALLY_OWNED.  (Although please use a shorter string!)

**Comment by JamzTheMan** [comment]
FWIW we use to have a lot of "OwnedByAll" of tokens when we had just the TV and had a shared "view" of the map (but still used iFoW/iView) because sometimes one person would log in on a laptop.

**Comment by Merudo** [comment]
PR #916 implements the options in https://github.com/RPTools/maptool/issues/742#issuecomment-554038076

**Comment by Phergus** [comment]
Options:
- BYALL - tokens Owned By All players
- NOTBYALL - tokens not Owned By All players
- SELF - tokens owned by the current player
- NOTSELF - tokens not owned by the current player
- OTHERS - tokens owned by other players, but not yourself
- ANY - tokens owned by any player
- NONE - tokens owned by no players
- SINGLE - tokens owned by a single player
- MULTIPLE - tokens owned by more than one player
- ARRAY - tokens owned by one or more of the players listed in the array

**Comment by Phergus** [comment]
Wiki pages updated.

**Comment by Phergus** [comment]
Tested:
- [ ]     BYALL - tokens Owned By All players
- [ ]     NOTBYALL - tokens not Owned By All players
- [ ]     SELF - tokens owned by the current player
- [ ]     NOTSELF - tokens not owned by the current player
- [ ]     OTHERS - tokens owned by other players, but not yourself
- [ ]     ANY - tokens owned by any player
- [ ]     NONE - tokens owned by no players
- [ ]     SINGLE - tokens owned by a single player
- [ ]     MULTIPLE - tokens owned by more than one player
- [ ]     ARRAY - tokens owned by one or more of the players listed in the array

Working as described.
