### ISSUE TITLE
Add Get Tokens with a Light Source to getTokenNames()

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#745]
**Is your feature request related to a problem? Please describe.**
Looping of a large number of tokens can be costly.

**Describe the solution you'd like**
As the title states, add the ability to retrieve tokens with a light source to the macro function GetTokenNames(). Currently, you need to create an MTScript loop to check the lights on a token. This function would retrieve them with one function call.

Add an additional 'condition' to getTokenNames called 'light' with the ability to pass a JSON object containing 'type', 'name', and 'value' as defined in the setLight() function. http://lmwcs.com/rptools/wiki/setLight 

- Value is either 1 or 0 to determine whether you're looking for tokens with lights or tokens without light
- Type is the light group. If Name has no value then the function returns any tokens with lights of that type (or tokens without lights of that type is Value is 0)
- Name finds any tokens with (or without depending on Value) the named light. 

**Describe alternatives you've considered**
Looping through tokens every time you need to compute light effects.

**Additional context**
This can be done in conjunction with #742

**Comment by Merudo** [comment]
I like it. Maybe if a `1` or `0` is given instead of a json array, it returns every token with/without vision?

**Comment by rkathey** [comment]
That would be a nice addition.

**Comment by Merudo** [comment]
PR #772 implements the feature.

**Comment by Phergus** [comment]
Basic functionality tested:
**Any Objects with Lights**
```
[h: cond = json.set("", "layer",'["Object"]')]
[h: cond = json.set(cond, "light",'{"value":1}')]
[r: names = getTokenNames("json", cond)]
```
**Any Tokens with Lights**
```
[h: cond = '{ "light": 1}']
[r: names = getTokenNames("json", cond)]
```
**Tokens with D20 Lights**
```
[h: cond = '{ "light": {"value":1, "category":"D20"}}']
[r: names = getTokens("json", cond)]
```
**Tokens with Torches**
```
[h: cond = json.set("", "layer",'["Token"]')]
[h: cond = json.set(cond, "light",'{"value":1,"name":"Torch - 20","category":"D20"}')]
[r: names = getTokens("json", cond)]
```
Working as described.

**Comment by Phergus** [comment]
Wiki pages for `getTokens` and `getTokenNames` updated with new condition/examples.  Closing.
