### ISSUE TITLE
Extend getlastPath() function to return token centre

### ISSUE THREAD

**Issue by Jaggeroth** [RPTools/maptool#748]
When you are using snap-to-size on square grids the getlastPath() function returns coordinates that are the top left boundary point of a cell.

For the purposes of collision detection, it would be useful if a parameter could be added to the function that caused it to return a path based upon the centre point of the token.

As well as being better for collision detection, it would also allow consistent behaviour for all grid types.

**Comment by rkathey** [comment]
I moved it

**Comment by Phergus** [comment]
He had already recreated the issue here.  #428

**Comment by rkathey** [comment]
Show we just close it as a duplicate then?

**Comment by Phergus** [comment]
Reckon so.  Closing.
