### ISSUE TITLE
Set Landing Map for Client Connect

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#75]
User issue from Dorpond working with a new MapTool GM
"When he loaded up his campaign, we connected as players and arrived in a map he wasn't expecting us to be on. My thoughts went back to our past discussions of having a landing page, where all players connected arrive at. This could be as simple as a set (default) map, or be as elaborate as having a non-map, full text/writing capable (recapping last sessions, listing current quests, etc) landing page."

After discussion, the thoughts are to allow the GM to set a landing page for the campaign or default the players to the GMs current map when they connect to a server. 

Possible solutions include
1. Flagging a map as a landing page on the MapTool Map menu. Rules around this include only having one landing page per campaign and the map must be player visible. If the map is set to non-visible, the flag is removed.
2. Force the players to the current GM map (by default). Again, the map would need to be player visible.
3. Consistently force the players to the first visible map in the Map List.

These are likely in precedent-order. If a Landing Page is set then go there. If there is no Landing Page then go to the GM's map. If the GM map isn't player-visible, go to the first visible map in the list.

**Comment by JamzTheMan** [comment]
I'm thinking #1 but with a twist, make it an editable HTML page, not a map. And provide a default page on new campaign can grass map. The landing page could have RPTools links to FAQ, macro wiki, YouTube channel, as well as a few MT shortcuts like "New Map" or "Start Server"

**Comment by Jaggeroth** [comment]
Hmmm. Not sure. I think defining a starting map should be enough. No need for people to learn html if they don't want.

**Comment by Azhrei** [comment]
Hm, I like it. :)

Links could point to other maps, but then people wouldn't know how to get back where they were. :)

I do like the landing page idea, though.  It would let us have a spot where content could be loaded dynamically from rptools.net to provide information about what's happening with MT.  It might also move us a step closer to having an HTTP client that can serve up map images in some kind of "observer" mode.

**Comment by JamzTheMan** [comment]
No need to learn HTML. I'm sure we could expose a simple rich text type editor if people want to edit the title/body/etc. Maybe we even start with that vs exposing the raw HTML.   I even see a drop area on said page were PC tokens are dropped. This tells MT here are the PC tokens (and clients that own them?) And now can move them map to map vs relying on custom macros. And it would have a grab button that pulls all macros back regardless of which map they are on.

Personally. I delete that dang grass map as often as use it. Typically I'm creating on black and use new map vs editing the texture...

Also, look at it from a new user. A green map with lots of buttons and menu options. Where to start? It's intimidating.

I like az's idea if pulling in content so we can dynamically adjust said page based on feedback?

**Comment by Jaggeroth** [comment]
Thing is these all great functions that could be equally useful on a map, so why build a special landing page?

**Comment by Azhrei** [comment]
I don't suppose it needs to be a special page.  Maybe a default map that contains an HTML control of some kind?  But then we're back to needing a way to identify which map is the default. :)

**Comment by Jaggeroth** [comment]
We definitely need that imo. 

Plus you really need to join the Slack, we are discussing this now :)

**Comment by Azhrei** [comment]
Heh, okay.  Send me an invite. :)

(I looked them up and didn't find anything concerning in their ToU policy, so I don't know what the hubbub was about.)

**Comment by rkathey** [comment]
Which address? the ecc one or the gmail one?

**Comment by rkathey** [comment]
the sales one?

**Comment by Azhrei** [comment]
Heh, good question.  I figured you’d use the one from GutHub, which would be from Gmail:  azhreifje@gmail.com is the one to use.

Thanks.

 <http://www.eeconsulting.net/>	
Edwards & Edwards Consulting, LLC <http://www.eeconsulting.net/>
Frank J. Edwards
sales@eec.com
Voice: +1 813.406.0604 (rings both office and mobile)

**Comment by Baaaaaz** [comment]
Tested in 1.16.0.rc-2 and looks fixed to me. Thanks!
