### ISSUE TITLE
json.evaluate doesn't work with token properties

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#750]
**Describe the bug**
json.evaluate doesn't get the value associated with a token property

**To Reproduce**
1. Create a token with 10 HP
2. Run the following macro on the token:

```java
[h: jsonArray = json.append("[]", "HP")]
[r: eval(json.get(jsonArray, 0))]
[r: json.get(json.evaluate(jsonArray),0)]
```

3. Check the results. The macro returns

```
10
HP
```

Meaning `json.evaluate` doesn't get the token property associated with `HP`, while `eval` does.

**Expected behavior**
`json.evaluate` returns the value associated with the token property, such as `10` instead of `HP`.

**MapTool Info**
- Version: 1.5.4, 1.5.5 RC1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
I guess it's a bug.  Note that if you supply actual macro code like `{DEX}` or `[r: DEX]` then it is eval() that doesn't like it and actually puts out an error.

**Comment by Merudo** [comment]
Oh! Maybe `json.evaluate` is the json version of `evalMacro` instead of `eval`.

**Comment by Phergus** [comment]
I suspect that is the case.

**Comment by aliasmask** [comment]
Yeah, what merudo said. You need to put macro code inside the json values (obj or array).

**Comment by Phergus** [comment]
Working as designed and tested with current JSON updates.
