### ISSUE TITLE
Add missing reserved variable names to editor syntax

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#753]
**Is your feature request related to a problem? Please describe.**
`init.current` and `init.round` reserved variables are not highlighted in macro editor

**Describe the solution you'd like**
They should be highlighted.

**Additional context**
Also not documented on Wiki.

**Comment by xdy** [comment]
My PR https://github.com/RPTools/maptool/pull/981 is intended to fix #753

**Comment by Phergus** [comment]
Tested. Init.current and init.round are now recognized by the editor.

**Comment by Phergus** [comment]
Wiki pages added:
http://www.lmwcs.com/rptools/wiki/init.round
http://www.lmwcs.com/rptools/wiki/init.current
