### ISSUE TITLE
Auto save feature for campaign and chat is not working.  Lost data.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#762]
**Describe the bug**
In MapTool 1.5.4, it looks like the auto save feature isn't working?  I had all the options set as follows for last night's (10/2/2019) game:

1. Campaign autosave every "10" min.
2. Save reminder on close "v" (checked).
3. Time between chat log autosaves "10" min.

Only saves sometime shortly after I loaded the campaign were done.  About 2 hours into the game, my Windows 10 computer blue screened (first time that's ever happened because of a video driver update and I forgot to reboot).  I found out that there were no auto saves for either the chat or the campaign, except there was one for the campaign apparently from when I had first loaded the campaign.
.
So last night we played from 7:15pm CDT till 10:15pm on 10/2/2019, and with those settings, this is what my autosave directories look like the attached autosave images.

**To Reproduce**
1. See configuration attached.
2. Started server.
3. Players attached.
4. No autosaving done during about 2 hours of game play.

**Expected behavior**
Autosave files should exist at 10 minute intervals.

**Screenshots**

**MapTool Info**
- Version: 1.5.4

**Desktop (please complete the following information):**
 Windows 10
![pereferences for autosave](https://user-images.githubusercontent.com/50708405/66213648-ce700f00-e685-11e9-9632-e7987252d89a.png)
![autosave cmpgn](https://user-images.githubusercontent.com/50708405/66213674-de87ee80-e685-11e9-8f63-82f2755bd2fd.png)
![autosave chat](https://user-images.githubusercontent.com/50708405/66213680-e182df00-e685-11e9-83ad-1f088ec9591d.png)

**Additional context**
From MapTool, paste info from menu Help -> Gather Debug Information...
You can also attach files (drag and drop here) such as log files or paste a file sharing link.

**Comment by JamzTheMan** [comment]
Yea, I got bit by that in 1.5.4 as well 2 weeks ago. Autosave has always been somewhat unreliable. It always seems to work when you check and fails at the worst times.

Maybe we need a watchdog process that watches the for the latest save and if it doesn't see a save for the last x (defined) minutes it changes the border to red or something to let you know autosave is behind schedule.

At least until we can be confident it works again. 

Also, maybe we change autosave to just save in directory mode and save on cpu/disk cycles for zip (a first step towards directory based saves)?

**Comment by Azhrei** [comment]
This really concerns me.

I will add some logging that identifies which branch is taken along step of the code path through the save routine.  Maybe something will turn up.

This is going to be a little chatty, though; what’s a good way to output this?  I’d like it to always be logged so it can be attached to an issue, but not be so chatty that it interferes with the game.  Maybe a separate JIDE panel that the user can minimize and ignore?

**Comment by JamzTheMan** [comment]
Just use log4j to log it, can always set it on or off by default and can be turned on/off via macro. Maybe a mix of info/debug/trace if needed?

**Comment by Azhrei** [comment]
But it always needs to be on or it’ll be too late to gather info when someone finds that the autosave didn’t work.  Or are you saying it would default to ON if autosave is on, and a macro could turn it off if desired?  That would work...

**Comment by JamzTheMan** [comment]
Yea, turn on by default. Maybe add on demand trace debug if you think is needed that you could easily turn on to  debug prod code.

And the logs are rolling now so if someone had a problem during game and locked up, logs should persist and be retrieved later. They are zipped up so size shouldn't be a concern.

Log4j2 should be perfomant enough to handle it (just don't open the built in log viewer though if you are logging like mad crazy)

**Comment by JamzTheMan** [comment]
Maybe add a last save datetime in the status bar too? Although it should probably read the directory to read the last save file and check every x minutes?

Do you think it's silent failing now? Would there possibily be something logged to sentry.io?

**Comment by Azhrei** [comment]
I haven’t seen anything in Sentry but I’ve been barely skimming it lately.  It’s worth a search, though...

**Comment by Phergus** [comment]
Something weird is going on with it.  I had a MapTool server instance running pretty much all day yesterday and 3 backups were created in the `.maptool-rptools/backup` folder appearing to correspond with perhaps campaign loads.

In the `.maptool-rptools/autosave` folder there was one `AutoSave.cmpgn` file created with a timestamp in the middle of the morning.

There were 6 chatlog*.html files created there at seemingly random times both less and more than my selected 5 minute period.

I never have it turned on myself and was surprised to see 60+ weirdly named campaign files in `backup`.

**Comment by Phergus** [comment]
Interestingly, it seems to work when running out of NetBeans.
```
15:42:18.378 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-10-04-15-42.html'
15:42:18.415 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
15:47:15.577 (AutoSaveManager.java:102) [AWT-EventQueue-0] INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 18
15:47:18.377 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-10-04-15-42.html'
15:47:18.379 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
15:52:18.377 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-10-04-15-42.html'
15:52:18.380 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
15:57:18.378 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-10-04-15-42.html'
15:57:18.397 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
```

**Comment by JamzTheMan** [comment]
Odd. And we probably shouldn't rule out any sort of permission/write issue while running from native exe

**Comment by adventuremagic123** [comment]
Thank you all for working on this.

**Comment by Merudo** [comment]
I did some tests and noticed the autosave timer works once, gets paused and then doesn't restart.

PR #918 fix the timer so it resumes properly after getting paused. There are probably other issues with the auto save system but that's a start.

**Comment by Azhrei** [comment]
Yes, there are (other problems).  I've finished testing and I'm happy with the new code.  But I screwed up the branch and need to spend some time fixing it.  I'll get to it tonight and submit the PR.

**Comment by Azhrei** [comment]
For the wiki:  as a troubleshooting aid, the AutoSaveManager will switch from measuring the autosave interval in minutes to seconds when the log level for that package is set to “DEBUG”.

I expect this won’t cause problems as ordinary users won’t be setting the log level for the ASM, but it’s a simple patch to revert if it’s deemed problematic.

**Comment by Phergus** [comment]
@melek See Az's note above.

I can definitely see having it in seconds being an issue for those folks with 200MB campaign files but, as you say, they are unlikely to change the log level so not a big concern.

**Comment by Azhrei** [comment]
> I can definitely see having it in seconds being an issue for those folks with 200MB campaign files

The timer is restarted only when an autosave competes, so it’s effectively the time between saves; meaning if it took 50s to save a campaign file (as one of my test campaigns did), the interval is from the end of one save to the start of the next (whether measured in minutes or seconds).

I point this out to clarify that a second autosave won’t begin while a current one is running.

**Comment by Phergus** [comment]
Also good info for the wiki.

**Comment by Merudo** [comment]
I could imagine issues if someone has their save interval set to 1.

**Comment by Azhrei** [comment]
What kind of issue?  I tested with intervals of 1 minute and 1 second.

**Comment by Merudo** [comment]
Wouldn't saving every second make the interface freeze or something?

**Comment by Phergus** [comment]
The chat log save is always writing to the same file.  With a 3 minute setting for campaign, I only saw the one save over 12 minutes.
```
06:12:21.541 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-11-19-06-10.html'
06:12:21.543 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
06:13:56.764 (AutoSaveManager.java:102) [AWT-EventQueue-0] INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 21
06:14:21.541 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-11-19-06-10.html'
06:14:21.543 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
06:16:21.542 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-11-19-06-10.html'
06:16:21.544 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
06:18:21.542 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-11-19-06-10.html'
06:18:21.543 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
06:20:21.543 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-11-19-06-10.html'
06:20:21.544 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
06:22:21.543 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-11-19-06-10.html'
06:22:21.547 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
06:24:21.544 (ChatAutoSave.java:66) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Saving log to 'C:\Users\Phil\.maptool-rptools\autosave\chatlog-2019-11-19-06-10.html'
06:24:21.547 (ChatAutoSave.java:77) [Timer-0] INFO  net.rptools.maptool.client.ChatAutoSave - Log saved
```

**Comment by Azhrei** [comment]
Campaign saves are done on a separate thread.

I didn't look at the chat saves.  Looking at the OP, I do see that chat saves are also listed as a problem.  I'll look into those as well.

**Comment by Phergus** [comment]
Unless the ASM logging is set to DEBUG, I'm not getting any log output for campaign saves.  Intentional?

**Comment by Azhrei** [comment]
Without DEBUG, you should only get a start/stop message.  Here's the kind of logging I get by default (I don't think I've got my Eclipse configured to automatically set any of the logging levels).  Notice that they're all INFO level messages.
```
12:26:56.164 (AutoSaveManager.java:128) [AWT-EventQueue-0] INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 87
12:26:56.164 (AutoSaveManager.java:137) [AutoSaveThread] INFO  net.rptools.maptool.client.AutoSaveManager - Starting autosave...
12:27:41.190 (AutoSaveManager.java:149) [AutoSaveThread] INFO  net.rptools.maptool.client.AutoSaveManager - Autosave complete.  Elapsed time (ms): 45,026
12:27:41.191 (AutoSaveManager.java:61) [AutoSaveThread] INFO  net.rptools.maptool.client.AutoSaveManager - Restarting autosave manager; interval in seconds is 120
12:29:41.286 (AutoSaveManager.java:128) [AWT-EventQueue-0] INFO  net.rptools.maptool.client.AutoSaveManager - Time to copy Campaign object (ms): 93
12:29:41.286 (AutoSaveManager.java:137) [AutoSaveThread] INFO  net.rptools.maptool.client.AutoSaveManager - Starting autosave...
12:30:26.286 (AutoSaveManager.java:149) [AutoSaveThread] INFO  net.rptools.maptool.client.AutoSaveManager - Autosave complete.  Elapsed time (ms): 45,000
12:30:26.286 (AutoSaveManager.java:61) [AutoSaveThread] INFO  net.rptools.maptool.client.AutoSaveManager - Restarting autosave manager; interval in seconds is 120
```

**Comment by Phergus** [comment]
I'm getting them now.  I had been mucking with log levels and had ASM set to WARN.

**Comment by Phergus** [comment]
Campaign autosave tested and working as expected.

**Comment by Phergus** [comment]
The Chat Log autosaves start with a new file whose name includes the data/time of the first save.

e.g:  `chatlog-2019-11-19-08-57.html`

All subsequent saves go to the same file and so the file timestamp changes but the filename stays the same.  Effectively this identifies the start of the session and so each new session gets its own chat log.

I'm guessing this was intentional and it seems like a good idea to me.

**Comment by Azhrei** [comment]
> I'm guessing this was intentional and it seems like a good idea to me. If everyone agrees then we can consider this issue closed except for some documentation updates.

It is intentional.  It's always possible to change the default filename so that only the current date is included, or even remove the date and time from the filename completely so the user would get a single large log file.

(There's still an issue that the chat log doesn't embed images so that the HTML displays avatars and other graphics.  It's possible by using `data:` URLs when exporting, but that requires more work than the current code which simply dumps the HTML accumulated in the Swing component to an external file.  But that's a separate issue and I think we already have it open.)

**Comment by Phergus** [comment]
Other chat discusssion: 
#284 
#115

**Comment by Phergus** [comment]
Based on the OPs screenshot above you can see that the chatlog was updated at the time his session ended suggesting that he did have a log but perhaps the filename threw him off.

My testing shows that the chat log currently, and in previous MapTool versions, is being updated at the correct interval.

**Comment by Phergus** [comment]
Wiki updated with additional info for autosave.  Closing.
