### ISSUE TITLE
Overlay perlin/gausian noise on tiling textures

### ISSUE THREAD

**Issue by Syndaryl** [RPTools/maptool#766]
**Is your feature request related to a problem? Please describe.**
I have brain damage that has left me sensitive to repeating visual patterns, such as tiled textures. The smaller the texture and denser the tiling, the more "abrasive" it feels. I understand neurotypical people find this a little displeasing too, but I have a nails-on-blackboard problem with it.

**Describe the solution you'd like**
A ticky-box option to Overlay a perlin noise or gausian noise function over textures used with drawing tools, where they will be tiled to fill the drawing tool shape, and a separate ticky-box option to Overlay the same over a map background image, which is tiled to fill your entire screen omg.
This would generate a low contrast, relatively large scale noise function. It should not tile, it should be independent of the tile of the texture underneath.
Using Overlay slightly brightens part of the underlying texture and slightly darkens part of the underlying texture.

The result "breaks up" the repetition of the tiling pattern enough that it feels drastically better for me, and I am informed it is more aesthetically pleasing for neurotypical people as well. The Cartographers Guild recommend it.

I _think_ the best implementation would make it a client-side option in the accessibility settings, so that it can be turned off by people who don't like the effect or find the effect not worth the extra processing overhead. It could default to off as well.

**Describe alternatives you've considered**
The alternative puts the onus on the GM to create larger tiles and apply the noise function themselves. This results in a) more work and b) larger file sizes for the tiles, and c) if done incorrectly results in seams when the new tile is ... tiled, which nobody likes.

**Additional context**

![Tiling Grass](https://user-images.githubusercontent.com/8820565/66257023-309e4200-e762-11e9-88bd-6af25dd4a1a4.png)

![Tiling Grass with Noise](https://user-images.githubusercontent.com/8820565/66257029-385de680-e762-11e9-846e-87ab7fc659de.png)

**Comment by JamzTheMan** [comment]
Sounds reasonable.

I know another thing that was considered, a lot of textures sometimes come with 4-8 "versions" like grass-a, grass-b, etc.  An option to select multiple textures when tiling and have it 'randomly" use those tiles may mix things up a bit.

TBH, I have not tried this (manually or otherwise) so not sure if the effect would be desirable or not.

**Comment by Azhrei** [comment]
I love this idea!

Since the noise isn’t part of the tile, it will need to be generated after the tiles are blitted to the image.  If the noise isn’t saved somehow, every refresh of the image would generate different noise, so what happens when the map is being panned?

**Comment by JamzTheMan** [comment]
That would be my concern, given that MT (currently) is "infinite" generating and caching this seems problematic...

Maybe this another case of allowing the map to be limited and restricted to a set size... (as an option) to allow this sort of thing?

**Comment by Azhrei** [comment]
And perhaps that’s okay on the client?  How often does the Player increase the size of the map?  Perhaps the server sends the campaign to the client who then converts the background image (or tiles) into a fixed size image and adds the noise overlay...?

**Comment by cwisniew** [comment]
Perlin noise should work quite well for something like this. It is also deterministic for any set of co-ordinates so unbounded maps should not be an issue.

**Comment by Azhrei** [comment]
Cool.  Never heard of it (off to visit Wikipedia).

**Comment by Syndaryl** [comment]
Perlin noise would produce the same result on any client, given the same inputs. You don't need to provide a random "seed" like when generating an actual random number - although you can if you want to in order to produce variations.

**Comment by Syndaryl** [comment]
Tile randomization would also be good! Both techniques are used in modern videogames to get the benefit of small texture sizes while reducing the visual impact.
I suggested the noise one because it has the least effort required on the part of the GM in order to accommodate someone. Adding in multi-textures would be a great enhancement.

**Comment by Phergus** [comment]
Rather than applying the noise as a separate, possibly CPU/GPU intensive process, why not just check the preferences setting and apply it to the texture before the tiling operation.  Would Perlin noise also show obvious repeating patterns if generated just once for the tile texture?

**Comment by cwisniew** [comment]
> Rather than applying the noise as a separate, possibly CPU/GPU intensive process, why not just check the preferences setting and apply it to the texture before the tiling operation. Would Perlin noise also show obvious repeating patterns if generated just once for the tile texture?

Applying the noise just once to the texture before they tiling operation unfortunately wont help as you are just darkening/lightening the existing pattern which means you would still be laying down a repeating pattern, and for tilesets where the existing pattern is subtle and not really noticeable you could even make the situation worse by introducing a new pattern which is.

**Comment by Phergus** [comment]
I was afraid of that.

**Comment by cwisniew** [comment]
I have applied an overlay of perlin noise to the background image.
Attached is what the standard grassland background looks like, @Syndaryl can you let me know if this is enough to remove the discomfort or not.

![image](https://user-images.githubusercontent.com/73173/66651569-e5f95a00-ec7a-11e9-9f87-2154ed6a13d4.png)

If this is enough then I can start working on the scrolling.

I may not even worry about zooming I kind of like how it works at the moment, this next image shows zooming in looks like without the noise being zoomed in, it kind of adds an extra texture, but I am open to what other people think
![image](https://user-images.githubusercontent.com/73173/66651881-bac33a80-ec7b-11e9-9a31-e1b8ad55969e.png)

I want to finish off background before tackling textured drawables as thats quite a bit more complicated.

**Comment by Merudo** [comment]
Am I the only one who thinks the default delta of `.2` is too much noise? It blurs the details too much and the texture is almost unrecognizable.

I suggest we use a lower delta such as `.1`

**Comment by Phergus** [comment]
I think we'll probably have it default off and then have a user preference for the values.

**Comment by cwisniew** [comment]
@Merudo as Phergus said it will be off by default I need to add that bit. But also the repeating pattern in the grass is so strong the noise also has to be strong to break it up it (which is the purpose of this patch)

**Comment by Syndaryl** [comment]
This works great, thank you very much. Having an adjustable delta sounds like a good idea - can we have perhaps a slider control? This way people can tweak to their own requirements, which with an Accessibility feature is very important.

Customization leads to Accessibility, accessibility enhances customization for the general populace :)

**Comment by Syndaryl** [comment]
I'm loving 0.2 myself :)

**Comment by Phergus** [comment]
Latest commits set the noise to off by default and added ability to toggle on/off.

To change, use /texturenoise alpha [seed] or /texturenoise on | off.

/texturenoise by itself will report current values if it is on.

> Current Values, alpha = 0.1, seed = 42.

**Comment by Phergus** [comment]
[Chat commands page](http://www.lmwcs.com/rptools/wiki/Chat_Commands) updated on wiki with new info.
