### ISSUE TITLE
Low frame rate on map panning with MT 1.5.5

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#767]
**Describe the bug**
Map panning in MT 1.5.5 (and 1.5.6) is noticeably more jerky than 1.5.4.

**To Reproduce**
1. Load attached campaign file in MT 1.5.4
2. Pan map and observe how smooth it is.
3. Load same campaign in MT 1.5.5
4. Pan map and see how jerky the movement s.

**Expected behavior**
Expect 1.5.5 to be as smooth as 1.5.4.

**Screenshots**
[Video of MT 1.5.4](https://www.youtube.com/watch?v=kpYz15S-oVA&feature=youtu.be)
[Video of MT 1.5.5](https://www.youtube.com/watch?v=qoZ4Xr4On3M&feature=youtu.be)

**MapTool Info**
- Version: 1.5.5, 1.5.6
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Reported by Wisewolf on forums.
https://forums.rptools.net/viewtopic.php?f=1&t=28361&start=15#p274201

Campaign file that shows issue.

[MapPanIssue2.cmpgn.zip](https://github.com/RPTools/maptool/files/3693865/MapPanIssue2.cmpgn.zip)

**Comment by JamzTheMan** [comment]
I'm guessing the performance enhancements to the renderer have some issues eh?

**Comment by Merudo** [comment]
I remember the framerate been capped at 30fps, maybe we could try to 60fps? I think 60fps is the norm for good fluidity.

**Comment by Phergus** [comment]
I don't think it has anything to do with frame rate cap unless that was changed in 1.5.5.

**Comment by Merudo** [comment]
I'm struggling to see the jerky movement in the supplied campaign so I don't think I'm the right person to try out a fix.

**Comment by Phergus** [comment]
That will teach you to have a decent graphics card.  Should have a crappy, old one like me.

Confirm that changing
`private static final int REPAINT_DEBOUNCE_INTERVAL = 33;`
to
`private static final int REPAINT_DEBOUNCE_INTERVAL = 16;`
Makes for a big improvement.

Maybe make this a preferences setting.

**Comment by Merudo** [comment]
So it seems PR #611 is the cause of the slowdown.

**Comment by JamzTheMan** [comment]
So did changing the interval fix it enough?

**Comment by Merudo** [comment]
Maybe we could have it set this way:

- Users can choose the fps they want. The fps is then converted into the appropriate debounce interval.
- Minimum fps is 10.
- A fps of less than 10 is interpreted as disabling the deboucer.

**Comment by JamzTheMan** [comment]
Looks ok to me but I'm not sure I'm the best judge on this one, 

I'll mark it `tested` but leave it open for one other person to test.

**Comment by Phergus** [comment]
To make it really obvious on my not high-end system I have to compare 15 fps to 120 fps and with two instances side-by-side.

**Comment by Phergus** [comment]
Closing.
