### ISSUE TITLE
Modifications of a token created by copyToken are ignored

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#769]
**Describe the bug**
Using `copyToken` returns the token id of the new token, however edits to the token are deleted when the macro ends.

**To Reproduce**
1. Create a token called "Dragon"
2. Run this code

```
[h: newtoken = copyToken("Dragon")]
[h: setProperty("AC", 10, newtoken)]
```
3. Check the AC of the new token. It's blank.

**Expected behavior**
The properties of the copied token can be freely edited.

**MapTool Info**
- Version: 1.5.6
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #771 fixes this issue.

**Comment by Merudo** [comment]
The wiki entry for [copyToken](https://lmwcs.com/rptools/wiki/copyToken) has a lot of text on how to make changes to the newly created token.

Now that newly copied tokens can be edited right away, should we keep that text?

**Comment by rkathey** [comment]
We probably need a version note of some sort. “As of MapTool version 1.5.x this is no longer necessary.”

**Comment by Phergus** [comment]
Probably just need to keep a note like:

> As of MapTool v1.5.7, tokens can now be modified immediately after a copy.  In prior versions of MapTool tokens couldn't be modified immediately after a copy without special techniques being used.

And then remove all the extra stuff.  The information would still be there in the history for the page.

Or it could be moved to a new page and just link to it after the note.

**Comment by Azhrei** [comment]
Page history won’t be useful if/when the wiki finally moves.  Creating a separate page and linking to it is probably better — It cleans up the current doc but persists the older docs.

When 2.0 comes out, that older link can be removed.  Or maybe sooner, if we decide that an earlier release is very stable and becomes our “go to” release for folks who don’t like living on the edge. 😉

**Comment by Phergus** [comment]
New page added and legacy content moved to new page.

[copyToken Page](http://www.lmwcs.com/rptools/wiki/copyToken)
[Legacy content page](http://www.lmwcs.com/rptools/wiki/copyToken_legacy)

**Comment by Phergus** [comment]
Closing.
