### ISSUE TITLE
macro logging stops working after one use

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#78]
When you turn on macro logging it works, however the next time you run it , it doesn't work anymore. 
It turns out that it works as long as you make a change in the 'advanced' tab of the launcher. If I keep turning on/off/on etc e.g. 'general debugging' then 'macro handling' remains active. If however i dont make a change then the macro handling logger doesn't work. 
Note I only checked the workings with the console, didn't check the actual log file (under the assumptions that they're showing the same).

**Comment by JamzTheMan** [comment]
Wolph, this issue should be resolved as of 1.4.1.4

Please confirm on you end it's resolved and we can close this bug.

**Comment by wolph42** [comment]
Fixed!
