### ISSUE TITLE
Distance per cell is saved incorrectly in German

### ISSUE THREAD

**Issue by aRTy42** [RPTools/maptool#780]
**Describe the bug**
The "Distance per cell" property of a map is saved at 10 times the value that is entered into the field when using the German interface, likely due to a mismatch between '.' and ',' for the decimal point.

**To Reproduce**
0. Use the German interface
1. Go to 'Map' > 'Edit Map' (DE: "Karte bearbeiten")
2. Look at 'Distance per cell' value. The number is using a '.' for the decimal point, assume '1.0'.
3. Don't change anything and click 'ok'
4. Drag around tokens and get a distance of 10 per cell
5. Re-open map menu and see that the value switched to '10.0'

(Optional)
6. Confirm menu again with 'ok' and re-open it. The value is now '100.0'. You can cycle this up by a factor of 10 each time.
7. Use an input of '1' or '1,0' instead and note that it is saved correctly as 1 unit. Opening the menu again displays it as '1.0' again.

Notes: I suspect the '.' is simply ignored when using the German interface because it is not an accepted character for a number field. A value such as '1.6' is indeed saved as '16' (or '16.0'), which supports the suspicion.

**Expected behavior**
Either load up the value with the German format ('1,0') or make sure the number field interprets a '.' correctly in addition to ',' 

**MapTool Info**
- Version: 1.5.6
- Install: Upgrade [from 1.5.3, but into new folder, so it should effectively be a new install]

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 7

**Additional context**
==== MapTool Information ====
MapTool Version: 1.5.6
MapTool Home...: C:\Users\aRTy\.maptool-rptools
Max mem avail..: 1 GB
Max mem used...: 463 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: D:\Programme\MapTool\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 7
OS Version.....: 6.1
OS Architecture: amd64
PATH...........: D:\Programme\MapTool\app;D:\Programme\MapTool
Number of Procs: 8

==== User Information ====
User Name: aRTy
User Home: C:\Users\aRTy
User Dir.: D:\Programme\MapTool\app

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Intel(R) 82579V Gigabit Network Connection
Interface Name: eth3
Address...: 192.168.2.102
Address...: fe80:0:0:0:8161:cdc5:67d9:1718%eth3

Host Address...: 192.168.2.102
Default Gateway: 192.168.2.1

==== Locale Information ====
Country.: Deutschland
Language: Deutsch
Locale..: Deutsch (Deutschland)
Variant.: 

==== Encoding Information ====
Default Locale:   de_DE
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(32)

==== Internet Gateway Devices ====
	No IGDs Found!

**Comment by Phergus** [comment]
Already reported under #507.  Closing as duplicate.
