### ISSUE TITLE
broadcast options: not-gm, not-self, not-gm-self

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#782]
**Is your feature request related to a problem? Please describe.**
The following message options are available in the BoT but not in `broadcast`

- not-gm
- not-self
- not-gm-self

**Describe the solution you'd like**
Adding these options to `broadcast`.

**Comment by Merudo** [comment]
PR #783 implements the new feature

**Comment by Phergus** [comment]
Tested.  Working as expected.

**Comment by Phergus** [comment]
Wiki updated.
