### ISSUE TITLE
json.toVars to take JSONArray

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#784]
**Is your feature request related to a problem? Please describe.**
Turning a JSONArray into variables could be made easier.

**Describe the solution you'd like**
The function `json.toVars` could take a `JSONArray`, for example

`json.toVars(jsonArray, variableName)`

which would create variables `variableName0`, `variableName1`, ...,

**Comment by Merudo** [comment]
PR #785 implements this feature

**Comment by Phergus** [comment]
Tested.  Working as described.

**Comment by Phergus** [comment]
Wiki documentation updated.  Closing.
