### ISSUE TITLE
Multiple bugs in Bar macro functions

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#786]
**Describe the bug**
1. `isBarVisible()`, `setBar()`, `setBarVisible()` and `getBar()` return an incorrect error message when there is no current token.
2.  `isBarVisible()`,  `setBar()` and `setBarVisible()` return success when passed a bogus bar name.
3. `getBar()` returns a misleading error message if given a bogus bar name.

**To Reproduce**
With no token impersonated execute the following commands from the Chat window:
```
[r: isBarVisible("Health")]
[r: setBar("Health",0.5)]
[r: setBarVisible("Health",1)]
[r: getBar("Health")]
```
All four will return:

> Error **executing initiative function**: there is no impersonated token.

With a token impersonated, enter the following into Chat:
```
[r: isBarVisible("bogusbarname")]
[r: setBar("bogusbarname",0.5)]
[r: setBarVisible("bogusbarname",1)]
[r: getBar("bogusbarname")]
```
 `isBarVisible()`, `setBar()` and `setBarVisible()` will return a value indicating a successful execution, i.e. the value that would be the current setting of the bar.

> Hero: 0
> Hero: 0.5
> Hero: 1

`getBar()` returns:

> Error in body of roll.
>    Statement options (if any): r
>    Statement Body : getBar("bogusbarname")

**Expected behavior**
1. Error message should not be referencing "initiative function" when no token is impersonated.
2. Attempting to set a value on a non-existent bar should return an error indicating bar isn't defined.
3. Attempting to get the value of a non-existent bar should return an error indicating bar isn't defined.

**MapTool Info**
- Version: 1.4.0.5, 1.5.6
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
The already merged PR #764 solves the first four errors, as well as the last one.

If no token is impersonated, the error message is

`Error executing "isBarVisible": there is no impersonated token.`

And, `setBar()` returns

`Function 'getBar' requires at least 1 parameters; 0 were provided.`

**Comment by Merudo** [comment]
PR #787 fixes the remaining issues.

**Comment by Phergus** [comment]
Fixes tested and are working as expected.  Closing.
