### ISSUE TITLE
Request: execFunction(functionName, args, defer, targets, delim)

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#790]
It would be nice to have execFunction(functionName,args,defer, targets, delim)

It would be just like execLink but for built in functions and UDFs. 
args would be a json array used to call the function.

Other than that, the same as execLink().

I found a need for something like this implementing the playStream() function and wanting to execute it on all the clients at the same time.

Example Code used to do that. You'll see where the redundancy lies in playSound:
```
@@ @playSound
[H: link = arg(0)]
[H, if(argCount() >= 2): repeat = arg(1); repeat = 1]
[H, if(argCount() >= 3): volume = arg(2); volume = 0.5]
[H, if(argCount() >= 4): start = arg(3); start = 0]
[H, if(argCount() >= 5): stop = arg(4); stop = 0]

[H: evalMacro(strformat("[H: playStream(link,repeat,volume%s%s)]",if(start || stop,","+start,""),if(stop,","+stop,"")))]

!!
@@ @LinkGoesHere
[H: "<!-- Edit these line to set your settings. Will play on all clients with shared source (like a web link). -->"]

[H: link = "https://ia800300.us.archive.org/29/items/Muzyka-CC/Aleksand_Sjakin_-_Flight_in_space.mp3"]
[H: preloadOnly = 0]
[H: continuousPlay = 0]
[H: repeatNumber = 1]
[H: volumePercent = 100]
[H: startSeconds = 0]
[H: stopSeconds = 0]

[H: "<!-- Don't Edit Below This Line -->"]

[H: repeat = repeatNumber]
[H, if(preloadOnly): repeat = 0]
[H, if(continuousPlay): repeat = -1]

[H: volume = min(1,max(0,volumePercent / 100))]

[H, if(stopSeconds < startSeconds): stopSeconds = 0]

[H: audioByte = macroLinkText("playSound@lib:musicplayer","none",json.append("",link,repeat,volume,startSeconds,stopSeconds))]
[H: execLink(audioByte,1,"all")]

!!
```

**Comment by JamzTheMan** [comment]
I second this. Although, would there be an opportunity to make this nicer than having to pass all the parms again? And args would have to be a json or something I guess? (UDF's can be passed a variable number of args for the same UDF)

Thought #1, add the ability to defineFunction that takes a 4th arg of `targets` so every time you called said UDF if just acts like an execLink? You can just define multiple UDF's for same function if needed? (messy though if you want to send to a specific target name)...
Maybe if the UDF has this defined, the last arg passed to the UDF is used as `targets`?

Thought #2, create a macro function like `execThis(targets)` that just executes the current macro to 'targets'? Your UDF could create it's own logic to determine if/who it executes for? No idea if this is feasible or not... 

Off the cuff ideas that I only put about 2 mins of thought into, but maybe it'll spur some discussion? :D

**Comment by aliasmask** [comment]
Here's some old code I used to do my own execFunction()

```
<!-- deferFunction(functionName,args) -->
[H: function = arg(0)]
[H, if(argCount() >= 2), code: {
   [H: args = arg(1)]
   [H, if(json.type(args) != "ARRAY"): args = json.append("",args)]
};{
   [H: args = ""]
}]
[H, if(currentToken() == ""): target = getMacroLocation();target = currentToken()]
[H: deferArgs = json.append("",function,args)]
[H: link = macroLinkText("execFunction@"+getMacroLocation(),"none",deferArgs,target)]
[H: execLink(link,1)]
```

```
<!-- execFunction(functionName,args) -->
[H: function = arg(0)]
[H: args = arg(1)]
[H: argList = ""]
[H, foreach(arg,args), code: {
   [H: argList = listAppend(argList,"arg"+roll.count)]
   [H: set("arg"+roll.count,arg)]
}]
[H: fnStr = strformat("%{function}(%{argList})")]
[H,C(500):"Delay one half second."]
[H: eval(fnStr)]
```

deferring was done in the first function. I forget why I put in the delay code.

**Comment by Merudo** [comment]
If the main argument for adding this feature is to handle `playStream`, maybe it would be simpler to add it a `target` parameter? Just a thought.

**Comment by aliasmask** [comment]
I've had other needs just as my example code shows. It's really a duplicate function of execLink but for functions.  playStream is just the latest example of, "Oh, I wish this existed."

**Comment by Merudo** [comment]
I tried to implement it but I can't get a reference to the parser when receiving a message through ClientMethodHandler.

I think this one requires some changes to the parser.

**Comment by Merudo** [comment]
PR #802 implements the requested change, although there might be a more elegant way to do it.

**Comment by Merudo** [comment]
Added documentation: https://lmwcs.com/rptools/wiki/execFunction

**Comment by Phergus** [comment]
@aliasmask  I'm leaving testing this for you.  :)

**Comment by Phergus** [comment]
Closing.
