### ISSUE TITLE
exposePCOnlyArea() not working as expected

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#792]
**Describe the bug**
The macro function `exposePCOnlyArea()`, corresponding hotkey (Ctrl-Shift-O) and token menu _Expose -> Only Currently Visible_ functions are not hiding previously exposed areas as expected if a sever is running.  Without a server running they work correctly.

Worked as expected in 1.4.0.5.  Broken as of 1.4.1.8.

**To Reproduce**
1. Start MapTool and load attached campaign file (v1.4.0.5)
2. With macro, menu or hotkey expose PC Only area.
3. Move Hero token outside of currently exposed area.
4. Repeat exposure step 2.  Note previously area is now hidden.
5. Start server with `Players can reveal vision`, `Auto Reveal On Movement`, and `Individual FoW` unchecked.
6. Expose PC only area.
7. Move token outside of exposed area.
8. Expose PC only area again. Note previous area is still exposed.

**Expected behavior**
Using any method of Exposing PC Only area should restore FoW to previously exposed areas and expose for all **PC** tokens with vision and light to see by.

**MapTool Info**
- Version: 1.4.1.8, 1.5.0+
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Rename without ".zip".
[ExposePCOnly1405.cmpgn.zip](https://github.com/RPTools/maptool/files/3720887/ExposePCOnly1405.cmpgn.zip)

**Comment by Merudo** [comment]
Is it only a problem when `Individual FoW` is unchecked?

**Comment by Merudo** [comment]
PR #917 fixes this.

**Comment by Phergus** [comment]
Testing reveals that it works now when a server isn't running but only partially when following steps 5 thru 8.  Correctly exposes on Server but on Player Client the previously exposed areas are still exposed.

**Comment by Merudo** [comment]
Interestingly, it exposes on player clients but only only when using token menu `Expose -> Only Currently Visible`, not while using the hotkey.

**Comment by Phergus** [comment]
Right.  The hotkey and macro both only do the server side correctly while the token menu option works on both ends.

**Comment by Merudo** [comment]
Also I noticed a related bug:  if you start a server with `Individual FoW` to On, `expose PC Only area` seems to work for both host and clients. However for new players joining the server, the area that should be hidden is still exposed.

**Comment by Phergus** [comment]
That would suggest that it is changing the "global" (i.e. campaign saved exposed areas) instead of the per token exposed area.

**Comment by Merudo** [comment]
PR #924 fixes clients not getting FoW reset, and new players connecting not getting proper FoW info from server.

**Comment by Phergus** [comment]
Tested with:
- [ ] Players Can Expose
- [ ] Expose on Move
- [X] Individual Views
- [X] Individual FoW
Server, 2 clients.  Tested `exposePCOnlyArea()`, Token menu Expose -> Only currently visible, and hotkey Ctrl-Shift-O.
**Working as expected.**

**Comment by Phergus** [comment]
Tested with:
- [ ] Players Can Expose
- [ ] Expose on Move
- [X] Individual Views
- [X] Individual FoW

Server, 3 clients(1 token each).  Tested `exposePCOnlyArea()`, Token menu Expose -> Only currently visible, and hotkey Ctrl-Shift-O.
**Working as expected.**

**Comment by Phergus** [comment]
Testing with
- [X] Players Can Expose
- [*] Expose on Move - with/without is the same
- [X] Individual Views
- [X] Individual FoW

Has revealed an issue with IV/IFoW when players expose.  If a player token with a light source moves and either exposes manually or automatically, the other player tokens within visual range of the light source do not get automatically updated with the newly exposed area.  Doing an expose manually, with Ctrl-Shift-O on server or with Ctrl-I by GM or player, exposes correctly.
This is not an effect of these changes as it happens in earlier 1.5 versions as well.

**Comment by Merudo** [comment]
I guess if a token with a light source moves, every token on the map should expose? Or is there a more efficient way to do it?

**Comment by Azhrei** [comment]
Just tokens within the sight distance of the light...?

**Comment by Merudo** [comment]
Each token can have a different sight distance, no?

**Comment by Phergus** [comment]
Right.  Each Sight definition can have a defined max distance or it can be limited by the map.  Then the map itself has a max sight distance.
If there isn't a way already, there should be a method (ZoneRenderer?) that for a given token gives the max distance they can see taking into account their sight setting.
In any case, whatever process takes place when you hit Ctrl-I for a token does work correctly so there's that.

**Comment by Merudo** [comment]
Interestingly, something similar happens with tokens with VBL.

Moving a token with VBL does not automatically update other player tokens with the newly exposed area. Rotating the token however, does update all tokens properly.

**Comment by JamzTheMan** [comment]
That sounds familiar, we had a similar bug a release or 3 back that did the same thing.

**Comment by Phergus** [comment]
Yeah.  In 1.5.4, changes made to token updates had caused this to happen but a fix was put in before release.

**Comment by Phergus** [comment]
Hold it a sec.  If a token with VBL moves (but doesn't have a light source and isn't a Player token) then only soft fog is supposed to updated.  e.g. a door with VBL opens but if what is behind it has never been exposed it stays that way until one or more tokens with vision/light expose the area through movement or manual exposure.  This is working correctly in the current code and in 1.5.7.

**Comment by Phergus** [comment]
Original issue has been addressed.  Closing.  Further changes will come under new issues.
