### ISSUE TITLE
Fill selection box option does not work on layers other than Token

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#796]
**Describe the bug**
When deselecting “Fill selection box” under “Preferences > Application > Performance”, this works only on the Token layer, but not on the layers Hidden, Object, and Background.

**To Reproduce**
1. Go to 'Preferences > Application > Performance'
2. Deselect 'Fill selection box'
3. Draw a selection box on any layer other than Token (Hidden, Object, or Background). The selection box is still filled.

**Expected behavior**
The selection box should not be filled on any layer, if “Fill selection box" is deselected, just as it is on the Token layer.

**MapTool Info**
- Version: 1.5.6
- Install: Upgrade from 1.5.4

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15

**Comment by xdy** [comment]
I just made a PR that should fix this, https://github.com/RPTools/maptool/pull/976

**Comment by Phergus** [comment]
Tested.  Preference setting affects selection on all layers now.
