### ISSUE TITLE
Splash Screen not displayed on macOS

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#799]
**Describe the bug**
I believe there should be a splash screen displayed while MapTool loads. It does not.

**To Reproduce**
1. Open MapTool.
2. While MapTool loads, there is no splash screen.

**Expected behavior**
While MapTool loads, there should be a splash screen.

**MapTool Info**
- Version: 1.5.6 [Edit: I mistakenly said 1.5.7 before]
- Install: Upgrade from 1.5.4

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15

**Comment by Phergus** [comment]
As 1.5.7 hasn't been released, I assume this means you are launching it from a local build?  What version JDK did you build against?

**Comment by Phergus** [comment]
So with 1.5.4 you were getting the splash screen?

**Comment by Azhrei** [comment]
Can you find and attach your log file?  It’ll be under `~/.maptool-rptools/` but I don’t recall the exact path.  That might have enough information to figure this out (my macOS install shows the splash screen, for example).

**Comment by mrkwnzl** [comment]
I think that might be it.
[maptool.log](https://github.com/RPTools/maptool/files/3763189/maptool.log)

**Comment by Phergus** [comment]
Nothing useful to solving this issue.

**Comment by mrkwnzl** [comment]
Anything else I could try?

**Comment by Phergus** [comment]
@Azhrei what version of Mac OS are you running where the spash screen works?

**Comment by Azhrei** [comment]
I'm on Mojave, which I think is 10.14.6.  The OP said he was on Catalina, 10.15...

I just checked a spare laptop where my wife has Catalina installed for testing, and I do not get a splash screen there when running 1.5.6.  I thought it might have been due to the pop up I got asking for permission to display _notifications_, but I told Catalina that was allowed and it didn't help.

I think @JamzTheMan has said there's a config file that turns on more logging, so I'll play with that and try again.  I just need to find the file. :)

**Comment by mrkwnzl** [comment]
I didn’t have a splash screen on 10.14.x either. I just recently upgraded to 10.15 (as it has been released just two weeks ago).

**Comment by Azhrei** [comment]
Okay, something weird is going on.  I installed 150 and the splash screen is there (on Catalina).  Now when I run 156, the splash screen works?!

I had changed the default notification style (in System Preferences) from "banners" to "alerts", so maybe that was it?  I changed it back and the splash still works — on both 150 and 156.  This is going to take some digging, I think. 😳

**Comment by mrkwnzl** [comment]
I played around with the notification settings. Turned on Alerts, then Banners, turned it off, then on again. I didn’t get a splash screen on any setting.

**Comment by Azhrei** [comment]
My next step is going to be to create a new throw-away username, try it out there, then preserve all changes under `~/Library` (where Java's Preferences and such are kept).  Then I can compare those to the ones for my current user...

**Comment by Azhrei** [comment]
I have not been able to recreate this issue again.  I've tried different user accounts on both Catalina and Mojave.  If we have anyone else report it, we can see about adding some additional logging in the code that handles the splash screen.  Maybe that will help narrow it down...?

**Comment by mrkwnzl** [comment]
For what it’s worth, I tried it with a new user account (with v. 1.5.13) and allowed all notifications and still didn’t get a splash screen.

**Comment by mrkwnzl** [comment]
Here’s something weird: I’ve had the splash screen once, yesterday. Doesn’t show up any more. I’m on 1.5.14, but yesterday wasn’t the first time I opened 1.5.14.

**Comment by Phergus** [comment]
@mrkwnzl  Are you still seeing this issue with later versions of MT?

**Comment by Azhrei** [comment]
I have a missing splash screen maybe once out of every 15-20 startups.  I have two external monitors for my laptop with the lid closed most of the time, but it doesn’t matter if MT is starting on the main monitor or secondary one.  When it disappears, the log has no additional data.

**Comment by mrkwnzl** [comment]
It appears only sporadically. With 1.8.5, I have a splash screen maybe once out of 5–8 times. I’m on macOS 11.2 (Intel).

**Comment by Phergus** [comment]
MT 1.8 is on Java 14 while 1.9 is Java 16 so we'll need to update this issue again once tested against 1.9.

**Comment by Phergus** [comment]
Okay Mac people who have run 1.9 or later.  Are you still missing the splash screen?

**Comment by cwisniew** [comment]
> Okay Mac people who have run 1.9 or later. Are you still missing the splash screen?

Unfortunately any test I do will not help much as I never experienced this issue with old versions on either Mac that I have.

**Comment by Azhrei** [comment]
I've been using 183 to play regularly and don't recall having seen it in a long time.  I'll keep an eye out for it and will file a new issue and mention this one if it comes back.  Closed.

(I'm guessing it has something to do with other components on the system.  I've been keeping adoptopenjdk up to date via `brew` and other than the VirtualBox hypervisor, I'm not using any other kernel extensions.  I also haven't had the SPOD in a long time, either. #262)
