### ISSUE TITLE
Incorrect tooltip for Show Chat Notification Background

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#800]
**Describe the bug**
The tooltip for `Show Chat Notification Background` (in Preferences) is 

```
Color of the text for typing notifications
```
which is the same tooltip as for `Typing Notification Color`.

The tooltip should instead be something like `The background flashes when a message is received`.

**Comment by Merudo** [comment]
PR #808 fixes the issue.

**Comment by Phergus** [comment]
Tooltip and label are now in agreement.  Peace is restored.
