### ISSUE TITLE
getStreamProps() returns malformed JSON

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#803]
**Describe the bug**
The JSON return by getStreamProps function puts quotes, with a leading space" around the time values and currentCount.

```
[{
  "uri": "http://erinmcnamee.com.hostbaby.com/files/01_Siuil_A_Ruin.mp3",
  "cycleCount": 0,
  "volume": 0.8,
  "startTime": " 0.0",
  "stopTime": " 230.28",
  "currentTime": " 0.0",
  "totalTime": " 230.28",
  "bufferTime": " 11.943241331315939",
  "currentCount": " 0",
  "status": "READY"
}]
```

**To Reproduce**
1. Play a sound clip with playStream()
2. Run getStreamProps() to display info

**Expected behavior**
Expect numeric values in the JSON to be numbers.

**MapTool Info**
- Version: 1.5.5+
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
Thank you for the report. I'll fix it.

**Comment by Merudo** [comment]
PR #807 fixes the issue.

**Comment by Phergus** [comment]
Tested.  Working as expected.
```
[{
  "uri": "http://erinmcnamee.com.hostbaby.com/files/13_1917_The_French_Prostitute.mp3",
  "cycleCount": 1,
  "volume": 0.8,
  "startTime": 0,
  "stopTime": 258.887,
  "currentTime": 0.5807483,
  "totalTime": 258.887,
  "bufferTime": 8.16639,
  "currentCount": 0,
  "status": "PLAYING"
}]
```
