### ISSUE TITLE
execLink / execFunction not running locally immediately

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#820]
**Describe the bug**
The functions `execLink` and `execFunction` don't run locally immediately even if `defer` is set to 0, when the target is "gm" or "all".

**To Reproduce**
1. Create a map "Grasslands" with a Dragon token on it.
2. Go on another map.
3. Run the following macro:
```
[h: execFunction("setCurrentMap", json.append("[]", "Grasslands"), 0, "all")]
[h: setState("Dead", 1, "Dragon")]
```

4. Look at the error: 

```Error executing "setState": the token name or id "Dragon" is unknown.```

The error is because the change of map is delayed for the current player, even though it shouldn't be.

**Expected behavior**
If `defer` is set to 0, the function/link are executed locally right away.

**MapTool Info**
- Version: 1.5.6, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Additionally, the options "not-self", "not-gm", and "not-gm-self" could be added as valid targets.

**Comment by Merudo** [comment]
PR #821 fixes this.

**Comment by Phergus** [comment]
Wiki pages were updated.

**Comment by Phergus** [comment]
Working as described.
