### ISSUE TITLE
Start time set with editStream is ignored by subsequent play calls.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#822]
**Describe the bug**
When preloading an audio stream with `playStream("music.mp3",0)` and then using `editStream("music.mp3", 1, 0.8, 10.0, 20.0)` to set a start and stop time, the start time is ignored by calls to `playStream("music.mp3")`.

**To Reproduce**
1. Execute the macro commands show below in order.  From chat window is best as some delay is needed between the commands to allow for buffering and whatnot.
2. Note that start/stop times have been set by `editStream()`
3. Note that stream plays from the beginning.

```
[r: playStream("https://ia800300.us.archive.org/29/items/Muzyka-CC/Aleksand_Sjakin_-_Flight_in_space.mp3", 0)]

<pre>[r: json.indent(getSoundProperties(),2)]</pre>

[r: editStream("https://ia800300.us.archive.org/29/items/Muzyka-CC/Aleksand_Sjakin_-_Flight_in_space.mp3", 1, 0.8, 30.0, 35.0)]

<pre>[r: json.indent(getSoundProperties(),2)]</pre>

[r: playStream("https://ia800300.us.archive.org/29/items/Muzyka-CC/Aleksand_Sjakin_-_Flight_in_space.mp3")]
```

**Expected behavior**
Expected playback to start the indicated start time.

**MapTool Info**
- Version: 1.5.6
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
More generally, should the settings of the stream be kept for following plays? So if I use

```playStream(uri, cycleCount, volume, start, stop)``` 

and then use 

```playStream(uri)```

the stream is played again with the same settings as before?

**Comment by Phergus** [comment]
I would think so.

If I `playStream(uri, cycleCount, volume, start, stop)` and it plays to completion (stopTime) then currentTime is set to the startTime in the stream properties so it is _ready to go_.

And if you `stopSound()` before it reaches the stop point, it also resets currentTime to the startTime.

**Comment by Merudo** [comment]
What about `cycleCount`? Should it uses the previously set `cycleCount`? Or should the stream be only played once if the parameter is omitted?

**Comment by Phergus** [comment]
I can see people wanting both behaviors but my instinct is to use the current value for the `cycleCount` if the parameter is omitted.  After all, what is the point of using `editStream `to set the values if you just have to repeat the values again when you call `playStream`?

**Comment by Phergus** [comment]
Changes tested.  Working as expected.
