### ISSUE TITLE
add a titleCase() macro function

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#829]
**Is your feature request related to a problem? Please describe.**
Its common for macro writers to want to be able to turn a descriptive skill name such as "Face Palm of Self Defence" into a key value that can be used in macros.
If you just use replace() it will end up as "FacePalmofSelfDefence" which is not as clear as "FacePalmOfSelfDefence" this function will resolve that. It is also useful for when you just want to turn some input into title case.

**Describe the solution you'd like**
New macro titleCase() that takes a string and returns a string...

**Describe alternatives you've considered**
Even though you could already do this with the following macro

_[h: titleCase = json.toList(json.evaluate(json.fromList(replace(string, "([^\\\p{IsAlphabetic}]*\\\p{IsAlphabetic}+[^\\\p{IsAlphabetic}]*)", ";{upper('\\$1',1)}"), ';')),'')]_

Its a tiny bit harder to remember than _[h: titleCase = titleCase(string)]_
It also has issues with any string that contains single quotes or semi colons.

**Comment by Azhrei** [comment]
This will fail when the locale is set to Turkish.

**Comment by cwisniew** [comment]
@Azhrei Please describe the failure you are seeing and how it needs to be corrected.

**Comment by Azhrei** [comment]
Turkish has four letter I’s, for example.  Changing the case on those letters can change the meaning of the word, thus automated case changing functions in the String class will throw exceptions when attempted.

This was reported to us many years ago when a Turkish user tried running MT and all references to upper() and lower() has to be replaced.  Fortunately, there weren’t that many.

It doesn’t affect internal-use-only fields, of course, but if a Turkish word were used as a token property, I believe it would currently fail because of how the case-insensitivity is currently done in the variable resolver Map.

And that’s all I know about that. 🙂

**Comment by Phergus** [comment]
With this string in the token notes and the Description property the code does this:
`Köpeğim nehirden geçiyor.`
```
[r: titleCase(Description)]
[r: titleCase(getNotes())]
```
Producing:
`Köpeğim Nehirden Geçiyor.`

But it doesn't have any of the accented chars at the beginning words.

**Comment by Phergus** [comment]
With two accented chars:
Source: `İstediğim şey sos`
Output: `İstediğim Şey Sos`

**Comment by Azhrei** [comment]
But you didn’t change the case of an I, J, or ... hm, there was at least one more character, but I don’t recall offhand.  I’m sure Google knows (via the Wikipedia page for Turkish).

**Comment by Phergus** [comment]
Source: `istediğim şey sos j J ı i`
Output: `Istediğim Şey Sos J J I I`

**Comment by Azhrei** [comment]
Hm, strange.  And your locale is set to Turkish?  Encoring doesn’t matter (can be UTF8).  I’ve had Turkish students confirm the students this in my Python classes and relate to how much of a pain it is.  I’m not sure why the JRE isn’t throwing an exception.  It used to. 🤷‍♂️

**Comment by Azhrei** [comment]
It looks like your dotted i and undotted i both converted to a capital I.  That’s wrong, IIRC.  But I’m not Turkish, so...

I’m still surprised there was no exception.  It could be that the current JRE simply ignores the exception now.

**Comment by Phergus** [comment]
As you can't start MapTool with the locale set to Turkish without multiple exceptions ending with it hung up, whether or not the `capitalize()` function is doing it "right" is kind of moot.

**Comment by Phergus** [comment]
See #843

**Comment by Phergus** [comment]
Function name changed to `capitalize()`.

**Comment by Phergus** [comment]
Basic wiki docs added.

**Comment by Phergus** [comment]
Tested.  Working as described.
