### ISSUE TITLE
Add File Sync Directory to getInfo("client") macro

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#848]
**Is your feature request related to a problem? Please describe.**
Most client preferences should return in getInfo("client") macro. Adding missing preference "File Sync Directory"
May be useful for > Add sounds to MapTool #615 as a way to sync sounds externally (google drive, dropbox, etc) and via macro adjust the path per client before playing a stream from a "local" file source.

**Describe the solution you'd like**
Add "file sync directory" to client info json

**Describe alternatives you've considered**
None, this IS the only solution. 😄 

**Additional context**
Sample usage:

```
[h: clientInfo = getInfo("client")]
[h: fileSyncPath = json.get(clientInfo, "file sync directory")]
[h: file = encode("file:///" + fileSyncPath + "/Map Tool Resources/! Audio !/Music/El Padrino - Godfather.mp3")]
[r: playStream(file)]
```

**Comment by Phergus** [comment]
Tested.  Working as described.

**Comment by Phergus** [comment]
Wiki page updated.

**Comment by Merudo** [comment]
Nice! I mentioned in the past implementing an "Audio Resources Directory" setting to specify local audio sounds, but it seems the "file sync directory" had this capability all along!

**Comment by JamzTheMan** [comment]
Yea, i had meant to add a function to access it for a while but never had a real reason to need it until now. :)
