### ISSUE TITLE
token tool 'forgets' layer between tool switch

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#85]
In short, when you switch between the token selection tool and another tool (e.g. VBL) then the token tool always snaps back to the TOKEN layer. (which is annoying if your working on e.g. the background layer).

**Comment by JamzTheMan** [comment]
Yea, this one bugs me too...

**Comment by JamzTheMan** [comment]
So I'm looking into this issue and believe I found another bug, if you use Map Explorer to jump to tokens, it only switches the Layer dialog if you select a Token on the Token layer OR if you go back to the Token layer. ie if you are on the hidden layer and select a token on the object layer, the layer switches but the dialog doesn't update.

**Comment by JamzTheMan** [comment]
This can be closed as of MapTool build 1.4.1.4.
