### ISSUE TITLE
Add log.trace to log macro group

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#850]
**Describe the solution you'd like**
Add log.trace(message) macro function to log group. Note: log.setLevel already accepts "TRACE" as a valid log level.

**Additional context**
After some framework development, I've found the need to leave in some detailed logging (like logging every UDF call with parms at the top of each UDF or within certain for each loops) but log file can become very busy finding other needed "debug" level logs. TRACE gives us one deeper level of DEBUG available during coding (and is a standard Log level within Java).

**Comment by Phergus** [comment]
Wiki page added:  http://www.lmwcs.com/rptools/wiki/log.trace

Closing.
