### ISSUE TITLE
Request: "mapname" parameter for getTokens & getTokenNames

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#867]
**Is your feature request related to a problem? Please describe.**
I wish to get a list of tokens for every map. Currently, this needs lots of `setCurrentMap`, which is slow and induces flickering.

**Describe the solution you'd like**
The functions `getTokens` and `getTokenNames` can take an optional `mapname` argument.

**Comment by Merudo** [comment]
PR #868 resolves this.

**Comment by Merudo** [comment]
I just had a realization: maybe we could add `mapName` as a field for the `conditions` json instead?

**Comment by Phergus** [comment]
That probably would be more in keeping with the rest of the function.  If someone wanted all tokens on a map, instead of this:
`getTokenNames(", ","{}", "somemap")`
they could do this:
`getTokenNames(", ",'{"mapName":"somemap"}')`

**Comment by Merudo** [comment]
I think so too. PR #869 implements this change.

**Comment by Merudo** [comment]
Documentation updated:

https://lmwcs.com/rptools/wiki/getTokens
https://lmwcs.com/rptools/wiki/getTokenNames

**Comment by Phergus** [comment]
Function tested and working as expected.
