### ISSUE TITLE
Option for json.path.read to return path instead of value

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#870]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to get the indexes of a json.array containing nested elements.

For example, if I have a json array containing Spells as json objects, I'd like to get the indexes of the spells with a specific value in a field instead of the spells themselves.

**Describe the solution you'd like**
A way to return the paths instead of the values when running a `json.path.read` statement. A way to do so would be to augment the `json.path.read`:

`json.path.read(json, path, asPath)`

where `asPath` can take the value 1 (to return path) or 0 (to return value).

**Additional context**
The Jayway library already contains this capability, by using

```Configuration.builder()
   Configuration conf = Configuration.builder().options(Option.AS_PATH_LIST).build();
```

**Comment by Merudo** [comment]
More generally, I think it would make sense to add a third parameter, "configuration", that is a json object containing the five Jayway configuration options:


ALWAYS_RETURN_LIST: Makes this implementation more compliant to the Goessner spec.
AS_PATH_LIST: Returns a list of path strings representing the path of the evaluation hits
DEFAULT_PATH_LEAF_TO_NULL: returns null for missing leaf.
REQUIRE_PROPERTIES: Configures JsonPath to require properties defined in path when an indefinite path is evaluated.
SUPPRESS_EXCEPTIONS: Suppress all exceptions when evaluating path.

**Comment by Merudo** [comment]
@cwisniew I know you are working on JSON stuff, what do you think of this?

**Comment by Merudo** [comment]
PR #871 implements this.

**Comment by Merudo** [comment]
PR #1112 implements this.

**Comment by Merudo** [comment]
Documentation updated: [json.path.read](https://lmwcs.com/rptools/wiki/json.path.read)

**Comment by Phergus** [comment]
Testing new parameters.

**Comment by Phergus** [comment]
Going to need an example of what REQUIRE_PROPERTIES is used for.  Didn't see it in the Jayway docs.

**Comment by JamzTheMan** [comment]
https://www.javadoc.io/doc/com.jayway.jsonpath/json-path/2.0.0/com/jayway/jsonpath/Option.html

Doc actually had an example, go figure lol (didn't expect it to be helpful)

**Comment by Phergus** [comment]
What?!  Useful examples in a javadoc?

**Comment by Phergus** [comment]
All config options tested.
