### ISSUE TITLE
Add metadata to getMacroProps function

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#872]
**Is your feature request related to a problem? Please describe.**
The ability to manage and edit macros externally from MapTool could benefit by adding additional metadata to the getMacroProps(<index>, "json") macro frunction

**Describe the solution you'd like**
Add a metadata object to the returned json that contains uuid, command checksum and properties checksum
```
"metadata":  { "uuid": String, "commandChecksum": String, "propsChecksum": String }
```

**Describe alternatives you've considered**
An external API is needed to generate a proper MD5 checksum which is slow and not ideal.

**Additional context**
commandChecksum is a MD5 checksum on the macro "command" only. With this, you can quickly tell if the macro has been edited or changed.
propsChecksum is a MD5 checksum for macro "properties" only, excluding the "command" and as such, can tell you if any of the properties have been changed.
The UUID is an easy way to identify macros even if the name has changed or if the name occurs multiple times.

**Comment by Phergus** [comment]
Tested. Working as described.

**Comment by Phergus** [comment]
Wiki page updated with new functionality.
