### ISSUE TITLE
REST.delete function should allow request body

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#874]
**Describe the bug**
REST specifications do allow for DELETE to send a request body (payload) and as such our macro function should allow for it as well. I've already encountered API's that require payloads on DELETE (like the GitHub API) and as such not able to perform DELETE's successfully with the current specifications.

**To Reproduce**
1. Try to send a REST.delete using headers and a payload

**Expected behavior**
REST.delete should follow the same macro function signature as REST.post (patch, & put)

**MapTool Info**
- Version: 1.5.0-1.5.6
- Install: Any

**Comment by Phergus** [comment]
[Wiki page](http://www.lmwcs.com/rptools/wiki/REST.delete) updated by Melek.

**Comment by Phergus** [comment]
Closing.
