### ISSUE TITLE
Keyboard shortcuts not working on macOS

### ISSUE THREAD

**Issue by mikehenry-se** [RPTools/maptool#883]
**Describe the bug**
A number of keyboard shortcuts are not working on macOS, for example:

**To Reproduce**
- Shift-Cmd-P does not switch between the Show As Player modes.
- Cmd-G does not show grid or switch grid off.
- etc.

**Expected behavior**
That all keyboard shortcuts should work as indicated in the menus.

**Screenshots**
n/a

**MapTool Info**
- Version: 1.5.6, 1.5.7-rc1
- Install: New

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.1 (but did not work with earlier versions either, i.e. 10.14

**Additional context**
n/a

**Comment by Phergus** [comment]
Can you check with MT 1.5.0?

Also does it work if you use Ctrl instead of Command?

**Comment by mikehenry-se** [comment]
Downloaded and ran MT 1.5.0. Same problem.
Tried it with Ctrl instead of Command. No difference.

**Comment by Phergus** [comment]
Thanks for checking.  We'll try and track it down quickly.

**Comment by mikehenry-se** [comment]
Menu-items tested for which keyboard shortcuts don't work on macOS:

- Fog-of-War (Cmd-W)
- FoW: Expose only at waypoints (Shift-Cmd-W)
- Show as Player (Shift-Cmd-P)
- Show Movement Distances (Cmd-D)
- Show Light Sources (Cmd-K)
- Show Grid (Cmd-G)
- Lock Player Movement (Shift-Cmd-L)

Not verified:

- Center Players on Current View (Cmd-F)
- Enforce Players to Current Map (Cmd-E)

Tested on MT 1.5.7-rc1

**Comment by Phergus** [comment]
Sigh.

Thanks for the additional info.

**Comment by mikehenry-se** [comment]
Thanks for your quick reply!

The most annoying of the verified ones missing are:

- Show Grid (Cmd-G)
- Show as Player (Shift-Cmd-P)

Others are nice to haves for me.

But I'll also say that the 1.5 versions of MapTool are awesome! I have been looking at the competition for a long time and think that they all pale in comparison, in particular when it comes to cross-platform support, scriptability and now Iso-maps/-tokens. You guys are doing great!

**Comment by Phergus** [comment]
Yeah.  Those are two I use all the time and it would definitely be annoying not having them.  :)

Appreciate the kind words!

**Comment by Phergus** [comment]
This appears to be a Java 9+ issue with Macs.  Older MT versions also show the issue with 9+ but when running under Java 8 they do work.

Still investigating potential solutions.

**Comment by cwisniew** [comment]
After investigation turns out what is happening is several menu items are being called twice when the accelerator key is used.

Searching for this behaviour finds following JDK bug
https://bugs.openjdk.java.net/browse/JDK-8208712

Which occurs in java 9+. Whenever a checkbox menu item is used with the apple menu look and feel (which puts the menu bar at top of the screen) using the accelerator key for that menu item will cause it to be called twice (oh joy!).

If you have a complicated enough scene you probably can observe this with fog of war accelerator key causing the map to flash.

now the next step is for us to work around this bug.

**Comment by Phergus** [comment]
Fix tested under Windows with no negative effects.

**Comment by mikehenry-se** [comment]
I'll see if I can pull and build this branch on my MBP to verify.

**Comment by mikehenry-se** [comment]
Hmm.. No go as I have Java 11 installed. I'll see if I can downgrade..

**Comment by Phergus** [comment]
Successful test reported by @JamzTheMan .  Closing.

**Comment by mikehenry-se** [comment]
MT 1.5.7-rc3 fixed all my issues. Thanks for the great work!

**Comment by Phergus** [comment]
That's good to hear.  Thanks for reporting it in the first place!
