### ISSUE TITLE
Previously exposed areas not shown after starting server.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#887]
**Describe the bug**
After loading a saved campaign with exposed map areas those areas are re-hidden when starting a server.  This occurs only when using Individual Views and Individual Fog of War.

**To Reproduce**
1. Load/create a map with vision enabled, fog of war and VBL.
2. Start server with Individual Views and Individual Fog of War enabled.
3. Place token with vision.  Also add light source to map if set to night.
4. Move token and expose some area of map.
5. Save campaign.
6. Stop Server.
7. Observe exposed areas are still exposed.
8. Restart Server and observe that previously exposed areas are now hidden.
9. Stop Server.
10. Select File -> New Campaign.
11. Reload campaign saved in step 5. Note exposed areas.
12. Start Server and observe that exposed areas are hidden again.

**Workaround**
Loading a campaign saved with exposed areas **_after_** the server is started does correctly show previously exposed areas.

**Expected behavior**
Expect previously exposed areas to still be exposed.

**MapTool Info**
- Version: 1.4.1.8, 1.5.+
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Simple example campaign with exposed areas. (Remove .zip extension.)
[ExposePersist1418b.cmpgn.zip](https://github.com/RPTools/maptool/files/3831693/ExposePersist1418b.cmpgn.zip)

**Comment by Merudo** [comment]
I worked on something similar (token ids getting reset) so I'll have a look at this.

**Comment by Phergus** [comment]
I suspect that when a campaign is loaded fresh, the tokens are scanned for exposed areas but when a server is started they aren't scanned.

**Comment by Merudo** [comment]
I haven't work on it yet but I suspect the same issue (scanned areas getting deleted) happens when a token is copy-pasted.

**Comment by Merudo** [comment]
PR #894 fixes this.

**Comment by Phergus** [comment]
Tested.  Working as expected.
