### ISSUE TITLE
Players can select tokens they own under hard fog of war.

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#890]
**Describe the bug**
On a MapTool server, connected players can select tokens owned by them and view and manipulate those tokens in the Selected panel.

This makes it possible to accidentally select NPCs/player owned tokens on explored portions of the map is not great, spoiling their presence to the players (such as friendly NPCs or Hirelings that might be further along on a map). 

If a server allows players to expose areas, they could also reveal unrevealed map area on tokens with vision. The GM is already putting trust on the players not to do that, but I don't think it is intended behavior.

**To Reproduce**
1. Create a map with fog of war and two Player-owned tokens. They can be 'Owned by All' or owned by the specific player. 
2. Start a server and connect a client to the server.
3. There are 3 ways to select an owned token:
3a. Click directly on the token under the hard fog.
3b. Click and drag a selection box over a token or token(s) under the hard fog.
3c. Click the 'Select all tokens on the map' button on the 'Selected' panel.

**Expected behavior**
Tokens under hard fog should not be selectable by players, regardless of ownership.

**Screenshots**

**MapTool Info**
- Version: 1.5.7rc1
- Install: Upgraded from 1.5.6

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment]
If I'm understanding you correctly, the issue is that Players can take action with the tokens they have ownership of even while under hard fog.  Is that correct?

If so, this behavior is intentional.  Why would player-owned tokens be "hidden" from them?

**Comment by JamzTheMan** [comment]
Correct. Let's say a token is Blind and has no vision but needs to cast a spell on himself? He can do so from the explorer or other means.

FoW is for vision based things only.

Maybe not assign ownership until needed. Doing so just based on sight seems predetermined. What if the Interaction goes badly?

**Comment by melek** [comment]
Understood; When I was writing up some documentation this seemed unintentional but thinking of Fog as separate from selection is helpful.

Sometimes I paste in NPCs the players have had control of in the past into a map (a jailbreak, for instance), and then if they players 'select all' in the panel they would see those tokens - but knowing this behavior I can remove ownership from them ahead of time.

Thanks for clarifying!
