### ISSUE TITLE
Feature Request:  Toggle display Text Labels on/off

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#891]
**Is your feature request related to a problem? Please describe.**
I like to use the text labels an my maps. They are quick and easy to handle und they are readable independently of the zoom level. Sadly, this is also the main issue. If you zoom out, this labels can cover whole parts of the map.

**Describe the solution you'd like**
I would like to see an option to hide/show text labels on the map. This could work like the options to hide/show grid or coordinates on the menu.

**Additional context**
Requested by Purzelkater on forums:
https://forums.rptools.net/viewtopic.php?f=26&t=28434

**Comment by Phergus** [comment]
Secondary request for macro function support as well.

**Comment by cwisniew** [comment]
Added following macro commands.

- **showTextLabels()** shows the map text labels.
- **hideTextLabels()** hides the map text labels.
- **getTextLabelStatus()** returns "show" or "hide".

**Comment by Azhrei** [comment]
Is it better to have show/hide functions or a single set function that takes a Boolean?  The latter seems better to me as it’s more flexible for scripting (no IF conditional needed to determine which function to call)...

**Comment by cwisniew** [comment]
I thought about it but in this case I felt this was clearer. Due to lack of real Boolean type you would really need the if anyway. At least this is clearer than showTextLabel(1 or 0)

**Comment by Phergus** [comment]
Menu option and macro functions working as described.

**Comment by Phergus** [comment]
Wiki updates for menu and new pages added:

- [getTextLabelStatus()](http://www.lmwcs.com/rptools/wiki/getTextLabelStatus)
- [hideTextLabels()](http://www.lmwcs.com/rptools/wiki/hideTextLabels)
- [showTextLabels()](http://www.lmwcs.com/rptools/wiki/showTextLabels)
