### ISSUE TITLE
Panels get permanently checked in 'Window' but aren't visible

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#892]
**Describe the bug**
When creating tabbed panels followed by using 'Restore Layout', panels can become inaccessible. Affected panels appear 'Checked' in the Window menu but aren't 'uncheckable' nor are open. 

MapTool must then be restarted to regain access to the stuck panels.

**To Reproduce**
1. Select 'Restore Layout' from the Window menu to get to a common starting place.
2. Open the 'Connections' panel from the Window menu. 
3. Open the 'Initiative' panel from the Window menu.
4. Drag the 'Initiative' panel onto the 'Connections' panel so as to add it as a tab to the pane.
5. Select 'Restore Layout' from the Window menu.
6. Open the 'Connections' panel from the Window menu.
7. Open the 'Window' menu. Observe that the 'Initiative' menu item is now checked, but is neither visible as a tab on the 'Connections' panel nor un-checkable.
8. If desired, continue tabbing non-default panels and restoring the layout to repeat the error until no non-default panels are accessible.
9. Restart MapTool to restore functionality. 

**Expected behavior**
Tabbing panels then restoring the layout should not risk the user losing access to panels.

**MapTool Info**
- Version: 1.5.7rc-1
- Install: Upgrade from 1.5.6

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10

**Additional context**
I think that the Restore Layout function is intended to both reset the default panels size and positions as well as reset how the other panels will show up when opened, but during this test I sometimes had panels popping up as 'floated' after closing them that way and restoring the layout.
<details>
<summary> 
From MapTool, paste info from menu Help -> Gather Debug Information...
</summary> 
```==== MapTool Information ====
MapTool Version: 1.5.7-rc.1
MapTool Home...: C:\Users\melek\.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 308 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\Users\melek\AppData\Local\MapTool\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
PATH...........: C:\Users\melek\AppData\Local\MapTool\app;C:\Users\melek\AppData\Local\MapTool
Number of Procs: 4

==== User Information ====
User Name: melek
User Home: C:\Users\melek
User Dir.: C:\Users\melek\AppData\Local\MapTool\app

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: VirtualBox Host-Only Ethernet Adapter #3
Interface Name: eth2
Address...: 192.168.95.1
Address...: fe80:0:0:0:dcd6:4118:81fe:c5c%eth2

Display Name..: Realtek PCIe GBE Family Controller
Interface Name: eth3
Address...: 192.168.0.114
Address...: fe80:0:0:0:c4df:cb97:74d7:1ddb%eth3

Display Name..: VirtualBox Host-Only Ethernet Adapter #4
Interface Name: eth6
Address...: 192.168.94.1
Address...: fe80:0:0:0:6528:383e:4882:3055%eth6

Host Address...: 192.168.94.1
Default Gateway: 192.168.0.1

==== Locale Information ====
Country.: United States
Language: 
Locale..: United States
Variant.: 

==== Encoding Information ====
Default Locale:   _US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 1920x1080(32)
Display 2: 1680x1050(32)

==== Internet Gateway Devices ====
Device Name.: CenturyLink UPnP v1.0
Model Name..: C3000Z
Manufacturer: ZyXEL
Model Number: C3000
Model Desc..: (null)
Firmware....: Custom/1.0 UPnP/1.0 Proc/Ver
External IP.: 97.120.112.236
```
</details>

**Comment by Merudo** [comment]
Last night during a game I managed to trigger this bug without selecting 'Restore Layout'. I had to restart the server to use the panel.

**Comment by Merudo** [comment]
Some of those issues may be bugs from the JIDE framework.

Do we have the JIDE Free License for Open Source Project? If so we could try upgrading the JIDE famework from 3.2.3 to 3.7.8 and see if that fixes it.

**Comment by Phergus** [comment]
Yes.  RPTools has a license for the JIDE libs.  I know that @Azhrei  had made an attempt to get the updated libs in the past without success but I don't know the details.

**Comment by Merudo** [comment]
The bug is also in 1.5.0, could be in 1.4.x too.

**Comment by Phergus** [comment]
This bug has been there since way back.  Probably 1.3 or earlier but definitely in 1.4.0.5.

Go ahead and reach out to them.  Pretty sure the license for RPTools is under Trevor Croft's name.

**Comment by Azhrei** [comment]
I think the email address they have is probably admin@rptools (you know the domain name).

**Comment by Merudo** [comment]
PR #1028 fixes the inaccessibility problem.

**Comment by Phergus** [comment]
Tested.  Working as expected.
