### ISSUE TITLE
Option to hide/minimize ribbon

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#897]
**Is your feature request related to a problem? Please describe.**
Most software with ribbons allow them to be minimized/hidden (Microsoft Office, Microsoft Edge,  Acrobat Reader, etc.

It would be nice for an option to hide/minimize the MapTool ribbon. 

**Describe the solution you'd like**
Either an option in the "Windows" menu to hide the ribbon, or a button to minimize it on/above the ribbon itself.

**Comment by Azhrei** [comment]
Wow, do we have ribbons?  That means we're modern, right?  No UI update needed — woohoo!

We don't actually have ribbons, though, right?  We just have toolbars.  And they're not even floating toolbars (which is a simple toggle option in JToolbar, IIRC).

I don't see a need to hide the toolbar.  People who want to go that minimalist will probably just run MT in fullscreen and get rid of _everything_.

**Comment by Merudo** [comment]
Isn't a ribbon just a toolbar at the top of a window?

I personally see a need to hide the toolbar. To be honest, I find it cluttered, and I rarely use the tools, especially as a player.

Btw, you can make the ribbon/toolbar floatable by dragging it from it's left edge.

**Comment by melek** [comment]
+1, it would be a welcome option. It could have a blue arrow button in the top left when minimized similar to the blue 'chat' notification in the lower left when the chat panel is closed, or be next to/appended to the modal window in the top right.

Fullscreen would be a sort of solution if you could have any panels at all open during fullscreen, even at least on a second monitor; my players almost always use the macro panels, and rarely or never use the toolbar during play. The only reason they do is to access the template tools.

IMO if it isn't trivial to do, it could wait until any planned UI rewrite that might affect the toolbar.

**Comment by Merudo** [comment]
Agree with you @melek. I noticed a lot of frameworks rely heavily on panels, so hiding the toolbar while keeping the panels seems quite useful.

The implementation should be pretty easy. We just have to add a JToggleButton to the toolbar and set it up. Main obstacle is finding a good blue arrow icon.

**Comment by Merudo** [comment]
I implemented the feature, here is how it would look like (with a placeholder icon):
![show](https://user-images.githubusercontent.com/7371085/68859002-f3579900-06ab-11ea-9231-427f8c168a68.png)
![hide](https://user-images.githubusercontent.com/7371085/68859012-f5b9f300-06ab-11ea-982b-648ba926fc32.png)

**Comment by Merudo** [comment]
PR #900 implements this! But, maybe we want another icon?

**Comment by Phergus** [comment]
> But, maybe we want another icon?

They are easily changed as your commit includes the pair.

**Comment by melek** [comment]
I don't see a PSD with the blue icons in the repository to use as a template, but I would think using the blue/white style matching most of the other UI buttons would look good. It could be grey when the toolbar is visible, and blue when it is hidden.

**Comment by JamzTheMan** [comment]
Yea, I just colorpick the blue/brown when needed. We really need new buttons...

**Comment by Phergus** [comment]
@melek What page should this be documented on?

**Comment by Phergus** [comment]
Tested.  Working as described.

**Comment by melek** [comment]
I've added information about the toggle in the User Interface article, both under the menu bar and the toolbar sections. It is an obvious enough feature that I don't think doing more than documenting it there is needed.

**Comment by Phergus** [comment]
Agreed.  Documentation complete.  Closing.
