### ISSUE TITLE
Give "mapName" parameter to "getOwned"

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#898]
**Is your feature request related to a problem? Please describe.**
I'd like to get the list of tokens owned on another map without switching to said map.

By adding a parameter "mapname" to getOwned/getOwnedNames, we could do that.

**Describe the solution you'd like**
Adding mapname as a parameter.

**Additional context**
It would make sense for getOwned() to return the list of tokens owned by the current player when no argument is given.

**Comment by Phergus** [comment]
> It would make sense for getOwned() to return the list of tokens owned by the current player when no argument is given.

Agreed though how often does a player think, "just how many tokens do I own on this map?"  Does it even need to be _Trusted_ for that case?

**Comment by Azhrei** [comment]
Good point.  I can’t think of a situation where a player would own a token but not be allowed to “know” about it.

There might be some kind of card game or board game where a player owns a card or a space on the board, yet they’re not allowed to know the details (maybe the cards are face down and playing a different card gives a peek at the face down cards? or in a wargame on a board where knowledge of the forces in a given place requires adjacent troops?).  I would think in those cases, if he token remains owned by the GM, though...

**Comment by Phergus** [comment]
Because there might be situations like that perhaps it is better for it to remain a trusted function and leave it to the macro coder / GM to decide what players can know.

**Comment by Phergus** [comment]
Tested functions `getOwned()` and `getOwnedNames()`.

- [ ] With map name
- [ ] Without map name
- [ ] No args

**Comment by Phergus** [comment]
What does, "made player parameter optional", mean?
