### ISSUE TITLE
Initiative functions addToInitiative, setInitiative, setInitiativeHold don't always work

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#912]
**Describe the bug**
The initiative functions addToInitiative, setInitiative, setInitiativeHold don't always work for clients.

**To Reproduce**
1. Create a Campaign macro with

```
[h: setInitiative(5)]
[h: setInitiative(10)]
```

2. Have a client run the macro on an owned token.
3. Every so often, the initiative will be set to 5 instead of 10.

**Expected behavior**
The latest initiative set should be what is kept.

**MapTool Info**
- Version: 1.5.7
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
Fixed by #913

**Comment by Phergus** [comment]
Seems to have fixed it.  Unable to reproduce with these changes.
