### ISSUE TITLE
RPTools_Map_Logo.png is being downloaded instead of part of package

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#920]
**Describe the bug**
In `OSXAdapter`, the image used for the macOS dock icon is being downloaded dynamically from RPTools.net and then cached for future use.  It's using an `http://` scheme that seems to fail in Eclipse (but works elsewhere), but we should be populating the JAR with this file instead and referencing it from there.

**To Reproduce**
1. Start MapTool within Eclipse on macOS
2. Note the exception from the PNG not being downloaded and the dock having the generic "Java" logo

**Expected behavior**
With the logo embedded, the image should always be available.

**MapTool Info**
- Version: latest `develop` branch (1.5.7)
- Install: None (Eclipse build)

**Desktop (please complete the following information):**
 - OS: macOS only
 - Version macOS Mojave 10.14.6 (although I believe not OS version dependent)

**Additional context**
No idea why this wasn't embedded into the JAR years ago. :(

Once cached, the name is referred to as `maptool-dock-icon.png` so we should probably just name it that in the JAR and refer to it the same way...

**Comment by xdy** [comment]
Just made a PR that might fix #920, I can't check as I don't have a mac...

**Comment by Phergus** [comment]
@Azhrei   Have you tested the fix?

**Comment by Azhrei** [comment]
Okay, tested from within Eclipse and it works...

And now I've built an uberJar and that works as well.

I'll close it.
