### ISSUE TITLE
Add Theme Support

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#921]
**Describe the solution you'd like**
As a short-term solution to the aging look of MapTool, provide some attractive themes for the TinyLaF look-and-feel manager that can be loaded at startup by MapTool.  This can already be done by manually placing a theme file in one of the locations that TinyLaF/MapTool already searches.  The goal here would be to make this more user-friendly.

- Install a selection of themes into the MapTool data directory upon install.  Most likely into `.maptool-rptools/themes/ui`.
- Provide a GUI selection in Preferences to choose from available themes and then place a copy of the selected theme in the correct location where it will be loaded after a restart.
- If possible, load newly selected theme and refresh UI immediately.

This archive has a list of PNG icons in the source in both `.csv` and `.ods` format.
[Icons in Source Corrected.zip](https://github.com/RPTools/maptool/files/3907194/Icons.in.Source.Corrected.zip)

**Comment by Phergus** [comment]
As MapTool already searches `.maptool-rptools/config` for `Default.theme` that would probably be a good place to put the selected theme.

See also [Themes for MapTool](https://github.com/RPTools/maptool/wiki/Themes-for-MapTool)

**Comment by rtakehara** [comment]
Made modern themes with green as secondary color, Icons on the way
[MT_Themes.zip](https://github.com/RPTools/maptool/files/3906512/MT_Themes.zip)

**Comment by Phergus** [comment]
@rtakehara  Very nice!

**Comment by rtakehara** [comment]
Made green flat transparent icons, hope they work well. Dark and 4k on the way, maybe today, certainly before the next 3 or 4 days... (got a campaign to prepare...)
[Icon_Modern.zip](https://github.com/RPTools/maptool/files/3906620/Icon_Modern.zip)

**Comment by Phergus** [comment]
Those look good.  I'm attaching a list of the icons used in the source.  There are 142 of them.  The zip has the lists in ODS and CSV format.
[IconsInSourceList.zip](https://github.com/RPTools/maptool/files/3907150/IconsInSourceList.zip)

**Comment by rtakehara** [comment]
Waw, thats a lot. Is there any way to see all of them? I have no idea how to navigate around here.

**Comment by Phergus** [comment]
Yeah.  Exactly which ones are the most important, well you probably covered that just be doing the most visible ones.

To see them here on GitHub, you can click on the Code tab near the top.  Then select the Develop branch from the dropdown on the left-top area.  After that you can navigate to: `src/main/resources/net/rptools/maptool/client/image/` by just clicking on folders until you get there.

Might be easier to just download the repo.  One the right side of the Code page is a Clone or Download button.  Click on that and you can select Download as a Zip file.   The repo is 19MB and includes everything so see the path above.

Alternatively you can grab the MapTool jar file out of an install and just unzip it somewhere.  There is a lot of stuff in there you don't care about.  The images will be under `net\rptools\maptool\client\image`.

**Comment by rtakehara** [comment]
Found it,  oh, wow! So the token selection border can be changed as easily as a button? That's a lot of customization, I assumed it was way less flexible, I will look into it.

Also, some icons are very self explanatory, but some are not, I will go hunting for them on the MT so I can understand the context, but the ones I don't find for any reason should I ask here?

**Comment by Azhrei** [comment]
You can ask here or on the Discord server.

I suppose at some point we should document which images are used where, either on our wiki or in a README file in the icon directory...

I don't think changing the token selection masks is a good idea, though.  I see that as sort of "core functionality" and if the colors were to change, it would be doubly hard to document how frameworks work or other basic operations.  But maybe I'm wrong; I'm willing to be convinced. 🙂

**Comment by Phergus** [comment]
Also be aware that there are 100+ images in those folders that aren't used anywhere.

**Comment by rtakehara** [comment]
@Azhrei yeah, a table with a description of what it is used and where would be useful.

About the selection, I was just surprised it was a normal image (or set of images). By core functionality you mean just the colors, right? because I can not change the colors, just the look and feel, for example, removing the black lines, leaving just a 3 pixel wide striped white and red would *probably* look better while  still being easy to read on a variety of backgrounds.  
Anyway, even if that's possible, its very low priority

@Phergus Oh! Phew... I was going to ask where that soccer ball was used, now I just need to ask why.

**Comment by Phergus** [comment]
Heh.  Some of the surplus images are from feature concepts that were never implemented and some are probably left over from very early versions of MT.  Safest to stick with just those items used in the code.  :)

**Comment by Azhrei** [comment]
I'll see if there's an easy way to scan all of the source looking for images... it shouldn't be too tough.  If I can create such a list, I'll post it here.

**Comment by rtakehara** [comment]
oh, I get it now, the list doc you made is for just the ones in use? that's way more helpful now hehe

**Comment by Phergus** [comment]
@Azhrei   Already done.  See the zip file above.   Did a quick search in the source for occurrences of ".png", pasted the output into Notepad++, handful of Search & Replace actions to put it into tab-delimited format and then paste into OpenOffice calc for sorting and final cleanup.  Took like 10 minutes.

**Comment by rtakehara** [comment]
@Phergus there are some icons in that table still missing, the tables panel have a new, delete, copy and edit tables, they are pencil.png, page_copy.png, delete.png and add.png

**Comment by Phergus** [comment]
Thanks @rtakehara .  I'll take a look at how those got missed and add them to the list.

**Comment by Phergus** [comment]
Ah.  Those - and a whole bunch more - are loaded via XML files that define dialogs.

**Comment by cwisniew** [comment]
PR #1222 contains the start (and probably easiest part) of the work for theme support.

At the moment it only allows for changing the TinyLAF theme and does not yet support changing icons images. I am marking this issue as up for grabs in case anyone wants to pick it up while I work on the Asset revamp. (I figure that even if no one picks it up before I get back to it, having some theme support is better than none).

### What remains to be done
Change theme to be represented by a directory under .maptool-rptools/themes/ui
The directory structure should contain
- theme.json, which contains:
	- theme name
    - mapping from icon names to icon file names
- tinylaf.theme
- icons
	- *all the icon files*

A new class <code>ThemeSupport</code> which will read the directory and json file above and provide methods to get the image for the different icons, and the file name for the tinylaf theme. The uses of the public static fields to retrieve images or image names for the UI need to be changed to use <code>ThemeSupport</code>.

**Comment by Phergus** [comment]
Added two of @rtakehara themes (RT_*) plus a variant (MT_*) and 4 variants (TL_*) of TinyL&F themes.
- MT_Flat_Green_Sans_13.theme
- RT_Default_Dark.theme
- RT_Flat_Default_Green.theme
- TL_Forest_Sans_11.theme
- TL_Forest_Sans_13.theme
- TL_Golden_Sans_11.theme
- TL_Golden_Sans_13.theme
_Sans_ denotes the use of the SansSerif font and the number indicates font size.  The default font on Windows is Tahoma which lacks complete character support.

These can be modified, deleted, added to or replaced but gives a few options for initial release.

**Comment by Phergus** [comment]
Issue #1248 opened for further work on themes.

Current implementation tested and working.

**Comment by Phergus** [comment]
Themes Menu added to Wiki page for [MapTool UI](www.lmwcs.com/rptools/wiki/MapTool_User_Interface).
