### ISSUE TITLE
Removing token VBL with setTokenVBL doesn't update client vision

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#932]
**Describe the bug**
If a token has a VBL and it gets removed with setTokenVBL(), the clients do not get updated (soft fog not changed).

**To Reproduce**
1. Create a token with VBL in a server with clients.
2. Remove the VBL with setTokenVBL().
3. Check the clients. They still see the VBL.

**Expected behavior**
Clients are properly updated.

**MapTool Info**
- Version: 1.5.7
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Tested.  Working as expected now.
