### ISSUE TITLE
Function setTokenImage doesn't update the token's native width and height.

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#952]
**Describe the bug**
setTokenImage doesn't update the token's native width and height.

**To Reproduce**
1. Follow the instructions on https://forums.rptools.net/viewtopic.php?f=21&t=28454

OR

1. Download the campaign and click on the Campaign macro: [setTokenImage.cmpgn.zip](https://github.com/RPTools/maptool/files/3903852/setTokenImage.cmpgn.zip)

2. Hover mouse over the image on the left, and notice the native width and height are not updated.

**Expected behavior**
Just like changing the token image through the token edit dialog menu, changing the token image through the setTokenImage macro should update the token native width and heigth. 

**MapTool Info**
- Version: 1.5.7
- Install: New,

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
PR #953 fixes this.

**Comment by Phergus** [comment]
Tested.  setTokenImage() properly updates native height/width.

**Comment by Phergus** [comment]
Wiki page updated.
