### ISSUE TITLE
MT crashes on long tooltip 

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#96]
When you open the token editor (double click on token), and go to the properties tab and then (accidentily) hover/move mouse over a property that has a really big value (e.g. long json array), MT shows a tooltip with the entire value. However if that value is REALLY big it effectively crashes and you have to terminate MT the hard way.

**Comment by Azhrei** [comment]
How would you like this solved?  If the value really is THAT big, should we truncate it at some point?  Should the tooltip panel be as large as possible with scrollbars?  (Can scrollbars even be interacted with in a tooltip?  I doubt it, since I don't think our tooltips will accept focus.)

**Comment by wolph42** [comment]
I think that any attempt to show it whole will cause the same crash as its simply too big. So to be save I would opt for truncating it after a certain length.

**Comment by Azhrei** [comment]
MT is not displaying the tool tip, the JIDE framework is.  I've overridden the code that determines what should be displayed for the tool tip on the Properties panel and limited the text to 100 characters plus an ellipsis.  I tested it with multiple properties with lengths of at least 200 characters for the values and it looks to be working.

**Comment by wolph42** [comment]
Awesome! Can't wait to test. Thnx
