### ISSUE TITLE
GM-Mode FoW autoexpose not working correctly

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#962]
**Describe the bug**
The preferences setting *Auto-expose fog on token movement (GM only)* stopped working correctly.  This setting allows for auto-expose without a server running.  With setting enabled, moving tokens are no longer visibly exposing the FoW.  It appears that the exposed FoW may be going on the token and not to the global exposed area.

**To Reproduce**
1. Create a map with FoW enabled and Vision set to Night.  Do not start a server.
2. Make sure the setting is enabled in Preferences -> Application.
3. Drop a PC token with Normal vision enabled and a light source assigned.
4. Drop a PC token with Darkvision enabled and no light sources.
5. Move tokens and observe that FoW is not exposed.

**Expected behavior**
With that preference setting enabled the Fog should be exposed.  This worked in 1.5.4 and was broken with1.5.5.  The exposed areas should be part of the global exposed fog.

**MapTool Info**
- Version: 1.5.5+
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
What is the setting "Auto-expose fog on token movement (GM only)" supposed to do, exactly? 

Is it only for personal servers?

**Comment by Phergus** [comment]
That preference setting has nothing to do with owned/unowned.  Not sure why the wiki has that.  Probably got confused with the new Server option.

Apparently it is an option that was put in to help with testing map/vbl with only the personal server running.  I've never had a clue what it was for before today.

Neither the text nor tooltip are particularly helpful so it definitely needs an update to the tooltip.

**Comment by Merudo** [comment]
Is "Auto-expose fog on token movement (GM only)" suppose to have an effect on personal servers only? If so, maybe it should be renamed to 

"Auto-expose fog on token movement (personal server only)"

**Comment by Phergus** [comment]
I've never checked the code to verify it but I believe that is true.

**Comment by Merudo** [comment]
Based on this discussion I believe the intended effect for GMs is:

- Personal server: tokens reveal if "Auto-expose fog on token movement (GM only)" setting is checked.
- Server running:  the setting above is ignored. Owned tokens reveal if "Auto Reveal on Movement" is on, and unowned tokens reveal if "GM reveal vision On Movement for Unowned Tokens" is on.

**Comment by JamzTheMan** [comment]
It use to expose FoW as needed, pretty useful to test VBL. I use to be able to reveal for an owned PC token (I would use a PC token to test) and it no longer works after fixing other FoW issue...

I believe it's exposing FoW for the token vs global FoW

**Comment by Phergus** [comment]
I'm with you so far.   :)

Note that any fix for this will be pushed to 1.5.9.

**Comment by melek** [comment]
The Wiki error is mine. When I tested the behavior, it wouldn't auto-expose unless I set token ownership - apparently I documented a bug as intended behavior... oops!

Have removed the word 'owned' on the Wiki so it is correct once this issue is resolved, and will update it further to reflect any updated tooltip. I'm not sure what a 'Personal Server' is, but I'm using Merudo's comment as a guideline. 

> - Auto-expose fog on token movement (GM Only)
> Will automatically expose Fog of War after moving a Token if ✓checked. This setting is intended to help test Fog of War and VBL when not hosting a game. When running a server, this setting is ignored in favor of the settings in the 'Start Server' dialog.

Will update further with feedback.

**Comment by Phergus** [comment]
@melek   Technically MapTool is always running a server.  We refer to the server you have when you just start up MapTool and are working on your campaign, building maps, and so on as a Personal Server.  Various internal aspects of MT rely on a server to work.

**Comment by Merudo** [comment]
The same issue happens with facing - changing the facing while using a cone light source doesn't update the FoW correctly.

**Comment by Merudo** [comment]
PR #965 fixes this.

**Comment by Phergus** [comment]
Tested.  With setting enabled and no server running, Tokens with vision that are moved now expose FoW.
