### ISSUE TITLE
Property Arrangement Problem

### ISSUE THREAD

**Issue by calddff5193** [RPTools/maptool#985]
![arrangement](https://user-images.githubusercontent.com/58839908/70773896-0a2d0080-1dbc-11ea-82b9-908e6685e028.png)

I really wonder why this does happens. Every time I write the property a bit longer it comes like that. Bunch of useless spaces with irregular sizes. Any solution?

**Comment by Merudo** [comment]
It's a Java high DPI issue, related to this: https://github.com/RPTools/maptool/issues/568

Here is how to fix it: https://www.rptools.net/2019/03/windows-10-dpi-scaling-strikes-again/

**Comment by calddff5193** [comment]
Oh, thanks! Now it works well.
Just one more thing - is there any way to change the system font size? It seems that the letters got way much bigger than it did in the previous versions, but there's no in-game font size change method except for the chatting font.

**Comment by Phergus** [comment]
The font sizes specified in MapTool haven't changed.  The increase is most likely from having scaling enabled in Windows.

**Comment by calddff5193** [comment]
Is that so? I'm running both 1.3.b91 and 1.5.8, but their font sizes were significantly different.
By the way, if that's the case then how may I fix the scaling?

**Comment by Phergus** [comment]
MT 1.5.7 and 1.3.b91 on a system with 125% scaling.
![Screenshot 2019-12-13 10 06 00](https://user-images.githubusercontent.com/34379254/70818273-827dcc80-1d90-11ea-9d05-4c7d74f4965e.png)

There will be slight rendering differences as 1.5+ is compiled for Java 10+ which has more support for HiDPI than the Java version used 1.3.b91.

To turn off scaling for an application see the link in @Merudo 's post above.

**Comment by calddff5193** [comment]
Exactly which post should I look at? It seems that Merudo has written a lot of posts here...

**Comment by Phergus** [comment]
He posted exactly once in this thread.  Look up.
