### ISSUE TITLE
"Square" symbol showing up when displaying rolls in a frame/dialog

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#989]
**Describe the bug**
When a roll is to be displayed in a frame/dialog, two extra &#9633;  are displayed in front of the roll. This happens both for inline and tooltip rolls.

**To Reproduce**
1. Run the macro:
```[frame("rolls"):{  [1d20] <br> [t: 1d20] }]```
2. Notice the extra squares.

**Expected behavior**
No squares.

**MapTool Info**
- Version: 1.5.0 to 1.5.8
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Note for the example above the squares show up in the mouse-over tooltip.  If the `expanded` roll option is used they show up in the frame text.

```[frame("rolls"):{ [e:1d20] <br> [t: 1d20] }]```

![Screenshot 2019-12-14 06 50 20](https://user-images.githubusercontent.com/34379254/70849619-3db06f00-1e3e-11ea-8049-031c2f15a958.png)

The `s` and `g` roll options add 's' and 'g' in between the squares.

This also happened in 1.4.0.5.

**Comment by Merudo** [comment]
I don't think the `s` and `g` options are supposed to work for frames and dialogs.

**Comment by Merudo** [comment]
PR #990 fixes this.

**Comment by Phergus** [comment]
Tested both dialogs and frames with `e` and `t` roll options.  Output is correct and no longer shows unprintable character symbol.
