### ISSUE TITLE
setName: clients get error message when GM uses duplicate name

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#993]
**Describe the bug**
When the GM changes a token's name to a duplicate, all players get an error message

> Only the GM can create multiple tokens with the same name

**To Reproduce**
1. Have a GM and player on the same server.
2. Create a token named "Dragon"
3. Have the GM type `[setName("Dragon", "Dragon")]`
4. The players get an error message.

**Expected behavior**
No error message if GM launched the command.

**MapTool Info**
- Version: 1.5.8
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by JamzTheMan** [comment]
Yeah, we were seeing this error message last week or three on 1.5.7 as well... Kept forgetting about it.

**Comment by Merudo** [comment]
PR #993 fixes this issue.

**Comment by Phergus** [comment]
Tested.  A GM using `setName()` to give a token a duplicate name no longer produces a warning and NPE on the player clients.

**Comment by Phergus** [comment]
Sentry issue: [MAPTOOL-2MK](https://sentry.io/organizations/rptools/issues/1330965158/?referrer=github_integration)

**Comment by Merudo** [comment]
> Sentry issue: [MAPTOOL-2MK](https://sentry.io/organizations/rptools/issues/1330965158/?referrer=github_integration)

I don't have the permission to look at it. Is there something wrong with the fix?

**Comment by Phergus** [comment]
It's probably limited to organization members.  I'll check.

**Comment by Phergus** [comment]
Can you follow the Sentry links in #945?

**Comment by Merudo** [comment]
Nope

**Comment by Merudo** [comment]
Thanks for sending me the Sentry report.

I suggest we replace the `IllegalArgumentException` by a `ParserException`, and deal with it the usual way.

**Comment by Phergus** [comment]
Seems like a good idea.

**Comment by Phergus** [comment]
Note that with your fix, it no longer generates the error.  That report was from pre-fix.

**Comment by Merudo** [comment]
It's going to generate a similar error eventually.

**Comment by Merudo** [comment]
PR #995 changes the `IllegalArgumentException` to the usual `ParserException`.

**Comment by Phergus** [comment]
Tested new code.  Attempting to give a token a duplicate name with `setToken()` now produces a more user-friendly error message.
