### ISSUE TITLE
Attempts to drop a duplicate token by player client only produces message on server

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#998]
**Describe the bug**
If a player client attempts to drop a token on a map that already has a token with that name it is rejected but only the server gets an error message.  The player client sees nothing.

**To Reproduce**
1. Start a server with default map set Visible to Players.
2. Place a "Hero" token on the map.
3. Start second MT instance and connect to server as Player.
4. Drag "Hero" token from library to map on Player client.  Token does not appear on map.
5. Server gets error message.
  > Failed to paste token(s) with duplicate name(s): [Hero]

**Expected behavior**
Player should be notified as to token drop failed.

**MapTool Info**
- Version: 1.5.8
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
I'll do this one.

I'll also localize the error message.

**Comment by Merudo** [comment]
PR #1004 fixes the issue.

**Comment by Phergus** [comment]
Tested.  Player client now gets notice of faux pas.
